### ISSUE TITLE
Show property in column nested object

### ISSUE THREAD

**Issue by leonanluppi** [DevExpress/devextreme-reactive#1009]
Hi,

How can I get specific property in object.

I have this object:

`[{
  id: 1,
  customer: {
    name: 'Foo', lastname: 'baz'
  }
}]`

I want to get customer.name and show it on column

**Comment by gsobolev** [comment]
Hi @leonanluppi,
 
Please check out [this guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-accessors/).
