### ISSUE TITLE
How to style PagingPanel's Pagination?

### ISSUE THREAD

**Issue by gerhat** [DevExpress/devextreme-reactive#1021]
I need to style the active page button but cannot find a way around it.

I was able to theme the pager applying the technique in **Appearance Customization** documentation in https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/, but I cannot get access to activeButton styling.

Am I missing something or it is just not possible?

Here is an example of what I am trying to achieve:
https://codesandbox.io/s/py7q96p2o7

Thanks a lot.

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, the `PagingPanel` plugin doesn't support such customization functionality. As a workaround, I can suggest you find a dom element using the `currentPage` property, then add a custom style to it. This [sample](https://codesandbox.io/s/3rn3jj7p21) shows how to do it. Once again, it isn't a documented way, just a temporary solution.

**Comment by gerhat** [comment]
Hi @SergeyAlexeev thanks a lot for the solution

**Comment by jimmycarlinco** [comment]
In your first codesandbox you could also target it like this:

`    '& button[class*="activeButton"]': {
        backgroundColor: "pink"
    },
`

**Comment by gerhat** [comment]
@jimmycarlinco this was my first thought but it didn't work in production build due to jss changing the names of the classes

**Comment by jimmycarlinco** [comment]
Just a little note on @SergeyAlexeev solution: shouldn't use index to find the dom element. It will not work for when there are more pages and buttons are shown for only some of them in the pager.
This is what I did instead:
```
const applyCustomButtonColor = (buttonIndex = 0) => {
  const buttons = document.querySelectorAll('.custom-pager button');
  Array.prototype.slice.call(buttons, 1, buttons.length - 1).forEach((button) => {
    if (button.textContent - 1 === buttonIndex) {
      button.style.fontWeight = 700; // eslint-disable-line no-param-reassign
      button.style.color = '#b2e55a'; // eslint-disable-line no-param-reassign
    } else {
      button.style = null; // eslint-disable-line no-param-reassign
    }
  });
};
```
