### ISSUE TITLE
How to add Group Summary Row

### ISSUE THREAD

**Issue by volkanakbas** [DevExpress/devextreme-reactive#1024]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I'd like to be able to add a summary row when column is grouped. Like the example in this picture.
<img width="961" alt="screen shot 2018-05-01 at 5 24 30 pm" src="https://user-images.githubusercontent.com/4326088/39496597-be667fe2-4d64-11e8-8a45-2ff7ad0558be.png">

**Comment by volkanakbas** [comment]
Hi Sergey,

Thank you for the sample, it helped me a lot. The sample was missing the last summary row, so if you add the below code, it'll add the last group summary row.

`acc.push(row); 
if (row.type === 'data' && tableBodyRows.length === acc.length){
      acc.push({
        type: 'summary',
        key: 'summary_${acc.length}',
      });
    }`

For other who wants to add data summary row for a total row, you can think of it as a footer row, here is an example which Devexpress devs created https://codesandbox.io/s/23pmkkq70p 
I'm trying to put this footer row like a sticky row for VirtualTable but have not been successful. If anyone knows how to add a Total row that sticks to the bottom of the table, I'd appreciate for any help.

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information. You can use the "footer" template to implement a "sticky" summary row.

I've created a [sample](https://codesandbox.io/s/61pr1yxq9z) that demonstrates this approach in action.

**Comment by volkanakbas** [comment]
Sergey, 
Thank you for your help. I was able to put together what I need from all the sample you created. I was wondering if you guys ever planning on creating "Aggregates" as a feature of the Grid. It is a must have in any finance application.

**Comment by SergeyAlexeev** [comment]
It's already in our backlog.

**Comment by SergeyAlexeev** [comment]
I've marked this issue as an enhancement. We'll update it as soon as we have any news.

**Comment by Verikon** [comment]
@SergeyAlexeev , rockstar support - thank you! It would be good to see more formal and in depth documentation on plugin development for react-grid.
