### ISSUE TITLE
Customize selected rows in TypeScript

### ISSUE THREAD

**Issue by GuyWithCookies** [DevExpress/devextreme-reactive#1025]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I read several Issues as well as the documentation of Appearance Customization as stated (here)[https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/).

However it is still not clear for me how to adapt the examples to the TableSelection.
To be more specific, I want to change the backgroundColor of a selected row.
But when i try to pass a customized rowTemplate to the TableSelection, the TypeScript-Compiler complains, that the `rowComponent` Property does not exist for TableSelection.

Relevant Code:
```
    ...
    const selectionRowTemplate = ({children}) => {
        <tr style={{"backgroundColor": "blue"}}>
            {children}
        </tr>
    };
    ...
    <TableSelection rowComponent={selectionRowTemplate} />
    ...
```

Could you please explain how to style selected rows or provide a small example?
Thank you in advance!

**Comment by kvet** [comment]
Hi,
 
Customization of the row with enabled selection is a bit different. Please see the related issue: #437
