### ISSUE TITLE
Separate action column

### ISSUE THREAD

**Issue by Peretz30** [DevExpress/devextreme-reactive#1029]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
2 action buttons ( 'edit', 'delete') in one column.

### Expected Behaviour
How can I separate whem? I want edit button to be thirst column and delete button in last column.

**Comment by kvet** [comment]
Hi,

It is possible by implementing the custom plugin. I've prepared a simple example: https://codesandbox.io/s/y30kr4x10j. Find more implementation details in the original TableEditColumn plugin's source code: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-edit-column.jsx

**Comment by Peretz30** [comment]
Thank you, @kvet ! It's working, but there is so much code to make such "simple" thing. I hope in the future your library would be more "friendly".

**Comment by laurakat** [comment]
@kvet Is there a example that works with 1.9.0? I've added a slimmed down version that just adds an action column with a button, but the header text and button aren't appearing in the dom. The original example also stops displaying anything (just an empty column) when I update to devexpress to 1.9.0.

https://codesandbox.io/s/kw8rj5rn85

**Comment by MaximKudriavtsev** [comment]
Hi @laurakat,
 
I have updated the [example](https://codesandbox.io/s/885qovnq7l).
