### ISSUE TITLE
Column Visibility Tooltip Doesn't Disappear on click away

### ISSUE THREAD

**Issue by klassicd** [DevExpress/devextreme-reactive#1032]
## Column Visibility Tooltip Doesn't Disappear on click away

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-visibility/

Hover over the column visibility button until the tooltip appears.  Click on the button.  Then click away to close the visibility settings dialog.  The tooltip reappears and stays until you click on the page again. 

### Expected Behaviour

 Tooltip should close after user clicks into dialog. 

### Steps to Reproduce (for Bugs)
See above.

### Your Environment
Chrome

devextreme-reactive: 1.1.2
react: 16.3
browser: Chrome
material-ui: 1.0.0-beta.43

**Comment by kvet** [comment]
Hi,
 
This is a way how focus works in Material UI. When you close the Column Chooser, the toggle button gains focus. So, the tooltip is shown.
 
We can disable tooltip showing on focus events, but we don't think that this is a right choice.

As a workaround, you can customize the toggle button by using the toggleButtonComponent property in the ColumnChooser plugin.

**Comment by klassicd** [comment]
Ok, thanks!
