### ISSUE TITLE
selectByRowDoubleClick

### ISSUE THREAD

**Issue by datadidit** [DevExpress/devextreme-reactive#1049]
TableSelectionProps contains a selectByRowClick. React supports `onDoubleClick` might be a nice feature to add `selectByRowDoubleClick` to the TableSelectionProps

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for the suggestion. To be honest, we don't have many requests related to this feature. Well, currently you can implement it on your side by overriding the `tableRow` template. This [sample](https://stackblitz.com/edit/react-czmx6p?file=index.js) demonstrates how to do it. You can find more information about the `Template` component in the [documentation](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/rendering-markup/).
