### ISSUE TITLE
VirtualTable + TableTableColumnResizing bug

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [DevExpress/devextreme-reactive#1051]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
```
<VirtualTable
     columnExtensions={tableColumnExtensions}
     cellComponent={Cell}
/>
<TableColumnResizing defaultColumnWidths={defaultColumnWidths} />
```
This causes only the first 20 or so rows to be rendered. It should be rendering 90+ rows in my use case.

### Your Environment
devextreme-reactive: ^1.2.0-beta.3
react: ^16.3.2
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: ^1.0.0-beta.43

**Comment by kvet** [comment]
Hi,

Here is an example of the VirtualTable and TableColumnResizing plugins that works well: https://codesandbox.io/s/4rjlm85k09. I don't understand your issue completely. Can you describe it in greater detail or provide a sample with the problem?

**Comment by NisanthanNanthakumar** [comment]
Hi kvet,

I looked through the codesandbox code and tested it with a lot more rows and it worked. However, when I tried it locally, it stopped rendering after 13 rows. I think it may have something to do `dev` vs `build`.

The following link is a screen recording of my dev render fail. http://recordit.co/IvNTxytMoG

**Comment by kvet** [comment]
I see the problem, however, I can't reproduce it on my side. So, I can't reproduce it without a demo. Can you share an example containing minimal steps to reproduce the issue?

**Comment by NisanthanNanthakumar** [comment]
Hi kvet,

I did a fresh reinstall of the node_modules and it started to work. And now I can't reproduce the issue either. Thanks for taking the time to look into the matter.
