### ISSUE TITLE
How to add a button on the Toolbar next to ColumnChoser

### ISSUE THREAD

**Issue by volkanakbas** [DevExpress/devextreme-reactive#1059]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### Expected Behaviour

I would like to add a button next to columnchoser button. this is what I tried but the end result is not what I'd like.  The button and the columnchoser button goes under the grouping label.
![screen shot 2018-05-10 at 12 05 48 pm](https://user-images.githubusercontent.com/4326088/39882936-fa44aa9c-544a-11e8-9d5e-e0f454c4e7f4.png)

I would like it to be 
![screen shot 2018-05-10 at 12 10 38 pm](https://user-images.githubusercontent.com/4326088/39883001-370c88f0-544b-11e8-9a55-9b8e0353d41b.png)

```
toolbarTemplate = params => {
    return (
      <div>
        {params.children}
        <Button>Test</Button>
      </div>
    );
  };

<Toolbar rootComponent={this.toolbarTemplate} /> 

```
Thank you.

**Comment by kvet** [comment]
Hi,

Here is the simplest working demo with a custom toolbar item: https://codesandbox.io/s/v438npq8l. It uses the Template and TemplatePlaceholder primitives from the `@devexpress/dx-react-core` package.

**Comment by volkanakbas** [comment]
@franklixuefei and @kvet, thanks to both of you. I was able to put together what I needed.
