### ISSUE TITLE
ColumnChooser causes page to stretch out vertically on page refresh

### ISSUE THREAD

**Issue by jimmycarlinco** [DevExpress/devextreme-reactive#1060]
Encountering a weird issue where ColumnChooser is causing the page to stretch out vertically causing a scrollbar and enabling user to scroll down the page. This happens only right after when I refresh the page the grid is on. If i open the column chooser and close it, the empty space below the grid disappears. I have no idea how to debug this further. Can you please help? I don't want to have to disable ColumbChooser because of this bug.

Thanks a lot if you can take a look.

**Comment by jimmycarlinco** [comment]
OK, I found this popper element that is positioned way off:
https://imgur.com/a/RRfUgbC

Can somebody tell me why is this happening? :)

**Comment by franklixuefei** [comment]
@jimmycarlinco I encountered the same problem. This issue originates from the [Material UI](https://github.com/mui-org/material-ui) lib that Reactive Grid depends on. Please take a look at [this post](https://github.com/mui-org/material-ui/issues/10909).

**Comment by jimmycarlinco** [comment]
That would mean making body overflow-y: hidden which is definitely gonna break things for me. Uhh.. Poppers also acting wierd in other places. Very annoying. If anyone has any other suggestions please.
