### ISSUE TITLE
How to implement material-ui@next tabs inside TableRowDetail 

### ISSUE THREAD

**Issue by jimmycarlinco** [DevExpress/devextreme-reactive#1061]
I'm kinda new to react so I hope this isn't just a really stupid question: how would you go about implementing material-ui tabs inside TableRowDetail: https://material-ui-next.com/demos/tabs/#basic-tabs

Right now I am struggling to get it to work because the TableRowDetail component is not re-rendered when the main component's state changes. Any idea? :)

**Comment by kvet** [comment]
Hi,

There is the `contentConponent` property in the TableRowDetail component that allows defining any custom component. Here is an example: https://codesandbox.io/s/9v392171r

**Comment by jimmycarlinco** [comment]
Thanks, almost there. One last thing: what would be the recommended way to access/connect redux store in SimleTabs component?

**Comment by jimmycarlinco** [comment]
I guess just another connect will suffice 👍 

Thanks a lot :) Closing
