### ISSUE TITLE
Are there flow-typed type definitions for this library?

### ISSUE THREAD

**Issue by marcusegues** [DevExpress/devextreme-reactive#1072]
Not sure what to use when running the command `flow-typed install ***@version`.

**Comment by kvet** [comment]
Hi,

We don't provide flow-typed type definitions. This is the first request for this feature. We will consider support for the future releases.

**Comment by churkin** [comment]
Hi all,
The Flow type checker is not so popular as TypeScript. For this reason we have decided not to implement it in the near future.
