### ISSUE TITLE
Material UI Next v1.0.0-rc.0 breaks this library correct?

### ISSUE THREAD

**Issue by marcusegues** [DevExpress/devextreme-reactive#1073]
https://github.com/mui-org/material-ui/releases

v1.0.0-rc.0 has breaking changes, it breaks devextreme-reactive, right?

**Comment by SergeyAlexeev** [comment]
Hi,

Yes, you are right. We are going to update our code base according to this [PR](https://github.com/mui-org/material-ui/pull/11310) and support the latest Material UI version as soon as possible.

**Comment by zcuric** [comment]
@SergeyAlexeev Hi, any plans on merging this soon? 
https://github.com/DevExpress/devextreme-reactive/pull/1079

**Comment by SergeyAlexeev** [comment]
@zcuric merged)

**Comment by kvet** [comment]
Hi,
 
This is released in 1.3.0-beta.1.
