### ISSUE TITLE
Typescript and upgrade from 1.0.0 to 1.2.0

### ISSUE THREAD

**Issue by a-robin** [DevExpress/devextreme-reactive#1074]
Hello guys,

I am using your component since 3 months and I am quite happy with it in general.
The only issues I have had though id to upgrade its version in general.

I am trying to bump the version from 1.0.0 to 1.2.0 but just using yarn upgrade and TS is giving me headhaches...

These are the versions I have in my package.json:

"@devexpress/dx-react-core": "1.2.0",
  "@devexpress/dx-react-grid": "1.2.0",
  "@devexpress/dx-react-grid-bootstrap3": "1.2.0",

And this is the output from webpack after trying to compile TS using presumably the types in the 1.2.0:

![image](https://user-images.githubusercontent.com/20032603/40041262-42ffe198-5815-11e8-8101-a419370c2cbe.png)

Any chance you could tell me what I am doing wrong please ?
I would assume that switching from one version to another should fairly easy as I don't use use any custom types, only the ones provided in the packages.

Thanks for your help

**Comment by kvet** [comment]
Hi,
 
It is the first time we see the following error. It looks like a configuration or environment issue. Try to reinstall node modules.

**Comment by a-robin** [comment]
I cleaned up node_modules, reinstalled with yarn install and bumped the version of react-bootstrap to 0.32.1.

I have not made any progress yet, do you have any suggestion by any chance ?

Thanks
