### ISSUE TITLE
Warning: Failed prop type: The prop `minColumnWidth` is marked as required in `TableColumnResizing`, but its value is `undefined`.

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#1081]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
I'm getting the following warning when running my app having updated to 1.2.0:

Warning: Failed prop type: The prop `minColumnWidth` is marked as required in `TableColumnResizing`, but its value is `undefined`.

### Expected Behaviour

No warning.

### Steps to Reproduce (for Bugs)

In the typescript defs, it is an optional prop, but on a brief inspection of the code, it appears you have defined the following proptypes that contradicts that:

https://github.com/DevExpress/devextreme-reactive/blob/07e93a18a0bf649e9fc27c8be0b3eeb8b5aebdb0/packages/dx-react-grid/src/plugins/table-column-resizing.jsx
```js
TableColumnResizing.propTypes = {
  defaultColumnWidths: PropTypes.array,
  columnWidths: PropTypes.array,
  onColumnWidthsChange: PropTypes.func,
  minColumnWidth: PropTypes.number.isRequired,
};
```

### Your Environment

devextreme-reactive: 1.2.0
react: @latest
browser: chrome
bootstrap: 3

**Comment by kvet** [comment]
Hi,

This issue is related to the following PR: #948.
