### ISSUE TITLE
Exposing select all functionality

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#1084]
I'm trying to expose 'select all' functionality to a component that uses the grid, and based on another issue https://github.com/DevExpress/devextreme-reactive/issues/532 I've kind of got it working, but due to an improper understanding of your plugin architecture I suspect, I am getting an issue that makes me think I'm going about this the wrong way. 

What I have is a plugin, that attempts to expose `selectAllAvailable, allSelected, someSelected, toggleSelectAll`, but because they are being extracted in the render method of the template (I think), it causes react issues when my parent component acts on the callback because it then ends up trying to change state in render. Is there a way to get at these without having to do it in a render?

My plugin is as follows:

```ts
import { Plugin, Template, TemplateConnector, TemplatePlaceholder } from '@devexpress/dx-react-core';
import * as React from 'react';

export interface SelectAllState {
    selectAllAvailable: boolean;
    allSelected: boolean;
    someSelected: boolean;
    toggleSelectAll: (state?: boolean) => void;
}

interface SelectAllAdapterProps {
    onSelectAllChanged?: (state?: SelectAllState) => void;
}

export class SelectAllAdapter extends React.Component<SelectAllAdapterProps> {
    private sas: SelectAllState = {
        allSelected: false,
        selectAllAvailable: false,
        someSelected: false,
        toggleSelectAll: () => { /*nop*/ }
    };

    public render() {
        return (
            // <Plugin>  name="SelectAllAdapter" dependencies={[{ name: 'IntegratedSelection' }]}>
            <Plugin>
                <Template name="table">
                    <TemplateConnector>
                        {(
                            // See docs here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-selection/#exports
                            { selectAllAvailable, allSelected, someSelected }: any,
                            { toggleSelectAll }: any
                        ) => {
                            this.updateState({ selectAllAvailable, allSelected, someSelected, toggleSelectAll });
                            return null;
                        }
                        }
                    </TemplateConnector>
                    <TemplatePlaceholder />
                </Template>
            </Plugin>
        );
    }

    private updateState = (newState: SelectAllState) => {
        if (typeof this.props.onSelectAllChanged !== 'function' || this.isUnchanged(newState)) {
            return;
        }
        this.sas = newState;
        this.props.onSelectAllChanged(newState);
    }

    private isUnchanged = (newState: SelectAllState) => (
        this.sas.allSelected === newState.allSelected &&
        this.sas.selectAllAvailable === newState.selectAllAvailable &&
        this.sas.someSelected === newState.someSelected &&
        this.sas.selectAllAvailable === newState.selectAllAvailable
    )
}
```

As you can see, updateState is in the template connector render, which I think is the root of the problem causing:

```
Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
```

The issue only seems to occur during the initial render.

**Comment by SergeyAlexeev** [comment]
Hi,

Usually, we use [Templates](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/rendering-markup/) to render a markup. You can use [Action](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/providing-actions/) to update a state.

**Comment by DanHarman** [comment]
@SergeyAlexeev thanks for responding.

It seems like the only way to get access to injected values is through the templateconnector and that only works inside render(), which makes it the wrong place to be manipulating state or invoking callbacks etc. Is there a way to get at them somewhere else?

From a high level all I'm trying to do is expose values and actions outside the grid, for instance I have my own toolbar that needs to be able to select all/none.

**Comment by kvet** [comment]
Hi,

Getters and Actions are not designed to be used outside the Grid because this breaks the React principle where props are passed from parent to child components. You should use the controlled mode in the following case.
