### ISSUE TITLE
Vertical column names

### ISSUE THREAD

**Issue by zcuric** [DevExpress/devextreme-reactive#1096]
Hi, this is probably one of the greatest react libraries around. 

I have couple of questions for some use cases: 
1. Is posible to set vertical column names?
2. Is posible to show/hide children in banded columns? Or in my particular case: all parents have the same children title (different data of course), would it be posible to somehow to show/hide child for all parents at once? Can `ColumnChooser` accept custom args to be manipulated with `onChange` event or similiar?

**Comment by zcuric** [comment]
@SergeyAlexeev Thanks!
One more question: What about sticky rows?

**Comment by zcuric** [comment]
@MaximKudriavtsev for example one row that could be set as footer and maybe show like calculated total number of the upper rows or something like that, and it will be always displayed, same as column in Virtual scrolling option, as you scroll.

**Comment by MaximKudriavtsev** [comment]
@zcuric we planned the implementation of this feature in our React Grid. For news, please follow this [thread](https://github.com/DevExpress/devextreme-reactive/issues/293).
