### ISSUE TITLE
[Enhancement] Update Material-UI Dependency to stable v1

### ISSUE THREAD

**Issue by GuyWithCookies** [DevExpress/devextreme-reactive#1097]
### Current Behaviour
Currently v0 Version of [Material-UI](https://github.com/mui-org/material-ui) is used - which is considered beta-status.

### Expected Behaviour
The first stable release v1 which just was released should be used to enhance stability.

**Comment by sli** [comment]
It seems like v1.2.0 uses a compatibly-new version of MUI (1.0RC) and has been migrated to the new @material-ui namespace. The version I can install from npm right now is also v1.2.0, but uses the old MUI import paths.

That's a little weird.

**Comment by kvet** [comment]
Hi,

We already support the new `material-ui` packages. Find more information at: #1073

**Comment by vtrphan** [comment]
Hi, i have upgraded to TypeScript 2.8.3 and get this error:

 error TS2322: Type '(theme: Theme) => { root: { padding: number; }; }' is not assignable to type 'Record<any, CSSProperties>'.
  Index signature is missing in type '(theme: Theme) => { root: { padding: number; }; }'.

How may i fix it? Thanks

**Comment by SergeyAlexeev** [comment]
Hi,

React Grid v1.3.0 is available on npm.
