### ISSUE TITLE
Templating table body?

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#1098]
I've written a plugin to integrate `react-contextmenu` into the grid and it's working pretty well, however I'm currently templating the `table` to wrap the rows in a single contextmenu trigger. Unfortunately this template wraps the whole `table-responsive` so I end up with the trigger on the header row as well as the body, which I don't want.

Is there a template that just wraps the rows, and also if I wrap it, will it break all the styling in the bootstrap theme? (I initially put a trigger on each row but it totally killed all the styling, and its better to have only one trigger anyway).

```js
export class GridContextMenu extends React.PureComponent<Props> {
    public render() {
        return (
            <Plugin>
                <Template name="table">
                    {(params: any) => (
                        <>
                            <ContextMenuTrigger id={this.props.id}>
                                <TemplatePlaceholder />
                            </ContextMenuTrigger>
                            <TemplateConnector>
                                {(
                                    // See docs here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-selection/#exports
                                    { getRowId, rows, selection, selectAllAvailable, allSelected, someSelected }: any,
                                    { toggleSelectAll }: any
                                ) => {
                                    const getSelectedRows = () => (rows as any[]).filter(r => (selection as any[]).indexOf(getRowId(r)) > -1);
                                    return this.props.menuComponent({ selection, selectAllAvailable, allSelected, someSelected, toggleSelectAll, getSelectedRows });
                                }}
                            </TemplateConnector>
                        </>
                    )}
                </Template>
            </Plugin>
        );
    }
}
```

An alternative would be a way of telling that the click was on the header vs body, but not sure this is accessible.

**Comment by SergeyAlexeev** [comment]
Hi,

Nice work! Unfortunately, there isn't such a template you described. Most likely, you know about the `Table` plugin's `bodyComponent` property. You can use it to [implement](https://stackblitz.com/edit/react-qjwcwz?file=index.js) a similar functionality. It isn't a plugin way, but still.

**Comment by DanHarman** [comment]
Thanks. That really breaks the encapsulation of the extension which is a bit nasty. Is there a way to set the bodyComponent from within a plugin?

**Comment by DanHarman** [comment]
ok thanks.
