### ISSUE TITLE
How to call action toggleColumnVisibility manually?

### ISSUE THREAD

**Issue by nskiro** [DevExpress/devextreme-reactive#1099]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Expected Behaviour
I would like to call action toggleColumnVisibility of TableColumnVisibility plugin manually (for example, hiding column from external checkbox) but i don't know how to do it. PLease help me!

### Your Environment

devextreme-reactive: 1.2.0
react: 16.3.2
browser: Google Chrome 66.0.3359.181 64 bit
bootstrap: none
react-bootstrap: 0.32.1
material-ui: none

**Comment by kvet** [comment]
Hi,

Actions are designed to be called within the Grid. For any external logic use the controlled mode in the TableColumnVisibility plugin.
