### ISSUE TITLE
Pseudo/Empty row to fill grid

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1103]
If I have a grid with fix height (ex. 1200px) and only 3 row. 
Can I draw empty row (pseudo row) for fill all grid without using data ?

**Comment by kvet** [comment]
Hi,

There is the VirtualTable plugin that supports rendering in a viewport with a fixed height. It also allows setting desired height. Have you tried it?

**Comment by ccamusso** [comment]
I try with this example but not work:
https://codesandbox.io/s/2v77w60qzj

I need to render empty row to fill free space of table, is possible?

**Comment by MaximKudriavtsev** [comment]
@ccamusso, use the [`VirtualTable`](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/) plugin.

[Example](https://codesandbox.io/s/pw5m5991k0)

**Comment by ccamusso** [comment]
Thank you Max,
but in your example (https://codesandbox.io/s/pw5m5991k0)  I not see empty row.
I see online a empty space.

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,

In this [example](https://codesandbox.io/s/1zv89w9y8q), an empty row is added to Grid's empty space using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) plugin. The row type is `nodata`.
