### ISSUE TITLE
Row detail does not persist with reactive app

### ISSUE THREAD

**Issue by msteinmn** [DevExpress/devextreme-reactive#1112]
DevExpress React v1.1.1

I have a reactive app where data is inserted into the collection in the backend. These changes are reactively pushed to the front-end via s subscription in real-time.

If a row detail is open in the table, then that stays attached to the row number. As new rows are inserted at the top of the table the row detail remains at the row # for which it was originally opened, but the content now has shifted down a row as a new row came in at the top.

Is there a way to make row detail persist to the content and not the row #?

**Comment by SergeyAlexeev** [comment]
Hi,

As far as I understand, there is a problem with row IDs. If so, I suggest you specify the `getRowId` property of [Grid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/). This [sample](https://codesandbox.io/s/9lv76lol34) shows how to do this.
