### ISSUE TITLE
Beta or RC or stable with MUIv1?

### ISSUE THREAD

**Issue by zcuric** [DevExpress/devextreme-reactive#1113]
Hi, any plans for releasing beta, RC, or stable version with MUIv1? I've seen that changes have been merged and it should be ready to go.
Need to update my apps :)

Thanks!

**Comment by lgsus-online** [comment]
+1

**Comment by SergeyAlexeev** [comment]
Hi,

Fixed in [v.1.3.0-beta.2](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#130-beta2-2018-05-24).
