### ISSUE TITLE
Adding custom background color for selected rows when using TableSelection with selectByRowClick

### ISSUE THREAD

**Issue by petruscurtu** [DevExpress/devextreme-reactive#1114]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Hello! Firstly I would like to say congratulations for an awesome job. Secondly, I would like to post a question. 
I am using a VirtualTable with TableSelection with selectByRowClick and highligthRow. I would like to add a custom css, nothing crazy only to change the background color, for the rows that are selected. Is there any way to achieve this feature?
Also I would like to make a custom cell containing maybe a checkbox or a column. I tried looking into TableEditColumn but this is not flexible enough for my needs.

### Your Environment

devextreme-reactive: 1.3.0-beta.1
react: 16.3.1
browser: chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-rc.0

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your feedback about our [React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/). To achieve the required result, you can follow this [thread](https://github.com/DevExpress/devextreme-reactive/issues/437).
