### ISSUE TITLE
Infinite scrolling for pagination

### ISSUE THREAD

**Issue by dispix** [DevExpress/devextreme-reactive#1119]
There's a lot of great documentation and tools for a classic pagination. However nothing is documented/provided for an infinite scrolling table. In the current state of react-grid, is it possible ? What would be needed to implement it ?

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your feedback about our [React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/). To achieve the required result, you can follow this [thread](https://github.com/DevExpress/devextreme-reactive/issues/501).
