### ISSUE TITLE
Tree grid with Virtual table renders endlessly the parent and child rows.

### ISSUE THREAD

**Issue by a-robin** [DevExpress/devextreme-reactive#1121]
Hi,

I have experienced some weird behaviour with the 1.20 grid having a virtual table and a tree grid in it.

When I expand the row to see its children and close it again, the first child row remains adding one row to the whole table every time.

Here is the snippet :

``` typescript

getChildRows = (row: Example, rootRows: Example[]) => {
    return row ? row.childViews : rootRows;
  };

 render() {
    return (<Grid
          rows={rows}
          columns={columns}
          getRowId={(example:Example) => example.id}
        >
<TreeDataState />
 <CustomTreeData getChildRows={this.getChildRows} />
<VirtualTable/>
<TableTreeColumn for="column" />
</Grid>
);
}
```

Is that something to expect combining the tre grid and the virtual table ?

Thanks

**Comment by MaximKudriavtsev** [comment]
Hi,

I can't [reproduce](https://codesandbox.io/s/r1m1vyv2mo) your issue. Please, check that all your rows (with children rows) have the `id` field with uniquel value.

**Comment by a-robin** [comment]
Hi Maxim,

I think you nailed it, I do have child rows that refer to a parent row id as it is a composite.

I will try that then.

Thanks

**Comment by a-robin** [comment]
It is solved! 

Thanks

**Comment by MaximKudriavtsev** [comment]
You are welcome!
