### ISSUE TITLE
Could not find module in path: 'material-ui/Tooltip' relative to '/node_modules/@devexpress/dx-react-grid-material-ui/dist/dx-react-grid-material-ui.cjs.js'

### ISSUE THREAD

**Issue by anil-reputation** [DevExpress/devextreme-reactive#1126]
@devexpress/dx-react-grid-material-ui still showing dependency on beta version of material UI which ideally it should not be. As i am using the latest version of material ui.  I dont want to use the beta version of material ui.

**I am not able to render table using @devexpress/dx-react-grid-material-ui. Code sandbox link is below.**
https://codesandbox.io/s/7z02o7p6nj

**Comment by anil-reputation** [comment]
I dont want to use deprecated package of material ui. With latest version can you resolve the issue

**Comment by SergeyAlexeev** [comment]
Hi,

We've supported Material UI v1.0.0 starting with [v1.3.0-beta.2](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#130-beta2-2018-05-24).

**Comment by anil-reputation** [comment]
I agree but at some places, its still referring to the beta version of material-ui which is deprecated now and not the latest one wich is causing the problem. You can try rendering the table with the latest material-ui i.e "@material-ui" not the "material-ui".

**Comment by SergeyAlexeev** [comment]
Please refer to [this](https://github.com/DevExpress/devextreme-reactive/issues/1130) issue.
