### ISSUE TITLE
Module not found: Can't resolve 'material-ui/Button' in 'node_modules\@devexpress\dx-react-grid-material-ui\dist'

### ISSUE THREAD

**Issue by ThatBrianDude** [DevExpress/devextreme-reactive#1130]
I have the following package.json:
  
"dependencies": {
    "@devexpress/dx-react-core": "^1.2.0",
    "@devexpress/dx-react-grid": "^1.2.0",
    "@devexpress/dx-react-grid-material-ui": "^1.2.0",
    "@material-ui/core": "^1.1.0",
    "material-ui": "^0.20.1",   

...

This was supposed to be solved in #1104 but it seems some people are still receiving this error. 

EDIT: for some reason github is removing "@ material-ui / core" and replacing it with "".  (The spaces are not in my package json, they are required to keep github from removing the dependancy.. weird)

**Comment by ThatBrianDude** [comment]
Fixed by updating dependancies to "^1.3.0-beta.2":

    "@devexpress/dx-react-core": "^1.3.0-beta.2",
    "@devexpress/dx-react-grid": "^1.3.0-beta.2",
    "@devexpress/dx-react-grid-material-ui": "^1.3.0-beta.2",
    "@material-ui/core": "^1.1.0",
    "material-ui": "^0.20.1",

**Comment by godara01** [comment]
You can do the `npm list` and then whichever dependency have  `UNMET PEER DEPENDENCY` mark, just install it manually.
Ex.
`+-- UNMET PEER DEPENDENCY @material-ui/core@^1.1.0`
`+-- UNMET PEER DEPENDENCY @material-ui/icons@^1.1.0`
Then install them by:
`npm install --save @material-ui/core@^1.1.0 @material-ui/icons@^1.1.0`

**Comment by atuljustano** [comment]
now getting this error
Module not found: Can't resolve '@material-ui/core/Grid' in 'E:\Material Ui\firstapp\src'
