### ISSUE TITLE
How to make sure Searching only happens on visible columns.

### ISSUE THREAD

**Issue by volkanakbas** [DevExpress/devextreme-reactive#1137]
I would like to be able to search on only visible columns. Is it possible?

I'm using the latest version.

Thanks.

**Comment by gsobolev** [comment]
Hi @volkanakbas,
 
Currently, the requested functionality is not available out of the box. Yet, we have plans to support it in future versions.
 
In the meantime, I suggest you use the workaround shown at [this sample](https://codesandbox.io/s/2x876o3rrj).

**Comment by volkanakbas** [comment]
Thank you, @gsobolev. Exactly what I needed.
