### ISSUE TITLE
React Grid Boolean data

### ISSUE THREAD

**Issue by tunegov** [DevExpress/devextreme-reactive#114]
How can I display boolean data? And I want to edit this cell. Can I add cell template for one column?

**Comment by kvet** [comment]
Hi,

It is possible to define a custom template for a specific column.

Examples can be found in our demos:
- [a custom cell template](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-demos/src/bootstrap3/featured/controlled-mode.jsx#L257)
- [a custom edit cell template](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-demos/src/bootstrap3/featured/controlled-mode.jsx#L262)
