### ISSUE TITLE
[Feature Request] Selectable and non-selectable rows

### ISSUE THREAD

**Issue by yzaroui** [DevExpress/devextreme-reactive#1149]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I also asked this in stackoverflow but didn't get any hint.

Is there a way to tell DevExtreme React Grid to show or hide the selection cell (checkbox) depending on some data in the row object like { selectable: true } ?

![image](https://user-images.githubusercontent.com/3058420/40786782-3004771e-64ec-11e8-93d2-b9c2f8436c6c.png)

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you use a custom cell component for the `TableSelection` plugin. This [sample](https://codesandbox.io/s/myo8rx6299) shows how to do it.
