### ISSUE TITLE
Receiving a maximum depth error

### ISSUE THREAD

**Issue by kgduong** [DevExpress/devextreme-reactive#1153]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Currently running some of the demo code within the devextreme-reactive tutorial and I'm receiving the following error:
**Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**

### Expected Behaviour
Expected behavior should generate a regular line graph as displayed in the examples. 

### Your Environment

devextreme-reactive: 18.1.3
react: 16.4
browser: Chrome
bootstrap: 4
react-bootstrap: 0.32.1
material-ui: none

**Comment by alexey-semikozov** [comment]
Hi @kgduong,
I'm unable to reproduce the behavior you are talking about. Would you please provide more details about your project?
Here is a sample that I used to reproduce this issue: https://codesandbox.io/s/lr5m9zrmyq
