### ISSUE TITLE
React Grid: Programmatically scroll to not generated row

### ISSUE THREAD

**Issue by veznidav** [DevExpress/devextreme-reactive#1170]
I use React Grid with Virtual Scrolling. I have about 500 rows in this grid. Each row has an ID. In my application, only 10 rows are visible at a time. If a user wants to see more rows, he simply scrolls down or up, no problem. But this application communicates with another system where users can select something. Based on this selection in another system I need to select the proper row in my React Grid and show the selected row to a user. I know the ID of the desired row, but I am not able to use `document.getElementById('elementID').scrollIntoView()` because this row has not been generated in the DOM so far. 

Simplified explanation: 
`React Grid w/ Virtual Scrolling shows 10 of 500 rows (ids: el1 - el10) -> in another system was selected an item corresponding to el200 in React Grid -> react app tries document.getElementById('el200').scrollIntoView() -> not successfull because there is no el200 so far`

Is it possible to programmatically scroll to a row that has not been generated so far?

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to the similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/436).
