### ISSUE TITLE
How to achieve horizontal virtual scrolling with flexbox container

### ISSUE THREAD

**Issue by harryluo91** [DevExpress/devextreme-reactive#1171]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Hi, I have a table as a child element of a flexbox container. Right now the table wrapper does not resize with the container because of the `min-width` property on the table, thus the table does not go into virtual scrolling mode. Is there a way resolve this? Thanks in advance.

### Your Environment

devextreme-reactive: 1.3.0
react: 16.4.0
browser: chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.2.0

**Comment by SergeyAlexeev** [comment]
Hi,

I could not reproduce this behavior. Would you please modify this [sample](https://codesandbox.io/s/xvz61108yw) to reproduce it?
