### ISSUE TITLE
[Bug] Column resize handles are invisible

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#1174]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I have created a Table using the that implements Column Resizing. Column resizing behaves normally **except** the resize handles are invisible. 

### Expected Behaviour

* The resize handles become visible when the user hovers over the table header row.
* The resize handles are visible when the user is resizing columns

### Steps to Reproduce (for Bugs)

[Example](https://codesandbox.io/s/l24o1vwxzl), forked from [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/#try-out-the-react-grid)

### Your Environment

Snipped from `package.json`

```
"@devexpress/dx-core": "^1.3.0",
"@devexpress/dx-grid-core": "^1.3.0",
"@devexpress/dx-react-core": "^1.3.0",
"@devexpress/dx-react-grid": "^1.3.0",
"@devexpress/dx-react-grid-material-ui": "^1.3.0",
"@material-ui/core": "^1.2.0",
"jss": "^9.8.2",
"react": "^16.4.0",
```

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your feedback. To solve this problem, you can add the [ThemeProvider](https://material-ui.com/customization/themes/#theme-provider) component.

Please follow this [example](https://codesandbox.io/s/7w249rj0mj) for detailed information.

**Comment by MaximKudriavtsev** [comment]
Make sure that you specify a primary color for your theme.

`
const myTheme = createMuiTheme({
  palette: {
    type: "light",
    primary: blue
  }
});
`

**Comment by thehig** [comment]
Thanks again for the reply, but I *definitely* have a primary color set

**Comment by MaximKudriavtsev** [comment]
Does your theme contain this [color](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.jsx#L22)?

**Comment by thehig** [comment]
Ah-ha, thats a good lead. I'll check it out, thanks

**Comment by thehig** [comment]
Yes this looks like it could be the source of the issue. My theme is set up to use a single hex color as Primary, and infer the other colors from there.

See **"Providing the colors directly"** [here](https://material-ui-next.com/customization/themes/)

**Comment by thehig** [comment]
I'm just coming back around to this now, is there any way to fix this without redefining how my applications colors are being generated?

**Comment by MaximKudriavtsev** [comment]
No. You should define the grid's theme as follows:

```jsx
import { MuiThemeProvider, createMuiTheme } from '@material-ui/core/styles';
import { blue } from '@material-ui/core/colors';

const lightTheme = createMuiTheme({
  palette: {
    type: 'light',
    primary: blue,
  },
});

const GridWrapper = ({ children }) => (
  <MuiThemeProvider theme={lightTheme}>
    {children}
  </MuiThemeProvider>
);
```

**Comment by thehig** [comment]
That totally wrecked my app's theme, but led me to a workaround:

```javascript
const theme = createMuiTheme(themeSource);

theme.palette.primary[300] = theme.palette.getContrastText(
  theme.palette.background.default
);
```

Thanks for the assistance
