### ISSUE TITLE
Cannot install 1.3.0

### ISSUE THREAD

**Issue by clivedsouza1010** [DevExpress/devextreme-reactive#1175]
Hi @kvet @SergeyAlexeev 

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

When I add ,
"@devexpress/dx-react-core": "^1.3.0",
    "@devexpress/dx-react-grid": "^1.3.0",
    "@devexpress/dx-react-grid-material-ui": "^1.3.0",

in my package.json and do a yarn install I get a message saying these packages are not available and get a list with the max package version of 1.2.0.

npm i --save @devexpress/dx-react-core @devexpress/dx-react-grid
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @devexpress/dx-core@1.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@devexpress/dx-react-core'

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @devexpress/dx-grid-core@1.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@devexpress/dx-react-grid'
npm ERR! notarget

### Expected Behaviour

I should be able to install 1.3.0

### Your Environment

material-ui-core: 1.3.0

**Comment by SergeyAlexeev** [comment]
Hi,

It [works](https://www.screencast.com/t/1XCGF2IT) fine on my side.

The `yarn info @devexpress/dx-react-grid` command shows all available versions as well:

```
versions:
   [ 
     ...
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.2.0-beta.1',
     '1.2.0-beta.2',
     '1.2.0-beta.3',
     '1.2.0',
     '1.3.0-beta.1',
     '1.3.0-beta.2',
     '1.3.0' 
],
```

**Comment by clivedsouza1010** [comment]
@SergeyAlexeev Thanks for looking into it. I am able to find the correct version of the following,

"@devexpress/dx-react-core": "^1.3.0",
"@devexpress/dx-react-grid": "^1.3.0",
"@devexpress/dx-react-grid-material-ui": "^1.3.0"

But I seem to have a problem with the following when I run a yarn install.

@devexpress/dx-core@1.3.0
@devexpress/dx-grid-core@1.3.0

I also ran yarn info and it shows me that 1.2.0 is the latest version for both.

```
a45e60f123c1:tets-yarn z001v7q$ yarn info @devexpress/dx-core
yarn info v1.5.1
error Could not open cafile: ENOENT: no such file or directory, open '/Users/z001v7q/Downloads/tgt-ca-bundle.crt'
{ name: '@devexpress/dx-core',
  description: 'Core library for DevExtreme Reactive Components',
  'dist-tags':
   { next: '1.2.0-beta.3',
     latest: '1.2.0' },
  versions:
   [ '1.0.0-alpha.1',
     '1.0.0-alpha.3',
     '1.0.0-alpha.4',
     '1.0.0-alpha.5',
     '1.0.0-alpha.6',
     '1.0.0-alpha.7',
     '1.0.0-alpha.8',
     '1.0.0-alpha.10',
     '1.0.0-alpha.11',
     '1.0.0-alpha.12',
     '1.0.0-alpha.13',
     '1.0.0-alpha.14',
 '1.0.0-beta.1',
     '1.0.0-beta.2',
     '1.0.0-beta.3',
     '1.0.0-rc.1',
     '1.0.0-rc.2',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.1.0-beta.1',
     '1.1.0-beta.2',
     '1.1.0-beta.3',
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.2.0-beta.1',
     '1.2.0-beta.2',
     '1.2.0-beta.3',
     '1.2.0' ],
 

a45e60f123c1:tets-yarn z001v7q$ yarn info @devexpress/dx-grid-core
yarn info v1.5.1
error Could not open cafile: ENOENT: no such file or directory, open '/Users/z001v7q/Downloads/tgt-ca-bundle.crt'
{ name: '@devexpress/dx-grid-core',
  description: 'Core library for the DevExtreme Reactive Grid component',
  'dist-tags':
   { next: '1.2.0-beta.3',
     latest: '1.2.0' },
  versions:
   [ '1.0.0-alpha.1',
     '1.0.0-alpha.2',
     '1.0.0-alpha.3',
     '1.0.0-alpha.4',
     '1.0.0-alpha.5',
     '1.0.0-alpha.6',
     '1.0.0-alpha.7',
     '1.0.0-alpha.8',
     '1.0.0-alpha.9',
     '1.0.0-alpha.10',
     '1.0.0-alpha.11',
     '1.0.0-alpha.12',
     '1.0.0-alpha.13',
     '1.0.0-alpha.14',
     '1.0.0-beta.1',
     '1.0.0-beta.2',
     '1.0.0-beta.3',
     '1.0.0-rc.1',
     '1.0.0-rc.2',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.1.0-beta.1',
     '1.1.0-beta.2',
     '1.1.0-beta.3',
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.2.0-beta.1',
     '1.2.0-beta.2',
     '1.2.0-beta.3',
     '1.2.0' ],

```

**Comment by SergeyAlexeev** [comment]
Sounds strange... 
`yarn info` [returns](https://www.screencast.com/t/XbvVptOO) all versions for the '@devexpress/dx-core' package. The same about the '@devexpress/dx-grid-core' one.

**Comment by clivedsouza1010** [comment]
@SergeyAlexeev not sure whats going on. Anybody else getting this issue or only me?

**Comment by clivedsouza1010** [comment]
@SergeyAlexeev I found the issue. I basically had to set the yarn config registry url. Thanks
