### ISSUE TITLE
How to edit and test this project

### ISSUE THREAD

**Issue by veznidav** [DevExpress/devextreme-reactive#1177]
Hi, I am pretty new to open source and have one beginner question. I would like to make changes to this project and debug it somehow (just want to know how things work etc.). Probably I should download the whole project and run it locally but I am not sure how can I test it. I tried to download it, referenced Grid and Table in my React app and then I expected I can modify Grid and Table source code but it did not work because the app did not compile at all.

**Comment by SergeyAlexeev** [comment]
Hi,

It's great to hear you are interested in our project!

First, [fork](https://help.github.com/articles/fork-a-repo/) the 'DevExpress/devextreme-reactive' repo. Then, [create a local clone](https://git-scm.com/docs/git-clone) of your fork. Next, go to your local copy and install all dependencies and build the project:

```
npm i
npm run build
```

or

```
yarn install
yarn build
```

if you are using yarn as a package manager.

The 'watch' mode is also available - `npm run build:watch`. After that you can see demos in a browser. Just navigate to http://localhost:3002/.
Of course, you can create a [pull request](https://help.github.com/articles/about-pull-requests/) if you find and fix a bug or implement a feature. We'll review it and merge it if it's OK. See this [article](https://guides.github.com/introduction/flow/) for more details.

**Comment by veznidav** [comment]
Thank you very much! I have one more question. If I make changes, how can I locally test the new version of a package (e.g. dx-react-grid-material-ui) in different React app that uses this package from npm repository?

**Comment by veznidav** [comment]
Also I got an error after `npm run build` or `yarn build` 
![image](https://user-images.githubusercontent.com/3127469/41152760-e9a43b4a-6b14-11e8-8d65-5d8c7878b344.png)

**Comment by SergeyAlexeev** [comment]
@veznidav please refer to this [issue](https://github.com/DevExpress/devextreme-reactive/issues/572).

**Comment by veznidav** [comment]
@SergeyAlexeev thanks, it works. This time I am dealing with the virtual table but I still can't find where are data for current view generated, could you give me an advice where to look?

**Comment by SergeyAlexeev** [comment]
Are you talking about a data for a demo? If so, check this [folder](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-demos/src/demo-data). If you are looking for virtual scrolling implementation, look at these files:

- [virtual-table-layout.jsx](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx)
- [virtual-table.js](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx)

**Comment by veznidav** [comment]
Thank you very much for your help!
