### ISSUE TITLE
Redux demo with remote data example

### ISSUE THREAD

**Issue by efstathiosntonas** [DevExpress/devextreme-reactive#1183]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Your Environment

devextreme-reactive: 1.3.0

Can you please provide a simple example with Redux and remote data?

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to this [demo](https://codesandbox.io/s/n3wvnm3p6l) that is based on [Redux Documentation](https://redux.js.org/advanced/async-actions).
