### ISSUE TITLE
How keep columns where they are when grouped?

### ISSUE THREAD

**Issue by volkanakbas** [DevExpress/devextreme-reactive#1188]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I would like to make sure columns don't move when they are grouped. It seems like every new grouping comes into columns move 40px to right. Here is the screen shot of current behaviour.
![screenshot](https://user-images.githubusercontent.com/4326088/41369317-2caecd76-6f0a-11e8-9721-ada1a8885abb.png)
 
I'm using the latest version.

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, we don't provide a ready-to-use solution for your case.

As a workaround, you can manually manage `colgroup` tag rendering on the `componentDidMount` and `componentDidUpdate` events.

One more thing I'd like to point out is that you need to add an offset for a table group cell. However, this requires writing additional code. You can use this [sample](https://codesandbox.io/s/j7lq2m0ojy) as a starting point.
