### ISSUE TITLE
Set Table height to 100%

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1196]
Hi,
Is it possible to set Table height to 100% and enabled vertical scroll bar to scroll row component?

Carlo

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you use the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/) plugin. It supports vertical and horizontal scrolling. I'd also like to point out one important detail - you need to specify the height in pixels. Please refer to this [issue](https://github.com/DevExpress/devextreme-reactive/issues/996) for more details.
