### ISSUE TITLE
Fill a remaining horizontal space

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1197]
Hi,
I've a Table with three column and this: defaultColumnWidths:
[
      { columnName: 'column_a', width: 20 },
      { columnName: 'column_b', width: '40' },
      { columnName: 'column_c', width: '100' }
]

Is it possibile:
1) to set Table with to 100%?
2) to set column_c to fill a remaining horizontal space?

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi,
1. The [DevExpress React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/)'s width is 100% by default.
2. If you want to fill all empty space, don't set the width property for the current column.

Please refer to this [example](https://codesandbox.io/s/jp566mlqz3) for detailed information.

**Comment by divyanshupathak94** [comment]
Hi @MaximKudriavtsev ,
I have the same requirement and I follow the code which you suggest above. What I want is that, last column should fill the remaining table area. How to achieve this? Please help.

I am inserting code snippet of columns below - 

```
[
            { title: 'Id', name: 'EmailTemplateId', type: 'int', width: 100 },
            { title: 'Subject', name: 'Subject', type: 'string' }
]
```

Here is my current output - 
![capture1](https://user-images.githubusercontent.com/37737345/42876144-64bac418-8aa3-11e8-9f42-62b865ee10d3.PNG)
Here is the output which I want -
![capture2](https://user-images.githubusercontent.com/37737345/42876178-8142e0f2-8aa3-11e8-956a-767d7caaf660.PNG)

**Comment by MaximKudriavtsev** [comment]
Hi @divyanshupathak94,

I can't reproduce the issue on my side. Please create a [sandbox](https://codesandbox.io/s/13qvz1qqzl) with minimum configuration for your case.

Make sure that your grid has only two objects in the `columns` field.
