### ISSUE TITLE
tr:hover - change background on mouse over

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1199]
Hi,
I'm trying to set background color of row when on mouse over row, but not work.
I'm using this code:

const TableRow = ({ row, ...restProps }) => (
  <Table.Row
    {...restProps}
    onClick={() => alert(JSON.stringify(row))}
    style={{
      cursor: 'pointer',
      '& tbody tr:hover': { backgroundColor: '#ff0000' }
    }}
  />
);

Is possible change color of row when on mouse over the row?

**Comment by ccamusso** [comment]
Fix, I'm using this setup:

const styles = theme => ({
  tableStriped: {
    '& tbody tr:hover': { backgroundColor: '#ff0000 !Important', },
    '& tbody tr:nth-of-type(odd)': { backgroundColor: '#f6f8fa', },
    '& tbody tr:nth-of-type(even)': { backgroundColor: '#fff', },
  }
});

**Comment by digitalillusion** [comment]
This is a better solution.
                <Table
                    rowComponent={
                        ({ row, ...restProps }) =>
                            <Table.Row
                                {...restProps}
                                {... {hover: true}}
                            />}
                />
