### ISSUE TITLE
Is it possible to show filter cell only in one column?

### ISSUE THREAD

**Issue by efstathiosntonas** [DevExpress/devextreme-reactive#1203]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

With this code:

```
const UnitsFilterCellBase = ({filter, onFilter, classes}) => (
    <TableCell className={classes.cell}>
        <Select
            className={classes.input}
            value={filter ? filter.value : ''}
            onChange={e => {
                console.log(e.target.value)
                onFilter(e.target.value ? {value: e.target.value} : null)
            }}
            inputProps={{
                name: 'CarCategory'
            }}
        >
            {categories.map(item => {
                return <MenuItem value={item.Id} key={item.Id}>{item.Category}</MenuItem>
            })}
        </Select>
    </TableCell>
);
const UnitsFilterCell = withStyles(styles, {name: 'CarCategory'})(UnitsFilterCellBase);

const FilterCell = (props) => {
    if (props.column.name === 'CarCategory') {
        return <UnitsFilterCell {...props} />;
    }
    return <TableFilterRow.Cell {...props} />;
};
```
It shows the select box in one column, and the other columns have the input with the 'Filter' placeholder. How can I not show the other filter inputs and keep only the Select?

I could set the `<TableFilterRow.Cell {...props} />` as a div and hide it with css but I think there is a better way, not by hacking.

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/404).
