### ISSUE TITLE
TableGroupRow not aligning when used with VirtualTable

### ISSUE THREAD

**Issue by KamalAman** [DevExpress/devextreme-reactive#1209]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
indentColumnWidth for TableGroupRow cannot be set to 0 when using virtualTable

### Expected Behaviour
When setting indentColumnWidth for TableGroupRow to 0, there should not be any indentation

Other issues with this are: 
 the VirtualTable body width does not take into consideration the scollbar on windows, but this is probably a side-effect due the the indentColumnWidth bug. 
  the VirtualTable header has a default background color. 
 
### Steps to Reproduce (for Bugs)
```javascript

import * as React from 'react';

import {
  GroupingState,
  IntegratedGrouping,
} from '@devexpress/dx-react-grid';

import {
  Grid,
  VirtualTable,
  TableHeaderRow,
  TableGroupRow,
} from '@devexpress/dx-react-grid-material-ui';

const getRowId = row => row.id;


const columns = [
  { title: 'Number', name: 'number' },
  { title: 'Group', name: 'group', type: 'number' },
  { title: 'Comment', name: 'comment' },
  { title: 'Thing', name: 'hasThing' },
]

const rows = [
  { id: 'a', number: 123, stringNmm: '3243', group: 'F', comment: 'Comment test', hasThing: true },
  { id: 'b', number: 23, group: 'E', stringNmm: '1543', comment: 'Hello World', hasThing: true },
  { id: 'c', number: 543, group: 'F', stringNmm: '3243', comment: 'Suger is low', hasThing: false },
  { id: 'd', number: 21, group: 'F', stringNmm: '32', comment: 's', hasThing: false }
];

export default class Demo extends React.PureComponent {
  render() {

    return (
      <Grid
        rows={rows}
        columns={columns}
        getRowId={getRowId}
      >
        <GroupingState
          grouping={[{ columnName: 'group' }]}
        />
        <IntegratedGrouping />
        <VirtualTable  height={200}/>
        <TableHeaderRow />
        <TableGroupRow indentColumnWidth={0}/>
      </Grid>
    );
  }
}
```
<img width="894" alt="screen shot 2018-06-21 at 2 14 25 pm" src="https://user-images.githubusercontent.com/2692357/41737618-cfb67cae-755d-11e8-9e83-cc511c638759.png">

### Your Environment
devextreme-reactive: 1.3.1
react: 16.4
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.2.1

**Comment by kvet** [comment]
Hi,

We've researched the issue and found a bug in Chromium and WebKit. We've created issues related to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=855367 and https://bugs.webkit.org/show_bug.cgi?id=186912.

As a workaround, we suggest you use the 0.1 value instead of 0.
 
Would you please also describe the problem with the scrollbar in greater detail and create a separate issue?
 
The VirtualTable header has a background color as it is implemented as an overlay. Thus body rows will be visible under the header row if we remove background.
