### ISSUE TITLE
Export to Excel / Get Visible rows on the grid

### ISSUE THREAD

**Issue by louisiano1** [DevExpress/devextreme-reactive#1212]
Hello guys, Is there a function to **Export the current grid to Excel**. 

If not, is there a way for me to access the visible rows on the grid after a couple of filters and maybe sorts have been applied; that way i can try to create a custom Export to excel functionality

**Comment by gsobolev** [comment]
Hi @louisiano1,

Please refer to #537 where the same question is discussed.
