### ISSUE TITLE
How to have custom row height in virtual table?

### ISSUE THREAD

**Issue by jasper-lu** [DevExpress/devextreme-reactive#1220]
- [x] I have searched this repository's issues and believe that this is not a duplicate.

I want to be able to have custom row heights in VirtualTable.
What I have tried so far is manually changing the row heights in css, and then changing the `estimatedRowHeight` property in VirtualTable to match. However, when I do this, VirtualTable does not work properly (it does not display all of the rows, just some). 

Is there a more proper way to approach this?

Thanks!

**Comment by SergeyAlexeev** [comment]
Hi,

I can't reproduce the issue on my side. Please, look at this [sample](https://codesandbox.io/s/y7p8o3z6p1).

**Comment by jasper-lu** [comment]
Does making the row height smaller not work in this way? That is how I ran into the issue -- I forced row heights to be 25px using css since adjusting the height in a manner similar to yours didn't seem to work.

**Comment by SergeyAlexeev** [comment]
I've updated my [sample](https://codesandbox.io/s/nrk95p3vzm). Now, row height is 25px. It works as expected. Would you please modify this example to reproduce the problem?

**Comment by jasper-lu** [comment]
I know my mistake -- I  did not change the row height, and only forced cell heights. When I do both, I do not run into the same errors.

I'm curious -- is there a way to make columns more dense as well?

**Comment by SergeyAlexeev** [comment]
Sure, please refer to this [guid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#column-width).
