### ISSUE TITLE
[Question] Conditional commands in TableEditColumn depending on Row Data

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#1222]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Question

I've been modifying a DevExpress table I created a while back to add in editing support. I'm curious about the 'TableEditColumn ', specifically is there any way to modify what commands are available based on the Row data?

If I have a user that can see data, but is only allowed to edit *some* rows, how could I go about disabling the 'edit' or 'delete' commands based on the content of the data (eg some 'canEdit: true' property in the row data)?

**Comment by gsobolev** [comment]
Hi @thehig!
 
Please refer to #689 where we discussed a similar question.

**Comment by thehig** [comment]
Thats great, thank you!
