### ISSUE TITLE
Locale with lingui.js or react-localization

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1228]
The Table locale work with lingui.js or localizzation ?

When I locale **PagingPanel** with this message:
```
const filterRowMessages = {
    filterPlaceholder: <Trans id="filtro" />,
};

```
I obtain this text in filter component: **[object Object]**
Is the same if i using react-localization module

Exist a solution or the table work only with static text?

**Comment by kvet** [comment]
Hi,
 
Grid messages are used in HTML element attributes. So, we can't allow setting a message as a React element.
 
In your case, I recommend you use the `WithI18n` high order component. You can see an example of the image in the following documentation section: https://github.com/lingui/js-lingui#key-features

**Comment by ccamusso** [comment]
Yes, I found solution:

```
import { withI18n } from '@lingui/react';
...
...
render() {
       let { i18n } = this.props;
       let msg = i18n.t`messageId`;
...
...
}
export default withI18n()(MyComponent);

```
