### ISSUE TITLE
[Bug] Popover locations for Sorting Controls overflowing

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#1240]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

When creating a constrained table that performs its' own horizontal scrolling and utilizes the `<TableHeaderRow showSortingControls />`, shrinking the container beyond a minimum size will cause the entire page to create a horizontal scrollbar

### Expected Behaviour

The usage of the Sorting Controls should not overflow the bounds of the Table

#### Code Sample: https://codesandbox.io/s/rmpn3lw2zo

Using a Chrome plugin called [Pesticide](https://pesticide.io/) we can make the sorting control divs visible

![image](https://user-images.githubusercontent.com/96122/42630425-99a6a202-85ce-11e8-96a5-fc733eb184f4.png)

And the corresponding HTML, showing that the popups are 'outside' the root of the application, which is as intended of course, but means i'm not sure how to resolve this

![image](https://user-images.githubusercontent.com/96122/42630414-8bd41bfa-85ce-11e8-8a76-db10907f53a2.png)

The popup anchors do update when resizing at larger sizes, but below some point, they stop tracking the corresponding UI components. However, performing mouseover on the Table Header (bringing up the 'sort' bubble) causes the popup to 'retrack' to the Header, and the scrollbar shrinks or goes away

**Comment by kvet** [comment]
Hi,
 
I've reproduced the issue and forwarded it to the original repository. Here is the link to the issue: https://github.com/mui-org/material-ui/issues/12132
 
Now, as a workaround, I suggest you apply the following styles to the body element: `overflow-x: hidden`.

**Comment by thehig** [comment]
Thanks for forwarding the issue, much appreciated.

As for the workaround, I already tried that to no avail, but thanks for the suggestion

**Comment by thehig** [comment]
This has been resolved by the MUI team. Thanks! :heart:
