### ISSUE TITLE
Is there a way to do something on rows update?

### ISSUE THREAD

**Issue by pbalzano91** [DevExpress/devextreme-reactive#1241]
So, let's say I'm rendering the grid based on a component's state:

`this.state = { rows: [...] }`
`<Grid rows={rows} ... />`

And then I change the state, causing the grid to re-render:

`this.setState({ rows: rows.filter(...) })`

Is there a way to handle that update from within the Grid? For example, if I add a new row, I want to make the bg color blue for that one.

Thanks!

**Comment by kvet** [comment]
Hi,

It is possible to easily implement your case outside the Grid. Here is it: https://codesandbox.io/s/mqlvpm8699. I use Redux in the example to share the state between several components.
