### ISSUE TITLE
TableSelection for selection of only one row?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1245]
TableSelection https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/ allows us to select one or more rows at once. Sometimes it is necessary to allow the selection of only one row. I.e. if user selects the second row, then the first selected row should be automatically removed from the list of the selected rows.

Suggestion is to add new property 'multiselect' to the TableSelection component and in the case of multiselect=false the user can select only one row. DevExpress grids for the desktop have such property.

Is there workaround at the present version of Grid (without multiselect property)?

At present I am using the `<Table rowComponent>` that listens to the clicks on the rows and and assigns the row Id to the this.state.selectedRowId and uses it for the style

```
TableRow = ({ row, ...restProps }) => (
        <Table.Row
            {...restProps}
            onClick={() => this.handleRowClick(row)}
            style={{
                cursor: 'pointer',
                backgroundColor: (row.order_no==this.state.selectedRowId) ? 'green' : 'transparent'
            }}
        />
    );
```
There is problem with this approach: the style is changes upon the click but the changes are not reflected immediately on the screen. I am required to artificially change some additional field of the row during the handling of the click and only then the updated style becomes visible. While such approach works it is a bit dirty: 1) it requires to change some fake field; 2) I am using data from the React state variable and that means that upon each click I should copy entire state and change this one field of the selected row. The grid can be used for quite big data and such copying can be quite expensive. And it is a bit slow indeed. That is why I am not quite satisfied with this workaround.

Maybe there is quick way (some kind if invalidation) how can I trigger the application of the new styles to the grid (or particular rows).

Of course, live would be better without workarounds.

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to the similar question #477.
