### ISSUE TITLE
Resize handles for columns don't appear when using material-ui v1.x

### ISSUE THREAD

**Issue by Maher4Ever** [DevExpress/devextreme-reactive#1246]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

The resize handles for columns don't appear when using material-ui v1.0.0 and newer versions.

### Expected Behaviour

The resize handles for columns should appear.

### Steps to Reproduce (for Bugs)

I simply added the `TableColumnResizing` component to the [CodeSandbox for Material UI](https://codesandbox.io/s/13qvz1qqzl) available on your [getting started guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/). The modified sandbox can be seen on https://codesandbox.io/s/jplj52pp7v

Try to resize the columns and you'll not see the resize handles appear. The cause of this is that the code in `resizing-control.jsx` template still [uses the old syntax](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.jsx#L22) for selecting colors from the palette. Same thing [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/resizing-control.jsx#L40) as well.

### Environment

- devextreme-reactive: 1.4.0
- react: 16.4.0
- vue: none
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.2.3

**Comment by MaximKudriavtsev** [comment]
Hi,

Check this [thread](https://github.com/DevExpress/devextreme-reactive/issues/1174) for more information.

**Comment by Maher4Ever** [comment]
Thank you for linking that thread. As you can see in the [release notes of v1.0.0-beta.28](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.28), material-ui changed the way palettes are defined and the indexing syntax into colors got deprecated. That syntax is still only supported in the official material design colors, but most projects probably don't use these colors in their palette for branding reasons. When using custom colors, you are only assured that the palette will have 3 properties: `dark`, `main` and `light`.

How hard would it be to simply change the lines I linked within `resizing-control.jsx` to `theme.palette.primary.light`? This should fix the issue.

**Comment by Maher4Ever** [comment]
Awesome! Thanks for the quick fix.
