### ISSUE TITLE
How to customize plugin components

### ISSUE THREAD

**Issue by gabirabelo** [DevExpress/devextreme-reactive#1249]
### I'm using ...

- [ x ] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
Hi!
I want to customize the header table and column tittle. 
I already searched the documentation and did not find. 
Can you help me?

**Comment by MaximKudriavtsev** [comment]
Hi,

We recommend customizing the React Grid using Plugin Components. See this [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#appearance-customization) for detailed information.
 
All the plugin components are listed in the API Reference. In your case, you need to use the [TableHeaderRow's components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#plugin-components).
 
If you have further questions regarding this, feel free to contact us.
