### ISSUE TITLE
Deselect All doesn't work without filter first.

### ISSUE THREAD

**Issue by KaiWynn** [DevExpress/devextreme-reactive#1252]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I clicked SelectAll then all rows selected, but when I wanted to DeselectAll by click the same button it didn't work. If I filter my rows, then SelectAll, and DeselectAll then it worked fine.

### Expected Behaviour
Select all, and deselect all by click on the button at anytime.

### Environment
This is the order of my plugins. I moved the IntegratedSelection up but that didn't work neither.
<IntegratedSorting />
<IntegratedGrouping />
<IntegratedFiltering />
<IntegratedSelection />
<IntegratedPaging />

- devextreme-reactive: 1.4.0
- react: 16.4.1
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: "@material-ui/core": "1.2.3", "material-ui": "1.0.0-beta.42"

**Comment by SergeyAlexeev** [comment]
Hi,

I can't reproduce the issue you described. This [sample](https://codesandbox.io/s/w7j5vx02j7) works as expected. Would you please modify it to reproduce the problem?

One more point. Do you really use the Material-UI v.1.2.3 and v.1.0.0-beta.42 at the same time? If so, I suggest you keep only Material-UI v.1.2.3.
