### ISSUE TITLE
Rows are not rendered when scrolled fast

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#1253]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
If I scroll very fast (up and down), the last few rows are not rendered sometimes. If I scroll up a bit again, they are re-rendered.

(Pay attention to the last few rows as I scroll. They became blank)

![4](https://user-images.githubusercontent.com/1334982/42963303-b2d0717a-8b48-11e8-8c58-d57cc9b223bc.gif)

### Expected Behaviour
The rows should be rendered all the time as I scroll up and down.

### Steps to Reproduce (for Bugs)

1. Implement a VirtualTable.
2. Add many rows to it.
3. Scroll fast.

### Environment

- devextreme-reactive: xxx
- react: 16.4.1
- vue: xxx
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.4.0

**Comment by SferaDev** [comment]
Happens the same to me /sub

I'm thinking to add a Loading overlay when adding the rows with a small delay as a temporal workaround.

**Comment by kvet** [comment]
Hi,

We could not reproduce the issue on our side. Is the bug reproducible on the following demo: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/?

If yes, please provide us with detailed info about the operating system, pointer device, and any other circumstances? In addition, provide us with an example where the problem is replicated.

**Comment by franklixuefei** [comment]
@kvet Sorry I was on vacation last week. Yes it does repro for me when I scroll down very fast. It almost happened every time if I drag the scrollbar down very abruptly. However, it only happens when I scroll or drag the scroll bar down, not up.

I actually wonder if there is some kind of race condition where the event listener sometimes fails or is not fast enough to respond to fast scrolling?

And also, I'm not sure if we can improve the overscan a little bit to prevent flickering of the rows while being scrolled? Probably expose that as a prop of `VirtualTable` just like what `React-Virtualized` does.

**Comment by psamim** [comment]
I have the same issue on Firefox in demo page. 
This is on Firefox nightly 67, Archlinux.

![peek 2019-02-12 19-12](https://user-images.githubusercontent.com/1868679/52647578-3bb61080-2efa-11e9-87d5-40137f76af96.gif)

**Comment by SergeyAlexeev** [comment]
Hi @psamim,

I've researched this problem and found the related issue [here](https://github.com/bvaughn/react-virtualized/issues/518#issuecomment-285633211). Please check it out.
