### ISSUE TITLE
Custom cell that always hold the row index

### ISSUE THREAD

**Issue by petruscurtu** [DevExpress/devextreme-reactive#1256]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
Hello! I am using the react grid in a react-redux app. I would like to implement a custom cell that holds the current index of the row. I have tried to provide a column that holds this value. It work well for filtering and fetching data. The problem arises when I sort by a column. As expected the grid sorts the data accordingly. The desired behavior would be that the index column holds the current row even if the data is filtered or sorted. I tried searching for generated columns but to no success. Your help would be much appreciated.

- devextreme-reactive: 1.3.0
- react: 16.4.0
- material-ui: 1.2.1

**Comment by SergeyAlexeev** [comment]
Hi,

We've already discussed the similar question here #885.
