### ISSUE TITLE
[QUESTION] Get row data for selected rows in React Grid

### ISSUE THREAD

**Issue by rajmakda** [DevExpress/devextreme-reactive#1257]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

 #QUESTION:

I have a table of employees with row data coming in through the props like this:
`<Grid rows={this.props.tableData} columns={columns}> ..... </Grid>`
The grid is using selection plugin and the selection array returns only the `row id` in the form of an integer. I am trying to get the `row data` for the rows that are selected and do some further processing on that data. How can I get the row data for all the selected rows? I have not specified any particular `id` for the tableData and it generates the integer on its own.

**Comment by MaximKudriavtsev** [comment]
Hi,
 
In your case, you should define an ID for each data item and pass a function that returns this ID to the [Grid component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/)'s `getRowId` property as shown in the following [example](https://codesandbox.io/s/qxqn2xkzow).
The selected row IDs are available via the [SelectionState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/) plugin's `selection` property.

**Comment by rajmakda** [comment]
Hi,

Thank you for this. It was really helpful, I did end up modifying this a little by handling the `changeSelection` in the component that wraps the table component.
