### ISSUE TITLE
Selection with 3 states including indeterminate

### ISSUE THREAD

**Issue by SferaDev** [DevExpress/devextreme-reactive#1259]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Expected Behaviour

Having a Checkbox that allows 3 states (false, indeterminate, true). We are building an app where either the user or the business updates the grid and selects data.

If the user has checked the checkbox we want to output value true, but if the business layer has checked the checkbox we want it to be checked as indeterminate.

If the RowID is on both arrays then true wins over indeterminate.

### Attempts to achieve this

I took as base the solution to a similar (yet different) issue: https://stackblitz.com/edit/react-deg9yu

But I haven't been able to pass an indeterminate property to the cell, similar to how selected property works.

### Environment

- "@devexpress/dx-react-core": "^1.4.0"
- "@devexpress/dx-react-grid": "^1.4.0"
- "@devexpress/dx-react-grid-material-ui": "^1.4.0"
- "@material-ui/core": "^1.4.0"
- "@material-ui/icons": "^1.1.0"
- "react": "^16.4.1"

**Comment by MaximKudriavtsev** [comment]
Hi,

To achieve this behavior, pass a custom `TableSelectCell` [component](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-select-cell.jsx) to the [TableSelection](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/) plugin's `cellCompopnent` property.
 
In the following [example](https://codesandbox.io/s/x3xz0xrvno), the `state` property has two arrays: `selectionByUser` specifies items selected by a user; `selectionAsIndeterminate` specifies items that have indeterminate state.

**Comment by SferaDev** [comment]
Awesome, it works like a charm! Thanks :)

Maybe all these examples would be useful to be indexed on your website demos.

Congratulations on this excellent library ;)
