### ISSUE TITLE
OnValueChange on editorComponent behaviour inconsistent.

### ISSUE THREAD

**Issue by wederer** [DevExpress/devextreme-reactive#1262]
I am currenctly trying to build a grid which only loads data on "enter" keypress and not while typing. This is necessary, as a lot of data is being handled.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

### Steps to Reproduce (for Bugs)
Please see the following demo:
https://codesandbox.io/s/yj1m5wo739

In this demo I built a **LazyFilterInput** Component which only causes an update of the data in the parent **Demo** component when pressing Enter. onBlur the LazyFilterInput just updates the filters.

This works great, as long as the filters are not empty. As soon as I delete one filter and press Enter (or cause onBlur to fire by leaving field) the **changeFilter** get's no filters at all anymore, even when other columns still have filters.

Scenario 1:

1. Input "France" in first column and press enter
2. Select second Filter and press enter on empty field

 => Filter in first column is ignored

Scenario 2:
1. Input "France" in first column and press enter
2. Input "Reims" in second column and press enter
3. Delete "reims" in second column and press enter  => Filter in first column correctly applied
4. Press enter in empty second column again => filter in first column ignored

### Environment
see demo

**Comment by wederer** [comment]
Thank you very much @MaximKudriavtsev for the fix!

Is there a way for me to get the fix into my current project?
When will you release the next version?

**Comment by MaximKudriavtsev** [comment]
We are going to release the next version soon. The fix will be available there.
