### ISSUE TITLE
How to style IconButton in FilterComponent?

### ISSUE THREAD

**Issue by wederer** [DevExpress/devextreme-reactive#1264]
As far as I can see there is no direct way for me to style the IconButton inside of the FilterComponent in FilterRow.
Is this correct?
If so, I will create a pull request to add a className to IconButton.

Are there plans to add more styling functionality to each component?

Thanks!

**Comment by SergeyAlexeev** [comment]
Hi,
 
Currently, it's possible to customize filter selector icons through the `iconComponent` property of the `TableFilterRow` plugin. As you can see, this property allows replacing an icon inside the `IconButton` component. Would you please provide us with your usecase that requires customizing the `IconButton` directly?

**Comment by wederer** [comment]
For example I want to make the **IconButton** smaller.
I can only customize the **FilterIcon** which is wrapped in **IconButton** which I can not style.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification! We'll discuss how to improve the described customization scenario and update this issue as soon as we have any news.

**Comment by wederer** [comment]
Awesome thanks!

**Comment by Krijovnick** [comment]
We've released the [1.8.0](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.8.0) version containing described changes.
