### ISSUE TITLE
How to hide expand/collapse option in React Grid Detail Row

### ISSUE THREAD

**Issue by amimas** [DevExpress/devextreme-reactive#1266]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Environment

- devextreme-reactive: 1.4.0
- react: 16.4.1
- browser: Chrome
- material-ui: 1.2.1

Hello,

I'm relatively new to React; still learning by using them in real use cases. However, I am finding the API references of devexpress a little bit difficult to understand to be able to implement any use cases. I believe I have a simple use case but I struggled with getting it working.

I have some data in JSON format. I'd like to display them in a table format. Clicking on each row should expand that row to display more details.

I was able to get the above use case implemented by following this doc, which has source code for an example that matches with the use case mentioned above.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/detail-row/

In my case, some of the rows does not have any data for details. So, I needed to disable the control/button that allows expanding or collapsing a row. I reviewed the following API reference and knew that I needed to use `toggleCellComponent` but it wasn't really clear on how to implement it.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail/

I searched the issues in this repository and came across #780 where someone posted following example that does exactly what I described above.
https://stackblitz.com/edit/react-dm4bxe?file=index.js

I tried to follow the example and managed to get that working but to be honest, I don't yet understand how this worked. I don't think I would have been able to figure it out on my own. Even though it worked functionally, I see the following warning in the console of Chrome's Developer Tool. It seems the above example generates the same warnings:

```
Warning: Received `false` for a non-boolean attribute `expanded`.

If you want to write it to the DOM, pass a string instead: expanded="false" or expanded={value.toString()}.

If you used to conditionally omit it with expanded={condition && value}, pass expanded={condition ? value : undefined} instead.
    in td (created by TableCell)
    in TableCell (created by WithStyles(TableCell))
    in WithStyles(TableCell) (created by TableStubCellBase)
    in TableStubCellBase (created by WithStyles(TableStubCellBase))
```
How do I fix it so that I don't have this warning anymore? Here's what my component's render method looks like. Is there a better way for me to conditionally hide/show the expand/collapse button?

```javascript
    render() {
        const {eventData} = this.props;
        const columns = [
                { name: 'date', title: 'Date' },
                { name: 'eventCount', title: 'Total Events', getCellValue: row => (row.events.length)}    
        ];

        const rowHasDetails = row => row.events.length > 0;

        return (
            <Paper className="mergeReportTableByDay">
                <Grid rows={eventData} columns={columns}>
                    <RowDetailState />
                    <Table />
                    <TableHeaderRow />
                    <TableRowDetail 
                        contentComponent={this.RowDetail}
                        toggleCellComponent={(data) => 
                            rowHasDetails(data.tableRow.row) ? (
                                <TableRowDetail.ToggleCell {...data} /> 
                            ) : ( <Table.StubCell {...data}/> )
                        }
                    />
                </Grid>
            </Paper>
        );
    }

    RowDetail = ({ row }) => (
       <div>Details of {row.events.title} on {row.date}</div>
    );
```

**Comment by MaximKudriavtsev** [comment]
Hi,

To disable a command button, use the [TableRowDetail](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail/) plugin's `toggleButtonComponent` component. See this [example](https://codesandbox.io/s/z6zkq1nxkx) for more information.

**Comment by amimas** [comment]
Thank you for your example. It seems a bit more simpler than the other example I followed and I don't have the warning anymore either.

You have the following function that decides whether the expand button is enabled or not. Why does it have multiple properties(i.e. `row` and `restProps`)? I noticed if I don't include `restProps`, I cannot expand the rows that have expand button enabled.

```javascript

const ToggleCellComponent = ({ row, ...restProps }) => {
  if (row.isExpand)
    return <TableRowDetail.ToggleCell row={row} {...restProps} />;
  return (
    <TableRowDetail.ToggleCell
      style={{
        pointerEvents: "none",
        opacity: 0.5
      }}
    />
  );
};
```

**Comment by MaximKudriavtsev** [comment]
In the function above, I use the [Spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax). You can find more information about React `restProps` in this [article](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes).
 
In the current example, `restProps` contains the `TabRowDetail.ToggleCell` component's all [propertyes](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail/#tablerowdetailtogglecellprops) except for row.
