### ISSUE TITLE
Expand/Collapse all Detail Rows

### ISSUE THREAD

**Issue by glenpadua** [DevExpress/devextreme-reactive#1275]
I have a Grid with the Detail Row plugin and would like to add a button that can toggle between expanding/collapsing all the rows. I understand that I'd have to use the `toggleDetailRowExpanded` Action to achieve this but I'm not too sure how to go about using the export. 

I saw this example for reference but wasn't able to equate the same for this purpose - https://stackblitz.com/edit/react-p3fueb?file=index.js

**Comment by kvet** [comment]
Hi.

Here is an example: https://stackblitz.com/edit/react-p3fueb?file=index.js. I am using a template that intersects the 'heading' row and the 'detail' column. I used the 'toggleDetailRowExpanded' action to toggle expanded detail rows.

**Comment by MaximKudriavtsev** [comment]
The updated example https://codesandbox.io/s/kk2jnnyyn5
