### ISSUE TITLE
Localization feature in Vue grid

### ISSUE THREAD

**Issue by abdullah-abunada** [DevExpress/devextreme-reactive#1276]
Hi all,

I'm using Vue.js Grid but I cant find localization feature like React grid.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] Vue Grid

**Comment by MaximKudriavtsev** [comment]
Hi,

Vue Grid has the same localization API as React Grid. See the Localization Messages section in the required plugin's API referece (for example, [Localization Messages in DxSearchPanel](https://devexpress.github.io/devextreme-reactive/vue/grid/docs/reference/search-panel/#localization-messages)).

[This](https://codesandbox.io/s/8k6zk6o582) example demonstrates how to use localization messages.
