### ISSUE TITLE
Getting Memory Leak Warning in SortingState and PagingState Components.

### ISSUE THREAD

**Issue by srikar237** [DevExpress/devextreme-reactive#1290]
Hi,
I am using React Grid. I am rendering the grid component with Sorting and Paging using a Higher order Component and whenever i click on corresponding buttons, i see that it gives the following Warning.

**Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SortingState**
**Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in PagingState**

Thanks,
Srikar B.

**Comment by kvet** [comment]
Hi.

The issue is not reproduced in any of our demos. Can you provide us with an example that reproduces the problem?

**Comment by srikar237** [comment]
Hi,

I will brief you what i am doing, 

I have a higher order component, to display either grid or loading. i have not seen this when i did not use higher order component.

Can you check on that... 

i also have a use case where i need to hide edit and delete buttons for specific rows... how can i achieve that.?

**Comment by srikar237** [comment]
class CommonContainer extends React.PureComponent {
    componentDidMount() {
        this.props.dispatch(UserActions.invokeWatcherSagasWithData(
                            getUserlist.REQUESTED,
                            this.props.legacyData
                        ));
    } 
    constructor(props) {
        super(props);  
    }    

    render() {
        const WrappedComponent = this.props.wrapppedComponent;
        const Wrapper = this.props.apiCallState === apiCallActions.SUCCESS ? (
            <WrappedComponent legacyData={this.props.legacyData} />
          ) : (
            this.props.apiCallState === apiCallActions.START ? (
                <div style={{ marginLeft: '45em', marginTop: '15em' }}>
                    <PulseLoader
                        color={'gray'} 
                        loading={true} 
                        size={18}
                        margin={'10px'}
                    />
                </div>                                
              ) : (
                <Error />
              )            
          );

        return (
            <div>
                {Wrapper}
            </div>
        );   
    }
}

**Comment by kvet** [comment]
I'm afraid that the information you provided is not enough. Please send us an example. You can start with the example form the "Try Out The React Grid" section in the following guide: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/

Here is a link to the question about hiding action buttons: https://github.com/DevExpress/devextreme-reactive/issues/689
