### ISSUE TITLE
[Typescript] wrong type for onCommitChanges ChangeSet parameter

### ISSUE THREAD

**Issue by JavierLight** [DevExpress/devextreme-reactive#1295]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

EditingState prop `onCommitChanges` passes a parameter of type `ChangeSet`

### Expected Behaviour

EditingState prop `onCommitChanges` should pass a parameter of type `ChangeSet[]`

### Steps to Reproduce (for Bugs)

**I guess this only happens for Typescript.**

From `node-modules/@devexpress/dx-react-grid/dx-react-grid.d.ts`:

```
export interface EditingStateProps {
// the rest of props are ok
  /** Handles row changes committing. */
  onCommitChanges: (changes: Array<ChangeSet>) => void;
}
```

From the React Grid own docs ([editing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/)):

```
<EditingState
           //the rest of props are ok
            onCommitChanges={this.commitChanges}
          />
```

```
 commitChanges({ added, changed, deleted }) { //This is not an array of ChangeSet but a ChangeSet
```

I'm not sure how the typescript file is being generated but I could try to find out and open a PR if you find this bug easy to solve. If that's the case it'd be great to get a hint.

**Comment by kvet** [comment]
Hi.

We've recently fixed the bug. Here is the link to the PR: https://github.com/DevExpress/devextreme-reactive/pull/1291
