### ISSUE TITLE
How to set dynamic height (and width) for the React Grid (inside flexbox)?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1304]
I have the page layout that resembles the nest flexboxes from the answer of https://stackoverflow.com/questions/51769036/why-nested-flexboxes-are-not-working-in-chrome - I would like to put React grid inside the 'content 2' div/flexbox are which smoothly consumes all the remaining screen place, so - I would like that React grid smoothly consumes all the remaining screen place (i.e. all screen place that is not consumed by the fixed parameters panel, fixed buttons/commands and navigation panels and so on - i.e. app layout with maximum effort not to allow browser scrolls to appear, especially to remove the vertical browser scrolling) and that React grid creates/removes inner scrolls accordingly. Is such dynamic resizing (especially vertical one) possible and how to achieve it - e.g. with the additional class names etc.

**Comment by kvet** [comment]
Hi.
 
Have you seen the following demo: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#stretching-out-to-parent-element-size?
 
I also want to mention the there is a small limitation in the current realization. We discussed it here: https://isc.devexpress.com/Thread/WorkplaceDetails/T661035. We are planning to fix it soon.

**Comment by alex153410** [comment]
Is there way how can I set up demonstration example with React Grid, e.g. in JSFiddle or in similar service?

**Comment by alex153410** [comment]
OK, I see, CodeSandbox is the right answer.

**Comment by alex153410** [comment]
CodeSandBox shows React Grid, but, unfortunately, the Grid styles are not applied, e.g. https://codesandbox.io/s/38y8x46y86 One can see that there is no borderlines in this sandbox and that there is no constraints on the grid height. Such minimum/maximum constraints on the Grid height appear in the usual use of the Grid (outside sandbox).

**Comment by kvet** [comment]
We've removed redundant markup from the Grid. So, now it is possible to customize all components.
