### ISSUE TITLE
double-click on a column separator resize to maximum

### ISSUE THREAD

**Issue by RahavLussato** [DevExpress/devextreme-reactive#1309]
Hi,
I thought about a cool and small feature that you could do with resizeable columns.
Double-click on a resizeable column separator, which will maximize the column next to it.
just like in excel.

**Comment by peterzebird** [comment]
Do you have an idea how this could be currently done ?
Thanks.

**Comment by LazyLahtak** [comment]
Hi

This scenario can be implement with the controlled mode. For this, you need to define the custom TableHeaderRow`s cellComponent with the onDoubleClick event. You can create ref to the Grid's container, get its width and calculate the new width of the column. Also, you can define a constant width of the container.

Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-4ruuj) illustrating how to do that with ref.
