### ISSUE TITLE
The container of VirtualTable overflows enclosing flexbox in Firefox

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1312]
Here is the example code: https://codesandbox.io/s/yk6pk8zqlx - it is React Bootstrap 4 grid. The page has header and footer DIV elements with the fixed size and all the remaining area should be taken by the grid. The remaining area can change due the the resize (minimization, maximization, resize) of the browser program. If necessary, grid should create inner scroll which keeps the header row in fixed position, but which scrolls the body rows. It is required, that the browser scrolls should never appear, if the height of the browser tend to minimum, then the inner scroll in grid should appear. In practice browser scroll can appear when the remaining space is smaller than the minimum size of the grid, that is fine.

### Current Behaviour
Run of the codebox in Firefox demonstrates the incorrect behaviour - the enclosing DIV overflows the enclosing flexbox - more on this below. 

### Expected Behaviour
Run of the codebox in Chrome demonstrates the correct behaviour. We don't need support for Edge. The internal browser in codebox incorrectly shows the header rows as being transparent, we ignore this codebox behaviour, we expand internal browser to the full browser view and then the header row is with expected background.

### Steps to Reproduce (for Bugs)
Use codebox https://codesandbox.io/s/yk6pk8zqlx

One can observe that codebox example creates the following tree both in Chrome and in Firefox:
DIV flex-area
     DIV d-flex flex-column
          DIV position: relative; display: flex; flex 1 1 auto;
               DIV table-responsive dx-g-bs-4-table-container
                    TABLE table mb-0 dx-g-bs4-table dx-g-bs4-table-head
                    TABLE table mb-0 dx-g-bs4-table

One can observe that in Chrome (which provised the correct rendering) all the components in the tree starting from '**DIV flex-area**' and ending with '**DIV table-responsive dx-g-bs-4-table-container**' have the constrained height - i.e. heigh that is more or less equal the the remaining browser space, e.g. 780 or 776px. And only '**TABLE table mb-0 dx-g-bs4-table**' have the big heigh or >1600px and that means that vertical scroll is created between **DIV table-responsive dx-g-bs-4-table-container** and **TABLE table mb-0 dx-g-bs4-table**. That is fine.

Firefox has different rendering: Firefox assigns then remaining height (780px) to **DIV flex-area only**. And Firefox assign full 1668px to the enclosing container **DIV d-flex flex-column already**. And it create the overflow, which destroys the inner scroll of the create and brings up the browser scroll, i.e. all the hierarchy is destroyed. **Apparently some fine tuning for  _DIV d-flex flex-column_ is required in Firefox.**

**Comment by kvet** [comment]
Hi,

I've already answered you here: https://github.com/DevExpress/devextreme-reactive/issues/1304. We are aware about the limitation and will fix it in the next release.
