### ISSUE TITLE
"Proxy is undefined" error in IE11 in version 1.5.0

### ISSUE THREAD

**Issue by wederer** [DevExpress/devextreme-reactive#1314]
### I'm using ...

- [X] React Grid

### Current Behaviour
Error in Console: "Proxy is undefined" and Grid is not loaded.

### Steps to Reproduce (for Bugs)
Open any Grid demo with current version (1.5.0) in IE11.
(e.g. https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/)

This bug was introduced somewhere between 1.3.0 and 1.5.0.
Probably with commit: https://github.com/DevExpress/devextreme-reactive/commit/9b7c82db9a5c249f67e74a90e95e74e7248b1cea

**Comment by kvet** [comment]
Hi.

We are aware of the problem and have already fixed it: https://github.com/DevExpress/devextreme-reactive/pull/1288. We will release the fix it in the next release.

**Comment by wederer** [comment]
@kvet Thank you for your answer. Have you already planned when you are going to publish the next release?

**Comment by kvet** [comment]
We are planning to release the next version by the end of this week.
