### ISSUE TITLE
Change standard font color

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1316]
Is possible change the default font color in all table.
The standard color for text in row, column and the check box is:  rgba(0, 0, 0, 0.54);

If I want set all to red, where is the solution?

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi,

Use `material-ui`  [ThemeProvider](https://material-ui.com/customization/themes/#theme-provider) to change the default palette.

This [example](https://codesandbox.io/s/xpy26w17rz) demonstrates how to color all text within a table with `red`.

**Comment by ccamusso** [comment]
Exists a solution with out using material-ui?
And work with Pagination component?

**Comment by MaximKudriavtsev** [comment]
For now, you can use custom plugin components. See our [Fundamentals](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/) guide for more information.

Unfortunately, our `Pagination` component does not provide useful appearance customization. We are going to improve it in future releases.
