### ISSUE TITLE
Creating custom theme package

### ISSUE THREAD

**Issue by mrijke** [DevExpress/devextreme-reactive#1318]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid (with TypeScript)
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I'm evaluating the Grid component and I need to create my own 'render' classes akin to for example `dx-react-grid-bootstrap3`, because we are using a different UI framework.
I'm following the example of `dx-react-grid-bootstrap3`, and making my own `<TableBase>` component like so:

```ts
<TableBase
      tableComponent={TableComponent}
      headComponent={TableHead}
      bodyComponent={TableBody}
      containerComponent={BasicContainer}
      cellComponent={TableCell}
      rowComponent={TableRow}
      noDataCellComponent={TableNoDataCell}
      noDataRowComponent={NoDataTableRow}
      stubHeaderCellComponent={TableStubCell}
      stubRowComponent={NoDataTableRow}
      stubCellComponent={TableStubCell}
/>
```
However, the `dx-react-grid-bootstrap3` also defines the `layoutComponent` prop.
I'm missing that in the TableBase component above and it causes a rendering issue in the browser:
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `TemplateConnector`.
    at invariant (invariant.js:42)
<snip>

The above error occurred in the <TemplateConnector> component:
    in TemplateConnector (created by Table)
    in TemplatePlaceholder (created by Table)
    in TemplatePlaceholder (created by GridCore)
    in div (created by BasicContainer)
    in BasicContainer (created by GridCore)
    in TemplatePlaceholder (created by PluginHost$$1)
    in PluginHost$$1 (created by Grid)
    in Grid (created by DummyTableComponent)
```

I'm not able to define that here, because the TypeScript typings say that `layoutComponent` is not a valid prop on `TableProps`. Furthermore, even if I were to be able to pass a `layoutComponent` , I cannot import the 'core' layout components like `dx-react-grid-bootstrap3` is doing - probably again due to the TypeScript definitions:
```js
import {
  TableLayout as TableLayoutCore,
  StaticTableLayout,
} from '@devexpress/dx-react-grid';
```
Any tips on creating a custom render classes while still using TypeScript?
Thanks in advance for your consideration!

### Environment
- devextreme-reactive: 1.5.1
- react: 16.4.1

**Comment by kvet** [comment]
Hi.

Thank you for reaching out to us. We don't provide public information about creating custom skins, because this API is unstable and can change in the future. We have plans to make it public but I can't give you any estimate as to when we will accomplish this.  

At the same time, it is possible to create a custom skin even in TypeScript. I've prepared a simple example for you: https://codesandbox.io/s/6x2r9zpr7w. You need to slightly extend our type definitions.

It would be great to hear from you once you are done with this task.
