### ISSUE TITLE
Hide horizontal scroolbar

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1322]
Is possible in VirtualTable hide horizontal scrollbar?

Carlo

**Comment by kvet** [comment]
Hi.

Can you describe your scenario in greater detail?

Horizontal scrolling is visible only when the sum of column widths is greater than the table width.

**Comment by ccamusso** [comment]
Yes,
the sum of column widths is greater of table width but I do not want to remove the columns and I would like in some cases to hide the horizontal scrollbar.
Is possible?

**Comment by kvet** [comment]
You can set a column's width. Or hide some columns.

**Comment by ccamusso** [comment]
I prefer hide scroll bar, is possible?

**Comment by kvet** [comment]
You can pass the `overflow: hidden` style to the containerComponent of the Table or the VirtualTable plugins.
