### ISSUE TITLE
How to make included rows in tree mode?

### ISSUE THREAD

**Issue by mathetes** [DevExpress/devextreme-reactive#1323]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I made TreeData component (https://codesandbox.io/s/wk6m7y74wl). 
### Expected Behaviour
Show me how to make sub rows in 3 or 4 levels.

- devextreme-reactive: xxx
- react: xxx
- vue: none
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

**Comment by kvet** [comment]
Hi.

Please see the following examples: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#basic-setup.

In general, there are 2 ways:
- using a parent-child connection with ids
- nested data structure
These two ways are shown in the demos. Take a close look at the 'getChildRows' method.
