### ISSUE TITLE
Why the CSS classes and the styles of the grid's inner elements depend on the context?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1326]
I have codesandbox https://codesandbox.io/s/w68xyz9vxw whose HTML element tree identically repeats the component tree of my application. 

Here is the component tree of the code in the sandbox:
![with_classes_codesandbox](https://user-images.githubusercontent.com/35434323/44262548-1767c880-a224-11e8-95ed-7511085aab89.png)

And here is the component tree of the code in my development environment:
![without_classes_app](https://user-images.githubusercontent.com/35434323/44262550-19318c00-a224-11e8-8464-490c742b1ca3.png)

One can see that while the component tree and styles are identity, there are differences of the classNams and styles of the inner elements of the grid. The inner <DIV> elements of the codesandbox example have class names 'd-flex flex-column' and also styles 'display: flex', but the inner <DIV> elements of the development code have no such class names. This can explain why the code in sandbox behaves differently than in development environment. Why those classnames and styles are getting removed from the inner elements of the grid?

Codesandbox has 1.5.1 (latest) version grids, and my development environment has the latest grid versions as well:
```
+-- @devexpress/dx-react-core@1.5.1
| +-- @devexpress/dx-core@1.5.1
| `-- prop-types@15.6.2
+-- @devexpress/dx-react-grid@1.5.1
| +-- @devexpress/dx-grid-core@1.5.1
| `-- prop-types@15.6.2
+-- @devexpress/dx-react-grid-bootstrap4@1.5.1
| +-- classnames@2.2.6
| `-- prop-types@15.6.2
```

**Comment by kvet** [comment]
Hi.

The Grid in the bootstrap theme doesn't have any context dependencies.

I am not sure, but maybe the problem is in your environment? Also, I see that you disabled javascript.
