### ISSUE TITLE
[Bug] React Grid regressions in version 1.6.0

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#1329]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I'm mainly dealing with remote date scenario. In previous versions (<=1.5.1), everything worked as expected. After upgrading to v1.6.0, problems start to surface.
1. Upon data retrieval, the grid is empty, even though the pager shows that I actually retrieved data from the server. I inspected the network activity, and I'm 100% sure that all data was retrieved. After navigating to other pages and navigate back, the grid data occured. Please note that by "navigating to other pages", I mean navigating to other UI router routes (Mine is a SPA). Upon navigating back, the data appeared, without doing any re-fetch from the server, because I cached the data.
2. Column resizing becomes really chunky and weird, which I believe is because of the resizing animation. Is there a way to disable resizing animation? When the table is complex, for example, holding a bunch of rows with nested component in the cells, resizing columns with animation is really ugly.

**Please note that I made ZERO changes to my codebase after bumping up to v1.6.0, and everything worked perfect in v1.5.1**

### Expected Behaviour
Expect same behavior as in v1.5.1.

### Steps to Reproduce (for Bugs)

![image](https://user-images.githubusercontent.com/1334982/44284592-18dec400-a217-11e8-9168-5215a3914fb9.png)

I also recorded two videos showing the problems.
First video shows the regression, and the second one shows the expected behaviour (<= 1.5.1)

[Regressions](https://youtu.be/3hAcQD1bgA4)
[Expected Behavior](https://youtu.be/KOvjsRtUmEU)

### Environment

- devextreme-reactive: xxx
- react: xxx
- vue: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by kvet** [comment]
Hi.
 
We've published the 1.6.1 version. The issue should be resolved. Please check it.
