### ISSUE TITLE
Prefiltering in filteringstate no longer working

### ISSUE THREAD

**Issue by carambolas** [DevExpress/devextreme-reactive#1332]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I've prefilled the filtering of a column on loading a table, but I can't remove the prefilled value with backspace

### Expected Behaviour
I expect the prefilled value to be removable via backspace as it was in 1.5.0

### Steps to Reproduce (for Bugs)

https://codesandbox.io/s/l7wz7m3xpm

I've prefilled the filteringstate with a value but I can't remove this value with backspace since the new update to 1.6.0. I reproduced it in the codesandbox above

### Environment

- devextreme-reactive: 1.6.0
- react: 16.4.2
- vue: xxx
- browser: chrome latest
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.5.0

**Comment by kvet** [comment]
Hi.
 
We've published the 1.6.1 version. The issue should be resolved. Please check it.

**Comment by carambolas** [comment]
All I get now is:
Could not find module in path: '@babel/runtime/7.0.0-beta.42/helpers/interopRequireDefault' relative to '/node_modules/recompose/wrapDisplayName.js'

**Comment by carambolas** [comment]
The above issue seems to be an issue with codesandbox. I've tried 1.6.1 on my local version, however, the issue with prefilling is still there :(

**Comment by kvet** [comment]
I found that you are using filtering in controlled mode but don't listen to its change event. I've modified your example: https://codesandbox.io/s/n5o39qpnj

If you want to use the uncontrolled mode, specify the `defaultFilters` property instead of `filters`.

**Comment by carambolas** [comment]
Thank you very much, that did the trick!
