### ISSUE TITLE
Customize paging styling

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1335]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
How can I add a className for PagingState? 

### Expected Behaviour
Expect to override the Bootstrap css.

### Environment

- devextreme-reactive: xxx
- react: xxx
- vue: none
- browser: none
- bootstrap: xxx
- react-bootstrap: xxx
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

The [PagingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-state/) plugin doesn't render UI elements. That's why you can't add a class name to this plugin. Would you please provide more details about your use case? What exactly CSS class do you want to customize?

**Comment by susuwatari2** [comment]
I have several CSS classes with different styling. Pagination has border by bootstrap default. I want to apply another class with no border, so it does not use inline styling.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification. In this case, I suggest you add a custom CSS class to the paging panel container using the `containerComponent` property of the [PagingPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-panel/) plugin.

This [sample](https://codesandbox.io/s/6x681rz74n) shows how to do it.
