### ISSUE TITLE
Failed to minify the code:  dx-chart-core.es.js:529

### ISSUE THREAD

**Issue by ankitshukla065** [DevExpress/devextreme-reactive#1337]
I am using Devexpress react chart (bootstrap 4). It's all working fine in Dev environment but when i run "npm run build", the process stops with error:-

**Failed to minify the code from this file:
        ./node_modules/@devexpress/dx-chart-core/dist/dx-chart-core.es.js:529**

I am using create-react-app template and react version 16.4
I have all the dependencies installed

**Comment by alexey-semikozov** [comment]
Hello ankitshukla065,
We have fixed it: #1294 and released 1.6.1 packages with this fix. Please change your packages version.
