### ISSUE TITLE
Edit Column reordering

### ISSUE THREAD

**Issue by piyushSinghalDemo** [DevExpress/devextreme-reactive#1342]
i am using vue grid chrome browser

I have edit column (new, edit,delete) in left but we want to align this column to end or right side in the grid how can i achieve this feature.Ex-
We have 2 column then i am getting column 1 as editing column, we want to reorder this columns and want to align editing column as column 2

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, we don't provide a public API for implementation the scenario you described. At the same time, we've already discussed a similar [question](https://github.com/DevExpress/devextreme-reactive/issues/287) in the context of the DevExtreme React Grid. You can use the same approach for Vue Grid. I've created a [sample](https://codesandbox.io/s/lyq1vq0m2l) that shows how to do it.

**Comment by piyushSinghalDemo** [comment]
@SergeyAlexeev  Thanks , It works good thanks a lot.
