### ISSUE TITLE
Typescript error with IntegratedSummary

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1343]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I got TypeScript error like this

`error TS2322: Type '{}' is not assignable to type 'IntegratedSummaryProps'.
  Property 'calculator' is missing in type '{}'.`

when trying to use `<IntegratedSummary />`

### Environment

- typescript: 3.0.1
- devextreme-reactive: 1.6.1
- react: 16.4.2
- vue: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.5.0

**Comment by kvet** [comment]
Hi.

Thank you to reaching out to us. I've reproduced the bug.
