### ISSUE TITLE
Sorting is broken then array of object values are non-existent for some rows

### ISSUE THREAD

**Issue by rememberlenny** [DevExpress/devextreme-reactive#1344]
Posted here: [https://www.devexpress.com/Support/Center/Question/Details/T666602/devextreme-reactive-table-sorting-null-values-broken](https://www.devexpress.com/Support/Center/Question/Details/T666602/devextreme-reactive-table-sorting-null-values-broken)

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

### Current Behaviour

We found an issue with the SORTING feature on the ReactGrid table.

Currently, we are rendering rows of content based on an array of objects. Some of these objects are missing key/values and are expected to render empty.

The sorting breaks when we process a SORT on a column of values with empty cells. What seems to be happening is that the sort works between the empty cells, but then breaks between the empty cells. 

For example, the following array:

```
[JavaScript]
// Unsorted 
// Notice some objects contain param value, while all contain a metric value
[
  {
    metric: f,
  },
  {
    metric: c,
    param: 3
  },
  {
    metric: d,
    param: 5
  },
  {
    metric: e,
    param: 4
  },
  {
    metric: b
  },
  {
    metric: a,
    param: 1
  }
]
```

will render ascending as:

```
[JavaScript]
// Current asc on param (ERROR)
// Notice the objects without a param value are not being sorted correctly
[
  {
    metric: a,
    param: 1
  }
  {
    metric: b
  },
  {
    metric: f,
  },
  {
    metric: e,
    param: 4
  },
  {
    metric: d,
    param: 5
  },
  {
    metric: c,
    param: 3
  },
]
```

or descending:

```
[JavaScript]
// Current desc on param (ERROR)
// Notice the objects without a param value are not being sorted correctly
[
  {
    metric: f,
  },
  {
    metric: e,
    param: 5
  },
  {
    metric: d,
    param: 4
  },
  {
    metric: c,
    param: 3
  },
  {
    metric: b
  },
  {
    metric: a,
    param: 1
  }
]
```

### Expected Behaviour

```
[JavaScript]
// Asc on param and treating the metric-only objects as GREATER or LESS than the other values
[
  {
    metric: a,
    param: 1
  }
  {
    metric: c,
    param: 3
  },
  {
    metric: e,
    param: 4
  },
  {
    metric: d,
    param: 5
  },
  {
    metric: b
  },
  {
    metric: f,
  },
]
```

OR

```
[JavaScript]
// Desc on param and treating the metric-only objects as GREATER or LESS than the other values
[
  {
    metric: f,
  },
  {
    metric: b
  },
  {
    metric: e,
    param: 5
  },
  {
    metric: d,
    param: 4
  },
  {
    metric: c,
    param: 3
  },
  {
    metric: a,
    param: 1
  }
]
```

### Environment

- devextreme-reactive: `1.4.0`
- react: `16.3.1`
- vue: none
- browser: `Chrome Version 68.0.3440.106 (Official Build) (64-bit)`
- bootstrap: none
- react-bootstrap: none
- material-ui: `1.5.1`

**Comment by kvet** [comment]
Hi.
 
Thank you for reaching out to us. I've reproduced the bug. Here is a link to it: https://codesandbox.io/s/13qvz1qqzl

**Comment by rememberlenny** [comment]
@kvet Incredibly impressed. Thank you.
