### ISSUE TITLE
how to add select with input in edit or create Row

### ISSUE THREAD

**Issue by piyushSinghalDemo** [DevExpress/devextreme-reactive#1346]
i am using vue grid chrome browser.

Currently i am getting input only on edit column(new, edit, delete), however on a lot of places we need select with input, So on edit or creating row can we get select with input.

**Comment by SergeyAlexeev** [comment]
Hi,
 
I'm afraid I don't understand your question. Would you please clarify what "input" you are talking about?

**Comment by piyushSinghalDemo** [comment]
for example we are using 'dx-editing-state' that time if we do click on new or edit link then in each cell we get textbox to insert data, is there any possibility that we can get select with input in cell?

![input](https://user-images.githubusercontent.com/30336741/44510992-02979480-a66b-11e8-96a3-724c9ad6f774.PNG

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information.
Please refer to this [demo](https://devexpress.github.io/devextreme-reactive/vue/grid/demos/featured/data-editing/) to see how to use a custom editor in the `TableEditRow` plugin.

**Comment by piyushSinghalDemo** [comment]
@SergeyAlexeev  thanks, this example resolves all my issues.
