### ISSUE TITLE
IE11: Column resize handles are too small

### ISSUE THREAD

**Issue by danpker** [DevExpress/devextreme-reactive#1354]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

In IE11 the column resize handles do not render to the full height of the column header. This is causing issues when combined with Column reordering

### Expected Behaviour

The handles extend to the full height of the column headers, like in other browsers.

### Steps to Reproduce (for Bugs)

1. Visit the [column resizing demo in the docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/) in IE11
2. Hover over a column to show the resizing handles
3. They do not extend to the full height of the column header

### Environment

- devextreme-reactive: 1.6.1
- react: 16.4.2
- browser: IE11

**Comment by SergeyAlexeev** [comment]
Hi,

As you can see in our  [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started#supported-browsers), React Grid doesn't support IE11. It can work in IE11, but some side effects are possible.

**Comment by danpker** [comment]
Does that mean this won't be fixed?

**Comment by SergeyAlexeev** [comment]
For now, we don't have plans to fix it.
