### ISSUE TITLE
Bug in IntegratedSummary

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1355]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I got this error when using Summary Row with an initially empty array as rows
`Cannot read property 'map' of undefined`

The idea is that the initial rows would be empty while waiting for data to be loaded asynchronously.

It works as normal when removing the Summary Row

### Expected Behaviour
 Summary Row would work with empty array.

### Steps to Reproduce (for Bugs)

See: https://codesandbox.io/s/rwm511j8rp

### Environment

- devextreme-reactive: 1.7.0
- react: 16.4.2
- vue: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for pointing out this issue. Your sample doesn't contain a summary row. It looks like you didn't save changes. According to your example, you are using a summary for tree items, aren't you? If so, I can't reproduce the described behavior on my side. Tree summary works as expected with empty rows.

**Comment by vtrphan** [comment]
Hey sorry, i have indeed forgotten to save. I have saved and reproduced the bug. Please check again. Thanks

**Comment by vtrphan** [comment]
Looks like the Summary Row bug will surface when used together with the Grouping Row and the rows data is an empty array
