### ISSUE TITLE
[Question] Case sensitive sorting

### ISSUE THREAD

**Issue by JavierLight** [DevExpress/devextreme-reactive#1356]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

I guess default behavior for sorting is **case sensitive** alphabetical order (asc/desc). Probably I'm missing something because I couldn't find anything in the API to change this to ignore case. Should I override default behavior with `integratedSortingColumnExtensions` ?

In case there is nothing provided by the API an easy example would be great (or something pointing me in the right direction). Thank you very much for your time.

**Comment by SergeyAlexeev** [comment]
Hi,

Yes, you are right. Use the `columnExtensions` property of the `IntegratedSorting` plugin to implement a custom sorting algorithm. See this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting#custom-sorting-algorithm), as well.

**Comment by JavierLight** [comment]
Thanks for the clarification. I saw the demo, but I'm wondering if it would be possible to keep the default sorting algorithm, modifying only the data passed (i.e. converting all passed data to lower case to ensure it is ignored, but keeping row data as it is).

In case it's not possible, I'm wondering if you could point me to the source of your sorting algorithm to avoid redoing it with that small change.

Thanks for your time!

**Comment by SergeyAlexeev** [comment]
Our default sorting algorithm is implemented [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-grid-core/src/plugins/integrated-sorting/computeds.js).
