### ISSUE TITLE
[Question] How to get a list of the list in a TableGroupRow -> cellComponent ?

### ISSUE THREAD

**Issue by kozlikov** [DevExpress/devextreme-reactive#1357]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

https://codesandbox.io/s/qxxkmx43jq

### Expected Behaviour

How to get the number of records in a group ?

### Steps to Reproduce (for Bugs)

I want to get the number of the loaded lines, like the screenshot + sendbox:
![image](https://user-images.githubusercontent.com/13614707/44628564-a4a8cc80-a94a-11e8-8c20-83667bd9c907.png)

Unfortunately, because of Symbol I can not access the current list:
![image](https://user-images.githubusercontent.com/13614707/44628550-5dbad700-a94a-11e8-91a8-62ee624ff160.png)

Please specify how to access the group list?
![image](https://user-images.githubusercontent.com/13614707/44628572-ffdabf00-a94a-11e8-9a3d-f093aa1ff32d.png)

### Environment

- devextreme-reactive: 1.7.0
- react: 16.4.2
- browser: Chrome 68.0.3440.106
- react-bootstrap: 0.32.1

**Comment by SergeyAlexeev** [comment]
Hi,

We've already discussed a similar question in the context of this [issue](https://github.com/DevExpress/devextreme-reactive/issues/813). Also, I'd like to note that we [introduced](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#features) the summary feature. Please refer to this [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/summary-row/). It includes a group row summary sample as well.
