### ISSUE TITLE
Adding custom button to column

### ISSUE THREAD

**Issue by Noobburner** [DevExpress/devextreme-reactive#1364]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] Vue Grid

Hello! I'm experiencing hard time adding custom button or link to column in the table. Is adding your custom buttons even possible here?

**Comment by SergeyAlexeev** [comment]
Hi,

This [demo](https://devexpress.github.io/devextreme-reactive/vue/grid/demos/featured/data-editing/) shows how to use custom buttons in the `DxTableEditColumn` plugin. If you don't use editing and want to add a custom button in a common table cell, use the `cellComponent` property of the [DxTable](https://devexpress.github.io/devextreme-reactive/vue/grid/docs/reference/table/) plugin. This [guide](https://devexpress.github.io/devextreme-reactive/vue/grid/docs/guides/fundamentals#appearance-customization) demonstrates how to do it.
