### ISSUE TITLE
Filter without value

### ISSUE THREAD

**Issue by canarddemagret** [DevExpress/devextreme-reactive#1365]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
I have a filter that removes all rows having a null value or/and empty String in the column. It does not require a value.

I must select the correct icon in the FilterSelector , then add a value (which is unnecessary) in the editorComponent, then press Enter.

### Expected Behaviour
I select the 'NotNullOrEmpty' filter, the filter is applied correctly

### Environment

- devextreme-reactive: 1.7.0
- react: 16.4.0
- material-ui: 1.3.0

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, you can use a custom filter selector component:

```js
<TableFilterRow
  //...
  filterSelectorComponent={FilterSelector}
/>
```
 
Then, use the [onChange](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#tablefilterrowfilterselectorprops) property of this component to handle filter operation changes. In this event you can apply the `notNullOrEmpty` filter operation.

This [sample](https://codesandbox.io/s/z6272z58xm) shows the described approach in action. There I've added the `notNullOrEmpty` filter operation for the `city` column.

**Comment by canarddemagret** [comment]
Hi,

Thanks for your answer,

Your solutions works only if I have only one column that use the filter `notNullOrEmpty`.
In `filterSelectorComponent` or in the `onChange`, I would need the column name.

I use the grid in a generic way and I cannot hard-code the column.
