### ISSUE TITLE
Is there a way to access the headTable?

### ISSUE THREAD

**Issue by Tamakimouto** [DevExpress/devextreme-reactive#1368]
As you know, `position: "sticky"` doesn't work in IE.

A virtual table seems to be made of 2 tables, one for the header and another for the entries. On IE we can instead use a `position: "absolute"` on the header table and put a margin-top on the lower table to get the same "sticky" effect. Replacing the tableComponent seems to affect the 2nd table, how do I add some styling to the upper table?

headComponent doesn't work since it points to the thead within that table.

**Comment by Tamakimouto** [comment]
Got it, you can get to it from a material override.

`
Table: {
    headTable: { 
        position: browser == ie ? "absolute" : "sticky"
    }
}
`

**Comment by kapilpipaliya** [comment]
can you explain more, how to change headTable Style in detail?

**Comment by Tamakimouto** [comment]
[I'm using a feature in Material UI to override it.](https://material-ui.com/customization/themes/#customizing-all-instances-of-a-component-type)

**Comment by kapilpipaliya** [comment]
can you provide full theme code. I tried myself but not working?
