### ISSUE TITLE
Why do Grouping rows have detail rows?

### ISSUE THREAD

**Issue by mruley** [DevExpress/devextreme-reactive#1369]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [X] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
We are currently using the React Grid to produce a table.  We have both grouping and row details in use.  However, at times when we click on the button to expand a row it will produce extra detail rows that are connected to the group rows (I wrote a function to print the connected row object).  Is there a way to prevent the group rows from having their own detail rows?

### Expected Behaviour
Group rows should not produce their own detail rows.

### Steps to Reproduce (for Bugs)
We have a component to print info in the detail row, right now it only returns an detailing of the connected table object.

### Environment
- devextreme-reactive: 1.40
- react: 16.4.1
- browser: Chrome
- bootstrap: 3.3.7
- react-bootstrap: 0.32.1
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,

Your final goal is not clear to me. What do you mean by saying that `Is there a way to prevent the group rows from having their own detail rows?`

Please change my [example](https://codesandbox.io/s/vjyjx31npl) to show your behavior and describe it in greter detail.

**Comment by mruley** [comment]
It's also generating the error **Warning: Encountered two children with the same key, `detail_undefined`** if that might be a clue

**Comment by mruley** [comment]
Here is a copy of my grid table code.  Right now I pass in variables to keep some of the detail rows open when the table renders.  When I go to expand an additional row, that's when I get the error and it suddenly creates multiple new detail rows (instead of just one)

    <CurrencyTypeProvider for={currencyColumns} />
    <EndDateTypeProvider for={enddateColumns} />
    
    <FilteringState filters={[{ columnName: "Visible", value: "True" }]} />
    <SearchState defaultValue="" />
    <IntegratedFiltering />
    <GroupingState
        grouping={[{ columnName: "Company", title: "" }]}
        defaultExpandedGroups={groups}
    />
    <IntegratedGrouping />
    <RowDetailState defaultExpandedRowIds={this.state.expandedRows} />
    <VirtualTable
        CellPadding="0"
        CellSpacing="0"
        height={700}
        columnExtensions={tableColumnExtensions}
    />
    <TableHeaderRow />
    <TableRowDetail contentComponent={this.RowDetail} />
    <TableColumnVisibility hiddenColumnNames={["Visible"]} />
    <TableBandHeader
        CellPadding="0"
        CellSpacing="0"
        cellComponent={this.renderHeaderCell}
        columnBands={columnBands}
    />
    <TableGroupRow
        cellComponent={this.renderGroupCell}
        rowComponent={CustomTableGroupRow}
        CellProps={tableGroupRow}
    />
    <Toolbar />
    <SearchPanel searchPlaceholder="test" />
    <SearchBarModification />
</Grid>

**Comment by mruley** [comment]
Think I might have found the issue.  When I was creating expandedRows variable I was setting the array index to be the same as the value, so when storing a 5 I was saying expandedRows[5] = 5.  I changed this to just pushing the values in so there'd be no gaps in the indexes and it seems to work correctly now.
