### ISSUE TITLE
How to refresh table data from other component?

### ISSUE THREAD

**Issue by Noobburner** [DevExpress/devextreme-reactive#1378]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] Vue Grid

### Current Behaviour
I call loadData() from other component by using refs but it refreshes nothing.

### Expected Behaviour
I call something from other component and it refreshes the table.

### Steps to Reproduce (for Bugs)
My code is equal to example from "Remote Paging" section here:
https://devexpress.github.io/devextreme-reactive/vue/grid/docs/guides/paging/

**Comment by SergeyAlexeev** [comment]
Hi,

As you can see, the `loadData` function contains this code:

```
if (queryString === this.lastQuery) {
  this.loading = false;
  return;
}
```


It helps to avoid unnecessary data loading if a query string isn't changed. So, if you don't change the query string and just call the `loadData` function, it does nothing.

I've created a [sample](https://codesandbox.io/s/kwzw476z15) that shows how to modify the `loadData` function to always load data. I've added the `forceReload` argument. If it's true, data will be always loaded. To see how it works, navigate to the second grid page, then click the `Refresh Grid` button.

**Comment by Noobburner** [comment]
This works. Thanks a lot!
