### ISSUE TITLE
The VirtualScrolling feature looks bad in Edge

### ISSUE THREAD

**Issue by MaximKudriavtsev** [DevExpress/devextreme-reactive#1381]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

`position: sticky` is looking bad on Edge, it is supported but the header is jumping.

### Environment

- browser: Microsoft Edge

**Comment by kvet** [comment]
Currently, there is an issue with virtual scrolling in Microsoft Edge: [sticky elements flicker on scroll](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18769340/). We won't fix this problem as it is related to the browser.
