### ISSUE TITLE
Custom Footer on 1.7.2

### ISSUE THREAD

**Issue by muhammedesadkaya** [DevExpress/devextreme-reactive#1394]
hi there. im using react grid (1.7.2) and bootstrap 4. i want to create custom footer. when i add div in end of the grid, the div shows top of the grid and i want to add column visibility on footer. help pls

**Comment by sodyumist** [comment]
Same issue help us pls

**Comment by SergeyAlexeev** [comment]
Hi,

You can render a column chooser in a grid footer using the [React Core API](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/).

As you can see in our documentation, the `ColumnChooser` plugin [depends](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/) on the `Toolbar` plugin and [renders](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser#plugin-developer-reference) its markup inside the `toolbarContent` template that is placed in a grid header. Well, the idea is moving the `toolbarContent` template from header to footer:

```
<Grid>
  {/* Render nothing in header. */}
  <Template name="header" />
  {/* Render toolbar content in footer. */}
  <Template name="footer">
    <TemplatePlaceholder name="toolbarContent" />
  </Template>
</Grid>
```

This [sample](https://codesandbox.io/s/xo457nponw) shows how to do it.

**Comment by muhammedesadkaya** [comment]
> Hi,
> 
> You can render a column chooser in a grid footer using the [React Core API](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/).
> 
> As you can see in our documentation, the `ColumnChooser` plugin [depends](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/) on the `Toolbar` plugin and [renders](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser#plugin-developer-reference) its markup inside the `toolbarContent` template that is placed in a grid header. Well, the idea is moving the `toolbarContent` template from header to footer:
> 
> ```
> <Grid>
>   {/* Render nothing in header. */}
>   <Template name="header" />
>   {/* Render toolbar content in footer. */}
>   <Template name="footer">
>     <TemplatePlaceholder name="toolbarContent" />
>   </Template>
> </Grid>
> ```
> This [sample](https://codesandbox.io/s/xo457nponw) shows how to do it.

thanks for answer. its working but when i use this code block, my paging gone. what's the trick? :)

**Comment by muhammedesadkaya** [comment]
> The following piece of code overrides the `footer` template that contains a paging panel.
> 
> ```
> <Template name="footer">
>   <TemplatePlaceholder name="toolbarContent" />
> </Template>
> ```
> To keep the paging panel inside a footer, just add the `TamplatePlaceholder` component without a name:
> 
> ```
> <Template name="footer">
>   <TemplatePlaceholder />
>   <TemplatePlaceholder name="toolbarContent" />
> </Template>
> ```
>  
> See the updated [sample](https://codesandbox.io/s/4qymyq1nx0). This [guide](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/rendering-markup#template-overriding) contains additional information about template overriding.

its work. thanks a lot. you saved my day :)

**Comment by muhammedesadkaya** [comment]
hi there again :) also i want to use grouping on header but i pushed the all components to footer with your help. help please :))
