### ISSUE TITLE
Alternate color row in the virtual table

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1407]
Is it possible to alternate color row in the virtual table?

I try this solution, but is not perfect

```
const styles = theme => ({
  tableStriped: {
    backgroundColor: '#fff',
    '& tbody tr:hover': { backgroundColor: '#f5f5f5 !Important' },
    '& tbody tr:nth-of-type(odd)': { backgroundColor: '#f6f8fa' },
    '& tbody tr:nth-of-type(even)': { backgroundColor: '#fff' }}
});
```
Example: https://codesandbox.io/s/ol5mw61ply

Problem:
after scrolling 5 row, Virtual Table remove a first row and colors row are inverted.

Carlo

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, you can use a persistent row index to identify a row. Then, depending on that index, add a specific CSS class for odd rows, for instance. We've already discussed the question about calculating a row index in the context of this [issue](https://github.com/DevExpress/devextreme-reactive/issues/885).

Please refer to this [sample](https://codesandbox.io/s/nz0z8yo4l) as well.

**Comment by ccamusso** [comment]
Is perfect.
Thank you.
