### ISSUE TITLE
default size for TableColumnResizing

### ISSUE THREAD

**Issue by FernandoGOT** [DevExpress/devextreme-reactive#1411]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

When I use the "TableColumnResizing" I need to set an array of objects to "defaultColumnWidths". The problem is that if I load a new column that isnt in the "defaultColumnWidths" array the react app braks.

* This can happen when I'm getting the columns from an API

### Expected Behaviour

I expect to have a default column size, so if I use "TableColumnResizing" and load a column that isn't in the "defaultColumnWidths", it is going to load the new column with the default width and not break the the application

### Steps to Reproduce (for Bugs)

Create a table usaing "TableColumnResizing" and pass "defaultColumnWidths" without one of the columns.

Exemple: https://codesandbox.io/s/nkowk83ynj

### Environment

- @devexpress/dx-react-core: 1.7.2
- @devexpress/dx-react-grid: 1.7.2
- @devexpress/dx-react-grid-material-ui: 1.7.2
- react: 16.4.2
- vue: none
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.0.2

**Comment by FernandoGOT** [comment]
I just saw that someone posted this at [#411](https://github.com/DevExpress/devextreme-reactive/issues/411), but here an better exemple

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
