### ISSUE TITLE
Paging panel buttons are out of alignment with material UI core 3.1.0

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#1413]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

See screenshot:
![screen shot 2018-09-19 at 7 02 28 pm](https://user-images.githubusercontent.com/14972752/45791450-947cc800-bc3e-11e8-87ec-b3995dc953c2.png)

### Expected Behaviour

Arrow buttons and page buttons should be aligned

### Steps to Reproduce (for Bugs)

Use a PagingPanel with `"@devexpress/dx-react-grid-material-ui": "1.7.2"`, (and all other devexpress packages at 1.7.2 as well) and `"@material-ui/core": "3.1.0"` The problem does not exist in 3.0.1.

### Environment

- devextreme-reactive: none
- react: 16.3.0
- vue: none
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: ^3.0.1

Note - This could very well be my fault - I noticed everything looks fine on your demo page, but I see the package.json uses `@material-ui/core": "^3.0.1"`, which will install 3.1.0. When I use MUI 3.0.1, everything looks great as it always have, but if I change to 3.1.0, I see the issue.

Also, if I remove the `height` style from `.Pagination-arrowButton`, the issue disappears. This could obviously be a material issue - please let me know if it seems that way and I can try to open an issue there.

**Comment by sethduncan** [comment]
I have the same issue. This could possibly be related to https://github.com/mui-org/material-ui/pull/12865 ?

**Comment by TheMoonDawg** [comment]
I believe the issue lies in this changeset in IconButton: https://github.com/mui-org/material-ui/pull/12865/files#diff-fde406414bd717fcea45f653b5632078

They switched from resizing the actual component itself to adjusting its padding whenever changing the size of IconButton.
