### ISSUE TITLE
Fixed Columns Not working when using customheader and custom Table Cell

### ISSUE THREAD

**Issue by vijayvmenon** [DevExpress/devextreme-reactive#1421]
I am using a custom header and custom Table Cell. The Fixed Columns are not working then.

Code here  - https://codesandbox.io/s/yjkq7vy4v

Please let me know how I can use fixed columns in combination with custom Headers and Table Cells.

**Comment by MaximKudriavtsev** [comment]
Hi,
 
To keep Fixed Columns default behavior, you should pass the `style` property in all custom components. I changed your [example](https://codesandbox.io/s/8kz3kvoz12) for detailed information.
