### ISSUE TITLE
RTL dragging behavior: Table column resizing\reordering

### ISSUE THREAD

**Issue by yotamberk** [DevExpress/devextreme-reactive#1423]
- [ x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [ x ] React Grid

### Current Behaviour
When using Material-ui table, resizing columns or reordering them causes a drag to the opposite side, and animations are wacky (reversed animations on group switch)  

### Expected Behaviour
To work the same as for LTR table

### Steps to Reproduce (for Bugs)
https://codesandbox.io/s/q756lv960w

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for pointing out that issue. To be honest, currently, we don't guarantee that React Grid works correctly in RTL mode. I've created the related  [issue](https://github.com/DevExpress/devextreme-reactive/issues/1433). Please refer to it to see our progress.
