### ISSUE TITLE
TreeData documentation fix

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1424]
'Remote Data Loading on Demand' example in this page:
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#basic-setup

using this resource:
const URL = 'https://js.devexpress.com/Demos/Mvc/api/treeListData';

but 'treeListData' file not working

Carlo

**Comment by ccamusso** [comment]
You can try to open this page with Chrome:
https://js.devexpress.com/Demos/Mvc/api/treeListData

The result is:
<Error>
<Message>An error has occurred.</Message>
</Error>

**Comment by SergeyAlexeev** [comment]
It's expected behavior of the default ASP.NET MVC ApiController that we are using on the server side. To test the API you can use [Postman](https://www.getpostman.com/), for instance.
