### ISSUE TITLE
Styling the "parent" rows of a TreeData table

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#1427]
I've created a TreeData table using getCellValue to calculate numeric values and DataTypeProviders to style the cells based on the columns data type.

What I would like is to be able to style the "parent" rows with some bolding or background to make the tree data easier to see, especially when horizontally scrolling. Is this possible in the current implementation?

**Comment by thehig** [comment]
You sir, are an absolute legend. No chance I would have figured this out myself

**Comment by MaximKudriavtsev** [comment]
My answer contains a wrong example link. The correct one - https://codesandbox.io/s/0y5nl764w0
