### ISSUE TITLE
React Grid nested tables

### ISSUE THREAD

**Issue by etairi** [DevExpress/devextreme-reactive#1429]
Is it possible to nest tables with React Grid? I want to achieve behavior close to TreeData, but in TreeData columns with similar data are inserted as child rows. But, what I want to achieve is that when a row is expanded, I want underneath it to display another table, with different column names and row values. Can I achieve this nested tables structure in React Grid?

**Comment by SergeyAlexeev** [comment]
Hi,

Are you looking for something like [this](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/redux-integration/)?

**Comment by etairi** [comment]
@SergeyAlexeev Yes, exactly like that! Thank you!
