### ISSUE TITLE
Make default Devextreme skins available

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#143]
Bootstrap and Material UI are all good and well, but I'm very much a fan of the simple Light and Dark (as well as compact) DevExtreme themes that ship with the standard jQuery etc. version.

Can we get TableViews implementing those themes? Or are they already there and I've missed them?

Gracias,

**Comment by SergeyAlexeev** [comment]
Hi, 

DevExtreme React Grid supports only Bootstrap and Material UI themes. If you are looking for something else, look at [Bootswatch](https://bootswatch.com/), for instance. This site provides free themes for Bootstrap. Well, you can choose a custom theme there. 

I've created [the sample](http://plnkr.co/edit/9XQ426uZwwKcEhV76r0L?p=preview), that demonstrates how to use the 'Darkly' theme with DevExtreme React Grid.
