### ISSUE TITLE
Select all members of a group

### ISSUE THREAD

**Issue by JavierLight** [DevExpress/devextreme-reactive#1438]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

I'm wondering if there is a hidden option in your API or workaround to allow selecting all elements in a group. I could only achieve to play with `IntegratedSelection` and `IntegratedGrouping` plugins order, to allow selecting all elements for expanded groups. I would like to display a select all button in each group: 

![image](https://user-images.githubusercontent.com/7041691/46141226-9d2f5880-c253-11e8-9622-bfb46d8a34a1.png)

Thanks for your time 😄

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, we don't provide an out-of-the-box functionality for your scenario. However, you can completely override the `cellComponent` property of the [TableGroupRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-group-row/) plugin. Please note, in this case, you need to implement a whole cell component including a toggle button, a column name, etc. We also have a similar built-in functionality in the  [TableTreeColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data#configuring-hierarchical-selection-controls) plugin. Does it meet your needs?

**Comment by JavierLight** [comment]
Hello,

Thank you very much for the clarification. We will use one of the suggested workarounds.

I'm closing the issue 😄
