### ISSUE TITLE
Missing several type definitions for dx-react-grid

### ISSUE THREAD

**Issue by StJohn3D** [DevExpress/devextreme-reactive#1441]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
Unable to import the last 4 exports because they are missing from `dx-react-grid.d.ts`.  I get compilation errors with error message:
> [ts] Module '"_...path..._/node_modules/@devexpress/dx-react-grid/dist/dx-react-grid"' has no exported member `export name`

Those 4 missing exports are `TableLayout,
  VirtualTableLayout,
  StaticTableLayout,
  GroupPanelLayout`

I first discovered this bug while trying do the following:
```tsx
import { GroupingPanel, GroupPanelLayout } from '@devexpress/dx-react-grid'
```

There's no issue importing `GroupingPanel`, but `GroupPanelLayout` is marked as not found and causes compilation errors. I've confirmed that the 4 missing exports listed above are present in both the `dx-react-grid.es.js` & `dx-react-grid.umd.js` files in dist. They are only missing in the `dx-react-grid.d.ts` file.

### Expected Behaviour
Should be able to import all exports of `dx-react-grid` in a typescript project.
Should be able to import `TableLayout,
  VirtualTableLayout,
  StaticTableLayout,
  GroupPanelLayout`

### Steps to Reproduce (for Bugs)
test.ts
```tsx
import { GroupingPanel, GroupPanelLayout } from '@devexpress/dx-react-grid'
```

### Environment

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "declaration": true,
    "outDir": "./lib",
    "strict": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "allowJs": false
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "**/__tests__/*"
  ]
}
```

- @devexpress/dx-react-grid: 1.7.2
- react: 16.5.0
- typescript: 3.0.3

**Comment by StJohn3D** [comment]
To any who are also running into this issue, my current workaround is to do this:
```tsx
import { GroupingPanel } from '@devexpress/dx-react-grid'
const GroupPanelLayout = require('@devexpress/dx-react-grid').GroupPanelLayout
```
Basically for anything that doesn't have type definitions use require.

**Comment by MaximKudriavtsev** [comment]
Hi,

We've already discussed the similar question here #1318.
