### ISSUE TITLE
Using containerComponent?

### ISSUE THREAD

**Issue by natenrb9** [DevExpress/devextreme-reactive#1442]
Do you have an example of modifying/customizing the containerComponent? I can't get it to work correctly.
Note: I have worked your with component a ton and have it being used all over my application, and have modified the rows and cells and more.

Here it mentions it, but shows no example...
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#appearance-customization

**Comment by MaximKudriavtsev** [comment]
Hi,

I created an [example](https://codesandbox.io/s/7k7l5p87l6) that shows how to use the Table `containerComponent`.

**Comment by natenrb9** [comment]
> Hi,
> 
> I created an [example](https://codesandbox.io/s/7k7l5p87l6) that shows how to use the Table `containerComponent`.

Awesome, thanks for the quick turnaround! That is exactly what I was doing...so must be something else going on...will look into it.
