### ISSUE TITLE
Next and prev page buttons misaligned

### ISSUE THREAD

**Issue by jimmycarlinco** [DevExpress/devextreme-reactive#1444]
Using latest material-ui (v 3.1.2) and leatest dx-react-grid-material-ui, the next and prev page buttons are mis-aligned: https://i.imgur.com/G7tTRsO.png

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

**Comment by jimmycarlinco** [comment]
Also expand row button is mis-algined: https://i.imgur.com/CYMzA1R.png

**Comment by SergeyAlexeev** [comment]
Hi,

We are already [aware](https://github.com/DevExpress/devextreme-reactive/issues/1413) of this issue. The fix will be available in the next update soon.
