### ISSUE TITLE
Enable Cell Selection as well as Multiple Cell Selection using CTRL or SHIFT

### ISSUE THREAD

**Issue by adrianvpcube** [DevExpress/devextreme-reactive#1447]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
When clicking on a column the entire row is selected and the ID of that row is returned.

### Expected Behaviour
Similair to MS Excel, it would be great if it was possible to select an individual cell or cells in different rows / columns and for these selections to be maintained in state similair to how the row id's are. For example, if the table contains 3 rows and 2 columns (name and age), the user could click on the Age column cell for row 1 and for this cell to highlight as selected. In addition to this, the user could click in Age cell row 1, hold shift down and click Age cell row 3 and for all cells in column Age to be selected.

I have managed a work around which is to override the cell template onclick handler, store a reference to each selected cell in state and apply an "active" css class during render for the selected cells. Its working without the ability to use SHIFT or CTRL.

Another possible option would be to "drag select across cells" as per excel, but an approach similair to the row select method found in this example (https://stackblitz.com/edit/react-nyprct?file=index.js) but for cell would be fantastic.

### Environment

- devextreme-reactive: 1.5.1
- react: 16.4.1
- vue: none
- browser: opera, firefox, chrome, edge - all latest versions
- bootstrap: 3.x
- react-bootstrap: 0.32.1
- material-ui: 1.0

**Comment by SergeyAlexeev** [comment]
Hi,

You can detect if the 'Ctrl' or 'Shift' key is pressed using the `onKeyDown` event:

```
let isCtrlKeyPressed = false;

<Table.Cell
  onKeyDown={e => {
    isCtrlKeyPressed = e.keyCode === 17;
  }}
  onKeyUp={() => {
    isCtrlKeyPressed = false;
  }}
  onClick={e => {
    if (isCtrlKeyPressed) {
      // your code
    }
  }}
  tabIndex={0}
/>
```

This [sample](https://codesandbox.io/s/30497kj17m) shows how it works in action.

**Comment by adrianvpcube** [comment]
Hi,

Thanks for the suggestion and the example. This will definitely help me with a better UI experience.
Do you think its possible / worth while detecting mouse down and over events to simulate “drag selection” like in excel?

Thanks again

**Comment by SergeyAlexeev** [comment]
I think you can use the `onMouseOver` event to implement this behavior.
Please refer to this [example](https://codesandbox.io/s/oxn957738z).

**Comment by adrianvpcube** [comment]
Awesome, thanks so much, I really appreciate the suggestions and examples – they are a huge help!

**Comment by colindcampbell** [comment]
@SergeyAlexeev I'm unable to put a click event on the table selection checkbox, is there a workaround for that? I can hook into onToggle in TableSelection.Cell, but that doesn't return the dom event. I'm using the cellComponent prop in the TableSelection component. Thanks for your help

**Comment by MaximKudriavtsev** [comment]
Hi @colindcampbell,

You should override a default [select cell component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/#tableselectioncellprops) and configure your own `onClick` property.

See the following [demo](https://codesandbox.io/s/57lkoqj3k) for more information.
