### ISSUE TITLE
When adding to the rows array for a Grid component no new rows are rendered.

### ISSUE THREAD

**Issue by Goblaz** [DevExpress/devextreme-reactive#1456]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [x] Virtual Table
- [x] Table Column Resizing
- [x] Table Header Row

### Current Behaviour
When the grid is rendered if the rows array has increased no new rows are rendered.

### Expected Behaviour
When the grid is rendered if the rows array has increased render the new row.

### What's Happening
 Currently I have two grids, clicking on one will swap the row to the other grid. Currently the first grid successfully removes the row when the rows array is updated, however when the second grid's rows are updated to include the new row the grid still shows no data. The component containing <Grid is re-rendering and supplying the updated rows array to the grid component.

### Environment

- devextreme-reactive: 1.7.2
- react: 16.3.2
- browser: Chrome Version 69.0.3497.100 (Official Build) (32-bit)
- react-bootstrap: 0.32.4
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

I can't reproduce the described problem on my side. Would you please modify this [sample](https://codesandbox.io/s/k37k541pyo) to reproduce the issue?
 
Please note, I'm creating the 'rows' copy each time:
 
```
this.addNewRow = () => {
  // Create rows copy
  const nextRows = this.state.rows.slice();
  nextRows.push({ /* ... */});
  this.setState({ rows: nextRows });
};
```
 
It's required to notify the Grid of row changes. Refer to this  [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/immutable-data/) for more information about working with the React state.

**Comment by Goblaz** [comment]
Fixed the issue. I was not returning a brand new object to the state.
