### ISSUE TITLE
TableFixedColumns plugin not importing

### ISSUE THREAD

**Issue by maverickdude** [DevExpress/devextreme-reactive#1460]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
Everything else is working fine but when I'm importing "TableFixedColumns", I'm getting following error:
"export 'TableFixedColumns' was not found in '@devexpress/dx-react-grid-bootstrap4'.

### Expected Behaviour
The plugin should be imported from package.

### Environment

- @devexpress/dx-react-core: 1.7.2
- @devexpress/dx-react-grid: 1.7.2
- @devexpress/dx-react-grid-bootstrap4: 1.7.2
- react: 16.5.2
- vue: xxx
- browser: Chrome Version 69.0
- bootstrap: 4.1.3
- reactstrap: 6.4.0
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,
 
Currently, the `TableFixedColumns` feature is available in the [1.8.0](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#180-2018-10-04) version of the [DevExtreme React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/). Find more details [here](https://github.com/DevExpress/devextreme-reactive/issues/293#issuecomment-426993767).
