### ISSUE TITLE
dx-react-grid not compiling

### ISSUE THREAD

**Issue by m15ch4** [DevExpress/devextreme-reactive#1471]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

While compiling project I get an error:

```
Failed to compile.

./node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.es.js
Attempted import error: 'getMessagesFormatter' is not exported from '@devexpress/dx-core'.

```
devextreme-reactive: 1.8.0
(Dependencies:  ....@1.8.0-beta.1)

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please modify this [sample](https://codesandbox.io/s/2zjw6qo7qj) to reproduce the issue?
