### ISSUE TITLE
Column Visibility Dropdown Placement

### ISSUE THREAD

**Issue by muhammedesadkaya** [DevExpress/devextreme-reactive#1477]
Hi there :)

When i click column visibilty icon  (the eye icon), the dropdown menu takes x-placement="top" and data-placement="top" but sometimes takes "bottom" but i want to set top always. Can you help me please?

Best Regards

**Comment by SergeyAlexeev** [comment]
Hi,

You can use the `overlayComponent` property of the `ColumnChooser` plugin in your case.

```
const Overlay = (props) => (
  <ColumnChooser.Overlay
    {...props}
    // add the related props to customize an overlay position
  />
);

<Grid>
  {/* ... */}
  <ColumnChooser overlayComponent={Overlay} />
</Grid>
```
