### ISSUE TITLE
Integrated Sorting issue

### ISSUE THREAD

**Issue by Eainde** [DevExpress/devextreme-reactive#1478]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

I am using integrated controlled/uncontrolled sorting, but found below issues there. Can someone help me to resolve these issues.
ISSUE 1: 
When I try to sort numbers it sort them as a string not as a number. e.g.
Array: {1,10,11,110,3,66,69,4,9}
result after sorting: {1,10,11,110,1,4,66,69,9}

ISSUE 2:
When there is data available in upper case and in lower case. It gives a priority to upper case first. e.g. It makes sense technically but it does make sense functionally. 
Array: {Hello, Andy, DEV, bob}
Result after sorting: {DEV,Andy,Hello,bob}

**Comment by SergeyAlexeev** [comment]
Hi,

I [can't reproduce](https://codesandbox.io/s/m761l4joz8) the behavior you described on my side.

As for the second issue, our sorting works as a standard [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) function. Please run the following code and check the result:

```
['Hello', 'Andy', 'DEV', 'bob'].sort((a, b) => {
  if(a > b) return 1;
  if(a < b) return -1;
  return 0;
});
```
