### ISSUE TITLE
Possible issue when combining RowDetailState and PagingState

### ISSUE THREAD

**Issue by wederer** [DevExpress/devextreme-reactive#1482]
### We are using:
```
    "@devexpress/dx-react-core": "^1.7.0",
    "@devexpress/dx-react-grid": "^1.7.0",
    "@devexpress/dx-react-grid-material-ui": "^1.7.0",
```
### Current Behaviour:
When combining RowDetailState with Paging some unexpected behaviour occurs.
To reproduce:
Show details for any item on position A on page X, switch to page Y and details for another item on position A on page Y will be shown.

### Expected Behaviour:
Once switching pages the RowDetailState should be reset.

**Comment by MaximKudriavtsev** [comment]
Hi,

Would you please modify this [sample](https://codesandbox.io/s/zqrzpjv0xl) to reproduce the issue?

**Comment by wederer** [comment]
I could not reproduce the issue with local data. It only ocurrs when loading data from a remote source (on page change) and when using PagingState in a controlled mode and RowDetailsState in an uncontrolled mode.
I fixed it by controlling RowDetailState and manually setting the expanded rows on page change.

**Comment by MaximKudriavtsev** [comment]
To make the `Detail Row` feature work correctly, you should specify an `id` field for your rows. Without this field, `RowDetailState` will use the row's number.
 
I updated the [example](https://codesandbox.io/s/zqrzpjv0xl) accordingly.

**Comment by wederer** [comment]
Ok, thank you! This info could also be added to the documentation.
