### ISSUE TITLE
Stay in edit mode for specific row if row field is not valid

### ISSUE THREAD

**Issue by Justiffy** [DevExpress/devextreme-reactive#1487]
Hi, if i click "new" button to add row and for that row i want to validate if some field has value or not or any other validation. And by that logic row will not be saved but it will leave edit mode. Is it possible to stay in edit mode for that row? And logic same for edit button,

    "@devexpress/dx-react-core": "1.8.0",
    "@devexpress/dx-react-grid": "1.8.0",
    "@devexpress/dx-react-grid-material-ui": "1.8.0",
     "react": "^16.2.0",

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the [similar](https://github.com/DevExpress/devextreme-reactive/issues/800) issue.

**Comment by Justiffy** [comment]
didint work for me :C

**Comment by MaximKudriavtsev** [comment]
@Justiffy https://codesandbox.io/s/yv28rxm61v
