### ISSUE TITLE
Sorting issue (sortingEnabled not working)

### ISSUE THREAD

**Issue by maverickdude** [DevExpress/devextreme-reactive#1488]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
When disabling sorting on a column using **sortingEnabled** option, column is still being sorted by clicking on column.
I recently updated package to version 1.7.2. I guess sorting was working fine previously and this issue is occurring in this version.

### Expected Behaviour
If sorting has been disabled on a column then user should not be able to sort with that specific column.

### Steps to Reproduce (for Bugs)

The same issue can be found on demo pages itself.
Check the section "Disable Sorting by a Column" in following page. Here column "sex" has disabled sorting but it's still sortable.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/

### Environment

- devextreme-reactive: 1.7.2
- react: 16.5.2
- browser: Chrome v69
- bootstrap: 4.1.3
- reactstrap: 6.4.0

**Comment by maverickdude** [comment]
Thanks Sergey for fixing the issue.
Could you please help me with updating the local package?
To update my packages, I ran following command:
`npm i --save @devexpress/dx-react-core @devexpress/dx-react-grid @devexpress/dx-react-grid-bootstrap4`

The above command updated the package to 1.8.0 but sorting error is still there.
Please help.

**Comment by SergeyAlexeev** [comment]
The fix isn't published to npm yet. It will be available with the next update soon. Please refer to this [issue](https://github.com/DevExpress/devextreme-reactive/issues/572) to see how to build packages locally.

**Comment by maverickdude** [comment]
Thank you so much for quick clarification.
