### ISSUE TITLE
TableFixedColumns - Sticky columns are not sticking related filter column

### ISSUE THREAD

**Issue by maverickdude** [DevExpress/devextreme-reactive#1489]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
When columns are made sticky with **TableFixedColumns**, the filter row of that column is not sticky.

### Expected Behaviour
If a column is sticky then the related filter column should be sticky too.

### Steps to Reproduce (for Bugs)

I have prepared a GIF to show the error I'm facing.
Here the first column is sticky but related filter column is not.
![fixed column error](https://user-images.githubusercontent.com/9529280/46943770-ff7abc80-d08d-11e8-9e22-4e1fed34bf05.gif)

### Environment

devextreme-reactive: 1.7.2
react: 16.5.2
browser: Chrome v69
bootstrap: 4.1.3
reactstrap: 6.4.0

**Comment by MaximKudriavtsev** [comment]
Hi,

I reproduced the current behavior when I used `TableFixedColumns` before the `TableFilterRow` plugin, and this behavior is expected because our [DevExtreme React Core](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/) uses the `Data Piping` principle (see [more](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/)).

In your case, we recommended you use the `TableFixedColumns` plugin after the `TableFilterRow` plugin. See an [example](https://codesandbox.io/s/3v1lk9wmoq).

**Comment by maverickdude** [comment]
Using your recommended suggestion solved the issue.
Thanks Maxim for the very quick help. You're the best!

**Comment by maverickdude** [comment]
Hi again @MaximKudriavtsev 

I have noticed that if a column is fixed then filter popup is not being displayed properly.

![fixed column filter row](https://user-images.githubusercontent.com/9529280/47950545-c1c8cf80-df79-11e8-9072-5c4c45db0871.PNG)

Below is my template:
`

            <Card
                 className="tree-table-card"
            >
                <GridBootstrap
                    rows={!_.isEmpty(rows) ? rows : []}
                    columns={columns}
                    getRowId={getRowId}
                >
                    <TreeDataState
                        expandedRowIds={expandedRowIds}
                        onExpandedRowIdsChange={this.changeExpandedRowIds}
                    />
                    <FilteringState
                        columnExtensions={tableColumnExtensions}
                        onFiltersChange={this.changeFilters}
                    />
                    <SortingState
                        sorting={sorting}
                        columnExtensions={tableColumnExtensions}
                        onSortingChange={this.changeSorting}
                    />
                    <PagingState
                        currentPage={currentPage}
                        onCurrentPageChange={this.changeCurrentPage}
                        onPageSizeChange={this.changePageSize}
                    />

                    <CustomTreeData
                        getChildRows={this.getChildRows}
                    />
                    <CustomPaging
                        totalCount={totalCount}
                    />
                    <SearchState />

                    <SelectionState
                        selection={selection}
                        onSelectionChange={this.changeSelection}
                    />

                    <Table
                        columnExtensions={tableColumnExtensions}
                    />
                    <TableColumnVisibility
                        defaultHiddenColumnNames={defaultHiddenColumnNames}
                    />
                    <TableHeaderRow
                        showSortingControls
                    />
                    <TableSelection
                        selectByRowClick
                        highlightRow
                        showSelectionColumn={false}
                    />
                    <TableBandHeader
                        columnBands={!_.isEmpty(columnBands) ? columnBands : []}
                    />
                    <TableFilterRow
                        showFilterSelector
                    />
                    <TableFixedColumns
                        leftColumns={leftColumns}
                        rightColumns={rightColumns}
                    />
                    <TableTreeColumn
                        for={tableTreeColumn}
                    />

                    <Toolbar />
                    <ColumnChooser />

                    <PagingPanel
                        pageSizes={pageSizes}
                    />
                </GridBootstrap>
            </Card>
`

**Comment by MaximKudriavtsev** [comment]
Hi @maverickdude,
 
Thank you for your interest in our product. The behavior you described looks like a bug. I reproduced it in this [example](https://codesandbox.io/s/nwjk40o3lj). I created a new bug issue, follow this [thread](https://github.com/DevExpress/devextreme-reactive/issues/1573) for detailed information about the status of the issue.
 
As a workaround, you can override the `tableColumn` template, please see the [example](https://codesandbox.io/s/6vyjj678wz).

**Comment by emattias** [comment]
This bug still exists for `dx-react-grid-material-ui`

**Comment by MaximKudriavtsev** [comment]
Hi @emattias,
 
I can't reproduce it with the `dx-react-grid-material-ui` package. Could you please update my [example](https://codesandbox.io/s/2r26o9jzy) to reproduce the incorrect behavior?
