### ISSUE TITLE
How to install the package with fork by npm?

### ISSUE THREAD

**Issue by ChengOuyang** [DevExpress/devextreme-reactive#1509]
I fork and change the code, then I want to install by package.json.

The package.json is follow but it not work:

```
"@devexpress/dx-react-grid-bootstrap3": "git://github.com/xxx/devextreme-reactive.git#master"
```

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to the similar [question](https://github.com/DevExpress/devextreme-reactive/issues/572).
