### ISSUE TITLE
Header - set background color

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1515]
Is possible change background color of header?

Carlo

**Comment by SergeyAlexeev** [comment]
Hi,

You can use the `cellComponent` property of the [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/) plugin to customize a header cell background.

**Comment by lin-zy1229** [comment]
It works basically, but couldn't update color of SelectionColumn and others...
![image](https://user-images.githubusercontent.com/13885833/54899548-11993a80-4f0b-11e9-92ec-74f3c42ab9aa.png)

**Comment by SergeyAlexeev** [comment]
Hi,

To customize the header cell you mentioned, use the 'stubHeaderCellComponent' property of the 'Table' plugin. If you are using the 'Select All' functionality, override the 'headerCellComponent' property of the 'TableSelection' plugin as well. Please refer to this [demo](https://codesandbox.io/s/n5v36mqjx0) for more details.
