### ISSUE TITLE
Table Summary Row - display text

### ISSUE THREAD

**Issue by imcallister** [DevExpress/devextreme-reactive#1525]
In the various aggregations in the summary row plugin the default display text is of the form "Sum:  1,234" or "Count: 23".

In situations where i am using it, it is clear from the context that they are all Sums, so seeing  "Sum: xxxx" in each column doesn't look great.

I know that I can use the Localization messages [https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-summary-row/#localization-messages](url)  to remove the "Sum" part but it still leaves me with displays of the form ":  xxxx".

From [https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-summary-row.jsx](url) I can see that the ":&nbsp;&nbsp" is hard-coded.

`<React.Fragment>
        {columnSummaries.map((summary) => {
           if (summary.value === null
            || formatlessSummaryTypes.includes(summary.type)
            || defaultTypelessSummaries.includes(summary.type)) {
            return (
              <Item
                key={summary.type}
              >
                {getMessage(summary.type)}
                :&nbsp;&nbsp;
                {String(summary.value)}
              </Item>
            );
          }`

Would it be possible to make that piece of the string customizable too? 

Thanks!

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for bringing our attention to this issue. I agree that, currently, it's quite difficult to customize a summary item. We will improve this in future releases. For now, you can use the [React Core API](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/) to implement the functionality you described. I've created a [sample](https://codesandbox.io/s/jln40lp20v) that shows how to override the 'tableCell' [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/) and create a custom summary item. Please refer to the comments in code.
