### ISSUE TITLE
Column started to resize crazily

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#1529]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart

### Current Behaviour
As can be seen below in the GIF capture, after I clicked on the Edit button, all the columns started to resize themselves like crazy. It was because I toggled the `showSelectionColumn` prop in `TableSelection` plugin.

![2](https://user-images.githubusercontent.com/1334982/47468611-0487ec00-d7b1-11e8-9fc3-384bb8738305.gif)

From below capture GIF, you can see that there is a `transform: translateX()` appearing in in the `style` tag.

![1](https://user-images.githubusercontent.com/1334982/47468446-2a60c100-d7b0-11e8-8952-4a86ccc48b0f.gif)

### Expected Behaviour
The columns should not resize themselves drastically like crazy.

### Steps to Reproduce (for Bugs)

In my code, I have `SelectionState` and `TableSelection` as the grid plugins. In `TableSelection`, I toggle the `showSelectionColumn` according to my state. Quite often, after I press the button to change the state (thus toggling the visibility of the selection column), the size of other columns started to auto-resize wildly and drastically, as shown in my screen capture GIF. This is very annoying.

I expect there to be a config where I can disable the column resizing animation entirely. i.e., I should be able to disable the entire `transition: translateX()` thingy. I understand that the animation under some circumstances are desirable, but in my case, I would like them to be disabled because they are causing much bigger problems.

### Environment

- devextreme-reactive: 1.8.0
- react: latest
- material-ui: latest

**Comment by MaximKudriavtsev** [comment]
Hi,

We know about this problem and the fix you described is the most appropriate for the moment. We will discuss how to better resolve this issue in the future.

**Comment by priyanshu92** [comment]
This also happens on showing/hiding columns using column chooser if the grid has a lot of columns.

**Comment by TheMoonDawg** [comment]
Has this not been fixed yet? We just encountered this bug as well.

**Comment by wpascucci** [comment]
Hi, I'm faced the same issue when use Grouping feature with CustomSummary, after ungrouping any column.

**Comment by kg-currenxie** [comment]
@franklixuefei how are you applying those styles?

**Comment by LazyLahtak** [comment]
Hi all
 
This error may refer to the [defaultColumnWidths](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#tablecolumnwidthinfo) option of the TableColumnResizing plugin. In this option, you need to specify a number type, not a string type.
Here is an [example](https://codesandbox.io/embed/vigilant-architecture-trg4c) where this error is reproduced. In the second [example](https://codesandbox.io/s/lkpc0-lkpc0), everything work correctly.

**Comment by LazyLahtak** [comment]
Please let us know if this solution suits you.
