### ISSUE TITLE
How to edit an item parent for tree data structure

### ISSUE THREAD

**Issue by sornman** [DevExpress/devextreme-reactive#1540]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart

### Current Behaviour

Unable to add a new row to a parent, or move an existing row up or down the tree.

### Expected Behaviour

I am looking to see if there is a way to work with editing tree data. I can create new top-level rows, and I can edit existing rows, but I can't move rows up or down the tree.

### Environment

- devextreme-reactive: 1.8.0
- react: 16.5.2
- material-ui: 3.2.0

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, we don't provide the functionality you described out of the box. We'll discuss the possibility of implementing it in future releases.

As a workaround, you can use the following steps:

- Add a custom button to a table edit column.
- Show an edit form by clicking on the created button.
- Save the inserted data.

I've created an [example](https://codesandbox.io/s/j2r95p220v) that demonstrates this approach in action. Please note that each item in the Grid's data contains the `id` and `parentId` fields. These fields are required for a hierarchical data structure.

As for moving a row between tree levels, you can use a custom editor that allows selecting a parent item. This [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/) shows how to use a custom cell editor.
