### ISSUE TITLE
Unable to use dx-react-grid without predefined theme

### ISSUE THREAD

**Issue by joinsunil** [DevExpress/devextreme-reactive#1541]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [x] React Chart

### Current Behaviour

I am implementing this awesome devextreme-reactive, earlier i used react-data-grid but failed to accomplish few use cases like word wrapping and all. After gone though this cool repo, i decided to implement devextreme-reactive, I have implemented it and it fits completely perfect in all my scenarios/use cases.

I have implemented with bootstrap 4 theme but I want to use my own css themes/templates. So i exported all the required components from `@devexpress/dx-react-grid'`.

Here is the [https://codesandbox.io/s/8l2xmqj0wj](https://codesandbox.io/s/8l2xmqj0wj)

### Expected Behaviour

It should be rendered

- devextreme-reactive: 1.8
- react: 16.4
- browser: Chrome 62+
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,

In your sample, you try to import the `VirtualTable` plugin from the `@devexpress/dx-react-grid` package, but this plugin is available only in theme packages, like `material-ui/bs3/bs4`. 

You can implement your own `VirtualTable` plugin using [our implementation](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap4/src/plugins/virtual-table.jsx) as an example.

This thread may be useful #1318.

**Comment by joinsunil** [comment]
@MaximKudriavtsev Thanks for your time, I have tweaked my code sandbox [here](https://codesandbox.io/s/8l2xmqj0wj) . Based on the example you referred. Still getting error can you please help me out ?

**Comment by rao123dk** [comment]
Hi @joinsunil @MaximKudriavtsev  thanks for this thread. I am also facing same problem.

**Comment by sundariya786** [comment]
Hi, @joinsunil @MaximKudriavtsev thanks for this thread. I am also facing the same problem.

**Comment by MaximKudriavtsev** [comment]
Hi @rao123dk, @sundariya786 

To create a custom theme package, you should define all required components. For example, I created a `Table` plugin with a [Semantic UI](https://react.semantic-ui.com/), see a [demo](https://codesandbox.io/s/yjn357wwlv). There are custom components with Semantic UI React controls in a `template` folder and custom plugins in a `plugin` folder. You can see the required components for a plugin in the plugin's file in our theme [source code](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-material-ui/src/plugins).

**Comment by joinsunil** [comment]
@MaximKudriavtsev ok got your point, i have to create a complete plugin as created for b3,b4 .. with all required plugins and templates, correct ?

One more thing is that I am using typescript few import are invalid like `withComponent` from `@devexpress/dx-react-core` and  `Draggable` from `@devexpress/dx-react-core`. Actually I want to achieve all functionality like b4 version but without css. What is the best way to achieve it in a small time ?

**Comment by MaximKudriavtsev** [comment]
@joinsunil 

> @MaximKudriavtsev ok got your point, i have to create a complete plugin as created for b3,b4 .. with all required plugins and templates, correct ?

Yes, you are right.

As for using TypeScript, you can see this [thread](https://github.com/DevExpress/devextreme-reactive/issues/1318#issuecomment-413135221).

> Actually I want to achieve all functionality like b4 version but without css. What is the best way to achieve it in a small time ?

You need to create all `plugins` and `templates` that you need in the way I displayed in the [example](https://codesandbox.io/s/yjn357wwlv). However, take special note that this API is not public and can be changed in the future without notification.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
