### ISSUE TITLE
Request: Reduce bundle size by removing "reactstrap" dependency

### ISSUE THREAD

**Issue by joerneu** [DevExpress/devextreme-reactive#1543]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart

### Current Behaviour

The grid with Bootstrap 4 uses "reactstrap" which increases the bundle size by 85KB.

### Expected Behaviour

Remove the dependency on "reactstrap" because almost none of it is used.

### More information

I am using Bootstrap 4 in my React application without "reactstrap".

I checked the source of the DevExtreme React Grid and only four components of "reactstrap" are used:

`import { Popover, Pagination, PaginationItem, PaginationLink } from 'reactstrap';`

Everything else is implemented by plain HTML with Bootstrap classes.

I believe it does not make sense to include "reactstrap" for these four components. The pagination components are just "sugar" around the Bootstrap 4 pagination HTML and classes. This could easily be replaced.

The Popover in "reactstrap" is Bootstrap 4 HTML with "react-popper". So, why not use "react-popper" directly and make "react-popper" a peer dependency instead?

With these minor changes the bundle size would decrease and "reactstrap" would be optional. And if someone would want to use "reactstrap", there would not be an issue because both libraries would depend on the same "react-popper" and the bundle size would not increase.

Here is an overview of the bundle size of a simple grid sample:

![gridsamplebundlesize](https://user-images.githubusercontent.com/31096117/47745220-78c80100-dc83-11e8-82ab-211fe1f33a21.png)

You can see that "reactstrap" accounts for 20% of the bundle size.

### Environment

- devextreme-reactive: 1.8.0
- react: 16.6
- browser: All
- bootstrap: 4
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,
 
Thank you for your suggestion and sharing results. We will think about improving this in future releases.
