### ISSUE TITLE
Problem resetting expand/collapse state on page change

### ISSUE THREAD

**Issue by theDude30** [DevExpress/devextreme-reactive#1551]
Hi,
I'm using RowDetailState with expandedRowIds attribute.
the expandedRowIds is a state parameter that onExpandedRowIdsChange adds the row ID to the parameter(state parameter).
When i change page or filter i reset the state parameter(expandedRowIds) but the expanded rows are not collapsing.

- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [ X] React Grid

### Current Behaviour

<RowDetailState expandedRowIds={this.state.expendedRowIds} onExpandedRowIdsChange={this.changeExpandedDetails} />

when this.state.expendedRowIds =[] it's not collapsing the rows.

### Expected Behaviour

I excpect that when i modify table content the state of the rowDetails (collapse/expand) would reset by setting the state parameter to []

### Steps to Reproduce (for Bugs)
See above.

### Environment

- devextreme-reactive: 1.6.0
- react: 16.3
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.4.3

**Comment by DmitryBogomolov** [comment]
Hello.

It looks like you are changing state with direct field reassignment of the `state` object.
State should only be changed with the `setState` method.
 
Here is an [example](https://codesandbox.io/s/50l9oo24kp) where expanded rows are collapsed when button is clicked. Would you please modify it to reproduce your scenario?

**Comment by theDude30** [comment]
Works great, thanks for the help
