### ISSUE TITLE
React Grid: Virtual scrolling not working (Edge)

### ISSUE THREAD

**Issue by joerneu** [DevExpress/devextreme-reactive#1557]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart

### Current Behaviour

Draws blank grid.

### Steps to Reproduce (for Bugs)

[Virtual scrolling demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/)

- Open in Edge
- Scroll all the way to the right
- Scroll down

-> The grid is blank.

- Scroll left and the rows appear again.

### Environment
- browser: Edge
- bootstrap: 3 & 4
- material-ui: Light and Dark theme

P.S.: Do you prefer that we report issues here on Github or the DevExpress support tickets?

**Comment by SergeyAlexeev** [comment]
Hi,
 
Thank you for pointing out this issue. Usually, we process bugs on GitHub. It allows us to generate the 'CHANGELOG.md' file automatically.
