### ISSUE TITLE
Table does not update with state changes

### ISSUE THREAD

**Issue by timmo001** [DevExpress/devextreme-reactive#1565]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart

### Current Behaviour

When updating the state of the rows, the table does not update. The only way to fix this is to set the rows to an enpty array and then set the rows to the new state.

### Expected Behaviour

Rows/Columns should update when setting a new state without this workaround

### Steps to Reproduce (for Bugs)

- Create a table with data set in state.
- Change the state of the rows
- The data will update in state, but the table does not.

### Environment

- devextreme-reactive: 1.8.0
- react: 16.5.2
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.8.0

**Comment by DmitryBogomolov** [comment]
Hello.

Would you provide a sample that modifies the state or update [this one](https://codesandbox.io/s/9z4l6lyl3o) to reproduce the issue?

**Comment by mrUmberto** [comment]
I had the same issue. But you can easily solve that by array copy:
```
setState({rows: [...modifiedRows]});
```

**Comment by franklixuefei** [comment]
remain pure
