### ISSUE TITLE
Filter popup displays bad if a column is fixed.

### ISSUE THREAD

**Issue by MaximKudriavtsev** [DevExpress/devextreme-reactive#1573]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart

### Current Behaviour

Cloned from #1489 

I have noticed that if a column is fixed then filter popup is not being displayed properly.

![fixed column filter row](https://user-images.githubusercontent.com/9529280/47950545-c1c8cf80-df79-11e8-9072-5c4c45db0871.PNG)

### Steps to Reproduce (for Bugs)
https://codesandbox.io/s/nwjk40o3lj

**Comment by maverickdude** [comment]
Thanks @MaximKudriavtsev 
The workaround works well.

Could you please share when NPM package will be updated? 
The last version was updated around a month before, so I'm just asking for info; nothing else. :)

**Comment by maverickdude** [comment]
Thanks @MaximKudriavtsev

**Comment by MaximKudriavtsev** [comment]
Hi @maverickdude,

We updated our NPM packages. You can see news in the [Changelog](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#190-2018-11-07) file.
