### ISSUE TITLE
How to create a custom value formatting remotely? 

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1586]
How to create a custom value formatting remotely? 

Value Formatting renders the formatted value to the DataTypeProvider pluin's formatterComponent property. 

I want to get one of the value from a remote data source.

```
const CurrencyFormatter = ({ value }) => (
fetch()
  .then(response => response.json())
);

const CurrencyTypeProvider = props => (
  <DataTypeProvider
    formatterComponent={CurrencyFormatter}
    {...props}
  />
);

this.state= {
dateColumns: ['saleDate']
}

render( ) {
    const {dateColumns} = this.state;
}

<CurrencyTypeProvider
            for={currencyColumns}
          />

```

- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart

### Current Behaviour
The value of currencyColumn cannot populate from api.

### Expected Behaviour
The value of currencyColumn is changed as the data from api.

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: xxx
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
I'm afraid I don't understand your question correctly. First of all, let's look at this peace of code:

```
const CurrencyFormatter = ({ value }) => (
fetch()
  .then(response => response.json())
);
```

It returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) object.

As you can see in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider#user-reference), the `formatterComponent` property accepts a component that renders the formatted value.

We have a [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/remote-data/) that shows how to work with remote data. Here we are using a [custom formatter component](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-demos/src/theme-sources/bootstrap4/components/currency-type-provider.jsx). Does it meet your needs?

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
