### ISSUE TITLE
Detail Row - column in different place

### ISSUE THREAD

**Issue by prhetio** [DevExpress/devextreme-reactive#1610]
Column with expand buttons is displayed as first column from left. I want to display this column as first one from right. I didn't find any information how to do this neither in documentation nor in Google. Also I want to display this column with header "More". Is it possible?

**Comment by SergeyAlexeev** [comment]
Hi,

As you can see in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail#plugin-developer-reference), the `TableRowDetail` plugin uses the `tableColumns` [getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) that contains table columns. You can customize this getter as follows:

```
<Getter name="tableColumns" computed={({ tableColumns }) => {
   const [ detailColumn, ...restColumns ] = tableColumns;
   return [...restColumns, detailColumn];
}}/>
```

As for the 'More' title for the 'detail' column, use the `stubHeaderCellComponent` property of the `Table` plugin.

Please refer to this [sample](https://codesandbox.io/s/zkxqj5m83m) for more details.

**Comment by prhetio** [comment]
Awesome! It works. This is exactly what I need. Thank you.
