### ISSUE TITLE
footerTableComponent not included in VirtualTableProps typescript interface

### ISSUE THREAD

**Issue by emattias** [DevExpress/devextreme-reactive#1616]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Typescript says that the VirtualTable component cant take a `footerTableComponent` prop.

### Expected Behaviour
For typescript to know about the `footerTableComponent` prop.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
