### ISSUE TITLE
How to use export template components

### ISSUE THREAD

**Issue by emattias** [DevExpress/devextreme-reactive#1618]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I cant individually import components under the [templates folder](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-material-ui/src/templates), like for example [Pager](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/paging-panel/pager.jsx)

### Expected Behaviour
To be able to import individual template components so that I can use some of them and override others. 

My use case is that I want to use the `PagingPanel` but not output the numbers to go to a certain page.

**Comment by MaximKudriavtsev** [comment]
We have provided a flexible functionality to override our components. All of our components are exported from their parent plugin. You can find a list of export templates in the `Plugin Components` section in our API reference docs, for example, [Table's components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#plugin-components).

You can find how to override templates in the [Foundamentals Guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/).

About Pager's components. Now, we have only one export component from the `PagingPanel` plugin. This is `containerComponent`. We have [plans](https://github.com/DevExpress/devextreme-reactive/issues/887) to add more export components from the `PagingPanel` plugin.
