### ISSUE TITLE
Documentation website cookie problem

### ISSUE THREAD

**Issue by TR3MIC** [DevExpress/devextreme-reactive#1622]
Hi, I have a small but annoying bug on the documentation website: the "Why we use cookies" banner won't remember that I've clicked "I understand".

In case it can help, the value of "dx-cookie-policy" is "Fri%20Nov%2016%202018%2010%3A18%3A59%20GMT-0500%20%28heure%20normale%20de%20l%u2019Est%20nord-am%E9ricain%29" (My computer and browser are in French, so maybe it's that. The value says "Fri Nov 16 2018 10:18:59 GTM-0500 (heure normale de l'Est nord-américain)").

Like I said, not a big deal, but it's still annoying to dismiss the banner each time I change page, or to just forget it and let it eat a part of the page.

**Comment by SergeyAlexeev** [comment]
Hi,
 
I can't reproduce the issue on my side. I used the 'GMT-0500 (Eastern Standard Time)' timezone on my PC and the 'Why We Use Cookies..' message appears only once.
 
Could you try to clear browser cookies? Does the problem still exist?

**Comment by TR3MIC** [comment]
I tried what you asked me to do, and even tried a guest Chrome session and the problem is still there. The cookie is created when I click "I understand", but the banner still appear on the next page or reload.

I also tried on Firefox, and still I have the same issue.

Maybe it's because my system is in French? I would need to try on an English system to confirm that (I'll try with a virtual machine and give you an update then).

**Comment by TR3MIC** [comment]
I can confirm, on a Ubuntu VM in French (Canada), the cookie value doesn't seem to be correctly interpreted and the banner will show on each pages. When I change the language to English (Canada) and accept (again) the cookie usage, it doesn't show anymore on reload or page change. If I switch back to French (Canada), the banner won't show up since the latest cookie value is the one with the English date version. If I clear the cookies and try again, now the problem has returned.

So I think the cookie value is not correctly translated from French to a valid date for the verification.

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information! I reproduced the problem. We'll create a PR that fixes it soon.
