### ISSUE TITLE
Custom scrollbar for VirtualTable

### ISSUE THREAD

**Issue by JavierLight** [DevExpress/devextreme-reactive#1628]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

I'm trying to use a custom scrollbar, cross-browser to replace the native scrollbar ([this is the library](https://github.com/malte-wessel/react-custom-scrollbars)). All I could achieve was to hide the scrollbar in the VirtualTable, setting overflow style to `hidden` in the `containerComponent` prop.

Is there any workaround to use specific styles for the rendered scrollbar so that they match the rest of the application?

Thank you very much for your time.

**Comment by MaximKudriavtsev** [comment]
Hi,

To customize native scrollbars you can pass a specific class to the `VirtualTable` plugin's `container` component. See the following [demo](https://codesandbox.io/s/4qxv441m9x).

**Comment by incadoi** [comment]
Maybe if you provide a custom component for `containerComponent` property of the `VirtualTable` you can inject your scrollbar there. You can start with their implementation and change it as you need.

**Comment by JavierLight** [comment]
Alright, thank you very much for your response. I was hoping this could be implemented using the `react-custom-scrollbars` library, because your workaround is not compatible with all browsers. Now I see this is not an issue of `devextreme-reactive`, so I'm closing it.
