### ISSUE TITLE
How to add validation and show error in the edit cell while in edit mode?

### ISSUE THREAD

**Issue by rishabh2712** [DevExpress/devextreme-reactive#1629]
I want to validate the inputs onCommitChanges and show the error message corresponding to each field.  I want a workaround that will add error and error-message to EditCell and keep the mode to edit.

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the similar [question](https://github.com/DevExpress/devextreme-reactive/issues/475).
