### ISSUE TITLE
Add additional actions to TableEditColumn

### ISSUE THREAD

**Issue by vantsymbalenko** [DevExpress/devextreme-reactive#1637]
Is it possible to add addition buttons besides add, delete and edit buttons to TableEditColumn?
For example I want to add button which will show modal box with all information about row

**Comment by ushkal** [comment]
Hi,
 
You can add additional actions using the [TableEditColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/).cellComponent property. I suggest you use the TableEditColumn.Command component as an action button and handle the onExecute event to invoke your action, i.e. show a popup.
Here's an [example](https://codesandbox.io/s/426kznjv5w).

**Comment by vantsymbalenko** [comment]
> Hi,
>  
> You can add additional actions using the [TableEditColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/).cellComponent property. I suggest you use the TableEditColumn.Command component as an action button and handle the onExecute event to invoke your action, i.e. show a popup.
> Here's an [example](https://codesandbox.io/s/426kznjv5w).

Yes it works, but how can I pass function from outside as custom action? Something like in case with delete row, Dialog component is opened when we have items in this.state.deleteRows

**Comment by benoitgrasset** [comment]
I tried your example, it works perfectly, but only with custom actions. I would like to add native 'add' button besides 'edit' and 'delete buttons'. Is it possible ?

**Comment by ushkal** [comment]
Hi @benoitgrasset,
 
It's possible to implement this behavior using the controlled mode. Here's an updated [example](https://codesandbox.io/s/6y300420nn).

**Comment by benoitgrasset** [comment]
thanks a lot it wworks,
but is it possible to add a row at a custom row index ? By default the row is added in first automatically

**Comment by ushkal** [comment]
To achieve this you will have to implement a custom plugin that moves an added row to the right place. Here's an updated [example](https://codesandbox.io/s/l9v90n2x8z).
Here's a [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) on creating custom plugins.

**Comment by benoitgrasset** [comment]
thanks a lot for your quick and accurate answer !
