### ISSUE TITLE
How can I customize toolbar and search panel?

### ISSUE THREAD

**Issue by Nusinka** [DevExpress/devextreme-reactive#1640]
Hi! I use dx-react-grid and dx-react-grid-material-ui. I couldn't find information how I can change css in this components. I tried sing Template in Toolbar, but I can't change css in MuiToolbar class. Please help

**Comment by ushkal** [comment]
Hi!

You can use the rootComponent property to customize the Toolbar, here's a [sample](https://codesandbox.io/s/jp6xqor7l9). 
See our docs for your reference: 
[Grid Appearance Customization](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#appearance-customization)
[Toolbar Plugin Reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/)
