### ISSUE TITLE
Single Slection

### ISSUE THREAD

**Issue by AsimRamay** [DevExpress/devextreme-reactive#1647]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### I'm using ...
- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler
### Current Behaviour
the grid selects multiple rows 
![image](https://user-images.githubusercontent.com/16746011/49128057-ed8f6900-f31d-11e8-8ac1-b64d95ea6af0.png)

### Expected Behaviour
I want it to select a single row only at any time 
![image](https://user-images.githubusercontent.com/16746011/49128078-fd0eb200-f31d-11e8-9551-7dbe9773ea83.png)

I can't find anything in documentation specifically for react to enable single selection(but i can for JS and other frameworks) and trying to deselect all results in an error 
![image](https://user-images.githubusercontent.com/16746011/49128139-33e4c800-f31e-11e8-944d-1bc8f7ac47d4.png)

### Environment
"dependencies": {
    "@blueprintjs/core": "^3.7.0",
    "@blueprintjs/datetime": "^3.3.0",
    "@blueprintjs/icons": "^3.2.0",
    "@blueprintjs/select": "^3.2.0",
    "@blueprintjs/table": "^3.2.0",
    "@blueprintjs/timezone": "^3.1.0",
    "@devexpress/dx-core": "^1.9.0",
    "@devexpress/dx-react-core": "^1.9.0",
    "@devexpress/dx-react-grid": "^1.9.0",
    "@devexpress/dx-react-grid-bootstrap4": "^1.9.0",
    "bootstrap": "^4.1.3",
    "devextreme": "^18.2.3",
    "devextreme-react": "^18.2.3",
    "fastify": "^1.12.1",
    "fastify-postgres": "^1.3.1",
    "open-iconic": "^1.1.1",
    "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "reactstrap": "^6.5.0"
  },
  "homepage": "./",
  "main": "src/main.js",
  "scripts": {
    "start": "nf start -p 3000",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "electron": "electron .",
    "electron-start": "node src/electron-wait-react",
    "react-start": "react-scripts start",
    "fastify-start": "node server/server"
  },
  "proxy": "http://localhost:3101",
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "electron": "^3.0.4",
    "foreman": "^3.0.1",
    "pg-native": "^3.0.0",
    "react-scripts": "2.0.4"
  }

### CODE
```
import * as React from 'react';
import { Card } from 'reactstrap';
import {
    FilteringState,
    IntegratedFiltering,
    SortingState,
    IntegratedSorting,
    SelectionState,
} from '@devexpress/dx-react-grid';
import {
    Grid,
    VirtualTable,
    TableHeaderRow,
    TableFilterRow,
    TableSelection,
} from '@devexpress/dx-react-grid-bootstrap4';

export class InfoTable extends React.PureComponent {
    constructor(){
        super()
        this.state = {
            numResultsRows: 0,
            results: [],
            loaded: false,
            columns: [],
            selection: [0]
        }
        this.grid = null;

        this.grid = (ref) => {
            this.grid = ref.instance;
        };
        this.changeSelection = selection => {
            this.grid.deselectAll();
            this.setState({ selection: [0] });
            this.setState({ selection: selection });
        };
    }

    componentDidMount() {
        // var searchString = store.getState().submitSearch.searchString;

        // Pretend an API call just happened and the results object is returned

        // This is the dummy data
        // var resultsObject = fetch().then(results => {
        //     return results.json();
        // })
        this.callApi()
            .then(res => this.createTable(res))
            .catch(err => console.log(err));
    }
    callApi = async () => {
        const response = await fetch(this.props.location.pathname);
        const body = await response.json();

        if (response.status !== 200) throw Error(body.message);

        return body;
    };

    // createColumn(columnData, index) {
    //     const cellRenderer = (rowIndex: number) => {
    //         return <Cell>{index}</Cell>
    //     };
    //     return <Column name={columnData} cellRenderer={cellRenderer}/>
    // }
    //
    // createColumns(columnDatas) {
    //
    //
    // }
    createTable(results) {
        var InfoColumns = Object.keys(results[0]);
        var InfoColInit  = [];

        for (var x = 0; x < InfoColumns.length; x++){
            InfoColInit[x] = {};
            InfoColInit[x]['name'] = InfoColumns[x];
            InfoColInit[x]['title']= InfoColumns[x];
        }
        this.setState({
            numResultsRows: results.length,
            results: results,
            columns: InfoColInit,
            loaded: true
        });
        //this.state.columns = CustColInit;
        //this.setState({ columns: CustColInit });
    }


    content() {

    }

    render() {
        if(this.state.loaded === true) {
            const { results, columns, selection } = this.state;
            return (

                <Card>
                    <Grid
                        rows={results}
                        columns={columns}
                        style={{ height: '100%'}}
                    >
                        <SortingState

                        />
                        <IntegratedSorting />
                        <FilteringState defaultFilters={[]} />
                        <IntegratedFiltering />
                        <SelectionState
                            selection={selection}
                            onSelectionChange={this.changeSelection}
                        />
                        <VirtualTable
                            height="auto"
                        />
                        <TableHeaderRow showSortingControls />
                        <TableSelection
                        selectByRowClick
                        highlightRow
                        showSelectionColumn={false}
                        />
                        <TableFilterRow />
                    </Grid>
                </Card>

            );
        }else{
            return (
                <span></span>
            );
        }
    }
}

export default InfoTable;
```

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the similar question #477.
