### ISSUE TITLE
Paging; Next and Previous buttons

### ISSUE THREAD

**Issue by greenallparagonuk** [DevExpress/devextreme-reactive#165]
I can't find how to turn the next and previous buttons on in the paging panel. 

Have they been missed out of this release?

**Comment by SergeyAlexeev** [comment]
Hi Andrew,

For now, DevExtreme React Grid doesn't support the previous/next buttons for pagination. But, it looks like a valuable UI improvement, and we are going to discuss the possibility to implement this functionality in the future.

Currently, you can implement such functionality on your side using the `pagerTemplate`  property of the [PagingPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-panel/) plugin.

First, import the [Pagination](https://react-bootstrap.github.io/components.html#pagination) component from the [react-bootstrap](https://react-bootstrap.github.io/) package:

    import { Pagination } from 'react-bootstrap';

Then, use it as a pager template:

    <PagingPanel
        allowedPageSizes={allowedPageSizes}
        pagerTemplate={
        ({
            totalPages,
            currentPage,
            onCurrentPageChange,
            }) => (<div className="clearfix">
            <Pagination
                style={{
                margin: 0,
                verticalAlign: 'bottom',
                }}
                className="pull-right"
                items={totalPages}
                activePage={currentPage + 1}
                boundaryLinks
                maxButtons={3}
                onSelect={page => onCurrentPageChange(page - 1)}
                next
                prev
            />
            </div>)
        }
    />

**Comment by susuwatari2** [comment]
Can you show a sample?

**Comment by LazyLahtak** [comment]
Implemented
