### ISSUE TITLE
Remote filter doesn't remain TableFilterRow

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1652]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Perform filtering remotely by handling filtering state changes, generating a request, and sending it to the server.

After that, the TableFilterRow is cleared.

What would that cause?
 

### Expected Behaviour

Perform filtering remotely by handling filtering state changes, generating a request, and sending it to the server.

After that, the **filter values should remain in the TableFilterRow.**

- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,
 
You can see how to configure remote filtering in the following [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#remote-filtering).

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,

I did not manage to reproduce the problem. You can see how to configure remote filtering with remote paging in the following [example](https://codesandbox.io/s/621nlm01o3).

Can you change my example to reproduce your behavior?

**Comment by susuwatari2** [comment]
@MaximKudriavtsev 

I tried to get it like mine in the following [sample](https://codesandbox.io/s/ry1v97vv0q). It doesn't really behavior the same but is it fine with my way? 
Perform filtering remotely by handling filtering state changes, generating a request `queryString` , and sending it to the server ` loadData(queryString)`.

**Comment by MaximKudriavtsev** [comment]
Hi,

Yes, you should handle all state changes, generate a `queryString`, and send it to the server.

In your sample, you used the `setTimeout` function together with the `setState` function. I believe this is dangerous and may cause many problems in the future.

Our guides have a lot of examples with a remote data source. For example https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/remote-data/

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
