### ISSUE TITLE
Feedback; Can't wait for the full release!

### ISSUE THREAD

**Issue by greenallparagonuk** [DevExpress/devextreme-reactive#166]
This grid is the best I've seen so far.  It is early in the development and their are bits missing, but it's still a good implementation. I can't wait for the small issues that remain to be resolved and a full version released!

**Comment by dxbykov** [comment]
Hi,
 
Thank you for your feedback. We expect to release a beta in a couple of months. 
 
It would also be great if you could share additional info with us to allow us to satisfy your needs better. Which 'must have' features do you expect to have by the final release? Which other React components would you like to have next if you need any? Thank you in advance!

**Comment by greenallparagonuk** [comment]
My team has had many discussions on which framework we should be using, React has come up as a good fit for us right now. So I have been working on converting a small part of a project we have already completed to a demo I can show our team leader to get approval.

The part of the project I choose was the reporting section, which has a number of sub pages showing customer activity etc.

So I need a grid to show this log data and allow the user to filter and sort. 

So most of the features I need you have already done. But if my team leader asks if we need to purchase a license and the BOSS has to get involved, little things like no "next" and "previous" buttons on the paging panel will prevent the purchase. Our BOSS is very critical of visual aspects like that.

One feature I've not had chance to look at yet is we need to be able to view sub-documents in a column; We are using DocumentDB (a no-sql database) more and more, and we are using sub-documents to store some of the data. (probably a bad example but) One of the logs in the above project is a file request log. In this log the fields are Time (the time it is was requested), Filename, Result, Error. Result and Error are sub-documents, Result is a simple POCO showing the details, Error is a POCO which has general details and an array of Error inside it. The current webpage for this is a div with formatting of the model, but it doesn't have all the nice features of a grid with sorting and filtering etc. etc. (well it does but it's a lot of code)

A feature I will need if we can get our BOSS to purchase a license will be for the detail row to be open/visible all the time (unable to close). This is a feature of a project that the customer requested and they may complain if they have to open the rows they want to view the info for (which isn't a lot), they can also press a button to action an event on that rows data.

But ultimately for the React Grid look and feel like the JQuery DevExtreme grid with all it's features and goodness.

Other controls I would like are the Scheduler, Chart and File Uploader controls from DevExtreme. The Scheduler for us is a big issue as we are currently using one from another provider which has so many workarounds it's very nearly just a grid and there support!!! (Don't get me started). It's so bad we are not going to re-new the license and this is the purchase our BOSS made then gave us the project saying "it will not take long.... Look I got a control to make it quick" (we ended up spending more than 4 weeks on just one page to display that control! But most of that was waiting for there support to get back to us). We ended up using basic features and getting it to link to separate pages to display detailed info.

I've used DevExpress before and I know how good they are and how good the support team is.

**Comment by dxbykov** [comment]
Thank you a lot for such a comprehensive answer. We'll take it into account when planning further development. 
 
One of our main goals is to make our Data Grid consist of loosely coupled, customizable and replaceable pieces (aka plugins). So you'll be able to implement any scenario you need for your business tasks. Of course, we try providing the most demanded features out-of-the-box. 
 
Regarding the detail row features, you definitely can show any piece of row data within it and put a corresponding interactive UI inside. Also, you can fully control the open/closed state using the [controlled state mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/#controlled-and-uncontrolled-modes). 
 
Feel free to ask any specific questions regarding the scenarios you need to implement.

**Comment by Krijovnick** [comment]
Hi,

DevExtreme React Chart CTP is available now. You can find getting started guides [here](https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/getting-started/). Try our charts and share any thoughts with us in the [GitHub issue tracker](https://github.com/DevExpress/devextreme-reactive/issues).

**Comment by MaximKudriavtsev** [comment]
Hi @greenallparagonuk,

DevExtreme React Scheduler CTP is available now. You can find getting started guides [here](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/). Try our scheduler and share any thoughts with us in the [GitHub issue tracker](https://github.com/DevExpress/devextreme-reactive/issues).
