### ISSUE TITLE
How to remove No data when the grid is loading from a fetch

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1663]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
'No data' stays in the grid when it is doing a fetch remotely.
I have a loading spinner, so it is unnecessary to say 'No data' when it is loading.

### Expected Behaviour
When it is loading, only requires the spinner, and remove 'No data'.
When it is done for fetching. no result will show 'No data'.

Any ideas how to handle the 'No data' with the spinner for remote data? I went through the docs already.

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you override the `noDataCellComponent` property of the `Table`(or `VirtualTable`)  plugin.

Let's see how it can be implemented in the context of this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering#remote-filtering).

```jsx
noDataCell(props) {
  return this.state.loading
    ? <td colSpan={props.colSpan} />
    : <VirtualTable.NoDataCell {...props} />;
}

render() {
  <Grid>
    <VirtualTable
      noDataCellComponent={this.noDataCell}
     />
  </Grid>
}
```

The idea is to show the 'No data' message only if loading is completed.

**Comment by susuwatari2** [comment]
@SergeyAlexeev What does this `noDataCellComponent` do? I still want to show 'No data' want there is no data. I want to hide 'No data' message when `loading: true`.

**Comment by SergeyAlexeev** [comment]
As you can see in our  [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/), the `noDataCellComponent` property contains a component that will be rendered if a table has no data. In my piece of code, I use an empty `td` tag as the `noDataCellComponent` component if data loading is in progress. Finally, if a table doesn't contain any rows, the 'No data' message will be rendered.

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it
