### ISSUE TITLE
Is it posible to have TableEditRow opened on mount?

### ISSUE THREAD

**Issue by zcuric** [DevExpress/devextreme-reactive#1664]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

Hi, 
I want to edit rows or add new ones in a Dialog. I already made the Dialog part, but I have to open the editing process in the Dialog again to start editing? Is posible to have TableEditRow already open with given row? Example code: 

```javascript
<Dialog fullWidth={true} maxWidth={false} open={!!editingRow.length} onClose={this.cancelEditing}>
  <DialogTitle>Edit</DialogTitle>
  <DialogContent>
    <Grid rows={editingRow} columns={columns}>
      <EditingState onCommitChanges={this.addingOrUpdating} />
      <Table />
      <TableHeaderRow />
      <TableEditRow />
      <TableEditColumn showEditCommand messages={editColumnMessages} />
    </Grid>
  </DialogContent>
  <DialogActions>
    <Button onClick={this.cancelEditing} color="primary">
      Close
    </Button>
  </DialogActions>
</Dialog>
```

**Comment by SergeyAlexeev** [comment]
Hi,

To render a row in edit mode you can use the `defaultEditingRowIds` property of the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/) plugin. This [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing#disable-editing-by-a-column) shows it in action. Please note that we are using the `getRowId` function to identify a row.

**Comment by zcuric** [comment]
@SergeyAlexeev Thank you. I did see that in docs, but I've used `editingRowIds` instead, and probably it didn't work because of that.

**Comment by SergeyAlexeev** [comment]
If you are using the `editingRowIds` property, you should handle the `onEditingRowIdsChange` event and update a plugin state manually. This workflow is called '[Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes#controlled-mode)'. Anyway, the `editingRowIds` property should switch related rows to the edit mode. 

See this [sample](https://codesandbox.io/s/j8oj8yjm3) for more details.
