### ISSUE TITLE
Tree Data  rows count   per row after filter

### ISSUE THREAD

**Issue by gwmaster** [DevExpress/devextreme-reactive#1668]
How can i build row counter per row that show total childs and Who remained after filter

(show after filter/total)

![image](https://user-images.githubusercontent.com/5362853/49306595-5c65f100-f4db-11e8-8f8b-7d32bc403a0b.png)

**Comment by SergeyAlexeev** [comment]
Hi,

You can implement the described scenario using our [React Core API](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/). As you can see in the Grid [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-tree-column#plugin-developer-reference), the `TablerTreeColumn` plugin imports the `tableBodyRows` and `getCollapsedRows` [getters](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). They are useful in your case. You can use them in context of a custom [plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/). It can be called 'ChildEnumerator', for instance. This plugin will extend the `tableCell`[template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/) with the two getters pointed above.
 
```jsx
const ChildEnumerator = () => (
  <Plugin>
    <Template
      name="tableCell"
      predicate={({ tableRow, tableColumn }) => isTreeTableCell(tableRow, tableColumn, "name")}
    >
      {params => (
        <TemplateConnector>
          {({ getCollapsedRows, tableBodyRows }) => (
            <TemplatePlaceholder params={{ ...params, getCollapsedRows, tableBodyRows }}  />
          )}
        </TemplateConnector>
      )}
    </Template>
  </Plugin>
);
```
 
Then, use the `getCollapsedRows`, `tableBodyRows` properties to calculate an available child count in a component that renders a tree cell.

See this [sample](https://codesandbox.io/s/5kwqr73z1l) for more details.

**Comment by gwmaster** [comment]
i have some bug after filtering

[sample](https://codesandbox.io/s/y0mqm7j29j)

its not count right after filtering
when it close show Close - (3/1) Open - (3/2)
and there second example by click on "Set Filter"  Close - (3/0) Open - (3/2)

Close:
![image](https://user-images.githubusercontent.com/38719063/49589785-f366f900-f972-11e8-884b-2b5eacb5e4e7.png)

Open:
![image](https://user-images.githubusercontent.com/38719063/49589803-fd88f780-f972-11e8-81ae-baeba441db9f.png)


second example:
Close: 
![image](https://user-images.githubusercontent.com/38719063/49589736-d16d7680-f972-11e8-9870-e8bb4a7fd8a2.png)

Open:
![image](https://user-images.githubusercontent.com/38719063/49589749-da5e4800-f972-11e8-81c7-fa7eacaceef1.png)

**Comment by SergeyAlexeev** [comment]
Currently, the `getCollapsedRows` getter doesn't consider row children. If a parent row doesn't match a filter, it won't be returned even if it contains children that match a filter. Anyway, you can manually calculate row children using initial rows and the `filters` getter that is available in the `TemplateConnector` component.
