### ISSUE TITLE
How to wrap multiple plugins into single component

### ISSUE THREAD

**Issue by Xocix** [DevExpress/devextreme-reactive#1669]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Question

Hi, i have been trying to wrap several DataTypeProviders into 1 component and use that component on the DevExtreme grid without any luck. The reason for this is to save space, i have a lot of columns.

My Providers looks like this:
```
const DateTypeProvider = props => <DataTypeProvider formatterComponent={FormatDateTime} {...props} />;
```
So what i have been trying to do is something like this:
```
const TypeProviders = props => {
    return (
        <React.Fragment>
            <CurrencyTypeProvider for={props.numberColumns} />
            <DateTypeProvider for={props.dateColumns} />
            <StringTypeProvider for={props.stringColumn} />
        </React.Fragment>
    );
};
```
and then i want to pass it down to the grid as props from a another component that takes in the 'for' props:
```
                <DXGrid rows={this.props.rows} columns={this.props.columns}>
                    <CustomPaging totalCount={this.props.totalCount} />
                    {this.props.typeProviders}
                    <Table />
                    <TableHeaderRow />
                    <IntegratedSelection />
                    <TableSelection />
                    <PagingPanel pageSizes={this.props.pageSizes} />
                </DXGrid>
```

This doesnt seem to work for some reason, nothing really happens.
This works fine:
```
                <DXGrid rows={this.props.rows} columns={this.props.columns}>
                    <CustomPaging totalCount={this.props.totalCount} />
                    <CurrencyTypeProvider for={props.numberColumns} />
                    <DateTypeProvider for={props.dateColumns} />
                    <StringTypeProvider for={props.stringColumn} />
                    <Table />
                    <TableHeaderRow />
                    <IntegratedSelection />
                    <TableSelection />
                    <PagingPanel pageSizes={this.props.pageSizes} />
                </DXGrid>
```

**Comment by ushkal** [comment]
Hi,
 
The [PluginHost](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/#plugin-host-component) component should contain only plugin primitives and plugin components, so you can't render React Fragment inside it. Instead, I suggest you wrap your data type providers in a [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/#plugin-component) and render it in a grid. 
I've created a [sample project](https://codesandbox.io/s/23wpv5zp7y) for your reference.

**Comment by Xocix** [comment]
Hi ushkal, thanks for explain the problem and giving me the sample project. I have tried following the example project and i have succeeded, it works perfectly!

I will close this issue.
