### ISSUE TITLE
PagingPanel containerComponent is not optional (TypeScript)

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1671]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When using with TypeScript, PagingPanel's containerComponent is not optional in the definition, forcing me to provide this prop

### Expected Behaviour
This prop is optional

### Environment

- devextreme-reactive: 1.9.0
- react: 16
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi,
 
Please provide information on how you use the [DevExtreme React Grid.](https://devexpress.github.io/devextreme-reactive/react/grid/)
Our theme packages (`@devexpress/dx-react-grid-material-ui/ ..bootstrap3/ ..bootstrap4`) include `.d.ts` files with following code
 
```tsx
export interface PagingPanelProps {
/** A component that renders the paging panel. */
containerComponent?: React.ComponentType<PagingPanelBase.ContainerProps>;
/** The page sizes that a user can select. */
pageSizes?: Array<number>;
/** An object that specifies the localization messages. */
messages?: PagingPanelBase.LocalizationMessages;
}
```
 
and `containerComponent` is an optional property.

**Comment by vtrphan** [comment]
Hi, i use React-Grid v 1.9.0, and in the dx-react-grid.d.ts file, the containerComponent is not optional.

`export interface PagingPanelProps {
  /** A component that renders the paging panel. */
  containerComponent: React.ComponentType<PagingPanel.ContainerProps>;
  /** The page sizes that a user can select. */
  pageSizes?: Array<number>;
  /** An object that specifies the localization messages. */
  messages?: PagingPanel.LocalizationMessages;
}`

I update the React-grid package with npm-install. Or is this type definition file somehow outdated?

**Comment by MaximKudriavtsev** [comment]
In basic scenarios, you should use the React Grid `@devexpress/dx-react-grid` with one of these visual packages

`@devexpress/dx-react-grid-material-ui`
`@devexpress/dx-react-grid-bootstrap4`
`@devexpress/dx-react-grid-bootstrap3`

For more information, follow our [Getting Started](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/#installation) guide. Also, we have a TypeScript [example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/typescript/).

If you want to create a custom theme based on the dx-react-grid, you should follow this [thread](https://github.com/DevExpress/devextreme-reactive/issues/1318).

**Comment by vtrphan** [comment]
i do use it with react-grid-material-ui. But in the definition file, the containerComponent prop is not optional.

**Comment by MaximKudriavtsev** [comment]
It seems that you import the PagingPanel plugin from `dx-react-grid`.
 
You should import all visual plugins from visual packages. Check the [Plugin Types](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-types) section.

https://codesandbox.io/s/xlopvkjyl4

**Comment by vtrphan** [comment]
yes, that was indeed the case. I was confused! Thank you. Problem has been solved.

**Comment by shwekhine** [comment]
MaximKudriavtsev - thanks. that helped me out.
