### ISSUE TITLE
Unable to implement custom TableColumnResizing 

### ISSUE THREAD

**Issue by rao123dk** [DevExpress/devextreme-reactive#1672]
- [ X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I am providing same props according to this docs [https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/](url) .
But Nothing happening. Even its html elements not appearing in the DOM.
  

### Expected Behaviour
It should work.

### Steps to Reproduce (for Bugs)

<TableColumnResizing
                        columnWidths={columnWidths}
                        minColumnWidth={10}
                        defaultColumnWidths={columnWidths}
                        onColumnWidthsChange={this.onColumnWidthChange}
  />

### Environment

- @devexpress/dx-react-core: 1.8.0
- react: 16.4.2
- browser: Chrome 70.0.3538.77
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by rao123dk** [comment]
Please send me one custom working Table Column Resizing demo.

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please clarify what the 'custom working Table Column Resizing demo' means? What customization do you want to implement?

Meanwhile, did you see this [article](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/) with the source code that you can use as a starting point?

**Comment by rao123dk** [comment]
I have followed this [link](https://codesandbox.io/s/yjn357wwlv)  for custom theme. could you please guide how could I implement tableColumnResizing feature in this.

**Comment by Ekta3012** [comment]
> I have followed this [link](https://codesandbox.io/s/yjn357wwlv) for custom theme. could you please guide how could I implement tableColumnResizing feature in this.

I am also facing the same issue @SergeyAlexeev .

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification.

If you are working on a custom theme, you can use any of our theme packages(dx-react-grid-bootstrap3, dx-react-grid-bootstrap4, dx-react-grid-material-ui) to start.

Let's look at the 'dx-react-grid-bootstrap3' [sources](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-bootstrap3/src). There are two folders - 'plugins' and 'templates'. The 'plugins' source contains React components that [wrap](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/src/plugins/table-header-row.jsx#L10) the related plugins from the 'dx-react-grid' package, but don't contain html tags or styles. They use components form the 'templates' to render UI.

So, to implement the column resizing feature in you custom theme you need to create the 'TableColumnResizing' plugin and templates that are responsible for related UI elements rendering, such as table header cell and resizing control. 

I've created a [sample](https://codesandbox.io/s/4xom180v14) that shows the described approach in action. Please note, I [skip the sorting and grouping features](https://codesandbox.io/s/4xom180v14?module=%2Fsrc%2Fplugins%2Ftable-header-row.js) for demo purposes.

**Comment by rao123dk** [comment]
Hi, Thanks for your quick answer, Actually again one new problems occurs while implementing with Typescript. Actually I forgot to mention before thread.
sample code is this:- 

import { withComponents } from "@devexpress/dx-react-core";
import { TableHeaderRow as TableHeaderRowBase } from "@devexpress/dx-react-grid";
import { TableHeaderCell as Cell } from "../templates/table-header-cell";
import { TableRow as Row } from "../templates/table-row";
// import { SortLabel } from "../templates/table-header-cell/sort-label";
// import { GroupButton } from "../templates/table-header-cell/group-button";
import { Title } from "../templates/table-header-cell/title";
import { Content } from "../templates/table-header-cell/content";
 
export const TableHeaderRow = withComponents({
  Cell,
  Row,
  Content,
  SortLabel: null,
  Title,
  GroupButton: null
})(TableHeaderRowBase);

TableHeaderRow.ROW_TYPE = TableHeaderRowBase.ROW_TYPE;


Then **withComponents** giving an error "'withComponents' only refers to a type, but is being used as a value here."

**Comment by SergeyAlexeev** [comment]
Currently, we don't provide a TypeScript definition for the `withComponents` function.

However, you can create a plugin without the `withComponents` function:

```jsx
export class TableHeaderRow extends React.PureComponent {
  render() {
    return (
      <TableHeaderRowBase
        cellComponent={Cell}
        rowComponent={Row}
        contentComponent={Content}
        titleComponent={Title}
        sortLabelComponent={null}
        groupButtonComponent={null}
        {...this.props}
      />
    );
  }
}
```

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by rao123dk** [comment]
Thanks working fine.
