### ISSUE TITLE
How to change a predefined text in the visual plugins

### ISSUE THREAD

**Issue by Nusinka** [DevExpress/devextreme-reactive#1676]
- [х] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I'm using React Grid with material-ui

Please help. How can I change filterPlaceholder in TableFilterRow?

**Comment by MaximKudriavtsev** [comment]
Hi,
 
To change all predefined text in all Reactive Components ([Grid](https://devexpress.github.io/devextreme-reactive/react/grid/), [Chart](https://devexpress.github.io/devextreme-reactive/react/chart/), [Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/)) use the plugin's `messages` property. See the [Localization guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/localization/).
 
To change the filter placeholder text, define the `messages` property of the `TableFilterRow` plugin with the following shape.
 
```jsx
..
<TableFilterRow
  messages={{ filterPlaceholder: 'My Placeholder Text' }}
/>
..
```
 
To see what properties are included in the messages object refer to the [Localization Messages](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#localization-messages) section of plugin's API reference.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
