### ISSUE TITLE
How to pass Row data into button rendered inside the row ?

### ISSUE THREAD

**Issue by TITAN9389** [DevExpress/devextreme-reactive#1688]
Need Help !
i would like to achieve some custom functions on the table ( rendering view,edit,delete) buttons and will need the the current row data which the button on it and pass to that button onClick ?

here is what i want to get. ( need at least id of my row data to pass and do something on button click ).
![image](https://user-images.githubusercontent.com/27279495/49693593-98aae880-fb90-11e8-9214-9827ed5e90fb.png)

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

using latest versions for all.
thanks in advance.

**Comment by ujwaldhakal** [comment]
I think i have run into similar issue and found out this 
` <Table cellComponent={this.getCell}></Table> `

`    getCell = (props) => {
        if (props.column.name.includes('actions')) {

            return (
                <Table.Cell>
                    <IconButton>
                        <Icon> edit </Icon>
                    </IconButton>
                </Table.Cell>
            )
        }

        return <Table.Cell {...props} />;

    }`
getCell runs on every loop all you need to do is define your actions like this

**Comment by TITAN9389** [comment]
> I think i have run into similar issue and found out this
> `<Table cellComponent={this.getCell}></Table>`
> 
> ` getCell = (props) => {
> if (props.column.name.includes('actions')) {
> 
> ```
>         return (
>             <Table.Cell>
>                 <IconButton>
>                     <Icon> edit </Icon>
>                 </IconButton>
>             </Table.Cell>
>         )
>     }
> 
>     return <Table.Cell {...props} />;
> 
> }`
> ```
> getCell runs on every loop all you need to do is define your actions like this
> 
> More on [Table reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/)
> 
> [This issue has already been filed by lrossy](https://github.com/DevExpress/devextreme-reactive/issues/639)

but does it pass the data of the row to that iconButton ?
