### ISSUE TITLE
bit values not rendered, responsiveness #875 but for bootstrap ? 

### ISSUE THREAD

**Issue by AsimRamay** [DevExpress/devextreme-reactive#1689]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
(at least i cant find it with the wording i used)

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
![image](https://user-images.githubusercontent.com/16746011/49712129-0e00e100-fc97-11e8-85d7-8e71ff56a1e1.png)

![image](https://user-images.githubusercontent.com/16746011/49712138-1ce79380-fc97-11e8-93fd-65b09d1c47bb.png)

### Expected Behaviour
i want bit values to render and they are currently not rendering even though data is there,

i want to add column datatypes to columns as well as mask some columns how would i do that dynamically like i have done for title in Picture 2 above , according to the documentation u can add standard datatype providers (without customizing them) for the widgets but i have only found custom datatype providers for the dxgrid (and its documentation)  

i want columns to resize like the example given in https://github.com/DevExpress/devextreme-reactive/issues/876
i have been able to do this with material ui but am not sure how to go about this with bootstrap

### Environment
material ui was only installed to check the example from issue 876 works currently (and it does)
{
  "name": "parkmanager18",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@blueprintjs/core": "^3.7.0",
    "@blueprintjs/datetime": "^3.3.0",
    "@blueprintjs/icons": "^3.2.0",
    "@blueprintjs/select": "^3.2.0",
    "@blueprintjs/table": "^3.2.0",
    "@blueprintjs/timezone": "^3.1.0",
    "@devexpress/dx-core": "^1.9.0",
    "@devexpress/dx-react-core": "^1.9.0",
    "@devexpress/dx-react-grid": "^1.9.0",
    "@devexpress/dx-react-grid-bootstrap4": "^1.9.0",
    "@devexpress/dx-react-grid-material-ui": "^1.9.1",
    "@material-ui/core": "^3.6.2",
    "@material-ui/icons": "^3.0.1",
    "bootstrap": "^4.1.3",
    "devextreme": "^18.2.3",
    "devextreme-react": "^18.2.3",
    "fastify": "^1.12.1",
    "fastify-postgres": "^1.3.1",
    "history": "^4.7.2",
    "open-iconic": "^1.1.1",
    "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "reactstrap": "^6.5.0"
  },
  "homepage": "./",
  "main": "src/main.js",
  "scripts": {
    "start": "nf start -p 3000",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "electron": "electron .",
    "electron-start": "node src/electron-wait-react",
    "react-start": "react-scripts start",
    "fastify-start": "node server/server"
  },
  "proxy": "http://localhost:3101",
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "electron": "^3.0.4",
    "foreman": "^3.0.1",
    "pg-native": "^3.0.0",
    "react-scripts": "2.0.4"
  }
}

**Comment by SergeyAlexeev** [comment]
Hi,

I'm afraid I don't understand your question.

> i want bit values to render 

What does the 'bit values' mean? According to your [image](https://user-images.githubusercontent.com/16746011/49712129-0e00e100-fc97-11e8-85d7-8e71ff56a1e1.png), it's a boolean value, right? Is so, you can use the `DataTypeProvider` plugin to render it. See this [demo](https://codesandbox.io/s/mj9y78p92x) for more details.
 
> i want columns to resize like the example given in #876

Please refer to this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals#multiline-cells).

**Comment by AsimRamay** [comment]
@SergeyAlexeev 
yes i mean Boolean, i sometimes accidentally call it bit cause some databases have the Boolean listed as that,
thank you very much for pointing me to the correct demos, it has allowed me to make a working solution,
i will close the issue now
