### ISSUE TITLE
Change icon of TableColumnVisibility

### ISSUE THREAD

**Issue by slava-lu** [DevExpress/devextreme-reactive#1692]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

How can I change the 'eye' icon of TableColumnVisibility to my custom Icon from material-UI?

**Comment by ushkal** [comment]
Hi,
 
You can use the `toggleButtonComponent `property of the `ColumnChooser `plugin. As a starting point, you can take [the code of our toggle button](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/column-chooser/toggle-button.jsx) and replace the `VisibilityOff` icon with yours. I've prepared a [sample project](https://codesandbox.io/s/mj34qpv09j) for your reference.

**Comment by slava-lu** [comment]
Thanks. Works perfectly!
