### ISSUE TITLE
Default current page 0 instead of 1 ?

### ISSUE THREAD

**Issue by ujwaldhakal** [DevExpress/devextreme-reactive#1694]
While using table component on `PagingState`  I was not able to change defaultCurrentPage as 1 instead of 0.

Why is currentPage denoted as 0 ? As far as i know 0 page means empty data state and page 1 means 1st page but in plugin. Its creating inconsistency or extra code has to be written to make 0 default 1 . Is there any easiest solution for this? 

I'm using ...
  React Grid

**Comment by SergeyAlexeev** [comment]
Hi,

Actually, the `defaultCurrentPage` property contains the current page index. It's a common practice in programming languages to mark the first array item as 0. That's why we are going the same way here. Would you please clarify why you want to use 1 instead of 0 as a current page?

**Comment by ujwaldhakal** [comment]
Page and array are similar thing i.e organizing data  so if you compare with real world then page and array are two different things consider page as a book where you have data in one page . If you realize  no any page starts with 0 it always starts with page 1. So if you are going to use this feature with api then you have change your api with default page 0 which doesnt make any sense. It would have been better if there were any custom preferences for default page.
