### ISSUE TITLE
TypeError: pluginHost.get is not a function

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1697]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
After updating to React Grid 1.9.1 (used with typescript, material-ui theme and Material-ui v.3.6.2, the grid stopped working and threw error: 

```
TypeError: pluginHost.get is not a function
492 | 
  493 | var getAvailableGetters = function getAvailableGetters(pluginHost) {
  494 |   var getGetterValue = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : function (getterName) {
> 495 |     return pluginHost.get("".concat(getterName, "Getter"));
  496 |   };
  497 |   var trackedDependencies = {};
  498 |   var getters;
```

### Expected Behaviour
React-grid continues to render normally

### Environment

- devextreme-reactive: xxx
- react: 16.4.2
- browser: Chrome 70
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.6.2

**Comment by ushkal** [comment]
Hi,
 
We could not reproduce the issue on our side. Please provide us with a sample project where the problem is replicated. You can use our [codesandbox project](https://codesandbox.io/s/13qvz1qqzl) as a starting point. 
Also try to upgrade React to version 16.6.

**Comment by vtrphan** [comment]
Yes, upgrading to React 16.6 works! Thank you!

**Comment by tx4x** [comment]
same here, typescript : 3.0.3 | react 16.6.3

**Comment by avtarvikas** [comment]
I tried upgrading to react 16.6 but still i am getting error this is my json file

`{
  "version": "0.2.0",
  "private": true,
  "dependencies": {
    "@devexpress/dx-react-core": "^1.10.0",
    "@devexpress/dx-react-grid": "^1.10.0",
    "@devexpress/dx-react-grid-material-ui": "^1.10.0",
    "@material-ui/core": "^3.1.1",
    "@material-ui/icons": "^3.0.1",
    "axios": "^0.17.0",
    "clevertap-react": "^1.0.0",
    "history": "^4.7.2",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "lodash": "^4.17.4",
    "material-ui": "^0.19.4",
    "mixpanel-browser": "^2.13.0",
    "moment": "^2.19.3",
    "prettier": "^1.9.2",
    "react": "16.3.1",
    "react-dom": "16.3.1",
    "react-loadable": "^5.3.1",
    "react-places-autocomplete": "^5.4.3",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.9",
    "react-scripts": "^1.1.1",
    "react-scroll-to": "^1.1.2",
    "redux": "^3.7.2",
    "redux-persist": "^5.9.1",
    "redux-thunk": "^2.2.0",
    "styled-components": "^2.4.0",
    "voucher-calculation": "1.2.12"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      "prettier --single-quote --write",
      "git add"
    ]
  },
  "scripts": {
    "precommit": "lint-staged",
    "start": "react-scripts start",
    "build": "react-scripts build && rm build/static/js/*.map",
    "build-start": "serve -s build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.4.0",
    "@storybook/addon-links": "^3.4.0",
    "@storybook/addons": "^3.4.0",
    "@storybook/react": "^3.4.0",
    "babel-core": "^6.26.0",
    "babel-runtime": "^6.26.0"
  },
  "prettier": {
    "singleQuote": true
  }
}
`

**Comment by tanmaiaccion** [comment]
@avtarvikas did you manage to resolve this? I am still facing the same issue. Node 8.9.3 and even updated  react to 16.8.2

**Comment by nthgol** [comment]
This is still an issue. Please reopen. @tanmaiaccion  the temporary solution is to use 1.9.0 for all the packages, don't tilda your package.json:
```
"@devexpress/dx-react-core": "1.9.0",
    "@devexpress/dx-react-grid": "1.9.0",
    "@devexpress/dx-react-grid-material-ui": "1.9.0",
```

**Comment by nhuthan** [comment]
same problem

**Comment by SergeyAlexeev** [comment]
@nhuthan would you please provide a codesandbox that shows the problem?

**Comment by avtarvikas** [comment]
> @avtarvikas did you manage to resolve this? I am still facing the same issue. Node 8.9.3 and even updated react to 16.8.2

it was resolved when i used 
`    "@devexpress/dx-react-core": "^1.9.1",
    "@devexpress/dx-react-grid": "^1.9.1",
    "@devexpress/dx-react-grid-material-ui": "^1.9.1",`

but then it still giving me error in production

**Comment by nhuthan** [comment]
I cannot create a codesandbox right now, reproducing the problem is not easy.
But when i make a breakpoint on error code, I see pluginHost is just empty object. Has no "get" function.
![image](https://user-images.githubusercontent.com/12423709/53866671-a8698a00-4024-11e9-80ff-030a1d5bd0b4.png)

**Comment by nhuthan** [comment]
Upgrade react, react-dom, webpack, webpack-*, aspnet-* packages to latest version help me solve the problem. I don't know what the real cause is but it working now.
