### ISSUE TITLE
Data Validation on data grid

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1698]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
It cannot validate data.

### Expected Behaviour

Is it able to validate data input within grid cells using predefined or custom validation rules in this react grid component? For example, adding a validation rule which can assign to each column using its validationRules option. These rules do not allow an end user to enter invalid data into grid cells.

How's about data validation remotely? Some columns are required.

Is that possible?

Thank you.

`validationColumns: [
    { columnName: 'FirstName', validationRules: 'required' }
]`

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the similar [question](https://github.com/DevExpress/devextreme-reactive/issues/475).
