### ISSUE TITLE
React virtual grid performance

### ISSUE THREAD

**Issue by hareaca** [DevExpress/devextreme-reactive#1701]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

It has something in common with [issue](https://github.com/DevExpress/devextreme-reactive/issues/1200), but there version update did the trick. While updating to 1.9.1 no noticeable changes happen. 

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
The virtual grid performance is getting worse (in the shared example is noticeable that scroll gets slow, as well columns reorder) when adding more columns while having a lot of rows as well.

### Expected Behaviour
The performance to not decrease that much.

### Steps to Reproduce (for Bugs)

Created a [codesandbox](https://codesandbox.io/s/rmj5zo494m).

### Environment

- devextreme-reactive: 1.8.0
- react: 16.6.3
- browser: Chrome 70.0.3538.110
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.6.2

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please test your demo in production mode? When you are using codesandbox, a demo is running in development mode. Also, you can check this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/). How does it work on your side?

**Comment by hareaca** [comment]
Yes, its true, the grid is smooth in production mode, didn't think it will be such an big difference.
Still having lag spikes when data is updating, but not sure the issue is coming from the grid. So will investigate and come back with an update.

Thanks!

**Comment by SergeyAlexeev** [comment]
We've discussed a similar question in the context of these issues:  #396, #1707. Please check them out.

**Comment by hareaca** [comment]
@SergeyAlexeev Great. Thanks!
