### ISSUE TITLE
Grid group rows display children quantity

### ISSUE THREAD

**Issue by nowaalex** [DevExpress/devextreme-reactive#1705]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

I want to show quantity of rows in a group title of Grid.
To achieve this I need to pass custom `TableGroupRow.contentComponent`.
I have access to fields like row.value inside my custom implementation of this component, but collapsed rows array is keyed by `Symbol` which is NOT exported from the library, so I need to write ugly code like this:
```
const finder = s => s.toString().includes( "collapsed" );

let COLLAPSED_KEY = "";

const setCollapsedKey = col => {
    const smb = Object.getOwnPropertySymbols( col );
    const n = smb.find( finder );
    if( !n && process.env.NODE_ENV !== "production" ){
        throw new Error( "Collapsed key not found" );
    }
    COLLAPSED_KEY = n;
}

const GroupContentComponent = ({ column, row }) => {

    if( !COLLAPSED_KEY ){
        setCollapsedKey( row );
    }

    const collapsed = row[ COLLAPSED_KEY ];

    return (
        <TableGroupRow.Content column={column} row={row}>
            {row.value} {Array.isArray( collapsed ) ? `(${collapsed.length})` : ""}
        </TableGroupRow.Content>
    );
}

```
Is it possible to export this symbol?

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, the constant you are talking about is private. However, you can implement your scenario using our [React Core API](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/). 

As you can see in documentation, the `IntegratedGrouping` plugin exports the [getCollapsedRows](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-grouping#plugin-developer-reference) getter that returns collapsed rows for a specific row. To use this getter create a custom [plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) as follows:

```jsx
const ItemCounter = () => (
  <Plugin name="ItemCounter">
    <Template
      name="tableCell"
      predicate={({ tableRow }) => isGroupTableRow(tableRow)}
    >
      {params => (
        <TemplateConnector>
          {({ getCollapsedRows }) => {
            const updatedParams = {
              ...params,
              tableRow: {
                ...params.tableRow,
                row: {
                  ...params.tableRow.row,
                  collapsedRows: getCollapsedRows(params.tableRow.row) || []
                }
              }
            };
            return <TemplatePlaceholder params={updatedParams} />;
          }}
        </TemplateConnector>
      )}
    </Template>
  </Plugin>
);
```

Here we calculate collapsed rows and update parameters that are used for group cell rendering. This [guide](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/rendering-markup/) contains detailed information about it.

I've created a [sample](https://codesandbox.io/s/lzvqypl5q) that shows this approach in action.

We'll discuss how to simplify your use-case implementation in the future.

**Comment by nowaalex** [comment]
Thank you for this approach, it works ok. Next question: is it possible to access summaries inside GroupRow somehow? I want to display summary not only under groups, but also in group titles. I understand, that I can use your approach with getCollapsedRows and do the work of IntegratedSummary manually. But is there a way to use ready sums of existing plugin?
