### ISSUE TITLE
ReadonlyArray Grid props

### ISSUE THREAD

**Issue by jeremybparagon** [DevExpress/devextreme-reactive#1708]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The `rows` prop for `Grid` expects a mutable array (`Array<any>`).

### Expected Behaviour

It should accept a `ReadonlyArray<any>`.

### Link to Docs

https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/

**Comment by churkin** [comment]
Fixed https://github.com/DevExpress/devextreme-reactive/commit/23ba6c54c7929af811ceae0ac87260f2bd45c25b
