### ISSUE TITLE
How to expand a specific row in the TreeDataState plugin

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1712]
I wrote this Treedata example:
https://codesandbox.io/s/vv4ok16nz3

Now, I want to open a specific 3° level of tree with this code: '2.1.6'
bat not work.

Is a bug or my code error?
Carlo

**Comment by MaximKudriavtsev** [comment]
Hi,
 
You should pass the row id to the `defaultExpandedRowIds` property instead of its value.
 
The updated example https://codesandbox.io/s/xpxzomqxwz

**Comment by ccamusso** [comment]
ok, is possible set custom row ID inside array data?

**Comment by MaximKudriavtsev** [comment]
Sure, you should define the [Grid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/) component property `getRowId`. Note that rows id must be equal.
When the `getRowId` property is defined, all grid plugins use your custom `id` filed. Before it, Grid uses row numbers as row ids.
 
Here is the updated example - https://codesandbox.io/s/xpxzomqxwz

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
