### ISSUE TITLE
Destructured out props in template components stop customizability if not propagated down to library component

### ISSUE THREAD

**Issue by emattias** [DevExpress/devextreme-reactive#1723]
I cant override a certain styling using @material-uis [css api](https://material-ui.com/customization/overrides/#overriding-with-classes) because the table-cell template component defined in `dx-react-grid-material-ui` destructures out the whole classes prop here: https://github.com/DevExpress/devextreme-reactive/blob/d7f345cc4020e77c5eb8ff64a8015eba8ca5de70/packages/dx-react-grid-material-ui/src/templates/table-cell.jsx#L33 and it only send some keys of the classes component down to the material-ui component here: https://github.com/DevExpress/devextreme-reactive/blob/d7f345cc4020e77c5eb8ff64a8015eba8ca5de70/packages/dx-react-grid-material-ui/src/templates/table-cell.jsx#L45

Perhaps you can do something like this: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Select/Select.js#L72

**Comment by emattias** [comment]
Another option might be to add something like `MUITableCellProps` prop to the `dx-react-grid-material-ui` `TableCell` component. Although since it sets the `footer` classes key the classes prop probably needs to be merged anyway.. 😅

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, you can use the `className` property to customize the cell appearance. Please look at this [example](https://codesandbox.io/s/1yx22zwy4q). Does it meet your needs?

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by emattias** [comment]
I have another case that would be solved if you add the possibility to send props down to a specific component that a devexpress component is using. 

I am trying to make it so that the `SortLabel` component is shown on hover, not only when the the table is ordered by that specific column. As you see [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/sort-label.jsx#L66) the `active` prop (which controls the visibility of the sortlabel) is hardcoded to only be `true` when `direction` prop is `truthy`.

If you would have something like `MUITableSortLabelProps` prop that takes an object I could control this without having to override (and replicate) everthing that the devexpress `SortLabel` does.

Here you can see an example of what I am talking about. This is how you can set props on the input component when using the material-ui [`TextField` component](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/TextField/TextField.js#L142). And heres the documentation for that `TextField` component: https://material-ui.com/api/text-field/
