### ISSUE TITLE
Format column

### ISSUE THREAD

**Issue by greenallparagonuk** [DevExpress/devextreme-reactive#173]
I have two requests really, I've got a datetime field I would like to display in a user friendly manor, currently shows as "2017-06-21T14:30:04.7403971+01:00". Should I format this in my controller before sending the json to the client page?

And the other is I have a sub-class/sub-document in my json, I tried pushing it into the grid as a field, but it doesn't like it. It doesn't give an error, but it also doesn't display the grid.

**Comment by kvet** [comment]
Hi,
 
We've already had a similar question: #114. Custom cell template should help you display data in both cases.

**Comment by greenallparagonuk** [comment]
WOW cool! just needed that.
