### ISSUE TITLE
How to hide the Grid's column header

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1733]
Is possible hide column header?

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,
 
Yes, you can remove the `TableHeaderRow` plugin from your application code to hide a column header.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
