### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#1739]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
```
warning " > @devexpress/dx-react-grid@1.10.0" has unmet peer dependency "@devexpress/dx-core@1.10.0".
warning "@devexpress/dx-react-grid > @devexpress/dx-grid-core@1.10.0" has unmet peer dependency "@devexpress/dx-core@1.10.0".
warning " > @devexpress/dx-react-grid-material-ui@1.10.0" has unmet peer dependency "@devexpress/dx-grid-core@1.10.0".
```

### Expected Behaviour

There shouldn't be unmet warnings.

### Environment

- devextreme-reactive: latest
- react: latest
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: latest

**Comment by MaximKudriavtsev** [comment]
Hi @franklixuefei,

Could you please provide information about your `package.json` and the grid component or send us an example? I'm asking this because we weren't able to reproduce any warnings
