### ISSUE TITLE
Persian date support

### ISSUE THREAD

**Issue by j209** [DevExpress/devextreme-reactive#1742]
Hi
Any plan for persian(jalali) Date  support?
[Bootstrap4 PersianDateTime picker](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker)
[Material-ui PersianDateTime picker ](https://material-ui-pickers.firebaseapp.com/localization/persian)

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please clarify what component you are using - Grid, Scheduler, or Chart?

BTW, currently, we are working on our roadmap, which will be available [here](https://js.devexpress.com/Roadmap/). It's very important for us to know which features are very important for you. [Here](https://community.devexpress.com/blogs/javascript/archive/2018/12/29/devextreme-reactive-2019-roadmap-your-vote-counts.aspx) you can quickly vote for these features.

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you have any additional questions.
