### ISSUE TITLE
How to make table header fixed in pagination mode?

### ISSUE THREAD

**Issue by lin-zy1229** [DevExpress/devextreme-reactive#1746]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Row Header is NOT fixed when scrolling in pagination mode.

### Expected Behaviour
Fix Row Header when scrolling in pagination mode.

### Environment

        "@devexpress/dx-react-core": "1.10.0",
        "@devexpress/dx-react-grid": "1.10.0",
        "@devexpress/dx-react-grid-material-ui": "1.10.0",
        "react": "16.6.3",
- browser: Chome

**Comment by ushkal** [comment]
Hi,
 
You can use the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/) plugin to achieve your goal. Please refer to the [following sample](https://codesandbox.io/s/ovqjp3mwz6).

**Comment by lin-zy1229** [comment]
Thanks, but I knew it.
What I want to know is just how to make table header fixed in **pagination mode**.
I need pagination to decrease rendering time.

**Comment by lin-zy1229** [comment]
Perfect, thanks!
I tried it but, I just missed the placing `VirtualTable ` next the `IntegratedPaging`.

**Comment by ushkal** [comment]
You are welcome!
