### ISSUE TITLE
Add input mask to TableFilterRow 

### ISSUE THREAD

**Issue by ivanshinkarenko** [DevExpress/devextreme-reactive#1748]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Can I add input mask to TableFilterRow ?
I have filtering by date & time and I want to make mask like this when someone begin type
"dd/mm/yyyy hh:mm:sss"

### Expected Behaviour
"dd/mm/yyyy hh:mm:sss"

### Environment

- devextreme-reactive: xxx
- react: xxx
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @ivanshinkarenko,


To add input mask override the filter cell component. To customize the filter component define the `TableFilterRow` plugin's `cellComponent` property. Refer to the [Customizing Filter Row Appearance](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#customizing-filter-row-appearance) section to see how to achieve this.
