### ISSUE TITLE
Virtual table width problem (i.e. rest of column got invisible after certain width)

### ISSUE THREAD

**Issue by rao123dk** [DevExpress/devextreme-reactive#1749]
- [  x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid 
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I have implemented a complete table component with own custom [template](https://codesandbox.io/s/4xom180v14). 
As you said in this [link](https://github.com/DevExpress/devextreme-reactive/issues/298#issuecomment-446994191), I followed the same link and my table header fixing problem is fixed, but when I am scrolling my table Horizontally then after certain width rest  table cell/row got hide. What's the problem. Please guide. 
![virtual table](https://user-images.githubusercontent.com/21997833/50832681-efb10280-1374-11e9-993f-535e42622144.png)

### Expected Behaviour
All data. should display.

### Environment

- devextreme-reactive: -1.8.0
- react: 16.4.2
- browser: chrome 70+
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi,
 
Would you please provide us with a sample project where the issue can be seen?

**Comment by ushkal** [comment]
The cause of the problem is that a style passed to the TableContainer component overwrites your 'overflow' style property so this element does not trigger scroll events. To fix this, just merge styles from props with yours. [Here](https://codesandbox.io/s/yk15rn4z19)'s the updated project. Please let me know if it helps.

**Comment by rao123dk** [comment]
Thanks, hiding problem is solved but when I am deleting the column from the table and if I have only one column left then its width would be fit to the entire area of div. but not haapening   [See](https://codesandbox.io/s/3055zn45k6)

**Comment by ushkal** [comment]
This behavior is expected: the column width is set to 200px and a stub header cell fills the remaining space. To make it appear as a single cell I recommend that you apply the same background style to your stub header cell component and show a resizing control on hover only.
