### ISSUE TITLE
How to disable custom field

### ISSUE THREAD

**Issue by zielinskipawel** [DevExpress/devextreme-reactive#1757]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I created component 'BooleanEditor' witch i want to use as a custom field in Grid.
But in edit mode i want to have disable column (but not all column this type).
What is easiest way to send this information to my component BooleanEditor ?

I add "editingEnabled" prop but i dont know how to set up it
```
import React from "react";
import PropTypes from "prop-types";
import FormControlLabel from "@material-ui/core/FormControlLabel";
import Switch from "@material-ui/core/Switch";

const BooleanEditor = ({value, onValueChange, editingEnabled}) => {

  if (value === undefined) {
    value = true;
  }
  return <FormControlLabel
    control={
      <Switch
        checked={value}
        onChange={event => onValueChange(!value)}
        value={value}
        color="primary"
        disabled={!editingEnabled}
      />
    }
    label={value ? "Yes" : "No"} />;
};

BooleanEditor.defaultProps = {
  editingEnabled: true
};
BooleanEditor.propTypes = {
  value: PropTypes.bool,
  onValueChange: PropTypes.any,
  editingEnabled: PropTypes.bool
};

export default BooleanEditor;
```
then in the other component i use it:
```
const BoolTypeProvider = props => (
  <DataTypeProvider
    formatterComponent={BoolFormatter}
    editorComponent={BooleanEditor}
    {...props} />);
```
i setup editingState

```
          <EditingState
            onCommitChanges={this.commitChanges}
            onRowChangesChange={this.rowChanges}
            columnExtensions={editingStateColumnExtensions}
          />
          <BoolTypeProvider
            for={booleanColumns}
          />
```

setup not edited columns like this: 
```
    let booleanColumns = ["VerificationType", "CompanyType"];

    let editingStateColumnExtensions =
      [
        { columnName: "VerificationType", editingEnabled: false },
      ];
```
### Environment

- devextreme-reactive: xxx
- react: 16.7.0
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.7.0

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, you can pass column extensions to the 'BooleanTypeProvider' component manually.

This [sample](https://codesandbox.io/s/1ym32v0jxq) shows how it can be implemented.

**Comment by zielinskipawel** [comment]
work great, thanks!
