### ISSUE TITLE
Passing event to onToggle  in SelectionCell

### ISSUE THREAD

**Issue by yotamberk** [DevExpress/devextreme-reactive#1759]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
`onToggle` in `TableSelection.CellProps` does not have an event as a parameter so I can;t detect (for example) if the shift key is pressed while I'm toggling the checkbox.

### Expected Behaviour
I would like to be able to select multiple checkboxes while holding shift key
(similar to Google Gmail)

**Comment by MaximKudriavtsev** [comment]
Hi,

Please refer to the similar [question](https://github.com/DevExpress/devextreme-reactive/issues/532).

**Comment by yotamberk** [comment]
Although similar, it still doesn't solve my problem. 
I need to do this on the SelectCell and not the row

**Comment by yotamberk** [comment]
Awesome. Thank you very much.
