### ISSUE TITLE
Using nested keys for column definition

### ISSUE THREAD

**Issue by zehbauer** [DevExpress/devextreme-reactive#176]
Having a data structure or row structure like this:
`row = [{id : 1, title: 'example 1', user: {name: "user 1"}}, {id : 2, title: 'example 2', user: {name: "user 2"}}]`
i would suspect that with the following column definition:
`this.state = {
      columns: [
        { name: "id", title: "ID" },
        { name: "title", title: "Title" },
        { name: "user.name", title: "User name" }
      ]
    };`
the grid is well defined and row[i].user.name is used as the value. 
Is there a different syntax to define this or are rows objects always expected to be flat?

**Comment by kvet** [comment]
Hi,
 
Currently, we do not support the nested row structure. A row object is expected to be flat.
 
As a workaround, you can map rows to a flat structure before passing it to Grid.
 
It is also possible to specify templates in order to display a nested structure. Find more at: #114

**Comment by zehbauer** [comment]
Thanks for the quick reply.

**Comment by kvet** [comment]
I've reopened the issue. It will allow you and other customers to track this feature progress.
