### ISSUE TITLE
autofocus on searchpanel rerenders

### ISSUE THREAD

**Issue by carambolas** [DevExpress/devextreme-reactive#1760]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have tried to add autoFocus to the searchpanel via the autoFocus property that's available in material-ui so that the focus is on the searchpanel when the page laods. It works, but each time I start typing in the other filters for example, the focus immediately switches back to the searchpanel instead of staying on the filter itself.

### Expected Behaviour
I don't expect the focus to return to the searchpanel after typing in a different field (with a different focus)

### Steps to Reproduce (for Bugs)

See following codesandbox:
https://codesandbox.io/s/rl17nk212o

### Environment

 (see also condesandbox)
- devextreme-reactive: 1.10
- react: 16.7
- browser: latest chrome
- material-ui: 3.8.3

**Comment by MaximKudriavtsev** [comment]
Hi @carambolas,

To prevent an element from being automatically focused each time it is re-rendered, do not create a new function in the render method. 
 
before
```jsx
<SearchPanel
  inputComponent={props => <SearchPanelInput {...props} />}
/>
```
 
after
```jsx
<SearchPanel
  inputComponent={SearchPanelInput}
/>
```
 
I updated your [example](https://codesandbox.io/s/pjn4555xr7). Let me know if you have additional questions.

**Comment by carambolas** [comment]
Thanks, that did the trick!
