### ISSUE TITLE
React Grid grouping row value is `undefined`

### ISSUE THREAD

**Issue by hareaca** [DevExpress/devextreme-reactive#1761]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When grouping by a column that could be undefined, the resulted row for undefined group looks like this:

```js
{
    compoundKey: "undefined",
    groupedBy: "column-name",
    key: "undefined",
    value: "undefined",
    ...
}
```

I understand that the key should be string, but don't get why value should be "undefined" as well.

After trying to see why this is happening, i found the next piece of code in integrated-grouping plugin that explains why value is "undefined":

```code
const { key, value = key } = groupCriteria(getCellValue(row, columnName), row);
```

Are there any reasons for having this behavior?

### Environment

- devextreme-reactive: 1.10.0

**Comment by hareaca** [comment]
Hello @MaximKudriavtsev ,

I faced this while using formatter components. It's strange that if we rely on some logic where we require value to not be undefined, now we also have to check if value is not "undefined", and i don't really think that it's a good idea to do a string check in the formatter component.

If we still want to show "undefined" to that group, maybe it would be better to have this integrated into the view component, instead of having it in groupedRows method.

**Comment by MaximKudriavtsev** [comment]
Thank you for your clarification. We will consider ways to resolve this problem.
