### ISSUE TITLE
defaultExpandedGroups expand second column

### ISSUE THREAD

**Issue by artemk0** [DevExpress/devextreme-reactive#1762]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Hi,

let's say I have the following table:

ColOne | ColTwo | ColThree
------ | ------ | --------
A | X | aaa
A | X | bbb
A | Y | ccc
B | X | ddd

My goal is to group content by first two columns and have **all** the groups expanded by default.

So I'm starting with defining the groups like:
`<GroupingState grouping={[{ columnName: 'ColOne' }, { columnName: 'ColTwo' }]} />`

As I've figured out (correct me if I'm wrong) there is no way to specify something like `defaultExpandedGroups={['ALL']}` - the groups (row values) should be defined explicitly. My next step is to define the default expanded groups:
`<GroupingState
          grouping={[{ columnName: 'ColOne' }, { columnName: 'ColTwo' }]} defaultExpandedGroups={['A', 'B']} />`

this works perfectly fine to expand the first group level. However how can I specify that the secod group level should be expanded by default as well?

The following doesn't work for me: 

`<GroupingState
          grouping={[{ columnName: 'ColOne' }, { columnName: 'ColTwo' }]} defaultExpandedGroups={['A', 'B', 'X', 'Y']} />`

### Environment

- devextreme-reactive: none
- react: 16.7.0
- browser: FF 64.0.2
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.6.2

**Comment by MaximKudriavtsev** [comment]
Hi @artemk0,

This issue is a duplicate. We are closing it and suggest writing in the [initial topic](https://github.com/DevExpress/devextreme-reactive/issues/756).
