### ISSUE TITLE
VirtualTable not rendering all rows when height changes

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#1763]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

On initial load, rows=[] and height is 160 (the height of the no data component). Rows are then fetched from the API, and we recalculate the height and pass it to the virtual table. The height is correct in the app, but only 6 rows are rendered, and the rest of the height is filled with some dummy row.

If I return null instead when the rows array is empty, the first render pass is correct, so this looks like a similar issue to https://github.com/DevExpress/devextreme-reactive/issues/1627 - maybe it was not properly fixed in the most recent release.

### Expected Behaviour

The table should render all rows passed in to it.

### Steps to Reproduce (for Bugs)

https://codesandbox.io/s/4jwj2kovx9

Click add more rows - note that even though height is being calculated correctly, only 6 rows appear in the table and in the DOM

### Environment

- devextreme-reactive: 1.10.0
- react: 16.6.3
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.7.0

**Comment by stclairdaniel** [comment]
That's so bizarre - here is a gif of what happens when I try it:
![rows](https://user-images.githubusercontent.com/14972752/51259995-20d79700-1962-11e9-9331-ff5dc908461f.gif)

Anyway, I will try replacing the VirtualTable with a Table in my local project and see if it fixes the issue.

**Comment by zhdanouskikh** [comment]
Having this issue reproduced too. On first render everything is ok. I have 10 rows and all of them are rendered. But if you resize window to smaller size and then resize back - I will have only few rows and stub element in the bottom of the table for the resized delta height.

**Comment by shaabanban** [comment]
I have been banging my head on my keyboard trying to resolve this issue. It seems like the windows resize event isn't being handled properly by the table which is causing rows to disappear when you resize.
![out](https://user-images.githubusercontent.com/4308274/52333947-91834800-2a24-11e9-9644-59b0eaa46cbc.gif)
