### ISSUE TITLE
How to place custom UI controls outside the Grid

### ISSUE THREAD

**Issue by Kison** [DevExpress/devextreme-reactive#1767]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Question
I have specific UI which requires to split ColumnChooser and Grid. I tried to place it outside of Grid but seems that such manipulation is not supports by library. Can someone give me any suggestion on how to place ColumnChooser outside of Grid? Thanks in advance.

**Comment by MaximKudriavtsev** [comment]
Hi @Kison,
 
To implement your custom outside UI controls for built-in React Grid features, you need to use a [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) and change necessary properties.
 
The following [example](https://codesandbox.io/s/l32y304rzl) demonstrates how to place the ColumnChooser UI outside the React Grid.

**Comment by Kison** [comment]
Hey, @MaximKudriavtsev. Thanks for solution, I will try it at some point today.

**Comment by Kison** [comment]
Thanks @MaximKudriavtsev. Example helped a lot.
