### ISSUE TITLE
How to add "Rows Selected" to PagingPanel, not outside of Grid?

### ISSUE THREAD

**Issue by lin-zy1229** [DevExpress/devextreme-reactive#1770]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I am using this code.
```
<Paper>
    <Grid>
    ... ...
    </Grid>
    <div>
        <span>Rows Selected: <strong>{selection.length}</strong></span>
    </div>
</Paper>
```
It shows "Row Selected" div in next row in the PagingPanel.

![image](https://user-images.githubusercontent.com/13885833/51195692-91fa5880-1928-11e9-9a20-dde4a98bf3f1.png)

### Expected Behaviour
I wanted it shows "Row Selected" in same row with "PagingPanel". so that I can save the space.

### Environment

dx-react-grid": "1.10.0"
dx-react-grid-material-ui": "1.10.0"
- react: latest
- bootstrap: none
- react-bootstrap: none
"@material-ui/core": "3.6.0",

**Comment by ushkal** [comment]
Hi, 
 
You can create a plugin that renders the number of selected rows in the "footer" template. Here is a [sample project](https://codesandbox.io/s/52x52vk0q4) for your reference.
