### ISSUE TITLE
How to set the height and add a vertical scrollbar to the React Grid

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1779]
I have this test https://codesandbox.io/s/9zok7jx4ro and I would like to set the fixed height for the grid. I expect that vertical scrollbars to the grid (not to the page) will appear if the content of the grid will be beyond the allocated height. This is my current task. In the future I would like set the properties of the grid so that it fills all the available vertical (and horizontal) space allocated for the grid by some external div element. The grid is really nice but I am desperately stuck with the configuration. Thanks.

**Comment by MaximKudriavtsev** [comment]
Hi @alex153410,

We suggest using the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/) plugin if you want to have a vertical scroll bar. Refer to the following [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#stretching-out-to-parent-element-size) to see how to implement auto height.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
