### ISSUE TITLE
ctrl in the controlled mode sorting for reset

### ISSUE THREAD

**Issue by iposokhin** [DevExpress/devextreme-reactive#1780]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have multisorting in the controlled mode, but I don't reset column sorting using CTRL. How it implement? The onSortingChange event generate only data either [{direction: 'asc', columnName:'someName'}] or [{direction: 'desc', columnName:'someName'}]. 

### Expected Behaviour
I want to recieve event with data. In this case I could see the key code, for example CTRL. If I don't understand something, please explain.

### Environment

- devextreme-reactive: 1.10
- react: 16.7

**Comment by ushkal** [comment]
Hi,
 
This behavior is enabled out of the box: holding a shift key enables multi-sorting and a ctrl key cancels sorting by a particular column. See the [Sorting guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/) for your reference. 
However, if you want to implement your own logic, I suggest you implement your own SortLabel then provide the onClick event handler where you can call the onSort method with parameters based on a click event. See this [sample project](https://codesandbox.io/s/4qvqn4xkq9) for your reference.

**Comment by iposokhin** [comment]
I forgot to say that I use Custom Label. It hasn't this behavior. So, I should use custom onclick?

**Comment by ushkal** [comment]
Hi @iposokhin ,
 
>  I should use custom onclick?

Yes, that's correct. You can use a sample project from my previous message for you reference. In this project, the custom onClick function is declared on lines 17-21.
 
Sorry for the late response.
