### ISSUE TITLE
in cell editing without clicking on Edit button

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1786]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Now we need to click on the Edit button by EditingState plugin. After we new the changes, we click on Save button to  apply the changes. 

### Expected Behaviour
We can click on any of the cells and do the editing. Then just have to click on a Save button to save the changes.

Are we able to do this?
![screenshot](https://user-images.githubusercontent.com/42453813/51415570-1d433c00-1b2b-11e9-9dbd-79ce5baf68b7.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

We've already registered the similar feature request #931.
