### ISSUE TITLE
The highlightSelected prop for TableSelection does not work with Bootstrap table

### ISSUE THREAD

**Issue by glenpadua** [DevExpress/devextreme-reactive#1794]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

Adding the `highlightSelected` prop does not highlight the row when selected. I noticed the demo here - https://stackblitz.com/edit/react-ranopq?file=index.js and a class of `active` is added to the `<tr>` whenever clicked. But in my table it does not seem to happen. The selection command works fine as expected with the checkbox. Any idea why this may be happening. I tried the same with a Bootstrap 3 table as well. 

Also the demo above that I found was from this issue - https://github.com/DevExpress/devextreme-reactive/issues/477 and it looks like `TableView` is now deprecated in favour of just `Table` which is where it doesn't seem to work. I've added a demo link below.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
The highlight isn't being applied to the selected row because the class of `active` isn't being added to the <tr>

### Expected Behaviour
The row should be highlighted when the `highlightSelected` prop is provided for TableSelection

### Steps to Reproduce (for Bugs)
https://stackblitz.com/edit/react-p6l2wd?file=index.js

### Environment

- devextreme-reactive: xxx
- react: ^16.2.0
- browser: All
- bootstrap: ^4.0.0
- react-bootstrap: none
- material-ui: none
- "@devexpress/dx-react-core": "^1.10.0",
- "@devexpress/dx-react-grid": "^1.10.0",
- "@devexpress/dx-react-grid-bootstrap4": "^1.10.0",

Edit: Updated demo link.

**Comment by ushkal** [comment]
Hi,

We have renamed the highlightSelected property to highlightRow in version 1.0.0-beta.2. Here's your updated sample: https://stackblitz.com/edit/react-qrlve2?file=index.js.
