### ISSUE TITLE
React VirtualTable auto height resize issue

### ISSUE THREAD

**Issue by hareaca** [DevExpress/devextreme-reactive#1795]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
While using VirtualTable auto height property ([guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#stretching-out-to-parent-element-size)) i noticed that the grid is no longer stretching out to Parent Element Size after resizing in certain cases.

### Expected Behaviour
Should always stretch out to Parent Element Size.

### Steps to Reproduce (for Bugs)

[here](https://codesandbox.io/s/rmj5zo494m) is a demo for this.

To reproduce this issue:
1. Start with a bigger size window, so vertical scroll should not be visible;
2. Resize window so it should force vertical scroll;
3. Resize window to fit again all content;
4. Now you can see that horizontal scroll bar is visible after last row, instead of being at the bottom of the window;

### Environment

- devextreme-reactive: 1.10.0
- react: 16.6.3
- browser: Chrome Version 71.0.3578.98
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.6.2

**Comment by alex153410** [comment]
I doubt that the https://github.com/DevExpress/devextreme-reactive/pull/1796/commits/66c10819b17f21532cb4fe3cf8668ce3bf8bceee solves the test case I have provided in https://codesandbox.io/s/jnzx32q28w The following style is the essence of this pull request:
```
.dx-g-bs4-table-container {
  flex: 1;
}
```
But nothing changes after I add it to my codesandbox code...

**Comment by ushkal** [comment]
Hi @alex153410

You need to include the Bootstrap CSS to your page to make our Grid work properly. Then make a 'main' element flexible, here's an [updated sample](https://codesandbox.io/s/14llpvw663).
