### ISSUE TITLE
I can't see cancel command in editing mode when I don't use "showDeleteCommand" for TableEditColumn.

### ISSUE THREAD

**Issue by lin-zy1229** [DevExpress/devextreme-reactive#1800]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I only need EDIT button and don't need delete command in TableEditColumn.
So, I added only "showEditCommand" property, and not used "showDeleteCommand".
Well, I can't see "Cancel command" when I tried to EDIT column. 
I can see only "Save command" at that time.

### Expected Behaviour

I want to see "Cancel command", in case I don't use "showDeleteCommand".

### Environment

- devextreme-reactive: latest
- react: latest
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by SergeyAlexeev** [comment]
Hi,

I can't reproduce the behavior you described - https://codesandbox.io/s/n35jzm9rpl
