### ISSUE TITLE
One column has multiple values

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1801]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have the data of states.
const data = [{ stateId: 3435, stateName, "AB" }, { stateId: 3243, stateName: "CA" }]

Now it is columns: [{ name: "stateName",  title: "State" }]
It shows the column named "State" with the value of "stateName".

### Expected Behaviour
I need to use the stateId for editing, so I want to has the "stateId", not as a column.
How can I have a column named "State", shows the value of "stateName" as the caption and contains the value of "stateId"? Every time I can update the stateId from the stateName.

How can I do it? I saw on the docs. Should I use `getCellValue` ? and how can I do that?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

This [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-accessors/) shows how to use custom data structures in React Grid.

As far as I understand, you want to use a selectbox as an editor, right? If so, this [article](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting#custom-editors) will be helpful as well.
