### ISSUE TITLE
Yarn build fails to minify 

### ISSUE THREAD

**Issue by SamueleDassatti** [DevExpress/devextreme-reactive#1802]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour
I am using the Chart component with Material UI and when I try to build my project with `yarn build` I get this error:

```
Failed to minify the code from this file:
./node_modules/@devexpress/dx-chart-core/dist/dx-chart-core.es.js:529
```

### Expected Behaviour
`yarn build` shoudn't throw any error.

### Environment

- devextreme-reactive: 1.10.0
- react: 16.7
- material-ui: 3.9.0

**Comment by DmitryBogomolov** [comment]
Hello.

Would you please modify the [sample.zip](https://github.com/DevExpress/devextreme-reactive/files/2803152/sample.zip) so that the issue is reproduced?

**Comment by SamueleDassatti** [comment]
I modified the sample but I wasn't able to reproduce the issue: `yarn build` doesn't return any error.

**Comment by DmitryBogomolov** [comment]
Can you provide a sample of your code where the error occurs?

**Comment by SamueleDassatti** [comment]
Try running `yarn build` on the last commit of the master branch of this repository: https://github.com/IglooCloud/IglooAurora

**Comment by DmitryBogomolov** [comment]
I got the following result after running `react-scripts build` in your project.

```bash
Failed to minify the code from this file:
    ./node_modules/@devexpress/dx-chart-core/node_modules/d3-array/src/quantile.js:3:15
```

There was also a link that leaded    [here](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify).

I updated the *react-scripts* version (to the latest one) and `react-script build` was performed successfully.

**Comment by SamueleDassatti** [comment]
That solved it! Thanks!

**Comment by DmitryBogomolov** [comment]
You are welcome.
