### ISSUE TITLE
Question summary row single message

### ISSUE THREAD

**Issue by rpkRED** [DevExpress/devextreme-reactive#1804]
In examples provided in doc for summary row every column has it's on calculation and message. My question is it possible to have only one message at for instance left side of row and just calculation numbers displayed for columns?

**Comment by SergeyAlexeev** [comment]
Hi,

As you can see in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/summary-state/#summaryitem), the 'columnName' field is required for the 'SummaryItem' interface.

Anyway, you can use any column name to calculate a row count. Look at this [sample](https://codesandbox.io/s/2xjvnlkx6n). Would you please clarify if there is any reason or requirement that you can't use a column name?
