### ISSUE TITLE
Error with installation Material-UI. Module not found: Can't resolve '@material-ui/icons/ChevronLeft'

### ISSUE THREAD

**Issue by scheung38** [DevExpress/devextreme-reactive#1805]
./node_modules/@devexpress/dx-react-grid-material-ui/dist/dx-react-grid-material-ui.es.js
Module not found: Can't resolve '@material-ui/icons/ChevronLeft' in '$HOME/hackajob/react/phonebook-interface/node_modules/@devexpress/dx-react-grid-material-ui/dist'

Something breaking?

### Environment
MacOSX

node
v11.6.0

  "dependencies": {
    "@devexpress/dx-grid-core": "^1.10.0",
    "@devexpress/dx-react-core": "^1.10.0",
    "@devexpress/dx-react-grid": "^1.10.0",
    "@devexpress/dx-react-grid-material-ui": "^1.10.0",
    "@material-ui/core": "^3.9.1",
    "material-ui": "^0.20.2",

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
