### ISSUE TITLE
How select all checkboxes rows by default?

### ISSUE THREAD

**Issue by alinealvesvianna** [DevExpress/devextreme-reactive#1807]
I wanted that when the table loaded, all checkboxes were selected. How can I do this?

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by MaximKudriavtsev** [comment]
Hi @alinealvesvianna,
 
We suggest using the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/). You need to define a [selection property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/#properties) for all your rows, and each row should have a unique identificator. See the [following demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/#basic-setup).

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
