### ISSUE TITLE
How to implement appear-in animation for a newly (real-time) added row

### ISSUE THREAD

**Issue by jimmycarlinco** [DevExpress/devextreme-reactive#1811]
Hello,

just a quick question to all of you developers who understand the grid better than I do:

how to implement a css animation when adding a new row received from socket.io in real-time? I am just wondering what the most performant way of achieving this is. I currently have a working implementation that works like this:

I have a notification system, where a new notification is also added in real-time when a new row is pushed that has property new on notification that the table row component TableRow checks as well as foreignKey of the row object that then adds a css class (.freshRow) with some css fade in animation. After it is added, I set the notification objects new property as false with delay. This works but I have doubts about the performance and it causing unneccesary re-renders. It is probably the wrong way to go about this solution, right? I am using redux.

Code for TableRow:

```
TableRow = ({ row, ...restProps }) => {
    const { client, notifications, markSingleNotificationAsReadWithDelay, gridType } = this.props;

    const classes = [];

    const notificationExists = () => {
      let result = false;
      if (notifications.list && !!notifications.list.length) {
        notifications.list.forEach((notification) => {
          if (
            notification.foreignKey === row.id &&
            notification.new
          ) {
            result = true;
            markSingleNotificationAsReadWithDelay(client, notification);
          }
        });
      }
      return result;
    };

    if (notificationExists()) {
      classes.push('freshRow');
    }
    return <Table.Row {...restProps} className={classnames(classes)} />;
  };
```

One current optimisation that I see myself is to not use forEach or the grid will lag out hard if there are too many notifications and to just normalize the redux state so it doesn't have to iterate over all notifications for each row. But before I do that, is there a better solution to do this that perhaps doesn't even have to modify the redux state to achieve this? I hope so :D

**Comment by SergeyAlexeev** [comment]
Hi,

You can extract the `notificationExists` function from the `TableRow` component to avoid its creation on each render.

I'd also like to point that we published a guide about [performance optimization](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/). There we described more common cases that can cause performance drawbacks.
