### ISSUE TITLE
Hide and show filterRow with filter icon button

### ISSUE THREAD

**Issue by VictorBNT** [DevExpress/devextreme-reactive#1827]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Expected Behaviour
Hi,

I would like to hide or show all filterRow with filter icon toogleButton. I think it's possible but I don't know how to do.

### Environment

- devextreme-reactive: 1.10.0
- react: 16.6.3
- browser: Chrome 71.0.3578.98
- react-bootstrap: none
- material-ui: 1.10.0

**Comment by ushkal** [comment]
Hi,
 
You can conditionally render a TableFilterRow plugin. Here's a [sample project](https://codesandbox.io/s/pp1q53ww60).

**Comment by VictorBNT** [comment]
Thanks. Works perfectly!
