### ISSUE TITLE
Edit .table-responsive style

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1829]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
It has some inline style in `.table-responsive` of
    .table-responsive{
        overflow: auto;
        border: 0px;
        margin: 0px;
    }
How can I edit them without using !important?

### Expected Behaviour
Is it possible to edit the data grid .table-responsive class?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
@susuwatari2, yes, you can override our styles using the '!important' declaration. Another approach is to pass your styles to the containerComponent as shown in this [example](https://codesandbox.io/s/yvxy8y5pv1).
