### ISSUE TITLE
Customize toolbar

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1830]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Expected Behaviour
How can I pass in the number of rows and create a extra button? How can we better use of `rootComponent` and `toolbarContent` with default `ColumnChoose` in the toolbar?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
@susuwatari2, you can achieve your goal by implementing custom plugins. See the [attached project](https://codesandbox.io/s/l53zzpz54q). In this project, Template and TemplatePlaceholder components are used for appending a content to the toolbar and TemplateConnector provides a template with the 'rows' getter value. 
For more information on developing custom plugins, refer to the [Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) guide.

**Comment by susuwatari2** [comment]
Thank you, @ushkal. It is close to what I am looking for. 
If I am doing as the project, I have problem with the column chooser. It doesn't allow to scroll if I have it opened.
Any ideas what causing the issues?
