### ISSUE TITLE
Grid component ignores className in v1.10.0

### ISSUE THREAD

**Issue by davidcastrojobsity** [DevExpress/devextreme-reactive#1835]
In version 1.9.0 I was able to pass a `className` prop to the `Grid` component to style my table, in version 1.10.0 the `className` prop is ignored.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
With this code:
```
<Grid
  rows={ rows }
  columns={ columns }
  className="my-awesome-table"
>
  ...other components
</Grid>
```
The resulting html is:
```
<div class="panel panel-default" style="display: flex; flex-direction: column;">
 ...other components
</div>
```
### Expected Behaviour
With this code:
```
<Grid
  rows={ rows }
  columns={ columns }
  className="my-awesome-table"
>
  ...other components
</Grid>
```
The resulting html should be:
```
<div class="panel panel-default my-awesome-table" style="display: flex; flex-direction: column;">
 ...other components
</div>
```

### Environment

- @devexpress/dx-react-core: 1.10.0,
- @devexpress/dx-react-grid: 1.10.0,
- @devexpress/dx-react-grid-bootstrap3: 1.10.0,
- react: 16.6.0
- react-bootstrap: 0.32.1

**Comment by MaximKudriavtsev** [comment]
Hi @davidcastrojobsity,

You used an undocumented API in version `1.9.0`. Instead, you need to use `rootCompomnent` to pass your custom properties to the Grid. See the following [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#stretching-out-to-parent-element-size) for more information.

**Comment by davidcastrojobsity** [comment]
Thank you! =)
