### ISSUE TITLE
Horizontal bar charts, how?

### ISSUE THREAD

**Issue by RopoMen** [DevExpress/devextreme-reactive#1836]
Hi,

I was looking the documentation for the Chart component, but I was unable to find a way to create horizontal charts. Is horizontal bar chart feature currently not implemented? If so, would it be easy to implement?

We are currently using DataGrid, TreeView, List and Chart from `devextreme-react`, but because it is quite bloat even if we are making imports in this way `evextreme-react/ui/list` we decided to migrate to pure React lib instead.

I noticed that we can use Grid from this library to replace TreeView, DataGrid and List, but if we cannot get horizontal bar charts to work, we most likely start using chart.js + react wrapper for it to replace `devextreme-react/ui/chart` and get our bundle size smaller.

Br,
- Markku

**Comment by DmitryBogomolov** [comment]
Hello.

Chart rotation is not supported.
 
A vertical bar can be replaced with a horizontal one using a custom [point component](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/bar-series/). Argument and value fields can be swapped.
Here is a [sample](https://codesandbox.io/s/0qr0179y00).
Please note, however, that it is only a visual change - it is not an actual rotated chart.

**Comment by RopoMen** [comment]
Hi,
Thanks for the example!

I tested this last night and it looked quite nice, but I'm not sure are we going to use that or should we use `react-chartjs-2` (even though it produces slightly bigger bundle).

I tested tooltips by adding these inside `<Chart>` as last components, but I was unable to get tooltips to show up.
```
<EventTracker />
<Tooltip />
```

Here is image of the chart that I would be needing and currently it only lacks the "tooltip". I think that there is a way to force all tooltips to show up and then style those to match our needs.
![chart](https://user-images.githubusercontent.com/7492812/52694392-3dbbb600-2f72-11e9-90ec-5b8b7c2e211a.png)

Unfortunately I don't have much time to try solve this by my self (and not expecting you to solve this for me), so I most likely use chartjs to get this done. One note to your example, if I had only one item in `data` array result is looking like this:
![one-item](https://user-images.githubusercontent.com/7492812/52694480-84111500-2f72-11e9-8b59-e8acb2f82008.png)


But again, thanks for the example it was helpful!

Br,
Markku

**Comment by DmitryBogomolov** [comment]
The tooltip is not shown because we changed only visual representation, but it is necessary to override the internal logic. At the moment, there is no public API for changing this logic. We will consider supporting rotated charts in future versions.

As for a single bar, the chart stretches a single bar according to the container size. If this behavior does not meet your requirements, please describe the desired behavior. Maybe we will consider implementing it in future builds.

**Comment by RopoMen** [comment]
Hi,

"As for a single bar, the chart stretches a single bar according to the container size. If this behavior does not meet your requirements, please describe the desired behavior"

If there is single bar, it should still show up the label of the serie at the left and not push it away from the container. When there were multiple bars it showed up series label on left correctly. 

But as horizontal bar chart is not currently supported and this was kind a "hax" that I was testing I cannot say that this was a bug neither. In my implementation the barchart was inside Bootstrap 4 column ~30% of the container width.

**Comment by DmitryBogomolov** [comment]
Sorry for the delay. I must have missed the notification. 

> If there is single bar, it should still show up the label of the serie at the left and not push it away from the container.

Thanks for the description. We'll keep it in mind when implementing chart rotation.

**Comment by Krijovnick** [comment]
We have released the [2.0.0](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#200-2019-07-08) version of DevExtreme Reactive Chart with this feature.
