### ISSUE TITLE
Batch Editing

### ISSUE THREAD

**Issue by cevr** [DevExpress/devextreme-reactive#1841]
Currently, you can only save one by one from what I can see and from what I can read in the documentation.

Is there a way to save every row that is in an editing state?

[Gif demonstrating issue](https://i.imgur.com/O4kLHhG.gifv)

**Comment by SergeyAlexeev** [comment]
Hi,

Do you mean [batch editing](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/BatchEditing/jQuery/Light/)? If so, currently we don't provide such a functionality out of the box. However, you can implement it on your side. Use the `EditingState` plugin in [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing#controlled-mode) to manage added and changed rows. Please refer to this [example](https://codesandbox.io/s/88opp32xpj) for more details. Here, I'm using a [custom plugin](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) that uses the `commitChangedRows` and `commitAddedRows` [actions](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/action/) to fire the `onCommitChanges` event.

**Comment by cevr** [comment]
Hi @SergeyAlexeev , thanks for this example, it solves my problem!

**Comment by cevr** [comment]
@SergeyAlexeev If batch editing were to be supported, I imagine canceling would be too right?

Perhaps `Support Batch Operations` would fit more closely. Thoughts?

**Comment by SergeyAlexeev** [comment]
@cevr We'll support canceling, of course. Our roadmap is [here](https://community.devexpress.com/blogs/javascript/archive/2019/01/22/devextreme-javascript-2019-roadmap.aspx).
