### ISSUE TITLE
Customize a cell and add a tag

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1846]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Only display the data in a cell

### Expected Behaviour
Click on a cell and it is a link but it is missing href
How can I passing a props into <a> tag ? 

    const formatter =({value, href}) => (<a href={href}>{value}</a>)
    export const typeProvider = props => ( <DataType formatterComponent={linkFormatter} /> )

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please clarify where you have the `href` value? Is it a field of the `row` object?

**Comment by susuwatari2** [comment]
Yes

**Comment by SergeyAlexeev** [comment]
As you can see in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider#datatypeprovidervalueformatterprops), a formatter component accepts the `row` props. Use it to access the `href` field. Refer to this [sample](https://codesandbox.io/s/pk802mzpj0) for more details.

**Comment by susuwatari2** [comment]
I modified your [sample](https://codesandbox.io/s/0qjj5008wp). As I want them going to the same page, I passed a href props. It cant read that. What is the better way to do that?

**Comment by SergeyAlexeev** [comment]
Hi,
 
As you pointed above, you keep the `href` field in a `row` object. In this case, I don't understand why you are using this code:

```jsx
<LinkProvider for={["name"]} href="www.google.com" />
```

Here you don't get `href` from a row. You just add the `href` property to the `LinkProvider` component. Anyway, you can access this property within this component:

```jsx
const LinkProvider = ({ href, ...restProps }) => (
  <DataTypeProvider
    formatterComponent={({ value, row }) => <Link href={href}>{value}</Link>}
    {...restProps}
  />
);
```
