### ISSUE TITLE
Installation of the OpenIconic icons for Bootstrap4 version

### ISSUE THREAD

**Issue by fabiandeny** [DevExpress/devextreme-reactive#1848]
As shown on [https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/](url), for the Bootstrap4 version, the arrow on the left of the Group is not showing.
I realized that I need to properly install and configure the OpenIconic icons.

I've done:
npm install --save @icon/open-iconic
put this on the root js:
import '@devexpress/dx-react-grid-bootstrap4/dist/dx-react-grid-bootstrap4.css';
add this to the scss file:
@import '~@icon/open-iconic/open-iconic.css';

What did I do wrong in this?

**Comment by ushkal** [comment]
Hi,

I advise you to use a recommended [approach](https://github.com/thecreation/standard-icons/tree/master/modules/open-iconic#icons-font----ideal-when-you-want-to-include-all-icons-at-once):
``` html
<head>
...
<link rel="stylesheet" href="@icon/open-iconic/open-iconic.css">
...
</head>
```
Please let me know if it helps.

**Comment by fabiandeny** [comment]
Sorry I forgot to mention I'm using React.
Where should I place the head section?

**Comment by ushkal** [comment]
Hi @fabiandeny ,

Usually the `<head>` section is located in the `index.html` file, but the location may be different depending on your project configuration. For example, if you are using a `react-helmet` component, you should use its `link` property. See the official OpenIconic [docs](https://github.com/iconic/open-iconic#with-bootstrap) for more information.
 
Sorry for the late response.

**Comment by fabiandeny** [comment]
Hi @ushkal,
I tried adding this in the index.html,
```
<head>
...
<link rel="stylesheet" href="@icon/open-iconic/open-iconic.css">
...
</head>
```
Still doesn't work. I'm sorry

**Comment by ushkal** [comment]
Hi @fabiandeny,

It seems that this approach requires adding an additional server configuration. Then I suggest you load open-iconic from CDN like this: 
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css" crossorigin="anonymous">
```
or using unpkg service
```
<link rel="stylesheet" href="https://unpkg.com/@icon/open-iconic/open-iconic.css">
```

We'll add this in our guide.

**Comment by fabiandeny** [comment]
Ok I'll give it a try later.
Thanks a lot for the help @ushkal

**Comment by ushkal** [comment]
You are welcome, @fabiandeny! Feel free to reopen this issue if you need further assistance.
