### ISSUE TITLE
MS Office React Fabric UI theme

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/devextreme-reactive#185]
Introduce a data grid for [React Fabric](https://github.com/OfficeDev/office-ui-fabric-react) by providing Fabric UI look and feel for the DevExtreme [React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/).

**Comment by terndrup** [comment]
+1 for this, I'm guessing a lot DevExpress users are building applications for Microsoft users (I know I am) so having the controls integrate seamlessly with Fabric UI themes and components would be amazing

**Comment by swapnildoshi2016** [comment]
> Introduce a data grid for [React Fabric](https://github.com/OfficeDev/office-ui-fabric-react) by providing Fabric UI look and feel for the DevExtreme [React Grid](https://devexpress.github.io/devextreme-reactive/react/grid/).

Is this in Pipe line.It would be awesome if we get Data Grid in Fabric UI styles

**Comment by churkin** [comment]
Hi everyone,
After further discussion, we decided to exclude implementation of the new UI themes from our strategy plans. Thus, I will close this issue. But you still can implement a custom theme yourself. Please use [this](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/custom-theme/) guide with examples.
