### ISSUE TITLE
Customize filter rows and filter selector

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1855]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have created an [example](https://codesandbox.io/s/llp9o02l29), feel free to fork and modify it.
The showFilterSelector applies on all filters, is it possible just using it for "age" and "salary" columns?

On the other hand, I have a FilterCell  for "age" in the example. How can I create a plugin for customized  FilterCell and use it for both "age" and "salary" by passing column name, max number?

**Comment by MaximKudriavtsev** [comment]
Hi @susuwatari2,
 
You can customize `FilterInput` via [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/#custom-editors), please see the [following demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#custom-filter-operations).  
To override FilterCell, you can use `cellComponent` of the `TableFilterRow` plugin.
 
The following [example](https://codesandbox.io/s/jjp025w4w5) demonstrates how to do it.

**Comment by susuwatari2** [comment]
Thank you @MaximKudriavtsev 
Is it possible if i want to select options for "Sex" column? The available value will be the option. In this case, it is "Male" and "Female".

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,
 
Yes, you can create a custom filter cell by overriding the `cellComponent` property of the `TableFilterRow` plugin. See the following [example](https://codesandbox.io/s/x018lkowz). To change a filer method you can use the custom filer algorithm. See the [following documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#integratedfilteringcolumnextension).

**Comment by susuwatari2** [comment]
@MaximKudriavtsev, I saw what you did by using the cellComponent. 
I want to have more than one select filter on the TableFilterRow, how can I pass the props and reuse the `<SelctFilterCell/>`? I forked and added `selectFilterCells` which have the custom filter for "Sex" and "City".
[https://codesandbox.io/s/oqy4rr19m9](url)

**Comment by MaximKudriavtsev** [comment]
You can add an `option` property into the `columns`. And use it inside custom components. See an [example](https://codesandbox.io/s/mmzqxz8nv8).

**Comment by susuwatari2** [comment]
@MaximKudriavtsev 
Where would be the better approach for adding operation in filter?

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,

See the [following guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#custom-filter-operations).
