### ISSUE TITLE
React Grid grouping is not working properly when the result from grouping criteria has value 0

### ISSUE THREAD

**Issue by hareaca** [DevExpress/devextreme-reactive#1859]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When applying grouping criteria, and the response has value 0 and the key something different, in the formatter component value is equal with the key.

### Expected Behaviour
The value in the formatter component should have the right value.

### Steps to Reproduce (for Bugs)

You can check the demo [here](https://codesandbox.io/s/ov5945y44y) where its used v.1.10.1.
As well you can check [here](https://codesandbox.io/s/k9p36lprzo) where its used v.1.8.0 and its working as expected.

**Comment by ushkal** [comment]
Hi @hareaca 
 
This bug was fixed in the scope of issue #1761. The new release 1.10.3 contains a fix.
