### ISSUE TITLE
Move FilterSelectorIcon from outside input field to inline with it as in material UI called it input adornment

### ISSUE THREAD

**Issue by ciforusalterra** [DevExpress/devextreme-reactive#1860]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
We can not move filter selector icon inline with TextField because of default design of TableFilterRow in dx-react-grid.

### Expected Behaviour
Want to make filter selector inline with TextField as startAdornment or endAdornment like in your react wrapper example [(Filtering Widget).](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/React/MaterialOrangeLight/)

### Environment

- @devexpress/dx-react-core: ^1.10.1,
- @devexpress/dx-react-grid: ^1.10.1,
- @devexpress/dx-react-grid-material-ui: ^1.10.1,
- react: ^16.7.0
- material-ui: ^3.9.2

**Comment by SergeyAlexeev** [comment]
Hi,
 
You can change the built-in UI by overriding the `editorComponent` and `toggleButtonComponent` properties of the `TableFilterRow` plugin. I've created a [sample](https://codesandbox.io/s/j1w4xy790v) that shows how to implement this.

**Comment by ciforusalterra** [comment]
Hi you're right if it only contain few columns that does not need horizontal scrolling. That will produce weird behaviour if we have a lot of columns like [this](https://jn2qwy2n43.codesandbox.io/). Do you have any other sugestion?

**Comment by ciforusalterra** [comment]
Forget it, I've solved this problem by changing the parent Cell position to relative like [this](https://codesandbox.io/s/7mw64o0rx6). Thanks bro.
