### ISSUE TITLE
Semantic UI theme

### ISSUE THREAD

**Issue by cemremengu** [DevExpress/devextreme-reactive#187]
Great work first of all! React community is definitely in need of a fully functional data grid like this.

We are currently (and I guess many other people as well) are using Semantic UI react components so it would be great if those styles are added as well (we can help for this!).

Otherwise, I think that bootstrap/material and semantic css will interfere with each other and we will have trouble using this beautiful data grid.

**Comment by dxbykov** [comment]
Hi @cemremengu,

Thank you for your suggestion and for looking into our data grid for React. We'll consider supporting Semantic UI rendering in our React components and update this thread once we have any decision on that. Technically it shouldn't be a problem.

**Comment by sjmnz** [comment]
+1 for Semantic UI support - it's our companies main CSS framework these days and would make DevExtreme that much more attractive to us!

**Comment by jannik2b** [comment]
Also would totally love to see support for Semantic UI!

**Comment by anztrax** [comment]
+1 for semantic UI support 👍

**Comment by maverickdude** [comment]
Hi @dxbykov 
Is there any update on this?

**Comment by oorestisime** [comment]
Hello, i don't know the workload on creating another theme but i am wondering whether this could be community driven, not only for semantic-ui but basically any other react UI library.

If you could outline the steps on what a UI library needs to have in order to build this and where people should look for the   "public API" of the data grid itself here then it shouldn't be that hard.

**Comment by SergeyAlexeev** [comment]
Hi,

We've prepared a [guide](https://github.com/DevExpress/devextreme-reactive/pull/1754) about a custom theme creating. It will be available on our [site](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/) with the next update.

**Comment by jannikbuschke** [comment]
nice!

**Comment by beatlecz** [comment]
Is there someone willing to implement Semantic UI theme based on the tutorial? :-) There is such bunch of controls it has to be implemented and I have completely no time to do it.

**Comment by jamesveostar** [comment]
Any update on this becoming a possibility?

**Comment by MaximKudriavtsev** [comment]
Hi @jamesveostar,

We don't have plans to implement the Semantic UI theme in the near future. We have a [guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/custom-theme/) about creating custom theme package with examples, so you can try to implement yourself and share results with the community.

**Comment by churkin** [comment]
Hi everyone,
After further discussion, we decided to exclude implementation of the new UI themes from our strategy plans. Thus, I will close this issue. But you still can implement a custom theme yourself. Please use [this](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/custom-theme/) guide with examples.
