### ISSUE TITLE
Typescript Import Errors on 1.10.3

### ISSUE THREAD

**Issue by patrick-moore** [DevExpress/devextreme-reactive#1875]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm getting the following typescript error after going from 1.10.1 to 1.10.3:

`Property 'defaultCalculator' does not exist on type 'ComponentType<IntegratedSummaryProps>'`

Here's where I'm trying to access defaultCalculator:

```tsx
const summaryCalculator = (type: string, rows: any[], getValue: any) => {
  if (type === "filteredSum") {
    if (!rows.length) {
      return null;
    }
    const total = rows.reduce((sum, row) => {
      if (row.selected) {
        return sum + getValue(row);
      }
      return sum;
    }, 0);
    return total;
  }
  return IntegratedSummary.defaultCalculator(type, rows, getValue);
};
```

I think this is related to this change: https://github.com/DevExpress/devextreme-reactive/commit/4bacf20#diff-d320e23a85f9e4da6ba0e4d3793cf968L15

### Expected Behaviour

No typescript errors

### Steps to Reproduce

Try to implement a custom summary algorithm following this [example ](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/summary-row/)

### Environment

- devextreme-reactive: ^1.10.3
- react: ^16.8.1

**Comment by ushkal** [comment]
Hi @patrick-moore
 
Thank you for reporting the issue. We'll fix it as soon as possible. In the meantime, you can use the following workaround:
`(IntegratedSummary as any).defaultCalculator(type, rows, getValue)`
