### ISSUE TITLE
Controlled Mode EditingState causes DataTypeProvider to lose focus after onValueChange called

### ISSUE THREAD

**Issue by nuzz78** [DevExpress/devextreme-reactive#1878]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Using a Grid with Material-Ui. Enter edit mode with a customer datatypeprovider - its nothing special for this demo, just a straight textfield. When typing a single character into the input field, the focus is immediately lost.

Now if I revert EditingState back to uncontrolled mode, by removing:
            editingRowIds={editingRowIds}
            onEditingRowIdsChange={this.changeEditingRowIds}
            rowChanges={rowChanges}
            onRowChangesChange={this.changeRowChanges}
            addedRows={addedRows}
            onAddedRowsChange={this.changeAddedRows}

The focus is now retained correctly by the datatypeprovider and I can enter my full text.

### Expected Behaviour

Should not lose focus.

### Steps to Reproduce

I have attached a react class that demonstrates the problem
[demo.txt](https://github.com/DevExpress/devextreme-reactive/files/2917813/demo.txt)

### Environment

- devexpress/dx-react-core: 1.10.1
- react: 16.8.2
- browser: xxx
- bootstrap: none
- react-bootstrap: ^1.0.0-beta.5
- material-ui: 3.9.2

**Comment by MaximKudriavtsev** [comment]
Hi @nuzz78,

Please don't create new components in the render methods. See the [following guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods) for more information on what best practice to customize components is, also refer to the [next issue](https://github.com/DevExpress/devextreme-reactive/issues/1760).

**Comment by nuzz78** [comment]
Very good. Turning the dataprovider into a const fixes it. Thanks for that. In this case I copied most of that from: https://community.devexpress.com/blogs/oliver/archive/2017/10/25/custom-sorting-grouping-filtering-and-more-in-devextreme-grid-for-react.aspx

See the section on dataproviders. It may not be what was meant, but thats the way I took it for creation.
