### ISSUE TITLE
No way to get editedstate inside datatypeprovider

### ISSUE THREAD

**Issue by nuzz78** [DevExpress/devextreme-reactive#1880]
- [ X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When a multiple datatypeproviders are used, they don't receive the changes that have been made to any other columns during the edit, just the value of the columns before any editing is done.

I cannot see any way to get the editing state into the datatypeproviders. I originally thought that I could do something like what I put in issue #1869. However that causes other issues because the datatypeprovider is instantiated each time, and you get focus issues. So I converted the datatypeproviders back to consts. This means I have no way of now injecting the rowchanges into the datatypeprovider. Its also possible that DatatypeProvider was never created with the intention of knowing about other cells. 

At the moment the value passed to datatypeprovider doesn't reflect the changes. Consider this output below, I edit the first amount cell, but when the editor is invoked, it doesn't contain the change, just the original values.

{column: {…}, row: {…}, value: "30391000", onValueChange: ƒ}
column: {name: "amount", title: "Sale Amount"}
onValueChange: ƒ onValueChange(newValue)
row: {product: "SolarOne", amount: "3039", amount2: "8000"}
value: "30391000"
__proto__: Object

DemoDataProvider.js:32 Editing column: amount2
DemoDataProvider.js:33 
{column: {…}, row: {…}, value: "8000", onValueChange: ƒ}
column: {name: "amount2", title: "Sale Amount2"}
onValueChange: ƒ onValueChange(newValue)
row: {product: "SolarOne", amount: "3039", amount2: "8000"}
value: "8000"
__proto__: Object

How can I get the current edited values of the row into the which ever Datatypeprovider is being used?

### Expected Behaviour

That the value of other cells that are changed within the row as passed to the cell being editted.

### Steps to Reproduce

I have attached a class demonstrating this.

### Environment

- devexpress/dx-react-core: 1.10.1
- react: 16.8.2
- browser: xxx
- bootstrap: none
- react-bootstrap: ^1.0.0-beta.5
- material-ui: 3.9.2
[demo.txt](https://github.com/DevExpress/devextreme-reactive/files/2923865/demo.txt)

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for your explanation. We designed the `DataTypeProvider` plugin to customize an editor depending on the column data type. I think the `onRowChangesChange` property of the `EditingState` plugin is more suitable for tracking column value changes.

I've created a [sample](https://codesandbox.io/s/oqr02n1z79) that shows how to do it.

**Comment by nuzz78** [comment]
Perfect. Thats exactly what I needed. However there is one slight problem with your example. If you edit the country and then go back to the original country it will never update the city combo. You need to change the code to have something like:

    // Find the original country for the stored state
    let row = this.state.rows.find(({ id }) => changedRowID === id);
    //if previous rowChanges !empty compare to whats in the state
    if( this.state.rowChanges[changedRowID] && 'countryId' in editTableState.rowChanges[changedRowID]) {
      row = this.state.rowChanges[changedRowID];
    }

    let country = row.country;

The above just ensures that the country you compare against is always the last change, rather than comparing against the original row countryId. (Not sure how I would express the above as a nice little const section like you used....)

Thanks for the great example, just wish that was present in the documentation.....
