### ISSUE TITLE
How to move search panel to left hand side?

### ISSUE THREAD

**Issue by cevr** [DevExpress/devextreme-reactive#1882]
Currently the search panel is on the right hand side because there's a div with a `margin-left: auto` property pushing it all the way to right. Is there a way to remove this div?

![Div in question](https://i.imgur.com/3b8lxvP.png)

**Comment by MaximKudriavtsev** [comment]
Hi @cevr,
 
To move [SearchPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/search-panel/) to the left side, we can suggest you try two workarounds.
- The simplest way. If your [Toolbar](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/) contains only `SearchPanel`, you can add the style to the `rootComponent` of `Toolbar`, see an [example](https://codesandbox.io/s/7zp43jnqjq).
 
- Use the DevExtreme Reactive Core to make you own `CustomSearchPanel` plugin, see an [example](https://codesandbox.io/s/5kxly9l4xx).
 

Also, you can use these ways if you want to move other plugins (GroupPanel, ColumnChooser) in the `Toolbar`.

**Comment by cevr** [comment]
@MaximKudriavtsev Thank you very much. Your first solution is simple and works great!
