### ISSUE TITLE
Render of Grid doesn't rerender the header row

### ISSUE THREAD

**Issue by nuzz78** [DevExpress/devextreme-reactive#1883]
- [ X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm running internationalisation in my app. However when I change language, all the table columns are rerendered correctly with the language change. However the header isn't refreshed, even though the column titles have been updated. 

Is there anyway to call a refresh on the header column? (I can't see one)

I even looked into the header cells:

`
const customCellComponent = props => {
  console.log(props);
  return (<TableHeaderRow.Cell {...props} ><FormattedMessage id="photo.clear" /></TableHeaderRow.Cell>);
}`

`<Grid
          rows={rows}
          columns={columns}
          getRowId={row => row.id}
        >
          {this.props.children}
          <EditingState
            editingRowIds={editingRowIds}
            onEditingRowIdsChange={this.changeEditingRowIds}
            rowChanges={rowChanges}
            onRowChangesChange={this.changeRowChanges}
            addedRows={addedRows}
            onAddedRowsChange={this.changeAddedRows}
            onCommitChanges={this.commitChanges}
          />
          <Table />
          <TableHeaderRow cellComponent={customCellComponent} />
          <TableEditRow />
          <TableEditColumn showAddCommand={!addedRows.length} showEditCommand showDeleteCommand commandComponent={Command} />
        </Grid>`

And I can see that the header is only ever called once when the grid is created. 

This is a show stopper for me, and if there is no way around this I'll have to look for another solution.

**Comment by SergeyAlexeev** [comment]
Hi,

To update column headers, you can use a standard React way. I mean the [setState](https://reactjs.org/docs/faq-state.html) function.

Please refer to [this](https://codesandbox.io/s/p78o232xw0) example.

**Comment by nuzz78** [comment]
Thanks for that. That was exactly what I'd done, but I'd stuffed up the componentDidUpdate method of my table class, so even though I'd changed it, it never got passed through.
