### ISSUE TITLE
TypeScript type error IntegratedFiltering.defaultPredicate property not exist

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1886]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

After updating to the latest ReactGrid version with react-grid-core moved to TS, i got this error:
IntegratedFiltering.defaultPredicate property 'defaultPredicate' not exist on type ComponentType<IntegratedFilteringProps, any>...

### Expected Behaviour

No Typescript type error

### Steps to Reproduce

Code snippet i used: 
```
filteringColumnExtensions: [
        {
          columnName: 'saleDate',
          predicate: (value, filter, row) => {
            if (!filter.value.length) return true;
            if (filter && filter.operation === 'month') {
              const month = parseInt(value.split('-')[1], 10);
              return month === parseInt(filter.value, 10);
            }
            return IntegratedFiltering.defaultPredicate(value, filter, row);
          },
        },
      ],
```

### Environment

- devextreme-reactive: 1.10.3
- react: 16.8.3
- browser: Chrome latest
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.2

**Comment by SergeyAlexeev** [comment]
Hi,

We've already fixed this issue in [this](https://github.com/DevExpress/devextreme-reactive/pull/1876) PR. The fix will be available with the next update.

You can use this way as a temporary workaround:

```ts
return (IntegratedFiltering as any).defaultPredicate(value, filter, row);
```
