### ISSUE TITLE
Fix column name on-scroll

### ISSUE THREAD

**Issue by uditdubey** [DevExpress/devextreme-reactive#1887]
Below is my code. Version of devexpress in my reactjs project is 1.7.2
Currently on-scrolling the table my column name also scrolls. I want to fix the column name.

Can anyone suggest how to fix it ?..
////--code----/////

            <Card>

            <Grid  style={{ height: '100%' }} rows={this.state.outstngLmtOrderRows} columns={this.state.outLmtOrdcolumns} getRowId={getRowId}>
                  
                  <DragDropProvider />

                  <SortingState onSortingChange={this.onChangeOutLmtColSorting} defaultSorting={[{ columnName: 'eventTime', direction: 'desc' }]} id="lmtChngOutLmtColSorting"/>

                  <IntegratedSorting columnExtensions={this.state.integratedSortingColumnExtensions}/>

                  <SearchState value={this.state.outLmtSearchValue} onValueChange={this.onChangeOutLmtSearchValue} id="lmtChngOutlmtSearchVal"/>

                  <IntegratedFiltering />

                  <Table
                    cellComponent={Cell}
                    tableComponent={withStyles(rowStyle, { name: 'TableComponent' })(TableComponentBase)}
                    height="auto" columnAutoWidth={true} columnExtensions={this.state.outLmtOrdColumnExtensions}/>

                  <TableColumnReordering order={this.state.outLmtColumnOrder} onOrderChange={this.onChangeOutLmtColOrder} id="lmtChngOutLmtColOrd"/>

                  <TableHeaderRow showSortingControls contentComponent={TableHeaderContent}/>

                  <TableColumnVisibility columnExtensions={this.state.colVisibilityExtensions} hiddenColumnNames={this.state.hiddenOutLmtColumnNames} onHiddenColumnNamesChange={this.onChangeHiddenOutLmtCol} id="lmtChngHiddenAllLmtColmn"/>

                  <Toolbar />

                  <SearchPanel messages={searchPlaceholderMsg}/>

                  <ColumnChooser />
            </Grid>
            </Card>
////--end of code---/////

Thanks !!

**Comment by MaximKudriavtsev** [comment]
Hi @uditdubey,

This issue is a duplicate. Use the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/) plugin instead of the `Table` plugin. We are closing it and suggest writing in the [initial topic](https://github.com/DevExpress/devextreme-reactive/issues/896).
