### ISSUE TITLE
How to disable reordering by a column?

### ISSUE THREAD

**Issue by nhuthan** [DevExpress/devextreme-reactive#1889]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
How to disable reordering by a column?

**Comment by MaximKudriavtsev** [comment]
Hi @nhuthan,

You can manage your own column order in the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode), see an [example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/#controlled-mode).

**Comment by nhuthan** [comment]
The TableColumnReordering component has no columnExtension property. How I can disableReodering some columns. Thanks.

**Comment by MaximKudriavtsev** [comment]
You are right about the `columnExtension` property for the `TableColumnReordering` plugin.
 
As I wrote above, you can manage column order in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode). I made an [example](https://codesandbox.io/s/2vkk2lrz6y).

**Comment by nhuthan** [comment]
@MaximKudriavtsev 
In your exemple, how to disable reordering the 'Name' column? 
I mean disable drag the 'Name' column, I want the 'Name' column always be first column but not a fixed column.

**Comment by MaximKudriavtsev** [comment]
To prevent dragging a special column, use the `cellComponent` component of the [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/) plugin and pass `draggingEnabled=false` into them.
 
In the [next example](https://codesandbox.io/s/lxq285p2kz), the `City` column is the first column always, and this column is not available for dragging.
