### ISSUE TITLE
Please pass row index to getCellValue function params

### ISSUE THREAD

**Issue by nhuthan** [DevExpress/devextreme-reactive#1890]
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I am adding a column to display the row number, it will be easy to do if any the row index parameter is passed to the getCellValue function, I am currently using a count variable but it works incorrectly.

**Comment by SergeyAlexeev** [comment]
Hi,

> I am currently using a count variable but it works incorrectly.

Would you please clarify what exactly works incorrectly? I've created a very simple [example](https://codesandbox.io/s/jj2rvzvr2w) that shows how to calculate a row index. Also, we discussed a question about how to get a row index for sorted rows in this [thread](https://github.com/DevExpress/devextreme-reactive/issues/885).

**Comment by nhuthan** [comment]
Hi @SergeyAlexeev,
Your example not working with SortingState, rows.indexOf not return current row order ([not working example](https://codesandbox.io/s/ppo0nj46kx))
I tried use a count variable but it not working with GroupingState because getCellValue does not call in sort order ([without grouping example](https://codesandbox.io/s/30wlnkz0oq) and [with grouping example](https://codesandbox.io/s/xjljjp303p))

**Comment by shangdev** [comment]
I am also need to get the index calc the row number.

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

The VirtualTable doesn't support animation. However, we will consider implementing it in the future.

**Comment by LazyLahtak** [comment]
Hi everyone,

The getCellValue function is defined in the Grid plugin, which is placed before other plugins (such as the IntegratedSorting plugin). It cannot get right index information in this function. To get the right index, you can add a custom plugin, which redefines the getCellValue getter after IntegratedSorting.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ripwv) illustrating how to do that.
