### ISSUE TITLE
TypeScript build error

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#1893]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

If i build my solution without the "skipLibCheck" flag Typescript will emit this error:
```
Could not find a declaration file for module '@devexpress/dx-core'. '/node_modules/@devexpress/dx-core/dist/dx-core.umd.js' implicitly has an 'any' type.
  Try `npm install @types/devexpress__dx-core` if it exists or add a new declaration (.d.ts) file containing `declare module 'devexpress__dx-core';`
```

### Expected Behaviour

No error

### Environment

- devextreme-reactive: 1.10.3
- react: 16.8.3
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.2

**Comment by ushkal** [comment]
HI,
 
Thank you for reporting the issue. It is resolved in the context of #1885.
