### ISSUE TITLE
Grid renders data rows incorrectly when a page is zoomed in Chrome

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-reactive#1898]
Steps to reproduce using the [this](https://codesandbox.io/s/20n3372mvn) example:

Ensure Browser is at 100% zoom at start.
Allow the example to render.
Zoom out browser using ctrl-mouse wheel so you can see more rows.
Hit the refresh button on the codesandbox virtual browser.
Marvel at only seeing 4 rows of data.
Reset zoom to 100%.
Hit the refresh button on virtual browser.
Everything ok again.

**Comment by ushkal** [comment]
fixed in https://github.com/DevExpress/devextreme-reactive/pull/1900

**Comment by DanHarman** [comment]
@ushkal Any idea when this is being released, its holding up a release at my end :(

**Comment by ushkal** [comment]
Hi @DanHarman,
We plan to release the next version by the end of the week.

**Comment by ushkal** [comment]
Hi @DanHarman 
We've released a new version of dx-grid containing a fix: https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.10.5

**Comment by DanHarman** [comment]
@ushkal Thanks, the issue has been resolved with the new release. Thanks!
