### ISSUE TITLE
How to create a custom plugin

### ISSUE THREAD

**Issue by cevr** [DevExpress/devextreme-reactive#1902]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description

It's there a way to create a custom search/filtering component that uses checkmarks to find/filter specific rows? I tried to create a custom search component but the checkmark would populate the input field as well.

![example](https://i.imgur.com/p8pWWcu.png)

There isn't really any docs explaining plugins that I can find.

**Comment by MaximKudriavtsev** [comment]
Hi @cevr,

We have a guide that shows how to create a custom plugin in [this section](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/). Also, you can find the DevExtreme React Core [docs here](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/).

**Comment by cevr** [comment]
@MaximKudriavtsev Thank you!
