### ISSUE TITLE
Fixed columns in combination with grouped columns

### ISSUE THREAD

**Issue by Keethanjan** [DevExpress/devextreme-reactive#1913]
### I'm using ...
- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
We are using React Grid. In this grid we're using two functionalities: 
1) Grouped columns
2) Fixed columns.

When we enable fixed columns we see a left divider (as this is enabled by default). However when we're using the grouped columns we don't see the left divider anymore.

We'd like to have the divider also visible when we are grouping and are using the fixed columns. What our assumption would be is in this case to have the line for the header and for the actual rows (so no divider for the group rows). 

Thanks!

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please clarify if you want to render borders for a group row?

![image](https://user-images.githubusercontent.com/1897913/54671055-1ffbe680-4b06-11e9-90b5-b2d36bce067d.png)

**Comment by Keethanjan** [comment]
Hi,

When we don't group it is rendered as follow (with the functionality fixed columns enabled):
![image](https://user-images.githubusercontent.com/1520269/54676786-c98ca900-4b01-11e9-8a5e-b6f3dae9d514.png)


When we enable grouping (in combination with the fixed columns) the divider line is gone, see screenshot:
![image](https://user-images.githubusercontent.com/1520269/54676904-0fe20800-4b02-11e9-9dc2-0c9a9ada46d8.png)


What we'd like to have are the lines drawn in red:
![image](https://user-images.githubusercontent.com/1520269/54676722-9cd89180-4b01-11e9-9a40-c489b773230a.png)

I hope that this is clear:) and if it isn't let me know.

Regards,

Keethanjan

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information. I've created a [sample](https://codesandbox.io/s/j71wq5k205) where I'm using fixed columns and grouping. I fixed the 'name' column and it always has a border. Would you please modify the sample to reproduce the issue?

**Comment by Keethanjan** [comment]
After talking to a colleague we found that it is related to the order of the components, see:
https://codesandbox.io/s/61mq93yqkn

We moved the FixedColumns above the GroupedColumns which is causing this.
We will update our code so this will work. You can close this case if you'd like.

Thanks!

**Comment by SergeyAlexeev** [comment]
[Plugin order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview#plugin-order) makes sense in this case.
