### ISSUE TITLE
Custom style in TableTreeColumn Cell

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1915]
I try to style TableTreeColumn bud not work correctly
https://codesandbox.io/s/lpw138v207  (line 67)

I want set fontWeight to bold only in tree column, is possible?

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,

You should not pass `Table.Row` into a `cellComponent`. I created an [example](https://codesandbox.io/s/lr7mp7norz).
