### ISSUE TITLE
TableTreeColumn Cell Component - Check if node tree is expanded or collapsed

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1919]
When I using a custom cell component in TableTreeColumn:
<TableTreeColumn for="id" cellComponent={this.treeColumnCell} />

I would like to check if node expanded or collapsed.
Is possible check this state in <TableTreeColumn.Cell> ?

My target is set different font style.
CC

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,

You can use the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) and manage the `expandedRowIds` property of the `TreeDataState` plugin and save expanded `IDs`. Inside the `cellComponent` of the `TableTreeColumn` plugin, you receive a `row` argument with the `id` property.
