### ISSUE TITLE
Disabling Grid Table animations?

### ISSUE THREAD

**Issue by kg-currenxie** [DevExpress/devextreme-reactive#1920]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description
Is it possible to disable all table animations? (for example; when columns come in/out of visibility)

- devextreme-reactive: 1.10.1

**Comment by MaximKudriavtsev** [comment]
Hi,

We've already registered the similar feature request #1529.
