### ISSUE TITLE
PagingPanel pageSizes is not working in dx-react-grid-bootstrap4

### ISSUE THREAD

**Issue by shwekhine** [DevExpress/devextreme-reactive#1922]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

`<PagingPanel pageSizes={pageSizes} />` is not working when clicked. It shows the buttons but nothing happens when clicked. I also tried in your demo test environment "https://codesandbox.io/s/ojzkojkm0q".
Below is my code - 

`const pageSizes =[5, 10, 20, 0];`

`return (`
`  <div className="App">`
`	<Grid rows={rows} columns={columns}>`
`	  <PagingState defaultCurrentPage={0} pageSize={5} />`
`	  <IntegratedPaging />`
`	  <Table />`
`	  <TableHeaderRow />`
`	  <PagingPanel pageSizes={pageSizes} />`
`	</Grid>`
`  </div>`
`);`

### Environment

- devextreme-reactive: 4
- react: 16.8.4
- browser: Chrome
- bootstrap: 4.3.1
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi @shwekhine,
 
The page size does not change because it is set manually in the PagingState plugin. Try to replace the 'pageSize' property with 'defaultPageSize'. See this [codesandbox ](https://codesandbox.io/s/jnqwx2r5qy) for your reference.
