### ISSUE TITLE
Problem with Dx-react-chart

### ISSUE THREAD

**Issue by toumDev** [DevExpress/devextreme-reactive#1923]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

I had a problem compiling the grid. I had to comment everything using PureComputed as it was saying "Cannot use namespace 'PureComputed' as a type".

I am using React. 

![image](https://user-images.githubusercontent.com/48727013/54621246-d5169c00-4a3d-11e9-9841-d83494e1fa5f.PNG)

**Comment by toumDev** [comment]
Versions are differents

**Comment by DmitryBogomolov** [comment]
Hello.

Which versions do you mean?

**Comment by DmitryBogomolov** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
