### ISSUE TITLE
TableFixedColumns - scroolbar not working with data tree

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1924]
Scroolbar not working when I using TableFixedColumns and data tree:
https://codesandbox.io/s/olkqj2xzm5

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,
 
The DevExtreme Reactive plugins extend the [Data Piping principle](https://en.wikipedia.org/wiki/Pipeline_(computing)) and says that the next plugin changes previous plugin data - see the [Plugin Order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order).
 
In your example, the `TableFixedColumns` plugin makes previous columns fixed and the `TableTreeColumn` plugin adds a new unfixed `tree column` (according to the plugin order in your example).
 
Change the order of plugins and it all will work fine - see the [attached example](https://codesandbox.io/s/olxz5qw2q6).
