### ISSUE TITLE
Search by multiple words with random order

### ISSUE THREAD

**Issue by Kison** [DevExpress/devextreme-reactive#1928]
[x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
[x] React Grid

### Description
Do you have possibility to search rows by multiple words with random order?
Example
Search phrase: `Audi  A4`
Search results should include: `Audi A4` & `A4 Audi`
Thanks in advance!

### Environment

- devextreme-reactive: 1.9.1
- react: 16.6.3
- browser: chrome
- material-ui: 3.6.2

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, we don't provide such a functionality out of the box. You can implement it using a custom filter [predicate](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#integratedfilteringcolumnextension). Please refer to this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/) for more details.
