### ISSUE TITLE
Virtual TableGrid inside flexbox (in Firefox) overflows and does not show scrollbars. Chrome OK.

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1929]
I am trying to use Grid VirtualTable to fill all the remaining space of some containing flexbox. The code is here https://codesandbox.io/s/1yyy6rk583 This example works as expected in the most up-to-date Chrome (73.0.3683.75 (Official Build) (64-bit)). One can see that VirtualTable smoothly adapts to the remaining container space (when then browser size is changed) and it creates its inner scrollbars when the content takes more place than available from the container. But this examples does not work in the Firefox (e.g. 66.0 (64-bit) and other recent releases): Virtual table overflows the parent elements and the scrollbars are not created in Firefox.

One can inspect this page and see that Dx Grid contains 3 elements - 2 visible tables (header and content) and 1 hidden div element and exactly this hidden div element has very large height value, that is, apparently, assigned by the Dx Javascript code (so, this is not the issue about the differences of interpretation of CSS by Chrome and Firefox).

- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

p.s. In recent years I opened several issues about Dx grid in the flexbox and now all of them are solved for Chrome and only the mentioned problem remains with Firefox. I do not consider MS Edge/Explorer.

**Comment by ushkal** [comment]
Hi @alex153410,
 
To fix the issue, apply the overflow: 'auto' style to your \<main\> element. [Here's](https://codesandbox.io/s/8yyxwxrjrl) an updated sample.

**Comment by alex153410** [comment]
Merci. It really works.
