### ISSUE TITLE
Selection + CustomPaging Example?

### ISSUE THREAD

**Issue by npapagna** [DevExpress/devextreme-reactive#1930]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I cannot get Selection + Custom paging working properly. No matter what i do, it seems the selection on one page is persisted across other pages.

That is, every page has the same selecion, and changing the in one page is replicated in the others.

I tried experimenting with plugin order, with no luck.

Is there a working example i can use to understand this behaviour better?

Thanks.

### Environment

- dx-react-core: 1.10.4
- dx-react-grid: 1.10.4
- dx-react-grid-material-ui: 1.10.4
- react: 16.6.3
- browser: Chrome
- material-ui: 3.7.0

**Comment by MaximKudriavtsev** [comment]
Hi @npapagna,
 
It seems you don't specify the `getRowId` property of the `Grid` component. Please specify it and use different `id` values for every row.
 
If this does not work, please create an [example](https://codesandbox.io/s/13qvz1qqzl) demonstrating the issue.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
