### ISSUE TITLE
 Column with action BUTTONS

### ISSUE THREAD

**Issue by rafaeldorval** [DevExpress/devextreme-reactive#1934]
- [] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Hello, I have a question about how I can implement an action column with BUTTONS, the examples on the documentation pages is with TableEditColumn, do you have any open or closed questions with this example? 
I checked these issues on the [issues](https://github.com/DevExpress/devextreme-reactive/issues/1029), the solution would be the same? Was there anything less verbose?

Thank you

### Environment

- devextreme-reactive: 1.10.4
- react: 16.8.4
- browser: Chrome
- material-ui: 3.9.2

**Comment by rafaeldorval** [comment]
![image](https://user-images.githubusercontent.com/38694520/54754469-fbf9dd00-4bb9-11e9-98a8-820a724979ed.png)

**Comment by diegooferreira** [comment]
How did you do this? Is it possible to do this with Icon Buttons and Just In Rows (not in header)? 

My Context: 

I have a TableRowDetail ... but, in the parent row (not detail row), I need buttons to do operations.

Is it Possible?

Thank you

**Comment by rafaeldorval** [comment]
This image is an example of what I want to implement.

**Comment by SergeyAlexeev** [comment]
Hi,

We discussed a question about how to move an editing column to the right in [this](https://github.com/DevExpress/devextreme-reactive/issues/287) issue.
 To use a custom command button, override the 'commandComponent' property of the 'TableEditColumn' plugin. Please refer to this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/).
