### ISSUE TITLE
VirtualTable - height='auto'

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1935]
Hi @MaximKudriavtsev,
in your example https://codesandbox.io/s/k3yyl82417
the height="auto" paramiter in VirtualTable does not work properly.

If you try to reduce the height of the browser and then increase it, the horizontal scrollbar remains in the middle of the screen.

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,
 
I cannot reproduce it. The demo looks fine on my side, see the following:
 
![animation-for-issue](https://user-images.githubusercontent.com/15093892/54897558-feba4200-4ed9-11e9-8709-c43fb3ee2ff2.gif)
 
Could you please make a .gif animation or more clear example demonstrating the issue?

**Comment by ccamusso** [comment]
This is my recording: 
https://drive.google.com/file/d/155tq2dtvx-Lj_IDaI1rxbaVlCZYiEp9c/view

**Comment by MaximKudriavtsev** [comment]
Okay, thank you, I see the problem. We have already fixed this [bug](https://github.com/DevExpress/devextreme-reactive/issues/1795). Please update your versions of DevExtreme Reactive, `react` and `react-dom` packages.

Follow the updated [example](https://codesandbox.io/s/r478pzn19m).
