### ISSUE TITLE
editing a row and scrolling the rows and columns

### ISSUE THREAD

**Issue by bhargav2496** [DevExpress/devextreme-reactive#1941]
I have an editable table now I want to add scrolling to that table and want to make a sticky columns to that table  when I add the `<VirutalTable>` tag to the code it  is not editable and if I remove  the columns are not sticky
Refer the gist <script src="https://gist.github.com/bhargav2496/86f8a4e1c9d382fab4d489b2f956930f.js"></script>

**Comment by MaximKudriavtsev** [comment]
Hi @bhargav2496,
 
I found a few problems in your code:

- you added the `TableHeaderRow` plugin twice.
- you added the `Table` and `VirtualTable` plugins together, which is incorrect. See the [following guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#related-plugins).

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
