### ISSUE TITLE
Set TableBandHeader title to center

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1942]
Is possible set TableBandHeader title to center.
I try with this example bud not work:
https://codesandbox.io/s/lpw138v207 (row 120)

CC

**Comment by ushkal** [comment]
Hi @ccamusso 

The [`ColumnBands`](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-band-header/#tablebandheadercolumnbands) interface does not support the `align` property. To implement your task I suggest you assign a text-align style to a Cell component using a `cellComponent` property of the [TableBandHeader](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-band-header/#properties) plugin. Please refer to the updated [sample](https://codesandbox.io/s/x9mnqv0zjp).
