### ISSUE TITLE
Enable 'messages' to be non string 

### ISSUE THREAD

**Issue by neriag** [DevExpress/devextreme-reactive#1944]
Hi!

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Many React-Grid sub-components receive prop named "messages"
(TableHeaderRow, TableEditColumn, PagingPanel, SearchPanel and others).
Right now, the messages have to be strings (otherwise warning appears in the console, caused by prop-types). However, sometimes I want to use component instead of string, for example - I want my own **button** to replace the "DELETE" message, not only my own **text**.

Is it possible to enable non-string input as a message?

Thanks in advance!

**Comment by MaximKudriavtsev** [comment]
Hi @neriag,

It is not possible. We recommend using `messages` properties if you want to change only default texts. If you want to change components you should create a [custom component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#customize-the-appearance).

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
