### ISSUE TITLE
About Load Remote Data on Demand

### ISSUE THREAD

**Issue by ahmetsezen** [DevExpress/devextreme-reactive#1946]
- [ X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
We have a problem with Load Remote Data on Demand.
We want to apply that example(Load Remote Data on Demand) as shown in link https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/

**We want to show arrow every row after clicked the row we want to send request to our api.**

Our API link like that http://localhost:3000/id/20004

then our result, this result for user which is id's 20004
```
"error": false,
   "status": 200,
   "result": [
       {
           "user_id": "20004",
           "parent_id": "0",
           "sponsor_id": null,
           "name": "name3",
       },
       {
           "user_id": "5306",
           "parent_id": "0",
           "sponsor_id": "20004",
           "name": "name2",
       },
       {
        "user_id": "5308",
        "parent_id": "5308",
        "sponsor_id": "20004",
        "name": "name",
        }

   ],
   "msg": "Team Tree Info."

```
**this result for user which is id's 5308**
```
{
"user_id": "5308",
"parent_id": "5308",
"sponsor_id": null,
"name": "hava",
},
{
"user_id": "4",
"parent_id": "0",
"sponsor_id": "5308",
"name": "ateş",
},
```

**we match sponsor_id = user_id or null for child rows but we couldn't get the idea how we display arrow for every row and when clicked the arrow send request to api and show them their parent**

**Our code** 
```
const getChildRows = (row, rootRows) => {
  const childRows = rootRows.filter(r => (r.sponsor_id === (row ? row.user_id : null)) );
  if (childRows.length) {
    return childRows;
  }

  return childRows.filter(r => (r.sponsor_id === (row ? row.user_id : null)));
};
```

```
loadData() {
    const { expandedRowIds, data, loading } = this.state;

    if (loading) {
      return;
    }

    const rowIdsWithNotLoadedChilds = [ROOT_ID, ...expandedRowIds]
    .filter(rowId => this.state.data.findIndex(row => row.parent_id === rowId) === -1);

    if (rowIdsWithNotLoadedChilds.length) {
      if (loading) return;
      this.setState({ loading: true });
      Promise.all(rowIdsWithNotLoadedChilds
        .map(rowId => fetch(`${URL}/${rowId}`)
          .then(response => response.json())))
        .then((loadedData) => {
          this.setState({
            data: data.concat(...loadedData),
            loading: false,
          });
        })
        .catch(() => this.setState({ loading: false }));
    }
  }
```
```
 changeExpandedRowIds(expandedRowIds) {
    this.setState({ expandedRowIds });
  }
```

```
 render() {
    const { rows, columns, expandedRowIds, tableColumnExtensions, data } = this.state;

    return (
      <Paper>
        <Grid rows={data} columns={columns} getRowId={getRowId} >
          <TreeDataState  expandedRowIds={expandedRowIds}
          getRowId={getRowId}
            onExpandedRowIdsChange={this.changeExpandedRowIds} />
          <CustomTreeData getChildRows={getChildRows} />
   
          <VirtualTable
            
            columnExtensions={tableColumnExtensions}
          />
         
          <TableHeaderRow />
          <TableTreeColumn for="kullAd" />
        </Grid>
      </Paper>
    );
  }
```

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

To show an arrow for each row, even for leaves, you need to return an empty array from the `getChildRows` function. Please refer to this [example](https://codesandbox.io/s/189njlqmrq) for more details.

Would you please clarify why you don't want to show arrows only for nodes like in our [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data#load-remote-data-on-demand)?

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
