### ISSUE TITLE
Adding Plugins beside groupingPanel Toolbar

### ISSUE THREAD

**Issue by yotamberk** [DevExpress/devextreme-reactive#1951]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description

Is there a way to add a plugin to the left of the GroupingPanel in the Toolbar?
(https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/)
I know it is possible to add Plugins to the `toolbarContent` target but it's not quite what I need. I'd like my plugin to target the other side of the toolbar before the GroupingPanel

**Comment by MaximKudriavtsev** [comment]
Hi,

We've already registered the similar issue #723.
