### ISSUE TITLE
Add one custom header button ( Expand/Collapse All)

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#1953]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
   I would like to add a custom button in the header (see attachment). This would be a "expand/collapse all button". I wish to keep all the other header titles. I know about "TableHeaderRow cellComponent={}" but it seems to overwrite all of the header. Is it possible to add custom button in the header or implement a expand/collapse all button ?

![image](https://user-images.githubusercontent.com/44379473/55744483-0bbf5100-5a03-11e9-8945-e9ec9db30117.png)

### Environment
- devextreme-reactive: 1.10.1
- react: 16.8.1
- browser: Chrome V73.0.3683.86 64bit
- bootstrap: none
- react-bootstrap: none
- material-ui: 1.10.1

**Comment by MaximKudriavtsev** [comment]
Hi @franciscailleAstus,
 
We suggest adding custom buttons into the Toolbar plugin. For more information, see [this topic](https://github.com/DevExpress/devextreme-reactive/issues/723).
Adding custom elements into `TableheaderRow` can break our markup alignment.
For the `Expand/Collapse all button` implementation, see [here](https://github.com/DevExpress/devextreme-reactive/issues/1275).

**Comment by franciscailleAstus** [comment]
Hi @MaximKudriavtsev,
Thanks for the answer.

Is it possible that it does not work with the latest versions ?
https://stackblitz.com/edit/react-emb86m?file=package.json

**Comment by MaximKudriavtsev** [comment]
@franciscailleAstus,

The updated example https://codesandbox.io/s/kk2jnnyyn5

**Comment by franciscailleAstus** [comment]
@MaximKudriavtsev Thanks again for the answer. 
This seems to be for _RowDetailState_. Is there a way to do something similar with _GroupingState_ ?

**Comment by MaximKudriavtsev** [comment]
@franciscailleAstus,

You can see in this [topic](https://github.com/DevExpress/devextreme-reactive/issues/756) how to work with Grouping. I created a [simple example](https://codesandbox.io/s/884kzv73k8) to demonstrate the implementation of the `Expand/Collapse` button for grouping. You can play with logic and customize behavior as you like.

**Comment by franciscailleAstus** [comment]
@MaximKudriavtsev 
Thank you very much !
