### ISSUE TITLE
Column Bands problem with horizontal scrolling 

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#1955]
I encountered a strange  alignment problem with Column Bands when doing horizontal scrolling

This is a video
https://drive.google.com/file/d/1P22mUmKQA6PyPDJJBLpfB9f1ltk8cnMv/view

This is code
https://codesandbox.io/s/lpw138v207

**Comment by ushkal** [comment]
Hi @ccamusso, 
Thank you for reporting the issue. This is a known issue and will be resolved in the context of #1389
