### ISSUE TITLE
VirtualTable scrolls container element on update

### ISSUE THREAD

**Issue by jesusgp22** [DevExpress/devextreme-reactive#1960]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I am using virtual table for several tables in my application, they are contained within an scrollable div that sometimes gets randomly scrolled when a table is updated

### Expected Behaviour
No scrolling of the container div

### Steps to Reproduce
I added an scroll listener in the scrollable element to wait for these random scroll events to happen:

this.rootEl.addEventListener('scroll', (e) => {
                    debugger
                    console.log("scroll", e)
                })

The Grid component itself looks like this:
```
<Grid
                    rows={locked ? lockedData : data}
                    columns={columns}
                    rootComponent={Root}
                    getRowId={this.getRowId}
                >
                    <DragDropProvider />
                    <FilteringState
                        filters={filters}
                    />
                    <IntegratedFiltering />
                    {
                        sortingEnabled && (
                            <SortingState
                                sorting={sorting}
                                onSortingChange={setTableSorting}
                            />
                        )
                    }
                    {
                        sortingEnabled && <IntegratedSorting columnExtensions={[{ columnName: 'status', compare: compareStatus }]} />
                    }
                    {
                        hasChildren && <TreeDataState
                            expandedRowIds={expandedRowIds}
                            onExpandedRowIdsChange={this.changeExpandedRowIds} />
                    }
                    {
                        hasChildren && <CustomTreeData getChildRows={getChildRows} />
                    }
                    {
                        hasDetails && <RowDetailState expandedRowIds={expandedRowIds} onExpandedRowIdsChange={this.changeExpandedRowIds} />
                    }
                    <SelectionState
                        selection={selection}
                        onSelectionChange={this.changeSelection}
                    />
                    <VirtualTable
                        height="auto"
                        estimatedRowHeight={20}
                        columnExtensions={columnExtensions}
                        cellComponent={Cell}
                    />
                    <TableColumnReordering
                        order={columnOrder}
                        onOrderChange={setColumnOrder}
                    />
                    <TableColumnResizing
                        columnWidths={columnWidths}
                        onColumnWidthsChange={setColumnWidth}
                        minColumnWidth={32}
                    />
                    <TableSelection
                        selectByRowClick
                        highlightRow
                        showSelectionColumn={false}
                        rowComponent={this.Row}
                    />
                    <TableHeaderRow
                        showSortingControls={sortingEnabled}
                        sortLabelComponent={SortLabel}
                    />
                    {
                        hasChildren && <TableTreeColumn
                            for="ordersPlaced"
                            indentComponent={TreeIndentComponent}
                            cellComponent={TreeColumnContent}
                            expandButtonComponent={TreeExpandButtonComponent}
                        />
                    }
                    {
                        hasDetails && <TableRowDetail contentComponent={this.props.RowDetail} />
                    }
                    <TableColumnVisibility
                        hiddenColumnNames={hiddenColumnNames}
                        onHiddenColumnNamesChange={setColumnVisibility}
                    />
                    <Toolbar
                        rootComponent={this.TableToolbar}
                    />
                </Grid>
```

The browser points to the following line of this file on the scroll listener callstack:

return [row, node.getBoundingClientRect().height];

(as seen here) https://github.com/DevExpress/devextreme-reactive/blob/5d58a5808a1903cef9c5d65b5ca7e7e43f91d157/packages/dx-react-grid/src/components/table-layout/virtual-table-layout.tsx

### Screenshots
Here is a sample of the call stack showing the last function call before the scroll listener callback gets called

![image](https://user-images.githubusercontent.com/2547899/55835321-7b0b7280-5ae1-11e9-9d61-21ad5ec9eca9.png)
****

### Environment

OS: Windows 10x64

- devextreme-reactive: 1.10.0
- react: 16.8.4
- browser: Chrome
- bootstrap: 4
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @jesusgp22,

I don't reproduce your issue. Could you modify [my example](https://codesandbox.io/s/pk2zo6v30m) to demonstrate wrong behavior?

**Comment by jesusgp22** [comment]
Hi @MaximKudriavtsev , 

After a bit of fiddling I finally found a reliable replication example:

To replicate the issue first scroll the container-element to about the top of the react-grid component (see the screenshot bellow)

NOTICE THAT THE ISSUE WILL NOT HAPPEN UNTIL YOU SCROLL THE container-element 

![image](https://user-images.githubusercontent.com/2547899/56674594-ef1c4d80-667f-11e9-9402-c8768ea7c4e9.png)

See how it is scrolled every second until the table is completely out of view

Here is the forked sandbox: https://codesandbox.io/s/0yqwo56ovp

**Comment by jesusgp22** [comment]
Setting up a debugger statement shows the same stack trace as seen on my app

![image](https://user-images.githubusercontent.com/2547899/56675567-09572b00-6682-11e9-86a4-6cf612590e9e.png)

**Comment by MaximKudriavtsev** [comment]
Hi @jesusgp22,


We need more time to research this issue. Currently, we suggest you pass the `overflow: hidden` style property to your grid's container component (line 123). Please refer to a [workaround here](https://codesandbox.io/s/4qr2zw9qw4).

**Comment by jesusgp22** [comment]
Hey @MaximKudriavtsev thanks for the workaround it does seem to work for me, I am looking forward to understand what's the root cause of this rather specific issue.

**Comment by MaximKudriavtsev** [comment]
@jesusgp22,

We need time to research the issue. We will update this topic when we have any results.

**Comment by MaximKudriavtsev** [comment]
[Sample](https://codesandbox.io/s/vqn7oyr2x5) for debugging.

**Comment by jesusgp22** [comment]
Seems like they have given a response:

https://bugs.chromium.org/p/chromium/issues/detail?id=957959

**Comment by MaximKudriavtsev** [comment]
@jesusgp22,

Yes, you can fix the issue by adding `overflow-anchor: none` to the scrollable container of your application. See the following [example](https://codesandbox.io/s/y2l07nx1v1) (line 112).
