### ISSUE TITLE
How to override React Scheduler components and use its interfaces

### ISSUE THREAD

**Issue by azazel404** [DevExpress/devextreme-reactive#1961]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x ] React Scheduler

### Description
i want custom DateNavigator , but documentation is not good
how to use this props DateNavigator.NavigationButtonProps
after im try for myself , calender left and right has gone , cant do anyting
please fix documentation with example if we use that components

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @azazel404,
 
The DevExtreme React Scheduler provides the capability to [rewrite default UI components](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance). You can pass your custom React components or customize our built-in components.
All UI plugins have properties with the `Component` postfix (xxxComponent) where you can pass your components. For example, we have the [DateNavigator](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/date-navigator/) plugin. This plugin has the `rootComponent`, `overlayComponent`, `toggleButtonComponent` and `navigationButtonComponent` properties. All of these properties has an interface. That is a set of properties that will be passed into the component.
 
```js
 

const CustomNavigationButton = (props) => {
  console.log(props); // { onVisibilityToggle, type }
  return (
    <DateNavigator.NavigationButton {...props}  />
  );
};

...
<DateNavigator
  navigationButtonComponent={CustomNavigationButton}
/>
...
```
 The props above has next [interface](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/date-navigator/#datenavigatornavigationbuttonprops).
 
Please see an online [example](https://codesandbox.io/s/ppmnq8jkpq).

**Comment by azazel404** [comment]
@MaximKudriavtsev  how about AppointmentTooltip.LayoutProps
i use AppointmentTooltip.HeaderProps try to custom Header Appointment Header
but..
showCloseButton has gone if i custom this AppointmentTooltip.HeaderProps.
then i try to custom Layout Appointments but still not solve use this props "AppointmentTooltip.LayoutProps" , how to use this "AppointmentTooltip.LayoutProps" 
please give example in documentation web sir , 1 month to show showclosebuton still not solve

**Comment by MaximKudriavtsev** [comment]
@azazel404,

Please use this sample to create an online example to illustrate the issue. Describe how you would like to customize UI.

**Comment by azazel404** [comment]
if i custom Header like this https://codesandbox.io/s/p9yvj43w0m
we can see if you click appoitments , appoitments tooltip no have button exit if appoitment tooltip running
 if i not custom header appointments and delete headerComponent={customHeader} from appointments tooltip
button exit from appoitment tooltip its work
how to implement showCLoseButton if we custom the appoitment tooltip
@MaximKudriavtsev

**Comment by MaximKudriavtsev** [comment]
@azazel404,

Do not forget to pass properties into our components. You can refer to this [example](https://codesandbox.io/s/1v0vz64xnj).
You can also see how to customize the [AppointmentTooltip](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/) plugin in the [following demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/):

**Comment by azazel404** [comment]
oh , i think children is not properties,  thanks for ask my question and solved my error
excited this library for manage Calendar , but i suggest to give example properties in documentation sir 
thanks for helping me

**Comment by MaximKudriavtsev** [comment]
You are welcome!
