### ISSUE TITLE
TableColumnResizing : set width by ID insted of columnName

### ISSUE THREAD

**Issue by InstantProgramming** [DevExpress/devextreme-reactive#1967]
- [ X ] React Grid

### Description
For the moment, the TableColumnResizing works by giving a width and a columnName as on object.
In my case, i have a tool that rename the TableColumns who are saved into a Database with graphQL so when a tableColumn get renamed i get the error : 
The "XXXX" column's width is not specified.
The TableColumnResizing plugin requires that all columns have the specified width.
A refetch of table Columns is done imediatly after the column Updates, when I delete a column it's all good, same when i Add one, but when i rename it's throw me this error. 

I guess if we could set default widths by the ID of the columns should save the problem.

Thanks in advance, and thanks a lot for this awesome Datatable !

**Comment by MaximKudriavtsev** [comment]
Hi @InstantProgramming,

You can pass your Database column a `name` property of the [Column](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/#column) interface. And change its `title` property to correctly display information in your table. You can use the `name` property as the column ID.

**Comment by InstantProgramming** [comment]
This solution fit perfectly, thanks a lot it solved my issue !
