### ISSUE TITLE
When adding filters I get: TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1968]
It would be nice to have all the source for this example as its not complete.

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/

Another example is in the sorting page

`    const { rows, columns, sorting } = this.state;`

but there are no definitions for these state params, or for the `changeSorting` function. Which means its harder to get a local version running.

**Comment by QuantumInformation** [comment]
Its ok, I found the expand arrows button to click on which shows the code.

I added this to my table

```   <FilteringState filters={filters} onFiltersChange={this.changeFilters} />
          <TableFilterRow />

          <IntegratedFiltering />
```

but get this error now
![image](https://user-images.githubusercontent.com/216566/56088343-b5289b80-5e76-11e9-8cc2-f2839409c9ec.png)

**Comment by QuantumInformation** [comment]
Changing the order of the Grids children fixed it

**Comment by MaximKudriavtsev** [comment]
Hi @QuantumInformation,

The DevExtreme Reactive plugins extend the [Data Piping principle](https://en.wikipedia.org/wiki/Pipeline_(computing)) and says that the next plugin changes previous plugin data - see the [Plugin Order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order).

**Comment by QuantumInformation** [comment]
great thx
