### ISSUE TITLE
Error when adding new series elements

### ISSUE THREAD

**Issue by alexkirsz** [DevExpress/devextreme-reactive#1971]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour

Adding new series after rendering the chart for the first time throws an error.

### Expected Behaviour

New series should be correctly added to the chart.

### Steps to Reproduce
https://codesandbox.io/s/vnqlwxlp0l

### Environment
See CodeSandbox

**Comment by DmitryBogomolov** [comment]
Hello.

We need time to research the issue.
For now use the [following workaround](https://codesandbox.io/s/8yx9yo3900).

**Comment by DmitryBogomolov** [comment]
[Sample](https://codesandbox.io/s/8zrj7mr2k9) for debugging.

**Comment by DmitryBogomolov** [comment]
Closed via https://github.com/DevExpress/devextreme-reactive/pull/2002.
