### ISSUE TITLE
Sort icons missing in header

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1973]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Sort icons missing in header### Expected Behaviour

Up and Down icons to show

### Steps to Reproduce

use these imports

```
import {
  Column,
  FilteringState,
  IntegratedFiltering,
  IntegratedSorting,
  SortingState
} from '@devexpress/dx-react-grid'
import {
  Grid,
  VirtualTable,
  TableHeaderRow,
  TableFilterRow
} from '@devexpress/dx-react-grid-bootstrap4'

import 'bootstrap/dist/css/bootstrap.css'

```

### Screenshots

![image](https://user-images.githubusercontent.com/216566/56123689-de2b5800-5f6c-11e9-86d1-a0d2446bd6ee.png)

### Environment

 "@devexpress/dx-react-core": "^1.10.5",
    "@devexpress/dx-react-grid": "^1.10.5",
    "@devexpress/dx-react-grid-bootstrap4": "^1.10.5",
    "applicationinsights-js": "^1.0.18",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "es6-shim": "^0.35.3",
    "lodash": "^4.17.10",
    "react": "^16.8.6",

**Comment by QuantumInformation** [comment]
Looks like a missing style, although I don't see any failed font requests

![image](https://user-images.githubusercontent.com/216566/56125550-17fe5d80-5f71-11e9-9322-0fd7c09dfbef.png)

**Comment by MaximKudriavtsev** [comment]
You should install the [OpenIconic icons](https://useiconic.com/open) also.
See the [Installation guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/).
![image](https://user-images.githubusercontent.com/15093892/56128838-6a4b7880-5f89-11e9-8f18-39835dbcf4f6.png)

**Comment by QuantumInformation** [comment]
ok thx,


![image](https://user-images.githubusercontent.com/216566/56129040-2cdeef00-5f79-11e9-9035-e3eca9e49dce.png)

**Comment by QuantumInformation** [comment]
Ok thx, but why not use font-awesome which has higher likelyhood of being used.
