### ISSUE TITLE
Arrow functions needed in Class properties examples

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1976]
Docs should use arrow functions in places like this

`  commitChanges = ({ added, changed, deleted }) => {`

instead of `  commitChanges({ added, changed, deleted }) {
`

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/

```js
export default class Demo extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      columns: [
        { name: 'name', title: 'Name' },
        { name: 'sex', title: 'Sex' },
        { name: 'city', title: 'City' },
        { name: 'car', title: 'Car' },
      ],
      rows: generateRows({
        columnValues: { id: ({ index }) => index, ...defaultColumnValues },
        length: 8,
      }),
    };

    this.commitChanges = this.commitChanges.bind(this);
  }

  commitChanges({ added, changed, deleted }) {
    let { rows } = this.state;
    if (added) {
      const startingAddedId = rows.length > 0 ? rows[rows.length - 1].id + 1 : 0;
      rows = [
        ...rows,
        ...added.map((row, index) => ({
          id: startingAddedId + index,
          ...row,
        })),
      ];
    }
```

otherwise this.props/this.state will be undefined

**Comment by DmitryBogomolov** [comment]
Hello.

There is 
```js
this.commitChanges = this.commitChanges.bind(this);
```
that prevents `this` from being undefined inside callback.

Do you have a sample where it is undefined?

**Comment by QuantumInformation** [comment]
Ah found it now, I would defo remove the binds and switch to arrows. Is it not possible.

Also, I would get rid of the collapsed arrows in the source, makes it really annoying to read and search on the page.
