### ISSUE TITLE
Filter input loses focus on typing a character

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1977]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I've followed the controlled example here

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/

However when typing the input loses focus.

Followed on from here

https://github.com/DevExpress/devextreme-reactive/issues/771

our code looks like this:

```
<Grid rows={downtimes} columns={columns} rootComponent={Root}>
          <SortingState />
          <FilteringState filters={filters} onFiltersChange={this.changeFilters} />
          <IntegratedFiltering />
          <IntegratedSorting />

          <EditingState onCommitChanges={this.commitChanges} />
          <VirtualTable height={'auto'} />
          <TableFilterRow />
          <TableHeaderRow showSortingControls />
          <TableEditRow />
          <TableEditColumn showAddCommand={true} showEditCommand />
        </Grid>
```

`    this.changeFilters = filters => this.setState({ filters })`
 

### Environment

 "@devexpress/dx-react-core": "^1.10.5",
    "@devexpress/dx-react-grid": "^1.10.5",
    "@devexpress/dx-react-grid-bootstrap4": "^1.10.5",
    "applicationinsights-js": "^1.0.18",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "es6-shim": "^0.35.3",
    "lodash": "^4.17.10",
    "open-iconic": "^1.1.1",
    "react": "^16.8.6",

**Comment by ushkal** [comment]
Hi @QuantumInformation,

I've created a sample project based on our demo and the code you provided, but couldn't reproduce the issue. Can you please modify this [project ](https://codesandbox.io/s/1075zr955j)so that the problem is reproduced?

**Comment by QuantumInformation** [comment]
Yeah, it's in a larger codebase and moved to another solution so not going to have time to replicate. Shall I close?
