### ISSUE TITLE
Could we have multiline columns for all columns without having to specify?

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1979]
Instead of doing
`      tableColumnExtensions: [{ columnName: 'comment', wordWrapEnabled: true }]`

for all columns, would be nice to just tell it to apply to all of them.

**Comment by QuantumInformation** [comment]
Also, the wrapping doesn't apply to words longer than the width. That would be nice too.

**Comment by ushkal** [comment]
Hi @QuantumInformation,
 

> would be nice to just tell it to apply to all of them

Thank you for this suggestion. We will consider implementing it in the future. 
 
> the wrapping doesn't apply to words longer than the width

To customize cell wrapping behavior, you can override the 'tableCell' component of the [Table](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#properties) plugin and assign a word-wrap style there. Here's an [example](https://codesandbox.io/s/pykonnpx5j).
