### ISSUE TITLE
The incredible shrinking dataGrid, loses elements on reach re-render

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1980]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

After each render the grid gradually loses each component eleent

1st render
![image](https://user-images.githubusercontent.com/216566/56290120-5daa5a00-611a-11e9-9543-5f79aceea7bc.png)
2nd render
![image](https://user-images.githubusercontent.com/216566/56290145-68fd8580-611a-11e9-89ce-39627c6813b2.png)
3rd
![image](https://user-images.githubusercontent.com/216566/56290181-79156500-611a-11e9-8b25-c76afc3e3966.png)
4th
![image](https://user-images.githubusercontent.com/216566/56290199-86caea80-611a-11e9-960f-6894a4ea20d9.png)

### Expected Behaviour

Not to do this

### Steps to Reproduce
```
  public render() {
    const Root = props => <Grid.Root {...props} style={{ height: '100%' }} />
.
.
        <Grid rows={downtimes} columns={columns} rootComponent={Root}>
          <SortingState />
          <FilteringState
            filters={filters}
            columnExtensions={tableColumnExtensions}
          />
          <Integrat
```

### Environment

```
 "@devexpress/dx-react-core": "^1.10.5",
    "@devexpress/dx-react-grid": "^1.10.5",
    "@devexpress/dx-react-grid-bootstrap4": "^1.10.5",
    "applicationinsights-js": "^1.0.18",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "es6-shim": "^0.35.3",
    "lodash": "^4.17.10",
    "open-iconic": "^1.1.1",
    "react": "^16.8.6",
```

Suffice to say this is a showstopper for us

**Comment by ushkal** [comment]
Hi @QuantumInformation,
 
Unfortunately the information you provided is insufficient to reproduce the issue. Please send us a runnable example - you can fork our codesandbox [sample](https://codesandbox.io/s/rymyjlonpq).

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
