### ISSUE TITLE
Placing a virtualized grid grows in height indefinitely.

### ISSUE THREAD

**Issue by QuantumInformation** [DevExpress/devextreme-reactive#1981]
Placing a virtualized grid with height auto inside an outer container with vh height, causes the grid to grow in height indefinitely.

![image](https://user-images.githubusercontent.com/216566/56295590-ef1ec980-6124-11e9-8d28-c5c70c617be0.png)

I'm afraid I will have to move away from this lib for now as having too many teething issues,

**Comment by MaximKudriavtsev** [comment]
Hi @QuantumInformation,

It is difficult to determine the cause of the problem by analyzing a screenshot. Moreover, your screenshot does demonstrate your Grid component configuration. We kindly ask you provide detailed information regarding your issues. This will help us find appropriate solutions much faster.

I assume that you do you specify the height of the grid's root element using the [rootComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/#user-reference) as shown in this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#fill-the-container). Try this solution and let us know your results.

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
