### ISSUE TITLE
Overriding DayScale component to ignore dates

### ISSUE THREAD

**Issue by AngelineLim** [DevExpress/devextreme-reactive#1987]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I would like to use React Scheduler to render a generalised weekly (and potentially monthly) schedule to be customised by the users. For instance, in the week view, I would like to **override the DayScale component to only show the days of a week** (e.g Sunday to Saturday), hence excluding the dates. 

![image-desc](https://user-images.githubusercontent.com/6859192/56504536-63a1a000-654b-11e9-9c63-d38d25e8f102.png)

However, referring to [WeekView Plugin Reference](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler/docs/reference/week-view.md#weekviewdayscalecellprops), using the WeekView.DayScaleCellProps is a bit restrictive as passing a null startDate will lead to a string "undefined" being rendered. 

How can I do so to achieve my goal? The dates seems to be tied to React Scheduler's day-scale layout at the moment. 

### Environment
- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @AngelineLim,

The [DevExtreme Reactive controls](https://devexpress.github.io/devextreme-reactive/react) give the flexible capability to customize default UI components, see Scheduler's [Fundamentals guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance). In your case, you should override a DayScaleCell component of the [WeekView](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/) plugin. You can pass your custom markup into DayScaleCell based on components props, and in this case, components props are [DayScaleCellProps](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewdayscalecellprops). You can see what markup we pass into the DaySclaeCell component by default in this [file](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/day-scale/cell.jsx).

Please see the following [example](https://codesandbox.io/s/6l79wrxz7n).

**Comment by AngelineLim** [comment]
Hey @MaximKudriavtsev , that worked perfectly, thank you!

**Comment by MaximKudriavtsev** [comment]
@AngelineLim, you are welcome!
