### ISSUE TITLE
commandComponent in TableEditColumn not rerendering when I check a selection

### ISSUE THREAD

**Issue by gigi206** [DevExpress/devextreme-reactive#1989]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
The issue occurs since version 1.10.1. It works well with version 1.10.0.

I use [TableEditColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumn-plugin-reference) with **commandComponent** props :
```
Command = ({id, onExecute}) => {
    console.log(this.state.selection)
    const CommandButton = this.commandComponents[id]
    return (
        <CommandButton
            onExecute={onExecute}
        />
    )
}

<TableEditColumn
    width={160}
    showAddCommand
    commandComponent={this.Command}
    cellComponent={this.Cell}
/>
```

When I use [selection](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/#react-grid---selection) and I click on a checkbox the function **Command** is never called.

Since version 1.10.1, console.log(this.state.selection) print an empty selection only when the page is loaded and not when I change the selection.

### Screenshots
With version 1.10.0 it works :
![](https://i.ibb.co/SJ7MBJZ/Capture-d-cran-de-2019-04-23-22-01-20.png)

With version 1.10.1 and superior 2/2 on the screenshot is replaced by 0/0.

**Comment by MaximKudriavtsev** [comment]
Hi @gigi206,

I don't reproduce your issue. Could you modify my [example](https://codesandbox.io/s/104r5l0r47) to demonstrate wrong behavior?

**Comment by gigi206** [comment]
Comment line 114.

The console.log line 102 print nothing if you change the selection with a superior version to 1.10.0

[This example](https://codesandbox.io/s/pmm57n20zx) with version 1.10.0 works.

**Comment by MaximKudriavtsev** [comment]
@gigi206,

OK, I see. This is expected since when you update the `selection` component, the `editing` component should not re-render. When you click the edit button, you can see it re-render.

In the 1.10.1 version, we have fixed this bug, and it now works as expected.

**Comment by gigi206** [comment]
It's annoying because new version break my code.

How to do [this example](https://codesandbox.io/s/pmm57n20zx) (create an action button to this place) with version 1.10.1 and superior ?

**Comment by MaximKudriavtsev** [comment]
@gigi206,

You can use our HOC [connectProps](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/connect-props/); take a look at the [Optimize Performance guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) for details about it.

In the [following example](https://codesandbox.io/s/46nrl9mo4), we use the `connectProps` function that passes a parent's state into a component's props. Note that we use `props` instead of `state` inside the `Command` component.

**Comment by gigi206** [comment]
It works great !

Thank you very much for your help :)
