### ISSUE TITLE
<VirtualTable rowComponent="..."> vs <Template name="tableRow">?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1994]
I am trying to use React Grid and I am going through documentation (to adjust row), samples and I need the following clarification, please.

I have the React component with inner custom Row component:

```
Row = ({ tableRow, ...restProps }) => {
  return (
	<Table.Row
	  {...restProps}
	  style={{backgroundColor: 'LightBlue'}}
	/>
  );
}
```
and the same React component returns the following markup (I provide only part of it):
```
<Grid>
        rows={this.props.orders}
        columns={this.state.columns}>
        ...
	<VirtualTable rowComponent={this.Row}/>
	<Template
	  name="tableRow"
	  predicate={ ({ tableRow }) => true }
	>
	  {params => (
		<TemplateConnector>
		  {() => (
			<this.Row
			  {...params}
			  onClick = {() => { alert('OK') } }
			  style = {{backgroundColor: 'SlateBlue'}}
			/>
		  )}
		</TemplateConnector>
	  )}
	</Template>
</Grid>	
```
I would like to format row (add a background color, of course more sophisticated formatting will follow later), I made some experimentation and now I feel that I have arrived at two alternative solutions that are doing almost the same thing. One solution is replacing VirutalTable.Row plugin component with this.Row component (I guess, it is higher order React component). Other solution is filling the "tableRow" export with the template.

I just wanted to clarify things:
- are these the equivalent solutions and if not - which one is suitable for what issue?
- in which case we should use <Template name="name_of_some_export_from_the_plugin"> and in which case we should assign (higher order) component to the property of some plugin (e.g. <VirtualTable rowComponent={this.Row}/>),

Some more documentation or examples would be great. Of course, I am aware of https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/ but still it would be nice to have something more (maybe there are another DevExpress tutorials). Is this plugin architecture the standard React design pattern? If yes, are there some general (DevExtreme-agnostic) descriptions of this design pattern (of course, apart from the link to the description of HOC)?

**_I can also observe that the code without <Template...> is not working and essentially the rowComponent is ignored on <VirtualTable...>. In which cases should I use rowComponent (without <Template...>?)_**

**Comment by ushkal** [comment]
Hi @alex153410,
 
> in which case we should use and in which case we should assign (higher order) component to the property of some plugin

We recommend you override the plugin's components to customize the existing Grid parts (rows, cells, etc.).
In case when you want to extend the grid functionality you will need to implement a custom plugin, refer to the [Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) guide for more details.
 
> are these the equivalent solutions and if not - which one is suitable for what issue?

Override rowComponent to customize row appearance, here's an [example](https://codesandbox.io/s/moj6347nqp).
 
> Is this plugin architecture the standard React design pattern?

The plugin architecture is our own concept and meets React principles.
