### ISSUE TITLE
Possible values for TableRow.type?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1995]
I read in https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablerow that TableRow.type is of type symbol with apparently some predefined (expected, possible) values. Where can I find them to use in the predicate of the <Template...> (see e.g. https://github.com/DevExpress/devextreme-reactive/issues/1994)? Currently only guesses and errors are available. Is 'data' a good value?

I would be OK to lookup up them in the source code, but I have no idea where to search for them? In @devexpress/dx-ract-grid.es.js file?

**Comment by ushkal** [comment]
Hi @alex153410,
 
Different row types are exposed by corresponding plugins as a static constant named ROW_TYPE. It is listed in the [Static Fields](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#static-fields) section. So for an ordinary data row, its type equals Table.ROW_TYPE. In the case of a group row, it is [TableGroupRow.ROW_TYPE](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-group-row/#static-fields). 
You can look up for a list of possible values in our documentation or in the dx-react-grid package [sources](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid).
