### ISSUE TITLE
Table with page scroll and fixed title and horizontal scroll?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#1997]
I have this sample https://codesandbox.io/s/1y7or92n7j

I would like the stackoverflow-like-scrolling behavior - let table expand fully the page and let the browser vertical scroll appears. But there should be fixed panels/divs for the header and footer (where the command buttons can sit) and table should have top and bottom margins accordingly. 

That is fine and that works. But 2 issues remains:
1) is it possible to keep title row of the table in the fixed vertical position (immediately below the header div)?
2) is it possible to keep the inner horizontal scroll of table in the fixed vertical position (immediately above the footer div)?

I am aware that I have been quite shameless recently with my frequent questions, but I am actively investigating possible scenarious of the grid. I now know that grid correctly fills the client area and uses inner scroll. And now I have to check whether the stackoverflow like scrolling is possible. Those both uses cases cover all the requirements that I need to fulfill. And those both uses cases are used in the SAP H4, so, they are quite reasonable (though the use of grid in modern web applications is quite confusing thing generally).

**Comment by ushkal** [comment]
Hi @alex153410,
 
> is it possible to keep title row of the table in the fixed vertical position (immediately below the header div)?

Fixing a grid title row is only possible when using the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/) plugin since the Table plugin doesn't support scrolling.
 
> is it possible to keep the inner horizontal scroll of table in the fixed vertical position (immediately above the footer div)?

Yes, it is possible. You need to make the grid container occupy the remaining content height. 
Here's an updated [example](https://codesandbox.io/s/3kq60ok9pp).
