### ISSUE TITLE
React Scheduler: Separate date and time picker to update startDate & endDate

### ISSUE THREAD

**Issue by AngelineLim** [DevExpress/devextreme-reactive#1999]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I would like to customise the AppointmentFormContainer to separate date and time picker, where the dates are only restricted to the current week. What's the best way to **to update both startDate and endDate at the same time from a single input?** 

Referring to your [React Scheduler Data Editing](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/) documentation, I'm currently playing around with the potential idea of: 
- use the current date mapped to the corresponding days of the week to populate dates on dropdown
- onChange() handler to update both startDate and endDate  

Here's a [modified working of your demo](https://codesandbox.io/s/j3x9rn03p9).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @AngelineLim,

Currently, we don't have such a public API to customize our [AppoitnmentForm](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/) plugin. We have plans to enhance this plugin and make its documentation clearer.

You can use our private API. According to the [AppointmentForm source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler/src/plugins/appointment-form.jsx), you can override the `startDateComponent` property and the `endDateComponent` property as well. You can use the [moment.js](https://momentjs.com/) library to make a drop-down list of the current week’s dates.

Please refer to the following [example](https://codesandbox.io/s/3x20w1zl56).
