### ISSUE TITLE
Phantom rows created after rerendering

### ISSUE THREAD

**Issue by andsmi97** [DevExpress/devextreme-reactive#2003]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

After rerendering data, i ve got some phantom rows. If i type english letter 'c' in searchbar in example below and then deleting it i will have another row which came out of nowhere. I also had this problem when i fetched data on different actions. Some rows just did't disappeared.
https://codesandbox.io/s/92j2v4vpr

### Expected Behaviour

Not having rows that doesn't exist

### Steps to Reproduce

https://codesandbox.io/s/92j2v4vpr

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @andsmi97,

You pass the `getRowId` property into the [Grid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/) component, but you also need to specify the `id` property in your data set. Please add the unique `id` property to each your data object. See the [updated example](https://codesandbox.io/s/2z0n3m79wj) that shows how to do this.

**Comment by andsmi97** [comment]
Hi Maxim, 
Thank you for finding that rookie mistake, i don't know how i've missed it :)

However, now I've got another question about multiple IDs tables. Is there any examples showing how to specify getRowId for multiple rows?
Thank you in advance.

**Comment by MaximKudriavtsev** [comment]
@andsmi97,

What do you mean by `multiple IDs tables`? It's unclear to me, please describe it in greater detail.

**Comment by andsmi97** [comment]
@MaximKudriavtsev,

Typical example would be junction table in SQL many to many relationship. It is usually implemented with 3 tables:
Films(filmId, filmName ),
Genres( genreId, genreName),
FilmsGenres(filmId,genreId)

In FilmsGenres table multiple id field would be filmId and genreId.

**Comment by MaximKudriavtsev** [comment]
@andsmi97,

Okay, I see. The DevExtreme Reactive Grid doesn't want to know what IDs you have. The most important thing is to make the `getRowId` function return a unique value for each. 

For example, you can specify a unique ID field for each row and the `getRowId` function as follows
```js
const getRowId = row => row.id;
```

Or combine your ID fields from SQL tables
```js
const getRowId = row => `${row.filmId}_${row.genreId}`
```

**Comment by andsmi97** [comment]
@MaximKudriavtsev great, i haven't thouth about second possibility, that is exactly what i need.
