### ISSUE TITLE
Add icon on a cell

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#2004]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Would we add an icon on the specific cell? In my example, I have a rules property. How can I add a red cross in the cell by using Data type provider?
Is it possible to click on the Need work column and open an expandable pane for showing some information? It only clickable when the row have errors (error: yes)
[example](https://codesandbox.io/s/43xljwx9w4)

### Environment

- devextreme-reactive
- react
- react-bootstrap:

**Comment by MaximKudriavtsev** [comment]
Hi @susuwatari2,

Yes, you can use [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) for this case. I created an [example](https://codesandbox.io/s/4qk2v7nl0x) that works according to your requirements.

**Comment by susuwatari2** [comment]
Hi @MaximKudriavtsev 
That works. In my first row, the city and car column are invalid, how can I add a red cross on the left of the data based on the rules property?

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,

Yes, it is possible. See the following [topic](https://github.com/DevExpress/devextreme-reactive/issues/1266).

**Comment by susuwatari2** [comment]
@MaximKudriavtsev 

Are you suggesting to use the `TableRowDetail` plugin? And call it in `RowDetail`?

I modified your [example](https://codesandbox.io/s/mzqo2n17mx). It doesn't look right if I need to use `<RowDetailState />`. 
I checked the detail row doc - [https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/detail-row/](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/detail-row/)
It requires both `TableRowDetail` and `RowDetailState` plugins. It is different than what I am expecting on  
 `NeedWorkTypeProviderFormatter ` onClick event.

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,

I suggest you override the `toggleCellComponent` of the [TableRowDetail](https://devexpress.github.io/devextreme-reactive/@next/react/grid/docs/reference/table-row-detail/) plugin. The detail row will be expanded by a click on the left cross icon. See the following [example](https://codesandbox.io/s/mj05kxryy).

**Comment by susuwatari2** [comment]
Thank you, @MaximKudriavtsev 

Is it possible to move the `toggleCellComponent`? By overriding, the position cannot change. It is on the first column by default and I am trying to have it on the last column. Is that possible?

**Comment by MaximKudriavtsev** [comment]
@susuwatari2,

See the [following topic](https://github.com/DevExpress/devextreme-reactive/issues/287#issuecomment-429224230) to learn how to change the order of commands.

You should reorder the `tableColumns` [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) by making your own custom plugin. Here is the [Custom Plugin Development guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).

See the following [example](https://codesandbox.io/s/wy27rp2wq8).
