### ISSUE TITLE
How to extend React Scheduler appointment content component 

### ISSUE THREAD

**Issue by AngelineLim** [DevExpress/devextreme-reactive#2008]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hi there, I would like to extend existing appointment content to display additional fields of data such as location, type (so that I can display some sort of icon to indicate the type of appointment) etc. I understand that I can replace the AppointmentContent by doing the following:

`const appointmentContent = ({ data }) => (
  <Appointments.AppointmentContent  style={// I would like to use the original style}>
    // uses field names of the data to display what you want to show
  </Appointments.AppointmentContent>
);`

and then replace your default component with a self-defined component

`<Appointments
      appointmentContentComponent={appointmentContent} />`

However, how can I **simply extend your Appointments.AppointmentContent by appending additional fields I want to display**, without replacing the entire component? 

Thank you in advance! 

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @AngelineLim,

Thank you for the detailed description. We don't have an easier way to customize the markup. You can use our [component's source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/appointment/appointment-content.jsx) to configure your own components.
