### ISSUE TITLE
Fixed column flickers while scrolling

### ISSUE THREAD

**Issue by vamsi0212** [DevExpress/devextreme-reactive#2009]
- [1] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Fixed column flickers while scrolling on ipad /iphone (both safari and chrome). Only th of fixed column flickers on scroll.   

### Expected Behaviour
Shouldn't flicker on scroll 

### Steps to Reproduce

Please open this on xcode simulator or ipad/iphone safari/chrome browser 
https://3y7r72n4ym.codesandbox.io/

Sample Code Here:
https://codesandbox.io/s/3y7r72n4ym

**Comment by ushkal** [comment]
Hi @vamsi0212.
 
We have investigated the issue and found that it is caused by [this bug](https://crbug.com/960267) in the WebKit engine. We cannot overcome it on our side using CSS or JS.

**Comment by vamsi0212** [comment]
@ushkal Thanks for taking time and looking into this. Just logged a bug with apple and will update if i hear anything back.
