### ISSUE TITLE
Support the Material-UI version 4.x.x

### ISSUE THREAD

**Issue by ngochip** [DevExpress/devextreme-reactive#2013]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When I updated material-UI to version 4, there were some changes in spacing,
However, it seems that the library has not changed.

> Warning: Material-UI: theme.spacing.unit usage has been deprecated.
> It will be removed in v5.
> You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.
in dx-react-grid-material-ui.es.js

### Screenshots

<img width="839" alt="Screen Shot 2019-05-08 at 9 26 13 AM" src="https://user-images.githubusercontent.com/11698418/57345045-b5653f80-7173-11e9-9847-bfc1f179d544.png">
<img width="822" alt="Screen Shot 2019-05-08 at 9 25 56 AM" src="https://user-images.githubusercontent.com/11698418/57345063-bd24e400-7173-11e9-86a8-f3a43b2490bd.png">

### Environment

- material-ui: ^4.0.0-beta.1

**Comment by MaximKudriavtsev** [comment]
Hi @ngochip,

We have not yet supported the Material-UI version `4.x.x`. We will consider your suggestion for future releases though.

**Comment by franklixuefei** [comment]
Hi,
Since Material V4 has just been released, do you have an ETA on when Reactive will support V4?

**Comment by MaximKudriavtsev** [comment]
Hi @franklixuefei,

Yes, we are researching the capability of integrating Material-UI V4 support into our library. However, I cannot give you the exact date when the solution will be ready, because there are a lot of underwater stones. We will update our [CHANGELOG](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md) when DevExtreme Reactive is ready for Material-UI V4.

**Comment by guillempuche** [comment]
I also have updated my project to MU v4.

I want to have my UI updated to the latest Material UI theme. For me, MU v4 is a must have for near future.

For this reason, it's necessary to update your awesome React Grid compatibility with the latest MU versions.

**Comment by MaximKudriavtsev** [comment]
Hi @guillempuche,

Thank you for your feedback, the update to v4 is a very important point. We need more time to realize it.

**Comment by TheMoonDawg** [comment]
Thanks for staying aware of the need. 

We're also having to wait to upgrade our core app to MUI 4.0 until the React Grid is updated!

**Comment by zhdanouskikh** [comment]
so, can anyone answer what's the ETA for the version upgrade?

**Comment by MaximKudriavtsev** [comment]
@zhdanouskikh,

At the moment, we are working on some features, which are important for this release. If all goes according to plan, we should publish new versions of DevExtreme Reactive next week.

**Comment by MaximKudriavtsev** [comment]
We have released the `2.0.0` version of [DevExtreme Reactive Components](https://devexpress.github.io/devextreme-reactive/react) with this feature.
