### ISSUE TITLE
Rendering something in the first filter cell

### ISSUE THREAD

**Issue by kg-currenxie** [DevExpress/devextreme-reactive#2015]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is it possible to render something in the "empty cell" next to the first filter? Haven't been able to find something. I guess it would be to override the FilterRow component? 🤔 

![Screenshot 2019-05-09 at 15 12 03](https://user-images.githubusercontent.com/48229166/57434169-e9705b80-726c-11e9-9924-8322bf918e14.png)

**Comment by churkin** [comment]
Hi @kg-currenxie,
According to our reactive grid's customization, you should implement and add to the grid a custom UI plugin that will render target cell content. [Here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) you can read more about custom plugin development and [here](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/rendering-markup/) - about our reactive controls structure and organization. I have created a small [example](https://codesandbox.io/s/1rrx1vymwj) that implements your scenario. Feel free to ask questions.
