### ISSUE TITLE
Custom argument scale

### ISSUE THREAD

**Issue by bonbonio** [DevExpress/devextreme-reactive#2016]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ x] React Chart
- [ ] React Scheduler

### Description
I have a temperature chart, and the labels on the x axis is the date, but I get the data as a timestamp, how can I format the argumentField, the documentation was not clear, but I basically will format the date to day and add a unit.

        <Chart data={data}>
          <ArgumentAxis />
          <ValueAxis />
            <BarSeries valueField="temp_avg" argumentField="date" color="#ffa726" />
          <Animation />
        </Chart>

I could not see an example of this, all the examples had correctly formatted json data initially.

- devextreme-reactive: 1.10.5
- react: 16.8.6
- material-ui: 3.x.x

**Comment by Krijovnick** [comment]
Hello @bonbonio ,
To create datetime argument scale, use [d3 time scale](https://github.com/d3/d3-scale#time-scales) and assign it to the [factory](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-scale/) option in the `ArgumentScale` plugin. You can see how it works in the [demos](https://devexpress.github.io/devextreme-reactive/react/chart/demos/line/log-time-axes/).
