### ISSUE TITLE
Fixed/Sticky headers of the grouped columns

### ISSUE THREAD

**Issue by DanLepsa** [DevExpress/devextreme-reactive#2017]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

We are using React Grid and Virtual Table and would like to always be able to see the headers of the grouped columns, when scrolling horizontally.

**Example before scrolling:**
![before1](https://user-images.githubusercontent.com/13150682/57461224-4b39c100-727f-11e9-90b8-1970d82d9f71.PNG)

**Current behaviour when scrolling:**
![before2](https://user-images.githubusercontent.com/13150682/57461231-4e34b180-727f-11e9-8f7e-102dcc575a4f.PNG)

**What we want to achive**
- grouped column header stays in the same place while scrolling
![after](https://user-images.githubusercontent.com/13150682/57461233-4f65de80-727f-11e9-86e6-af56b94c5481.PNG)

Thanks!

**Comment by MaximKudriavtsev** [comment]
Hi,

We've already registered the similar issue #1798.
