### ISSUE TITLE
Filter input loses focus on typing a character

### ISSUE THREAD

**Issue by tazomazo** [DevExpress/devextreme-reactive#2019]
I was searching for the issue and found a similar topic that was closed without a solution:

https://github.com/DevExpress/devextreme-reactive/issues/1977

What's missing in the linked example (https://codesandbox.io/s/1075zr955j) is a customized cell component (for hiding disabled filters for example).

If you add 
```
<TableFilterRow 
   cellComponent={FilterCell}
/>
```

and

```
const FilterCell = (props) => {
  return <TableFilterRow.Cell {...props} />;
};
```

then the input field loses the focus after every change.

Would be nice to have a fix / workaround for that.

Greets!

**Comment by MaximKudriavtsev** [comment]
Hi @tazomazo,

All work fine on my side. Can you modify my [example](https://codesandbox.io/s/ox6m9460py) to reproduce the issue?



![ScreenRecording20190513at1](https://user-images.githubusercontent.com/15093892/57616503-f3ed6680-7586-11e9-8d1c-0c47e6fc97cd.gif)

**Comment by tazomazo** [comment]
Hi @MaximKudriavtsev,

you didn't add the custom cell component to <TableFilterRow />.

I updaded your example:
ttps://codesandbox.io/s/9yo00kp50y

**Comment by MaximKudriavtsev** [comment]
@tazomazo,

 No, I added a custom cell and defined this component before defining a class. You should avoid defining components inside render methods. Please follow this [guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods) for more information.

The [updated example](https://codesandbox.io/s/vv3x86m1pl).

**Comment by tazomazo** [comment]
@MaximKudriavtsev 

I somehow read over "You should avoid defining components inside render methods"... moved my custom filter component outside the render function and it worked :)

Thank you for the quick support!

**Comment by MaximKudriavtsev** [comment]
@tazomazo,

You are welcome!
