### ISSUE TITLE
rowDetail component disappears on editing in any grid

### ISSUE THREAD

**Issue by matthewjwhitney** [DevExpress/devextreme-reactive#2021]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

on any grid where there is editing, whenever i perform two editing actions (any two of add, edit, delete), the row detail component disappears. there are multiple grid components rendered, one of them being a nested grid in the row detail component.

another thing worth mentioning is when the RowDetail disappears it is replaced with a StubRow.

### Expected Behaviour

RowDetail should not disappear...

### Steps to Reproduce

I have tried to reproduce the problem in a code sandbox but it has proven to be difficult. I have at least copied all of my source code related to this issue without attempting to render it.
https://codesandbox.io/s/n9lpz7npjp

i have created a reusable controlled Grid component. I am guessing the issue has something to do with multiple Grids being rendered on the page somehow but I have no idea. I'm banging my head against the wall about this.

### Screenshots

here is a gif i recorded of it happening.
https://gph.is/g/4Lx9xlp

### Environment

-"@devexpress/dx-core": "^1.10.5",
-"@devexpress/dx-grid-core": "^1.10.5",
-"@devexpress/dx-react-core": "^1.10.5",
-"@devexpress/dx-react-grid": "^1.10.5",
-"@devexpress/dx-react-grid-material-ui": "^1.10.5",
-"@material-ui/core": "^3.9.3",
-"react": "^16.8.6",
- Chromium Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on LinuxMint 19 (64-bit)

**Comment by ushkal** [comment]
Hi @matthewjwhitney,
 
I've tried to make your sample project work but failed: it lacks many utility functions, sample data for the redux store. Please modify the project so that we can use it to reproduce the issue.
