### ISSUE TITLE
TableRowDetail with action buttons

### ISSUE THREAD

**Issue by diegooferreira** [DevExpress/devextreme-reactive#2027]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Environment

Is there a way to use action/icon buttons inside the detail row, with custom actions?

I will try to ilustrate:

![image](https://user-images.githubusercontent.com/3593817/57772815-d9350200-76ec-11e9-86ef-777aa406561a.png)

It's actions columns, custom actions... I will not edit the record.

Someone can help?

Thanks

**Comment by diegooferreira** [comment]
That's my component that render de grid master - detail 

`import React from "react";
import Paper from "@material-ui/core/Paper";
import axios from "axios";
import { withStyles } from '@material-ui/core/styles';
import { RowDetailState, EditingState } from "@devexpress/dx-react-grid";
import { Grid, Table, TableHeaderRow, TableRowDetail, TableEditColumn, TableEditRow } from "@devexpress/dx-react-grid-material-ui";
import AttachMoney from '@material-ui/icons/AttachMoney';
import ThumbUpAlt from '@material-ui/icons/ThumbUpAlt';

const RowDetail = ({ column, children, classes, row, ...restProps }) => (
    <Paper>
        <Grid
            rows={row.itens}
            columns={[{ name: "descricao", title: "Sabor", getCellValue: row => (row.sabor ? row.sabor.descricao : undefined) }, { name: "quantidade", title: "Qtde." }]}>
            <Table columnExtensions={[{ columnName: "quantidade", width: 120 }]} />
            <TableHeaderRow cellComponent={SubHeaderComponent} />
        </Grid>
    </Paper>
);

const ToggleCellComponent = ({ row, ...restProps }) => {
    if (row.isExpand)
        return <TableRowDetail.ToggleCell row={row} {...restProps} />;
    return (
        <TableRowDetail.ToggleCell
            style={{
                pointerEvents: "none",
                opacity: 0.5
            }}
        />
    );
};

const styles = theme => ({
    subHeader: {
        backgroundColor: '#3366CC',
        color: 'white'
    },
    header: {
        fontSize: 16
    },
    button: {
        margin: `0 ${theme.spacing.unit}px`,
    }
});


const HeaderComponentBase = ({ classes, ...restProps }) => (
    <TableHeaderRow.Cell
        {...restProps}
        className={classes.header}
    />
);

const SubHeaderComponentBase = ({ classes, ...restProps }) => (
    <TableHeaderRow.Cell
        {...restProps}
        className={classes.subHeader}
    />
);

export const SubHeaderComponent = withStyles(styles, { name: 'SubHeaderComponent' })(SubHeaderComponentBase);
export const HeaderComponent = withStyles(styles, { name: 'HeaderComponent' })(HeaderComponentBase);

export default class GridContabilizacao extends React.PureComponent {
    componentDidMount() {
        axios.get("API URL", {}).then((res) => {
            
            res.data.forEach(pedido => {
                pedido.isExpand = true;
            });

            this.setState({
                rows: res.data
            });
        }).catch((error) => {
            alert("API Error: " + error);
        });
    }

    constructor(props) {
        super(props);
        
        this.state = {
            rows: []
        };
    }

    render() {
        const { rows, columns, booleanColumns } = this.state;

        return (
            <Paper>
                <Grid rows={rows} columns={[
                    { name: "empresa", title: "Empresa" },
                    { name: "nome", title: "Nome" },
                    { name: "email", title: "E-mail" }]}>
                    <RowDetailState />

                    <Table columnExtensions={[{ columnName: "empresa", width: 120 }]} />
                    <TableHeaderRow cellComponent={HeaderComponent} />

                    <TableRowDetail
                        contentComponent={RowDetail}
                        toggleCellComponent={ToggleCellComponent}
                    />
                </Grid>
            </Paper>
        );
    }
}`

**Comment by ushkal** [comment]
Hi @diegooferreira ,
 
As I understand, you are using a second Grid as a detail row and want to add custom actions in this grid. In this case I recommend you override the cell of the inner grid using the [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecellprops) and add your action there. Please refer to the following [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-f7qso).
