### ISSUE TITLE
How to right define PagingPanel messages with template

### ISSUE THREAD

**Issue by trplfr** [DevExpress/devextreme-reactive#2036]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

Hello!
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
For localization, components have `messages` prop, which accepts a `string`. When I use template literals, instead of the necessary data I get `undefined`.

How to deal with it? I want to use `i18n` with your library.
Thanks!

https://imgur.com/a/SxHMwyK
https://imgur.com/a/BuS03c0

**Comment by MaximKudriavtsev** [comment]
Hi @trplfr,

You need to define a [function](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-panel/#localization-messages) in the `info` field. The following code should work 

```jsx
...
<PagingPanel
  messages={{
    info: ({ from, to, count }) => `${from}${from < to ? `-${to}` : ''} of ${count}`,
  }}
/>
...
```
