### ISSUE TITLE
Parsing error: Unexpected token on simple grid example

### ISSUE THREAD

**Issue by DrainMorten** [DevExpress/devextreme-reactive#204]
Hi! This is probably more a setup issue than a Devexpress react grid issue, but maybe its possible to be pointed in a direction.
In our react app I have followed the devexpress react grid documentation, and installed:

npm i --save @devexpress/dx-react-core @devexpress/dx-react-grid
npm i --save @devexpress/dx-react-grid-bootstrap3

and copied in the simple grid starting code, but I get a parsing error: Unexpected Token on the third '}' in the rows line: rows={[{ id: 0, ... }, ...]}

Sorry if this is very vague, it just does not say much about this type of setup issues in the the documentation. The code is basically the same as the example, but posted a screenshot of the parsing error for easier viewing.

![dxgrid](https://user-images.githubusercontent.com/29375412/28320662-78d77442-6bd1-11e7-8378-2f6ab9e940f7.png)

Any tips is appreciated!
Morten

**Comment by kvet** [comment]
Hi,

`...` means that there may be any number of other fields or array items. You can check our [WebpackBin for Bootstrap3](https://www.webpackbin.com/bins/-KoCcFwPPtps5fEN0PkI) without the `...` symbol.

We will update our basic with less confusing code.

**Comment by DrainMorten** [comment]
Ah, right, thanks! Still learning..

Another issue I encountered when installing bootstrap 3 package from the documentation, only with yarn:
yarn add --dev @devexpress/dx-react-grid-bootstrap3

It seemed to install ok but I got the message:
warning "@devexpress/dx-react-grid-bootstrap3@1.0.0-alpha.5" has unmet peer dependency "react-bootstrap@^0.31.0".

Then when trying to compile i get this error:
ERROR in ./~/@devexpress/dx-react-grid-bootstrap3/dist/dx-react-grid-bootstrap3.es.js
Module not found: Error: Can't resolve 'react-bootstrap' in '...(local file path)...\node_modules\@devexpress\dx-react-grid-bootstrap3\dist'

Is there usually some other places in an application this must be setup also?

**Comment by DrainMorten** [comment]
SOLVED: I solved the above issue by manually installing the react-bootstrap@^0.31.0.

**Comment by kvet** [comment]
I've noticed that we don't require installing of the 'react-bootstrap' package in the documentation. But it is required as DevExtreme React Grid uses it in the Bootstrap 3 templates package. 

Thank you for reporting this issue. We will fix it.
