### ISSUE TITLE
ColumnChooser is jumping to the left corner if select/deselect column from the list

### ISSUE THREAD

**Issue by zhdanouskikh** [DevExpress/devextreme-reactive#2041]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I'm using controlled TableColumnVisibility plugin. When I'm opening ColumnChooser and trying to select/deselect column - all grid is rerendering and ColumnChooser is jumping to the left upper corner of window.

### Expected Behaviour
ColumnChooser is located on the same place where it was before, no grid rerendering should be performed, only necessary parts, like in uncontrolled component.

### Steps to Reproduce
Just see this sandbox example https://codesandbox.io/s/elated-fog-3jc32

### Environment

- @devexpress/dx-react-core: 1.10.5
- @devexpress/dx-react-grid: 1.10.5
- @devexpress/dx-react-grid-material-ui: 1.10.5
- react: 16.8.3
- browser: Chrome 74.0.3729.157 (Official Build) (64-bit)
- bootstrap: none
- react-bootstrap: none
- @material-ui/core: 3.9.2

**Comment by MaximKudriavtsev** [comment]
Hi @zhdanouskikh,

We've already registered the similar issue #1888. Please, refer to [this guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods). The updated demo [here](https://codesandbox.io/s/brave-villani-8zgsc).

**Comment by Potseluiko** [comment]
> Please, refer to [this guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods). The updated demo [here](https://codesandbox.io/s/brave-villani-8zgsc).

Thanks, it helped

**Comment by MaximKudriavtsev** [comment]
@Potseluiko,

You are welcome!
