### ISSUE TITLE
Allow to customize pagination buttons

### ISSUE THREAD

**Issue by kg-currenxie** [DevExpress/devextreme-reactive#2044]
We'd like to customize the pagination buttons, to add the ability to right-click -> open in new tab, for example :)

Maybe to this button component?
https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/paging-panel/pagination.jsx#L62

Either via rest props, or replacing it via a template. 

Thanks :)

**Comment by churkin** [comment]
Hi @kg-currenxie,
Unfortunately we have no elegant way to customize pagination buttons yet. But we are going to implement this ability in the near feature. I suggest you try the workaround described in the #1335 issue.
Feel free to ask any additional questions.
