### ISSUE TITLE
Grid - Changing an array of columns that is associated with the DataTypeProvider.for property at runtime does not have any effect

### ISSUE THREAD

**Issue by jmarcelfpg** [DevExpress/devextreme-reactive#2047]
I tried in your forum https://www.devexpress.com/Support/Center/Question/Details/T744000/datatypeprovider-is-stuck-with-my-old-empty-array

but It has 1 day and I don't get any response yet

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

our app use it as a main component, and we are remotely and dynamically getting columns from the server, and many of your components are memoizing the data and showing me a weird bugs.

### Expected Behaviour

![image](https://user-images.githubusercontent.com/35382667/58346533-d63ebd80-7e20-11e9-87cb-8a5c4f03c439.png)

### Steps to Reproduce

I created a simple example for you to reproduce one of my issues following most of your examples

In this one the DataTypeProvider is stuck with the firs empty array, simulating an empty columns at first but after I we start getting columns from the server.

I reproduced this on storybook so my export default looks like an extra useless function component.

[JavaScript]
```
import React, { Component, Fragment } from "react";
import { withStyles } from "@material-ui/core/styles";
import Paper from "@material-ui/core/Paper";
import { DataTypeProvider } from "@devexpress/dx-react-grid";
import {
  Grid,
  Table,
  TableHeaderRow,
} from "@devexpress/dx-react-grid-material-ui";

import columns from "./columns";
import data from "./data";

const styles = theme => ({
  div: {
    overflowY: "auto",
    overflowX: "hidden",
  },
});

class DevExpressGrid extends Component {
  constructor(props) {
    super(props);

    this.state = {
      columns: ,
      rows: data.map((row, id) => Object.assign(row, { id })),
      formattedColumns: [],
    };
  }

  componentDidMount() {
    this.setState({ columns: [...columns],formattedColumns: ["city"] });
  }

  render() {
    const { rows, columns, formattedColumns } = this.state;
    const { classes } = this.props;

    return (
      <Fragment>
        <div className={classes.div}>
          <Grid rows={rows} columns={columns}>
            <DataTypeProvider
              for={formattedColumns}
              formatterComponent={() => "Hi"}
            />
            <Table />
            <TableHeaderRow />
          </Grid>
        </div>
      </Fragment>
    );
  }
}

const StyledDevExpressGrid = withStyles(styles)(DevExpressGrid);

export default () => <StyledDevExpressGrid />;
```

### Screenshots

![image](https://user-images.githubusercontent.com/35382667/58346595-02f2d500-7e21-11e9-9fce-d9650054ae18.png)

I fixed simulating a refresh call but I don't like it so if you can gave to me a better solution I appreciated

this solution is wrapping every in the next array
[JavaScript]
```
{columns.length && [
              <DataTypeProvider
                for={formattedColumns}
                formatterComponent={() => "Hi"}
              />,
              <Table />,
              <TableHeaderRow />,
            ]}

```
But in a major scale my main component is bigger and I don't like this solution

### Environment

```
"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-knobs": "^5.0.11",
"@storybook/addon-links": "^5.0.11",
"@storybook/react": "^5.0.11"
"@devexpress/dx-react-core": "^1.9.0",
"@devexpress/dx-react-grid": "^1.9.0",
"@devexpress/dx-react-grid-material-ui": "^1.9.0",
"@material-ui/core": "^3.2.2",
"@material-ui/icons": "^3.0.1",
"react": "^16.6.0",
```

**Comment by Krijovnick** [comment]
Hi @jmarcelfpg ,
 
You can re-create the `DataTypeProvider` component like in the [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-5zx5x). 
Another workaround is to call the `forceUpdate` method when the `for` property in the `DataTypeProvider` has updated.

**Comment by jmarcelfpg** [comment]
@Krijovnick, Great the exmaple works, thank you so much, and would you explain to me how can I call the forceUpdate?, maybe later could be useful, but we can close this ticket now thanks
