### ISSUE TITLE
onSortingChange of SortingState plugin returned value

### ISSUE THREAD

**Issue by tammynka** [DevExpress/devextreme-reactive#2048]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

We've enhanced the column object to contain additional props on top of the name and title. When using the `SortingState` plugin, we'd like to receive the full column object back from the `onSortingChange` callback function, which currently only returns the column name and the sorting direction. 
Is it at all possible?

### Environment

- devextreme-reactive: 1.10.0
- react: 16.7.0
- material-ui: 3.8.1

**Comment by ushkal** [comment]
Hi @tammynka ,
 
I recommend you find the full column objects in columns array using the [columnName](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/sorting-state/#sorting) property of the Sorting setting. See the following [project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-fotgr) for your reference.
