### ISSUE TITLE
Scheduler how to set WeekView height auto 

### ISSUE THREAD

**Issue by msmfsd** [DevExpress/devextreme-reactive#2050]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x ] React Scheduler

### Description
Is there any way I can set WeekView and DayView height to auto. Currently they are set to 700px and overflow-Y scroll.

Thanks

### Environment
- devextreme-reactive: latest
- react: 16+
- material-ui: latest

**Comment by MaximKudriavtsev** [comment]
Hi @msmfsd,

We have already implemented this feature in the following [PR](https://github.com/DevExpress/devextreme-reactive/pull/2043), but have not published yet. The next React Scheduler realize will be available after one-two weeks.

Now you can define the [layoutComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewlayoutprops) property of the `WeekView` plugin and manage your custom markup as you require. See our implementation of the [LayoutComponent](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/layouts/vertical-view-layout.jsx) for WeekView

**Comment by msmfsd** [comment]
Thanks @MaximKudriavtsev awesome!

**Comment by MaximKudriavtsev** [comment]
@msmfsd 

We have [released](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1111-2019-06-14) the 1.11.1 version of DevExtreme Reactive Scheduler with this feature.
