### ISSUE TITLE
Mui Typography Warning

### ISSUE THREAD

**Issue by mahmoud16h** [DevExpress/devextreme-reactive#2051]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Works perfectly fine. Just getting the below warning when using the package:
Warning: Material-UI: you are using the deprecated typography variants that will be removed in the next major release.
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2

### Expected Behaviour

No warning

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: One

**Comment by churkin** [comment]
Hi @mahmoud16h, 
Please let me know what MUI version you use.
