### ISSUE TITLE
dx-react-grid can not be transpiled due to TS1005 ts error in typings

### ISSUE THREAD

**Issue by qw4n7y** [DevExpress/devextreme-reactive#2056]
- [x] React Grid

### Current Behaviour

ERROR in /root/node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.d.ts
[tsl] ERROR in /root/node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.d.ts(292,42)
      TS1005: ',' expected.

### Environment

typescript: 3.1.6
@devexpress/dx-react-grid: 1.11.0

**Comment by ushkal** [comment]
Hi @qw4n7y ,

I couldn't reproduce the issue. Would you please modify this [project](https://codesandbox.io/s/objective-williams-9htyi) so that the error is reproduced?

**Comment by Methuselah96** [comment]
@ushkal The TypeScript errors only occur in older versions of TypeScript. The newest type declarations use TypeScript features that were added recently (I believe 3.4) and so are now incompatible with 3.1.6. I'm not sure how to reproduce that in CodeSandbox.

**Comment by ushkal** [comment]
Hi all,
 
We've fixed the issue in the context of this [PR](https://github.com/DevExpress/devextreme-reactive/pull/2069/files#diff-f7077e677e665a868416e0b191d47112R506). The latest version 1.11.1 contains the fix.
