### ISSUE TITLE
Material UI v4.

### ISSUE THREAD

**Issue by mammad2c** [DevExpress/devextreme-reactive#2061]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Current Behaviour

showing warning for Material UI v4
index.js:1375 Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`

### Screenshots

![image](https://user-images.githubusercontent.com/16647736/58730683-1514da80-8402-11e9-9c58-d8cc34139621.png)

### Environment

- devextreme-reactive: 1.11.0
- react: 16.8.6
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.0.1

**Comment by MaximKudriavtsev** [comment]
Hi @mammad2c,

This issue is a duplicate. We are closing it and suggest writing in the [initial topic](https://github.com/DevExpress/devextreme-reactive/issues/2013).
