### ISSUE TITLE
VirtualTable rows sometimes do not render on last page in lazy load mode

### ISSUE THREAD

**Issue by jmorrill** [DevExpress/devextreme-reactive#2062]
VirtualTable in Material UI rows sometimes do not render using "lazy loaded" method after you do a sort on a column.

I thought this may be an issue with my code, but I was able to reproduce[ in the online demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/).  I admit it takes a lot of scrolling and sorting to make it happen in the demo, but happens more often in my application.

![ezgif-2-360973b7fd07](https://user-images.githubusercontent.com/6867609/58765950-87360e00-852d-11e9-9d4d-7aff37f7b236.gif)

In the online demo, you can make it do it reliably, by using the scrollbar and dragging to the very bottom.  Then sort one of the columns.  Rows will not render until you scroll again.  I'm hoping this is all related to the same bug.

![image](https://user-images.githubusercontent.com/6867609/58765987-1ba07080-852e-11e9-80de-37f02854ecba.png)

**Comment by yedukondalurd** [comment]
I have the same issue.
