### ISSUE TITLE
Alternate row and fixed column

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#2071]
In this example I've created a grid with alternate row and fixed column.
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-e6zj3

Is possibile alternate background color row in fixed column?

**Comment by ushkal** [comment]
Hi @ccamusso ,
 
To implement this, you can set a background color to 'inherit' for a fixed cell component. Then set the white background color for a header row so that header titles do not overlap. Here's an updated [project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ole5j).

**Comment by ccamusso** [comment]
Thank you, work fine.
