### ISSUE TITLE
AppointmentTooltip isn't refreshed when the underlying data changes

### ISSUE THREAD

**Issue by VeegaP** [DevExpress/devextreme-reactive#2073]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
Once an appointment is selected, the AppointmentTooltip pops up. If the underlying data is changed by a third party, the contents of the tooltip aren't refreshed.

### Expected Behaviour
Update the AppointmentTooltip contents when the selected appointment data changes.

### Steps to Reproduce
1. Use a Scheduler component with AppointmentTooltip
2. Click on an appointment
3. Change that appointment state

If this is the intended behavior, what is the correct approach to work around it?

**Comment by MaximKudriavtsev** [comment]
Hi @VeegaP,

We do not consider this behavior, the [AppointmentTooltip](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/) shows static appointment data when you are clicking on an appointment. Implementation of this feature can lead to many unexpected errors, so we are not sure we will implement it in the near future.

BTW, you can manage the AppointmentTooltip state by passing the [appointmentMeta](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmentmeta) property into it and change it when you receive new data. Or turn off a tooltip's visibility when you receive new data by the `visible` property.

Could you describe your use case, what happens in your application, how many updates you have in it? This information will be very helpful to us.

**Comment by VeegaP** [comment]
Hi @MaximKudriavtsev ,
thanks for the feedback.

My application is a Scheduler shared between multiple clients, each client connects via websockets to the server and listens to the appointments data. Whenever this data changes, each client is notified and proceeds to update its state (the scheduler data).

In all fairness I'm relatively new to the React world, and wasn't sure if this was an intended behavior or not. As such, I'm not sure what the right approach to updating the appointmentMeta would be, but I'll look into it. 

Thanks!

**Comment by MaximKudriavtsev** [comment]
@VeegaP,

You can find information about updating the `appointmentMeta` property in the following [demo](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-demos/src/demo-sources/scheduler-tooltip/material-ui/controlled.jsx#L114).

**Comment by MaximKudriavtsev** [comment]
@VeegaP,

We have released the [1.11.1 version](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1111-2019-06-14) of the React Scheduler and a [guide about an appointment tooltip](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/). These demos can be useful to understand how to work with the AppointmentTooltip plugin.

**Comment by VeegaP** [comment]
@MaximKudriavtsev,
Thank you! I actually had been able to achieve what I wanted by binding the `appointmentMeta` property sto a property in my state, that kept track of the selected appointment id and build an appointmentMeta object by finding the matching appointment and keeping the target in the state as well.

It works, but if the appointment date changes, the tooltip stays on the same target as of now. I'll look into how to work around it.

**Comment by MaximKudriavtsev** [comment]
@VeegaP,

> the tooltip stays on the same target as of now

Currently, I don't have an idea of how to achieve it. I think it is related to the [Material-UI Popover](https://material-ui.com/api/popover/) component's behavior.

As a workaround, try displaying the AppointmentTooltip on the side of the Scheduler component at a fixed position.
