### ISSUE TITLE
How to get column index in a cell click event

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#2077]
During onCellClick event is possible get column index?

Carlo

**Comment by MaximKudriavtsev** [comment]
Hi @ccamusso,

According to the documentation, `cellComponent` [receives](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) a `column` object. If you know a column name, you can calculate the column index.

Please see the following [demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-722x7).
