### ISSUE TITLE
Pagination clickable ellipsis

### ISSUE THREAD

**Issue by muradianartem** [DevExpress/devextreme-reactive#2079]
Hi, I am using React-grid, I am looking for to make ellipsis in pagination clickable so user can open any page he wants. But I cannot understand how can I handle it?

**Comment by MaximKudriavtsev** [comment]
Hi @muradianartem,

On this point, you can override the [PagingPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-panel/) plugin's `containerComponent` property. As a base of your own custom component, you can use our [source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/paging-panel/pager.jsx).

You can find how to override components in the [Fundamentals](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#customize-the-appearance) guide.
