### ISSUE TITLE
 How to change the color of the checkbox using the material UI?

### ISSUE THREAD

**Issue by alinealvesvianna** [DevExpress/devextreme-reactive#2087]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

How can I change the color of the checkbox used in tableSelection?

![image](https://user-images.githubusercontent.com/7591901/59438541-19f66880-8dca-11e9-9d04-fdcc4dc99a80.png)

### Environment

- devextreme-reactive: 1.10.0
- react: next
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.0

**Comment by MaximKudriavtsev** [comment]
Hi @alinealvesvianna,

This issue is a duplicate. We are closing it and suggest writing in the [initial topic](https://github.com/DevExpress/devextreme-reactive/issues/933).
