### ISSUE TITLE
Resizing column width

### ISSUE THREAD

**Issue by DrainMorten** [DevExpress/devextreme-reactive#209]
Hi,
Is it possible to adjust the column width of the grid? One of the column values in my application are GUIDs, and at the moment, due to many columns, part of the guid/column field is hidden/clipped.

Kind regards,
Morten

**Comment by kvet** [comment]
Hi,
 
There is no official way to set column width. But it is possible to do it with an undocumented API. Check the following example: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-demos/src/bootstrap3/column-reordering/uncontrolled.jsx

**Comment by kvet** [comment]
To set a specific width of a column, specify the `width` property of the Column interface. Refer to the API Reference for more details: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-view/#column
 
The column resizing feature implemented in #297 will be released soon.
