### ISSUE TITLE
ReactGrid -Paging Panel - TypeError: Cannot read property 'registerPlugin' of null

### ISSUE THREAD

**Issue by dnbr2002** [DevExpress/devextreme-reactive#2093]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I tried to add a paging panel to my table.  Seems like a simple enough thing to do.  
All I get is
![image](https://user-images.githubusercontent.com/19315113/59541706-89ef1680-8ed0-11e9-8520-7366fc080b69.png)

I also see this in cmder
![image](https://user-images.githubusercontent.com/19315113/59541774-d0447580-8ed0-11e9-9593-0ab3b7d56247.png)

relevant code in my table. 
```
import {
    RowDetailState,
    PagingState,
    IntegratedPaging,
} from '@devexpress/dx-react-grid';
import {
    Grid,
    Table,
    TableHeaderRow,
    TableRowDetail,
    PagingPanel
} from '@devexpress/dx-react-grid-material-ui';
```

```
            <Paper>
                <Grid
                    rows={rows}
                    columns={columns}
                >
                    <PagingState
                        defaultCurrentPage={0}
                        pageSize={5}
                    />
                    <RowDetailState
                        expandedRowIds={expandedRowIds}
                        onExpandedRowIdsChange={this.changeExpandedDetails}
                    />

                    <IntegratedPaging />
                    <Table
                        cellComponent={Cell}
                    />
                    <TableHeaderRow />
                    <TableRowDetail
                        contentComponent={RowDetail}
                    />
                </Grid>
                <PagingPanel />
            </Paper>
```

### Environment
I'm using 
 ```
    "@devexpress/dx-react-core": "^1.11.1",
    "@devexpress/dx-react-grid": "^1.11.1",
    "@devexpress/dx-react-grid-material-ui": "^1.11.1",
```

- devextreme-reactive: 1.11.1
- react: 16.4.1
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.0.1

**Comment by ushkal** [comment]
Hi @dnbr2002,

You need to place the PagingPanel plugin inside the Grid:
```
  <TableRowDetail
    contentComponent={RowDetail}
   />
  <PagingPanel />
</Grid>
```

**Comment by dnbr2002** [comment]
Thank you!  That was it.
