### ISSUE TITLE
How to do group bulk editing?

### ISSUE THREAD

**Issue by dlucidone** [DevExpress/devextreme-reactive#2095]
I want to edit all the rows in a group based on select all checkbox in the group level so that it will trigger edit all in all the rows.
I'm able to to CRUD in single row but didn't found much documentation on bulk editing of rows in group level.

Thanks

**Comment by churkin** [comment]
Hi @dlucidone,
I think it is very specific and hard to implement scenario. Let me know if the 'batch editing' feature solves your requirements. For implementation progress, you can track #1841 issue .

**Comment by dlucidone** [comment]
Hi,

Yes batch edit will suit my scenario but my data is grouped in three nested level so the problem is the select all option is in top level of the column rather than the grouped level.

Thanks

**Comment by churkin** [comment]
Hi @dlucidone,
Can you please describe your scenario in greater detail? It will allow me to help you.

**Comment by dlucidone** [comment]
hi Churkin,

Thanks for the response.

Here is the scenario - 

Data = [{
        "state": "B ",
        "sity": 6,
        "area": 63,
        "age": 20.0,
        "height": 32.0
    },{
        "state": "B ",
        "city": 6,
        "area": 63,
        "age": 20.0,
        "height": 32.0
    },{
        "State": "B ",
        "City": 6,
        "area": 63,
        "age": 29.0,
        "height": 33.0,

    }]

for this data i want to 
1- first group by - State 
2- Second group by  - city
3- third group by  - city

Then in my grouped row Age and height, I want a multi row select checkbox in the nested group level rather than the select All checkbox in the parent row{State, City ..etc } of the table.

Let me know if this clears the air!

thanks anyway for the awesome library

**Comment by churkin** [comment]
@dlucidone,
Could you send me a simple example in the [CodeSandbox](https://codesandbox.io/), for example. I will try to reproduce your scenario on my side.
