### ISSUE TITLE
[React Scheduler] Change default time scale format to HH:00 instead of HH:30

### ISSUE THREAD

**Issue by AngelineLim** [DevExpress/devextreme-reactive#2098]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi there, is there a way to change the default time format displayed on the timescale where the HH:mm is HH:00 instead of HH:30 (as shown below)? 

![sample](https://user-images.githubusercontent.com/6859192/59706174-804c1280-9232-11e9-83b5-28bcbd8fdd6e.png)

I've tried: 
- updating the startDayHour to start at half past a certain hour, but it seems to only support integer value; 
- overriding the timescale provided, but that would mean I'll need to re-implement my own timescale and "plug" it in

Look forward to hearing back! Cheers!

**Comment by MaximKudriavtsev** [comment]
Hi @AngelineLim,

To change the time scale texts, you should override the `TimeScaleLayout` component with the `TimeScaleCell` component. Please see the following [example](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-b9gq7).

BTW, you can set the `cellDuration` property of the [WeekView](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/) plugin to 60, see the next [demo](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-05izh).
