### ISSUE TITLE
Date Range filter

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2100]
Is it possible to filter the grid using a date range? Example showing only rows from 2019-02-24 to 2019-02-26. Only demos I found were 'Contains, starts with or ends with'

**Comment by DmitryBogomolov** [comment]
Hello @paufar.

You can specify a custom filter predicate using the columnExtensions property of the [IntegratedFiltering](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/) plugin.
Here is a [sample](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-4f662).
 
Take a look at the following [page](https://github.com/DevExpress/devextreme-reactive/issues/1399). A more complex variant of the "between" filter is shown there.
