### ISSUE TITLE
Could not find a declaration file for module '@devexpress/dx-core'

### ISSUE THREAD

**Issue by Evelyn-McDonald** [DevExpress/devextreme-reactive#2101]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

This issue seems to crop up again when upgrading from 1.11.0 -> 1.11.1

```/[my_app]/node_modules/@devexpress/dx-react-core/dist/dx-react-core.d.ts
ERROR in /[my_app]/node_modules/@devexpress/dx-react-core/dist/dx-react-core.d.ts(6,25):
TS7016: Could not find a declaration file for module '@devexpress/dx-core'. '/[my_app]/node_modules/@devexpress/dx-core/dist/dx-core.umd.js' implicitly has an 'any' type.
  Try `npm install @types/devexpress__dx-core` if it exists or add a new declaration (.d.ts) file containing `declare module '@devexpress/dx-core';
```

### Expected Behaviour

The application should compile and run.

### Steps to Reproduce

- Using a TypeScript application, upgrade to React Grid v1.10.3
- Build & run it

### Environment

- devextreme-reactive: 1.11.1
- react: 16.8.0
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: core 4.1.1

**Comment by Krijovnick** [comment]
Hello @Evelyn-McDonald 

I couldn't reproduce the problem. Could you change the [example](https://codesandbox.io/s/silly-https-see2m) to reproduce the error?

**Comment by Evelyn-McDonald** [comment]
Seems to be an issue related to `react-scripts-ts` in combination with v1.11.1. I'll close the issue until I'm able to pinpoint it.
