### ISSUE TITLE
ZoomAndPan is not defined in the typescript definition file.

### ISSUE THREAD

**Issue by towry** [DevExpress/devextreme-reactive#2107]
`@devexpress/dx-react-chart-material-ui: v1.11.1`

In my TS file, if I do the import:

```ts
import { ZoomAndPan } from '@devexpress/dx-react-chart-material-ui';
```
It will give me an error: `has no exported member 'ZoomAndPan'`

I have to use `require` to get the plugin to work:

```js
const ZoomAndPan = require('@devexpress/dx-react-chart-material-ui').ZoomAndPan;
```

**Comment by towry** [comment]
Changed to react-vis.

**Comment by DmitryBogomolov** [comment]
In [this sample](https://codesandbox.io/s/react-typescript-ssj6e) Chart works but there is an import warning with the same text.
