### ISSUE TITLE
How to get full control styling for data table from DevExtreme React Grid with material-ui? Ask Question

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#2108]
Hi , I have trouble with styling DevExtreme React Grid, follow by there found from there documentation [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/) and search the GitHub issue and StackOverflow already, still not find the solution.

Here's the [sample code](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-b56kj?fontsize=14) I have from copy some other repo. My questions:

1. 

How can I get full control on the styling, because I see `<Table>`component, but is there a way I can adding class to `table td and th` element, I would like to add the class or someway to have full control styling for font size or hover styling.

2.

I had a really hard time my table header, like to change to bold and another background color, it's by material UI

3.
After I add the [Fixed Columns method](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fixed-columns/) on scrolling my table, the style is not matching with my other table row, it's changed to all white background, no grey and white on each row.

4.
When I hit the rest, I would like to row change to be another color.

Thank you so much for your help!

**Comment by MaximKudriavtsev** [comment]
Hi @madebymt,

To access default components, override `xxxComponent` properties of UI plugins. You can see how to do this in the [following guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/).

Regarding applying styles to fixed columns. You should pass a special class name to a row component as [follows](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-p5xce).
