### ISSUE TITLE
Paging and sorting function with React

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#2110]
HI 
I saw someone else ask the same question, but the[ answer demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/) is typescript, so I'm curious to have any other react approach.
I did see the doc about paging section mention:

When you use paging features with sorting, grouping, or filtering, take note of the order in which the plugins appear in the Grid’s container. You need to choose whether to paginate filtered rows or filter the current page. In the former case, put the IntegratedFiltering plugin before the IntegratedPaging one. Otherwise, inverse the plugins’ order.```

So I try that in this order, still not working, the [sample code here:](PagingPanel function is not working)(https://codesandbox.io/s/devextreme-react-grid-for-material-ui-n3fx6?fontsize=14)
```
 <Paper>
        <Grid rows={rows} columns={columns}>
          <SortingState
            defaultSorting={[{ columnName: "city", direction: "asc" }]}
          />
          <IntegratedSorting />
          <PagingState defaultCurrentPage={0} pageSize={5} />
          <IntegratedPaging />
          <Table tableComponent={TableComponent} />
          <TableHeaderRow showSortingControls />
          <PagingPanel pageSizes={pageSizes} />
          <TableFixedColumns leftColumns={leftColumns} />
        </Grid>
      </Paper>
```

Thank you so much!

**Comment by MaximKudriavtsev** [comment]
Hi @madebymt,

We are using [data piping principles](https://en.wikipedia.org/wiki/Pipeline_(computing)); see the [following guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/).

Thus, you should define `xxxState` plugins, then these `IntegratedXXX` plugins, and, finally, UI plugins. To change resulting data, reorder only `IntegratedXXX` plugins. See the [updated demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-94z6j).

**Comment by madebymt** [comment]
Hi @MaximKudriavtsev 
From the updated demo, the `Rows per page:` to choose how many to show per page is still not function, when I change default paging to show 2, then change number to 5 per page is not updated. Also, how do I sort by row, not by data per page row, I check the doc [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/sorting-state/) still not quite sure which one I can use. Thank you so much for your help.

**Comment by madebymt** [comment]
Hi, @MaximKudriavtsev 
I'm still having an issue with the sorting with pagination, after adjust what you suggest, still have issue for`Uncontrolled Mode` 
The filter is working, but I tried to click the table row to do default sorting is not working.

Here's the order of the state, integrate, and UI like you suggest:
```
  <SortingState
              defaultSorting={[{ columnName: "city", direction: "asc" }]}
            />
            <FilteringState defaultFilters={[]} />
            <PagingState defaultCurrentPage={0} defaultPageSize={15} />

            <IntegratedSorting />
            <IntegratedFiltering />
            <IntegratedPaging />

            <Table
              cellComponent={this.tableCellStyle}
              rowComponent={TableRowStyle}
              columnExtensions={tableColumnExtensions}
            />
            <TableHeaderRow
              showSortingControl
              contentComponent={TableHeaderContentStyle}
            />
            <TableFilterRow />

            <TableFixedColumns
              leftColumns={leftColumns}
              showLeftDivider={false}
              showRightDivider={false}
              cellComponent={TableStickyCellStyle}
            />
            <PagingPanel containerComponent={PagingContainer} />
          </Grid>
```
Thank you.

**Comment by MaximKudriavtsev** [comment]
@madebymt,

>From the updated demo, the Rows per page: to choose how many to show per page is still not function, when I change default paging to show 2, then change number to 5 per page is not updated. 

This happens because you pass a constant value to the `pageSize` property. This is a [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).


> I'm still having an issue with the sorting with pagination, after adjust what you suggest, still have issue forUncontrolled Mode
The filter is working, but I tried to click the table row to do default sorting is not working.

This issue can be caused by the fact that you created a lot of custom components.

I would also like to note that it's difficult to understand what the issue is without detailed information. Would you create a sample in the [sandbox](https://codesandbox.io/s/13qvz1qqzl) and describe the issue in as many detail as possible?

**Comment by madebymt** [comment]
Thank you @MaximKudriavtsev 
I fixed it, thanks for the links!
---
Here's the code if would help other people
```
//after state area:
changePageSize = pageSize => this.setState({ pageSize });
// Plugin
<PagingState
              defaultCurrentPage={0}
              pageSizes={pageSizes}
              defaultPageSize={15}
              onPageSizeChange={this.changePageSize}
            />
<IntegratedPaging />
//UI 
<PagingPanel pageSizes={pageSizes} />
```

**Comment by MaximKudriavtsev** [comment]
@madebymt,

You are welcome!
