### ISSUE TITLE
How to create validation of table while adding new column

### ISSUE THREAD

**Issue by bhargav2496** [DevExpress/devextreme-reactive#2111]
Hi 
I need ti validate the each column data while inserting the new row and also validate the each field while editing the column and I tried this [demo](https://stackblitz.com/edit/react-1ctqvq?file=index.js) but it doesn't validate while adding or editing the fields

Is there any other way to validate the fields

**Comment by ushkal** [comment]
Hi @bhargav2496,

Please refer to the similar [question](https://github.com/DevExpress/devextreme-reactive/issues/475).
