### ISSUE TITLE
Data not loading when sorting in already cached data chunk

### ISSUE THREAD

**Issue by michaelfaisst** [DevExpress/devextreme-reactive#2114]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When changing the sorting of a lazy-loaded virtual table, while beeing in an area of the grid which has been chached, the `getRows` method will not be called.

### Expected Behaviour

`getRows` should be called to fetch the data with the new sorting.

### Steps to Reproduce

You can reproduce this step in your "Row caching" example [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/).

1. Open your browsers dev tools and switch to network request
2. Scroll down the table (after around row 105 will be visible) until the second data request will be sent (should be skip=200, take=100)
3. Now scroll up to the top of grid again
4. Sort any column

After following these steps data will not be loaded and the "gray box" loading state will be displayed permanently. I'm guessing that it has something to do with `skip` beeing to high for the currently displayed range of data.

![image](https://user-images.githubusercontent.com/1477993/60102772-a3a91d00-975e-11e9-8d2a-32814f84f760.png)

### Environment

- devextreme-reactive: 1.11.1
- react: 16.8.2

**Comment by LazyLahtak** [comment]
Hi @michaelfaisst,
 
We have fixed this bug. The fix will be available in the next update.
