### ISSUE TITLE
Filtering in cached virtual table displays wrong data

### ISSUE THREAD

**Issue by michaelfaisst** [DevExpress/devextreme-reactive#2115]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When doing remote filtering and e.g. no data is returned from the api, there are still rows displayed in the grid.

### Expected Behaviour

Display correct rows after filtering.

### Steps to Reproduce

Can be reproduced in the "Row caching" example [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/). Just filter e.g. Category with "asdf". The api call returns `{"data": [],"totalCount": 0}`, but data is still displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/1477993/60164749-6a27ee80-97fe-11e9-9181-52820f800fcc.png)

### Environment

- devextreme-reactive: 1.11.1
- react: 16.8.2

**Comment by ushkal** [comment]
Hi @michaelfaisst ,

Thank you for reporting the issue. I've reproduced this problem and we'll fix it soon. In the meantime, I suggest you [debounce](https://medium.com/@jamischarles/what-is-debouncing-2505c0648ff1) requests using the lodash.debounce function as shown in this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-uv7et).

**Comment by LazyLahtak** [comment]
Hi @michaelfaisst,
 
The fetch function loads data async. On every filter change, you recall the function and some async calls conflict with each other. To prevent this, you should call a new fetch only after the previous one ends data loading.
Refer to this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-sh4ys) illustrating how to do that.
