### ISSUE TITLE
Change Filter grid view to table header with dropdown?

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#2119]
### I'm using ...#####
- React Grid
- devextreme-reactive: 1.11.1

### Description ######
(I search the issue make haven't seen same questions)
I'm just want to check is it possible to make filter function next to table header row with an icon when it clicks the icon have a dropdown with the filter selection.
Like image below:
<img width="888" alt="Screen Shot 2019-06-26 at 12 12 32 PM" src="https://user-images.githubusercontent.com/26178313/60200762-5c796580-980c-11e9-92ca-87a8a1ef8ff6.png">
[Demo code here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-d9th2)

Thanks!

**Comment by ushkal** [comment]
Hi,
It's possible by implementing custom plugins. Here's a [demo project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-dqor9) showing implementation details.

**Comment by madebymt** [comment]
@ushkal Thank you for the demo, I see the filter dropdown, is possible do the dropdown next to the table header with an arrow icon. dropdown display when you click it. Not sure we have the ability to move that whole row up. Thanks!

**Comment by ushkal** [comment]
@madebymt Here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-4j8l2).

**Comment by madebymt** [comment]
@ushkal  Thank you so much for the cool demo, I'll follow your guide to work on it. Thanks!

**Comment by ushkal** [comment]
You are welcome!

**Comment by madebymt** [comment]
@ushkal 
Is possible adding search option in the filter dropdown? 
Like Demo can type in a value to filter:https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/

Thank you!

**Comment by ushkal** [comment]
Hi @madebymt ,

Here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-wgl7g) if it's still actual. I apologize for the delayed response.
