### ISSUE TITLE
columns resizing working weirdly

### ISSUE THREAD

**Issue by ichirukia1566** [DevExpress/devextreme-reactive#2120]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Hi, I am currently working on a standard dashboard-like project. I have already added some standard functionalities and would like to add column resizing as well. However, it is working weirdly now.

![GIF](https://user-images.githubusercontent.com/5390408/60227429-dddeff80-98c1-11e9-8b52-efd4c5eeaa60.gif)

As you can see from the gif, width of the table when page is loaded is a very large value, and the min-width value is also extremely large. After I drag the handle to resize, the first column extends crazily, its width becomes about 1000x larger, and the min-width value also changes.

### Expected Behaviour

It should work as in the example in your documents.

### Steps to Reproduce

My table code is as following.
```
<Grid rows={rows} columns={columns}>
  <FilteringState defaultFilters={[{ columnName: 'tid', value: '' }]} />
  <SortingState
    defaultSorting={[{ columnName: 'tid', direction: 'asc' }]}
  />
  <SearchState />
  <IntegratedFiltering columnExtensions={filteringColumnExtensions} />
  <IntegratedSorting />

  <DataTypeProvider
    for={['tdate']}
    availableFilterOperations={dateFilterOperations}
  />
  <DataTypeProvider
     for={['vdate']}
     availableFilterOperations={numericFilterOperations}
   />
  <RowDetailState />
  <Table columnExtensions={tableColumnExtensions} />
  <TableColumnResizing defaultColumnWidths={defaultColumnWidths}/>
  <TableHeaderRow showSortingControls={true} />
  <TableRowDetail contentComponent={RowDetail} />
  <TableFilterRow
    showFilterSelector
    iconComponent={FilterIcon}
    messages={{ month: 'Month equals' }}
  />
  <Toolbar />
  <SearchPanel />
</Grid>
```

### Screenshots

Please refer to the gif above.

### Environment

- devextreme-reactive: 1.11.1
- react: 16.8.6
- browser: Firefox 67.0.4
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.1.1

Thank you in advance

**Comment by LazyLahtak** [comment]
Hi @ichirukia1566 ,,
 
We have same [issue](https://github.com/DevExpress/devextreme-reactive/issues/1529) about this problem. We will appreciate it if you share more details with us or send a runnable project. It will help us fix the issue quickly.

**Comment by ichirukia1566** [comment]
Thank you for the response, I will try to do that during the weekends.

**Comment by ichirukia1566** [comment]
Sorry for the late reply. You could see it here.
[CodeSandbox](https://codesandbox.io/embed/vigilant-architecture-trg4c)
Thanks!

**Comment by LazyLahtak** [comment]
@ichirukia1566 
 
Thank you for example!
We researched you code and found the cause of this problem. See the solution in [this](https://github.com/DevExpress/devextreme-reactive/issues/1529#issuecomment-507156481) ticket.

**Comment by ichirukia1566** [comment]
I guess I need to read the API more carefully. Thank you so much and have a nice day!

**Comment by LazyLahtak** [comment]
@ichirukia1566, You're welcome!
