### ISSUE TITLE
Is there a way to setCellValues in unbound columns?  ReactGrid vs DataGrid

### ISSUE THREAD

**Issue by dnbr2002** [DevExpress/devextreme-reactive#2125]
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I'm sort of wondering which solution I am supposed to be using at this point.  I had started with React Grid.  It has been great but the last thing I need is a unbound column where I simply rank/count the rows in this unbound column starting with first row getting the #1, second row #2 and so on.  It will be the ranking of the sort I put on the table. I want to display this quite simply.  I see here in the Javascript docs for DataGrid you can do this
https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#calculateCellValue

But I can't find this for the React Grid.  And now I'm kind of confused why I even started with React Grid, It almost looks like you can do more with DataGrid than the React Grid.  So which should I be using. Did I miss how to set a cell value in a unbound column in React Grid Docs?  If not will this be added to the React Grid or should I just change my whole table over to DataGrid? Not sure about the decision tree on React Grid vs DataGrid but if React Grid is something your sticking with seems like setting cell values would be an important feature.  Hoping I just missed it.  Tables have been great!  Thanks

**Comment by dnbr2002** [comment]
Basically I want to do use ID as seen here.  
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode

Bit I get 
The row id is undefined. Check the getRowId function. 

When using

```
const getRowId = row => row.id
```
Which make sense because my row does not basic, 0, 1, 2 ID value.  It has a key value which doesn't help here.  

If the table was returning the index from the mapped row I could easily get it but it doesn't seem to be there.  Also in the example you create your rows differently with the generateRows function.   

```
      rows: generateRows({
        columnValues: { id: ({ index }) => index, ...defaultNestedColumnValues },
        length: 8,
      }),
```

My data is coming from a prop in React, Not a function pulling in local data.  The Array of objects is set.  Don't think I can tap on a the id like you are doing here in the table component....

**Comment by MaximKudriavtsev** [comment]
Hi @dnbr2002,

The Reactive Grid has the [getCellValue](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/#column) property to calculate a custom column value; see the [following sample](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-bf4jl).

As for the `getRowId` function, you should define a unique id field for data of each row.

Also, you can find differences between [DevExtreme Reactive Grid](https://devexpress.github.io/devextreme-reactive/react/grid/) and [DevExtrrreme DataGrid](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/jQuery/Light/) in the following [blog post](https://community.devexpress.com/blogs/oliver/archive/2018/04/20/devextreme-new-react-wrappers-vs-native-react-components.aspx).

**Comment by dnbr2002** [comment]
That is a great getCellValue example!  I needed that.  Regarding unique Id field, I have one, it's just not what I would use as a ranking number in the column.  I think I have found a way to set it before the remote data gets to the table now, this will also make my ranks more global if I want to use it anywhere else.  Blog post is just what I was looking for the difference.  Thanks for the links! Great help.

**Comment by MaximKudriavtsev** [comment]
You are welcome!
