### ISSUE TITLE
Add the ability to filter by formatted values

### ISSUE THREAD

**Issue by zhdanouskikh** [DevExpress/devextreme-reactive#2129]
When I'm trying to search rows, IntegratedFiltering is searching within unformatted values. Is it possible to search in a range of formatted values?

**Comment by churkin** [comment]
Hi @zhdanouskikh,
I need more time to investigate this issue and discuss the current behavior with the team. You did not describe your scenario but I expect that you can use this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-m7eo4) as a workaround. Let me know if it solves the problem.

**Comment by zhdanouskikh** [comment]
@churkin I am using SearchPanel for filtering, not TableFilterRow
Maybe there's problem with SearchPanel component?

**Comment by zhdanouskikh** [comment]
@churkin if I understood you correctly - in the EditorBase component you're normalizing value to the unformatted, right? And that's why it works. But it's a workaround.

**Comment by churkin** [comment]
Hi @zhdanouskikh,
Yes you could use this trick for the SearchPanel as well. Unfortunately we cannot suggest you anything instead of this workaround at the moment. Let me know if you face any problems when applying this solution to the SearchPanel.

**Comment by zhdanouskikh** [comment]
@churkin thank you! I will try it.

**Comment by zhdanouskikh** [comment]
@churkin for me trick with editor base is not working for some reason. I don't have TableFilterRow and FilteringState. I have SearchState SearchPanel, but editorComponent for custom formatter is working only for TableFilterRow and Filtering state for me.

Could you please prepare an example with working variant for SearchState and SearchPanel?

**Comment by ushkal** [comment]
Hi,
 
I suggest you use the [IntegratedFiltering.columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#integratedfilteringcolumnextension) property to implement your task. There, you can specify a custom predicate that tests a cell value against a search value. In this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-2ce5w), the 'percent' and 'phone' columns' values are stored as plain numbers, but can be searched using a formatted string, e. g. '(0123) 123-456' or '10%'.

**Comment by zhdanouskikh** [comment]
@ushkal nice suggestion! thank you!

**Comment by ushkal** [comment]
You are welcome!

**Comment by zhdanouskikh** [comment]
@ushkal that worked for me, thank's.
Maybe you should add this thing to documentation, because it's not very obvious)

**Comment by ushkal** [comment]
Thank you for this suggestion. We'll add it in our guides.
