### ISSUE TITLE
Add a documentation topic describing a right order of plugins

### ISSUE THREAD

**Issue by crayolaeater12** [DevExpress/devextreme-reactive#2132]
[x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Can we have a ranking/ordering list or overview list/example on how the plugins are supposed to be integrated with regards to the data piping principle? While it has been very helpful that the docs provide a warning if plugin order matters for a particular Grid feature, It has been somewhat tedious to click on every related plugins' references found in the feature's docs.

### Environment
react: "^16.8.6",
@devexpress/dx-react-core: "^1.11.1",
@devexpress/dx-react-grid: "^1.11.1",
@devexpress/dx-react-grid-material-ui: "^1.11.1",

**Comment by churkin** [comment]
Hi @crayolaeater12, 
I think it will be great to add a documentation topic describing a right order of plugins.
Thank you for your cooperation.
