### ISSUE TITLE
MaterialUI Scheduler missing right border since upgrade to 1.11.1

### ISSUE THREAD

**Issue by msmfsd** [DevExpress/devextreme-reactive#2133]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Scheduler

### Current Behaviour
Since upgrading from `1.10.1` to `1.11.1` Scheduler MonthView missing right border on table cells, see attached screenshot. 

### Expected Behaviour
Table cells located on right of calendar should have a border-right of 1px grey.

### Steps to Reproduce
- Upgrade to `v1.11.1`

### Screenshots
![Screen Shot 2019-07-02 at 2 11 11 pm](https://user-images.githubusercontent.com/17868999/60482314-4cfa9080-9cd4-11e9-96be-487f0f03ce97.png)

### Environment
- dx-react-core: 1.11.1
- dx-react-scheduler: 1.11.1
- dx-react-scheduler-material-ui: 1.11.1
- material-ui: 3.9.3
- react: 16.8.6
- browser: Chrome latest

**Comment by AryamnovEugeniy** [comment]
Hi, msmfsd
Thank you for your feedback. I've reproduced this behavior. We will try to fix it as soon as possible.

**Comment by AryamnovEugeniy** [comment]
Hello again @msmfsd,
 
We fixed the inconsistency with borders around Scheduler. Starting with this release, there are no borders around Scheduler. You can follow [this](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-nsfd4) example to set borders around Scheduler. To achieve this, create CustomLayout and pass a border style to it as shown in the example.
