### ISSUE TITLE
Rendering noDataCellComponent when VirtualTableState is loading

### ISSUE THREAD

**Issue by Gobbenobber** [DevExpress/devextreme-reactive#2135]
Hello,

I have been able to successfully render the NoDataCellComponent whenever using just the VirtualTable component; however, as soon as I include the usage of the VirtualTableState component, the noDataCellComponent property seems to be ignored.
In other words, I am simply shown the skeleton rows instead of the component which I pass as the noDataCellComponent attribute of the VirtualTable element.

Am I missing something? Is there a way to actually provide a NoDataCellComponent when using VirtualTableState?

See example below...

```
...
<VirtualTableState
            loading={loading}
            totalRowCount={this.props.machineCount || 0}
            pageSize={VIRTUAL_PAGE_SIZE > this.props.machineCount! ? this.props.machineCount! : VIRTUAL_PAGE_SIZE}
            skip={skip}
            getRows={this.getRemoteRows}
            infiniteScrolling={false}
/>
<VirtualTable
          tableComponent={TableComponent}
          headComponent={HeaderComponent}
          height='auto'
          noDataCellComponent={this.NoDataCellComponent}
/>
...
  private NoDataCellComponent = (restProps: Table.NoDataCellProps): JSX.Element => (
    <NoData noDataCellProps={restProps} isFetchingData={this.state.loading} />
  )
...

```

Where NoData is a class defined as:

```
interface AppProps {
    isFetchingData: boolean;
    noDataCellProps: Table.NoDataCellProps;
}

type Props = AppProps;

export class NoData extends React.PureComponent<Props> {
    public render() {
        const content = this.props.isFetchingData
            ? (
                <td colSpan={this.props.noDataCellProps.colSpan} className="py-5">
                    <div className="center-across-columns padding-vertical-10px">
                        <Spinner shouldOverlay={false} shouldUseAbsolutePositioning={true} />
                    </div>
                </td>
            )
            : (
                <VirtualTable.NoDataCell {...this.props.noDataCellProps} getMessage={getNoDataMessage} />
            )

        return (
            content
        )
    }

```

As soon as I remove the usage of VirtualTableState, I am able to use the custom NoDataCellComponent.

**Comment by Krijovnick** [comment]
Hi,
 
The `noDataCellComponent` property renders a table cell when there is no data in the virtual table.
The `VirtualTableState` component manages remote data and shows the skeleton rows until data is received or when you are scrolling the table and data is loaded. Thus if remote data is not returned for a long time, you can return `totalCount` as 0 and `loading` as false and `noDataCellComponent` is rendered.
