### ISSUE TITLE
Infinite scrolling sometimes won't render rows

### ISSUE THREAD

**Issue by chr22** [DevExpress/devextreme-reactive#2139]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Sometimes when scrolling fast with Infinite Scrolling enabled the table won't render rows, as shown in the two images below taken from your own documentation.

![image](https://user-images.githubusercontent.com/3649594/60648743-d8913000-9e40-11e9-9698-6f8e92217394.png)

![image](https://user-images.githubusercontent.com/3649594/60648720-c8795080-9e40-11e9-9dd3-02d4d5b2322f.png)

There are some other issues with this problem but they have both been closed.
https://github.com/DevExpress/devextreme-reactive/issues/1253
https://github.com/DevExpress/devextreme-reactive/issues/2062

**Comment by Krijovnick** [comment]
Hi @chr22 

Thank you for reporting the issue. We know about this problem and we'll fix it soon.

**Comment by LazyLahtak** [comment]
This bug awaits when this [issue](https://github.com/DevExpress/devextreme-reactive/issues/1389) is fixed.
