### ISSUE TITLE
TableTreeColumn Icon

### ISSUE THREAD

**Issue by ronaiza-cardoso** [DevExpress/devextreme-reactive#2142]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
### Description
I want to be abble to change the icon of `CustomTreeData` to folder instead chevron. This is my example code: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-89r89

**Comment by ushkal** [comment]
Hi @ronaiza-cardoso ,

I suggest you override the `expandButtonComponent` of the [TableTreeColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-tree-column/#properties) plugin. See the following [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-qedxo).

**Comment by ronaiza-cardoso** [comment]
Thank you!

**Comment by ushkal** [comment]
You are welcome!
