### ISSUE TITLE
How to customize toolbar plugin

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#2147]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Using Grouping and ColumnChoose plugin but how would I separate the columnchooser and grouping panel into two rows by using plugins.

![toolbar (2)](https://user-images.githubusercontent.com/42453813/60741690-46138e00-9f1f-11e9-928e-7760da3328e8.png)

`<Toolbar rootComponent={}>
<TotalRowCount/>
<ColumnChooser/>
<GroupingPanel />`

I have created a [sample](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-uljpo). 

### Environment

- devextreme-reactive: xxx
- react: 16
- bootstrap
- react-bootstrap

**Comment by Krijovnick** [comment]
Hi,

You can create and place you custom `ColumnChooser` plugin outside of the React Grid. For more information, see [#1767](https://github.com/DevExpress/devextreme-reactive/issues/1767) issue.

**Comment by susuwatari2** [comment]
Hi @Krijovnick, 
What can I do with GroupingPanel?

**Comment by Krijovnick** [comment]
Could you provide more information what you want to do with `GroupingPanel`, `DragDropProvider` and your custom plugins?
According to your previous information about the problem and provided screenshot, I created an [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-bjciq).

**Comment by susuwatari2** [comment]
Thank you, @Krijovnick. 
If I want to keep the Column chooser plugin as default, do I have to recreate the whole hide and show table columns components?

**Comment by Krijovnick** [comment]
@susuwatari2 yes, you can reuse the ColumnChooser plugin [components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#plugin-components) to implement that. I modified the [sample](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-70kh3) to show that.

**Comment by susuwatari2** [comment]
@Krijovnick, I want to customize the toggle button, does it sound right?
`const columnChooserButton = (onToggleButton, buttonRef) => (
  <ColumnChooser.ToggleButton>
<Button
onClick={onToggleButton}
    ref={buttonRef}
>Column Chooser
</Button>
  </ColumnChooser.ToggleButton>
);`

**Comment by Krijovnick** [comment]
@susuwatari2 If you want to use your custom `Button` in the `ColumnChooser` plugin you shouldn't wrap it in the ` ColumnChooser.ToggleButton`:
`const columnChooserButton = (onToggleButton, buttonRef) => (
<Button onClick={onToggleButton} ref={buttonRef}>Column Chooser</Button> 
);`

**Comment by susuwatari2** [comment]
Thank you, @Krijovnick. It works. 
I am trying to modify your columnChooserOverlay and columnChooserItems but it is overwhelming. 
This [sample]( https://codesandbox.io/s/4qzqrmnv69) is what I had. I have followed what you did and created [a new demo](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-x3kp4) here.

**Comment by Krijovnick** [comment]
@susuwatari2 Could you clarify what is not working in your example?

**Comment by susuwatari2** [comment]
@Krijovnick Did you see what I had in my sample? I can do filtering on the column chooser before.

**Comment by Krijovnick** [comment]
@susuwatari2 As I can see in your example, you add your `FormControl` component to the `ColumnChooser` plugin. 
As this is the code that you are using to extend the functionality of our components, we cannot guarantee that this code will work well with our components. As an exception, I modified your [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-czh5d) so that your filtering works.
