### ISSUE TITLE
Scheduler support Jalali ( Persian ) calendar

### ISSUE THREAD

**Issue by alirezamirsepassi** [DevExpress/devextreme-reactive#2150]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Please support Jalali ( Persian ) calendar. Keep in mind that the calendar must be RTL in jalali view.

**Comment by MaximKudriavtsev** [comment]
Hi @alirezamirsepassi,

I have created a [demo](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-b3h8i) based on our [Localization Guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/localization/). Please refer to it and let me know if it is OK. Should we add this demo to our documentation?

We have plans to implement RTL but I cannot give you any estimate at the moment.

**Comment by alirezamirsepassi** [comment]
That's great, but the start day of the week is Saturday on Persian calendars.
Also, I'm not sure whether the dates are ok. Can you please make one that could show today's date and can be changed?
Thanks

**Comment by MaximKudriavtsev** [comment]
@alirezamirsepassi,

I have updated the d[emo](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-ld6e3). Could you please review it and add notes? Is the current calendar more convenient for you?

**Comment by alirezamirsepassi** [comment]
Yes, thank you so much for taking the time.

**Comment by MaximKudriavtsev** [comment]
@alirezamirsepassi 

You are welcome!
