### ISSUE TITLE
Change GroupingPanel style

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#2155]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ v] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

How can I change the style in GroupingPanel plugin? And the DragAndDrop row?

### Expected Behaviour

I want to change the button size and color? Can I use css for that? And what is the classname for that?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap
- react-bootstrap

**Comment by LazyLahtak** [comment]
Hi @susuwatari2,
 
You can use a custom component to change the style for the GroupPanel and DragDropProvider items. In this case, it should be [itemComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grouping-panel/#groupingpanelitemprops) for GroupPanel and [columnComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/drag-drop-provider/#dragdropprovidercolumnprops) for DragDropProvider. If you want to use the CSS file, define the className property for components. 
Here is [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-csfkz).
