### ISSUE TITLE
Is it possible to use React ref on Grid (ref.current is null, is Grid a functional component)?

### ISSUE THREAD

**Issue by alex153410** [DevExpress/devextreme-reactive#2158]
### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

I am trying to update the Grid Appearance based on some class variable, i.e. continue https://github.com/DevExpress/devextreme-reactive/issues/2011 Such update of appearance happens automatically when I update the values of the props (which are assigned to the grid.rows attribute). But if <Table.Row style={{...}}> redefinition contain some state variable of encompassing component and this state variable gets updated, then Grid appearance is not updated. It is normally. My idea was to use forceUpdates() on the <Grid> component (as suggested in the #2011) and that is why I am following https://reactjs.org/docs/refs-and-the-dom.html and create code that uses refs: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-1d2hn

The problem is, that ref.current is and remains null (e.g. see the handleCommandClick. This fact suggests that Grid may be functional component (not class). I**s Grid really a functional component and - if so - how to create wrapper that wraps Grid function as React component** and then I can use ref on this component and perform forceUpdates()?

**Comment by LazyLahtak** [comment]
Hi @alex153410 ,
 
The Grid is PureComponent that updates when it gets new properties or changes the state. Also, we removed the ref property from the Grid and don't process it. You can apply appState as a key property for the Grid to update it.
Here is [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-0zq0g).
