### ISSUE TITLE
DayScale panel flickers/partially disappears in Edge when scrolling Scheduler

### ISSUE THREAD

**Issue by AryamnovEugeniy** [DevExpress/devextreme-reactive#2161]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
Scheduler's DayScale panel flickers/partially disappears in Edge when scrolling as shown in the gif below.
The bug is known to Microsoft. They promise to release a fix soon.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15018231/

### Expected Behaviour
DayScale panel should neither flicker nor disappear.

### Steps to Reproduce
Scroll Scheduler in Edge

### Screenshots

![DayScale panel in Edge](https://user-images.githubusercontent.com/51905811/61051263-4e713a80-a3f1-11e9-9d8a-e94d51763a95.gif)

### Environment

- devextreme-reactive: 2.0.0
- browser: Microsoft Edge
- material-ui: 4.1.3

**Comment by churkin** [comment]
Can I close this?
