### ISSUE TITLE
Link cell with tree view

### ISSUE THREAD

**Issue by ronaiza-cardoso** [DevExpress/devextreme-reactive#2162]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
### Description
I need to add link to my tree view. Here is my sample example: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-nb679?fontsize=14

**Comment by ushkal** [comment]
Hi @ronaiza-cardoso ,

Here's an [updated version](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-gdlil) of your application.

**Comment by ronaiza-cardoso** [comment]
Thank you for the instantaneous response! I have one more question: can I make async calls to subtree content?

**Comment by ushkal** [comment]
Could you please describe your scenario in greater detail?

**Comment by ronaiza-cardoso** [comment]
Now on my current example I have this set of data: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-nb679?fontsize=14 But on real-world example, my `subFolder` content is going to be loading on demand. Like, when I click on folder the `subFolder` content gonna be load from one service

**Comment by ushkal** [comment]
I suggest you refer to the "Tree data - [Load remote data on demand](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#load-remote-data-on-demand)" demo which covers your scenario

**Comment by ronaiza-cardoso** [comment]
I can't see the data structure of this example.

**Comment by ushkal** [comment]
The data structure of this example is: 
```
interface Node { 
  parentId: string,
  id: string,
  name: string,
  <other data properties>
}
```
 
The nodes with empty `parentId` are the first-level nodes. They are loaded on a first request when `parentIds=ROOT_ID `
