### ISSUE TITLE
Tree Data Expand Async

### ISSUE THREAD

**Issue by ronaiza-cardoso** [DevExpress/devextreme-reactive#2164]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description
I do not understand how async tree works. Like, how the root row is loaded? I can find where the root row is loaded.

https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ku5o7

**Comment by ushkal** [comment]
Hi @ronaiza-cardoso ,
 
This code allows the root row to be loaded when a data set is empty: 
`const rowIdsWithNotLoadedChilds = [ROOT_ID, ...expandedRowIds]`
 
When a row is expanded, its child rows are loaded as a result of the following sequence: 
- The expand button is clicked
- The onExpandedRowIdsChange event fires
- The app state is updated with new expanded ids
- The app renders
- componentDidUpdate is called 
- loadData is called

**Comment by ronaiza-cardoso** [comment]
But `ROOT_ID` is never empty, [here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ku5o7) start with `0` which is the fist item.

**Comment by ronaiza-cardoso** [comment]
![image](https://user-images.githubusercontent.com/7999914/61131950-4af1b800-a4b2-11e9-9cd4-191d36798f5e.png)

I wasn't able to find where the state was updated between the `componentDidUpdate` and the render.

**Comment by ushkal** [comment]
> But ROOT_ID is never empty, here start with 0 which is the fist item.

`ROOT_ID` is a `CategoryId` for the first item:
```
{
Id: 1,
CategoryId: 0,
Name: "Stores"
}
```
So there's no item having `ROOT_ID` as `Id`.
 
> I wasn't able to find where the state was updated between the componentDidUpdate and the render.

The state gets updated before the render occurs so this behavior is expected. For more information, please refer to the react [docs](https://hi.reactjs.org/docs/state-and-lifecycle.html).

**Comment by ronaiza-cardoso** [comment]
yes, but I can find where the state update is been trigged

**Comment by ushkal** [comment]
The issue is not clear to me. The "[Load remote data on demand](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#load-remote-data-on-demand)" demo shows how to initialize the ROOT_ID constant. See the 17th code line in the demo. Would you please elaborate on why you cannot use the same approach?

**Comment by ronaiza-cardoso** [comment]
Look this example: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-nb679 is been send no data.

**Comment by ushkal** [comment]
Here's a [modified example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-62f9e). For more details on using the getChildRows function please refer to the [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/custom-tree-data/#properties) and the "[Custom tree data](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#custom-tree-data)" demo.

**Comment by ronaiza-cardoso** [comment]
Still not able to get data on demand... here is another example: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-nb679

**Comment by ushkal** [comment]
The data is not displayed in your example because there are no rows with `ROOT_ID `as their `parentId`. So the Grid doesn't know what root rows are. Here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-sew12). 
Let us know if have any further questions.

**Comment by ronaiza-cardoso** [comment]
Ow! thank you soo much for your patience!  works like a charm!

**Comment by ushkal** [comment]
You are welcome!
