### ISSUE TITLE
React Chart - allow Tooltip customization

### ISSUE THREAD

**Issue by dimon82** [DevExpress/devextreme-reactive#2166]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

I'm not able to customize styles of Tooltip (specifically changing the background color), it does provide OverlayComponent but it's the top level and the styles are overridden by MuiPaper, there is also ContentComponent, but it's the actual content of the mui paper. I want to be able to change background color of the whole tooltip, including MuiPaper div as well as the arrow.

**Comment by Krijovnick** [comment]
Hi @dimon82 
Thank you for reporting the issue. I've reproduced this problem and we'll fix it soon.
