### ISSUE TITLE
The Chart's height is not same with the height property

### ISSUE THREAD

**Issue by JarponOK** [DevExpress/devextreme-reactive#2172]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour

The actual height of the chart does not match the specified

### Expected Behaviour

The height of the chart must correspond to the height of the DOM element.

### Steps to Reproduce

1. Set chart's property `height` to `XXX px` 
2. Inspect the DOM element. DOM elements `height`  is `XXX + 20 px`

i research the problem and found out that the chart has `padding: 10px`, which gives a total of `20px`

### Screenshots

![image](https://user-images.githubusercontent.com/35765711/61385496-2c792b80-a8bb-11e9-8d9a-022f14c343f0.png)
![image](https://user-images.githubusercontent.com/35765711/61385610-5cc0ca00-a8bb-11e9-8e05-bf34e06d7d4c.png)
![image](https://user-images.githubusercontent.com/35765711/61385621-677b5f00-a8bb-11e9-9923-67ed757fae8d.png)

### Environment

- "@devexpress/dx-react-chart": "^2.0.0"
- "@devexpress/dx-react-chart-material-ui": "^2.0.0"
- "react": "^16.5.2"
- browser: Safari, Google Chrome
- bootstrap: none
- react-bootstrap: none
- "@material-ui/core": "^4.2.0"
- "@material-ui/icons": "^4.2.1"
- "@material-ui/styles": "^4.1.2"

**Comment by churkin** [comment]
Hi @JarponOK,
Thank you for the issue, it looks like a bug. We will research and fix this soon.
