### ISSUE TITLE
node_modules/@devexpress/dx-core/dist/dx-core.d.ts missing

### ISSUE THREAD

**Issue by mfellner** [DevExpress/devextreme-reactive#2177]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate of an open or resolved issue.

Closed unresolved duplicate: https://github.com/DevExpress/devextreme-reactive/issues/2101

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
```
Error at ../../node_modules/@devexpress/dx-react-core/dist/dx-react-core.d.ts:6:25: Could not find a declaration file for module '@devexpress/dx-core'
```
* `node_modules/@devexpress/dx-core/dist/dx-core.d.ts` does not exist
* `node_modules/@devexpress/dx-react-core/dist/dx-react-core.d.ts` includes this line:
```ts
import { Mutable } from '@devexpress/dx-core';
``` 

* https://cdn.jsdelivr.net/npm/@devexpress/dx-react-core@2.0.1/dist/dx-react-core.d.ts
* https://www.jsdelivr.com/package/npm/@devexpress/dx-core?path=dist

### Expected Behaviour
`node_modules/@devexpress/dx-core/dist/dx-core.d.ts` does exist.

### Environment

* "@devexpress/dx-react-core": "2.0.1"
* "@devexpress/dx-react-grid": "2.0.1"
* "@devexpress/dx-react-grid-material-ui": "2.0.1"
* "react": "16.8.6"
* "react-dom": "16.8.6"
* "typescript": "3.5.3"

**Comment by ushkal** [comment]
Hi,
 
Thank you for pointing out to this issue. We'll fix it in the next release. As a workaround to make your project compile, you can add a `.d.ts` file with the following content:

```
declare module '@devexpress/dx-core' {
  type Mutable<T> = { -readonly [P in keyof T]: T[P] };
}
```
