### ISSUE TITLE
Can I Banded Columns with same object key?

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#2181]
HI,
I have questions about can I Banded Columns with same object key because it shows me a bunch of error in the console.

 my data looks like:
```
const data = [{
    name: 'Joe',
    year: 2019,
    saving: 0,
    member: false,
    group: "A"
  },
  {
    name: 'Amy',
    year: 2019,
    saving: 0,
    member: false,
    group: "B"
  },
  {
    name: 'Bob',
    year: 2019,
    saving: 0,
    member: true,
    group: "C"
  }
];

const columnBands = [
  { title: "Group A",
    children: [
   { columnName: "name" }, 
   { columnName: "year" },
   {columnName: "saving" }, 
  { columnName: "member" }
]
  },
  { title: "Group B",
    children: [
   { columnName: "name" }, 
   { columnName: "year" },
   {columnName: "saving" }, 
   { columnName: "member" }
]
  }
]
```
If I do this above code, banded Columns got messy because they have the same object key, they not sure which parent is it.

I even try to turn my data with a different key name like this:
```
  {
    name_B: 'Amy',
    year_B: 2019,
    saving_B: 0,
    member_B: false,
    group_B: "B"
  }
```
When I turn data like above, the <Grid row={rows}> will show cant not map through error.

Do we have any way to solve this kind of issue? Thank you!

My idea kind like this picture below: 
<img width="872" alt="Screen Shot 2019-07-19 at 4 00 15 PM" src="https://user-images.githubusercontent.com/26178313/61565906-13e64e00-aa40-11e9-8e17-5f6544cf21cd.png">

**Comment by MaximKudriavtsev** [comment]
Hi @madebymt,

The Banded Columns feature works expected in this case.

I see two easy ways to achieve your behavior:

- add unique keys to your columns, see the [next example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-vx6dp);
- add tree data tables into your project to display it, see the [following example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-s6qsu).

**Comment by madebymt** [comment]
Thank you so much for your example! @MaximKudriavtsev

**Comment by MaximKudriavtsev** [comment]
@madebymt 

You are welcome!
