### ISSUE TITLE
Calculate the average of child rows, in Tree data, display on parent row

### ISSUE THREAD

**Issue by cobyrne09** [DevExpress/devextreme-reactive#2182]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

So I have a tree data grid in uncontrolled mode with a plain array of data, with numerous root rows. Each child has a value 'completion' that is a boolean value. I would like to calculate a completion percentage of all the children (recursively), and display that on the parent row. I see a number of examples of this being done with grouped data (using either sum or averages) and displaying it in a summary row, but none with tree data and displaying the value on the parent row. Is this possible? Would the recursion cause too much overhead? Thanks so much!

### Environment

- devextreme-reactive: 2.0.0
- react: 16.8.6
- browser: chrome
- bootstrap: 4
- react-bootstrap: none
- material-ui: none

**Comment by Krijovnick** [comment]
@cobyrne09 This functionality is not supported out of the box. You can calculate the `treeSummaryValues` property in the `CustomSummary` plugin by yourself and reuse the `cellComponent` property in the `TableTreeColumn` plugin to set your values:
```
CellComponent = props => (
  <TemplateConnector>
    {({ treeSummaryValues }) => {
      return (
        <TableTreeColumn.Cell {...props}>
          {props.children}
          <p>{treeSummaryValues[0]}</p>
        </TableTreeColumn.Cell>
      );
    }}
  </TemplateConnector>
);
```

**Comment by cobyrne09** [comment]
thank you!!
