### ISSUE TITLE
React Chart - when data changes, chart is not refreshing

### ISSUE THREAD

**Issue by dimon82** [DevExpress/devextreme-reactive#2185]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

I pass in data that changes depending on the filters, however the chart itself doesn't refresh. The data is react state which can change. It seems like chart needs to refresh as well.

**Comment by MaximKudriavtsev** [comment]
Hi @dimon82,

I can't reproduce it. Could you please update my [example](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-v9u59) to reproduce the incorrect behavior?

**Comment by dimon82** [comment]
Hi @MaximKudriavtsev, working with local state seems to be working fine. I'm using MobX state management and looks like passing in its state (observable) to the chart only works on the first render, subsequent updates to that state do not refresh the chart. This is interesting why it only works the first time.. Given that local react state works, I did find a workaround by converting MobX "data" array to vanilla JS array right before passing that to the chart... this worked. So problem solved for me, unless you want to take a look why MobX state doesn't work as expected, but I assume it's not a priority :)

Quick question though, does Animation only work on the first render? It doesn't seem to animate the chart when data changes.

**Comment by MaximKudriavtsev** [comment]
@dimon82,

You can find information about MobX integration in the [following topic](https://github.com/DevExpress/devextreme-reactive/issues/452#issuecomment-344233646).

> Quick question though, does Animation only work on the first render? It doesn't seem to animate the chart when data changes.

Yes, animation works only the first render out of the box. We will work on this point in the future.
