### ISSUE TITLE
Conditional CommandButtons rendering

### ISSUE THREAD

**Issue by andsmi97** [DevExpress/devextreme-reactive#2190]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is it possible to create conditional CommandColumn rendering? 
For example i want to disable editing and deleting rows where date is not the closest to current date like on screenshot.
![image](https://user-images.githubusercontent.com/26883514/61788498-e2dc9380-ae1a-11e9-9e9a-8652c9de3d9c.png)

**Comment by churkin** [comment]
Hi @andsmi97, 
[Here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-guhru) is the code example that implements the scenario you described above. Let me know if you have any additional questions.

**Comment by andsmi97** [comment]
Thank you, that's exactly what i was needed!

**Comment by churkin** [comment]
You are welcome!
