### ISSUE TITLE
<SearchPanel /> Placeholder not working

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2192]
Hi, 

I am using [devextreme's React grid ](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/) and am having issues with changing the Search panel placeholder. I am using the following code: 
                        `<SearchPanel searchPlaceholder="Search by date or order number"/>`
but for some reason it's not affecting the input placeholder. Does the searchPlaceholder have any known conflicts with other features?

**Comment by LazyLahtak** [comment]
Hi @paufar,
 
The SearchPanel plugin has the messages [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/search-panel/#properties) with the [LocalizationMessages](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/search-panel/#localization-messages) type. It is an object with the searchPlaceholder field, which contains a custom message for the search panel. You need to pass this object with your message in the messages property.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-m4x02) of how to do it.

**Comment by LazyLahtak** [comment]
Let us know if you still have questions.
