### ISSUE TITLE
How to do custom filtering behavior and stay default searching behavior

### ISSUE THREAD

**Issue by iposokhin** [DevExpress/devextreme-reactive#2196]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I use controlled mode on searching and filtering. IntegratedFiltering depends on both. Default behavior for serching is cool. But I want use a custom filtering behavior. When I add column extensions property in IntegratedFiltering component searching behavior will depend by predicate function, that I would like to use only for filtering. How to do default serching and custom filtering?

- devextreme-reactive: 1.10.1
- react: 16.8.1
- browser: any

**Comment by ushkal** [comment]
Hi @iposokhin ,

In a predicate function, you can determine whether the current action is filtering or searching using the `filter.operation` property: in the filtering action, it is always defined and in the searching one, it is always undefined. In this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-hg5pm) project, custom filtering behavior is used for date column, while search is left as is.
Let us know if you have any further questions.

**Comment by iposokhin** [comment]
Hi @ushkal ,

A little bit wrong but it helped. In my case I haven't `filter.operation` because use my own filter form and filter has only columnName and value properties. But the idea of returning IntegratedFiltering.defaultPredicate(value, filter, row) helped me. Thank you!

**Comment by ushkal** [comment]
You are welcome!
