### ISSUE TITLE
Columns resizing with partial predefined columns width

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2209]
### I'm using ...
- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Using the "TableColumnResizing" plugin, it is not possible to partialy specify columns width.
For example, I want to have specific width for 2 out of my 5 columns. I would like to have the 3 unspecified to be set automaticaly by the grid (as if it was all handle by it).

I did try this : 
{...}.map((m)=>{ columnName: m.name, width: m.width ? m.width : "auto" } as TableColumnWidthInfo)
It works to show the grid, but I cannot resize columns with { width:"auto" }

**Comment by LazyLahtak** [comment]
Hi @franciscailleAstus,

We are aware of this issue and are working on it. Please [subscribe](https://github.com/DevExpress/devextreme-reactive/issues/411) to it to be informed of our progress.
