### ISSUE TITLE
Filtering not working correctly in Lazy Loading demo

### ISSUE THREAD

**Issue by npc144** [DevExpress/devextreme-reactive#2214]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
In the current lazy-loading documentation (https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/), section "Row Caching", if I search "843.6" (visible wihout filter) in the amount column, it does not return any result. It also don't show any after I remove the filter. The same is true for the "Date" column.

It does work however If I go character by character, at least until the last character, which for some reason does not.

The others columns seems to work, but they are not using a custom DataTypeProvider.

### Expected Behaviour
The filtered row should still be displayed when typed in full, even in a DataTypeProvider.
After removing the filter, it should show the original data, not "No Data"

### Steps to Reproduce

Copy & paste a value in the "Amount" column. It will show "No Data". Remove the filter, it still show "No Data".

### Environment

The official website documentation.

**Comment by ushkal** [comment]
Hi,
 
Thank you for reporting this issue. We'll fix it soon.

**Comment by ushkal** [comment]
We've researched the issue and found that it is caused by a problem in a cache created by the [createRowCache](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/create-row-cache/) function. As a workaround you can use your own cache implementation.
