### ISSUE TITLE
Is it possible to filter 2 columns at once using SearchPanel? 

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2220]
I have a table including a column for customer name and a column for the surname. Is it possible that from the search panel when i type in a full name , the filter uses both columns for search?

**Comment by LazyLahtak** [comment]
Hi @paufar,

The [SearchPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/search-panel/) plugin works with [SearchState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/search-state/) that creates a predicate to search some value in all cells. In your case, I recommend you use [FilteringState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/filtering-state/). To work with it, you may create a [custom plugin](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/), which will be placed in the [toolbarContent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/#exports) template, and define a function, which will calculate [filters](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/filtering-state/#filter) from your string. 
If you need to define a complex condition, you can create another plugin that will calculate [filterExpression](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#filterexpression) and pass it as the filterExpression [getter](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#imports) for IntegratedFiltering. Attached is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-2t53u) where we illustrated this approach. 
Let us know if this solution is suitable.

**Comment by paufar** [comment]
HI @LazyLahtak thanks for your reply - the example is exactly what I need, however my component is a class and so when typing nothing is happening - https://codesandbox.io/s/devextreme-react-grid-for-material-ui-k599w?fontsize=14 (this is my component stripped of the API fetches to remove as much unrelated code as possible so the component won't run, however maybe you can identify a clear issue here? I'm thinking its something because of the difference between useState and setState but not sure what it is

**Comment by LazyLahtak** [comment]
Hi @paufar,
 
We couldn't run you project using only a virtual table, even without additional components. Please, send us a runnable project so that we could assist you.

**Comment by paufar** [comment]
hi @LazyLahtak 
Updated the component: 
Its a much simpler component that what I actually have but the structure of the component is the same and this also shows how i integrated the code from your example in my component. Let me know if this helps thanks
https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-cjob1

**Comment by LazyLahtak** [comment]
@paufar,
 
The Getter is PureComponent. That is why this component should get a new copy of the function in the computed property every time to call it and return the new filterExpression. There were some mistakes related to the use of setState in that example.
I [modified it](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-w5v7k).
Let us know if it suits your needs.

**Comment by paufar** [comment]
@LazyLahtak - Thanks for the update it works now! However is there any way to keep the rest of the filtering for other columns? and have this as an addition to the original search panel which searches in all columns?

**Comment by LazyLahtak** [comment]
@paufar,
 
Custom plugin can work with original searching and filtering capabilities. To enable this, you need to place the CustomFiltering plugin after SearchState and FilteringState. In the plugin, you need to redefine the filteringExpression getter by adding your custom filters.
Attached is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-j6gwt) that contains CustomSearchPanel with SearchPanel and TableFilteringRow. To allow filtering only in certain columns, you need to define [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#tablefilterrowcellprops) for [TableFilteringRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/).
Let us know if it is what you need.

**Comment by paufar** [comment]
@LazyLahtak 

Is it possible to have all the filters in one? The default searchPanel used to search in all of the table column all from the same search box instead of having filters on top of each column with individual filters.

**Comment by LazyLahtak** [comment]
@paufar,
 
Would you please clarify what you mean? The SearchPanel already works like a filter for all columns.

**Comment by paufar** [comment]
@lazylahtak for me the last 2 examples you sent the search box only searches the first name and surname for example if i search by car type it does not  show any results so it seems like the default search panel functionality was overwritten with the custom search panel

**Comment by LazyLahtak** [comment]
@paufar,
 
As I understand it, you need the custom search panel to filter columns by a full name for name and surname columns, or by a value for other columns.
Here is the new [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-rvf9z). Does this solution suit you?

**Comment by paufar** [comment]
@lazylahtak that’s perfect!! Thanks!

**Comment by LazyLahtak** [comment]
@paufar, You're welcome!
