### ISSUE TITLE
React Grid 1.11 docs?

### ISSUE THREAD

**Issue by matthewjwhitney** [DevExpress/devextreme-reactive#2221]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Where are the react grid 1.11 docs? i'm not ready to switch to 2.0 but the docs on the website don't seem to have a way to select the docs for older versions.

### Environment

- devextreme-reactive: 1.11
- react: 16.8.6
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.3

**Comment by Krijovnick** [comment]
Hello @matthewjwhitney 
 
We released version 2.0 of DevExtreme Reactive Components because of a migrate to MUI v4, and the difference in the documentation between versions 1.11 and 2.0 is really slight.
Could you please clarify what prevents you from switching to v2.0?
