### ISSUE TITLE
Add a drop down for particular columns on filter row

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#2222]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am using <TableFilterRow />. Is it possible to add a drop down for select option on particular columns? It is great if you have any example on <TableFilterRow.Cell />.

### Environment

- devextreme-reactive: xxx
- react-bootstrap

**Comment by ushkal** [comment]
Hi @susuwatari2 ,

Please review a similar [issue ](https://github.com/DevExpress/devextreme-reactive/issues/2119) and let us know if this solution doesn't meet your requirements.
