### ISSUE TITLE
Changing Filter Operation does not trigger "onFiltersChange"

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2224]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Changing the filter operation does not trigger "onFiltersChange" event.

### Expected Behaviour

Changing the filter operation shoul trigger "onFiltersChange".

### Linked Issue
https://github.com/DevExpress/devextreme-reactive/issues/1269

- devextreme-reactive: 2.0.2
- react: 16.8.6
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3.1

**Comment by Krijovnick** [comment]
Hi @franciscailleAstus 

I can't reproduce the issue. Could you modify the [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-l7ymv) to reproduce the problem.

**Comment by franciscailleAstus** [comment]
Here is my example: [https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-vp7bz](url)

I would like to have the filter "isEmpty" as shown:
![image](https://user-images.githubusercontent.com/44379473/62728866-cc256780-b9ea-11e9-82a3-0db86cf9c3f2.png)

When selected, I would like to show all values that have : "null" | "". I already have a custom predicate for that, but it is only triggered when I start typing into the filter.

**Comment by Krijovnick** [comment]
Filter operations trigger the "onFiltersChange" event when any filter is set. If you want to show all values that have "null"  or  "" set those values in the Filter Row editor respectively.
![2019-08-09_1356](https://user-images.githubusercontent.com/8238559/62774553-b88f0500-baad-11e9-8e32-e96727dad54e.png)
