### ISSUE TITLE
Customize Filter Row Appearance with Operations selector

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2225]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am using the "Customize Filter Row Appearance" overriding the "cellComponent" attribute of "TableFilterRow". I would like to show the operation selector next to my custom filter row. Is this possible ?

![image](https://user-images.githubusercontent.com/44379473/62652943-7be6d080-b92a-11e9-958b-c3b9393125b2.png)

### Environment

- devextreme-reactive: 2.0.2
- react: 16.8.6
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3.1

**Comment by LazyLahtak** [comment]
Hi @franciscailleAstus,
 
TableFilterRow's cellComponent has two children. The first one is an operation selector, the second one is a text field. To show the selector after the text field, place the second child before the first.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-4b7sq) on how to do that.
Let us know if this solution is suitable.
