### ISSUE TITLE
Expand Detail Row on Row Click

### ISSUE THREAD

**Issue by hawekotte** [DevExpress/devextreme-reactive#2230]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I would like to be able to expand a detail row when the corresponding row is clicked (rather than only being able to click the toggle icon on the left).

I am currently capturing which row was clicked using the `Table` `rowComponent` `onClick` handler. Though I am now unsure of how to make use of this information. I presume it can use `toggleDetailRowExpanded` but I am unsure of how to implement this (as [this issue](https://github.com/DevExpress/devextreme-reactive/issues/1275) is closed and doesn't quite fit my needs). Cheers!

**Comment by MaximKudriavtsev** [comment]
Hi @hawekotte,

To achieve this behavior, you should use the [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) and as you correctly mentioned, override the table row component. The next [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-e3bbl) demonstrates how to do it.

**Comment by hawekotte** [comment]
Thanks for the reply @MaximKudriavtsev! I've taken a look at the provided example and read the docs, but the implementation still isn't working. I am using a functional component but that should not be a big problem as the [controlled mode example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) uses such. 

To better help diagnose the issue I have set up a minimal recreation of the issue [here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-g6gho). Let me know what other information is needed, and again thank you very much for all of the help! 😄

**Comment by MaximKudriavtsev** [comment]
@hawekotte,

In controlled mode, you should use properties without the `default` prefix because these properties apply only for initial component rendering.

I’ve updated your [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-02ccf) and now it works fine.

**Comment by hawekotte** [comment]
How could I miss that? Thanks a ton!

**Comment by MaximKudriavtsev** [comment]
You are welcome!
