### ISSUE TITLE
Add capability to collapse appointments with similar time 

### ISSUE THREAD

**Issue by nonatudrinkidrive** [DevExpress/devextreme-reactive#2231]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Tell me pls. how to collector appointment or components not support.

### Environment

"@devexpress/dx-react-core": "^2.0.2",
"@devexpress/dx-react-scheduler": "^2.0.2",
"@devexpress/dx-react-scheduler-material-ui": "^2.0.2",

**Comment by MaximKudriavtsev** [comment]
Hi @nonatudrinkidrive,

Thank you for your reply. If I understand you correctly, you mean an appointment collector that collapses appointments at a similar time. Please see the following image.

![image](https://user-images.githubusercontent.com/15093892/62933711-8215fa80-bdcb-11e9-86c7-0e5b18495fbe.png)

We think this is the most required feature and it has high priority in our plans. It will be implemented as soon as possible. Now we are working under our `Release` version of the Reactive Scheduler and I cannot give you an estimates when this feature will be implemented.

**Comment by nonatudrinkidrive** [comment]
Oh.. that i want., Thank for reply me. :)

**Comment by cuongqle** [comment]
Hi @MaksimKonyaev : do we have plant for the release of this feature?

**Comment by MaximKudriavtsev** [comment]
Hi @cuongqle,

Yes, we hope to implement this feature soon. You can describe your requirements here so that we can consider them as well.

It would be helpful if you give us more information about your application.

**Comment by cuongqle** [comment]
Hi @MaximKudriavtsev ,

We are building an internally webapp using for our staffs, and we are using Material-Ui library, we have a module to allow user to create appointments and it will connect to outlook for notification.

We notice that, it does not look user friendly when there are multiple appointments in a cell within a day (as attached image)

![image](https://user-images.githubusercontent.com/7144697/75035726-c3a60180-54e2-11ea-9587-6c663c6f1555.png)

So we want to improve it to limit appointment per cell and add an expender (such as Show More), and click on it, display them in another popup or something like that)

Something like already built on devexpress scheduler component as below image
![image](https://user-images.githubusercontent.com/7144697/75035995-6199cc00-54e3-11ea-9e4d-a8157e33aead.png)

Hope my short describe are enough clearly!

Thanks/Cuong

**Comment by MaximKudriavtsev** [comment]
@cuongqle,

Thank you for sharing this information. Unfortunately, we don't have a workaround at the moment.

Would you please clarify why you are not using our [DevExtreme Scheduler for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/)?

**Comment by cuongqle** [comment]
@MaximKudriavtsev : thanks for quick response.
Yes, sure. 
From material-ui page document:
[](https://material-ui.com/discover-more/related-projects/#schedulers-calendars)
They recommend to use devexpress-reactnative [](https://devexpress.github.io/devextreme-reactive/react/scheduler/), one of the main reason is to make all application having the same look and feel of material-ui style.

That why i use that library instead of devextreme scheduler for react.

**Comment by MaximKudriavtsev** [comment]
@cuongqle, thank you!

**Comment by MaximKudriavtsev** [comment]
We have released the 2.7.0 version of [DevExtreme Reactive Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/) with this feature.

![image](https://user-images.githubusercontent.com/15093892/87781640-b8f55b80-c839-11ea-8d0a-b9b71e9b7120.png)

**Comment by gfiury** [comment]
Thanks @MaximKudriavtsev for the future!!!

As @cuongqle said, it would be great if we have some code to workaround the MonthView.

I found this example: [Not overflowing](https://codesandbox.io/s/wandering-dew-98lxp)
There is a new Plugin called **IntegratedAppointments**

Is it possible to change the example to make something like the below image?
![day example](https://user-images.githubusercontent.com/20029282/88342400-ba30f780-cd15-11ea-8e16-57aa8f6a2942.png)

Regards,
William

**Comment by rawad663** [comment]
This thread is very useful! I'm looking for a way to limit the number of appointments in MonthView cells, and show "+n more" for any additional appointment.

I have not found a way to do it so far. Any help is appreciated!

**Comment by EduardoFochetto** [comment]
Hello everyone, is there any update on this task? I wish to limit the number of appointments in MonthView and WeekView cells, and also show "+n more", i tried the [IntegratedAppointments](https://codesandbox.io/s/wandering-dew-98lxp) and partially works, but i have not found a way to show the "+n more". 

Thanks in advance for the answers!
