### ISSUE TITLE
how do i make odd rows and even rows different colored?

### ISSUE THREAD

**Issue by rhqD** [DevExpress/devextreme-reactive#2237]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

how do i make odd rows and even rows different colored?
 shouldn't there be a option for this. like rowAlternationEnabled in devextreme-react/data-grid?
do i have to do that myself? if i do, how?

### Environment

- devextreme-reactive: 2.0.0
- react: 16
- browser: none
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/627#issuecomment-371119006).
