### ISSUE TITLE
VirtualTable crashing bug

### ISSUE THREAD

**Issue by limzb** [DevExpress/devextreme-reactive#2243]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

React Grid throws an TemplatePlaceHolderBase exception when there is too much data in a small virtual table, eg: 100 rows of data in a 200px height virtual table.

### Expected Behaviour

Virtual table should not throw the exception

### Steps to Reproduce

**Sample Code**

```
import React from 'react'
import {
  Grid,
  TableHeaderRow,
  VirtualTable,
} from '@devexpress/dx-react-grid-material-ui'

const Root = (props) => <Grid.Root {...props} style={{ height: '100%' }} />

const getRowId = (row) => row.id

class Report extends React.Component {
  render () {
    return (
      <div>
        <Grid
          // rootComponent={Root}
          getRowId={getRowId}
          columns={[
            {
              name: 'name',
              title: 'Name',
            },
            {
              name: 'description',
              title: 'Description',
            },
          ]}
          rows={[
            { id: '1', name: '123', description: '123' },
            { id: '2', name: '123', description: '123' },
            { id: '3', name: '123', description: '123' },
            { id: '4', name: '123', description: '123' },
            { id: '5', name: '123', description: '123' },
            { id: '6', name: '123', description: '123' },
            { id: '7', name: '123', description: '123' },
            { id: '8', name: '123', description: '123' },
            { id: '9', name: '123', description: '123' },
            { id: '10', name: '123', description: '123' },
            { id: '11', name: '123', description: '123' },
            { id: '12', name: '123', description: '123' },
            { id: '13', name: '123', description: '123' },
            { id: '14', name: '123', description: '123' },
            { id: '15', name: '123', description: '123' },
            { id: '16', name: '123', description: '123' },
            { id: '17', name: '123', description: '123' },
            { id: '18', name: '123', description: '123' },
            { id: '19', name: '123', description: '123' },
            { id: '20', name: '123', description: '123' },
            { id: '21', name: '123', description: '123' },
            { id: '22', name: '123', description: '123' },
            { id: '23', name: '123', description: '123' },
            { id: '24', name: '123', description: '123' },
            { id: '25', name: '123', description: '123' },
          ]}
        >
          <VirtualTable height={200} />
          <TableHeaderRow />
        </Grid>
      </div>
    )
  }
}
export default Report
```

### Screenshots

![image](https://user-images.githubusercontent.com/33625320/63154692-cc091580-c043-11e9-902a-fb2420a92bca.png)
![image](https://user-images.githubusercontent.com/33625320/63157865-8865da00-c04a-11e9-8940-edb7060c878a.png)

### Environment

- @devexpress/dx-grid-core: 2.0.3
- @devexpress/dx-react-grid: 2.0.3
- @devexpress/dx-react-core: 2.0.3
- @devexpress/dx-react-grid-material-ui: 2.0.3
- react: 16.9.0
- browser: Google Chrome
- material-ui: 4.3.2

**Comment by MaximKudriavtsev** [comment]
I can't reproduce it. Could you please update [my example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ixiit) to reproduce the incorrect behavior?

**Comment by limzb** [comment]
Hi @MaximKudriavtsev, thanks for answering my question. 
Sorry for the late reply, this problem has been resolved. 
It was happening due to the upgrade of react version, previously we were using react v16.8 and then upgraded to v16.9, hence the issue aforementioned.
