### ISSUE TITLE
Filter editor can't be disabled when DataTypeProvider is used

### ISSUE THREAD

**Issue by calvinl** [DevExpress/devextreme-reactive#2247]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm using a table with both `TableEditRow` and `TableFilterRow` as well as a `DataTypeProvider` to add a boolean data type (to render a Yes/No dropdown selection as the `editorComponent`). Problem is, I only wanted this to render in TableEditRow and not TableFilterRow, but it's rendering it for both. I'm also not receiving the `disabled` prop in my `editorComponent` even though I have `filteringDisabled` in `columnExtensions`. 

### Expected Behaviour

Properly receive column extension props in `editorComponent` of `DataTypeProvider`

**Comment by ushkal** [comment]
Hi @calvinl ,

I've reproduced the issue. We'll fix it soon. In the meantime, I suggest you override the [TableEditRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-row/#properties).cellComponent property to accomplish your task.

**Comment by calvinl** [comment]
@ushkal I've also noticed that there should probably be a way to differentiate whether the editor being used is for filtering or for editing as there are some props that need to vary, for example the placeholder and styles. Perhaps the solution is to pass those as props into `editorComponent` ?

**Comment by ushkal** [comment]
>there should probably be a way to differentiate whether the editor being used is for filtering or for editing as there are some props that need to vary

Thank you for this suggestion. We plan to improve this API in future releases.

**Comment by calvinl** [comment]
@ushkal thank you! I'll create a new issue for that.
