### ISSUE TITLE
Virtual table in combination with column chooser gives error

### ISSUE THREAD

**Issue by brense** [DevExpress/devextreme-reactive#2248]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

`VirtualTable` in combination with `ColumnChooser` gives an error when changing column visibility. It works fine when a normal Table is used.

### Expected Behaviour

That `VirtualTable` works the same as normal `Table` when changing column visibility.

### Steps to Reproduce

As mentioned above, when changing column visibility on a `VirtualTable` an error is thrown:
`Uncaught TypeError: Cannot read property 'type' of undefined`
See screenshot below for more details

### Screenshots

[https://imgur.com/a/zlEbc42](https://imgur.com/a/zlEbc42)

### Environment

- devextreme-reactive: 2.0.3
- react: 16.9.0
- browser: Chrome 76.0.3809.100 (64bit)
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3.2

**Comment by ushkal** [comment]
Hi @brense ,
 
Thank you for reporting the issue. We'll fix it soon.

**Comment by brense** [comment]
Perfect! Thank you for the swift response!
