### ISSUE TITLE
Undefined row id when using remote grouping example

### ISSUE THREAD

**Issue by npc144** [DevExpress/devextreme-reactive#2250]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I've copy/pasted the "Remote Grouping" example situated [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/) in this [codesandbox](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-iyn5l).

After a drag and drop of a column in the grouping header, the message "The row id is undefined. Check the getRowId function. The row is ..." appear in the console. At this point the grouping seems to work fine but if you remove the column from the grouping, theres a "Encountered two children with the same key" which in turn, make the row data undefined.

When you do this on the documentation website, the grid disappear.

I've tried using older version of devexpress in the sandbox but theres no difference.

### Expected Behaviour

Removing a row that was previously grouped from the TableGroupRow should put the table in it's initial state.

### Steps to Reproduce

Drag and drop any column in the group header and then remove it.

### Environment

- devextreme-reactive: 2.0.3
- react: 16.9.0
- browser: chrome
- material-ui: 4.3.2

**Comment by LazyLahtak** [comment]
Hi @npc144,
 
Thank you for reporting this issue. We will research it and fix as soon as possible.
