### ISSUE TITLE
getColumnWidthGetter has undefined "column" (ColumnChooser issue ?)

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2252]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

With the new version (2.0.3) I get an undefined column, when I try to remove column with the columnChooser.
![image](https://user-images.githubusercontent.com/44379473/63378900-2adecf80-c361-11e9-8cc6-1df0306c3591.png)

With version < 2.0.3, everything was fine.

### Expected Behaviour

I should not get 
![image](https://user-images.githubusercontent.com/44379473/63378973-506bd900-c361-11e9-875e-1f1d634e0876.png)
when trying to remove column with the columnChooser.

### Steps to Reproduce

Remove a column with the columnChooser plugin.

### Environment

- devextreme-reactive: 2.0.3
- react: 16.9.0
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3.2

**Comment by LazyLahtak** [comment]
Hi @franciscailleAstus,
 
We already have a report about this bug. We will fix it soon. Please refer to this bug [report](https://github.com/DevExpress/devextreme-reactive/issues/2248) for further information.
