### ISSUE TITLE
Header Fixed Cell, Border Style Problem

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2255]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When the columns are grouped, the border at the top of the lines should not appear. But when the state is updated in the table, the problem is corrected.

### Screenshots

![image](https://user-images.githubusercontent.com/13018803/63417526-21f60880-c40a-11e9-9431-ab6bfb6c1b0d.png)
![image](https://user-images.githubusercontent.com/13018803/63417556-33d7ab80-c40a-11e9-8d16-1c6561cee383.png)
![image](https://user-images.githubusercontent.com/13018803/63417696-70a3a280-c40a-11e9-91a8-e1042f4385b4.png)
![image](https://user-images.githubusercontent.com/13018803/63417571-39cd8c80-c40a-11e9-89c3-960bc0a7e6f9.png)

### Environment

- devextreme-reactive: xxx
- @devexpress/dx-react-core: "^2.0.2",
   @devexpress/dx-react-grid: "^2.0.2",
   @devexpress/dx-react-grid-material-ui: "^2.0.2",
   @material-ui/core: "^4.3.1",
   prop-types: "^15.7.2",
   react: "^16.8.6",
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,
 
I couldn't create the same example based on your screenshots. Could you please send a runnable project? This will help us research this case.

**Comment by ahmetcaglayan** [comment]
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ysk40

![image](https://user-images.githubusercontent.com/13018803/63570746-da48bb80-c586-11e9-9bc8-b320b9882604.png)

the same applies to the selection column.

**Comment by ahmetcaglayan** [comment]
![image](https://user-images.githubusercontent.com/13018803/63571218-41b33b00-c588-11e9-920d-3668e4d5252f.png)
![image](https://user-images.githubusercontent.com/13018803/63571248-57286500-c588-11e9-9502-09e51092a4ce.png)

**Comment by LazyLahtak** [comment]
@ahmetcaglayan, 

I researched you example and found some mistakes in the styles' definition. Here is the updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-rv8xc).
If you have further questions, let us know.
