### ISSUE TITLE
Custom title for header 

### ISSUE THREAD

**Issue by simonwebdev000000001** [DevExpress/devextreme-reactive#2259]
Hi, i would like to to set up my theme className for header title, but can`t find a way how can i apply my own header title + props which have sorting.
https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-hfjmy. In this example i want to apply class 'test' dirrect to title span,
![Screenshot_14](https://user-images.githubusercontent.com/7140418/63439018-f852d680-c435-11e9-801f-8b7d9538d71c.jpg)

**Comment by ushkal** [comment]
Hi @simonwebdev000000001 ,
You need to override the `contentComponent` instead. See the following [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-7kzlm).
