### ISSUE TITLE
How custom table head style ?

### ISSUE THREAD

**Issue by shangdev** [DevExpress/devextreme-reactive#2268]
### I'm using ...

React Grid

### Description

I try this code:

```
const HeadComponent = ({ row, ...restProps }) => (
    <Table.Head
        {...restProps}
        style={{ ... }}
    />
);

<Grid>
    ...
    <VirtualTable
        headComponent={HeadComponent}
    />
    ...
</Grid>
```

It's not work, I'm get error message.

### Environment

- devextreme-reactive: 1.11.1
- react: 16.9.0+
- material-ui: 3.9.3

**Comment by LazyLahtak** [comment]
Hi @shangdev,
There are some mistakes in the defined HeadComponent. You should define it like VirtualTable.TableHead. Here is a working [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-rezdf).
To get more information about VirtualTable components. see our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/).
If you have any further questions, please let us know.
