### ISSUE TITLE
Cannot read property of undefined error when hiding a column when the page has no scrollbar

### ISSUE THREAD

**Issue by abdellatifdanba** [DevExpress/devextreme-reactive#2273]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I get an error when I hide columns when the page has **no** scrollbar. Error message: "Uncaught TypeError: Cannot read property 'type' of undefined" line 1795 in "dx-grid-core-es.js".

### Expected Behaviour

The code should not break when a user hides a column without a horizontal scrollbar.

### Steps to Reproduce

1. Click on the "choose columns" button in the grid.
2. Choose 1 or multiple columns to hide.
3. Receive an error when there is no scrollbar.

### Screenshots

![image](https://user-images.githubusercontent.com/54537475/63690058-fb6e0e00-c80b-11e9-94ca-f033a624d681.png)

### Environment

- devextreme-reactive: 2.0.2
- react: 16.9.0
- browser: Chrome, Firefox
- bootstrap: none
- react-bootstrap: none
- material-ui: 6.4.1

**Comment by LazyLahtak** [comment]
Hi @abdellatifdanba,

We already received a [report](https://github.com/DevExpress/devextreme-reactive/issues/2248) about this issue and fixed it. The fix will be published with our next release.
