### ISSUE TITLE
Header table styling

### ISSUE THREAD

**Issue by maximenathan** [DevExpress/devextreme-reactive#2276]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I can't find a way to style properly Table Header
I want to only display a border at the bottom of the Header containing the `label` and `filters` like this :

![image](https://user-images.githubusercontent.com/7127156/63757340-2fa00800-c8ba-11e9-800c-a96471e837ea.png)

But the closer I get is a partial border:
[Code SandBox example](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-x4mmp)
I want to apply a `border-collapse: collapse` on the head table, but can't find a way to do it

Any idea? 
Thank you very much

### Environment

- devextreme-reactive: 2.0.0
- react: 16.9
- browser: chomr 74
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3

**Comment by LazyLahtak** [comment]
Hi @maximenathan,

If you want to define borders for these cells, you should define cellComponent for corresponding plugins. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-p2o4v), where I have removed unnecessary borders.
Let us know if it meets your needs.

**Comment by maximenathan** [comment]
Perfect, I wasn't looking for the correct solution
Thank you!

**Comment by LazyLahtak** [comment]
You are welcome!
