### ISSUE TITLE
Error when changing visible columns

### ISSUE THREAD

**Issue by chr22** [DevExpress/devextreme-reactive#2281]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Maybe 1/3 of the times I change which columns the table should show with the `columns` property on Grid it will throw an error.

This is a problem that has been introduced in version 2.0.3. It works fine in 2.0.2.

### Expected Behaviour

No error being triggered.

### Steps to Reproduce

Change columns in virtual table after it has been rendered. It sometimes takes 2-3 changes to trigger the problem.

### Screenshots

![image](https://user-images.githubusercontent.com/3649594/63865939-bdf7b500-c9b2-11e9-8eba-af71dd4650d4.png)
![image](https://user-images.githubusercontent.com/3649594/63865967-c8b24a00-c9b2-11e9-878b-47ac5285d2f6.png)

### Environment

- devextreme-reactive: 2.0.3
- react: 16.9.0
- browser: Chrome 76
- bootstrap: 2.0.3
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi @chr22 ,

We have already fixed this issue in the context of #2248 . The fix will be published soon.
