### ISSUE TITLE
How to disable horizontal scroll When vertical scroll?

### ISSUE THREAD

**Issue by shangdev** [DevExpress/devextreme-reactive#2282]
### I'm using ...

React Grid

### Description

How to disable horizontal scroll When vertical scroll? Or disable vertical scroll When horizontal scroll?

View this demo: https://hpigw.csb.app/

When I scroll horizontally, I can also scroll vertically, I think this is a bad experience for the customer.

### Environment

- devextreme-reactive: 1.11.1

**Comment by LazyLahtak** [comment]
Hi @shangdev,

Unfortunately, we don't support this scenario.
If we can help you with anything else, please let us know.

**Comment by shangdev** [comment]
@LazyLahtak 

Can I detect table scroll event?

**Comment by LazyLahtak** [comment]
@shangdev,
 
You can detect scroll events by using your onScroll handler to override an onScroll property in VirtualTables's containerComponent. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-k75nd) of how to do that.
Let us know if this approach suits for you.
