### ISSUE TITLE
Pagination in Toolbar | Reactive Grid

### ISSUE THREAD

**Issue by waltervanwoudenberg** [DevExpress/devextreme-reactive#2285]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello,

I was wondering if there is an easy way to hook the pagination in the toolbar.
`dx-react-grid/src/plugins/paging-panel.tsx`
Right now it is:
```javascript
 <Template name="footer">
``` 
while I would like to have the same component in the toolbar like: 
```javascript 
<Template name="toolbarContent">
```

It seems to me that this is not an easy thing to do cos of the way the plugins are exported.
The `dx-react-grid-material-ui/src/templates/paging-panel/` are not being exported so if I want to recreate the component and hook it into the toolbar I have to copy/paste the templates and plugin file just to change one line of code to hook it into the toolbar.

**Comment by LazyLahtak** [comment]
Hi @waltervanwoudenberg ,
 
Creating your own plugin is the only way to redefine templates. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-q6v91) where we placed the PagingPanel into the template "toolbarContent".
If you have any questions, please let us know.
