### ISSUE TITLE
Selection Plugin State has issues

### ISSUE THREAD

**Issue by eprislac** [DevExpress/devextreme-reactive#2292]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I have a grid with multiple custom data type providers (datepicker, checkbox, email formatter) and multiple working plugins (filtering, paging, sorting) When I tried adding selection, Typescript refuses to compile, and gives me this error:
```
Type 'Dispatch<never[] | ((prevState: never[]) => never[])>' is not assignable to type '(selection: ReactText[]) => void'.
  Types of parameters 'value' and 'selection' are incompatible.
    Type 'ReactText[]' is not assignable to type 'never[] | ((prevState: never[]) => never[])'.
      Type 'ReactText[]' is not assignable to type 'never[]'.
        Type 'ReactText' is not assignable to type 'never'.
          Type 'string' is not assignable to type 'never'.  TS2322

    271 |             <SelectionState
    272 |               selection={selection}
  > 273 |               onSelectionChange={setSelection}
        |               ^
    274 |             />
    275 |             <PagingState
    276 |               defaultCurrentPage={0}
```

### Environment
- @devexpress/dx-react-core: ^2.0.3
- react: 16.8.6
- typescript: 3.5.2
- browser: none
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.1.3

**Comment by MaximKudriavtsev** [comment]
Hi @eprislac,

 Please try to define the `Array<number | string>` type for the `React.useState function`. See my [example](https://codesandbox.io/s/react-typescript-mto76).

**Comment by eprislac** [comment]
> Please try to define the `Array<number | string>` type for the `React.useState function`. See my [example](https://codesandbox.io/s/react-typescript-mto76).

Are you saying I have to set a default selection?

**Comment by MaximKudriavtsev** [comment]
@eprislac,

I mean that you should set your `React.useState's` type, please see the [example above](https://codesandbox.io/s/react-typescript-mto76). The selection can be an array without elements.

```js
const [selection, setSelection] = React.useState<Array<number | string>>([]);
...
<SelectionState
  selection={selection}
  onSelectionChange={setSelection}
/>
```
