### ISSUE TITLE
How to prevent VirtualTable fixed column header shaking?

### ISSUE THREAD

**Issue by shangdev** [DevExpress/devextreme-reactive#2296]
When use VirtualTable fixed column header, The head will shake when I slide the table, It seems that all the VirtualTable are like this.

Can you improve it?

**Comment by ushkal** [comment]
Hi @shangdev ,
 
Would you please clarify which browser and device you are using?

**Comment by shangdev** [comment]
@ushkal 

PC is normal.
Mobile is unusual.

E.g. Iphone 7, Huawei v8.

**Comment by shangdev** [comment]
demo: https://codesandbox.io/s/cranky-mcnulty-rygws
media: 
![gifhome_272x480_5s](https://user-images.githubusercontent.com/15621520/64186159-f14dae80-cea0-11e9-9285-ac6ab4191de3.gif)

**Comment by ushkal** [comment]
Thank you for the clarification. The issue is caused by the following [bug ](https://bugs.webkit.org/show_bug.cgi?id=197660)in a Webkit engine. Currently we can't provide you with any workaround.

**Comment by shangdev** [comment]
@ushkal 

Can table be fixed column header?

**Comment by ushkal** [comment]
@shangdev Currently we don't support this. Here's a ticket with a feature request where you can track our progress in this regard: [Fixed header without Virtual Scrolling](https://github.com/DevExpress/devextreme-reactive/issues/896).
