### ISSUE TITLE
Exception on expanding a group row if groupItems are not specified in SummaryState

### ISSUE THREAD

**Issue by npc144** [DevExpress/devextreme-reactive#2297]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Using this example : https://codesandbox.io/s/devextreme-react-grid-for-material-ui-iyn5l
After dragging the "city" column in the header for grouping and then expanding the first grouped rows, an error occur and the table become blank. The error thrown in the sandbox is 
"Cannot read property 'Aachen' of undefined". This only seems to happen for some rows.

### Expected Behaviour

The grouped rows should expands normally when used with summaries.

### Environment

- devextreme-reactive: 2.0.4
- react: 16.9.0
- browser: chrome
- material-ui: 4.4.0

**Comment by ushkal** [comment]
Hi @npc144 , 
 
Thank you for reporting the problem. We will fix it soon.
