### ISSUE TITLE
Ability to add color="primary" for checkbox on Material-UI

### ISSUE THREAD

**Issue by mrowe009** [DevExpress/devextreme-reactive#2301]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

It would be great to be able to add the ability to apply the color styling `"primary"` on the checkbox for the table component on the selections imported from Material-UI.

The use case for this would be to allow the checkbox to have the primary color of the theme, rather than the setting the secondary color, which in our case, is already set to a different color.

**Comment by AryamnovEugeniy** [comment]
Hello.

You can use solutions presented [here](https://github.com/DevExpress/devextreme-reactive/issues/933). You can override cellComponent of the TableSelection plugin. Does this meet your requirements?

**Comment by mrowe009** [comment]
I guess it does meet the requirement, but i just wish there was less of a manual approach to this. it will do for now, but maybe later on consider this in the future if/whenever more color accents appear in the table, it would be nice to adjust the color for all elements (not just the checkbox) the same way material-ui does it by just supplying the `color` property to plugins

**Comment by AryamnovEugeniy** [comment]
Hi again,

Our approach is to override components if we need to customize them. We want to preserve consistency in this case, so we're not planning to change our approach in the future.

If you have other questions, don't hesitate to contact us.
