### ISSUE TITLE
Need "onOperationsChange" event

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2303]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

With the FilteringState pluggin, we have "onFiltersChange" event. It is not triggered when the user change the operation (equals, contains, startWith, etc). I have operations (isEmpty and isNotEmpty) which would required me to set the filter value to something else than empty string when operation is set. Would it be possible to have an event "onOperationsChange" that I could use? I don't want the user to start typing something in the filter value to apply the "isEmpty" and "isNotEmpty" operations.

### Environment

- devextreme-reactive: 2.0.4
- react: 16.9.0
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.4.0

**Comment by LazyLahtak** [comment]
Hi @franciscailleAstus,

This functionality doesn't support our grid, but we will think about this feature. As a workaround you can do next: you can define you own cellComponent, to provide necessary properties (column.name and onChange) to children (filterSelectorComponent and editorComponent). Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-jxrgn) of how to do that.
Let us know if this solution meets you needs.

**Comment by franciscailleAstus** [comment]
Hi @LazyLahtak,
Thanks alot for the example ! Was exactly what I needed. :)

**Comment by LazyLahtak** [comment]
You are welcome!
