### ISSUE TITLE
How pass additional props to cellComponent

### ISSUE THREAD

**Issue by KirillYoYo** [DevExpress/devextreme-reactive#2308]
How I can pass additional props to cellComponent if this code is not valid:

`
<TableFilterRow cellComponent={(props) => <FilterCell additionalProps={'bla bla bla''} {...props} />} />
`

- in case https://github.com/DevExpress/devextreme-reactive/issues/2019

**Comment by LazyLahtak** [comment]
Hi @KirillYoYo ,
 
Your code has some mistakes. To define [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#properties) of TableFilterRow, you should return [TableFilterRow.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#plugin-components), not FilterCell. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-x2ylg).
Let us know if it meets your needs.
