### ISSUE TITLE
How to show skeleton in VirtualTable when user scrolling and data loading from memory

### ISSUE THREAD

**Issue by xap9i** [DevExpress/devextreme-reactive#2311]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

**Comment by xap9i** [comment]
TableRaw sceleton as one when using VirtualTableState and load data from remote data store

**Comment by ushkal** [comment]
Hi,
 
To implement your task, replace stub cells with skeleton cells using the following code: 
```
<VirtualTable
  stubCellComponent={VirtualTable.SkeletonCell}
 />
```
Please let me know if it helps.

**Comment by xap9i** [comment]
Yes, that's helped me, thanks.
