### ISSUE TITLE
Typescript error in React Chart Spline Area demo

### ISSUE THREAD

**Issue by stb1rd** [DevExpress/devextreme-reactive#2312]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour
[[DEMO] React Chart Spline Area](https://devexpress.github.io/devextreme-reactive/react/chart/demos/area/spline-area/)
```
<ArgumentScale factory={scalePoint} />
```
`factory` attribute can't be set with `scalePoint` because of typescript error:
`Type '{ (): ScalePoint<string>; <Domain extends { toString(): string; }>(): ScalePoint<Domain>; }' is not assignable to type 'FactoryFn'.`

### Expected Behaviour
`factory` attribute can be set with `scalePoint`

### Steps to Reproduce
[Codesandbox](https://codesandbox.io/s/dx-react-chart-example-area-wave-types-7cdd0)

### Environment
```
  "dependencies": {
    "@devexpress/dx-react-chart": "2.0.4",
    "@devexpress/dx-react-chart-material-ui": "2.0.4",
    "@devexpress/dx-react-core": "2.0.4",
    "@material-ui/core": "4.4.0",
    "@types/d3-scale": "2.1.1",
    "@types/d3-shape": "1.3.1",
    "d3-scale": "3.1.0",
    "d3-shape": "1.3.5",
    "react": "16.8.4",
    "react-dom": "16.8.4",
    "react-scripts": "2.1.3"
  },
  "devDependencies": {
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.2",
    "typescript": "3.3.3"
  },
```

**Comment by Krijovnick** [comment]
Hi @stb1rd 

Thank you for reporting the problem. We will fix it soon.
