### ISSUE TITLE
Can VirtualTable render a larger buffer?

### ISSUE THREAD

**Issue by calvinl** [DevExpress/devextreme-reactive#2315]
Hi there,

Is it possible to have `VirtualTable` render more rows ahead of just what's available in the current viewport? I can't seem to find an option like this.

**Comment by ushkal** [comment]
Hi @calvinl ,

We've already discussed this question in a context of this issue: #2085 .

**Comment by calvinl** [comment]
@ushkal thanks for responding. I'm wondering if you share the line in the source code that controls this? It would be helpful to do some testing on our own to see if it fits our use case better.

**Comment by ushkal** [comment]
[Here's](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-grid-core/src/utils/virtual-table.ts#L107) the line that controls the overscan rows count. I apologize for the late response.
