### ISSUE TITLE
dx-react-grid-bootstrap3 cellComponent  not working

### ISSUE THREAD

**Issue by sajidnetmeet** [DevExpress/devextreme-reactive#2319]
Im Using ASP.NET react, my dx-react-grid-bootstrap3 version is  "1.10.5". I have created a custom cell component to make my cell a hyperlink. but it is not working.

**Comment by LazyLahtak** [comment]
Hi @sajidnetmeet,
 
Could you please provide us with an example? This will help us research the issue and try to find a possible solution.

**Comment by sajidnetmeet** [comment]
import * as React from 'react';
import { RouteComponentProps } from 'react-router';
import { Template, TemplatePlaceholder, TemplateConnector } from '@devexpress/dx-react-core';
import { IntegratedFiltering, FilteringState, SearchState, GroupingState, IntegratedGrouping, DataTypeProvider, PagingState, IntegratedPaging } from '@devexpress/dx-react-grid';
import { Grid, Table, TableHeaderRow, TableFilterRow, Toolbar, SearchPanel, GroupingPanel, DragDropProvider, TableGroupRow, ColumnChooser, TableColumnVisibility, PagingPanel, TableColumnResizing, VirtualTable } from '@devexpress/dx-react-grid-bootstrap3';
import { axiosCall, exportTableToExcel, buildExportData, buildReportHeader, getCompanyDetails, CompanyDetails, getPaginationPanelMsg, getTimeForSelectedTimeZone, dateTimeFormat, initialLoadingInfoComponent, reportEmptyGroupMessage, DateTypeProvider, exportSelectorForDateTimeField, IFilterOperation, getLocalizationMessages, getIconComponent, dtBetweenSelector, dtBetweenPredicate, getNumberFilterOperations, nmBetweenSelector, nmBetweenPredicate, CurrencyTypeProvider } from '../common/common';
import { ToastContainer, ToastMessageAnimated } from 'react-toastr';
import { ClipLoader } from 'react-spinners';
import * as moment from 'moment';
import * as Datetime from 'react-datetime';
import * as UserStore from '../../store/UserStore';
import { ApplicationState } from '../../store';
import { connect } from 'react-redux';
import { Popover, OverlayTrigger } from 'react-bootstrap';
import { ReportsDateRangeClearGroupingSection } from './ReportsDateRangeClearGroupingSection';
import { toastrSuccessTitle, toastrWarningTitle, EnterValidDate, EnterValidDateRange } from '../validations/messages';
import { NavLink, Link } from 'react-router-dom';
let container: any;
let currentTime: any = '';
const classWithErrors = 'input-style w-100 input_error autocomplete-div';
const classWithoutErrors = 'input-style w-100 autocomplete-div';
const dateColumns = ['createdOn', 'viewingDateTime'];
const numColumns = ['leadId', 'leadRequirementId', 'budget'];
const currencyColumns = ['budget'];

let endDate = new Date();
endDate.setDate(endDate.getDate() - 30);

interface AgeAnalysisReportState {
    rows: Array<any>;
    columns: Array<any>;
    filters: Array<any>;
    loading: boolean;
    filteringColumnExtensions: Array<any>;
    currentFilterOperation: string;
    betweenFilter: Array<any>;
    isDateTimeValid: boolean;
    defaultExpandedRowIds: Array<string>;
    exportData: Array<any>;
    hiddenColumnNames: Array<string>;
    currentCompany: CompanyDetails;
    currentPageIndex: number;
    currentPageSize: number;
    isInitialLoading: boolean;
    groupings: Array<any>;
    defaultColumnWidths: Array<any>;
    tableColumnExtensions: Array<any>;
    currentDateFilterOperations: Array<IFilterOperation>;
    currentNumFilterOperations: Array<IFilterOperation>;
    startDate: Date;
    endDate: Date;
}


const Cell = (props) => {
    debugger;
    const { column } = props;
    debugger
    if (column.name === 'propertyName') {
        debugger
        if (props.value != null) {
            return <td> <NavLink to={'/AgeAnalysisBreakdownReport/' + props.value} >{props.value}</NavLink></td>;
        }
        else {
            return <td>Age Analysis</td>;
        }
    }
    return <Table.Cell {...props} />;
};



type UserStore = Partial<UserStore.UserState> & RouteComponentProps<{}>;
class AgeAnalysisReport1 extends React.Component<UserStore, AgeAnalysisReportState>{
    exportData: Array<any> = [{ 'data': 'some data' }];
    hiddenColumnNames: Array<string> = [];
    isPrintBtnClicked: boolean = false;

    componentDidMount() {
        this.loadData();
        getCompanyDetails(this.props.branchId, this.handleCompanyDetails, container);
        getTimeForSelectedTimeZone(this.updateTimeZoneTime, container);
    }

    updateTimeZoneTime = (data: any) => {
        currentTime = moment(data.data).format(dateTimeFormat);
    }


    handleCompanyDetails = (data: any) => {
        this.setState({ currentCompany: data.data as CompanyDetails });
    }

    loadData = () => {
        var params = {
            startDate: moment(this.state.startDate).format(dateTimeFormat),
            endDate: moment(this.state.endDate).format(dateTimeFormat)
        }
        axiosCall('get', '/BIReport/GetAgeAnalysisReportData', params, (data) => this.handleDataReceivedFromServer(data.data), null, (data) => { this.setState({ loading: false }) }, container);

        this.setState({ loading: true });
        
    }

    handleDataReceivedFromServer = (data) => {
        this.setState({ rows: data, loading: false });
        //expand the records
        this.expandRecords();
    }


    expandRecords = () => {
        const arr: Array<string> = [];
        for (let i = 0; i < this.exportData.length; i++) {
            if (this.exportData[i]['compoundKey']) {
                arr.push((this.exportData[i]['compoundKey']).toString());
            }
        }
        this.setState({ defaultExpandedRowIds: arr });
    }

    constructor(props: any) {
        super(props);

        

        this.state = {
            columns: [
                {
                    name: 'propertyName',
                    title: 'Property Name'
                    
                },                
                { name: 'totalOutstanding', title: 'Total Outstanding' },
                { name: 'first30Days', title: '1 To 30 Days' },
                { name: 'first60Days', title: '31 To 60 Days' },
                { name: 'first90Days', title: '61 To 90 Days' },
                { name: 'older', title: 'Older' },
                
            ],
            rows: [],
            currentFilterOperation: 'dtBetween',
            betweenFilter: [],
            filters: [],
            loading: true,
            filteringColumnExtensions: [
                //{
                //    columnName: 'viewingDateTime',
                //    predicate: (value, filter, row) => {
                //        dtBetweenPredicate(value, filter)
                //    }
                //},
                //{
                //    columnName: 'createdOn',
                //    predicate: (value, filter, row) => dtBetweenPredicate(value, filter)
                //},
                //{
                //    columnName: 'leadId',
                //    predicate: (value, filter, row) => nmBetweenPredicate(value, filter)
                //},
                //{
                //    columnName: 'leadRequirementId',
                //    predicate: (value, filter, row) => nmBetweenPredicate(value, filter)
                //},

            ],
            isDateTimeValid: true,
            defaultExpandedRowIds: [],
            exportData: [],
            hiddenColumnNames: [],
            currentCompany: {
                companyId: 0,
                companyName: "",
                address: "",
                phone: "",
                fax: "",
                email: "",
                logoImage: '',
                logoPath: ""
            },
            currentPageIndex: 0,
            currentPageSize: 100,
            isInitialLoading: true,
            groupings: [],
            defaultColumnWidths: [
                { columnName: 'propertyName', width: 180 },
                { columnName: 'totalOutstanding', width: 180 },
                { columnName: 'first30Days', width: 180 },
                { columnName: 'first60Days', width: 180 },
                { columnName: 'first90Days', width: 180 },
                { columnName: 'older', width: 180 },
                
            ],
            tableColumnExtensions: [
                { columnName: 'first30Days', align: 'right' },
                { columnName: 'first60Days', align: 'right' },
                { columnName: 'first90Days', align: 'right' },
                { columnName: 'older', align: 'right' },
                { columnName: 'totalOutstanding', align: 'right' },
            ],
            currentDateFilterOperations: dateColumns.map(prop => ({ colName: prop, filterOperation: 'dtBetween' })),
            currentNumFilterOperations: numColumns.map(prop => ({ colName: prop, filterOperation: 'numBetween' })),
            startDate: endDate,
            endDate: new Date()
        };

        this.exportBtnClick = this.exportBtnClick.bind(this);
        this.expandRecords = this.expandRecords.bind(this);
        this.handleCompanyDetails = this.handleCompanyDetails.bind(this);
        this.updateTimeZoneTime = this.updateTimeZoneTime.bind(this);
        this.betweenEditorValueChanged = this.betweenEditorValueChanged.bind(this);
        this.nmBetweenEditorValueChanged = this.nmBetweenEditorValueChanged.bind(this);
    }

    exportBtnClick = () => {
        this.setState({ exportData: this.exportData, hiddenColumnNames: this.hiddenColumnNames }, () => {
            exportTableToExcel("tblExport", "Age Analysis Report");
        });

    }

    printBtnCLickHandler = () => {
        this.isPrintBtnClicked = true;
        this.expandRecords();
    }


    betweenEditorValueChanged(value, index, column) {
        const { currentFilterOperation } = this.state;
        const { filters } = this.state;
        const viewingDateFilterIndex = filters.findIndex(i => i.columnName === "viewingDateTime");
        const createdDateFilterIndex = filters.findIndex(i => i.columnName === "createdOn");
        let nextValue = value;
        nextValue = value == '' ? undefined : moment(value).isValid() ? nextValue : undefined;
        const nextFilters = this.state.filters.slice();
        if (viewingDateFilterIndex === -1 && column == "viewingDateTime") {
            nextFilters.push({
                columnName: "viewingDateTime",
                value: [nextValue, undefined],
                operation: currentFilterOperation
            });
        } else if (viewingDateFilterIndex !== -1 && column == "viewingDateTime") {
            nextFilters[viewingDateFilterIndex].value[index] = nextValue;
        }
        if (createdDateFilterIndex === -1 && column == "createdOn") {
            nextFilters.push({
                columnName: "createdOn",
                value: [nextValue, undefined],
                operation: currentFilterOperation
            });
        } else if (createdDateFilterIndex !== -1 && column == "createdOn") {
            nextFilters[createdDateFilterIndex].value[index] = nextValue;
        }

        this.setState({ filters: nextFilters });
    }

    nmBetweenEditorValueChanged(value, index, column) {
        const { currentNumFilterOperations } = this.state;
        let { filters } = this.state;
        const createdOnFilterIndex = filters.findIndex(i => i.columnName === column);

        let nextValue = value;
        nextValue = value === '' ? undefined : value;
        const nextFilters = this.state.filters.slice();

        const ggg = currentNumFilterOperations.find(ind => ind.colName == column);

        if (createdOnFilterIndex === -1) {
            nextFilters.push({
                columnName: column,
                value: [nextValue, undefined],
                operation: ggg.filterOperation
            });
        } else {
            if (nextFilters[createdOnFilterIndex].value == undefined) {
                const vall = Array<string>(2);
                vall[index] = nextValue;
                nextFilters[createdOnFilterIndex].value = vall;
            } else {
                nextFilters[createdOnFilterIndex].value[index] = nextValue;
            }
        }

        this.setState({ filters: nextFilters });
    }

    filterCell = ({ column, ...restProps }: TableFilterRow.CellProps) => {
        const { currentDateFilterOperations, filters, currentNumFilterOperations } = this.state;

        const columnIndex = filters.findIndex(i => i.columnName === column.name);
        let currFilterOp: IFilterOperation;

        //datetime filtering
        if (dateColumns.indexOf(column.name) > -1) {

            currFilterOp = currentDateFilterOperations.find(val => val.colName === column.name);

            return (<TableFilterRow.Cell column={column} {...restProps}>
                {<TableFilterRow.FilterSelector
                    availableValues={exportSelectorForDateTimeField}
                    value={currFilterOp.filterOperation}
                    getMessage={getLocalizationMessages}
                    onChange={filterOperation => {
                        restProps.onFilter({ columnName: column.name, operation: filterOperation });
                        const inx = currentDateFilterOperations.indexOf(currFilterOp);
                        currFilterOp.filterOperation = filterOperation;
                        currentDateFilterOperations[inx] = currFilterOp;
                        this.setState({
                            currentDateFilterOperations,
                            filters: []
                        });
                    }}
                    toggleButtonComponent={({ ...props }: TableFilterRow.ToggleButtonProps) => <TableFilterRow.ToggleButton className="report-button"{...props} />}
                    iconComponent={getIconComponent}
                    disabled={false}
                />}
                {currFilterOp.filterOperation === 'dtBetween' ?
                    dtBetweenSelector(column.name, this.betweenEditorValueChanged)
                    : (
                        <TableFilterRow.Editor
                            getMessage={() => "Filter..."}
                            value={columnIndex === -1 ? '' : filters[columnIndex].value}
                            onChange={(val) => {
                                restProps.onFilter({
                                    columnName: column.name,
                                    value: val,
                                    operation: currFilterOp.filterOperation
                                });
                                const ss = this.state.filters;
                                if (columnIndex === -1) {
                                    ss.push({
                                        columnName: column.name,
                                        value: val,
                                        operation: currFilterOp.filterOperation
                                    });
                                } else {
                                    ss[columnIndex].value = val;
                                }
                                this.setState({ filters: ss })
                            }
                            }
                            disabled={false}
                            className="report-filter"
                        />
                    )}
            </TableFilterRow.Cell>);

        }

        //numeric field filtering
        else if (numColumns.indexOf(column.name) > -1) {

            currFilterOp = currentNumFilterOperations.find(val => val.colName === column.name);

            return (<TableFilterRow.Cell column={column} {...restProps}>
                {<TableFilterRow.FilterSelector
                    availableValues={getNumberFilterOperations}
                    value={currFilterOp.filterOperation}
                    getMessage={getLocalizationMessages}
                    onChange={filterOperation => {
                        restProps.onFilter({ columnName: column.name, operation: filterOperation });
                        const inx = currentNumFilterOperations.indexOf(currFilterOp);
                        currFilterOp.filterOperation = filterOperation;
                        currentNumFilterOperations[inx] = currFilterOp;
                        this.setState({
                            currentNumFilterOperations,
                            filters: []
                        });
                    }}
                    toggleButtonComponent={({ ...props }: TableFilterRow.ToggleButtonProps) => <TableFilterRow.ToggleButton className="report-button"{...props} />}
                    iconComponent={getIconComponent}
                    disabled={false}
                />}
                {currFilterOp.filterOperation === 'numBetween' ?
                    nmBetweenSelector(column.name, this.nmBetweenEditorValueChanged)
                    : (
                        <TableFilterRow.Editor
                            getMessage={() => "Filter..."}
                            value={columnIndex === -1 ? '' : filters[columnIndex].value}
                            onChange={(val) => {
                                const ind = currentNumFilterOperations.find(val => val.colName === column.name);

                                restProps.onFilter({
                                    columnName: column.name,
                                    value: val,
                                    operation: ind.filterOperation
                                });

                            }}
                            disabled={false}
                            className="report-filter"
                        />
                    )}
            </TableFilterRow.Cell>);
        }

        return <TableFilterRow.Cell column={column} {...restProps} className="drag-drop-border" />
    }


    applyFilterBtnHandler = (startDate: Date, endDate: Date) => {
        if (!this.state.loading) {
            this.setState({ loading: true, isInitialLoading: false }, () => {
                this.setState({ startDate: startDate, endDate: endDate }, () => {
                    this.loadData();
                })
            })
        }
    }

    //function to handle clear groupings
    clearGroupings = () => {
        this.setState({ groupings: [] })
    }

   
    public render() {
        let { rows, columns, filters, loading, filteringColumnExtensions, defaultExpandedRowIds } = this.state;

        return <div>
            <div className="d-flex col-12 col-md-12">
                <h3 className="report-heading report-heading-responsive col-12 col-md-12 printIgnore">Age Analysis Report</h3>
            </div>
            <div className="container-fluid p-0 px-4 printIgnore">
                <div className="d-flex  top-border-title">
                </div></div>
            <div className="export-print-button report-buttons-reponsive col-md-12 printIgnore">
                <span className="col-md-12 export-to-excel export-to-excel-response printIgnore note-text">Print or Export To Excel applies to contents visible to the current page</span>
                <a className="export-excel" data-tooltip="Export To Excel" data-placement="left"> <img src="dist/images/export-excel.png" style={{ width: 25, height: 25, cursor: 'pointer', marginRight: 10, marginTop: -7 }} onClick={() => this.exportBtnClick()} /></a>
                <span className="report-buttons-reponsive mx-2">
                    <a className="print" data-tooltip="Print" data-placement="bottom" onClick={() => this.printBtnCLickHandler()}><i className="fa fa-print" style={{ cursor: 'pointer', fontSize: 21 }} aria-hidden="true"></i></a></span>
            </div>
            {buildReportHeader('Age Analysis Report 2019', this.state.currentCompany.companyName, this.state.currentCompany.address, this.state.currentCompany.logoPath, currentTime)}

            <ReportsDateRangeClearGroupingSection
                applyFilterHandler={this.applyFilterBtnHandler}
                clearGroupingHandler={this.clearGroupings}
                groupLength={this.state.groupings.length}
                startDate={this.state.startDate}
                endDate={this.state.endDate}
                container={container}
                loading={this.state.loading}
            />
            <Grid
                rows={rows}
                columns={columns}>

                <DateTypeProvider
                    for={dateColumns}
                />
                <CurrencyTypeProvider
                    for={currencyColumns}
                />
                <FilteringState
                    filters={filters}
                    onFiltersChange={(filters) => this.setState({ filters })}
                />
                <PagingState
                    defaultCurrentPage={0}
                    defaultPageSize={100}
                    currentPage={this.state.currentPageIndex}
                    pageSize={this.state.currentPageSize}
                />
                <IntegratedPaging />
                <SearchState />
                <IntegratedFiltering columnExtensions={filteringColumnExtensions} />
                <DragDropProvider />

                <GroupingState
                    onGroupingChange={(props) => {
                        this.setState({ groupings: props }, () => {
                            setTimeout(() => {
                                for (let i = 0; i < props.length; i++) {
                                    this.expandRecords();
                                }
                            }, 1000);
                        });
                    }}
                    //defaultGrouping={[{ columnName: 'leadId' }]}
                    expandedGroups={defaultExpandedRowIds}
                    defaultExpandedGroups={defaultExpandedRowIds}
                    grouping={this.state.groupings}
                    onExpandedGroupsChange={groups => {
                        this.setState({ defaultExpandedRowIds: groups });
                    }}
                />
                <IntegratedGrouping />
                <Table
                    cellComponent={Cell}
                    columnExtensions={this.state.tableColumnExtensions}
                    bodyComponent={(
                    
                        { ...props }: Table.DataRowProps) => <Table.TableBody className="font-13" {...props} />}
                  
                />
               
                <VirtualTable />
                <TableColumnResizing defaultColumnWidths={this.state.defaultColumnWidths} />
                <TableHeaderRow
                    cellComponent={({ ...props }: TableHeaderRow.CellProps) => <TableHeaderRow.Cell className="drag-drop-border" {...props} />}
                    titleComponent={({ ...props }: TableHeaderRow.ContentProps) => <TableHeaderRow.Content className="report-header" {...props} />}
                />
                <PagingPanel
                    pageSizes={[100, 500, 1000]}
                    containerComponent={(props) =>
                        <PagingPanel.Container
                            className='printIgnore page-nav' {...props}
                            getMessage={(msg: string, parameters?: { from: number, to: number, count: number }) => getPaginationPanelMsg(msg, parameters)}
                            onCurrentPageChange={(pgNumber) => {
                                this.setState({ currentPageIndex: pgNumber });
                                setTimeout(() => {
                                    this.expandRecords();
                                }, 1000);
                            }}
                            onPageSizeChange={(pgSize) => {
                                this.setState({ currentPageSize: pgSize });
                                setTimeout(() => {
                                    this.expandRecords();
                                }, 1000);
                            }}
                        />} />
                <TableGroupRow contentComponent={({ ...props }: TableGroupRow.ContentProps) => <TableGroupRow.Content className="font-13" {...props} />} />
                <TableColumnVisibility columnTogglingEnabled={true} />
                <TableFilterRow
                    toggleButtonComponent={({ ...props }: TableFilterRow.ToggleButtonProps) => <TableFilterRow.ToggleButton className="report-button" {...props} />}
                    iconComponent={({ ...props }: TableFilterRow.IconProps) => <TableFilterRow.Icon className="report-icon" {...props} />}
                    //editorComponent={({ ...props }: TableFilterRow.EditorProps) => <TableFilterRow.Editor className="report-filter" {...props} />}
                    showFilterSelector
                    cellComponent={this.filterCell}
                //rowComponent={(props: Table.RowProps) => <TableFilterRow.Row className='printIgnore' {...props} />}

                />
                <Toolbar rootComponent={({ ...props }: Toolbar.RootProps) => <Toolbar.Root className="drag-drop-panel" {...props} />} />
                <GroupingPanel
                    containerComponent={(props: GroupingPanel.ContainerProps) => <GroupingPanel.Container className='grouping-panel-container' {...props} />}
                    showGroupingControls={true}
                    messages={{ 'groupByColumn': reportEmptyGroupMessage }}
                    itemComponent={({ ...props }: GroupingPanel.ItemProps) => <GroupingPanel.Item className="drag-drop-border lead-report-drag" {...props} />} />
                <ColumnChooser
                    toggleButtonComponent={(props: ColumnChooser.ToggleButtonProps) => <ColumnChooser.ToggleButton className='printIgnore' {...props} />}
                    containerComponent={({ ...props }: ColumnChooser.ContainerProps) => <ColumnChooser.Container className="font-12" {...props} />}
                />
                <SearchPanel inputComponent={(props: SearchPanel.InputProps) => <SearchPanel.Input className='printIgnore report-search-responsive search' {...props} />} />
                <Template name="root">
                    <TemplatePlaceholder />
                    <TemplateConnector>
                        {({ rows, hiddenColumnNames }) => {
                            this.exportData = rows;
                            this.hiddenColumnNames = hiddenColumnNames;
                            //if (this.state.loading) {
                            //    this.setState({ loading:false });
                            //}

                            if (this.isPrintBtnClicked) {
                                this.isPrintBtnClicked = false;
                                //printElem('table');
                                setTimeout(() => { window.print() }, 100);
                                //window.print();
                            }
                            return null;
                        }}
                    </TemplateConnector>
                </Template>

            </Grid>
            <div className="dev-report-loader"><ClipLoader color={'#000'} loading={this.state.loading} /></div>

            {buildExportData(this.state.hiddenColumnNames, this.state.columns, this.state.exportData, this.state.currentCompany.companyName, this.state.currentCompany.address)}

            <ToastContainer
                ref={ref => container = ref}
                className="toast-top-right"
                toastMessageFactory={React.createFactory(ToastMessageAnimated)} />
        </div>
    }
}

export default connect((state: ApplicationState) => state.user)(AgeAnalysisReport1) as typeof AgeAnalysisReport1;

**Comment by sajidnetmeet** [comment]
Above is my code, in this the cellComponents cell value is not giving me the hyper link

**Comment by LazyLahtak** [comment]
@sajidnetmeet ,

Thank you for your example! I tried to create a [project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-wj2ok) in the sandbox where I pass NavLink to cellComponent. Please, let us know if that solution suits you. If it doesn't meet your requirements, please, provide us a runnable project in the sandbox or modify the example I attached.

**Comment by sajidnetmeet** [comment]
I have copied the same code which you have given to my solution, but still it is not working. Is there any version we will be using in dx-react-grid-bootstrap3 or any other components?

**Comment by sajidnetmeet** [comment]
Hi, I have found the issue. The issue is that I am using <VirtualTable/> for scrolling, so that the cellComponent not working. I need both hyperlink cell and Virtual Table. How can I achieve this?

**Comment by sajidnetmeet** [comment]
Hi, I think adding the cellComponenet within the VirtualTable will do the work.
Thank you very much for the help.

**Comment by LazyLahtak** [comment]
@sajidnetmeet,

I just noticed that you were using the Virtual Table with the Table. The Virtual Table already uses the Table.
If you have any further questions, let us know.
