### ISSUE TITLE
How to make less marks on the x axis?

### ISSUE THREAD

**Issue by Megoos** [DevExpress/devextreme-reactive#2335]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

I have a chart, and the labels on the x axis, but I get the incorrect axis for me. Please help me make less marks on the x axis (e.g. 4 or 5 marks). From the [documentation](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-scale/#scaleobject) I do not understand how to do this. I would be grateful if you show an example.
![image](https://user-images.githubusercontent.com/9866017/64991366-69bd6200-d8da-11e9-82ec-09f59b2d7f44.png)

```
<Chart data={data} rotated={true} height={250} width={320}>
	<ArgumentAxis /> 
	<ValueAxis /> 
	<ValueScale factory={???}/> 
	<BarSeries 
		valueField="count" 
		argumentField="title" 
		color="#004ccc80" 
		pointComponent={props => ( <BarSeries.Point {...props} maxBarWidth={5} rx="2" ry="2" /> )}
	 /> 
	<EventTracker /> 
	<Tooltip /> 
	<Animation /> 
</Chart>
```

### Environment

- @devexpress/dx-react-chart: 2.0.4
- @devexpress/dx-react-chart-material-ui: 2.0.4
- @devexpress/dx-react-core: 2.0.4
- d3-scale: 3.1.0
- react: 16.8.4
- material-ui: 4.4.0
- browser: Chrome latest
- bootstrap: none
- react-bootstrap: none

**Comment by Krijovnick** [comment]
Hi @Megoos 

We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/2306).
