### ISSUE TITLE
dx-react-grid-bootstrap3 Cell Click Event

### ISSUE THREAD

**Issue by sajidnetmeet** [DevExpress/devextreme-reactive#2337]
Hi, 
How can I trigger a click event in dx-react-grid-bootstrap3 ?

**Comment by LazyLahtak** [comment]
Hi @sajidnetmeet,

To trigger a click event by click on a component, you need to pass the component by using the onClick property. For example, if you want to trigger the event by a click on a cell, pass a Cell with the onClick property to the cellComponent property in the Table (VirtualTable). Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-eltrl) of how to do that.
Let us know if it meets your needs.

**Comment by sajidnetmeet** [comment]
Yes, thank you. up to that part I have already figured out. Im Using ReactJS / Typescript. What I have to do is when a Column (ID) is clicked, I need to call a function which is already there. As the function is within the exported class, how can I access it. when i type "this." the function name is not populated.

**Comment by LazyLahtak** [comment]
@sajidnetmeet,
If you need that the component gets access to class functions, you need to define that component in the class and bind it. Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-c3kz1), where a Cell is defined in the class.
If you have any further questions, let us know.
