### ISSUE TITLE
Delete issue of scheduler editing demos

### ISSUE THREAD

**Issue by yueerchen** [DevExpress/devextreme-reactive#2339]
- I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- React Scheduler

### Current Behaviour

The first created appointment with id = 0 can not be deleted due to the criteria of if(deleted).
It can be changed to if(deleted >= 0) to address the issue

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @yueerchen,

Thank you for reporting the problem. We will fix it soon.

**Comment by MaximKudriavtsev** [comment]
Fixed by [PR](https://github.com/DevExpress/devextreme-reactive/commit/1e837eb95676bc5656ef0f4ee4648143a08b3679)
