### ISSUE TITLE
Problem w/ editing when using VirtualTableView

### ISSUE THREAD

**Issue by ddmedeiros** [DevExpress/devextreme-reactive#234]
When i click edit on a row  when using VirtualTableView the edit column seems to lose its width and all other columns are pushed to the left of the table, my component construction seems to work fine when using regular TableView though.

**Comment by kvet** [comment]
Hi,

I've noticed the issue. In the meantime, I suggest you use the following workaround:

Provide a custom editCellTemplate for the TableEditRow plugin. It should pass the style property to the root cell element.

Here is an example of a template that receives the style property: https://github.com/DevExpress/devextreme-reactive/blob/v1.0.0-alpha.6/packages/dx-react-demos/src/bootstrap3/featured-controlled-mode/demo.jsx#L202

Here is an example of specifying the editCellTemplate property: https://github.com/DevExpress/devextreme-reactive/blob/v1.0.0-alpha.6/packages/dx-react-demos/src/bootstrap3/featured-controlled-mode/demo.jsx#L275

**Comment by kvet** [comment]
I've checked the proposed workaround and found that it is not working in 1.0.0-alpha.6. It is not currently possible to workaround the issue. I apologize for the inconvenience.

**Comment by leandro-silva-me** [comment]
> I've noticed the issue. In the meantime, I suggest you use the following workaround

So, since it is closed, i will guess that the solution is still to use the workaround right?

But the bug still exists, is any issue for it? And if there isnt, this issue should had been closed?

**Comment by kvet** [comment]
Hi,

The proposed workaround is not working. The issue has been fixed. The fix is merged to the master branch. It will be available with the next release soon.
