### ISSUE TITLE
How can you trigger the edit table without using the default edit row column button? 

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2343]
I need a way to trigger the edit row with a custom button. Ideally the button triggers the edit state on the whole table but if I get a way to trigger the edit state on its own it will be enough for now

**Comment by LazyLahtak** [comment]
Hi @paufar,
 
To trigger edit state on the whole table, you should use the editingRowIds property of the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/#properties) plugin. To apply changes, you should define the rowChanges property and call the commitChanges function with rowChanges manually.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0nxqz) illustrating how to do that.
Let us know if it meets your needs.

**Comment by paufar** [comment]
Thanks! Managed to do it but struggling with the changes. Is there an example using classes? @LazyLahtak

**Comment by LazyLahtak** [comment]
@paufar,

Here is updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-22rb9) using classes.

**Comment by paufar** [comment]
Thanks @LazyLahtak ! appreciate the help
