### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined adter update to 2.0.5

### ISSUE THREAD

**Issue by nihhwo** [DevExpress/devextreme-reactive#2346]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

### Current Behaviour
After updating devexpress dependencies (devexpress/dx-react-core, devexpress/dx-react-grid and dx-react-grid-material-ui) from 2.0.4 to 2.0.5 the following probem exists in node_modules/@devexpress/dx-grid-core/dist/dx-grid-core.es.js:

TypeError: Cannot read property 'name' of undefined

![image](https://user-images.githubusercontent.com/42541373/65334101-0d03c500-dbc2-11e9-81cb-294127e13756.png)

### Environment
- react: 16.9.0
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.4.2

**Comment by LazyLahtak** [comment]
Hi @nihhwo ,
 
Thank you for your report. Could you please provide us with your code? This will help us solve this problem.

**Comment by LazyLahtak** [comment]
@nihhwo ,

We've fixed the issue for a scenario when some columns that are not contained in the Grid's columns property are added at the center or end of the table. Please let us know if your case is different.

![image](https://user-images.githubusercontent.com/43685423/65518159-823a0780-deec-11e9-92e2-2f9c7d65417e.png)

**Comment by nihhwo** [comment]
Hi @LazyLahtak,

**Comment by LazyLahtak** [comment]
@nihhwo,
 
Thank you for your response. The fix will be available in the nearest release.
