### ISSUE TITLE
devextreme-reactive vs devextreme-react

### ISSUE THREAD

**Issue by j209** [DevExpress/devextreme-reactive#2347]
Hi
What is different between [devextreme-reactive](https://github.com/DevExpress/devextreme-reactive) and [devextreme-react](https://github.com/DevExpress/devextreme-react)?

**Comment by MaximKudriavtsev** [comment]
Hi @j209,

We have already registered a similar [issue](https://www.devexpress.com/Support/Center/Question/Details/T811071/devextreme-react-vs-devextreme-reactive).
