### ISSUE TITLE
Filter Boolean values in Column

### ISSUE THREAD

**Issue by sajidnetmeet** [DevExpress/devextreme-reactive#2349]
Hi, 
I am using ReactJS typescript with dx-react-grid-bootstrap3, in which the Boolean column is displayed NO if false and YES if true.
How can I filter the column by typing YES / NO in the filter option. When I try to type TRUE / FALSE it filters correctly.

**Comment by LazyLahtak** [comment]
Hi @sajidnetmeet,
 
You may use [editorComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/#datatypeprovidervalueeditorprops) of the DataTypeProvider plugin to create custom editors for the whole column. This also applies to the editor in TableFilterRow's Cell. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-3-nib7c) illustrating how to do that.
Please let us know if this solution meets your requirements.

**Comment by sajidnetmeet** [comment]
Hi Thank you for the reply. But I am using react type script. So in <option> I cannot add value = {true} as it says type true cannot be added to string...

**Comment by LazyLahtak** [comment]
@sajidnetmeet,

The `value` field in `select` and `option` HTML elements has the `string | numer | string[] | undefined` type. This type cannot be redefined. You may convert the boolean type into a string (true -> "true", false -> "false") or number (true -> 1, false -> 0).
If you have further questions, please let us know.
