### ISSUE TITLE
cellComponent changes are not being applied while using custome buttons using commandComponent

### ISSUE THREAD

**Issue by rpinto070615** [DevExpress/devextreme-reactive#2350]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I'm using React Grid of @devexpress/dx-react-grid-bootstrap4 and using custom buttons with the help of commandComponent in TableEditColumn. I'm trying to disable the commit button by using cellComponent. But it doesn't work if I use commandComponent. The disabling works fine if I'm using the default New/Save/Cancel button. 

### Expected Behaviour
cellComponent behaviour works fine when using commandComponent.

### Steps to Reproduce

Grid
   TableEditColumn
          showAddCommand
          showEditCommand
          showDeleteCommand
          commandComponent={Command}
          cellComponent={props.editCol}
     
Grid
--------------------------------------------------------------------------
const CommandButton = ({ onExecute, icon, text, hint, color }: any) => (
  <button
    type="button"
    className="btn btn-link dx-g-bs4-table-edit-command-cell"
    style={{ padding: 11 }}
    title={hint}
    onClick={e => {
      onExecute();
      e.stopPropagation();
    }}
  >
    <span className={color || "undefined"}>
      {icon ? (
        <i className={`oi oi-${icon}`} style={{ marginRight: text ? 5 : 0 }} />
      ) : null}
      {text}
    </span>
  </button>
);

const AddButton = ({ onExecute }: any) => (
  <CommandButton
    icon="plus"
    text="New"
    hint="Create new row"
    onExecute={onExecute}
  />
);

const EditButton = ({ onExecute }: any) => (
  <CommandButton
    icon="pencil"
    text="Edit"
    hint="Edit row"
    color="text-warning"
    onExecute={onExecute}
  />
);

const DeleteButton = ({ onExecute }: any) => (
  <CommandButton
    icon="trash"
    hint="Delete row"
    color="text-danger"
    onExecute={() => {
      if (window.confirm("Are you sure you want to delete this row?")) {
        onExecute();
      }
    }}
  />
);

const CommitButton = ({ id, onExecute }: any) => (
  <CommandButton
    text="Save"
    icon="check"
    hint="Save changes"
    color="text-success"
    onExecute={onExecute}
  />
);

const CancelButton = ({ onExecute }: any) => (
  <CommandButton
    icon="x"
    hint="Cancel changes"
    color="text-danger"
    onExecute={onExecute}
    isDanger
  />
);

const commandComponents = {
  add: AddButton,
  edit: EditButton,
  delete: DeleteButton,
  commit: CommitButton,
  cancel: CancelButton
};

export const Command = ({ id, onExecute }: any) => {
  const ButtonComponent = commandComponents[id];
  return <ButtonComponent onExecute={onExecute} />;
};
--------------------------------------------------------------
const EditCol = (props: any) => {
  if (
    (!props.row.account || props.row.account === "") &&
    props.tableRow.type === TableEditRow.ADDED_ROW_TYPE
  ) {
    return (
      <TableEditColumn.Cell {...props}>
        {React.Children.map(props.children, child =>
          child
            ? (child.props.id === 'commit'
              ? React.cloneElement(child, { disabled: true })
              : child)
            : false
        )}
      </TableEditColumn.Cell>
    );
  }
  return <TableEditColumn.Cell {...props} />;
};

### Environment

- devextreme-reactive: @devexpress/dx-react-grid-bootstrap4
- react: 16.8.2
- browser: chrome
- bootstrap: 4
- react-bootstrap: 1.0.0-beta.5
- material-ui: none
- using react-hooks

**Comment by LazyLahtak** [comment]
Hi @rpinto070615,
 
I've researched your code and created an [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-1p27k) for you. As far as I understand, you need to provide the `disabled` property in the `CommandButton` component to disable the command.
Please let us know if the solution shown in the sample meets your needs.

**Comment by rpinto070615** [comment]
Hello @LazyLahtak, THANKYOU SO MUCH for your help! I somehow forgot the disabled property to be added to the button. thanks a lot for your help! The sample met my need exactly.

**Comment by LazyLahtak** [comment]
You are welcome!
