### ISSUE TITLE
Dragover over row

### ISSUE THREAD

**Issue by ronaiza-cardoso** [DevExpress/devextreme-reactive#2357]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description
Is it possible to implement Dragover (of a file) over a row? I need to make upload of files, so when the user makes the dragover of a file over a row the table should trigger a function that give me information about the row that the document was being dragged and the file itself.

Here I have my current implementation of the table: https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-tree-view-with-link-yjzdy

**Comment by ushkal** [comment]
Hi @ronaiza-cardoso,
 
To implement this task you need to override the [Table](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/) plugin's [rowComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablerow) property with your own component that handles drag-and-drop events. Use this sample [project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-lhst5) for your reference.
