### ISSUE TITLE
Export data in Excel format in Reactive Grid

### ISSUE THREAD

**Issue by ushkal** [DevExpress/devextreme-reactive#2366]
# The Problem
Users cannot export data from the Grid.

# The Proposed Solution
We plan to add a new capability that will allow users to export data in Excel format. For simplicity and rich customization, the ExcelJS library will be used. We'll provide options for saving a document and cell customization. Features like grouping, bands and fixed columns will work out of the box.

# We Need Your Feedback

## Take a Quick Poll

[Do you find the new capability to export data in Excel format in Reactive Grid useful?](https://docs.google.com/forms/d/e/1FAIpQLSeLKLZGDCaBvmiULoxPFmoUAx0ZxUz50yXI_940Zwvo73YvnQ/viewform)

**Comment by MaximKudriavtsev** [comment]
We have released the `2.5.0` version of [DevExtreme Reactive Grid](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/) with this feature.
