### ISSUE TITLE
String not supported for TableColumnWidthInfo.Width

### ISSUE THREAD

**Issue by Chris-Boe** [DevExpress/devextreme-reactive#2368]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The Docs here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/
state that the TableColumnWidthInfo.Width supports either number or string as the value, but only number is supported in code. This is misleading and limits the functionality of the extension.

### Expected Behaviour

I would expect TableColumnWidthInfo.Width to also support strings so we can use basic css syntax as well. I would also expect the docs to reflect the accurate type for the API.

### Screenshots

![image](https://user-images.githubusercontent.com/8600792/65796239-ee04b600-e120-11e9-8b42-f116208c45e1.png)
![image](https://user-images.githubusercontent.com/8600792/65796283-12f92900-e121-11e9-9001-757354754ffb.png)

### Environment

Environment is not really relevant.
I filed this under bug report since the docs don't match the code, but it can also be considered a feature request I guess.

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @Chris-Boe,
 
Our docs compile with the latest version of our products. Since version 2.0.5 we provide the ability to use a string for the TableColumnWidthInfo.Width. Please check out your current version.
