### ISSUE TITLE
node_modules/@devexpress/dx-grid-core/dist/dx-grid-core.d.ts missing

### ISSUE THREAD

**Issue by mfellner** [DevExpress/devextreme-reactive#2374]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

Similar issue for dx-core: https://github.com/DevExpress/devextreme-reactive/issues/2177

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

```
Error at ../../node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.d.ts:6:29: Could not find a declaration file for module '@devexpress/dx-grid-core'. 
```

* node_modules/@devexpress/dx-core/dist/dx-grid-core.d.ts does not exist
* node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.d.ts includes this line:
```ts
import { EditingCell } from '@devexpress/dx-grid-core';
```

### Expected Behaviour
`node_modules/@devexpress/dx-grid-core/dist/dx-grid-core.d.ts` does exist.

### Environment

- "@devexpress/dx-react-core": "2.1.0"
- "@devexpress/dx-react-grid": "2.1.0"
- "@devexpress/dx-react-grid-material-ui": "2.1.0"
- "react": "16.10.1"
- "react-dom": "16.10.1"
- "typescript": "3.6.3"

**Comment by ushkal** [comment]
Hi,
 
We've already registered the same issue. You can track the progress here: #2373 .
