### ISSUE TITLE
How to customize DayScale Cell component

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2376]
Hi,

how can we change the day scale values like hourly split as 8:00 ,9:00,10:00 etc.
currently it has like 8:30, 9:30 ,10:30 so on..
please let me know how to modify the values

Thanks,

**Comment by AryamnovEugeniy** [comment]
Hello,

TimeScale cells are responsible for the changes you want to make. We've created a [demo](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-cwi1l) of how to customize timeScaleCellComponent.
[Here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-scale/cell.jsx) you can find how the TimeScale Cell is implemented.
And [here](https://github.com/DevExpress/devextreme-reactive/issues/1961#issuecomment-481655019) you can find more examples of how to customize Scheduler's components.

If you have other questions, don't hesitate to contact us.

**Comment by sowjanyavadada** [comment]
> Hello,
> 
> TimeScale cells are responsible for the changes you want to make. We've created a [demo](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-cwi1l) of how to customize timeScaleCellComponent.
> [Here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-scale/cell.jsx) you can find how the TimeScale Cell is implemented.
> And [here](https://github.com/DevExpress/devextreme-reactive/issues/1961#issuecomment-481655019) you can find more examples of how to customize Scheduler's components.
> 
> If you have other questions, don't hesitate to contact us.

Thank you. it worked.

**Comment by AryamnovEugeniy** [comment]
Starting with 2.2.0 version, we've changed the TimeScale's API. Now, to customize its values, you should use timeScaleLabelComponent as shown in [this demo](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-6my7k).

[Here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-scale/label.jsx) you can find how the TimeScale Label is implemented.
[Here](https://github.com/DevExpress/devextreme-reactive/issues/1961#issuecomment-481655019) you can find more examples of how to customize Scheduler's components.
And [here](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalelabelprops) you can find the TimeScale Label's API
