### ISSUE TITLE
how to place custom button next to date navigator

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2377]
Hi,

i tried to place the custom button next to date navigator, the button click is not working..
probably its not allowing to place the custom button on the scheduler 

please let me know. if any way to place on top of the scheduler.

Thanks,

**Comment by MaximKudriavtsev** [comment]
Hi,

We have demos with custom buttons in the Toolbar component. To manipulate your custom button (or another custom component in the scheduler) we recommend using a state management library like React-Redux. You can see how to implement it in the [next demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/redux-integration/). This demo will be also helpful: [How to implement it without redux](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/).

**Comment by sowjanyavadada** [comment]
> Hi,
> 
> We have demos with custom buttons in the Toolbar component. To manipulate your custom button (or another custom component in the scheduler) we recommend using a state management library like React-Redux. You can see how to implement it in the [next demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/redux-integration/). This demo will be also helpful: [How to implement it without redux](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/).

thank you. it worked.
