### ISSUE TITLE
Override IntegratedSelection CheckBox for tree data

### ISSUE THREAD

**Issue by nihhwo** [DevExpress/devextreme-reactive#2380]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x ] React Grid

### Description
Regarding issue [#933](https://github.com/DevExpress/devextreme-reactive/issues/933) I would like to know the same thing (how to customize the color of a CheckBox) just not for TableSelection, but for IntegratedSelection, as I have a tree data structure. I don't know how to create a custom Component for IntegratedSelection. You can find an example of the grid structure [here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-tu390)

### Environment
- devextreme-reactive: 19.1
- react: 16.9.0
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.4.2

**Comment by nihhwo** [comment]
Perfect, thank you very much!

**Comment by LazyLahtak** [comment]
You are welcome!
