### ISSUE TITLE
Is there a way to update the rows without updating the whole grid?

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2381]
I am using a customToolbar component that includes a date range filter, with this filter i am fetching new data based on the dates and filtering accordingly. When trying to set the new data fetched as rows, the component goes in a loop as the while grid is rerendered. Is there anyway to set the rows on the table and not the Grid? Can the toolbar and table be rendered separately?

**Comment by MaximKudriavtsev** [comment]
Hi @paufar,

We strongly recommended you check these points in the [Optimize Performance guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/). If you have already used this approach, please send us your working example based on these [CodeSendboxes](https://github.com/DevExpress/devextreme-reactive/issues/2358). Thanks.
