### ISSUE TITLE
Grid - Performance is slow on IE 11

### ISSUE THREAD

**Issue by ybri** [DevExpress/devextreme-reactive#2382]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description

Hello,
I have created a basic table using the Grid component in my React app but I am facing a problem with its performance on IE11.
It takes more than 3 seconds to display a page of 20 rows compared to 800ms in chrome.

Do you know what I can do to improve the performance of the grid on IE 11?

Thank you,

### Environment

- @babel/polyfill: ^7.4.4,
- @devexpress/dx-core: ^1.11.1,
- @devexpress/dx-react-core: ^1.11.1,
- @devexpress/dx-react-grid: ^1.11.1,
- @devexpress/dx-react-grid-material-ui: 1.11.1,
- @material-ui/core: ^3.2.0,
- bootstrap: none

**Comment by MaximKudriavtsev** [comment]
Hi @ybri,

We have already registered the [same issue](https://www.devexpress.com/Support/Center/Question/Details/T819698/grid-performance-is-slow-on-ie-11-devexpress-dx-react-grid-material-ui).
