### ISSUE TITLE
How to change background color of the Scheduler

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2383]
Hi,

i am not able to override the background color of scheduler.
can you please let me know how to override the color.

**Comment by AryamnovEugeniy** [comment]
Hi,

You can follow [this guide](https://material-ui.com/customization/theming/#theming) to change the Material-UI theme, which is the preferred way.
Or you can follow [this guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance) and customize the background color of all components you need. In your case they include the Scheduler's rootComponent, a View's emptyDayScaleEmptyCellComponent and a View's dayScaleLayoutComponent.
