### ISSUE TITLE
custom date picker on scheduler UI

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2384]
Hi,

i would like to replace the "Date Navigator"(calendar)  with my custom date picker.

is it possible to integrate with the scheduler UI?

**Comment by MaximKudriavtsev** [comment]
Hi @sowjanyavadada,

To use your custom Date Navigator either 

Override our built-in [Date Navigator](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/date-navigator/) and use your custom component via `rootComponent` and `overlayComponent` of the DateNavigator plugin. See the [Appearance Customization guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance).

Or use your own date navigator component externally and manage [ViewSate's](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/view-state/) `currentDate` property manually in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).

In both of these ways, we recommended using state management libraries like React-Redux. See [Optimize Performace guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly).

**Comment by sowjanyavadada** [comment]
> Hi @sowjanyavadada,
> 
> To use your custom Date Navigator either
> 
> Override our built-in [Date Navigator](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/date-navigator/) and use your custom component via `rootComponent` and `overlayComponent` of the DateNavigator plugin. See the [Appearance Customization guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance).
> 
> Or use your own date navigator component externally and manage [ViewSate's](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/view-state/) `currentDate` property manually in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).
> 
> In both of these ways, we recommended using state management libraries like React-Redux. See [Optimize Performace guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly).

Controlled Mode link is throwing 404  page not found.

**Comment by MaximKudriavtsev** [comment]
@sowjanyavadada 

I have updated the link to [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).
