### ISSUE TITLE
appointment width change on scheduler

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2385]
Hi,

when we select 15 mins time interval, the width of the appointment slot is not much room to display the content.
can we override the 15 mins  appointment width to display multiple lines.
example    fullname
                  phone number     8:00-8:15AM

Thanks

**Comment by MaximKudriavtsev** [comment]
Hi @sowjanyavadada,

You can override and pass some classes and styles into the [Appointment](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/) component to manipulate its `height` and `width`. See the [Appearance Customization article](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance).

Also, we plan to enhance displaying data in low-time appointments. We are working on this problem now.
