### ISSUE TITLE
Problem with TableColumnResizing

### ISSUE THREAD

**Issue by nihhwo** [DevExpress/devextreme-reactive#2386]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

### Current Behaviour
I can use the following [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-tu390) without any problem, until I uncomment the resizing plugin. What is the problem in this case? Is the custom column width maybe not recognized?

**Comment by LazyLahtak** [comment]
Hi @nihhwo,

I researched your example and found some mistakes.
The defaultColumnWidths array is incorrectly defined.
Secondly, the TableColumnResizing plugin must be placed before the TableHeaderRow plugin (see [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#dependencies)). Plugins` order is important.
Also, we implemented the ability to use percent width in version 2.0.5. That version requires MaterialUI version 4+ and React version 16.8+.
Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-h1efy).
If you have any further questions, let us know.

**Comment by nihhwo** [comment]
Thank you very much for your fast response. Still, there exists the problem of chnaging the size of the last column ("city") next to the custom column. Can you help me with that?

**Comment by LazyLahtak** [comment]
@nihhwo,
 
TableColumnResizing doesn't allow resizing custom columns. We will consider adding this ability. As a workaround you can define TableHeaderRow's cellComponent and disable resizing for the "city" column to remove the right separator. In the "nextColumn" resizing mode it is still possible to resize this column by resizing the previous column.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-7eozi).
