### ISSUE TITLE
How to change DateNavigator's OpenButton date format

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2387]
Hi 

Can we change the Date Navigator date format(currently it showing October 2,2019) can we modify it to "Oct 2, 2019". first 3 letters of month.

**Comment by AryamnovEugeniy** [comment]
Hi,

You can override DateNavigator's [OpenButton](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/date-navigator/#datenavigatoropenbuttonprops) component. Change the OpenButton's text property the way you want it to be.

If you have other questions, we will be glad to answer them.

**Comment by sowjanyavadada** [comment]
thanks for the info, my requirement is also display the day of the week for example
Mon,Sep 07.   i achieved the (Sep 07) part but how to show the day of the week.

**Comment by AryamnovEugeniy** [comment]
Hello,

You can convert the OpenButton's text to the Date object, for example, using the [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) method. And then you can format the date to achieve your goals.

**Comment by sowjanyavadada** [comment]
Thanks.it worked

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
