### ISSUE TITLE
Lost TableHeaderRow and TableRowDetail after upgraded to version 2.1

### ISSUE THREAD

**Issue by KaiWynn** [DevExpress/devextreme-reactive#2388]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
After I upgraded to version 2.1 from 1.10, the TableHeaderRow and TableRowDetail are not showing up in my grid.

### Expected Behaviour
The grid should be the same after upgrade.

### Steps to Reproduce
Nothing changed in my codes, but I installed a few new things:
    "react": "16.10.1",
    "react-dom": "16.10.1",
    "@devexpress/dx-react-core": "2.1.1",
    "@devexpress/dx-react-grid": "2.1.1",
    "@devexpress/dx-react-grid-material-ui": "2.1.1", 
    

### Screenshots
![image](https://user-images.githubusercontent.com/36289934/66062691-80350180-e507-11e9-9915-e397a82e547d.png)

### Environment

- devextreme-reactive: 2.1.1
- react: 16.10.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.4.3

**Comment by LazyLahtak** [comment]
Hi @KaiWynn,
 
Thank you for your report. Could you please provide us with your code? This will help us solve this problem.

**Comment by KaiWynn** [comment]
`import React from 'react'
import { withRouter } from 'react-router-dom'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'

import { withStyles } from '@material-ui/core/styles'
import { withAlert } from 'react-alert'

import Paper from '@material-ui/core/Paper'
import IconButton from '@material-ui/core/IconButton'
import ExportFileIcon from '@material-ui/icons/TrendingUp'
import ImportFileIcon from '@material-ui/icons/SaveAlt'
import ImportIcon from '@material-ui/icons/PlayForWork'
import AddNewIcon from '@material-ui/icons/AddCircle'

import fetchTbp from '../app-helper/fetch-tbp'
import { apiURL } from '../app-helper/fetch-tbp'
import { setSelectLists } from '../store/listData/actionCreator'

import DeleteDialog from '../app-comp/DeleteDialog'
import AddDialog from './AddDialog'
import SelectFilter from './SelectFilter'
import SelectMenu from './SelectMenu'

import Dropzone from 'react-dropzone'
import * as XLSX from 'xlsx'

import {
  columnNames,
  columnWidths,
  columnEditingEnabled,
  columnGroupingEnabled,
  columnHidden,
  columnGrouping,
  // columnBoolean,
} from './constants'

import {
  Template,
  TemplatePlaceholder,
  Getter,
} from '@devexpress/dx-react-core'

import {
  EditingState,
  SortingState,
  IntegratedSorting,
  FilteringState,
  IntegratedFiltering,
  RowDetailState,
  PagingState,
  IntegratedPaging,
  GroupingState,
  IntegratedGrouping,
  SelectionState,
  IntegratedSelection,
} from '@devexpress/dx-react-grid'

import {
  Grid,
  Table,
  TableHeaderRow,
  TableColumnResizing,
  TableEditColumn,
  TableFilterRow,
  ColumnChooser,
  TableColumnVisibility,
  Toolbar,
  TableRowDetail,
  PagingPanel,
  TableGroupRow,
  // GroupingPanel,
  DragDropProvider,
  TableSelection,
} from '@devexpress/dx-react-grid-material-ui'

import {
  gridStyles,
  CommandButtons,
  // BooleanTypeProvider,
  dropZoneStyle,
} from '../app-helper/grid-setting'

const getRowId = row => row.row_id

class BusinessLineGrid extends React.PureComponent {
  constructor(props) {
    super(props)
    this.state = {
      importFile: [],
      showImport: false,
      openAddDialog: false,
      openSelectMenu: false,
      favoriteBusinessLine: [],
      myFavoriteBusinessLine: [],
      enableMenuItem: [],

      // Columns
      columns: columnNames,
      columnWidths: columnWidths,

      // Column settings
      groupingStateColumnExtensions: columnGroupingEnabled,
      grouping: columnGrouping,
      expandedGroups: [`${new Date().getFullYear()}`],
      sorting: [],
      filters: [],
      hiddenColumnNames: columnHidden,
      editingStateColumnExtensions: columnEditingEnabled,

      // Rows
      rows: [],
      deletingRows: [],
      selection: [],

      // Page
      currentPage: 0,
      pageSize: 10,
      pageSizes: [10, 15, 20, 25, 30, 0],
    }

    // Row: New, Add, Edit, Delete
    this.cancelDelete = () => this.setState({ deletingRows: [] })
    this.changeColumnWidths = columnWidths => this.setState({ columnWidths })
    this.changeSorting = sorting => this.setState({ sorting })
    this.changeFilters = filters => this.setState({ filters })
    this.changeGrouping = grouping => this.setState({ grouping })
    this.changeExpandedGroups = expandedGroups =>
      this.setState({ expandedGroups })
    this.hiddenColumnNamesChange = hiddenColumnNames =>
      this.setState({ hiddenColumnNames })
    this.changeSelection = selection => {
      this.setState({ selection })
    }
    this.changeCurrentPage = currentPage => this.setState({ currentPage })
    this.changePageSize = pageSize => this.setState({ pageSize })
    this.clearFilter = () => this.setState({ filters: [] })

    this.commitChanges = ({ deleted }) => {
      let { rows } = this.state
      this.setState({ rows, deletingRows: deleted || this.state.deletingRows })
    }

    // Delete row confimation
    this.deleteRows = () => {
      const rows = this.state.rows.slice()
      this.state.deletingRows.forEach(rowId => {
        const index = rows.findIndex(row => row.row_id === rowId)
        if (index > -1) {
          rows.splice(index, 1)
        }

        fetchTbp({
          url: '/deleteBusinessLine/' + rowId,
          method: 'DELETE',
        }).then(resp => {
          this.props.alert.success('Row Deleted')
        })
      })

      this.setState({ rows, deletingRows: [] })
    }

    this.changeExpandedDetails = expandedRowIds => {
      const lnobs_yr = expandedRowIds[0].replace('-', '/')
      const selectedYear = parseInt(expandedRowIds[0].split('-')[1])
      const currentYear = new Date().getFullYear()
      const currentMonth = new Date().getMonth() + 1
      let monthLabel = 'ALL'

      if (selectedYear === currentYear) {
        if (currentMonth < 4) {
          monthLabel = 'JAN'
        } else if (currentMonth < 7) {
          monthLabel = 'APR'
        } else if (currentMonth < 8) {
          monthLabel = 'JUL'
        } else if (currentMonth < 10) {
          monthLabel = 'AUG'
        } else {
          monthLabel = 'OCT'
        }
      }

      this.props.history.push(`/ForecastDetail/${lnobs_yr}/${monthLabel}`)
    }

    this.EditColumnCell = props => (
      <TableEditColumn.Cell {...props}>
        {React.Children.toArray(props.children).filter(child => {
          if (child.props.id === 'delete') {
            if (this.state.selection.indexOf(props.tableRow.row.row_id) > -1) {
              return true
            }
            return false
          }

          return true
        })}
      </TableEditColumn.Cell>
    )

    this.tableBodyRowsComputed = ({ tableBodyRows }) =>
      tableBodyRows.map((tableBodyRow, i) => ({
        ...tableBodyRow,
        ROW_INDEX: i,
      }))

    this.tableRow = ({ tableRow, ...restProps }) => {
      const odd = !!(tableRow.ROW_INDEX % 2)
      return (
        <Table.Row
          {...restProps}
          tableRow={tableRow}
          style={{
            backgroundColor: odd ? '#fff' : '#f6f8fa',
          }}
        />
      )
    }

    this.filterBusinessLine = businessLineId => {
      this.setState({ favoriteBusinessLine: businessLineId })
    }

    this.getFavorite = () => {
      fetchTbp({
        url: '/getUserSetting/favoriteBusinessLine/' + this.props.appUserId,
      }).then(resp => {
        if (resp.data) {
          const userSetting = resp.data[0].user_setting
          this.setState({
            favoriteBusinessLine: userSetting.lnobs_i,
            myFavoriteBusinessLine: userSetting.lnobs_i,
          })
        } else {
          this.getData()
        }
      })
    }

    this.showFavorite = () => {
      this.setState({
        favoriteBusinessLine: this.state.myFavoriteBusinessLine,
      })
    }

    this.saveFavorite = () => {
      fetchTbp({
        url: '/saveUserSetting',
        method: 'POST',
        body: {
          setting: { lnobs_i: this.state.favoriteBusinessLine },
          appUserId: this.props.appUserId,
          settingName: 'favoriteBusinessLine',
        },
      }).then(resp => {
        if (resp.data[0].status === 'Done') {
          this.setState({
            myFavoriteBusinessLine: this.state.favoriteBusinessLine,
          })
          this.props.alert.success('Favorites Saved')
        }
      })
    }

    this.deleteFavorite = () => {
      fetchTbp({
        url: '/deleteUserSetting/favoriteBusinessLine/' + this.props.appUserId,
        method: 'DELETE',
      }).then(resp => {
        if (resp.data.status === 'Ok') {
          this.setState({
            favoriteBusinessLine: [],
            myFavoriteBusinessLine: [],
          })
          this.props.alert.success('Favorites Deleted')
        }
      })
    }

    this.getData = () => {
      const urlTail = !_.isEmpty(this.state.favoriteBusinessLine)
        ? `/${this.state.favoriteBusinessLine}`
        : ''
      fetchTbp({
        url: '/getBusinessLineForecast' + urlTail,
      }).then(resp => {
        this.setState({
          rows: resp.data,
        })
      })
    }

    // Get lists for select lists.
    this.getLists = () => {
      if (this.props.selectLists) {
        return
      }

      const currentYear = new Date().getFullYear()

      const businessYear = {
        yr_num: [
          {
            value: currentYear,
            label: `${currentYear}`,
          },
          {
            value: currentYear + 1,
            label: `${currentYear + 1}`,
          },
        ],
      }

      const businessLineList = fetchTbp({
        url: '/getListBusinessLine',
      }).then(resp => {
        return { lnobs_n: resp.data }
      })

      const copList = fetchTbp({
        url: '/getListCop',
      }).then(resp => {
        return { cop_n: resp.data }
      })

      const vendorList = fetchTbp({
        url: '/getListVendor',
      }).then(resp => {
        return { bpart_n: resp.data }
      })

      Promise.all([businessYear, businessLineList, copList, vendorList]).then(
        values => {
          const allLists = Object.assign(
            values[0],
            values[1],
            values[2],
            values[3],
          )
          this.props.setSelectLists(allLists)
        },
      )
    }

    this.addNewDialog = () => {
      this.setState({ openAddDialog: true })
    }

    this.cancelAdd = () => {
      this.setState({ openAddDialog: false })
    }

    this.saveRecord = newRecord => {
      newRecord['crte_by_i'] = this.props.appUserId

      fetchTbp({
        url: '/addNewBusinessLine',
        method: 'POST',
        body: newRecord,
      }).then(resp => {
        const apiStatus = resp.data[0].status
        if (apiStatus === 'Done') {
          this.getData()
          this.props.alert.success('New record added')
          this.setState({ openAddDialog: false })
        } else {
          this.props.alert.error(apiStatus)
        }
      })
    }

    this.selectMenu = () => {
      this.setState({ openSelectMenu: true })
    }

    this.selectMenuClick = listItem => {
      switch (listItem) {
        case 'myFav':
          this.showFavorite()
          break
        case 'saveFav':
          this.saveFavorite()
          break
        case 'deleteFav':
          this.deleteFavorite()
          break
        default:
          break
      }
    }

    this.enableMenuItem = () => {
      let enableItems = []

      if (!_.isEmpty(this.state.myFavoriteBusinessLine)) {
        if (
          this.state.favoriteBusinessLine !== this.state.myFavoriteBusinessLine
        ) {
          enableItems.push('myFav')
        }
        enableItems.push('deleteFav')
      }

      if (!_.isEmpty(this.state.favoriteBusinessLine)) {
        if (
          this.state.favoriteBusinessLine !== this.state.myFavoriteBusinessLine
        ) {
          enableItems.push('saveFav')
        }
      }
      this.setState({ enableMenuItem: enableItems })
    }

    this.exportData = () => {
      window.location = apiURL + '/exportForecastPlan/' + this.state.selection
    }

    this.showImport = () => {
      this.setState(prevState => ({ showImport: !prevState.showImport }))
    }

    this.onDrop = importFile => {
      this.setState({ importFile })
    }

    this.importData = e => {
      const f = this.state.importFile[0]
      const reader = new FileReader()
      reader.onload = e => {
        //evt = on_file_select event
        /* Parse data */
        const bstr = e.target.result
        const wb = XLSX.read(bstr, { type: 'binary' })
        /* Get first worksheet */
        const wsname = wb.SheetNames[0]
        const ws = wb.Sheets[wsname]
        /* Convert array of arrays */
        const jsonData = XLSX.utils.sheet_to_json(ws, { header: 0 })

        fetchTbp({
          url: '/importForecastPlan',
          method: 'POST',
          body: {
            jsonData: jsonData,
            appUserId: this.props.appUserId,
          },
        }).then(resp => {
          const apiStatus = resp.data[0].status

          if (apiStatus === 'Done') {
            this.setState({
              showImport: false,
              importFile: [],
            })
            this.getData()
            this.props.alert.success('Import completed!')
          } else {
            this.props.alert.error(apiStatus)
          }
        })
      }
      reader.readAsBinaryString(f)
    }

    this.allowImport = () => {
      const currentMonth = new Date().getMonth() + 1
      if (
        currentMonth === 1 ||
        currentMonth === 4 ||
        currentMonth === 7 ||
        currentMonth === 8 ||
        currentMonth === 10 ||
        currentMonth === 12
      ) {
        return true
      } else {
        return false
      }
    }
  }

  componentDidMount() {
    this.props.appUserId && this.getFavorite()
    this.getLists()
  }

  componentDidUpdate(prevProps, prevState) {
    if (this.state.favoriteBusinessLine !== prevState.favoriteBusinessLine) {
      this.getData()
      this.enableMenuItem()
    }

    if (
      this.state.myFavoriteBusinessLine !== prevState.myFavoriteBusinessLine
    ) {
      this.enableMenuItem()
    }
  }

  render() {
    const { classes } = this.props
    const {
      rows,
      columns,
      deletingRows,
      columnWidths,
      sorting,
      filters,
      tableColumnExtensions,
      hiddenColumnNames,
      expandedRowIds,
      pageSize,
      pageSizes,
      currentPage,
      filteringStateColumnExtensions,
      grouping,
      expandedGroups,
      groupingStateColumnExtensions,
      selection,
    } = this.state

    return (
      <Paper>
        <Grid rows={rows} columns={columns} getRowId={getRowId}>
          <EditingState onCommitChanges={this.commitChanges} />
          <SortingState
            sorting={sorting}
            onSortingChange={this.changeSorting}
          />
          <IntegratedSorting />
          <DragDropProvider />
          <GroupingState
            grouping={grouping}
            onGroupingChange={this.changeGrouping}
            columnExtensions={groupingStateColumnExtensions}
            expandedGroups={expandedGroups}
            onExpandedGroupsChange={this.changeExpandedGroups}
          />
          <IntegratedGrouping />
          <FilteringState
            filters={filters}
            onFiltersChange={this.changeFilters}
            columnExtensions={filteringStateColumnExtensions}
          />
          <IntegratedFiltering />
          <RowDetailState
            expandedRowIds={expandedRowIds}
            onExpandedRowIdsChange={this.changeExpandedDetails}
          />
          <SelectionState
            selection={selection}
            onSelectionChange={this.changeSelection}
          />
          <IntegratedSelection />
          <PagingState
            currentPage={currentPage}
            onCurrentPageChange={this.changeCurrentPage}
            pageSize={pageSize}
            onPageSizeChange={this.changePageSize}
          />
          <IntegratedPaging />
          <Table
            columnExtensions={tableColumnExtensions}
            rowComponent={this.tableRow}
          />
          <Getter name="tableBodyRows" computed={this.tableBodyRowsComputed} />
          <TableColumnResizing
            columnWidths={columnWidths}
            onColumnWidthsChange={this.changeColumnWidths}
          />
          <TableHeaderRow showSortingControls />
          <TableFilterRow />
          <TableSelection showSelectAll={true} showSelectionColumn={true} />
          <PagingPanel pageSizes={pageSizes} />

          <TableRowDetail />

          <TableEditColumn
            width="70"
            showDeleteCommand
            commandComponent={CommandButtons}
            cellComponent={this.EditColumnCell}
          />

          <TableColumnVisibility
            hiddenColumnNames={hiddenColumnNames}
            onHiddenColumnNamesChange={this.hiddenColumnNamesChange}
          />
          <TableGroupRow />
          <Toolbar />
          <Template name="toolbarContent">
            <IconButton title="Add New" onClick={this.addNewDialog}>
              <AddNewIcon />
            </IconButton>

            {this.props.selectLists && (
              <div style={{ width: 600 }}>
                <SelectFilter
                  listOptions={this.props.selectLists.lnobs_n}
                  defaultList={this.state.favoriteBusinessLine}
                  afterChange={this.filterBusinessLine}
                />
              </div>
            )}

            <SelectMenu
              menuClick={this.selectMenuClick}
              enableItems={this.state.enableMenuItem}
            />

            <TemplatePlaceholder />
            {this.state.showImport && !_.isEmpty(this.state.importFile) && (
              <IconButton title="Import" onClick={this.importData}>
                <ImportIcon />
              </IconButton>
            )}
            {this.state.showImport && (
              <section>
                <div className="dropzone">
                  <Dropzone
                    style={dropZoneStyle}
                    accept=".xlsx"
                    onDrop={this.onDrop.bind(this)}
                  >
                    {!_.isEmpty(this.state.importFile) ? (
                      <p> {this.state.importFile.map(f => f.name)} </p>
                    ) : (
                      <p>Drop file or click to select file to import.</p>
                    )}
                  </Dropzone>
                </div>
              </section>
            )}

            {this.allowImport() && (
              <IconButton title="Import From Excel" onClick={this.showImport}>
                <ImportFileIcon />
              </IconButton>
            )}

            {selection.length > 0 && (
              <IconButton title="Export To Excel" onClick={this.exportData}>
                <ExportFileIcon />
              </IconButton>
            )}
          </Template>
          <ColumnChooser />
        </Grid>

        <AddDialog
          openDialog={this.state.openAddDialog}
          optionLists={this.props.selectLists ? this.props.selectLists : {}}
          cancelAdd={this.cancelAdd}
          saveRecord={this.saveRecord}
        />

        <DeleteDialog
          classes={classes}
          rows={rows}
          columns={columns}
          idColumn={'row_id'}
          deletingRows={deletingRows}
          cancelDelete={this.cancelDelete.bind(this)}
          deleteRows={this.deleteRows.bind(this)}
        />
      </Paper>
    )
  }
}

const mapStateToProps = state => {
  return {
    selectLists: state.listData.selectLists,
  }
}

const mapDispatchToProps = dispatch =>
  bindActionCreators({ setSelectLists }, dispatch)

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(withRouter(withStyles(gridStyles)(withAlert(BusinessLineGrid))))
`

**Comment by LazyLahtak** [comment]
@KaiWynn,

Thank you for your example. It helped us find an error. We will fix it in the nearest release.
For now, you can use a number for the TableEditColumn's width property instead of a string. Another option is to specify CSS-accepted units (for example, "70px").

**Comment by KaiWynn** [comment]
Thank you for all your works that helped my works easier.

**Comment by LazyLahtak** [comment]
You are welcome
