### ISSUE TITLE
Does it make sense to include peer dependencies changes in CHANGELOG.MD

### ISSUE THREAD

**Issue by artyil** [DevExpress/devextreme-reactive#2394]
I just wonder why peerDependencies changes are not included in 
https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md 

It would be very nice to get this information in advance, eg: react / react-dom peerDependencies updates

**Comment by MaximKudriavtsev** [comment]
Hi @artyil,

Thank you for this suggestion. We'll consider it when planning a future sprint.

**Comment by AryamnovEugeniy** [comment]
Hi @artyil,

We have considered your suggestion. We release a new version every two weeks and with this we update all our dependencies, including peer dependencies. But if we include peer dependencies changes in CHANGELOG.MD, it will contain too much information.
Would you explain why you need this information? What problem are you experiencing? It is possible that we will reconsider our decision based on your scenario.

**Comment by artyil** [comment]
Hi @AryamnovEugeniy and @MaximKudriavtsev,
Thanks for your response.

My issue occurs with the following scenario:


Given a react application `MyReactApp` which using exact versions control (--save-exact) for all its `dependencies` in package.json.

Among others, `MyReactApp` use `react@16.8.6` (exact) version as its dependency.

It also has `@devexpress/dx-react-core@2.0.4` (exact) as dependency, which has same react version in `peerDependencies`:
```
npm show "@devexpress/dx-react-core@2.0.4" peerDependencies
{ react: '>=16.8.6', 'react-dom': '>=16.8.6' }
```

Now, I want to update `@devexpress/dx-react-core` package by patching the version from 2.0.4 to 2.0.5 because I want to be able to benefit from all recent bug fixes and other goodies.

Let list `peerDependencies` for `@devexpress/dx-react-core@2.0.*`:
```
npm show "@devexpress/dx-react-core@2.0.*" peerDependencies
@devexpress/dx-react-core@2.0.0 { react: '>=16.8.6', 'react-dom': '>=16.8.6' }
@devexpress/dx-react-core@2.0.1 { react: '>=16.8.6', 'react-dom': '>=16.8.6' }
@devexpress/dx-react-core@2.0.2 { react: '>=16.8.6', 'react-dom': '>=16.8.6' }
@devexpress/dx-react-core@2.0.3 { react: '>=16.8.6', 'react-dom': '>=16.8.6' }
@devexpress/dx-react-core@2.0.4 { react: '>=16.8.6', 'react-dom': '>=16.8.6' }
@devexpress/dx-react-core@2.0.5 { react: '>=16.9.0', 'react-dom': '>=16.9.0' }
```

Unfortunately, version 2.0.5 (which is a patch) updated `react` package in peerDependencies to next **minor** version.

Due to above, it is not safe for `MyReactApp` to update `@devexpress/dx-react-core@2.0.4` to `2.0.5` without also updating `react` to `16.9.0` which I can't (do due to reasons). 

I am not aware what the decision you made behind this peerDependency update in patch release, and I can't really benefit from your minor update and any future update without first checking peerDependencies. 

In general, if I follow semver conventions I don't expect breaking changes in patch or minor releases.

So this is the long story, I hope it make sense, waiting for your feedback

**Comment by churkin** [comment]
Hi @artyil,
Thank you for the feedback. We decided to review our dependencies update policy. We will not add new information to the change log as you suggest, but we will not update peer dependencies on each minor release either.
