### ISSUE TITLE
Adds incorrect cell if the cell duration goes out of the day 

### ISSUE THREAD

**Issue by churkin** [DevExpress/devextreme-reactive#2402]
```jsx
<DayView
  startDayHour={18}
  endDayHour={23}
  cellDuration={130}
/>
```

<img width="499" alt="Screenshot 2019-10-07 at 11 35 11" src="https://user-images.githubusercontent.com/5182202/66296599-96bbce00-e8f6-11e9-9797-2326b3e1d424.png">

**Comment by MaximKudriavtsev** [comment]
Hi,

This bug already has been fixed. Related with #2401.
