### ISSUE TITLE
How to fit content columns in React Grid

### ISSUE THREAD

**Issue by c0m1t** [DevExpress/devextreme-reactive#2403]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I want the data table columns to exactly **fit their contents**.
The data table rows are expandable and I set the width of the toggle column to zero because i want the rows to toggle when i clicked on the entire row and hide the toggle column.

Also when I try to set explicit width to columns by using `columnExtention` prop on `Table` component, DevExpress adds an empty additional column at the end of the table. 

### Environment
- dx-react-core:  1.10.5
- dx-react-grid: 1.10.5
- dx-react-grid-material-ui: 1.10.5
- react: 16.8.3
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.1

**Comment by MaximKudriavtsev** [comment]
Hi @c0m1t,

I have created an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-tyd0g) illustrating how to hide a toggle column. Let us know if it resolves the problem.

BTW we have already released the [2.1.1 version of our React Components](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#211-2019-10-01) and strongly recommend you use it because only new versions have new features and some bug fixes which are incompatible with old versions.

**Comment by c0m1t** [comment]
@MaximKudriavtsev Thank you for your response
My main problem is I want to have a table which its columns width are as wide as their widest cell in them and I do not want the table to be 100% of their parent component. 
A table that its content sets the width not their container, A table which its width changes by changing its content.

**Comment by MaximKudriavtsev** [comment]
@c0m1t,

You can pass the `display: block` CSS property into the table component. See the following [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-y3rjc).

**Comment by c0m1t** [comment]
@MaximKudriavtsev Yes it works. Thank you.

**Comment by c0m1t** [comment]
@MaximKudriavtsev shouldnt I be using `Table.Table` component instead of `table`?
There are some props on `TableComponent` which do not exist on DOM elements. like `tableRef`, ... .

**Comment by c0m1t** [comment]
@MaximKudriavtsev shouldnt I be using `Table.Table` component instead of `table`?
There are some props on `TableComponent` which do not exist on DOM elements. like `tableRef`, ... .

**Comment by MaximKudriavtsev** [comment]
It is good news that the problem has been resolved. Thank you for letting us know about your progress 🚀
