### ISSUE TITLE
change the line width of appointment 

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2405]
hi

i would like to change the first line border width under the date navigator.

how can we pass the styles to change the top border width.

Thanks

**Comment by MaximKudriavtsev** [comment]
Hi @sowjanyavadada,

Could you please clarify what you want to achieve? The title of this issue is not clear. You can attach pictures to illustrate the expected behavior.

**Comment by sowjanyavadada** [comment]
<img width="506" alt="Screen Shot 2019-10-07 at 8 55 51 AM" src="https://user-images.githubusercontent.com/54480333/66334224-36c92580-e8fe-11e9-9d9d-a8f141ab47ae.png">

**Comment by MaximKudriavtsev** [comment]
@sowjanyavadada,

In your case, you should override the Toolbar's root component. Please see the [following issue](https://github.com/DevExpress/devextreme-reactive/issues/1961#issuecomment-481655019) that illustrates how to override built-in components.

This [example](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-xi7jg) demonstrates how to remove a border from the Toolbar component.

**Comment by sowjanyavadada** [comment]
It worked Thank you, And can we change the hour line as dark line and 30mins lines in lighter line. Please let me to 
<img width="411" alt="Screen Shot 2019-10-09 at 10 44 13 AM" src="https://user-images.githubusercontent.com/54480333/66498569-e7146680-ea83-11e9-97d7-30a4aa38f90e.png">

**Comment by MaximKudriavtsev** [comment]
@sowjanyavadada,

Sure, you can override the [DayView](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/day-view/) plugin's `timeTableCellComponent` property to change the border color. You can see how to override our components in the [Fundamentals guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/).

**Comment by sowjanyavadada** [comment]
Thank you very much.
