### ISSUE TITLE
[Proposal] switch to `clsx` from `classnames`

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#2407]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

It seems people are switching from `classnames` to `clsx`, which has the same functionality as `classnames` and with much smaller size.
This should be a fairly simple change - global replacing `classnames` with `clsx`.

>A tiny (223B) utility for constructing className strings conditionally.
Also serves as a faster & smaller drop-in replacement for the classnames module.

https://github.com/lukeed/clsx

**Comment by MaximKudriavtsev** [comment]
Hi @franklixuefei,

Thank you for your suggestion. This library looks great, but we need some time to research if we can use it instead of `classnames`. We will consider it in future releases.

**Comment by churkin** [comment]
Implemented
