### ISSUE TITLE
Edge: Virtual Table - header scrolls with fixed columns

### ISSUE THREAD

**Issue by chr22** [DevExpress/devextreme-reactive#2410]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The header scrolls to the side in Edge if Virtual Table is used with fixed columns. Below is a screenshot from your documentation.

[Documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fixed-columns/)

### Expected Behaviour

The fixed columns should be fixed in place.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

![image](https://user-images.githubusercontent.com/3649594/66394775-3b610d00-e9d6-11e9-9bf2-76b3a5222a0d.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Thank you for reporting the problem. We will fix it soon.

**Comment by LazyLahtak** [comment]
@chr22

We researched the problem and found that this bug is related to the Edge [bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18940617/). Thus, we won't be able to fix it on our side.
