### ISSUE TITLE
Grid stuck in skeleton state when scrolling to the bottom

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2418]
When scrolling to the bottom of the grid i noticed that the grid is "stuck in skeleton state" where it populates a lot of empty rows and just shows empty rectangles.

![image](https://user-images.githubusercontent.com/36677885/66495425-7f790e00-eab9-11e9-9c86-a1a6dc5cb410.png)

this is my grid code: 
```
<Grid rows={rows} columns={columns} getRowId={getRowId}>
            <DragDropProvider />
            <FilteringState filters={filters} />
            <CustomFiltering filterString={filterString} />
            <IntegratedFiltering />
            <SortingState sorting={sorting} onSortingChange={this.changeSorting} />
            <IntegratedSorting />
            <VirtualTable columnExtensions={tableColumnExtensions} cellComponent={this.Cell} />
            <TableColumnResizing defaultColumnWidths={defaultColumnWidths} />
            <TableColumnReordering defaultOrder={defaultColumnOrder} />
            <TableHeaderRow showSortingControls />
            <TableColumnVisibility defaultHiddenColumnNames={defaultHiddenColumnNames} />
            <Toolbar flexibleSpaceComponent={() => this.ToolbarFlexibleSpace(dateFrom, dateTo, fetchInProgress)} />
            <ColumnChooser />
            <CustomSearchPanel onValueChange={this.changeSearchValue} />
          </Grid>
```

**Comment by LazyLahtak** [comment]
Hi @paufar,

Thank you for your report. Would you please provide us with your code? This will help us solve this problem. Also, could you specify which version of the Grid you are using?

**Comment by paufar** [comment]
SOLVED: the issue was that I was not setting the estimatedRowHeight on the Virtual table and so it was estimating the wrong height and populating the table with the skeleton state image. Make sure that when using VirtualTable, you set the estimatedRowHeight if you are changing the default row height of Materialui/bootstrap etc.

**Comment by LazyLahtak** [comment]
It is good news that the problem has been resolved. Thank you for letting us know about your progress.
