### ISSUE TITLE
Time scale custom format

### ISSUE THREAD

**Issue by sowjanyavadada** [DevExpress/devextreme-reactive#2419]
Hi,

Can we apply style to display time like 8 AM,9AM etc in the grid instead of 8:00 am , 9:00 am..

Thanks

**Comment by AryamnovEugeniy** [comment]
Hi,

You can follow [this guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/localization/#customize-date-formatting) to override the [TimeScale's cell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalecellprops) and set the formatDate property to a function that formats dates the way you need to.

**Comment by sowjanyavadada** [comment]
Thank you so much it helped .
