### ISSUE TITLE
Does Virtual Table support the width set by TableHeaderRow.Cell?

### ISSUE THREAD

**Issue by 734204679** [DevExpress/devextreme-reactive#2425]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

The width of TableHeaderRow.Cell is set using %. This setting takes effect with Table , but it will be invalid when using  VirtualTable  . I want to know if VirtualTable does not support custom TableHeaderRow.Cell width. maybe my usage is wrong?

https://codesandbox.io/s/devextreme-react-grid-for-material-ui-kz1q3?fontsize=14

**Comment by LazyLahtak** [comment]
Hi @734204679,

To set the width of columns, you can use the Table's [columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumnextension) property and VirtualTable's [columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#virtualtablecolumnextension) property. As you can see, VirtualTable supports only the width in pixel - see this [topic](https://github.com/DevExpress/devextreme-reactive/issues/411#issuecomment-532627709).
If you have any further questions, let us know.
