### ISSUE TITLE
How to change the DoubleClick on a TableCell in WeekView 

### ISSUE THREAD

**Issue by eranabir** [DevExpress/devextreme-reactive#2427]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
How can I replace the double click option on the TimeCell in the WeekView to open my own ModalComponent

![Capture](https://user-images.githubusercontent.com/6376366/66709600-677ee400-ed70-11e9-93c3-1a21f2d01695.PNG)

**Comment by AryamnovEugeniy** [comment]
Hi,

You can customize WeekView's [timeTableCellComponent ](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimetablecellprops)and override onDoubleClick property to open, for example, your own ModalComponent, as I've shown in [this demo](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-1wxeh).
If you want to open your own AppointmentForm, however, you may consider customizing our AppointmentForm as shown in [this demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/).

If you have further questions, we'll be glad to answer them.
