### ISSUE TITLE
VirtualTable; Reordering and Grouping animation does not work.

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2429]
https://codesandbox.io/s/naughty-snow-te4bw

In the normal table component, columns can be animated swapped. But 'VirtualTable' does not animate. The same applies to grouping. Animation does not work.

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

- devextreme-reactive: xxx
- react: 16.8.6
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

The VirtualTable doesn't support animation. However, we will consider implementing it in the future.

**Comment by ahmetcaglayan** [comment]
https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/drag-drop-provider/

To this page or

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/

It would be great to write a description on these pages. Because I thought I couldn't do it :) I thought I couldn't.

I'm happy you're adding. Thank you.

**Comment by LazyLahtak** [comment]
@ahmetcaglayan ,

It's not clear what you mean by `write a description on these pages`. Could you please clarify this?

**Comment by ahmetcaglayan** [comment]
Animation not supported, did not write. These pages can also be written something like the animation support is only available in the Table component.

**Comment by LazyLahtak** [comment]
@ahmetcaglayan,

Thank you for your idea. We will think about adding the required information to our documentation. Should you have any other questions, feel free to open a new issue. We will be happy to help you.
