### ISSUE TITLE
TableColumnReordering with dynamic defaultOrder option

### ISSUE THREAD

**Issue by sevytoor** [DevExpress/devextreme-reactive#2430]
Hi there, 

I'm facing with some issues with **TableColumnReordering** feature.
Everything works fine if the **defaultOrder** is set to a constant value like 
`const defaultOrder=["column1",column2]` and then use it like
 ```
 <TableColumnReordering
                defaultOrder={defaultOrder}
/>
```
Now, when i came to build this defaultOrder value, i cannot reorder the culumn.
The thing is,I build myself from function the orderDefault like:
Suppose that I have data in JSON from such API like
```
{
  column1:"col1",
  column2:"col2
}
```
my function will return something like:
`defaultOrder=["column1","column2"]`

But when apply this in TableColumnReordering , it doesn't work.

Have you already faced with the same issue?
Thanks

**Comment by LazyLahtak** [comment]
Hi @sevytoor,

The TableColumnReordering's `defaultOrder` property defines initial order of columns. For you case, you should use [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/#controlled-mode) and define the `order` and the `onOrderChange` properties for the TableColumnReordering plugin.
Here is example illustrating how to change column order programmatically.

Also you can find more information about controlled and uncontrolled mode in [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).

**Comment by LazyLahtak** [comment]
Hi @sevytoor,

TableColumnReordering's `defaultOrder` property defines the initial order of columns. In your case, you need to use the [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/#controlled-mode) and define the `order` and the `onOrderChange` properties of the TableColumnReordering plugin.
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ycl0m) illustrating how to programmatically change columns' order.

Also, you can find more information about controlled and uncontrolled mode in the [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).
If you have any further questions, let us know.
