### ISSUE TITLE
Question about inline editing with support for custom edit controls

### ISSUE THREAD

**Issue by sjsingh85** [DevExpress/devextreme-reactive#2433]
[x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Great control!
I am trying to use the inline click and edit feature with custom controls. Can you help me figure out following issues:
1. Why is it that the control is not reverting back to "Not Editing" state once user changes a value and clicks outside. This is specific to drop down control in the example.
2. Why am I not able to go to edit mode for "active" (last) column. Is it because of svg not bubbling up a click event? Can i manually add an onclick somehow to do this?
3. How can I tab into next column to edit that particular cell in that row.
4. If the point 3 above is not possible - can I make all columns in a row as editable once user taps on any column in the row and perform save when user clicks outside that row to revert back to "Not Editing" state?

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/devextreme-react-grid-for-material-ui-11gtg&gt;. Another Example &lt;https://codesandbox.io/s/devextreme-react-grid-for-material-ui-2uuoo&gt;

### Environment

- devextreme-reactive: 2.1.2
- react: 16.9.0
- browser: chrome
- material-ui: 4.5.0

Thanks!

**Comment by LazyLahtak** [comment]
Hi @sjsingh85,

TableInlineCellEditing's [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/#tableinlinecelleditingcellprops) has props you can use. To revert the editor to the non-editing state, you can pass the onBlur property to your component.

In the last column, you define your own component that replaces the Table.Cell component. The TableInlineCellEditing plugin provides this component with the additional onClick event, which switches the cell to editing mode. You can pass that event to your component. Also, you can use DataTypeProvider's [formatterComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/#datatypeprovidervalueformatterprops) to format the cell's data.

We have plans to implement keyboard navigation. Meanwhile, you can use the native focus. To switch a cell to the editing mode, define the onFocus event.

Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-7gkh5).
Let us know if it meets your requirements.

**Comment by sjsingh85** [comment]
Thanks @LazyLahtak for the example. This is good for now.

Do you have any ETA on keyboard navigation?

Thanks

**Comment by LazyLahtak** [comment]
@sjsingh85,

I cannot promise you the exact ETA for this. We have some features that need to be implemented previously to support keyboard navigation correctly.
