### ISSUE TITLE
Grid crashes when column count is changed if the TableFilterRow plugin is used

### ISSUE THREAD

**Issue by sometimesElen** [DevExpress/devextreme-reactive#2447]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
TableFilterRow plugin crashes Grid. 

### Expected Behaviour
Grid should work as without it.

### Steps to Reproduce
1. Open sample https://codesandbox.io/s/lucid-fermat-50vcb
2. Scroll the grid to the very right.
3. Press the  " Set DATA_SET_2" button under the grid.

Application crashes.
Сrash is reproduced if TableFilterRow  plugin is connected.

Sample 1 that crashes : https://codesandbox.io/s/lucid-fermat-50vcb
Sample 2 without TableFilterRow that doesn't crash https://codesandbox.io/s/restless-microservice-08tb4

### Environment

- devextreme-reactive: 2.0.2
- react: 16.8.6
- browser: Google Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Thank you for reporting the problem. The fix will be available in the nearest release.
