### ISSUE TITLE
InlineEditing with booleans as checkboxes

### ISSUE THREAD

**Issue by andrei-dascalu** [DevExpress/devextreme-reactive#2467]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello,

First of all, thank you so much for providing this set of amazing React components, made my life so much easier.
Second, I'm pretty much of a n00b with a stupid question: how can I use inline editing table but at the same time have boolean values editable as checkboxes? All the examples on the site seem to use simple text fields all around and while I've seen a couple of questions on Github centered around checkboxes, there wasn't any code or explanations that could help a n00b like me.

I found https://github.com/DevExpress/devextreme-reactive/issues/114 that may related to what I need but the links offered there return 404.

Thanks!

**Comment by LazyLahtak** [comment]
Hi @andrei-dascalu,

You can use the [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) plugin, to define your own editor for the specified columns. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-l7ulb) illustrating a custom editor and formatter for a boolean column. You can find some other examples in our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/).

If you have any further questions, let us know.
