### ISSUE TITLE
@devexpress/dx-react-grid-material-ui How do I leave a line in the edit state when I click the Save button?

### ISSUE THREAD

**Issue by SMaverick78** [DevExpress/devextreme-reactive#2468]
Hello!
TableEditColumn from @devexpress/dx-react-grid-material-ui
How do I leave a line in the edit state when I click the Save button? For string validation.
In the screenshot I circled the button that I need to make a (commit = disabled ) depending on the condition. From the parent component
![show edit button](https://user-images.githubusercontent.com/15866632/67092596-50008a80-f1b8-11e9-9f22-e2fd274f9b63.PNG)
Maybe there's another solution

**Comment by LazyLahtak** [comment]
Hi @SMaverick78,

Could you please provide us with your code or runnable project (for example, in [CodeSandbox](https://codesandbox.io/s/13qvz1qqzl))? This will help us solve this problem.

**Comment by SMaverick78** [comment]
root component

```
<Grid rows={rows} columns={columnFields} getRowId={getRowId}>
  <TableEditColumn
    width={120}
    showAddCommand
    showEditCommand
    showDeleteCommand
    commandComponent={TableEditCommandComponent}
  />
</Grid>
```
child component

```
export const commandTemplates = {
  add: (onClick, enableAdding, showAddCommand, { caption = 'Создать', isIcon = false } = {}) => {
    if (!showAddCommand) return null;

    return isIcon ? (
      <IconButton onClick={onClick} title="Создать новую запись">
        <AddIcon />
      </IconButton>
    ) : (
      <Button color="primary" onClick={onClick} title="Создать новую запись" disabled={!enableAdding}>
        {caption}
      </Button>
    );
  },
  edit: onClick => (
// edit button
    <IconButton onClick={onClick} title="Редактировать запись">
      <EditIcon />
    </IconButton>
  ),
};

const TableEditCommandComponent = ({ onExecute, enableAdding, showAddCommand, id }) => {
  const template = commandTemplates[id];
  if (template) {
    const onClick = e => {
      onExecute();

      e.stopPropagation();
    };
    return template(onClick, enableAdding, showAddCommand);
  }
  return undefined;
};

export default TableEditCommandComponent;
```

I need access from the root component to the child buttons. For example, the edit button. In the editor Manager from the root component. Is that possible? Tell me how to do it.

**Comment by LazyLahtak** [comment]
@SMaverick78,

Could you please clarify what you mean by 'need access from the root component to the child buttons'?
I've made an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-8zelj) illustrating TableEditColumn with custom icon buttons. Let us know if it meets your requirements.

**Comment by SMaverick78** [comment]
Thank you very much I think it will do. You can close the question.

**Comment by LazyLahtak** [comment]
You are welcome!
