### ISSUE TITLE
add demo data file url to site 

### ISSUE THREAD

**Issue by sayjeyhi** [DevExpress/devextreme-reactive#2469]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Scheduler
- [x] React Chart

It is better to have a link to demo-data file , which used in this demo source : 
https://devexpress.github.io/devextreme-reactive/react/chart/demos/area/step-area/

**Comment by MaximKudriavtsev** [comment]
Hi @sayjeyhi,

Thank you for your interest in our product. We have plans to publish all our demos in the Codesendbox online editor. Now you can find all demos data in our [source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-chart-demos/src/demo-data/data-vizualization.js#L134).
