### ISSUE TITLE
How to make DateNavigator visible by default ?

### ISSUE THREAD

**Issue by mara1esh** [DevExpress/devextreme-reactive#2481]
Hi guys. I'm trying to make `<DateNavigator />` component visible by default but it's unsuccessful. Can you advice me how to make the component opened by default ? 

What I want:
In the screen first component is  `<DateNavigator />`, second  `<Scheduler />`
<img width="498" alt="Screen Shot 2019-10-23 at 11 29 02 AM" src="https://user-images.githubusercontent.com/36697430/67373485-6035b280-f588-11e9-9f5c-72e453e20130.png">

**Comment by AryamnovEugeniy** [comment]
Hi,

You can customize the DateNavigator as described in this [issue](https://github.com/DevExpress/devextreme-reactive/issues/2384).

If you have further questions, let us know.
