### ISSUE TITLE
Columns headers near grouped headers renders incorrectly on horizontal scroll

### ISSUE THREAD

**Issue by divizionbyzero** [DevExpress/devextreme-reactive#2483]
Hi guys! I have an issue with React Grid. When scrolling the grid horizontally, columns that are next to grouped columns are rendered incorrectly, with an offset. This occurs exactly when the grouped columns disappear from view. 

1. Before scroll (group marked in yellow will cause a scrolling problem):
![image](https://user-images.githubusercontent.com/11850548/67380349-d93a0780-f592-11e9-9b97-da0cd86a5a1f.png)

2. Scrolling, before the problem. All column headers are on its right place...
![image](https://user-images.githubusercontent.com/11850548/67380427-fb338a00-f592-11e9-9076-1caf54442f69.png)

3. It happened. Column title "Type" not in its place, like others column names after. And I can see column "Status" in HTML, currently it almost out of viewport, but it renders on place, where should be group with columns.
![image](https://user-images.githubusercontent.com/11850548/67380803-8c0a6580-f593-11e9-873a-6dfc3960b030.png)

- devextreme-reactive: 2.1.2
- react: 16.8.22
- browser: Chrome version 77.0.3865.120
- bootstrap: 4.3.1
- react-bootstrap: 0.32.4

**Comment by LazyLahtak** [comment]
Hi @divizionbyzero,

Thank you for your report. Could you please provide us with your code? This will help us solve this problem.
