### ISSUE TITLE
Merge cells of row, for de facto grouping row

### ISSUE THREAD

**Issue by cobyrne09** [DevExpress/devextreme-reactive#2485]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I would like to make a standard row look like a grouped row, and allow the text to span the width of the row, as opposed to being confined to one cell. Essentially, is it possible to merge <td> cells with either the cellComponent or rowComponent? How would I go about this? Thank you!

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.0.0
- react: 16.8.6
- bootstrap: 4
- react-bootstrap: none

**Comment by LazyLahtak** [comment]
Hi @cobyrne09,

It doesn't clear what scenario you want to implement. Here are several ways how to achieve what you described:

* You can render only one column that be stretched to the full width.
* You can also render only one cell with colSpan equal to the number of columns (here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-l8w39)).
* You can just remove the cells` border.

Could you please clarify which scenario you mean?
