### ISSUE TITLE
Grid sometimes renders empty space when trying to group in Google Chrome in Material-UI Grouping demos

### ISSUE THREAD

**Issue by AryamnovEugeniy** [DevExpress/devextreme-reactive#2487]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Scrollbar appears

### Expected Behaviour
Scrollbar shouldn't appear

### Steps to Reproduce
Try grouping in, for example, [this demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/#controlled-mode) as shown in the gif below

### Screenshots
![Scrollbar](https://user-images.githubusercontent.com/51905811/67553990-1f1fd880-f717-11e9-9776-5467de73394d.gif)

### Environment

- devextreme-reactive: 2.1.2
- browser: Google Chrome

**Comment by LazyLahtak** [comment]
The bug relates to using grouping in iframe. Without iframe grouping works correctly. Here is an [example](https://smygu.csb.app/) created in codesandox.
