### ISSUE TITLE
Do VirtualTable rows need to have sequential id values?

### ISSUE THREAD

**Issue by tmaiaroto** [DevExpress/devextreme-reactive#2495]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I'm having a hard time with the lazy loading and caching, using the example from the docs, the initial load is * 2 and I set page size of 5 so it loads 10. Great. Then I scroll down and it loads the next 5 and adds them to the cache. Great.

Here's where it breaks. It does not seem to show the proper rows in the grid and I see all the stub/skeleton rows. It can't seem to determine what to show after it has now loaded 15 rows. It scrolls back to the top of the table as well.

I only have 36 total rows so far from the database. I use the id from my database records so they are not sequential.

I've been trying for literally days. Something isn't right. The requestedSkip and take might not be right. Pouring over for hours the difference between example and my own code and all I can really see is that the demo has row ids that are sequential; 1, 2, 3, 4...

Thanks

### Environment

- devextreme-reactive: 2.1.2
- react: 16.8.0
- browser: Chrome
- material-ui: 4.4.1

**Comment by tmaiaroto** [comment]
Also, after the second request, it loads no more. Even if I scroll up and down again.
VirtualTableState has

```
{
  "infiniteScrolling": true,
  "loading": false,
  "totalRowCount": 36,
  "pageSize": 5,
  "skip": 10,
  "getRows": "getRemoteRows()"
}
```

**Comment by tmaiaroto** [comment]
It just gets fed all sorts of wrong numbers. Especially when scrolling quickly. It can't figure out where it is or what to request or what it has loaded. Even when I finally get all 36 records loaded, if I scroll back up and down enough the cache loads the wrong stuff and the table area gets super huge. Rows load in incorrectly, etc.

Maybe more examples? Will this even work with smaller sets of rows? Or do I need like 100 at a time?

**Comment by LazyLahtak** [comment]
Hi @tmaiaroto,

The Virtual Table loads new rows on scrolling. This may not work if page size equals the rows count in viewport of the table. If your viewport shows 5 rows at a time, you should have a bigger page size (10, for example).
Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-kezwq) with 5 page size and another [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-otm64) with 10 page size.
Please let us know if this solution meets your requirements.

**Comment by tmaiaroto** [comment]
Hmm, ok. I think that part is fine. I see when `getRows` is called by the virtualtablestate and looks in order.

Now all I need is for the thing to not scroll back to the top on update. I'm using the row cache with memo like in the example. I think because the skip/take are updated in state it re-renders.

**Comment by tmaiaroto** [comment]
I got it. It was that I'm using 100% height so I made a custom `<Grid.Root>` for `rootComponent` ... but I wanted to include other things in there that became fixed. So I originally had: 

```
<Grid.Root
        {...props}
        classes={classes}
        style={{ height: '100%' }}
      >
        {gridRootChildren}
        {props.children}
</Grid.Root>
```

Not only that, but I defined this as a function component within the component that was also rendering the grid. So I moved it outside of that, removed the custom children and just made it short and sweet _(outside the main component rendering the grid):_

```
const Root = props => {
  const useStyles = makeStyles(borderedTable);
  const classes = useStyles();
  return <Grid.Root {...props} classes={classes} style={{ height: '100%' }} />;
};
```

The custom children that I wanted fixed? I put those into a plugin that targets the `toolbarContent` template (a very small boilerplate plugin), use like so: 
```<ToolbarChildrenWrapper>{childrenComponentsToFix}</ToolbarChildrenWrapper>```

So the toolbar area stays fixed and accomplishes what I was after with the grid root.

Is there any other way to pass custom components into a fixed area? I don't mind using the toolbar for this, but it took me a good while to learn about plugins and then this whole issue with the updates moving the scrollbar back up, etc. Literally poured days and days into this. Maybe some simpler solution would have steered me away from this issue.

Anyway, now that I can actually get it working, I'm super excited to use your stuff soon! It's a really awesome framework. Thanks!!

**Comment by LazyLahtak** [comment]
@tmaiaroto,

It is good news that the problem has been resolved.
To place custom components in fixed area without using the Toolbar, you can use 'header' and 'footer' templates. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-qioiz) illustrating how to do that.
If you have any further questions, let us know.

**Comment by tmaiaroto** [comment]
Ah, perfect, thanks! I realized I already used that position to move the add row button out of the column header before. By the way, is there a full list of all your code sandbox examples somewhere? I'm trying to navigate code sandbox itself without much luck...can't seem to find any sort of "by same author" type thing.

**Comment by LazyLahtak** [comment]
@tmaiaroto 

We are making the new site where you can open each example in codesandbox.
