### ISSUE TITLE
Faced with the problem of navigation in the table row with the TAB key. 

### ISSUE THREAD

**Issue by SMaverick78** [DevExpress/devextreme-reactive#2500]
Hello! I use @devexpress/dx-react-grid-material-ui. Faced with the problem of navigation in the table row with the TAB key. The table has columns editable(input, select) and not editable (to output just values). These columns alternate in different ways. The table is three browser screens wide. The last column is always editable(input) and is at the end 3 of the browser screen. If the penultimate column is not editable or 2 columns. Tab navigation does not work and does not reach the end of the third browser screen.  As far as I understand the last column does not fall within the visibility of the browser screen. And for this reason, the tab key navigation does not work in a row. ((( Can you correct that?

**Comment by AryamnovEugeniy** [comment]
Hi,

I wasn't able to reproduce the issue. Could you update my example to reproduce the incorrect behaviour?
