### ISSUE TITLE
Redesign Table Title 

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2503]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

 I'm using ...
- [ x] React Grid

### Description
I am trying to change the header title,the font size,font weight and background color of the Table Title, can someone give me a little guide. The documentation is not really detailed with many examples

**Comment by AryamnovEugeniy** [comment]
Hello,

You can customize the [TableHeaderRow ](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/)component. To do that, follow [this guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#customize-the-appearance).
But we do not have Table Title component. Please, provide additional information on what you want to achieve so we could help you.

**Comment by lutakyn** [comment]
I want to change the Header Titles,the background color of the table header as well

**Comment by AryamnovEugeniy** [comment]
Hello,

You can customize either [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/)'s [row component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablerowprops) or [cell component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowcellprops), or both. In [this demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-13i1f) I've overridden the `TableHeaderRow`'s `cellComponent` and changed the text color, background color and font weight.
Does this solutions meet your requirements?
If you have further questions, feel free to ask them.
