### ISSUE TITLE
Page freezed when reordering

### ISSUE THREAD

**Issue by chr22** [DevExpress/devextreme-reactive#2510]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Sometimes when i drag a column the whole page freezes and the only thing I can do to make the page responsive again is to reload the page.

It looks like in the image below where the column I am dragging is floating and the page is overlayed by a div element with fixed position.

![image](https://user-images.githubusercontent.com/3649594/68033718-8b26b180-fcc0-11e9-928c-50f11f9ee3cf.png)

### Expected Behaviour

That I can reorder columns without the page freezes.

### Steps to Reproduce

It only happends rarely and I can't see a pattern.
My setup is as below:
- Virtual Table
- Lazy loading
- Controlled Mode (Redux)
- Reorder
- Resize
- Sorting
- Multiple custom formatterComponents
- Bootstrap styling
- Custom header component that adds an icon with hover
- No infinite scrolling

### Environment

- devextreme-reactive: 2.2.0
- react: 16.11.0
- browser: Chrome 78
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hi,

I couldn't reproduce this issue. Could you, please, provide us with your code? It would help us solve your problem.
