### ISSUE TITLE
Change Cell Text Color depending of conditions from data

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2512]
### Description
   I want to change the test color of a single cell depending on the status type,find a sample image .
When the status = pending,color should be yellow,when status = blue,color should be blue, when status = declined,color should be red

![blueeeeeee](https://user-images.githubusercontent.com/32960420/68138178-0afe8700-ff20-11e9-9cc6-fb7e0fba2962.jpg)

## Sample Code
      data= [
         created_at: "2019-11-02 14:22:48.021912"
         sendername: "WittyBuzz"
        status: "1"
        updated_at: "2019-11-02 14:22:48.021912"
        user_id: 2
        uuid: "d30dfe9e-b1c8-4a82-9694-74c91f124037",
         created_at: "2019-11-02 14:22:48.021912"
         sendername: "WittyBuzz"
        status: "0"
        updated_at: "2019-11-02 14:22:48.021912"
        user_id: 3
        uuid: "d30dfe9e-b1c8-4a82-9694-74c91f124037",
       created_at: "2019-11-02 14:22:48.021912"
         sendername: "WittyBuzz"
        status: "2"
        updated_at: "2019-11-02 14:22:48.021912"
        user_id: 4
        uuid: "d30dfe9e-b1c8-4a82-9694-74c91f124037"]
   
        var newList = []
            var status =''
            var senderNameList = response.data.data.data
           //console.log('sender list',senderNameList)
           senderNameList.forEach(item=>{
             if(item.status == "0"){
              status="Pending"
             }
            else if(item.status == "1"){
              status="Approved"
             }
             else if(item.status == "3"){
              status="Declined"
             }
             newList.push({
               status : status,
               user_id:item.user_id,
               uuid:item.uuid,
               sendername:item.sendername,
               created_at:item.created_at,
               updated_at:item.updated_at
             })
            
             return newList
           })  
      
    
      
### I'm using ...

- [x ] React Grid

### Environment
      "@devexpress/dx-react-core": "^2.2.0",
      "@devexpress/dx-react-grid": "^2.2.0",
      "@devexpress/dx-react-grid-bootstrap4": "^2.2.0",

**Comment by AryamnovEugeniy** [comment]
Hi,

You can override the [Table.cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) and change its `color` CSS props as shown in [this demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-zt7zx).
Does this solution meet your requirements?
[Here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/) you can find more demos demonstrating customization of different Grid's components.
If you have other questions, don't hesitate to ask them.

**Comment by lutakyn** [comment]
No, it didn't I am using the bootstrap not material UI. I tried my best to make it work,it didn't pick the colors.can you send the bootstrap version of the solution?

**Comment by AryamnovEugeniy** [comment]
I've updated the sample for Bootstrap 4. [Here](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-492dx) it is.
Does this solution meet your requirements?

**Comment by lutakyn** [comment]
I have a GridUtil component which I want to make it reusable so I wanted to pass cellComponent as props.find the example below


  
  ```
 const GridUtils = (props) => {
 const {rows,columns} = props
   const [pageSizes] = useState([10, 20,30,40,50,100]);

   const [selection, setSelection] = useState([]);
    return(
        <div className="card">
        <Grid 
          rows={rows || []} 
          columns={columns || []}>
          <PagingState/>
          <SearchState defaultValue="" />
          <SelectionState
            selection={selection}
            onSelectionChange={setSelection}
          />
  
   
          <IntegratedPaging />
          <IntegratedSelection />
          <IntegratedFiltering />
          <Table 
           rowComponent={TableRow} 
           cellComponent={props.cellComponent}//getting props here didn't work
            tableComponent={TableComponent} />
          <TableHeaderRow/>
          <Toolbar />
          <SearchPanel />
          <PagingPanel pageSizes={pageSizes} />
        </Grid>
  
      </div>

    )
  }
```

I am now passing data down to it as below,It is not having any effects on the text colors as you did in the bootstrap example.you can add corrections to it 
```
const columns = [
  { name: "user_id", title: "ID" },
  
  { name: "sendername", title: "Sender Name" },
  { name: "created_at", title: "Date Created" },
  { name: "status", title: "Status" },
  { name: "updated_at", title: "Date Updated" }
];
 const rows =[
{ created_at: "2019-11-02 14:22:48.021912"
sendername: "Test"
status: "Approved"
updated_at: "2019-11-02 14:22:48.021912"
user_id: 2
uuid: "d30dfe9e-b1c8-4a82-9694-74c91f124037"
},
{
created_at: "2019-11-02 14:22:48.027888"
sendername: "Test2"
status: "Approved"
updated_at: "2019-11-02 14:22:48.027888"
user_id: 2
uuid: "bc3f41ec-6b11-4427-a32a-2ba273f0c868"
}
]


const getStyleByValue = value => {
  console.log("table value",value)

  if (value == "Pending") return { color: "yellow" };
  if (value == "Declined") return { color: "red" };
  if (value == "Approved") return { color: "blue" };
  return undefined;
};

const TableCell = ({ value, classes, style, ...restProps }) => (
  // console.log("table value",value)
  <Table.Cell
    style={{ ...getStyleByValue(value), ...style }}
    value={value}
    {...restProps}
  />
);

class SenderNames extends React.Component {

  render() {
    return (
      <div>

        <GridUtils 
        columns={columns} 
        rows={rows} 
        cellComponent={TableCell}
        />

      </div>
    );
  }
}
```

**Comment by AryamnovEugeniy** [comment]
Hi again,

I've made an example based on the code you sent. [Here ](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-qkeyk)it is. Text color differs depending on the `status` property value. But I removed `rowComponent`'s and `tableComponent`'s customization since you didn't provide these components. Does this work as you want it to?

**Comment by lutakyn** [comment]
this is the code for rowComponent and tabelComponent,I hope it is not blocking the change you made
```
const TableComponent = ({ ...restProps }) => (
    <Table.Table {...restProps} className="table-striped" />
  );

  //on table row click
  const TableRow = ({ classes, row, ...restProps }) => (
    <Table.Row
      {...restProps}
      // eslint-disable-next-line no-alert
      onClick={() => alert(JSON.stringify(row))}
      // className={classes.tableStriped}
    />
  );
```

**Comment by AryamnovEugeniy** [comment]
I've updated the [sample](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-qkeyk) using components you sent. And I couldn't reproduce the issue. Is this solutions suitable for you?
