### ISSUE TITLE
Can I lazy load all rows into virtual table?

### ISSUE THREAD

**Issue by tmaiaroto** [DevExpress/devextreme-reactive#2519]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is it possible to load all rows into the virtual table? Rather than having VirtualTableState maintain 3 "pages" ... I'd like to try loading (in a paginated fashion) all the data my API would return into the table.

I realize the current solution was for performance, but the state of my app and all the data formatters is leading to performance issues. Due to that, the current solution can get a bit messed up if you scroll around quickly. It can even max out on the number of updates being made if you really drag the scroll bar around. I believe this is due to how long it takes a row to render (even when pulled from the row cache).

So my thinking is I might be better off not loading/unloading rows at all and just keep appending on scroll.

Thanks!

### Environment

- devextreme-reactive: 2.2.0
- react: 16.8.0
- browser: Chrome
- material-ui: 4.4.1

**Comment by AryamnovEugeniy** [comment]
Hi,

The number of rows loaded in lazy loading is equal to the doubled page size. So, you should set the [VirtualTableState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table-state/)'s`virtualPageSize` equal to the half of the total number of your rows as I've done in [this sample](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-813w2) (in my sample the total number of rows is `MAX_ROWS`). If you have an odd number of rows in your table, you should round it down, for instance, using `Math.floor, as I've done in my example.

**Comment by tmaiaroto** [comment]
Thanks, but I'm not sure that's quite what I'm after. I want to scroll to load, say, 50 at a time...but then keep 250 rows loaded forever. So when I scroll backwards, it won't fetch them from cache or API.

So if I set the virtual page size to 125 (which I could only do after the first API response when I know how many rows I have), then it'll adjust the skip/take, right? Starting with 50, I'll get 0,100 initially. The next request would be 100,125. But I don't want to get 125 rows in one request. I want to get 25 (or 50 even) at a time until I have loaded all of them.

Then of course persist them in the table so when I scroll back up, it doesn't need to fetch from the row cache or API again. Setting the virtual page size may keep a larger number actively loaded, but it also isn't known immediately and it will change the API request.

**Comment by AryamnovEugeniy** [comment]
Could you please provide us with your code or your data formatters or could you update my example in the message above so the problem would appear? Because the Lazy Loading assumes that you will have to load data. And your example would help us sooner solve the issue.

**Comment by tmaiaroto** [comment]
I've been able to improve performance with some tricks on the formatters and such, but ultimately I believe things are slow for me because the virtual table is re-rendering the rowComponent so often. New rows on scroll up/down and new columns on scroll left/right. The children are changing in those cases and it's leading to many other things in turn re-rendering.

In this case, this optimization technique is degrading performance. I can understand changes for collapsed columns, column visibility, etc. But the viewport visibility bounds I think leads to more problems. I thought the only time the rows would change would be on up/down scrolling to get more rows. I didn't realize it's called when things enter/leave the viewport.

Could I use the normal `<Table>` component and somehow append to it, maintaining scroll position?

**Comment by AryamnovEugeniy** [comment]
Hi,

You could wrap the Grid into a container (for instance, a div) with a fixed height and use the Table instead of the VirtualTable. In this case, you can handle the [onScroll](https://www.w3schools.com/jsref/event_onscroll.asp) event of the container and when the scrollTop + container's height is equal to scrollHeight, you should update your data. However, the 'Table' plugin renders all the rows you provide to it on every update. If you have lots of rows (for example, more than 1000) or complex elements (such as complex formatters), performance will be much worse than with 'VirtualTable'.

**Comment by AryamnovEugeniy** [comment]
We cannot know what is causing your problems without an example. Could you provide us with a working code which reproduces the issue?
