### ISSUE TITLE
InfiniteScroll grid showing placeholder/skeleton rows with a limited number of total rows

### ISSUE THREAD

**Issue by psmod2** [DevExpress/devextreme-reactive#2532]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm using Lazy Loading along with Infinite Scroll, the total number of rows is being set, however it the table continues to show skeleton/placeholder rows.

### Expected Behaviour

I'd expect say in this example below (see screenshot), there are only 3 rows of data, that the table only shows those 3, along with no vertical scroll or placeholder rows.

If I add estimatedRowHeight like so `<VirtualTable estimatedRowHeight={0} />` it behaves a bit better, but why would I need to set it to 0? And also its not exactly correct in that:
1 - there's a small space after the last row
2 - there's white space (I guess set by a default height) at the end of the table:

![Screen Shot 2019-11-13 at 10 37 51](https://user-images.githubusercontent.com/15928263/68725500-fe55ef00-0601-11ea-8bfc-4c34646a0e24.png)

### Steps to Reproduce

Here's the code:

```
<InfiniteScrollTableContextProvider error={error} columns={columns} onRefresh={refresh} getPath={getPath}>
			<Grid rootComponent={RootComponent} rows={rows} columns={gridColumns} getRowId={row => (row as IndexedRow<ROW>)._index}>
				<DragDropProvider />
				<VirtualTableState
					infiniteScrolling
					// By taking error into consideration, the table can look like it is loading when the error overlay is active
					loading={loading || error}
					totalRowCount={totalCount}
					pageSize={pageSize}
					skip={skip}
					getRows={getRows}
				/>
				<SearchState onValueChange={setSearchValue} />
				<SortingState sorting={sorting} onSortingChange={changeSorting} />
				<VirtualTable />
				{showLinkColumn && <DataTypeProvider key={"linkProvider"} for={["link"]} formatterComponent={LinkFormatter} />}
				{dataTypeProviders}
				<TableColumnVisibility hiddenColumnNames={hiddenColumns} onHiddenColumnNamesChange={changeHiddenColumns} />
				<TableColumnReordering order={columnOrder} onOrderChange={changeColumnOrder} />
				<TableColumnResizing defaultColumnWidths={defaultColumnWidths} />
				<TableHeaderRow showSortingControls sortLabelComponent={SortLabel} />
				<Toolbar />
				{showSearchField && <SearchPanel />}
				<RefreshTableControl disabled={loading} onClick={refresh} />
				<ColumnChooser itemComponent={ToggleColumnItem} />
				<TableFixedColumns leftColumns={fixedColumns} />
			</Grid>
		</InfiniteScrollTableContextProvider>
```

### Screenshots

![Screen Shot 2019-11-13 at 10 11 11](https://user-images.githubusercontent.com/15928263/68724188-23e0f980-05fe-11ea-8e65-51a0caa7d3a5.png)

And it scrolls all the way to the bottom

![Screen Shot 2019-11-13 at 10 11 23](https://user-images.githubusercontent.com/15928263/68724194-26435380-05fe-11ea-910e-5e2bb31a8523.png)

### Environment

- "@devexpress/dx-react-core": "^2.0.5",
- "@devexpress/dx-react-grid": "^2.0.5",
- "@devexpress/dx-react-grid-material-ui": "^2.0.5",
- react: 16.9.0
- browser: Chrome 78.0.3904.97

**Comment by AryamnovEugeniy** [comment]
Hi,

Thank you for reporting the issue. But we do not have enough data to reproduce it. Could you provide us with a working sample where your issue is reproduced? This would help us sooner solve your problem.

**Comment by psmod2** [comment]
Sure - is there something specific you need?

**Comment by AryamnovEugeniy** [comment]
We do not have information, first of all, on what properties you use in the VirtualTableState. You sent us only your render method but this is not enough. The best would be a working sample in [CodeSandbox](https://codesandbox.io/s/13qvz1qqzl), for example.
