### ISSUE TITLE
Need to customise value axis steps.

### ISSUE THREAD

**Issue by simerdev** [DevExpress/devextreme-reactive#2533]
I am creating line chart, but I am facing a problem. My values varies from 0 to 5, and the graph values axis are in decimal points like _0,0.5,1,1.5,2_ and so on till 5. But I do not need these decimal points. I need simple value axis like _0,1,2,3,4,5._ Is there any way with which I can achieve this. 

**PS**: When the value range is bigger like 0 to 10, then it works fine, like don't get decimal values, but when the range is small like in my case 0 to 5 then only I face this issue. 

**Here is screenshot of the issue** https://prnt.sc/pw8592

**Comment by Krijovnick** [comment]
Hi @simerdev,

To avoid decimal labels, you can use the `labelComponent` property in the [ValueAxis](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/value-axis/) plugin like in the following [example](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-723d7).

**Comment by simerdev** [comment]
Ok Thanks @Krijovnick . But what if I want to remove the lines for decimals.

**Comment by Krijovnick** [comment]
@simerdev You can filter grid lines using the `gridComponent` property like in the updated [example](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-9do0d).
