### ISSUE TITLE
TableInlineCellEditing issues with EditingState columnExtensions editingEnabled: false

### ISSUE THREAD

**Issue by foxart78** [DevExpress/devextreme-reactive#2535]
Hi, I've an issue when try to use TableInlineCellEditing in combination with <EditingState ... /> for disabling editing on some columns. 
When I click over cell where the editing was disabled, the cell become an editable control with the value correctly disabled. But when I click outside the che cell area, the cell remain in edit mode!

Moreover, from this moment if I click over other editable cell of others row I obtain this situation:

![image](https://user-images.githubusercontent.com/7845955/68862964-b06ae500-06ee-11ea-9c8f-e85df553b6b1.png)

This is a portion of my code:

```
                    <EditingState
                        onCommitChanges={this.commitChanges}
                        //defaultEditingRowIds={[0]}
                        columnExtensions={[
                            { columnName: 'bill', editingEnabled: false },
                            { columnName: 'date', editingEnabled: false }
                        ]}
                    />
.....
                    <TableInlineCellEditing
                        selectTextOnEditStart={true}
                    />
```

**Comment by LazyLahtak** [comment]
@foxart78,

Thank you for reporting the problem. We will fix it soon.
