### ISSUE TITLE
How to achieve a "Matrix Report" with Table

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2538]
Hi, i am try to accomplish a "Matrix Report" with the "dx-react-grid", which would looks like this :

![image](https://user-images.githubusercontent.com/19796912/69058036-dd502c80-0a4d-11ea-85f2-233836cd2a51.png)

I know that i can render this header with "TableBandHeader" component, but what confusing me is , how could i render the left side content with the "Table" component ? Is there any idea to achieve this, or its just impossible ?

**Comment by AryamnovEugeniy** [comment]
Hello,

This feature is not implemented in the Reactive Grid. But our other product, DevExtreme PivotGrid, allows to achieve what you have described. You may try it. [Here] (https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/Overview/React/Light/)is a demo.

If you have any other questions, don't hesitate to ask them.

**Comment by yl1215** [comment]
> Hello,
> 
> This feature is not implemented in the Reactive Grid. But our other product, DevExtreme PivotGrid, allows to achieve what you have described. You may try it. [Here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/Overview/React/Light/) is a demo.
> Does this solution suit you?
> 
> If you have any other questions, don't hesitate to ask them.

Yes, this is what i want! thanks man :)

**Comment by yl1215** [comment]
> Hello,
> 
> This feature is not implemented in the Reactive Grid. But our other product, DevExtreme PivotGrid, allows to achieve what you have described. You may try it. [Here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/Overview/React/Light/) is a demo.
> Does this solution suit you?
> 
> If you have any other questions, don't hesitate to ask them.

But if i want to achieve this with the Table component, which plugin could i reference to.

**Comment by yl1215** [comment]
> Hello,
> 
> This feature is not implemented in the Reactive Grid. But our other product, DevExtreme PivotGrid, allows to achieve what you have described. You may try it. [Here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/Overview/React/Light/) is a demo.
> Does this solution suit you?
> 
> If you have any other questions, don't hesitate to ask them.

I mean to write my own plugin.

**Comment by LazyLahtak** [comment]
Hi @yl1215,

Here is our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) on how to create custom plugins.
Also, I made an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xkwz2) illustrating how to implement the feature you request.
Please let us know if this solution meets your requirements.

**Comment by yl1215** [comment]
> Hi @yl1215,
> 
> Here is our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) on how to create custom plugins.
> Also, I made an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xkwz2) illustrating how to implement the feature you request.
> Please let us know if this solution meets your requirements.

Yes, its useful, very thanks. :)

**Comment by LazyLahtak** [comment]
You are welcome!
