### ISSUE TITLE
React Grid: implement a custom DataTypeProvider with @material-ui/pickers when edit a date (datepicker)

### ISSUE THREAD

**Issue by ihatem** [DevExpress/devextreme-reactive#2539]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

this is my [CodeSandbox example](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-wi6m2) 

I wanted to implement a custom `DataTypeProvider` with a custom `editorComponent` which is a `DatePicker`. 

First, I tried the `@material-ui/pickers` but it provides a special date value: 
```javascript
// value provided by @material-ui/pickers
// Valid Date :
new Date().toString
// => Valid date with this format : "Mon Nov 18 2019 23:41:58 GMT+0100 (Central European Standard Time)" 
// Invalid Date
"Invalid Date"
// else it provides a "Invalid Date" String
```

We can use a controlled component like this : 
```javascript
const LookupEditor = () => {
    const [dateValue, setDateValue] = useState(new Date());
    return (
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <KeyboardDatePicker
          disableToolbar
          variant="inline"
          format="MM/dd/yyyy"
          id="date-picker-inline"
          value={dateValue}
          onChange={date => setDateValue(date)} // date have a new Date().toString() format like explained above
          KeyboardButtonProps={{
            "aria-label": "change date"
          }}
        />
      </MuiPickersUtilsProvider>
    );
  };
```

but even with the native `TextField` component from `@material-ui/core`. We can choose a date with the picker but it broke when we want to type the date manually: 

```javascript
const LookupEditor = ({ value, onValueChange }) => {
    return (
      <TextField
        id="date"
        type="date"
        value={value ? value : format(new Date(), "yyyy-MM-dd")}
        onChange={e => {
          onValueChange(e.target.value);
        }}
        InputLabelProps={{
          shrink: true
        }}
      />
    );
  };
```
Please refer to my [CodeSandbox example](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-wi6m2) for a full demo.

As I understood, `e.target.value` is different from the `value` that `editorComponent` expect. 

How can I do to implement my datepicker properly and handling the value change ? 

### Environment

- devextreme-reactive: 2.2.1
- react: 16.10.2
- browser: Firefox Developer Edition 71.0b10
- material-ui: 4.5.1

**Comment by AryamnovEugeniy** [comment]
Hello,

The `Date` value you get from `KeyboardDatePicker` is not formatted correctly. You should format to 'mm/dd/yyyy' format. I updated your [demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-custom-editing-cell-datepicker-x4i7o). Here I use [moment](https://momentjs.com/) to format the date correctly inside `onChange`:

```
onChange={date => {
    onValueChange(moment(date).format('L'));
}}
```

Let us know if this solution suits you.

**Comment by ihatem** [comment]
I already tried to do that with `date-fns` but even with `moment` it still the same problem. We can choose the date from the picker but we can't type it manually: label tells you Invalid date and the value doesn't change. 

Here's my [codesandbox](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-custom-editing-cell-datepicker-o8mfq) updated with your solution.

**Comment by AryamnovEugeniy** [comment]
Hello,

Sorry for the late response.
You shouldn't create components inside the render method (see our [guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/) on how to optimize performance) because it makes performance of your app worse. In your case, every time you type a character, you create a new DatePicker and it does not remember the previous date. So, first of all, you should place the DatePicker component outside the render method and, secondly. you should check whether the date is valid before calling `onValueChange` so that you do not update your state. In that case, the DatePicker will check the date correctly. Here is a [working sample](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-custom-editing-cell-datepicker-o7gcj).
