### ISSUE TITLE
Limit of appointments per cell

### ISSUE THREAD

**Issue by mara1esh** [DevExpress/devextreme-reactive#2542]
Hi guys. I have a question about work with appointments. How can i limit the display of appointments in a cell? I mean I want to make it similar as in google calendar (screenshot below). So if I have 10 appointments per day I want to display only part of them

![Screen Shot 2019-11-19 at 4 13 52 PM](https://user-images.githubusercontent.com/36697430/69153920-bb0aed00-0ae7-11ea-82f1-42381f723541.png)

**Comment by AryamnovEugeniy** [comment]
Hi,

Thank you for your interest in our product. This feature hasn't been implemented yet. But it has a very high priority in our plans. You can follow [this issue](https://github.com/DevExpress/devextreme-reactive/issues/2231)

**Comment by mara1esh** [comment]
@AryamnovEugeniy thank you for the answer,

in this case, can you advice me, which component contains array of day appointments and can I get override it?

**Comment by AryamnovEugeniy** [comment]
@mara1esh hello again,

I've created a demo [here](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-1uef4) where I get the list of appointments. You'll have to create a new plugin ([here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) is our guide on how to do this) where you'll have to change appointments you get from "appointments" [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) using your own "appointments" Getter with computed value (as I've done in the sample. I created a computed Getter and used `console.log` to show all the appointments).
