### ISSUE TITLE
Material-ui tab, not all columns appear

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2550]
https://codesandbox.io/s/shy-snowflake-z3d0p

material-ui tab doesn't show all the columns of the table I'm using. 
The problem is the second menu. 
When I put the table in the first menu does not occur. 
But when I switch to the second menu, the problem occurs, it only shows the first 2 columns. 
Cannot make full width adjustment.

https://material-ui.com/components/tabs/

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

Thank you for your report. We need additional time to research this behaviour.

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

We found that that fix of this issue breaks the number of other popular scenarios and affect a lot of users.  So, decided to revert it in this PR here: #2771.

We also double-checked this particular case and found you can overcome the issue using this approach: https://codesandbox.io/s/keen-ride-uojre
