### ISSUE TITLE
@devexpress/dx-react-grid How do I do сustomize Keyboard Navigation Cell.

### ISSUE THREAD

**Issue by SMaverick78** [DevExpress/devextreme-reactive#2558]
Hello! If the ability to do customize the navigation keyboard? As in the Example at this link https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CustomizeKeyboardNavigation/React/Light/. in this example, you can use the onfocusedcellchanging function to get column width data. About the position in which the cell is located. If anything similar in @devexpress/dx-react-grid.  If there is an opportunity to make an example. I will be very grateful to you.

**Comment by LazyLahtak** [comment]
Hi @SMaverick78,

For now, our Grid doesn't support keyboard navigation, but we have a similar issue. You can follow [this topic](#1966) to be informed about our progress.
