### ISSUE TITLE
Cell Action and Icon

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2560]
I'm using ...
- [ ] React Grid

### Description
I am able to show the data and play with the colours as in the image below.However I find it difficult to add 3 icons with their actions on a single row. Please any help on it.
Any sample of code to assist me on this will help me.i am using bootstrap and material ui

![20191127_000126](https://user-images.githubusercontent.com/32960420/69682363-15d4b380-10a9-11ea-8b1f-0efeddc7cb8c.jpg)

### Environment
- devextreme-reactive
- react
-bootstrap

**Comment by AryamnovEugeniy** [comment]
Hello,

I've added three icons to the last cell of every row and actions to each icon [this demo](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-gcrp8).
Does this meet your requirements?
