### ISSUE TITLE
How to show the border of every cell in the table, furthermore, the border could be dragged and resizing the column.

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2561]
Hi, i got a problem of, how to show the border of every cell in the table, furthermore, the border could be dragged and resizing the column. Something like this pic.

![image](https://user-images.githubusercontent.com/19796912/69715117-ac08e800-1142-11ea-9f10-cc71a7793307.png)

Those border could be dragged.

**Comment by AryamnovEugeniy** [comment]
Hello,

I've created an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-uovxf) where I show all borders (except external ones). It may be done with Table's [Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) customization.
And also, you can resize the columns by dragging Table Header's borders using [TableColumnResizing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/) plugin.
Does this solution suit you?

If you have any other questions, feel free to contact us.

**Comment by yl1215** [comment]
Yes, this is useful! I have some other problems and i would open a new issue. Very thanks!

**Comment by AryamnovEugeniy** [comment]
I'm glad that it was useful!
