### ISSUE TITLE
Pagination buttons styling (Material-UI)

### ISSUE THREAD

**Issue by cohancarpentier** [DevExpress/devextreme-reactive#2563]
tl;dr we would like to be able to change the `color` attribute of the "Previous" and "Next" button in the Material-UI pagination component.

### I'm using ...

- `@devexpress/dx-react-grid-material-ui`
- `PagingPanel`

### Description

We'd like to be able to change the pagination button color to `primary` without having to fork this project.

**Comment by MaximKudriavtsev** [comment]
Hi @cohancarpentier,

We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/1021).
