### ISSUE TITLE
DetailRow does not working when using LazyLoading VirtualTable

### ISSUE THREAD

**Issue by psmod2** [DevExpress/devextreme-reactive#2564]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When I click on a DetailRow, all `<tr>`s, except  the first appear to vanish:

So this is before I click on the expand detail view row:

![Screen Shot 2019-11-28 at 11 28 56](https://user-images.githubusercontent.com/15928263/69772258-c8ecfc00-11d2-11ea-91fa-bd494c2dfc38.png)

All the table rows are present.

But once i click on the table row, all but first disappear:
![Screen Shot 2019-11-28 at 11 29 09](https://user-images.githubusercontent.com/15928263/69772324-f0dc5f80-11d2-11ea-9fad-1d95dfc0152d.png)

Here is the grid:

```
<Grid rootComponent={RootComponent} rows={rows} columns={gridColumns} getRowId={row => (row as IndexedRow<ROW>)._index}>
				<DragDropProvider />
				<VirtualTableState
					infiniteScrolling={loading || forceReload || totalCount > skip + pageSize * 2}
					loading={loading || error || forceReload}
					totalRowCount={totalCount}
					pageSize={pageSize}
					skip={skip}
					getRows={getRows}
				/>
				<RowDetailState />
				<SearchState onValueChange={setSearchValue} />
				<SortingState sorting={sorting} onSortingChange={changeSorting} />
				<VirtualTable estimatedRowHeight={60} />
				{showLinkColumn && <DataTypeProvider key={"linkProvider"} for={["link"]} formatterComponent={LinkFormatter} />}
				{dataTypeProviders}
				<TableColumnVisibility hiddenColumnNames={hiddenColumns} onHiddenColumnNamesChange={changeHiddenColumns} />
				<TableColumnReordering order={columnOrder} onOrderChange={changeColumnOrder} />
				<TableColumnResizing defaultColumnWidths={defaultColumnWidths} />
				<TableHeaderRow showSortingControls sortLabelComponent={SortLabel} />
				{showDetailRow && <TableRowDetail contentComponent={showDetailRow} />}
				<Toolbar />
				{showSearchField && <SearchPanel />}
				<RefreshTableControl disabled={loading} onClick={refresh} />
				<ColumnChooser itemComponent={ToggleColumnItem} />
				<TableFixedColumns leftColumns={fixedColumns} />
			</Grid>
```

### Expected Behaviour

The detail row should appear as expected.

### Steps to Reproduce

- Using Lazy Loading
- Add a detail row
- The row isn't expanded

Is there something additional I need to do, or is it actually supported with VirtualTableState

Thanks

### Environment

- "@devexpress/dx-react-core": "^2.0.5",
- "@devexpress/dx-react-grid": "^2.0.5",
- "@devexpress/dx-react-grid-material-ui": "^2.0.5",
- react: 16.9.0
- browser: Chrome 78.0.3904.97

**Comment by LazyLahtak** [comment]
Hi @psmod2,

Could you please provide a project or modify my [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-1gsbg) to reproduce this behavior?

**Comment by psmod2** [comment]
Hmm - looks like its something to do with the `VIRTUAL_PAGE_SIZE = 1`. if I set to 1, then I can reproduce the error.

**Comment by LazyLahtak** [comment]
@psmod2,

`VIRTUAL_PAGE_SIZE` shouldn't be less than visible rows count. For example, if you see about 10 rows in viewport, `VIRTUAL_PAGE_SIZE` should be equal or more than 10.

**Comment by psmod2** [comment]
Ok - I just noticed on my side, if I set the totalCount at the start to `0` its working as expected.

Perhaps all this is just down to some behaviour in code on my side. I'll investigate a little more.

**Comment by LazyLahtak** [comment]
@psmod2,

If you have any further questions, feel free to contact us.

**Comment by psmod2** [comment]
@LazyLahtak 
So I can still reproduce the error - setting the total count to 0 isn't really a solution for me.

Anyway, if you scroll to the bottom of the table (say by setting the max rows to something like 100) - then try to open the last row. You'll see the phantom rows appearing.

**Comment by psmod2** [comment]
Ok - got it
I had to add some logic to `onExpandedRowIdsChange` to increment or decrement the total number of rows.
