### ISSUE TITLE
How to customize the header cell but still engaged with the "TableColumnResizing" component .

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2565]
The problem is that when i try to customize the background color of header cell , i have to replace it with a new cell component, and then i lost the resize of the column although i used the  TableColumnResizing component.

**Comment by MaximKudriavtsev** [comment]
Hi @yl1215,

We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/1515).

**Comment by yl1215** [comment]
Yes, its useful,  very thanks.

**Comment by MaximKudriavtsev** [comment]
@yl1215 you are welcome!

**Comment by yl1215** [comment]
By the way，any idea to achieve the resize of table body ... I mean, not only to drag the header's body, also the border of table body ....

**Comment by MaximKudriavtsev** [comment]
@yl1215,

Thank you for your suggestion, but we have no plans to enhance the column resizing feature now.
