### ISSUE TITLE
Configure TableColumnReordering to have pinned columns (should NOT re-order)

### ISSUE THREAD

**Issue by shanedev6** [DevExpress/devextreme-reactive#2567]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
 Is it possible to have fixed/pinned columns so that the TableColumnReordering will not reorder specific columns?

### Environment

- devextreme-reactive: 2.3.0
- react: 16.12.0
- browser: MacOS Chrome
- bootstrap: 4.4.0
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

You can use [TableColumnReordeing in controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/#controlled-mode) to forbid reordering of the necessary columns. You can also disable dragging on a column header cell. [Here](https://codesandbox.io/s/flamboyant-fog-2i02c) is an example demonstrating this behaviour. Does this suit you?

**Comment by shanedev6** [comment]
Awesome. Yes it does. Thanks

**Comment by AryamnovEugeniy** [comment]
I'm glad that it helped!
