### ISSUE TITLE
How to change background-color after selection row?

### ISSUE THREAD

**Issue by Olegborodko** [DevExpress/devextreme-reactive#2568]
`<tr> ` has css class - **MuiTableRow-root** 
after  selection it has class **TableSelectRow-selected-358**
but this class is not constant, and after time it will be different

Part of my code is
```
<VirtualTable/> 
<TableSelection
  selectByRowClick
  highlightRow
  showSelectionColumn={false}
 />
```

I try to add **rowComponent** to **TableSelection** , but it is not work
```
rowComponent={(props) => 
  <Table.Row
  {...props}
  className={props.selected ? 'selected-row' : ''}
  >
  </Table.Row>
}
```

**Comment by Olegborodko** [comment]
I found a solution 
```
tr[class*="TableSelectRow-selected"] td{
  font-weight: 700
}
```

fought for half a day ..

**Comment by LazyLahtak** [comment]
Hi @Olegborodko,

You may change the background color of a row using the [MuiThemeProvider](https://v3.material-ui.com/api/mui-theme-provider/). Here is an [example](https://codesandbox.io/s/condescending-galois-g1y1q) illustrating how to do that.
Let us know if it meets your needs.
