### ISSUE TITLE
Rows missing / Phantom rows appearing when a detail row as a lot of content

### ISSUE THREAD

**Issue by psmod2** [DevExpress/devextreme-reactive#2569]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When my detail row contains a lot of data (I'm showing a payload in there), on expanding the row, then scrolling to the bottom  I see phantom rows, also the bottom rows are missing.

### Expected Behaviour

All rows should remain visible and the phantom rows should not appear.

### Steps to Reproduce

See codepen:
- Open the first detail row
- Scroll to the bottom

https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0oisi

### Screenshots

![Screen Shot 2019-12-03 at 15 08 30](https://user-images.githubusercontent.com/15928263/70024904-ca596280-15de-11ea-8e5f-c5087381c04e.png)

### Environment

- "@devexpress/dx-react-core": "^2.0.5",
- "@devexpress/dx-react-grid": "^2.0.5",
- "@devexpress/dx-react-grid-material-ui": "^2.0.5",
- react: 16.9.0
- browser: Chrome 78.0.3904.97

**Comment by psmod2** [comment]
Also to note, if i set the `rowHeight` of the https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail/ I was expecting if its really long it would show a scroll/overflow, but this isn't the case

**Comment by ushkal** [comment]
Hi @psmod2,

According to CSS [algorithms](https://www.w3.org/TR/CSS21/tables.html#height-layout), a row or cell cannot limit content’s height, so the purpose of a `rowHeight `property is to set a minimal row height. So this functionality should be implemented in the `contentComponent `e.g. by applying the following style to the root div element: 
```
{
  height: 250,
  overflow: 'auto'
}
```

**Comment by psmod2** [comment]
@ushkal - Awesome. Thanks!
