### ISSUE TITLE
TableColumnResizing default width,  I should set empty

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2575]
https://codesandbox.io/s/nostalgic-babbage-2twd9

The table column resizing: when the column widths are set empty,  I get an error. I should be able to set the widths empty, it should work its own default widths.

users want to turn on this feature,
but the initial column widths,
they want to work from tuning.
We hope to be able to run as an empty array

### I'm using ...
- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by AryamnovEugeniy** [comment]
Hello,

You can set column widths to 'auto' and [TableColumnResizing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#properties)'s `resizingMode` to `nextColumn` as I've done in [this sample](https://codesandbox.io/s/thirsty-silence-zgpc5). In that case, you don't have to specify the widths yourself. Does this solution suit you?

**Comment by ahmetcaglayan** [comment]
for now working. But only <TableColumnResizing /> not use state.

**Comment by ahmetcaglayan** [comment]
"<TableColumnResizing />"

**Comment by AryamnovEugeniy** [comment]
In this case you should use [Uncontrolled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#uncontrolled-mode). Provide `defaultColumnWidths` instead of `columnWidths` to the `TableColumnResizing` plugin.
