### ISSUE TITLE
Typographical error on filter documentation

### ISSUE THREAD

**Issue by crayolaeater12** [DevExpress/devextreme-reactive#2580]
As you can see on [FilteringState Plugin Reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/filtering-state/). There is a typographical error on the available built-in operations under the FilterOperations section. `contains, notContains, startsWith, endsWith, equal, notEqual, greaterThan, graterThenOrEqual, lessThan, lessThanOrEqual`. Using the documented `graterThenOrEqual` will cause the filter to default. Use of `greaterThanOrEqual` seems to be the correct option to use in my version.

Currently using:
"@devexpress/dx-react-core": "^2.3.0",
"@devexpress/dx-react-grid": "^2.3.0",
"@devexpress/dx-react-grid-material-ui": "^2.3.0",

**Comment by LazyLahtak** [comment]
Hi @crayolaeater12,

Thank you for reporting an error. We will correct it in the nearest release.
