### ISSUE TITLE
Chart label with graph

### ISSUE THREAD

**Issue by paillave** [DevExpress/devextreme-reactive#2582]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description
I am showing a pie chart. The problem is that I want to show the label. If I show the legend at the bottom, it takes to whole place and the chart is literally hidden by the legend. So as an alternative, I want to show label on slices somehow like this:
![image](https://user-images.githubusercontent.com/4611176/70194363-721b8100-1702-11ea-829d-884e3e75e1c2.png)

The problem is that I don't find anywhere how to implement this very standard feature.

What I want to avoid:the legend that is so large that it hides the chart
![image](https://user-images.githubusercontent.com/4611176/70194268-1e109c80-1702-11ea-9c8a-b5ec8a9f0d4a.png)

**Comment by Krijovnick** [comment]
Hi @paillave 
To show labels near the pie chart slices, you can use the `pointComponent` property in the [PieSeries](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/pie-series/) plugin. I created an [example](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-bjdhp) to show how to do this.

**Comment by paillave** [comment]
thanks for the answer. This is what I wanted indeed. But for such a standard feature, I expected something quiet... more out of the box than injecting a custom component based on trigonometry mathematics (even if very simple). This would be acceptable for a basic low level open source component, but from devexpress... it is sadly disappointing given how evolved most of your components are.

**Comment by Krijovnick** [comment]
@paillave The concept of our product is a flexible customization. We provide a wide API to implement any user request. The most popular features are available out of the box.
