### ISSUE TITLE
Scrolling within a cell

### ISSUE THREAD

**Issue by anurastogi** [DevExpress/devextreme-reactive#2586]
I am using React Scheduler to display some data. When there are many rows to be displayed within a cell, the data is not visible. Is there any way of adding a scrollbar when the contents exceed the width?
![665d9c31-32a4-45f2-a4f0-084563beb9df](https://user-images.githubusercontent.com/48476931/70323513-f41abf80-1852-11ea-8385-5c95c15d63a7.jpg)

**Comment by MaximKudriavtsev** [comment]
Hi @anurastogi,

We are aware of this UX problem and plan to add the Compact Appointments feature in the near future after we introduce the [Grouping feature](https://github.com/DevExpress/devextreme-reactive/issues/2236). You can leave your feedback about it in the [next issue](https://github.com/DevExpress/devextreme-reactive/issues/2231).

As a workaround, we suggest you add height to an all-day cell. See the [following example](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-uo9n7).
