### ISSUE TITLE
How to add values to the Legend labels?

### ISSUE THREAD

**Issue by whyjay17** [DevExpress/devextreme-reactive#2587]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

Thanks for the great library. I was wondering how I can add values to the legend labels. 

https://codesandbox.io/embed/devextreme-react-chart-for-material-ui-3s2x1?fontsize=14&hidenavigation=1&theme=dark

In this example, I want to put 12 next to Russia and 7 next to Canada, etc. 
I tried to search the docs and demo page on the website, but I wasn't able to find a clear demo of how to change what the legend displays. 

It would be great if anyone could help.

Thank you.

### Environment

- devextreme-reactive: 2.3.1
- react: 16.8.6
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.5.2

**Comment by Krijovnick** [comment]
Hi @whyjay17 
You can use the `labelComponent` option in the [Legend](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/legend/) plugin. I am modifying your [example](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-yd5n5) to show how to set custom text in the legend.
