### ISSUE TITLE
Incompatibility between VirtualTable and TableSelection

### ISSUE THREAD

**Issue by FernandoGOT** [DevExpress/devextreme-reactive#2588]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When using ```VirtualTable``` with the property ```rowComponent``` everything works correctly, but if I add the ```TableSelection```, the ```rowComponent``` from ```VirtualTable``` stop working

### Expected Behaviour

The ```TableSelection``` can't overwrite the ```rowComponent``` property from ```VirtualTable```

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/dx-react-grid-bug-ycvzs

### Screenshots

![dx-react-grid-bug](https://user-images.githubusercontent.com/8334222/70350846-57eabb80-1846-11ea-91e7-7861699ce730.gif)

### Environment

- devextreme-reactive: 2.3.1
- react: 16.12.0
- browser: chrome
- material-ui: 4.7.1

**Comment by LazyLahtak** [comment]
Hi @FernandoGOT,

The `TableSelection` plugin's `highlightRow` property overrides rowComponent from VirtualTable. You can use the solution described [here](https://github.com/DevExpress/devextreme-reactive/issues/437#issuecomment-504986730).
