### ISSUE TITLE
Selection in controlled mode not work

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#2590]
I try you selection controlled mode code: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/
in this my example:
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-vnbpr

but not work.
Is a bug?

**Comment by LazyLahtak** [comment]
Hi @ccamusso,

I found a mistake in your example. According to the [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/#properties), the `selection` property of the `SelectionState` plugin should be a string or number array. Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-2k2id).
If you have any further questions, let us know.

**Comment by ccamusso** [comment]
Work, thks.

**Comment by LazyLahtak** [comment]
You are welcome!
