### ISSUE TITLE
Row Reorder Workaround Lag

### ISSUE THREAD

**Issue by ryanwood3** [DevExpress/devextreme-reactive#2592]
### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I was following the following thread regarding row reordering which included a workaround using react-sortable-hoc: https://github.com/DevExpress/devextreme-reactive/issues/419.
After following the example provided, I was able to implement row reordering into my grid however, there seems to be significant lag when using VirtualTable to scroll.  My grid is obviously more complex than the example provided with 9 columns and upwards of 1500 rows (I am using paging as well).  However, this lag is still present with a smaller number of rows (I tested with 24 rows and there was still substantial lag on scroll and column resize).  Is there any workaround for this performance issue?

**Comment by ushkal** [comment]
Hi @ryanwood3 ,

Please provide us with a sample project or change this [codesandbox](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-6fz3p) so that we can reproduce the lag. It will help us find the cause of the issue. Also, check that you are using the production mode.

**Comment by ryanwood3** [comment]
How can I ensure that I am using production mode?

**Comment by ryanwood3** [comment]
Also is there a way to avoid the row from squeezing together when dragging it.  Example seen in the following picture 
![image](https://user-images.githubusercontent.com/18450921/70630457-d8177500-1be8-11ea-92d8-d63c630e8854.png)

**Comment by ushkal** [comment]
> How can I ensure that I am using production mode?

Please refer to this [guide](https://reactjs.org/docs/optimizing-performance.html).

>Also is there a way to avoid the row from squeezing together when dragging it.

This happens because react-sortable-hoc renders a row being dragged outside a table so cell sizing works incorrectly. As a workaround you can set cell width manually as shown in this [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-zuu18).
