### ISSUE TITLE
Error "Can't perform a React state update on an unmounted component." while using LineSeries.Path

### ISSUE THREAD

**Issue by kamil-lon** [DevExpress/devextreme-reactive#2593]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour
I use Chart and LineSeries like on this demo: https://devexpress.github.io/devextreme-reactive/react/chart/demos/line/spline/.
I have console error:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ComponentWithAnimation (created by Line)
    in Line (at dashboard.page.tsx:136)
    in Line (created by TemplateConnectorBase)`

### Expected Behaviour
No error.

### Steps to Reproduce

![er1](https://user-images.githubusercontent.com/48553085/70604531-1b79df80-1bf9-11ea-949a-5ff3de6a7c7f.PNG)
![er2](https://user-images.githubusercontent.com/48553085/70604543-1f0d6680-1bf9-11ea-9053-0d3d577cc93c.PNG)

### Screenshots
![err](https://user-images.githubusercontent.com/48553085/70604404-f38a7c00-1bf8-11ea-9de3-cfab89cb71e6.PNG)

### Environment

- devextreme-reactive: none
- devexpress/dx-react-chart: 2.3.0
- devexpress/dx-react-chart-material-ui: 2.3.0
- devexpress/dx-react-core: 2.3.0,
- react: 16.10.2
- browser: Chrome 78
- bootstrap: none
- react-bootstrap: none
- material-ui/core: 4.7.0

**Comment by ushkal** [comment]
Hi @kamil-lon ,

I couldn't reproduce the issue using our demo sources. Please provide us with a runnable project or change this sample [project](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-id01d) so that we could reproduce it.

**Comment by kamil-lon** [comment]
> 
> 
> Hi @kamil-lon ,
> 
> I couldn't reproduce the issue using our demo sources. Please provide us with a runnable project or change this sample [project](https://codesandbox.io/s/devextreme-react-chart-for-material-ui-id01d) so that we could reproduce it.

https://codesandbox.io/s/devextreme-react-chart-for-material-ui-xcrwi
Change and re-change something. Then is some similar error on console.

**Comment by ushkal** [comment]
Thank you for the clarification. According to this [issue](https://github.com/codesandbox/codesandbox-client/issues/2151), the error you encountered is a CodeSandbox bug, meaning that it doesn't affect your app in production. I've downloaded the codesandbox you provided and run it locally and the error does not appear.
