### ISSUE TITLE
Drag and drop for rows in tree data grid

### ISSUE THREAD

**Issue by nihhwo** [DevExpress/devextreme-reactive#2594]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description
As issue #2414 is locked, I open a new issue on this topic. I tried to integrate [react-sortable-tree](https://github.com/frontend-collective/react-sortable-tree) into an existing [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xof5f) with tree data, but I need some help. I don't know how to use both libraries together.

**Comment by LazyLahtak** [comment]
Hi @nihhwo,

I've made an [example](https://codesandbox.io/s/zealous-shape-plld8) illustrating possible implementation using `react-sortable-hoc`. The sample shows how you can use this library with our tree data grid.
If you have any further questions, let us know.

**Comment by nihhwo** [comment]
Thanks a lot!

**Comment by LazyLahtak** [comment]
You are welcome!
