### ISSUE TITLE
Readonly causing Typescript build errors - PR included

### ISSUE THREAD

**Issue by justincasey** [DevExpress/devextreme-reactive#2598]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

devexpress/dx-react-grid is building with Typescript errors.

### Expected Behaviour

Should build without Typescript errors. There is an error resulting from a possible incorrect usage of the `readonly` attribute for interface/type properties.

### Screenshots

![image](https://user-images.githubusercontent.com/4348807/70731601-919b4680-1ccc-11ea-98fa-3e77afcce1eb.png)

### Environment

- @devexpress/dx-react-core: 2.3.1
- @devexpress/dx-react-grid: 2.3.1
- @devexpress/dx-react-grid-material-ui: 2.3.1
- react: 16.9.0
- material-ui: 4.6.0

Link to proposed PR: https://github.com/DevExpress/devextreme-reactive/pull/2597

**Comment by briandelancey** [comment]
Looks like this issue was introduced in 2.3.1 except for those in _dx-react-scheduler_ which have been there since 2.2.0
