### ISSUE TITLE
Bar Chart doesn't work with scaleTime as an argument scale factory

### ISSUE THREAD

**Issue by dimon82** [DevExpress/devextreme-reactive#2601]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description
Bar Chart is displayed incorrectly using `scaleTime` as an argument scale factory:

![image](https://user-images.githubusercontent.com/5393145/70956277-64ca9480-2028-11ea-902d-e79d91efd49c.png)

Without using dates (and scaleTime factory) it displays as it should:

![image](https://user-images.githubusercontent.com/5393145/70956323-904d7f00-2028-11ea-90f2-91344083e7f7.png)

It works fine with Line Chart though. How can I make it work with bar charts?

**Comment by AryamnovEugeniy** [comment]
Hello,

Bar Chart cannot work correctly with `scaleTime`. You should use, for instance, [scaleBand](https://github.com/d3/d3-scale#band-scales) instead. Here is an [example](https://codesandbox.io/s/friendly-rgb-gcp5t) where I use `scaleBand` with dates. Does this solution suit you?
If you have any other questions, feel free to ask them.

**Comment by dimon82** [comment]
Thanks for a quick response! Yeah, I've read that bar charts should not be used with `scaleTime`, however what if I have to... `scaleBand` works, however this is what I get:

![image](https://user-images.githubusercontent.com/5393145/71037325-55088a00-20d4-11ea-9735-e3f04e617b22.png)

I need those stacked bars to have some margin between one another, something like:

![image](https://user-images.githubusercontent.com/5393145/71037499-a0229d00-20d4-11ea-9021-e05c454c22e4.png)

I get the chart above by just removing `factory={scaleBand as any}` (by the way in typescript factory is not assignable to any scale without converting it to `any`) and making the dates as strings. Is there a reason why `scaleBand` creates it this way? I'd really love to use dates instead of strings but couldn't figure out how to adjust margin between stacks when factory is set to `scaleBand` .

And one more question, is there a way to automatically adjust the number of argument axis labels depending on the time range that is selected for the chart? If I get 2-3 days worth of data for every hour, I get this: 

![image](https://user-images.githubusercontent.com/5393145/71037850-656d3480-20d5-11ea-954e-e4e94fddf243.png)

Would be nice if the number of labels were chosen automatically somehow, just like when you use `scaleTime`, such as

![image](https://user-images.githubusercontent.com/5393145/71038013-c1d05400-20d5-11ea-959d-75955a0b234f.png)

or

![image](https://user-images.githubusercontent.com/5393145/71038070-da406e80-20d5-11ea-9e98-d826ed22f538.png)

**Comment by AryamnovEugeniy** [comment]
Hello again,

you can import our 'scaleBand' from `dx-chart-core` and use it instead:
```
import { scaleBand } from "@devexpress/dx-chart-core"
```
Or you can scaleBand paddings as shown in [this example](https://codesandbox.io/s/currying-cdn-6h8zu).
About labels. We already have similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/2306). For now, you can filter labels manually. [Here](https://github.com/DevExpress/devextreme-reactive/issues/2306#issuecomment-528814298) is workaround.

Does this solution suit you?

**Comment by dimon82** [comment]
@AryamnovEugeniy, thanks! Looks to be working just fine.

One more comment since we're on it. Not a big deal, but would be nice if I could assign `scaleBand` and `scaleTime` to `ArgumentScale factory` without converting it to `any` in typescript. `factory` is a type of `FactoryFn` which is not what scaleBand and scaleTime are.

**Comment by dimon82** [comment]
@AryamnovEugeniy updated package to the latest version (2.3.1) and now getting an error trying to style tooltip arrow

> Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `OverlayBase`.
    in arrowComponent (created by OverlayBase)

here is the code (was working fine before update)

`<Tooltip arrowComponent={(props) => <Tooltip.Arrow {...props}  className={classes.tooltipArrow} />} />`

**Comment by AryamnovEugeniy** [comment]
According to [docs](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-scale/#properties), `factory` is of type `() => ScaleObject`. You can use this type as shown [here](https://codesandbox.io/s/brave-liskov-hzc0l).

In regards to the `arrowComponent`: it seems that you'd been using the Chart's beta version. Since then, some changes have been made to this component and the Chart has been released. So, you'll have to use [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html).

**Comment by dimon82** [comment]
@AryamnovEugeniy thank you! I haven't found anything in the docs that I shows how to use it properly with `forwardRef`. I'm using typescript and it does allow me to use it as `<Tooltip arrowComponent={(props) => <Tooltip.Arrow {...props} className={classes.tooltipArrow} />} />`. Were the typings updated? If you could, can you please show me how I can convert this line into using forwardRef to style the tooltip's arrow?

**Comment by AryamnovEugeniy** [comment]
Hello again,

[Here](https://codesandbox.io/s/focused-visvesvaraya-w9176) is an example of how to do this.
And yes, you are right, it was a breaking change. It was done when Chart was still beta version. We'll fix change log and update this issue as soon as it is done.

If you have any other questions, don't hesitate to contact us.

**Comment by dimon82** [comment]
Thank you! Tooltip arrows work now. Appreciate your help!

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
