### ISSUE TITLE
Unable to set percentage width in column with VirtualTable - columnExtensions

### ISSUE THREAD

**Issue by foxart78** [DevExpress/devextreme-reactive#2606]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When I try to set column width on VirtualTable using a percentage value, obtain an error

> `<VirtualTable columnExtensions={[{columnName: 'name', width: '50%'}]}/>`

If I try using Table instead VirtualTable, percentage value are allowed 

### Steps to Reproduce
https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-u4smv?fontsize=14&hidenavigation=1&theme=dark

### Environment
- devextreme-reactive: 2.3.0
- react: 16.11.0
- browser: Google Chrome 79.0.3945.79
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by MaximKudriavtsev** [comment]
Hi @foxart78,

This is expected behavior. According to our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#virtualtablecolumnextension), width values can be only in pixels as this is required by the VirtualTable plugin.

**Comment by foxart78** [comment]
Thanks, sorry but I hadn't got checked on documentation.
I had assumed that the property "ColumnExtension" of Table and VirtualTable works at the same.

Thank you again.
