### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by SMaverick78** [DevExpress/devextreme-reactive#2607]
Hello! I have tables in tabs. When switching tabs I get an error. ((((
breadcrumbs.js:64 TypeError: Cannot read property 'start' of undefined
    at ee (dx-grid-core.es.js:1882)
    at dx-react-grid.es.js:2707
    at e.render (dx-react-core.es.js:535)
https://github.com/DevExpress/devextreme-reactive/blob/d83cdc32baef5517b3dcc5c00877cb1f7080f646/packages/dx-grid-core/src/plugins/table-fixed-columns/helpers.ts#L45

**Comment by ushkal** [comment]
Hi @SMaverick78 ,

I couldn't reproduce the described behavior. Please send us a runnable project or modify this [codesandbox](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0wj8n) so that the issue is reproduced.

**Comment by ARL64** [comment]
Hi @ushkal, I have the same issue. Using VirtualTable, TableRowDetail, RowDetailState and rightColums.
Using Table instead of VirtualTable and leftColumns instead of rightColumns, I get the error.

Unable to reproduce it on codepen because of _A cross-origin error was thrown. React doesn't have access to the actual error object in development._

Here is the [codesanbox](https://codesandbox.io/s/cannot-read-property-start-of-undefined-0ze6l).

Removing the TableRowDetail get it working.

**Comment by ARL64** [comment]
![Capture d’écran 2019-12-19 à 15 33 48](https://user-images.githubusercontent.com/837109/71181764-1231e800-2275-11ea-913c-2618b17ceaee.png)

Index
`import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Tabs, Tab, Typography } from "@material-ui/core";
import { RowDetailState } from "@devexpress/dx-react-grid";
import {
  Grid,
  TableHeaderRow,
  TableFixedColumns,
  TableRowDetail,
  VirtualTable,
} from "@devexpress/dx-react-grid-material-ui";

const TabPanel = props => {
  const { children, value, index, ...other } = props;

  return (
    <Typography
      {...other}
      component="div"
      role="tabpanel"
      hidden={value !== index}
      style={{ height: "100%" }}
      id={`simple-tabpanel-${index}`}
    >
      <div style={{ height: "100%" }}>{children}</div>
    </Typography>
  );
};

function App() {
  const [columns] = useState([
    { name: "name", title: "Name" },
    { name: "gender", title: "Gender" },
    { name: "city", title: "City" },
    { name: "car", title: "Car" }
  ]);
  const [rows] = useState([
    { gender: "Female", name: "Sandra", city: "Las Vegas", car: "Audi A4" },
    { gender: "Male", name: "Paul", city: "Paris", car: "Nissan Altima" },
    { gender: "Male", name: "Mark", city: "Paris", car: "Honda Accord" },
    { gender: "Male", name: "Paul", city: "Paris", car: "Nissan Altima" },
    { gender: "Female", name: "Linda", city: "Austin", car: "Toyota Corolla" },
    {
      gender: "Male",
      name: "Robert",
      city: "Las Vegas",
      car: "Chevrolet Cruze"
    },
    { gender: "Female", name: "Lisa", city: "London", car: "BMW 750" },
    { gender: "Male", name: "Mark", city: "Chicago", car: "Toyota Corolla" },
    {
      gender: "Male",
      name: "Thomas",
      city: "Rio de Janeiro",
      car: "Honda Accord"
    },
    { gender: "Male", name: "Robert", city: "Las Vegas", car: "Honda Civic" },
    { gender: "Female", name: "Betty", city: "Paris", car: "Honda Civic" },
    {
      gender: "Male",
      name: "Robert",
      city: "Los Angeles",
      car: "Honda Accord"
    },
    {
      gender: "Male",
      name: "William",
      city: "Los Angeles",
      car: "Honda Civic"
    },
    { gender: "Male", name: "Mark", city: "Austin", car: "Nissan Altima" }
  ]);
  const [rightColumns] = useState(["car"]);
  const [value, setValue] = useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <div>
      <Tabs centered value={value} onChange={handleChange}>
        <Tab label="Tab 1" />
        <Tab label="Tab 2" />
      </Tabs>
      <TabPanel value={value} index={0}>
        <div>Go to tab 2</div>
      </TabPanel>
      <TabPanel value={value} index={1}>
        <Grid rows={rows} columns={columns}>
          <RowDetailState />
          <VirtualTable estimatedRowHeight={50} />
          <TableHeaderRow />
          <TableFixedColumns leftColumns={rightColumns} />
          <TableRowDetail contentComponent={({ row }) => row.car} />
        </Grid>
      </TabPanel>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
`

**Comment by ushkal** [comment]
Hi @ARL64 ,

Thank you for the provided example. The TableFixedColumns plugin should be placed after all other Table* plugins to work properly. We'll add the TableRowDetail plugin to its dependencies to avoid confusion.

@SMaverick78 , please let me know if this solution solves this problem.

**Comment by ARL64** [comment]
Hi @ushkal, 

Thank you for the clarification. It's working.

**Comment by SMaverick78** [comment]
Not help. (((((

**Comment by ushkal** [comment]
@SMaverick78,

Please send us a runnable project or modify this [codesandbox ](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0wj8n)so that we could fix this error.

**Comment by abbazabacto** [comment]
Ticket is closed, but for the ones like me reading this thread in search for a solution:

For me this had to do with an `TableBandHeader` with an empty list passed to `columnBands`, in combination with a `TableGroupRow`. Conditionally rendering this `TableBandHeader` solved it for me:

```tsx
{columnBands.length ? (<TableBandHeader columnBands={columnBands} />) : null}
```
