### ISSUE TITLE
Cell Editing Conditional

### ISSUE THREAD

**Issue by foxart78** [DevExpress/devextreme-reactive#2608]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

it's possible to make an Inline Cell Editing using for example DataTypeProvider
that allow editing only in specific conditions determined by other cell of the same row?

![image](https://user-images.githubusercontent.com/7845955/71094555-76887500-21ab-11ea-819b-8f2619dfe45a.png)

### Environment

- devextreme-reactive: 2.3.0
- react: 16.11.0
- browser: N/A
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by LazyLahtak** [comment]
Hi @foxart78,

You can use `TableInlineCellEditing` [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/#tableinlinecelleditingcellprops). It is possible to get a row from the component's properties and check a value in a specific column. Here is an [example](https://codesandbox.io/s/runtime-cache-8eqvj) illustrating how to do that.
Please let us know if this solution meets your requirements.

**Comment by foxart78** [comment]
> Hi @foxart78,
> 
> You can use `TableInlineCellEditing` [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/#tableinlinecelleditingcellprops). It is possible to get a row from the component's properties and check a value in a specific column. Here is an [example](https://codesandbox.io/s/runtime-cache-8eqvj) illustrating how to do that.
> Please let us know if this solution meets your requirements.

That's exactly what I needed!
Thanks

**Comment by LazyLahtak** [comment]
You are welcome!
