### ISSUE TITLE
React Grid - Hide one of the columns sorting arrows

### ISSUE THREAD

**Issue by ryanwood3** [DevExpress/devextreme-reactive#2609]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I would like to be able to hide only one of the sorting arrows.  I am disabling sorting on the Location column, however I still want to default the grids sort by location.  However, since the user cannot click the column to sort, I do not want to show the arrow icon next to the column title.  However, the user can still sort by other columns such as Line #, so the arrow icons should still appear next to those columns when they are selected.

![image](https://user-images.githubusercontent.com/18450921/71094999-1e308380-2169-11ea-8fdc-a7de9e173ba5.png)

Another question I had is in regards to custom sorting.  I am currently using the columnExtensions prop found in IntegratedSorting.  This works fine for asc sorting, however I want the ability to customize desc sorting as well.  Is is possible to customize the sort for a particular column and direction?

In regards to my second question.  I am using grouping, and I basically want one of the groups to stay at the top no matter what column the data is being sorted by.  I'd like the data within the group to sort, but for that group to always remain at the top.

**Comment by AryamnovEugeniy** [comment]
Hello,

In regards to your first question, here is an [example](https://codesandbox.io/s/brave-galileo-4c00e) where I hid the sorting arrow for the first column. All you need is to override the [sortLabelComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowsortlabelprops).

About your second question. You can try using `SortingState`'s [columnExtension](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/sorting-state/#sortingstatecolumnextension). Change the function you set in the `columnExtensions` depending on the sorting direction of the column you need (to do this, use `SortingState`'s `onSortingChange` property). Here is an [example](https://codesandbox.io/s/romantic-mountain-romwz) where I placed the 'High priority' row above all the others.

Does this solution meet your requirements? Let us know if you have any questions.

**Comment by ryanwood3** [comment]
It does.  Thank you so much!
