### ISSUE TITLE
Problem with creating two appointments by editing

### ISSUE THREAD

**Issue by vealjoshua** [DevExpress/devextreme-reactive#2610]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Scheduler

### Current Behaviour

When I add drag and drop capabilities and copy capabilities they do not work nicely together. When I try to copy it adds 2 appointments instead of 1. When I drag and move a recurring appointment and choose all appointments it only moves 1 when I expect it to move all recurring appointments. It seems like I can no have <IntegratedEditing /> and <EditRecurrenceMenu /> in the same grid

`
<Paper>
				<Scheduler data={data} height={660}>
					<ViewState currentDate={currentDate} />
					<EditingState onCommitChanges={this.commitChanges} />

					<WeekView />
					<MonthView />

					<Toolbar />
					<ViewSwitcher />

					<Appointments />
					<IntegratedEditing />
					<EditRecurrenceMenu />
					<AppointmentTooltip showOpenButton showDeleteButton />
					<AppointmentForm />

					<DragDropProvider />
				</Scheduler>
			</Paper>`

**Comment by MaximKudriavtsev** [comment]
Hi @vealjoshua,

You added both [IntegratedEditing](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/integrated-editing/) and [EditRecurrenceMenu](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/edit-recurrence-menu/) that actually do the same thing - if you wish to be able to choose between edit types, add the `EditRecurrenceMenu` plugin; `IntegratedEditing` uses the current edit type. So, please remove one of these plugins.
