### ISSUE TITLE
Chart's tooltip shows incorrect text

### ISSUE THREAD

**Issue by dimon82** [DevExpress/devextreme-reactive#2615]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

`Tooltip`'s `text` (`ContentProps`) is showing incorrect value in stacked bar chart, light green on the image below is supposed to show 2 (that's what the value is), but it's showing 14

![image](https://user-images.githubusercontent.com/5393145/71300147-4e357d80-2347-11ea-9059-0e2e98f659e4.png)

**Comment by AryamnovEugeniy** [comment]
Hello,

You can try to modify the text you display in the tooltip. For example, as I've done in this [example](https://codesandbox.io/s/fervent-goldwasser-ssknr).
