### ISSUE TITLE
Band column cant divided correctly in some situation

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2617]
![image](https://user-images.githubusercontent.com/19796912/71462889-bb398f00-27ef-11ea-89fa-6ce2693f8ea8.png)

Hi, i got a problem in this picture, you can see the middle line cell melt to one, but they have different father. They are expected to be two cell ! How could i accomplish this feature. any advice would be helpful !

**Comment by LazyLahtak** [comment]
Hi @yl1215,

Could you please provide us with your code or a runnable project (for example in the [CodeSandbox](https://codesandbox.io/s/13qvz1qqzl))?

**Comment by yl1215** [comment]
Its not very convenient to move the code to CodeSandBox, but i can provide the data.
[
  {
    "title": "nation/city",
    "children": [
      {
        "title": "US",
        "children": [
          {
            "title": "b",
            "children": [
              {
                "columnName": "columnA"
              }
            ]
          }
        ]
      },
      {
        "title": "CN",
        "children": [
          {
            "title": "b",
            "children": [
              {
                "columnName": "columnB"
              }
            ]
          },
          {
            "title": "a",
            "children": [
              {
                "columnName": "columnC"
              }
            ]
          }
        ]
      }
    ]
  }
]

This is the columnBands prop of plugin TableBandHeader for the picture. The problem is that the title US and the title CN both have a child whose title is b, even more, they are neighbors. So they have been melt to one cell, but that should not be right. If this is not clear, please let me know.

**Comment by ushkal** [comment]
Hi @yl1215 ,

Thank you for the code sample. I've reproduced the issue and we'll fix it soon.
