### ISSUE TITLE
Cannot read property 'attach' of undefined at attach

### ISSUE THREAD

**Issue by doorisopen** [DevExpress/devextreme-reactive#2619]
Hello! 
I am facing the same issue. [material-ui/issues/19005](https://github.com/mui-org/material-ui/issues/19005)

`
"dependencies": {
    "@devexpress/dx-react-core": "^2.3.2",
    "@devexpress/dx-react-scheduler": "^2.3.2",
    "@devexpress/dx-react-scheduler-material-ui": "^2.3.2",
    "@material-ui/core": "^4.8.1",
    "@material-ui/icons": "^4.5.1",
`

![error1](https://user-images.githubusercontent.com/34861411/71543081-28951d80-29b2-11ea-9028-7dc7394cb96f.jpg)

**Comment by iamnikita97** [comment]
https://github.com/mui-org/material-ui/issues/19005
