### ISSUE TITLE
BandRows with VirtualTable got some problems 

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2624]
Hi, i got a problem when i use the virtual table with my own plugin BandRows. The bandRow is used to group the rows in this way:

![image](https://user-images.githubusercontent.com/19796912/71776169-ac10c900-2fc7-11ea-9928-5feffe8c7d33.png)

And the reason i use VirtualTable not Table is that i need to fix the header.
Now, the problem is that when i use VirtualTable, the number of 'tr' is limited, when i scroll up, only 4 tr dom node is  saved in the up invisible area. However, my banded row cell, whose rowSpan may over 4, so it comes that when i scroll up, the banded cell just disappeared because his parent tr dom node been deleted but the cell itself still in the visible area.

Any advices that i can overcome this problem with VirtualTable would be very helpful !

**Comment by ushkal** [comment]
Hi @yl1215 ,

The count of overscan rows cannot be changed - please refer to this [ticket](https://github.com/DevExpress/devextreme-reactive/issues/2085#issuecomment-502061114) for more information. I suggest you recalculate rowSpan when the scrollbar position changes. To achieve this, use a private 'viewport' getter. Please refer to the TableBandHeader plugin's source code to see to solve a similar problem.
Please note that this is a private API that can be changed without notification.

**Comment by yl1215** [comment]
Ok，very thanks.

**Comment by ushkal** [comment]
You are welcome! 
Please let us know if you have any further questions.
