### ISSUE TITLE
Localization Messages in EditRecurrenceMenu plugin: `menuDeletingTitle` can not be overridden

### ISSUE THREAD

**Issue by cipriandraghici93** [DevExpress/devextreme-reactive#2626]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

Using:  <EditRecurrenceMenu
                               messages={{
                                    all: "All",
                                    menuDeletingTitle: "Delete recurring schedule",
                                }}
                            />
It's working for "all" text, but not for "menuDeletingTitle"

### Expected Behaviour

All the localization messages should be overridden.

### Steps to Reproduce

1. Create a simple react scheduler adding the EditReccurrenceMenu plugin
2. Create a reccurrence appointment
3. Try to delete a reccurence appointment
4. The popup menu title is not changed.

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

![image](https://user-images.githubusercontent.com/11082863/71852505-87a90f80-30e1-11ea-83fb-a768284b0881.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

Thank you for reporting the issue! We'll fix it as soon as possible.
