### ISSUE TITLE
TableEditColumn Delete Command does not preventDefault

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#2627]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I have a Table.Row with an onClick event handler, and a TableEditColumn with an onCommitChanges handler.

Clicking on the 'Delete' icon in the TableEditColumn causes both the onCommitChanges and onClick events to trigger.

### Expected Behaviour

The option is available somewhere to have the 'Delete' command preventDefault or stop propagation somehow.

### Steps to Reproduce

https://codesandbox.io/s/devextreme-react-grid-for-material-ui-py5f8?fontsize=14&hidenavigation=1&theme=dark

**Comment by AryamnovEugeniy** [comment]
Hello,

You can use [stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) inside your `Command` component as I've done for `DeleteButton` [here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-049ll). In this case the Row's onClick is not triggered any more on DeleteButton click.
Does this solution suit you?

If you have any other questions, feel free to ask them.

**Comment by thehig** [comment]
Yep, that works a charm. Thank you very much!

**Comment by AryamnovEugeniy** [comment]
I am glad that it helped!
