### ISSUE TITLE
TableColumnResizing does not work with dx-react-grid-bootstrap4

### ISSUE THREAD

**Issue by andycaramba** [DevExpress/devextreme-reactive#2632]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
TableColumnResizing does not work with @devexpress/dx-react-grid-bootstrap4

### Steps to Reproduce

Link to the example that reproduces the issue: [CodeSandbox](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap4-with-column-resizing-2w9zv).

**Comment by MaximKudriavtsev** [comment]
Hi @andycaramba,

Add the DevExtreme React Grid styles in the root .js file:

`import '@devexpress/dx-react-grid-bootstrap4/dist/dx-react-grid-bootstrap4.css';`

See the updated [example](https://codesandbox.io/s/devextreme-react-grid-for-bootstrap4-with-column-resizing-31r1b).

**Comment by andycaramba** [comment]
@MaximKudriavtsev Thank you
