### ISSUE TITLE
How to monitor the didmount of Table

### ISSUE THREAD

**Issue by yl1215** [DevExpress/devextreme-reactive#2634]
Hi, i got a problem when i try to get the dom structure of table when i change the props.
The problem is that when i change the props of Table, i try to get the new dom structure of Table, however i cant get the new dom in my own componentDidMount. It seems that Table has use its own setState to update the dom, not my props. So how could i get the new dom of Table, is there a callback?

**Comment by AryamnovEugeniy** [comment]
Hello,

Could you describe what you want to achieve in more detail? What are you trying to achieve? Or could you provide an example of what you want to achieve?
Also, in our Grid, `componentDidMount` is called only once when the Grid is created. When you change props, `componentDidUpdate` is called.

**Comment by yl1215** [comment]
Thanks, i have find another way to achieve my goal, i will close this issue.
