### ISSUE TITLE
Scrolling by keyboard doesn't work correctly

### ISSUE THREAD

**Issue by a-omarova** [DevExpress/devextreme-reactive#2641]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

After one or few clicks from the keyboard (up, down) the focus of the dashboard is lost and scroll doesn't work, you have to click to the dashboard again

It reproduce on the demos page https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/

### Environment

- devextreme-reactive: 2.3.0
- react: 16.8.6
- browser: Chrome 79
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.2.0

**Comment by LazyLahtak** [comment]
Hi @a-omarova.

Virtual Table scrolling by keyboard arrows isn't implemented yet. We have a similar [request](https://github.com/DevExpress/devextreme-reactive/issues/1966) and will take it into account when planning our future releases.

If you have any questions, fell free to contact us.
