### ISSUE TITLE
TableColumnResizing does not work with IntegratedSelection

### ISSUE THREAD

**Issue by ennisthemenace** [DevExpress/devextreme-reactive#2647]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

when using IntegratedSelection TableColumnResizing returns an error as the column for the checkbox from IntegratedSelection is not in the defaultColumnWidths array. 

### Expected Behaviour

Resize should work

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.4.0
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.0

**Comment by LazyLahtak** [comment]
Hi @ennisthemenace

I made an [example](https://codesandbox.io/s/throbbing-wildflower-wjl0v) with the `TableColumnResizing` and `IntegratedSelection` plugins and didn't get the error. Could you please provide your code or modify my example to reproduce the issue?
