### ISSUE TITLE
TableTreeColumn does not work when changing the FOR property.

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2649]
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-nef1j

**TableTreeColumn** does not work when changing the **for** property.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

Thank you for reporting the problem. We will fix it soon.
