### ISSUE TITLE
Do you plan to add header filters to the grid?

### ISSUE THREAD

**Issue by draxtor** [DevExpress/devextreme-reactive#2658]
[x] React Grid
  [ ] React Chart
  [ ] React Scheduler
As a fan of old dx grid I'm wondering if you plan to add this feature:
![image](https://user-images.githubusercontent.com/3110724/73439473-f596ce80-434f-11ea-90f8-f93244717d41.png)

Thanks

**Comment by dxbykov** [comment]
Hi @draxtor,

This feature is not in our [Roadmap for 2020](https://community.devexpress.com/blogs/javascript/archive/2020/01/29/devextreme-angular-react-vue-jquery-2020-roadmap.aspx). Nevertheless, you can manually implement it on top of our React Grid. Please refer to the [examples](https://github.com/DevExpress/devextreme-reactive/issues/2119) we shared in a similar issue.

> As a fan of old dx grid...

In this case, may I ask you why you don't use our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/React/) instead?

**Comment by draxtor** [comment]
Thanks I'll check examples supplied,

Rearding DataGrid for React: we want to move forward native react components and to avoid jquery wrappers. For maintainability purposes, performance & unit testing.

**Comment by dxbykov** [comment]
> For maintainability purposes, performance & unit testing.

Thanks for sharing this. I would appreciate it if you take a moment and list some specific performance or testing related issues that you faced with our DataGrid for React (if there are any). We'd like it to be as good as our native React Grid  :)

> to avoid jquery wrappers

Note that our React wrappers are not jQuery-based.
