### ISSUE TITLE
Property 'ref' does not  exist on VirtualTable

### ISSUE THREAD

**Issue by holmeren** [DevExpress/devextreme-reactive#2659]
I'm trying to implement the 'ScrollToRow' feature, but the VirtualTable wont accept 'ref' as a property ,and give the following error message 

_`Property 'ref' does not exist on type 'IntrinsicAttributes & VirtualTableProps & { children?: ReactNode; }'.`_

I'm using typescript, and have the following packages installed
`    "@devexpress/dx-grid-core": "2.4.0",
    "@devexpress/dx-react-core": "2.4.0",
    "@devexpress/dx-react-grid": "2.4.0",
    "@devexpress/dx-react-grid-material-ui": "2.4.0",`

Am i missing something important, or is there another way to call ScrollToRow?

**Comment by ushkal** [comment]
Hi @holmeren,

I've reproduced the issue. We'll fix it soon. In the meantime I recommend you use the following workaround: 
```
const vtRef = useRef<any>();
```
