### ISSUE TITLE
do we have startWeekDay param in week-view for scheduler component

### ISSUE THREAD

**Issue by sayjeyhi** [DevExpress/devextreme-reactive#2660]
hello ,
thanks for this great library .
I have a question on `scheduler` reactive library. 
Do we have `startWeekDay` param in `week-view` component ?
For us Saturday is start day of week and I do not know how to solve showing correct sort of week days..

**Comment by AryamnovEugeniy** [comment]
Hello @sayjeyhi !

Thank you for your interest in our components!
We do have a possibility to change the start day of the week - the `firstDayOfWeek` parameter of the [Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/#properties) itself. [Here](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-lm6tz) is a small sample I made to illustrate this. For Saturday, the `firstDayOfTheWeek` should be 6.

If you have any other questions, feel free to ask them.
