### ISSUE TITLE
Making the entire header clickable - rather than just title

### ISSUE THREAD

**Issue by psmod2** [DevExpress/devextreme-reactive#2663]
- [ X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi,

I have a React Grid table which has sorting controls - however I'd like the entire cell to be clickable so that it can be sorted - at the moment only the title text itself is clickable.

In my Chrome dev tools I see if I set the title width to 100% it does the job, but not sure how to actually apply this.

Here is a codepen of roughly what I have:
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xufkf

Any help appreciated.

### Environment

- "@devexpress/dx-react-core": "^2.0.5",
- "@devexpress/dx-react-grid": "^2.0.5",
- "@devexpress/dx-react-grid-material-ui": "^2.0.5",
- react: 16.9.0
- browser: Chrome 79.0.3945.130

**Comment by AryamnovEugeniy** [comment]
Hello,

I've updated your [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-q8hex). There I've overridden three `TableHeaderRow`'s components: [Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowcellprops), [Content](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowcontentprops) and [SortLabel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowsortlabelprops). I've changed several styles and defined `onClick` prop for the `SortLabel`.
Does this solution suit your requirements?

**Comment by psmod2** [comment]
Thanks - I took a look and I actually found a simplier way using CSS - it does the trick but wondering what you think:

So basically to `<TableHeaderRow.SortLabel>` I added a class with the style:

```
titleLabelFull: {
			"& > span": {
				width: "100%"
			}
		}
```

See: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-rqjbv

What I like about this way is that sort arrow also appears when you hover over the cell

**Comment by AryamnovEugeniy** [comment]
Yes, that's even better.
If you have any other questions, feel free to ask them
