### ISSUE TITLE
Is there anyway to disable checkbox based on a criteria in the TableTreeColumn

### ISSUE THREAD

**Issue by jjkaur** [DevExpress/devextreme-reactive#2667]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Grid

### Description
Is there any way to disable checkbox based on a criteria in the TableTreeColumn?

### Environment
none

**Comment by LazyLahtak** [comment]
Hi @jjkaur,

You can use TableTreeColumn's cellComponent and get children from [properties](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-tree-column/#tabletreecolumncellprops). Then you can provide the `disabled` property to the 3-rd child of the cell. Here is an [example](https://codesandbox.io/s/bold-rgb-b399t) with the described workaround.
Also, we will consider about improving our API.
