### ISSUE TITLE
[UPDATED] document `rowComponent` prop for `<TableSelection>` plugin

### ISSUE THREAD

**Issue by cellog** [DevExpress/devextreme-reactive#2668]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I would like to enable Material-UI hover on table rows: https://material-ui.com/api/table-row/

However, when using selection (https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/) with highlightRow and selectByRowClick, this makes it no longer possible to use the `rowComponent` that would enable customization.

How then can I most easily handle this edge case?

**UPDATE: according to https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-selection.tsx the `rowComponent` property is available. This is undocumented. If it were documented, it would satisfy the constraint of this request**

**UPDATE 2: The typescript props also needs to be updated**

### Environment

- devextreme-reactive: 2.4.0
- react: 16.12.0
- browser: Chrome 80
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.8.3

**Comment by LazyLahtak** [comment]
Hi @cellog,

Thank you for your interest in our product.
We have discussed this issue and decided to update our documentation and make TableSelection's `rowComponent` public.

**Comment by cellog** [comment]
Thank you, I really appreciate this!
