### ISSUE TITLE
All Day events do not appear in the Scheduler

### ISSUE THREAD

**Issue by jkernagis2** [DevExpress/devextreme-reactive#2680]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

All day events are not rendering in the scheduler.

### Expected Behaviour

All day events should render in the scheduler.

### Steps to Reproduce

I adjusted the provided scheduler sandbox to show the problem.  All I did was remove all but one appointment (which has allDay = true), and added the <AllDayPanel /> component to the <Scheduler>.

Link to the example that reproduces the issue: https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-w1b6h

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for reporting the issue! We've already fixed this bug in this [Pull Request](https://github.com/DevExpress/devextreme-reactive/pull/2673). The fix will be released very soon. We apologise for this inconvenience.
If you have any other question, feel free to ask them.

**Comment by cuongqle** [comment]
Thanks for the fix. I have got the same issue. Do we have plant to release this fixed version?
Or any idea to get a workaround?

**Comment by AryamnovEugeniy** [comment]
Hello @cuongqle,

A new release, containing the fix, will be available either today or tomorrow. I will update this thread once the fixed version is released.

**Comment by AryamnovEugeniy** [comment]
The version containing the fix has been released

**Comment by cuongqle** [comment]
Thanks @AryamnovEugeniy . Its working great!

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
