### ISSUE TITLE
SelectionState does not work on page 2

### ISSUE THREAD

**Issue by NguyenTheSon** [DevExpress/devextreme-reactive#2681]
When I click one row on page 1 then next to page 2. the corresponding row is ticked

**Comment by AryamnovEugeniy** [comment]
Hello,

I could not reproduce the issue you had described. Could you update [my example](https://codesandbox.io/s/zealous-joliot-k351c) so that the issue would appear? Or could you provide a more detailed description (code snippets and steps to reproduce the issue)?

**Comment by MaximKudriavtsev** [comment]
@NguyenTheSon,

It seems you don't specify the `getRowId` property of the Grid component. Please specify it and use different `id` values for every row. Similar [with](https://github.com/DevExpress/devextreme-reactive/issues/1930).
