### ISSUE TITLE
Editable column without clicking

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2683]
![D4F4B7DF-4499-44BA-B97D-BB8A6EA6228F_1_105_c](https://user-images.githubusercontent.com/13018803/74740228-87b53700-526b-11ea-93a1-2133d8ff150b.jpeg)

I want to show a column fully editable. So I don't want to go into the editing state as I click. I can do this using DataTypeProvider. But when updating row data, the table is re-rendered. I lost the focus from the inputs :(

https://codesandbox.io/s/trusting-cray-h1bct

How do I link the input of "onCommitChanges" to the property.

so inputs will be rendered on every line. so the user will see as soon as the column is editable. Can this column be edited by clicking? he won't have to check.

**Comment by AryamnovEugeniy** [comment]
Hello,

You can use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode) to manage the cells you are editing through `EditingState`'s [editingCells](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/#properties) prop. Just do not remove the cells you need from this array and they will stay in the editing mode. Here is an [example](https://codesandbox.io/s/focused-zhukovsky-6ht4w) based on your sample. In the example I made all cells in the `units` column editable.

Does this solution suit your needs?

**Comment by ahmetcaglayan** [comment]
https://codesandbox.io/s/purple-http-pnhyw

Thanks, it worked, but I am using VirtualTable. While scrolling, the focus is on the inputs. The change event of the inputs is triggered.

How do I block auto focus. If I do that, I think this will be a temporary solution for me. I think you should add the feature that such a column comes in completely editing mode. Otherwise, the user cannot know which column is editable.

**Comment by ahmetcaglayan** [comment]
Thanks I solved it with DataTypeProvider.
