### ISSUE TITLE
Issue that columns with edit mode off render the editing component

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2684]
https://codesandbox.io/s/trusting-golick-skn26

Editing feature of all columns is off. (columnEditingEnabled = false)
edit product column open (columnExtensions={[{ columnName: "product", editingEnabled: true }]})

but when I click on the Shipped column it goes into editing mode.

for some cases, we don't want to show the edit feature in other columns. For example, disabled input appears in other columns. No input appears. In fact, that column is not editable. Clicking on the cell goes into the editing state and does not appear disabled.

**Comment by AryamnovEugeniy** [comment]
Hello,

You should use [disabled](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/#datatypeprovidervalueeditorprops) prop to make your editor read-only. Here is the [updated sample](https://codesandbox.io/s/practical-dew-emx4w).

If you have any other questions, don't hesitate to ask them.

**Comment by ahmetcaglayan** [comment]
You misunderstood my question.
I don't want that component to appear at all when I click.
But it seems even if it is disabled.

**Comment by AryamnovEugeniy** [comment]
In this case you can use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode) and manage `EditingState`'s [editingCells](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/#properties) directly through `editingCells` and `onEditingCellsChange` props. Here is the updated example: https://codesandbox.io/s/silent-shape-2iosi.
Does this solution suit your needs?

**Comment by ahmetcaglayan** [comment]
I think this solves my problem.
Compared to other sold charts, you have a much more helpful team. 
Thank you so much.

**Comment by AryamnovEugeniy** [comment]
I'm glad that it helped!
