### ISSUE TITLE
Customize RadioGroup Buttons

### ISSUE THREAD

**Issue by vealjoshua** [DevExpress/devextreme-reactive#2687]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Scheduler

### Description
I'm trying to remove the "Never" option from the radio group on the appointment from when you click "repeat".

![image](https://user-images.githubusercontent.com/23144377/74893726-ae01d200-5352-11ea-8919-2accc46c84d8.png)

**Comment by AryamnovEugeniy** [comment]
Hello,

This is a part of the `radioGroupComponent`. And to remove `Never` option, you will have to override this component. First of all, you need to find it by its type: it is of `endRepeat` type. And then we advise you to copy the content of [this file](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/appointment-form/recurrence/radio-group/end-repeat-editor.jsx) and just delete unnecessary parts from it.
To illustrate this, I made an [example](https://codesandbox.io/s/laughing-ptolemy-f04rw) where I deleted the `Never` option from the `AppointmentForm`.
