### ISSUE TITLE
[Scheduler] Resources color palette

### ISSUE THREAD

**Issue by ARL64** [DevExpress/devextreme-reactive#2688]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi, I am using the Resources plugin. I have three resources. 1st resource have 10 possible values. 2nd resource have between 10 and 20 possible values and last resource has only 4 possible values.
My question is how many colors can be handled with the default color when no color palette is specified for the resource ?

16 from the default palette ? [red, pink, purple, deepPurple, indigo, blue, lightBlue, cyan, teal, green, lightGreen, lime, yellow, ember, orange, deepOrange]

When I click to the appointment to show the AppointmentTooltip I'm getting this error :
<img width="1404" alt="Capture d’écran 2020-02-20 à 09 35 09" src="https://user-images.githubusercontent.com/837109/74916944-04105d00-53c7-11ea-8786-71d4a77b7ff5.png">

Is this a bug or I am doing something wrong ?

### Environment

- devextreme-reactive: 2.4.0
- react: 16.12.0
- browser: Opera GX 66.0
- material-ui: 4.9.3

**Comment by AryamnovEugeniy** [comment]
Hello,

Thank you for reporting the issue, we will fix this as soon as possible.
In the meantime, we advise you to assign colors to your [resource instances](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/resources/#resourceinstance).  You may create your own colors (a color is an object that contains the following fields: 50, 100, 200, 300, etc., see the [Material-UI guide on colors](https://material-ui.com/customization/color/)). And I've made a [small example](https://codesandbox.io/s/modern-smoke-19ri3) where I use 20 resources, and the color of the last one is a color object described above.
But there is another option. You may create a custom [palette](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/resources/#palette) which will contain as many colors as you need.

**Comment by ARL64** [comment]
Thank you very much. It's very clear now. I'll make a custom palette in the meantine 👍 

Thanks to take time to make a detailed answer.

**Comment by AryamnovEugeniy** [comment]
You are welcome!
