### ISSUE TITLE
Remote Dropdown Column Filter 

### ISSUE THREAD

**Issue by furkanilhan** [DevExpress/devextreme-reactive#2692]
### I'm using ...

- [x] React Grid

### Description

(I search the issue make haven't seen same questions)
I'm just want to check is it possible to make filter function next to table header row with an icon when it clicks the icon have a dropdown with the filter selection which items comes from remote api.
Like image below:
![image](https://user-images.githubusercontent.com/21006973/75023735-59bd3600-54a9-11ea-9e8e-cc1570604be0.png)

When i select one or multiple item and click OK button from dropdown, I want to make remote request to the api.

[Here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/React/Light/) is the example from devextreme data grid. 

Thanks

**Comment by ushkal** [comment]
Hi @furkanilhan ,

I suggest you use an approach from this [issue](https://github.com/DevExpress/devextreme-reactive/issues/2119). Please let me know if it helps

**Comment by furkanilhan** [comment]
@ushkal How do you implement the multiple selection for a column

**Comment by ushkal** [comment]
@furkanilhan ,

I apologize for the delayed response. Here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-20jez).

**Comment by furkanilhan** [comment]
Thank you for your response. I have a little annoying problem. The problem is when you select one of the filter from dropdown, the dropdown closes immediately as you can realize. And when I want to select another filter I have to open dropdown again. I have a lot of columns and a  lot of filters so this is an annoying problem for my users. What I want to do is make user able to select multiple filter from one dropdown without closing.

**Comment by ushkal** [comment]
@furkanilhan,

I've updated the [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xjtp3). Now the drop-down menu closes when you click outside its borders.
