### ISSUE TITLE
[Scheduler] Update resources after first initialization

### ISSUE THREAD

**Issue by ARL64** [DevExpress/devextreme-reactive#2693]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

Hello,

I am using the Resources plugin and the AppointmentTooltip. Resources are found when I fetch my appointments. This means that resource's possible values are updated in time and my appointments are using the exact resource's possible values.

![planning_error](https://user-images.githubusercontent.com/837109/75038472-b96e0e00-54b6-11ea-915b-b525c26357e6.png)

So at initialization I get like 20 possible values for the resource, when I click to the next week or next month I can get only 10 possible values (the 20 and the 10 possible values are used). It seems that appointments are rendered before resource is updated and sometimes I get this error :

<img width="1404" alt="Capture d’écran 2020-02-21 à 14 16 48" src="https://user-images.githubusercontent.com/837109/75038286-6005df00-54b6-11ea-8908-c1d11634881b.png">

### Expected Behaviour

Update resource before render new fetched appointments?

### Steps to Reproduce

In this example users are generated from the appointments in the action. 

Reducer:

```js
 case SET_APPOINTMENTS:
  draft.appointments = action.appointments;
  draft.users = action.users;
  draft.loading = false;
  break;
```

Component:

```js
const { appointments, users } = store;
```

```js
<Scheduler data={appointments}>
  ...
  <ViewState
    currentViewName={currentView}
    onCurrentDateChange={date => setCurrentDate(date)} // API fetch
    onCurrentViewNameChange={view => setCurrentView(view)} // API fetch
   />
  ...
  <Resources
    data={[
      {
        fieldName: 'userId',
        title: 'User',
        instances: users, // From the store updated when appointments are updated
        },
    ]}
  />
</Scheduler>
```

### Environment

- devextreme-reactive: 2.4.0
- react: 16.12.0
- browser: Opera GX 66
- material-ui: 4.9.3

**Comment by AryamnovEugeniy** [comment]
Hello @ARL64!

Thank you for reporting the issue. We will fix this as soon as possible.
