### ISSUE TITLE
React Scheduler Appearance Customization demo crashes

### ISSUE THREAD

**Issue by MaximKudriavtsev** [DevExpress/devextreme-reactive#2694]
### I'm using ...

- [x] React Scheduler

### Steps to Reproduce
- go to [demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/)
- open appointment tooltip
- switch another task priority
- demo crashes

### Env
- devextreme-reactive: 2.4.1
- browser: Crome
- os: MacOs

**Comment by AryamnovEugeniy** [comment]
I close this as a duplicate of #2693
