### ISSUE TITLE
zebra row in VirtualTable problem

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2697]
https://codesandbox.io/s/elegant-greider-11ctf

Using your example, I just added the VirtualTable feature. 
But as you scroll, the line ads change.

Look at line 9. The color changed as I scrolled.

![5C2082B4-41EA-44A1-87F6-435341540C2D_1_105_c](https://user-images.githubusercontent.com/13018803/75147264-f3851d00-570d-11ea-91ad-22004e732077.jpeg)

![ED619EC7-DEBF-4976-B3F1-CA6144CBF37F](https://user-images.githubusercontent.com/13018803/75147270-f5e77700-570d-11ea-96ac-1fb75415a75b.jpeg)
![B8D9DBE5-C54D-4801-B64A-B2B92E1C2141](https://user-images.githubusercontent.com/13018803/75147272-f6800d80-570d-11ea-918b-6864a8268c2f.jpeg)

**Comment by MaximKudriavtsev** [comment]
We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/1407).
