### ISSUE TITLE
Include currently selected filter operation in DataTypeProvider.ValueEditorProps

### ISSUE THREAD

**Issue by jjordy** [DevExpress/devextreme-reactive#2698]
### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Ability to get current filter operation inside of a custom editorComponent.

I have a custom Date range filter that i am applying to date columns, in addition i have added a custom "between" filter option. It would be ideal if the ``DataTypeProvider.ValueEditorProps`` also provided the currently selected filter option so you could make decisions in the custom component based on that selected filter. If this is already possible and I am missing something please feel free to close this issue.

Thanks, Jordy

**Comment by LazyLahtak** [comment]
Hi @jjordy,

You can add properties to `DataTypeProvider.ValueEditor`. Refer to this [topic](https://github.com/DevExpress/devextreme-reactive/issues/2303) to see how you can get filter options ("contains", "equal", e.t.c) on their change. Here is an [example](https://codesandbox.io/s/distracted-leavitt-tl7tz) illustrating this for your scenario.
Let us know if it meets your requirements.

**Comment by jjordy** [comment]
@LazyLahtak I believe this will solve my use case perfectly thanks for the example code.

**Comment by LazyLahtak** [comment]
You're welcome!
