### ISSUE TITLE
Simple Dropdown on a single cell

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2700]
- I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
I'm using 
- [ ] React Grid

### Description
    I went through the docs but the implementation of the dropdown of a single cell was quite complicated. I want to have a simple dropdown with 3 items on a cell. 

### Environment

- devextreme-reactive: v 2.3.0
- react: v 16
- browser: Chrome
- bootstrap: v 4.0
- react-bootstrap: v 4.0.3

**Comment by LazyLahtak** [comment]
Hi @lutakyn,

We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/1178). Aslo [here](https://getbootstrap.com/docs/4.0/components/dropdowns/) is how you can implement a dropdown in bootstrap 4.
Does it meet your requirements?

**Comment by lutakyn** [comment]
I fixed it with a simple select and it worked.Thank you for your example

**Comment by LazyLahtak** [comment]
You are welcome!
