### ISSUE TITLE
Responsive Scheduler MonthView Height

### ISSUE THREAD

**Issue by troyschneringer** [DevExpress/devextreme-reactive#2706]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [x] React Scheduler

### Description
I am trying to have the height of the scheduler when in MonthView be responsive to full height of the containing element on the page.  However, the height of each of the TimeTableCell elements appears to be fixed and doesn't fill.

<img width="1715" alt="Screen Shot 2020-02-26 at 11 15 54 AM" src="https://user-images.githubusercontent.com/1273031/75378999-85fdfb80-5889-11ea-8c9d-710880396eab.png">

### Environment
- devextreme-reactive: 2.4.0
- react: 16.12
- browser: Chrome 80
- material-ui: 4.9.2

**Comment by MaximKudriavtsev** [comment]
Hi @troyschneringer,

We don't have this functionality out of the box. My suggestion is to set `height` for the [MonthView.TimeTableCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/month-view/#monthviewtimetablecellprops) component.

See the following [demo](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-uub1g) for more information.
