### ISSUE TITLE
How to right-align text in TableFilterRow.Cell

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#2707]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I have set up a Table that uses the TableFilterRow. The columns in this table have right-aligned text. I'm currently unable to figure out how to make the text in the Filter cell right-aligned to match with the column.

Any help would be greatly appreciated, thank you

### Environment

    "@devexpress/dx-react-core": "^2.3.2",
    "@devexpress/dx-react-grid": "^2.3.2",
    "@devexpress/dx-react-grid-material-ui": "^2.3.2",
    "@material-ui/core": "^4.8.0",

**Comment by ushkal** [comment]
Hi @thehig ,

You need to override the [TableFilterRow’s](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#properties) editorComponent and provide the necessary css rules. Here’s an [example](https://codesandbox.io/s/silly-thunder-wqnix).

**Comment by thehig** [comment]
Yep. Works perfectly. Thank you!
