### ISSUE TITLE
DefaultFilters props is possible for FilteringState in controlled grids?

### ISSUE THREAD

**Issue by esinoner** [DevExpress/devextreme-reactive#2708]
I am using grids in different tabs, when a user change tabs, grids render with same props. But if user used filters for grid in the first tab and goes to the second tab and returns, user see filtered grid but nothing in the column filter editor, this causes complexity. I want to render grid with same grid filters without going to the service. I think defaultfilters prop can solve problem, but it doesnt work for controlled grids.

**Comment by LazyLahtak** [comment]
Hi @esinoner,

I created an [example](https://codesandbox.io/s/brave-monad-jtl5w) based on your description. Could you please try it? If the solution I demonstrated doesn't meet your requirements, please clarify your scenario.

**Comment by esinoner** [comment]
Hi LazyLahtak,
Your example matches my requirements with a difference, i am using remote mode, thats why am not using IntegratedFiltering component, is it still possible to keep selected filters on tab changes?

**Comment by LazyLahtak** [comment]
Hi @esinoner,

In the case of remote filtering, you need to pass the `filters` property into the `FilteringState` plugin, but remove `IntegratedFiltering`. Then, you'll keep values in `TableFilterRow`. Here is an updated [example](https://codesandbox.io/s/zealous-mountain-7je0m).

**Comment by esinoner** [comment]
Hi LazyLahtak,
Thank you very much for the examples you prepared and for your interest

**Comment by LazyLahtak** [comment]
You are welcome!
