### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by semy** [DevExpress/devextreme-reactive#2709]
Since React v16.13.0 the following warning are visible:
"Warning: Cannot update a component from inside the function body of a different component."

See here:
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html

I get this warning for all StateComponents. 

SelectionStateBase, RowDetailStateBase etc.

Would be nice if you could fix this. Thank you!

**Comment by ushkal** [comment]
Hi @semy,

Thank you for reporting this problem. We'll fix it soon.

**Comment by nailtonoliveira** [comment]
Same issue here on `PagingStateBase`, any updates about the fix?
