### ISSUE TITLE
Show filling percentage for a day / overlapping events alert

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#2718]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello, i'm wondering if it's possible to calculate / show the filling percentage for everyday, i.e. how busy that day is, if the events cover all the timeslots then it would show 100%. And is there a way to detect and alert over overlapping events (is it even possible to have overlapping events ?)

Thanks a lot.

**Comment by MaximKudriavtsev** [comment]
Hi @vtrphan,

We don't have these features out of the box. However, you can easily calculate them manually by using your own appointments array and currentDate from the [ViewState](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/view-state/) plugin. You can pass calculated values into the `DayScaleCell` component. Refer to this [Guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/) to learn how to use our components and how to customize them.
