### ISSUE TITLE
Cannot create group row stub cell

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2722]
https://codesandbox.io/s/muddy-wood-l155s

![image](https://user-images.githubusercontent.com/13018803/75880944-4efe8b80-5e2f-11ea-84d2-ff61d0da56e9.png)

![image](https://user-images.githubusercontent.com/13018803/75881339-e49a1b00-5e2f-11ea-9d45-131e3fce6a91.png)

![image](https://user-images.githubusercontent.com/13018803/75881596-72760600-5e30-11ea-8c43-6fd759d2d690.png)

It happens for line 2. But it doesn't happen for group number 1 line. Border does not appear.

**Comment by ahmetcaglayan** [comment]
![image](https://user-images.githubusercontent.com/13018803/75881864-fe882d80-5e30-11ea-870a-b5bf952f6746.png)

Another problem, is that even though I don't add subtotal sum to the groups, it becomes empty line.

**Comment by ahmetcaglayan** [comment]
![image](https://user-images.githubusercontent.com/13018803/75951776-ec080580-5ebd-11ea-8b01-f469f908abea.png)

When I don't use groupItems in SummaryState, it shows the group line properly.

`
<SummaryState totalItems={props.summaryItems} groupItems={[]} />
`

**Comment by ushkal** [comment]
Hi @ahmetcaglayan ,

Thank you for reporting this problem. I've reproduced it and we'll fix it soon.

**Comment by ahmetcaglayan** [comment]
![image](https://user-images.githubusercontent.com/13018803/76515688-14b66f00-646b-11ea-8f76-39c5d159ac3b.png)

hello, I bought it using 2.5.1v. The above problem has been fixed. But the second problem I mentioned continues. When you print the total up, the blank line remains below.
