### ISSUE TITLE
Accessibility: column headers and query results are rendered as separate tables instead of a single one when using lazy loading

### ISSUE THREAD

**Issue by Neurrone** [DevExpress/devextreme-reactive#2728]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When using lazy loading, table headers and actual data are rendered as 2 separate tables instead of a single one. This causes accessibility problems, since for instance, screen readers won't be able to inform users about the column's header when moving in the second table since semantically the 2 tables are unrelated and it can't infer the column/data relationship.

### Expected Behaviour
Column headers and data rendering in a single table.

### Steps to Reproduce

See the [lazy loading example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/) - e.g the basic example sandbox.

### Environment

N/A

**Comment by ushkal** [comment]
Hi,

The grid header and content are rendered in a separate table due to technical limitations: it's impossible to fix a thread element using a sticky position. See this chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=702927) for more details. We will consider fixing this issue once the chromium bug is fixed.

**Comment by Neurrone** [comment]
Would the approach outlined in this article on [fixed table headers](https://adrianroselli.com/2020/01/fixed-table-headers.html) work?

**Comment by LazyLahtak** [comment]
Hi @Neurrone
 
Thank you for sharing your opinion. This article may be helpful and we will consider adding it in the future. We need time to research this.

**Comment by aardrian** [comment]
> See this chromium bug for more details. We will consider fixing this issue once the chromium bug is fixed.

The Chromium bug is fixed and deployed, and Safari 14 no longer requires a prefixed style.
* https://developer.chrome.com/blog/tablesng/
* https://adrianroselli.com/2020/01/fixed-table-headers.html#Update02

**Comment by Neurrone** [comment]
Thanks @Krijovnick for fixing this.
