### ISSUE TITLE
TypeScript error: Cannot find module 'exceljs'

### ISSUE THREAD

**Issue by Methuselah96** [DevExpress/devextreme-reactive#2731]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

TypeScript fails to build with:
```
ERROR in C:/projects/project/node_modules/@devexpress/dx-react-grid/dist/dx-react-grid.d.ts(6,22):
TS2307: Cannot find module 'exceljs'.
```

### Expected Behaviour

TypeScript successfully builds.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.5.0
- react: N/A
- browser: N/A
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi @Methuselah96 ,

Thank you for reporting this issue. We'll fix it soon.
