### ISSUE TITLE
Can't read property ''any_property'' of undefined

### ISSUE THREAD

**Issue by KindBear** [DevExpress/devextreme-reactive#2733]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

Hey! last week I work with scheduler and have a lot of exceptions Can't read property ''any_property'' of undefined. Why you don't check is property undefined or not? And how I have this exception when I pass an empty array to Resources data props;

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/pedantic-brown-to1g0&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @KindBear,

You should define the `instances` value of the `resources` property. See the following [example](https://codesandbox.io/s/goofy-bose-pp785).
