### ISSUE TITLE
custom input with button using TableInlineCellEditing

### ISSUE THREAD

**Issue by texas697** [DevExpress/devextreme-reactive#2735]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment
```
`const AmountInput = ({
  value, onValueChange, onBlur, autoFocus
}) => {
  const classes = useStyles();
  const dispatch = useDispatch();
  const isAmountOpen = useSelector(selectors.getIsAmountOpen);

  const onChange = (e) => {
    const val = e.target.value;
    console.log(val);
    onValueChange(val);
  };

  const toggleAmountRow = () => {
    console.log(isAmountOpen);
    dispatch(actions.toggleIsAmountOpen(!isAmountOpen));
  };

  return (
    <React.Fragment>
      <InputBase
        autoFocus={autoFocus}
        onBlur={onBlur}
        fullWidth
        value={value}
        className={classes.input}
        onChange={onChange}
        inputProps={{ 'aria-label': 'amount-input' }}
      />
      <IconButton onClick={toggleAmountRow} className={classes.iconButton} aria-label="amount-input-btn">
        {isAmountOpen ? <ExpandMoreIcon /> : <ExpandLessIcon />}
      </IconButton>
    </React.Fragment>
  );
};

const AmountInputProvider = props => (
  <DataTypeProvider
    editorComponent={AmountInput}
    {...props}
  />
);

export default AmountInputProvider;`
```

```
`<AmountInputProvider for={config.INPUT_BUTTON_COLUMNS} />`
```

- devextreme-reactive: 2.5.0
- react: 16.12.0
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.3.3

**Comment by LazyLahtak** [comment]
Hi @texas697,

I've made an [example](https://codesandbox.io/s/agitated-greider-tvzm8) based on your code. Does it meet your requirements?

**Comment by texas697** [comment]
Perfect! thank you very much!

**Comment by LazyLahtak** [comment]
You are welcome!
