### ISSUE TITLE
VirtualRowsCache not reset when onFiltersChange in 

### ISSUE THREAD

**Issue by sitajaf** [DevExpress/devextreme-reactive#2739]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When using VirtualTable with remote filtering, if one scrolls further down resulting in loading of more data, if one filters by a value that is clearly in the table (meaning it exists), just an empty grid with the right column count is rendered.

After some investigation, I believe it's because the VirtualRowsCache is not reset when the filter parameters change which leaves `skip` value as the same.  This results in wrong parameters being sent while fetching remote data. e.g
if skip = 200 and take=300, if the result is among the first 10 results, it is not returned and yet the totalRowCount will be correct. 

### Expected Behaviour
The `skip` value should be reset to 0 when onFiltersChange in the FilteringState is called. 

### Steps to Reproduce
While using `VirtualTableBase` and FilteringState with remote filters i.e filters and onRemoteFiltering managed externally:
- Scroll down until more results are loaded in the table. i.e `skip` > 0
- Filter by any value currently visible in the grid

### What I have tried
One way I can solve this by directly calling `clearRowCache` action. This can be through:
- extending FilteringState and using a custom plugin with TemplateConnector and calling actions.clearRowCache(). e.g
```
<Plugin>
    <TemplateConnector>
      {(getters, actions) => {
        actions.clearRowCache();
        return null;
      }}
    </TemplateConnector>
  </Plugin>
```
The problem with this is it's called in render hence problems of updating state while rendering.
- Calling actions.clearRowCache before I call `onFiltersChange`, but there is no way (that I know of) to access the global `actions` without going though a plugin with TemplateConnector like above.

### Screenshots
<img width="947" alt="Screen Shot 2020-03-12 at 1 28 22 am" src="https://user-images.githubusercontent.com/4855439/76427801-e603ae80-6400-11ea-96ba-bf797869b58f.png">

### Environment

- devextreme-reactive: 19.1.6
- devextreme-react: 19.1.6
- dx-react-grid-bootstrap4: 2.0.5
- react: 16.8.1
- browser: chrome (all browsers though)
- bootstrap: 4

**Comment by LazyLahtak** [comment]
Thank you for reporting the problem. We will fix it soon.

**Comment by sitajaf** [comment]
@LazyLahtak , any update on this?

**Comment by LazyLahtak** [comment]
Hi @sitajaf 

The fix will be available in the nearest release.

**Comment by sitajaf** [comment]
Hey @LazyLahtak,
Thanks for working on this and responding.
Any idea on the release timelines? We have this issue currently in prod and are keen on closing it as soon as possible.
Thanks again.

**Comment by LazyLahtak** [comment]
Hi @sitajaf,

We release a new version every few weeks.
Also, you may use the following workaround: on filter change you should scroll up the table and reset `skip` value to 0. Here is an [example](https://codesandbox.io/s/adoring-surf-k1sf4).

**Comment by sitajaf** [comment]
Thanks @LazyLahtak,
Let me have a look.
