### ISSUE TITLE
An empty group summary row is rendered if no total group summaries are specified

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2741]
![image](https://user-images.githubusercontent.com/13018803/76515688-14b66f00-646b-11ea-8f76-39c5d159ac3b.png)

https://github.com/DevExpress/devextreme-reactive/issues/2722#event-3114189574

Hello, I bought it using 2.5.1v. But the second problem I mentioned continues. When you print the total up, the blank line remains below.

**Comment by ushkal** [comment]
Hi @ahmetcaglayan ,

I've reproduced this behavior. We'll fix it soon.
