### ISSUE TITLE
I am using dev express version 2.1.2. I am trying to use SummaryState plugin. It does not work for me. Does it have to do with the version ?

### ISSUE THREAD

**Issue by anushaNemilidinne** [DevExpress/devextreme-reactive#2745]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by anushaNemilidinne** [comment]
https://codesandbox.io/s/currying-voice-7nhnl link to my example

**Comment by ushkal** [comment]
Hi @anushaNemilidinne ,

You need to add the TableSummaryRow plugin to render the group summary row. Here's an updated [example](https://codesandbox.io/s/eloquent-morning-qnt3w).

**Comment by anushaNemilidinne** [comment]
I actually do not need a summary row but just display the count in each group as shown. 

![image](https://user-images.githubusercontent.com/35274794/76661474-87961780-6549-11ea-9d31-afd051fe5a78.png)

In the link i provided, if you change the version to 2.5.1. It works

**Comment by anushaNemilidinne** [comment]
![version](https://user-images.githubusercontent.com/35274794/76661979-c082bc00-654a-11ea-961b-01c8e80efb23.png)

Seems like I missed this part. Upgrading of my version to latest resolves the issue.

Thanks @ushkal.

**Comment by ushkal** [comment]
> Upgrading of my version to latest resolves the issue.

Yes, this functionality was implemented in v2.3.1.
> Thanks @ushkal.

You are welcome!
