### ISSUE TITLE
ArgumentScale factory type is not compatible with d3-scale's scaleTime

### ISSUE THREAD

**Issue by mehdithreem** [DevExpress/devextreme-reactive#2746]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Chart
- [ ] React Grid
- [ ] React Scheduler

### Current Behaviour

If you rewrite [this demo](https://devexpress.github.io/devextreme-reactive/react/chart/demos/line/log-time-axes) in typescript, you will get the following error:

```Type '{ (): ScaleTime<number, number>; <Output>(): ScaleTime<Output, Output>; <Range, Output>(): ScaleTime<Range, Output>; }' is not assignable to type 'FactoryFn'.
  Call signature return types 'ScaleTime<number, number>' and 'ScaleObject' are incompatible.
    The types returned by 'domain(...)' are incompatible between these types.
      Type 'Date[]' is missing the following properties from type 'ScaleObject': domain, range, copy  TS2322
```

### Expected Behaviour

`factor`y attribute can be set with `scaleTime`

### Steps to Reproduce

[CodeSandbox](https://codesandbox.io/s/dx-react-chart-example-argumentscales-factory-types-jk8jz).

### Environment

```
  "dependencies": {
    "@devexpress/dx-react-chart": "^2.5.1",
    "@devexpress/dx-react-chart-material-ui": "^2.5.1",
    "@devexpress/dx-react-core": "^2.5.1",
    "@material-ui/core": "latest",
    "@material-ui/icons": "^4.9.1",
    "@types/d3-scale": "^2.2.0",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@types/react-router-dom": "^5.1.3",
    "@types/webpack-env": "^1.15.1",
    "d3-scale": "^3.2.1",
    "jss-rtl": "^0.3.0",
    "react": "latest",
    "react-dom": "latest",
    "react-router-dom": "^5.1.2",
    "react-scripts": "latest",
    "typescript": "latest"
  },
```

**Comment by AryamnovEugeniy** [comment]
Hello,

Thank you for reporting the issue. We will fix it soon.
