### ISSUE TITLE
React Grid crashes when scaling root node while using VirtualTable

### ISSUE THREAD

**Issue by LvWentao** [DevExpress/devextreme-reactive#2749]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Current Behaviour

when I set "transfrom: scale(0.5)" in root node and set height="auto" in VirtualTable plugin, 
React Grid crashed

### Link to Sandbox:
https://codesandbox.io/s/musing-mclean-ge7yq

**Comment by LazyLahtak** [comment]
Hi @LvWentao,

Thank you for your report. We need some time to investigation this issue.

**Comment by LazyLahtak** [comment]
Hi @LvWentao,

We found that the fix of this issue can break a number of other popular scenarios and affect a lot of users. So, we decided to revert it in this PR: #2866.

We also double-checked this case and found that you can address the issue using this approach: [https://codesandbox.io/s/sad-dawn-rqutn?file=/index.html](https://codesandbox.io/s/sad-dawn-rqutn?file=/index.html).

Please let us know if this solution meets your requirements.
