### ISSUE TITLE
Appointment tooltip display on mouse hover

### ISSUE THREAD

**Issue by cuongqle** [DevExpress/devextreme-reactive#2752]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi, is it possible to show appointment tooltip when mouse over on appointment instead of clicking on it? If not, do we have any workaround to gain this?

**Comment by AryamnovEugeniy** [comment]
Hello!

I made a [small example](https://codesandbox.io/s/priceless-microservice-wsrn1) on how to accomplish this.  First of all, you need to use `AppointmentTooltip` in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/#controlled-mode). Then, you need to override `Appointments`' [apppointmentComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentprops) and define `onMouseEnter` and `onMouseLeave` there. And finally, override `AppointmentTooltip`'s [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmenttooltiplayoutprops) as I've done in the sample to make MUI's Popover work with `onMouseEnter` and `onMouseLeave`.

**Comment by cuongqle** [comment]
> Hello!
> 
> I made a [small example](https://codesandbox.io/s/priceless-microservice-wsrn1) on how to accomplish this. First of all, you need to use `AppointmentTooltip` in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/#controlled-mode). Then, you need to override `Appointments`' [apppointmentComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentprops) and define `onMouseEnter` and `onMouseLeave` there. And finally, override `AppointmentTooltip`'s [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmenttooltiplayoutprops) as I've done in the sample to make MUI's Popover work with `onMouseEnter` and `onMouseLeave`.



> Hello!
> 
> I made a [small example](https://codesandbox.io/s/priceless-microservice-wsrn1) on how to accomplish this. First of all, you need to use `AppointmentTooltip` in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/#controlled-mode). Then, you need to override `Appointments`' [apppointmentComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentprops) and define `onMouseEnter` and `onMouseLeave` there. And finally, override `AppointmentTooltip`'s [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmenttooltiplayoutprops) as I've done in the sample to make MUI's Popover work with `onMouseEnter` and `onMouseLeave`.

Hi @AryamnovEugeniy ,

Thanks for quickly response. Yep, sample working great, however, with style pointer-events: none in tooltip popover, we will not able to interact tooltip popup event if it showing Edit / Delete / Close button.
![image](https://user-images.githubusercontent.com/7144697/76835370-8a527e80-6861-11ea-93ea-08187682c823.png)
Any alternative way that able to interact tooltip popup?

Thanks/Cuong

**Comment by cuongqle** [comment]
> > Hello!
> > I made a [small example](https://codesandbox.io/s/priceless-microservice-wsrn1) on how to accomplish this. First of all, you need to use `AppointmentTooltip` in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/#controlled-mode). Then, you need to override `Appointments`' [apppointmentComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentprops) and define `onMouseEnter` and `onMouseLeave` there. And finally, override `AppointmentTooltip`'s [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmenttooltiplayoutprops) as I've done in the sample to make MUI's Popover work with `onMouseEnter` and `onMouseLeave`.
> 
> Hi @AryamnovEugeniy ,
> 
> Thanks for quickly response. Yep, sample working great, however, with style pointer-events: none in tooltip popover, we will not able to interact tooltip popup event if it showing Edit / Delete / Close button.
> ![image](https://user-images.githubusercontent.com/7144697/76835370-8a527e80-6861-11ea-93ea-08187682c823.png)
> Any alternative way that able to interact tooltip popup?
> 
> Thanks/Cuong

Ok, no worries @AryamnovEugeniy , i can manage to interact it as well, thank you for your time!

**Comment by AryamnovEugeniy** [comment]
You are welcome!
