### ISSUE TITLE
All day panel - customize

### ISSUE THREAD

**Issue by cuongqle** [DevExpress/devextreme-reactive#2754]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi,

Is it possible to custom all day panel? I would like to render it manually, because it having layout issue in IE and i know we do not support older browsers such as IE11. This is how it is displaying on IE11:

![image](https://user-images.githubusercontent.com/7144697/76848019-90525a80-6875-11ea-8273-e40f8b2df409.png)

Thanks/Cuong

**Comment by AryamnovEugeniy** [comment]
Hello,

Yes, it's possible. AllDayPanel is made of the following components: [Cell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelcellprops), [Row](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelrowprops), [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanellayoutprops), [TitleCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypaneltitlecellprops), [Container](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelcontainerprops) and [AppointmentLayer](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelappointmentlayerprops). All of them are customizable. Here is [AllDayPanel`s API](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/). And here is our [guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance) on appearance customization.
If you have any other questions, don't hesitate to ask them.

**Comment by cuongqle** [comment]
> Hello,
> 
> Yes, it's possible. AllDayPanel is made of the following components: [Cell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelcellprops), [Row](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelrowprops), [Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanellayoutprops), [TitleCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypaneltitlecellprops), [Container](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelcontainerprops) and [AppointmentLayer](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/#alldaypanelappointmentlayerprops). All of them are customizable. Here is [AllDayPanel`s API](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/all-day-panel/). And here is our [guide](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance) on appearance customization.
> If you have any other questions, don't hesitate to ask them.
I will. Thanks @AryamnovEugeniy
