### ISSUE TITLE
Warning when clicking a checkbox to select row

### ISSUE THREAD

**Issue by mrowe009** [DevExpress/devextreme-reactive#2756]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When selecting a row on the table through the checkbox, this warning appears

`Warning: Cannot update a component from inside the function body of a different component.`

### Expected Behaviour

No warning to appear when clicking a checkbox

### Steps to Reproduce

copying the same example used in the demos reproduces the behavior

### Environment

- devextreme-reactive: xxx
- react: 16.13.0
- browser: Brave
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.5

**Comment by ushkal** [comment]
Hi @mrowe009 ,

We have already fixed this issue in the context of #2709
