### ISSUE TITLE
VirtualTableState and FilteringState resulting in Race Condition

### ISSUE THREAD

**Issue by christofflueck** [DevExpress/devextreme-reactive#2759]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
We're evaluating Grid Libraries for our rebuild of our current Website using React. Our old website uses jqGrid so we're trying to reproduce the same functionalities.
Our first goal was to have virtual scrolling, then filtering (which both worked) and now we're trying to achieve both at the same time. This is all for remote data. But the getRows function gets called before the setState withing onFiltersChange had time to take effect. Resulting in reverting that state change. Are we using this wrong?

Link to the example that reproduces the issue: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-uz698

### Environment
 - Windows using Webstorm

  "dependencies": {
    "@devexpress/dx-react-core": "^2.5.1",
    "@devexpress/dx-react-grid": "^2.5.1",
    "@devexpress/dx-react-grid-material-ui": "^2.5.1",
    "@material-ui/core": "^4.9.7",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/pickers": "^3.2.10",
    "react": "16.12.0",
    "react-dom": "16.12.0",

**Comment by ushkal** [comment]
Hi @christofflueck ,

I recommend you use the useReducer hook instead of useState for a complex state. Here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0fn6c). Please let me know if it helps you.

**Comment by christofflueck** [comment]
hi @ushkal 
Thank you for your response. In the example you've given me there's still bugs with the state not being updated correctly. When I input a filter it sends up to 3 requests, the first with the new filter, the 2nd with the old filter and the 3rd with the new filter again. This leads to race conditions again and makes the data change rapidly. Is the grid not meant for pure remote data fetching with virtual scrolling?

**Comment by ushkal** [comment]
@christofflueck here's an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0fn6c) where this problem is fixed.
