### ISSUE TITLE
Reactive Grid adding 2 rows on click

### ISSUE THREAD

**Issue by FrancoAucamp** [DevExpress/devextreme-reactive#2760]
A checked check box should look like this: [x]

- [x] I have searched this repository's [issues]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

   This is my first time using github for support so excuse me if i don't know the odds and ends. I use the reactive grid material ui with editing (used the demo as starting point) to add a new row with predefined values in the changeAddedRows. When the user clicks on the new button for some reason it adds 2 identical rows with the same id(i use a guid). I've been stuck on this for 2 days, any help or pointers would be greatly appreciated.

Link to the example that reproduces the issue: &lt;https://github.com/FrancoAucamp/devextreme-reactive/commit/c5dab94b757f918ed295bf4b014fa1c5c68b980e&gt; 
### Environment

- devextreme-reactive: 2.4.1
- react: 16.10.2
- browser: Chrome Latest
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.4

**Comment by AryamnovEugeniy** [comment]
Hello!

You use a lot of external code that is not accessible to us. Could you modify [this example](https://codesandbox.io/s/ovnve) so that the issue would appear?

**Comment by FrancoAucamp** [comment]
My bad, had 
<TableEditRow
cellComponent=
{EditCell}
/>         
twice in the return of my functional component.
