### ISSUE TITLE
Can I customize Scheduler cells based on custom data passed to the Scheduler?

### ISSUE THREAD

**Issue by nevadyzm** [DevExpress/devextreme-reactive#2763]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hi!
I'm evaluating the React Scheduler component for a startup company that I'm a co-founder of.
I'm trying to customize the background color of different cells, similar to how it's done for weekends in "Customize the Appearance" section here:
https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals#customize-the-appearance

The only difference is, I would like to do the customization based on my custom data. Is it possible to pass additional parameters to the scheduler in a way that makes them available in TimeTableCellBase component? 
To be more precise, I would like to somehow pass "greyOutStartDate" and "greyOutEndDate" to the scheduler so that every cell in between those dates will have a grey background. 
I'll greatly appreciate any guidance you can provide on this, React Scheduler looks great and I really hope we can use it in our product. 

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.5.0
- react: 16.12.0
- browser: xxx
- bootstrap: 4.4.1
- react-bootstrap: none
- material-ui: 4.9.5

**Comment by AryamnovEugeniy** [comment]
Hello!

Yes, that is possible. All you need is to pass your props to the cell component you want to customize. I would advise using a state management library, such as [Redux](https://redux.js.org/). [Here](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) we have an article on how to pass props to our components. And here I made an [example](https://codesandbox.io/s/wonderful-voice-zq8eo) in case you do not want to use `Redux`: I used the [connectProps](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/connect-props/) function, which creates a new component that allows you to pass additional properties to the wrapped component. In the example I passed `myCustomProp` to the [TimeTableCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimetablecellprops).
Does this suit your needs?

**Comment by nevadyzm** [comment]
Thank you so much, this is exactly what I was looking for!
I really appreciate the quick response!
