### ISSUE TITLE
Add example for sorting with multiple columns

### ISSUE THREAD

**Issue by kor0p** [DevExpress/devextreme-reactive#2764]
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I several days read docs and finally created this [sandbox](https://codesandbox.io/s/practical-currying-ky44f) from example to have multiple columns sorted. I don't understand why there not similar example in docs. Can you provide that? It will be very cool for newcomers. Also thanks for your great libs!

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product! Sorting by multiple columns is allowed in the Grid by default. All you need is to click several columns while holding `Shift` to sort data by these columns. Clicking a column while holding `Ctrl` (`Cmd` for MacOS) cancels sorting by this column. Here is the [description](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/#react-grid---sorting) of this behaviour.
Maybe, this would suit your needs?

**Comment by kor0p** [comment]
Thanks for quick response. It is very cool, but using some keys to sort is very illogical, isn't it? So I don't like this behavior and wrote own. If you like my kind of multiple columns sorting too, please, provide an example for that, as a useful custom user experience of React Grid.

**Comment by AryamnovEugeniy** [comment]
Thank you for the idea. I believe such a section may be useful for other users as well. We'll discuss its implementation after we finish our Roadmap tasks.
