### ISSUE TITLE
Display the full branch when filtering a node in a tree

### ISSUE THREAD

**Issue by gontard** [DevExpress/devextreme-reactive#2768]
### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I would like to be able to display the parent and the children of a filtered node. 

It is similar to the `fullBranch` filter mode of the `devextreme-react/tree-list` (https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/FilterModes/React/Light/)

**Comment by MaximKudriavtsev** [comment]
Hi @gontard,

Currently, React Grid doesn't have such functionality. However, you can easily implement it yourself. For this, just define your own filter predicate in the [columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/integrated-filtering/#integratedfilteringcolumnextension) property of the `IntegratedFiltering` plugin.

The following [demo](https://codesandbox.io/s/practical-blackburn-0nbee) illustrates how to define a custom filter predicate for the name column.

**Comment by gontard** [comment]
@MaximKudriavtsev thanks for your quick answer. I will try with a custom predicate
