### ISSUE TITLE
Persist Column Reordering

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#277]
Hey guys,

just a suggestion for the Column Reordering plugin. In the DevExtreme HTML5 JS version of the grid it is possible to persist the user's chosen column order and other settings by storing it in something like a Cookie or in LocalStorage.

Any thoughts on getting this into the React version too?

In theory it would just be to save the Column Reorder state in somekind of store (i.e. a Redux store) and pass that to the <ColumnOrderState> plugin, but would like to see it implemented by you guys since you guys rock.

Thanks and keep up the good work!

**Comment by dxbykov** [comment]
Hi,

Thanks for your feedback. It's really important to us. As for your requirement, we've prepared a [sample implementation](https://stackblitz.com/edit/react-fw4ifk?file=index.js). 
 
I'd also like to mention that the principles we follow working on React components are slightly different than those we put into the DevExtreme HTML5 JS version. We want to keep our React components light, fast and their API minimalistic but flexible. We wouldn't like to build in any single feature that is possible to implement. At the same time, we want it to be clearly implementable.
 
As we can see, the case you are describing can be implemented in several lines of code giving more control and understanding about how things work. So, let us know if the suggested solution doesn't meet your needs. Your feedback would be highly appreciated.

**Comment by terndrup** [comment]
Hi Alexander,

that example is perfect, thanks a lot!

Personally with that little amount of code I would consider building it into the devextreme reactive grid but it's completely up to you and I understand that you're not going to be porting everything from the HTML5 components.

Keep up the good work and thanks!
