### ISSUE TITLE
error building - Grid show empty page

### ISSUE THREAD

**Issue by shmuliko** [DevExpress/devextreme-reactive#2773]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

i downgrade yarn to 1.22.0
lint - stop with errors
test - stop with errors
build:watch - if i run build:watch first, is stop with errors
if i run 'build' only first, the 'build:watch' compiled successfully, but react grid project opened with empty page. [write 'Loading...' to few seconds, and clear]
in the console have few warnings and errors, the Charts and Scheduler working with some warnings, (without errors).

the browser console errors:

the console errors:
1. Uncaught TypeError: Cannot read property 'source' of undefined
2. react-dom.development.js:21843 The above error occurred in the <DemoCodeProvider> component:

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

![image](https://user-images.githubusercontent.com/1821946/77422619-731e0e80-6dd6-11ea-987a-42250ebf0cb8.png)

![image](https://user-images.githubusercontent.com/1821946/77422663-8630de80-6dd6-11ea-8b7e-87b301543cdf.png)

![image](https://user-images.githubusercontent.com/1821946/77422745-abbde800-6dd6-11ea-871b-2efce4a97c94.png)

### Environment

- devextreme-reactive: 2.5.1
- react: none
- browser: chrome 80.0.3987.132
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @shmuliko,

Thank you for your report. We know about this issue and the fix will be available in the nearest release.
