### ISSUE TITLE
Customizing CSS for ValueAxis.label

### ISSUE THREAD

**Issue by NouamaneTazi** [DevExpress/devextreme-reactive#2783]
How can I customize the text labels in the axis (color / rotation) ?

**Comment by LazyLahtak** [comment]
Hi @NouamaneTazi,

To customize axis label you should define your own label component (for the [ArgumentAxis](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-axis/#argumentaxislabelprops) and the [ValueAxis](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/value-axis/#valueaxislabelprops)). Here is an [example](https://devexpress.github.io/devextreme-reactive/react/chart/demos/combination/multiple-axes/) on our site (pay attention to the PriceLabel and the LabelWithThousand components).
If you have any further questions, let us know.
