### ISSUE TITLE
Grid page size Select scrolls to top on open

### ISSUE THREAD

**Issue by ferc** [DevExpress/devextreme-reactive#2788]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When I click on the `Select` component in order to change the page size in the Grid, the page scrolls to top (Material-UI implementation)

Seems to be related with the `position: absolute` added in this line: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/paging-panel/page-size-selector.jsx#L31

### Expected Behaviour

The scroll should not be affected when I open the page size `Select`

### Steps to Reproduce

Just click to the page size `Select`, make sure you scrolled down first in order to open the page size select (so you can see the scroll jump)

Link to the example that reproduces the issue: [https://codesandbox.io/s/qw73m](https://codesandbox.io/s/qw73m) / [https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/) (every grid with pagination)

### Screenshots

<img width="503" alt="Screen Shot 2020-03-31 at 5 11 00 PM" src="https://user-images.githubusercontent.com/902031/78070681-9b77b100-7372-11ea-89d9-6f6955e96b45.png">

### Environment

- devextreme-reactive: 2.5.1
- react: 16.8.3
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.5

**Comment by LazyLahtak** [comment]
Hi @ferc,

Thank you for your report. We will fix it soon.
