### ISSUE TITLE
VirtualTable Grid not scrolling in Safari Browser

### ISSUE THREAD

**Issue by ims7inc** [DevExpress/devextreme-reactive#2789]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

   
### Current Behaviour
DataGrid not scrolling in safari browser. But it is scrolling in Safari Browser

### Expected Behaviour
DataGrid should scroll in Safari

### Steps to Reproduce

                 <Grid
                        columns={ columns }
                        key={ plugins.length }
                        rows={ rows }
                        rootComponent={ GridRoot }>
                        <VirtualTable height="100%" />
                    </Grid>

**Comment by ushkal** [comment]
Hi @ims7inc ,

I couldn't reproduce the described problem. Please send us a runnable project or modify this [codesandbox](https://codesandbox.io/s/amazing-banzai-2ylhv) so that the issue is reproduced.

**Comment by ims7inc** [comment]
After removing unwanted wrapers issue got fixed
