### ISSUE TITLE
access line information, line id number and onChanged event

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2793]
Hello,
How can I get the line information and id number I want to edit.
Also how can I access the onChanged event?
Can you help me ?

`

     import React, { Component } from "react";
     import Paper from '@material-ui/core/Paper';
     import { EditingState,SearchState,IntegratedFiltering, GroupingState,  IntegratedGrouping,} from '@devexpress/dx-react-grid';
     import {  ColumnChooser,  Grid,  Table,  TableColumnResizing,  TableColumnVisibility,  TableEditColumn,  TableEditRow,  TableFixedColumns,  TableHeaderRow,  Toolbar,  SearchPanel,  TableGroupRow,  GroupingPanel,  DragDropProvider,} from '@devexpress/dx-react-grid-material-ui';

     class Bounty extends Component {
       constructor(props) {
         super(props);
         this.state = {
           isLoaded: true,
           columns: [
             {name: 'name', title: 'Name'},
             {name: 'city', title: 'city'}
           ],
           rows : [
             { sex: "Female", name: "Sandra", city: "Las Vegas", car: "Audi A4" },
             { sex: "Male", name: "Paul", city: "Paris", car: "Nissan Altima" },
             { sex: "Male", name: "Mark", city: "Paris", car: "Honda Accord" },
             { sex: "Male", name: "Paul", city: "Paris", car: "Nissan Altima" },
             { sex: "Female", name: "Linda", city: "Austin", car: "Toyota Corolla" }
           ]
         };
         this.commitChanges = this.commitChanges.bind(this);
         //this.getRowId = this.getRowId.bind(this);
       }
       }

       commitChanges({ added, changed, deleted }) {
         let { rows } = this.state;
         let changedRows;

         if (added) {
           console.log("added")
         }
         if (changed) {
           changedRows = rows.map(row => (changed[row.id] ? { ...row, ...changed[row.id] } : row));
           console.log("changed");
           console.log(rows.map(row => (changed[row.id])))
          }
         if (deleted) {
           console.log("deleted")
         }
        };
        //getRowId(row) {
        //  console.log(this.state.rows.indexOf(row));
        //  return this.state.rows.indexOf(row);
        //}

       render() {
         const { isLoaded, drList, rows, columns } = this.state;
         if (!isLoaded) {
           return <div>Loading...</div>;
         } else {
           return (
             <div className={"animated fadeIn "}>
            <Row>
               <Paper>
                   <Grid
                    rows={rows}
                    columns={columns}
                    getRowId={this.getRowId}
                  >
                <EditingState
                  onCommitChanges={this.commitChanges}
                />
                <Table
                  /*columnExtensions={tableColumnExtensions}*/
                />
                <TableHeaderRow />
                <TableEditRow />
                <TableEditColumn
                  showAddCommand
                  showEditCommand
                  showDeleteCommand
                />
               </Grid>
              </Paper>
             </Row>
           </div>
         );
         }
       }
     }
     export default Bounty;

`

**Comment by AryamnovEugeniy** [comment]
Hello @turkdoktoru ,

I suggest you use Grid in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode). In this case, you will be managing the Grid's state externally.
To do that, you need to pass certain props to the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/). In order to control row's id use `editingRowIds` and `onEditingRowIdsChange` properties. To control row changes use `rowChanges` and `onRowChangesChange` properties. Here is our [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode), which shows how to use Grid's editing features in `Controlled Mode`.

If you have any other questions, feel free to ask them.

**Comment by turkdoktoru** [comment]
I have tried the examples given before.
But with the code I wrote above, I could not get the line information and id number.
Can you give an example according to the code

**Comment by AryamnovEugeniy** [comment]
I noticed a mistake in your code. You need to provide unique ID for every row if you want to edit them correctly. So, here is a [sandbox example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-oyb3v) where I added IDs to your data and implemented the approach I described in the previous comment.
