### ISSUE TITLE
Bug with ExportGrid when I use DataTypeProvider

### ISSUE THREAD

**Issue by lucas-bustos** [DevExpress/devextreme-reactive#2795]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I have created a column called "Modality" that is an Enum. Each number represents a value; for example "value =1" represents a string that is "Number One". When I convert it to excel and download it, in the column "Modality", I expect to see Number One, but I see only a number (1).

### Expected Behaviour
When I download the excel in the column "Modality", I expect to see the value that converts with the component DataTypeProvider. In this example I convert 1 (Number) in a string "Number One".

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/goofy-nobel-iwyhr&gt; 

### Screenshots
![ScreenShoot](https://user-images.githubusercontent.com/58180079/78373775-68673480-75a1-11ea-82bf-c60810cc71b1.png)

### Environment

- devextreme-reactive: 2.6.0
- react: 16.11
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: YES

**Comment by ushkal** [comment]
Hi @lucas-bustos ,

This behavior is expected: the row values are exported as-is. Please use the [customizeCell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid-exporter/#properties) function to change an exported value. 
Here's an updated [codesandbox](https://codesandbox.io/s/sleepy-rubin-2oc4p).
