### ISSUE TITLE
adjust column width

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2796]
Hello,
There is an editable table. I want to adjust the width of the columns. I have read the document but it gives an error like below. Could you help ?

[https://ibb.co/qntBX4D](url)

`

       constructor(props) {
       this.state = {
              columns: [
             { name: "name", title: "Name", width: 5},
             { name: "surname", title: "Surname", width:5 },
             { name: "birthDay", title: "birthDay", width: 5},
           ],
           defaultColumnWidths: [
             { name: "name", width:10 },
             { name: "surname", width: 6},
             { name: "birthDay", width:3 }
           ]
         };
         }

     render() {
        return (
             <Paper>
                <Grid
                  rows={this.state.examinationItems}
                  columns={this.state.columns}
                >
                  <EditingState
                    onCommitChanges={this.commitChanges}
                  />
                  <Table />
                  <TableColumnResizing
                    defaultColumnWidths={this.state.defaultColumnWidths}
                    resizingMode={"nextColumn"}
                  />
                  <TableHeaderRow />
                  <TableEditRow />
                  <TableEditColumn
                    showAddCommand
                    showEditCommand
                    showDeleteCommand
                    commandComponent={Command}
                  />
                </Grid>
              </Paper>
        )
     }
`

**Comment by LazyLahtak** [comment]
Hi @turkdoktoru,

I've noticed an error in the code you provided.
According to our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#tablecolumnwidthinfo), you are required to define the TableColumnResizing `defaultColumnWidths` property with an array of the following objects:

```js
{
  columnName: ...,
  width: ...,
}
```

Follow this [example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#uncontrolled-mode) on our site.

If you have any further questions, let us know.

**Comment by turkdoktoru** [comment]
I solved the problem. but it shows two columns, what could be the reason?

[https://imgur.com/crnYyLU](url)
