### ISSUE TITLE
Lazy Loading, api with paging feature 

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2798]
https://codesandbox.io/s/pee1s

Hello,

here are the features to take and skip in your example. But in my api special, it works as "how many data do you want on each page". My api has pageSize and pageIndex features. Your api takes the requestedSkip and take features. You have set up the building accordingly. There is no example of how I should install this structure in the api specific below.

axios.post ("apiUrl", { pageSize: take, pageındex })

**Comment by LazyLahtak** [comment]
Hi @ahmetcaglayan,

I've created an [example](https://codesandbox.io/s/wonderful-sunset-ntc9z) based on your description.
Let us know if it meets your requirements.

**Comment by ahmetcaglayan** [comment]
My sample api
https://jsonplaceholder.typicode.com/posts?_page=2&_limit=5

My api, the limit should always be fixed. the limit should not change.

Does not work correctly as follows
https://codesandbox.io/s/pensive-wright-kw0lh


It doesn't work properly with the pageSize you provided. Because it attracts 2 times data at first. When he gets somewhere in between, he again makes twice the request. The "take" variable does not work according to the number I have fixed.

**Comment by ahmetcaglayan** [comment]
5000 rows api
https://jsonplaceholder.typicode.com/photos?_page=2&_limit=5

**Comment by LazyLahtak** [comment]
Thank you for your clarification.
I can't provide you a working example for your API now.
I suggest you use [Remote Paging](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/paging/#remote-paging). It seems more comparable with your API.
Is this solution acceptable?

**Comment by ahmetcaglayan** [comment]
Thanks for be interested.
Our designers insist on the "lazy loading" structure. Normally api is more suitable for "pagination" structure.
I would be glad if you can set an example for this. Everyone's api structure is not the way you want. Generally, people use this structure.

**Comment by LazyLahtak** [comment]
Thank you for the clarification. 

Our virtual loading mechanism takes some additional amount of data in a single request to make scrolling smooth. This means that Grid loads multiple pages within a single request if necessary.

Originally the current API was designed based on the SQL standards where "skip" is equivalent to "OFFSET" and "take" is equivalent to "LIMIT"." This technique allows taking multiple pages, and our current logic doesn't cause any issues in a common case. 
 
At the same time your service requires the grid to always pass the current page number which makes it impossible to pre-load multiple pages. Reactive Grid doesn't provide an option to split this data loading logic into multiple fixed requests. This a complex task that requires time and resources. We'll consider it in the future but cannot give you any estimate at present.
 
The only option is to use Remote paging with pager at the moment.
