### ISSUE TITLE
Virtual Table Height

### ISSUE THREAD

**Issue by ddmedeiros** [DevExpress/devextreme-reactive#280]
Is there a way to set the height for the container div of virtual table component via its props, instead of its fixed 530px height ?

**Comment by kvet** [comment]
Hi,
 
Currently, there is no way to set virtual table height. We will notify you once the possibility is added.

**Comment by DanHarman** [comment]
This is an urgent one for me too. I'm using AutoSizer from https://bvaughn.github.io/react-virtualized/#/components/AutoSizer to support having an adjustable splitter so need to be able to set the height.

**Comment by DanHarman** [comment]
I've hacked this in for the time being. Partial code sample:
```
import { AutoSizer } from 'react-virtualized';

function debounce(func: (..._: any[]) => void, timeout: number) {
    let timeoutHandle: number | null;
    return (...args: any[]) => {
        const deferred = () => {
            timeoutHandle = null;
            func(args);
        };

        clearTimeout(timeoutHandle!);
        timeoutHandle = setTimeout(deferred, timeout);
    };
}

class MyGrid extends React.Component<ConnectedProps, {}> {     
    private hackDxGridHeight = debounce((height: number) => {
        window.requestAnimationFrame(() => {
            const node = ReactDOM.findDOMNode(this) as HTMLElement;
            if (node !== undefined) {
                ReactDOM.findDOMNode(this).getElementsByClassName('panel')[0].children[0].setAttribute('style', `height: ${height}px;`);
            }
        });
    }, 1000);

    public render() {
        return (
            <div style={{ position: 'relative', height: '100%', width: '100%', background: '#0F0' }}>
                <AutoSizer>
                    {({ height }) => {
                        this.hackDxGridHeight(height);
                        return <div style={{ position: 'absolute', width: '100%', height: `${height}px` }}>
                            <Grid getRowId={getRowId}
                                rows={this.props.trades}
                                height={height}
                                columns={[...]}>
                                <SortingState />
                                <LocalSorting />
                                <VirtualTableView />

                                <TableColumnResizing defaultColumnWidths={this.defaultColumnWidths} />

                                <TableHeaderRow allowResizing allowSorting />
                            </Grid>
                        </div>;
                    }}
                </AutoSizer>
            </div>
        );
    }
}
```

**Comment by DanHarman** [comment]
Just a heads up for anyone doing this hack, you may not see cells if you enlarge past the size of the 'overscan' buffer of the table. Scrolling fixes it, but not looked into how to actually force it to redraw. this.forceUpdate() doesn't seem to do it though.

**Comment by DanHarman** [comment]
@kvet Is there a way to force the virtual table view to recalculate the number of visible rows as with my hack if I make the table too big, it exceeds the current number of rendered rows and doesn't update until I scroll a fraction.

**Comment by kvet** [comment]
@DanHarman, I can recommend changing the `scrollTop` property of the DOM Node that was obtained in the `hackDxGridHeight` method. So, try to increase the `scrollTop` value by 1 pixel. This will trigger Virtual Table rendering.

**Comment by leandro-silva-me** [comment]
What about Table width? Not implemented same as height?

**Comment by DanHarman** [comment]
@leandro-silva-me width is 100% so already fills the available space. Only height is fixed.

**Comment by elertan** [comment]
Not sure if this is 'fixed'. But you can set the table's height by using the `containerComponent` prop on the `VirtualTable` component. You basically pass down the props onto a `<div>` element and set the style of that div element to your desired height.

**Comment by DanHarman** [comment]
Yes it was fixed a while back.  No need to hack it anymore.
