### ISSUE TITLE
lookup field and data in editingTable

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2804]
Hello,

I am using EditingTable. How can I use lookup field in a table?
https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/

**Comment by ushkal** [comment]
Hi @turkdoktoru ,

Please refer to the following demo: [React Grid Data Editing](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/).
