### ISSUE TITLE
Exception is thrown on removing a column when column bands is used and the last column is aligned to the right

### ISSUE THREAD

**Issue by karczk** [DevExpress/devextreme-reactive#2806]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Grid crash - unhandled error
```
Uncaught TypeError: Cannot read property '0' of undefined
    at getBandComponent
```

### Expected Behaviour

Column should be removed without any error.

### Steps to Reproduce

Click on the button:
https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-x6jrx

This is the minimal setup, I've set the width to force some columns to be invisible (children of the group). Also fixed column on the right side is required to reproduce it.

### Screenshots

![image](https://user-images.githubusercontent.com/8329336/78881133-ab6c5080-7a56-11ea-8575-ba09e00a5def.png)

### Environment

- devextreme-reactive: 2.4.0 / 2.6.0
- react: 16.x
- browser: Chrome / Firefox
- bootstrap: 4.x
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi @karczk ,

Thank you for reporting this issue. I've reproduced it and we'll fix it soon.

**Comment by mwoody1** [comment]
@ushkal Not sure if it will be of any use, but I've come accross a scenario where this occurs without aligning any columns. Using [this sandbox](https://codesandbox.io/s/zen-shannon-21e9w), if any banded column is hidden first it will product the same error.

**Comment by MaximKudriavtsev** [comment]
Hi @mwoody1,

Thank you for your participation! It will help us to fix the problem.
