### ISSUE TITLE
add drop-down menu in editable table

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2809]
There is an editable table with devextreme-reactive. In this table, I want to add more than one button with the "ActionColumns" feature and change the functions of the buttons. How can I do that ?

I want it to be like the picture below. I am giving reference link.

I put the application that runs into the codesandbox, I just want the buttons to be added as in the picture. Can you show it on codesandbox?

**codesandbox**
[https://codesandbox.io/s/tender-pine-b2coc?file=/src/CustomerList.js](url)

**my topic**
[https://stackoverflow.com/questions/61118599/add-drop-down-menu-in-editable-table](url)

**How can I add a drop down menu as in the picture?
But the existing edit and delete buttons will remain the same**
[https://i.stack.imgur.com/g7AAX.png](url)

reference
[https://stackoverflow.com/questions/50845136/how-to-add-a-button-inside-a-cell-in-the-devextreme-react-grid](url)

**Comment by LazyLahtak** [comment]
Hi @turkdoktoru.

Please refer to the following topic: #1178

**Comment by turkdoktoru** [comment]
the referenced source code will not work for me. How can I do like the picture I shared?

**Comment by AryamnovEugeniy** [comment]
Hello @turkdoktoru ,

Could you please clarify what you want to achieve? The approach described above would render buttons in a separate column. Each row would contain a button as in your screenshot.

By the way, I updated your [example](https://codesandbox.io/s/focused-goldwasser-icpms) where I used a different approach. You may override `Table`'s [cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) component and render your button there as I've done. Another way is to use `DataTypeProvider`, see our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/).

**Comment by turkdoktoru** [comment]
I want to do as in the picture.
There will be "Edit-Delete" under the Dropdown Menu.
Next to Dropdown, there will be an "Open" button.

[https://ibb.co/hyHjCDw](url)

**Comment by LazyLahtak** [comment]
Hi @turkdoktoru,

To achieve this, I suggest you customize the TableEditColumn [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncellprops).
Here is an [example](https://codesandbox.io/s/crazy-payne-8be25).

**Comment by turkdoktoru** [comment]
very thanks, superrrr

**Comment by LazyLahtak** [comment]
You are welcome!
