### ISSUE TITLE
dx-react-grid-material-ui is not compatible with the latest version of material-ui 

### ISSUE THREAD

**Issue by zipengwu** [DevExpress/devextreme-reactive#281]
the latest version of material-ui has removed createStyleSheet() method.

**Comment by ErichBSchulz** [comment]
confirmed :-(

**Comment by SergeyAlexeev** [comment]
Hi, 
Thank you for reporting the issue, but we have been already noticed about it. This [PR](https://github.com/DevExpress/devextreme-reactive/pull/275) fixes the problem.

**Comment by oallouch** [comment]
I saw that and I'm waiting for a release.
I just want to include this lib in all my material-ui projects !
Btw, it's in their doc that I found a link to this project.

**Comment by gfpacheco** [comment]
Would you release a new version with the mentioned changes please?
