### ISSUE TITLE
Direction Selection For Column Sorting

### ISSUE THREAD

**Issue by esinoner** [DevExpress/devextreme-reactive#2810]
I'm using
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

To sort right now, you just click on the column header, and it picks the direction. You reverse by clicking again. It would be more user friendly if you let user to make direction selection. We are using sort feature on remote mode and if user doesnt want to use default direction, he has to go backend two times. If there would be up down arrow buttons near column headers, it will be very nice.

**Comment by LazyLahtak** [comment]
Hi @esinoner,

You can customize the TableHeaderRow [SortLabel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowsortlabelprops) component. Here is an [example](https://codesandbox.io/s/brave-worker-up8zj?file=/demo.js).
If you have any further questions, let us know.
