### ISSUE TITLE
Multi-level group summaries are incorrect when showInGroupFooter is false

### ISSUE THREAD

**Issue by patrick-moore** [DevExpress/devextreme-reactive#2811]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Group summaries are incorrect when displayed in the group row with multiple levels of grouping. They are correct when the parent group is collapsed, but if the parent group is expanded while some of the child groups are collapsed it looks like rows are being double counted.

### Expected Behaviour

Summaries should not change based on whether groups are expanded/collapsed

### Steps to Reproduce

1. Create a grid with multiple levels of grouping
1. Add summary state with displayInGroupFooter to false
1. Expand a parent group, but keep 1 or more of the child groups collapsed 

Link to the example that reproduces the issue: [Code Sandbox](https://codesandbox.io/s/blue-pond-jhrzf)
Expand/collapse the product grouping within North America

### Screenshots

Correct when parent groups are collapsed:
<img width="985" alt="Screen Shot 2020-04-11 at 4 13 08 PM" src="https://user-images.githubusercontent.com/26011834/79055239-12ce0000-7c11-11ea-8fe5-ce79c9b259a6.png">

Incorrect when parent group is expanded, but child groups  are collapsed:

<img width="982" alt="Screen Shot 2020-04-11 at 4 13 18 PM" src="https://user-images.githubusercontent.com/26011834/79055246-20838580-7c11-11ea-9778-4753a0819a12.png">

<img width="977" alt="Screen Shot 2020-04-11 at 4 13 24 PM" src="https://user-images.githubusercontent.com/26011834/79055248-237e7600-7c11-11ea-8966-c57bb596c9d7.png">

### Environment

- devextreme-reactive: 2.6.1
- react: ^16.3.1
- browser: Chrome
- bootstrap: none
- react-bootstrap: 0.33.1
- material-ui: none

**Comment by ushkal** [comment]
Hi @patrick-moore ,

Thank you for reporting this issue. We'll fix it soon.
