### ISSUE TITLE
show changes on customized appointment

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2812]
Hello,
I use a customized appointment. I transfer a data I selected with the table onto the textBox. But it doesn't show the changes instantly on the form. It shows when signing out on the form. I want to show the instant changes on the form. How can I fix this problem?

I transfer a line information that I selected on the table as state.selectedRowInfo.
However, the transferred change is not instantly displayed on the form.

as it appears in the picture. shows only when exiting

https://imgur.com/a43347v
https://imgur.com/gQxIkPe
`

       BasicLayout = ({ onFieldChange, appointmentData, ...restProps }) => {
         const onCustomFieldChange = (nextValue) => {
             onFieldChange({ customerName: nextValue });
         };
         return (
           <AppointmentForm.BasicLayout
           appointmentData={appointmentData}
           onFieldChange={onFieldChange}
           {...restProps}
        >
        <AppointmentForm.Label
          text="Customer Name"
          type="title"
        />
        <AppointmentForm.TextEditor
          value={ this.state.selectedRowInfo.customerName }
          onValueChange={onCustomFieldChange}
          defaultValue={ this.state.selectedRowInfo.customerName }
          placeholder="Customer name"
        />

        <Card>
          <CardBody>
            <Paper>
              <Grid
                rows={this.state.customerItems}
                columns={this.state.columns}
              >

                <Table
                  rowComponent={this.TableRow}
                />

                <TableHeaderRow />
                 </Grid>
               </Paper>
              </CardBody>
            </Card>
          </AppointmentForm.BasicLayout>
        );
       };

`

`

       TableRow = ({ row, ...restProps }) => (
         <Table.Row
         {...restProps}
            onClick={() => {
                             this.setState({ selectedRowInfo: row})
                          }}
         /> 
       );
`

**Comment by AryamnovEugeniy** [comment]
Hello,

It works for me: https://codesandbox.io/s/quiet-worker-lissx?file=/demo.js.
But I would not advise you to define your components inside render method. It may significantly reduce performance of your application. See our [article](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/) on how to improve performance.
One more point. Consider using `Selection` plugins to implement row selection in your Grid. Here is an [example](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/selection/#select-on-a-row-click).
