### ISSUE TITLE
I am using dev express react grid version 2.1.2. The table renders without any issue in my local instance but when i deploy it to the server, it squishes and disappears. Any idea will be greatly helpful.

### ISSUE THREAD

**Issue by anushaNemilidinne** [DevExpress/devextreme-reactive#2819]
"@devexpress/dx-react-core": "^2.1.2",
 "@devexpress/dx-react-grid": "^2.1.2",
 "@devexpress/dx-react-grid-material-ui": "^2.1.2",

Here is what it is rendering:

![image](https://user-images.githubusercontent.com/35274794/79138396-103aea00-7d7a-11ea-85f1-e99c744570ce.png)

Here is how it should be:

![image](https://user-images.githubusercontent.com/35274794/79138520-437d7900-7d7a-11ea-8ff6-a8df6ab2ec29.png)

I observed the style sheets and found that the height is constantly reduced till it reaches 0 px. 

Note: This is not happening in my local instance but only when I deploy it to the server.

**Comment by LazyLahtak** [comment]
Hi @anushaNemilidinne,

I couldn't reproduce this issue. Would you provide your code or a runnable project (using [CodeSandbox](https://codesandbox.io/s/kdlc6), for example)? It will help us to find a solution.
