### ISSUE TITLE
Custom cell templating "Element type is invalid" error

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#282]
Hey guys, 

I tried to implement your templating demo/example found in https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-demos/src/bootstrap3/featured-uncontrolled-mode/demo.jsx

You have a template for a progressbarcell and a highlighted cell which I tried to copy and adapt to my needs. I started with a very simple template to try it out which is basically the same as your highlighted cell:

```js
import React from 'react';
import PropTypes from 'prop-types';

const getStatus = (value) => {
  switch (value) {
    case -1:
      return 'OFF';
    case 0:
      return 'OFF';
    case 1:
      return 'GOOD';
    case 2:
      return 'BAD';
    default:
      return 'N/A';
  }
};

export const VarStatusCell = ({ align, value, style }) => (
  <td
    style={{
      textAlign: align,
      ...style,
    }}
  >
    ${getStatus(value)}
  </td>
);
VarStatusCell.propTypes = {
  align: PropTypes.string.isRequired,
  value: PropTypes.number.isRequired,
  style: PropTypes.object,
};
VarStatusCell.defaultProps = {
  style: {},
  align: 'left',
};
```
and in my table component I have the following tableview configuration:

```js
                  <DragDropContext />
                  <TableView
                    tableCellTemplate={({ row, column, style }) => {
                      if (column.name === 'status') {
                        return (
                          <VarStatusCell value={row.status} style={style} />
                        );
                      }
                      return null;
                    }}
                    allowColumnReordering
                  />
                  <TableHeaderRow allowDragging />
```
Pretty much copied one to one from your example, but this breaks my code with the following error

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `TemplateConnector`.
    at invariant (invariant.js:44)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:74)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:367)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
```

I thought maybe it had to do with the "return undefined" for columns that don't have a template but changing that to null or removing it hasn't fixed the error.

Any ideas what this could be? Has the templating syntax changed since the demo was made?

**Comment by kvet** [comment]
Hi,
 
The template syntax hasn't been changed since the demo was made. It is required to return `undefined` from the template that partially overrides the original one.

I assume that you don't import VarStatusCell into the file with Grid and this causes the issue.
 
Additional info: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/README.md#reference
 
Feel free to provide us an example demonstrating the issue based on this WebpackBin: https://www.webpackbin.com/bins/-KoCcFwPPtps5fEN0PkI

**Comment by terndrup** [comment]
Hey,

the VarStatusCell was imported properly, I recreated the issue in this webpackbin you linked:

https://www.webpackbin.com/bins/-KoCcFwPPtps5fEN0PkI

Same error is returned in log:

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `TemplateConnector`.
```

**Comment by terndrup** [comment]
UPDATE: Fixed the issue by changing the import statement to 

```
import { VarStatusCell } from './statustemplate.js';

```

instead of 

```
import VarStatusCell from './statustemplate.js';
```
I don't know what the difference is but it fixed it... does the { } around mean its importing as a react component or something?

**Comment by kvet** [comment]
Read more about ES Modules here: http://2ality.com/2014/09/es6-modules-final.html
