### ISSUE TITLE
get monthly start and end dates

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2820]
Hello,

How can we get the month start and end dates based on the selected month information?
start and end dates if weekly view is selected
start and end dates if monthly view is selected

in https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/view-switching/#controlled-mo

**Comment by AryamnovEugeniy** [comment]
Hello,

You may [create your own plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/providing-values/) and use the following [Getters](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/): `startViewDate` and `endViewDate`. Here is an [example](https://codesandbox.io/s/determined-mcnulty-m6j64?file=/demo.js) I made. I created `IntegratedDates` plugin where I extended the `Getters` mentioned above.
Note that plugin order is important. Your plugin should be after the `ViewState`, `MonthView`, `WeekView` and `DayView` plugins.

**Comment by turkdoktoru** [comment]
the sample is very nice. I added to my project.
But
`

   pluginDependencies = [
    { name: "DayView", optional: true },
    { name: "MonthView", optional: true },
    { name: "WeekView", optional: true },
    { name: "ViewState", optional: true }
  ];
  startViewDateComputed = ({ startViewDate }) => {
  return startViewDate;
};
  startViewDateComputed() {
     return function() {
     console.log(this.props);
  }
 };
 endViewDateComputed = ({ endViewDate }) => {
    return endViewDate;
 };

   render() {

   console.log("**I want to access the start and end date here**")

    const IntegratedDates = () => {
      return (
    <Plugin dependencies={this.pluginDependencies} name="IntegratedDates">
      <Getter name="startViewDate" computed={this.startViewDateComputed} />
      <Getter name="endViewDate" computed={this.endViewDateComputed} />
    </Plugin>
  );
  };
`

How can I use it in?

**Comment by AryamnovEugeniy** [comment]
There are some options available. For example, you may save the dates as instance fields of your class. Another option is to use React's [useEffect](https://reactjs.org/docs/hooks-effect.html). There may be others. If the approaches I outlined do not help you, please, clarify your scenario so that we would be able to assist you.
