### ISSUE TITLE
clearRowsCacheAction is not a function

### ISSUE THREAD

**Issue by plevamatus** [DevExpress/devextreme-reactive#2821]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Rows caching example from your demos, doesn't work properly. When you type something in filter row, error message "clearRowsCacheAction is not a function" appears.

### Steps to Reproduce

- open Rows caching example in CodeSample https://codesandbox.io/s/9vk2r
- type something in filter row

### Screenshots

![image](https://user-images.githubusercontent.com/11454499/79198275-864f5780-7e33-11ea-8b0f-19c1caeacf5c.png)

### Environment

- devextreme-reactive: 2.6.1
- react: 16.13.1
- browser: chrome 80.0.3987.163
- material-ui: 4.9.7

**Comment by ushkal** [comment]
Hi @plevamatus ,

Thank you for reporting this problem. We will fix this soon.
