### ISSUE TITLE
Bug appears when applying data to bar charts 

### ISSUE THREAD

**Issue by MyNameIsHung** [DevExpress/devextreme-reactive#2823]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x ] React Chart
- [ ] React Scheduler

### Current Behaviour

I obtained an array containing some data from some wb API and found out that the bar chart would not display the information given correctly.
When I deleted the ArgumentAxis and the ValueAxis it worked.

### Expected Behaviour

The bar chart was supposed to display information correctly

### Steps to Reproduce

I dont know
Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

![image](https://user-images.githubusercontent.com/46376260/79298063-30011800-7f0a-11ea-8a05-ef3c9b8f9eaf.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

**Comment by LazyLahtak** [comment]
Hi @MyNameIsHung,

Thank you for notifying us of this issue. We will fix it soon.
As a workaround, I suggest you define initial data with zero values. Here is an [example](https://codesandbox.io/s/beautiful-perlman-pni65?file=/demo.js).
