### ISSUE TITLE
Disable the paging counter in Paging Panel

### ISSUE THREAD

**Issue by varunrayen** [DevExpress/devextreme-reactive#2827]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am trying to disable the page counter in the paging panel and show only the next and previous buttons. How can i achieve this?

<img width="274" alt="image" src="https://user-images.githubusercontent.com/589444/79419108-c9483100-7fd3-11ea-8ab0-c98199f70438.png">

### Environment

- devexpress/dx-react-core: 2.6.1
- devexpress/dx-react-grid: 2.6.1
- react: 16.8.6

**Comment by ushkal** [comment]
Hi @varunrayen ,

I suggest you override the `containerComponent` property of the [PagingPanel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/paging-panel/) plugin. I've created an [example](https://codesandbox.io/s/elegant-moser-dcb8e) for you.
