### ISSUE TITLE
Customize ColumnChooser Item checkbox color

### ISSUE THREAD

**Issue by xde013** [DevExpress/devextreme-reactive#2829]
### I'm using ...

- [x] React Grid
- [x] Material UI

### Description
I would like to override the default checkbox color of the column chooser which is set by default with secondary material ui color.

The following doesn't seem to override the secondary color of the checkbox 😞 
![image](https://user-images.githubusercontent.com/21088699/79446544-a53e1d00-7fde-11ea-8124-5faa358aeb8a.png)

I'm using ColumnItem as the itemComponent for the ColumnChooser
```js
 <ColumnChooser itemComponent={ColumnItem} />
```
Any help is appreciated 🙏 

### Environment
- devextreme-reactive: 2.6.1
- react: 16.13.1
- material-ui: 4.9.10

**Comment by ushkal** [comment]
Hi @xde013,

I suggest you pass a function to `makeStyles` and set a checkbox color depending on whether the column is visible. I've created a [codesandbox](https://codesandbox.io/s/crazy-hopper-kfgun) for you.

**Comment by ushkal** [comment]
@xde013 ,

Here's an updated [codesandbox](https://codesandbox.io/s/cranky-elbakyan-xspqz?file=/column-chooser-item.jsx). I apologize for the late response.
