### ISSUE TITLE
How to preload the row data for each input field ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [DevExpress/devextreme-reactive#283]
Hello, folks,
I've trying to preload the data for every field in the row while selecting a item Code / Id, for instance, with such data given to `row` props : 

```javascript
[
    {
        "id": "0001",
        "firstName": "Foo",
        "lastName": "Bar",
        ...
    },
    {
        "id": "0002",
        "firstName": "Hello",
        "lastName": "World",
        ...
    }
]
```
the fields `firstName` , `lastName` should be automatically preloaded to "Foo" and "Bar" while we select `id` = "0001".

Appreciate your helps :)

**Comment by kvet** [comment]
Hi,
 
I could not understand your scenario completely. Can you describe it in greater detail?
 
If you want to react to the selection change event, use the onSelectionChange event of the SelectionState plugin. See the reference documentation for additional info: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/

**Comment by be-next-hotdog** [comment]
On considering your `controlled mode`, what I meant was, when we add a new row or edit a row on the table, all the other preload value will be updated automatically according to the selected 'id' : 

```
_______________________________________
|     id     |    Firstname   |  Lastname  |
|  0001   |    Foo             |  Bar             |
```
after I click the edit button and select id => 0002, the preload value of each field should update as below :
``` 
_______________________________________
|     id     |    Firstname   |  Lastname  |
|  0002  |    Hello           |  World         |
```

**Comment by kvet** [comment]
Here is an example demonstrating the ability to change dependent columns when editing a newly added row: https://stackblitz.com/edit/react-krde5t?file=index.js
 
1. Click the 'New' button. A row will be preloaded by the default values.
2. Change the id field of the newly added row to '002'. The type field will be updated according to the entered id.

**Comment by be-next-hotdog** [comment]
Thank a lot for your example, BTW, could we still make editable the dependent data after the preload ? :)

**Comment by kvet** [comment]
Yes, it is possible. The example above allows changing a value in the 'type' column after an id is entered.

It is also possible to implement a much more complicated custom logic. You can also track changes in an added row data by comparing it with the previous one stored in a component state.

**Comment by be-next-hotdog** [comment]
Great, I've been trying to look for the onChange event in EditingState but nothing found. Always considering to your example, if I wanna make the preload dependent value as a default value / or an editable value in input field. What should I do then to make the input onChange event work ? Maybe you meant the `onEditingRowsChange ` props or the `onChangedRowsChange ` props ? 

Could you modify your online example to show the usecase possible ?

**Comment by kvet** [comment]
I've missed this scenario in my example. Please see the updated one: https://stackblitz.com/edit/react-krde5t?file=index.js

If you need to apply the same logic while editing an existing row use `changedRows` and `onChangedRowsChange` props of the EditingState plugin.

**Comment by be-next-hotdog** [comment]
Yepp, top !
