### ISSUE TITLE
GridExporter not showing grid to export data.Help

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2830]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate. I have followed the steps in this demo below  https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/ , but my grid exporter is not showing. I don't see anything related to it on my page. Can you verify this works??

### I'm using ...

- [ ] React Grid

### Current Behaviour
Grid with information is not showing the export feature

### Expected Behaviour
A grid with an export feature is supposed to show.

### Steps to Reproduce
Use the code below

    `import React, { useState,useRef, useCallback } from "react";
      import { withRouter } from "react-router-dom";
      import {
     Template,
     TemplatePlaceholder,
     TemplateConnector
       } from "@devexpress/dx-react-core";
     import { PagingState,SearchState,SelectionState,IntegratedPaging,
     IntegratedSelection,
     IntegratedFiltering
     } from "@devexpress/dx-react-grid";
     import {
    Grid,
    Table,
    TableHeaderRow,
    Toolbar,
    SearchPanel,
    PagingPanel,
    ExportPanel
     } from "@devexpress/dx-react-grid-bootstrap4";
      import { GridExporter } from '@devexpress/dx-react-grid-export';
     import saveAs from 'file-saver';
      import "@devexpress/dx-react-grid-bootstrap4/dist/dx-react-grid-bootstrap4.css";

      const onSave = (workbook) => {
      workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'DataGrid.xlsx');
      });
     };
      const GridUtils = props => {
      const { rows, columns } = props;
       const [pageSizes] = React.useState([50, 100, 500, 0]);
       const exporterRef = useRef(null);
      const startExport = useCallback(() => {
       exporterRef.current.exportGrid();
        }, [exporterRef]);
  
      const [selection, setSelection] = React.useState([]);
 
      return (
        <div className="">
      <Grid rows={rows || []} columns={columns || []}>
        <PagingState />
        <SearchState defaultValue="" />
        <SelectionState
          selection={selection}
          onSelectionChange={setSelection}
        />

        <IntegratedPaging />
        <IntegratedSelection />
        <IntegratedFiltering />
        <PagingPanel pageSizes={pageSizes} />
        <Table
          cellComponent={props.cellComponent} //getting props here didn't work
          tableComponent={props.tableComponent}
          rowComponent={props.rowComponent}
        />
        <TableHeaderRow />
        <Toolbar />
        <ExportPanel startExport={startExport} />
        <SearchPanel />
        <Template name="toolbarContent">
          <TemplateConnector>
            {({ totalCount }) => (
              <React.Fragment>
                <div>Total Count: {totalCount} Records</div>
                <TemplatePlaceholder />
              </React.Fragment>
            )}
          </TemplateConnector>
        </Template>
      </Grid>
      <GridExporter
        ref={exporterRef}
        rows={rows}
        columns={columns}
        selection={selection}
        onSave={onSave}
      />
        </div>
       );
      };

      export default withRouter(GridUtils);`

### Screenshots

![image](https://user-images.githubusercontent.com/32960420/79451664-699f5500-7fd6-11ea-93f7-79d7c9180e3c.png)

### Environment

- devextreme-reactive: "^2.6.2",
- react: xxx"^16.12.0",
- browser: chrome
- bootstrap: "^4.4.1",
- react-bootstrap: "^1.0.0-beta.16",

**Comment by lutakyn** [comment]
hello guys, I carefully started to trace the export button on my ui and I realised the color i blending with my backgroung so its white. How can customize the button to green or another color. The export functionality is working

**Comment by ushkal** [comment]
Hi @lutakyn,

>How can customize the button to green or another color. 

You need to override the `ExportPanel`'s [toggleButtonComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/export-panel/#exportpaneltogglebuttonprops) and pass your styles there. Here's an [example](https://codesandbox.io/s/awesome-bhabha-oche9?file=/demo.js).

**Comment by lutakyn** [comment]
Thank you.

**Comment by ushkal** [comment]
You are welcome!
