### ISSUE TITLE
Custom batch edit buttons on top of TableEditColumn

### ISSUE THREAD

**Issue by annarkh** [DevExpress/devextreme-reactive#2831]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I use TableEditColumn and I want to add functionality of batch editing (#1841 might be related to this). I want to be able to add buttons on to of the TableEditColumn, which can be customized (like the "NEW" button in the header row). I've attached two visual designs for it -- both for filtered and non-filtered tables.
![image_2020-04-16_21-23-39](https://user-images.githubusercontent.com/50014204/79492688-ff63d000-8028-11ea-960f-0fe197b41af3.png)
![image_2020-04-16_21-22-21](https://user-images.githubusercontent.com/50014204/79492694-0094fd00-8029-11ea-821d-255500132331.png)

**Comment by LazyLahtak** [comment]
Hi @annarkh,

I suggest you create a custom plugin - see [this](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) guide. You can place your button into a specific Table cell using [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/). Also, you can add your own row using [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) if TableFilterRow plugin doesn't exist.
Here is an [example](https://codesandbox.io/s/white-glade-qws4o).
Let us know if this solution meets your requirements.

**Comment by annarkh** [comment]
Hello @LazyLahtak,

Thank you for your work upon this request. I was struggling to resolve this issue for a couple of days. Your solution is just awesome, and I can finally achieve the results I wanted, because of your brilliant example, as well as the reference to the docs.

The approach you've mentioned works like a charm. It's a pity that I couldn't realize that the custom plugin is the only way to do this even though I've spent a lot of time going through the docs. 

Thank you personally for this one! Have a wonderful day.
