### ISSUE TITLE
How can i add inline edit custom templates

### ISSUE THREAD

**Issue by totalard** [DevExpress/devextreme-reactive#2833]
I would like to implement custom inputs in inline edit, like select, auto complete etc.. in demo,, i seen only text input.. how is that possible, please give me just link.. i searched so far

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

We have already had a similar issue. [Here](https://github.com/DevExpress/devextreme-reactive/issues/2433) it is.
