### ISSUE TITLE
Grid - There is no simple way to handle row click

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-reactive#284]
Provide an API for handling row click.

**Comment by kenzo23312** [comment]
I have same question/request as @NickMitrokhin

**Comment by SergeyAlexeev** [comment]
We've added the described functionality in the [1.0.0-alpha.10](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1.0.0-alpha.10) update. 
 
Now, the `TableView` plugin contains the `tableRowTemplate` property that allows handling the `onClick` event.
 
The following code demonstrates how to do this:

```js
<Grid
  rows={rows}
  columns={columns}
>
  <TableView
    tableRowTemplate={({ children, row }) => (
      <tr
        onClick={(e) => {
          // ...   
        }}
      >
        {children}
      </tr>
    )}
  />
</Grid>
```

**Comment by dapozdnyakov** [comment]
@SergeyAlexeev this approach doesn't work when using TableSelection with selectByRowClick and/or highlightSelected props.

**Comment by SergeyAlexeev** [comment]
Indeed, and this is stated in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/).
If you are using the `selectByRowClick` or `highlightSelected` properties, table rows will have a custom appearance (the gray background for selected rows) and the click event will be handled for them. In case you apply a custom row template, it will remove the selected row color and disable the click event handling.

**Comment by dapozdnyakov** [comment]
@SergeyAlexeev So what's the right way to handle onDoubleClick in this situation?

**Comment by SergeyAlexeev** [comment]
I've created a separate [issue](https://github.com/DevExpress/devextreme-reactive/issues/437) that describes how to implement your scenario.
