### ISSUE TITLE
clamp is not a function error when reporting

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2840]
Hello there,

I'm reporting. The following data comes with json.
I use the following codes when reporting. But it fails. Can you help with this ?
I read the documents but I get an error about "argumentField"

I'm adding the error image.
[https://ibb.co/LkRjQKN](url)

`

        render () {
        const { data: chartData} = this.state;
           return(
              <Paper>
                      <Chart
                        data={chartData}
                      >
                          <ArgumentAxis />
                          <ValueAxis />

                          <BarSeries
                            name="Total debts"
                            valueField="totalDebt"
                            argumentField="totalDebt"
                            color="#ffd700"
                          />

                          <Animation />
                          <Legend position="bottom" rootComponent={this.Root}  />
                          <Title text="Olimpic Medals in 2008" />
                          <Stack />
                      </Chart>
                  </Paper>
             )
      }

`

**Json result (from API)**

     {
          constantSpendingAmount: "650"
          constantSpendingTotal: "1200"
          receivedAmount: "53.00"
          spendingAmount: "100"
          spendingKdv: "15"
          spendingTotal: "160"
          totalDebt: "290.00"
      }
`

**Comment by LazyLahtak** [comment]
Hi @turkdoktoru,

I couldn't reproduce this issue. Would you provide a runnable project (using [CodeSandbox](https://codesandbox.io/s/hopeful-taussig-tlhk8?file=/demo.js), for example)? It will help us to find a solution.
