### ISSUE TITLE
display error on selected appointment dates

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2845]
Hello there,

I use the appointment system below. But I will ask something. Although "April" is written in the 4th month on the start and end dates, it does not show up in April. Is this a bug? Or is there a place where I make a mistake

In the examples, although 3 of them were selected on April 01, 2020, 2 records show in May. How can we fix this? Or is it bug

[https://imgur.com/VyKc0nf](url)

`

     export const appointments = [
       {
         title: "Rollout of New Website and Marketing Brochures",
         startDate: new Date(2020, 4, 01, 10, 0),                            //april 1
         endDate: new Date(2020, 4, 01, 11, 30),                           //april 1
         id: 37,
         location: "Room 3"
      },
      { 
         title: "Update NDA Agreement",
         startDate: new Date(2020, 4, 01, 10, 0),                         // April 1
         endDate: new Date(2020, 4, 01, 14, 30),                        // April 1
         id: 38,
         location: "Room 2"
       },
       {
          title: "Customer Workshop",
         startDate: new Date(2020, 3, 01, 11, 0),                        // March 1
         endDate: new Date(2020, 3, 01, 12, 0),                        // March   1
         allDay: true,
         id: 39,
         location: "Room 1"
       }
     ];
`

**Comment by AryamnovEugeniy** [comment]
Hello,

The Scheduler works as expected. You may refer to the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) or even try your dates in browser's console, for instance, here is what I've got when I created a new date as you did:
![image](https://user-images.githubusercontent.com/51905811/79848022-34757700-83c9-11ea-8d0b-478d5395c034.png)
