### ISSUE TITLE
all documentation unavailable

### ISSUE THREAD

**Issue by cellog** [DevExpress/devextreme-reactive#2846]
A reference to redux devtools is killing off all the examples:

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Steps to Reproduce

visit any documentation page with an example

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

<img width="1677" alt="Screen Shot 2020-04-20 at 8 38 11 PM" src="https://user-images.githubusercontent.com/98250/79812420-db64ff00-8346-11ea-9c76-a80af3178b5f.png">

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @cellog,

I couldn't reproduce this error. I am using Redux DevTools, but all demos work fine. Our demos work with Redux DevTools correctly - see Redux [documentation](https://github.com/zalmoxisus/redux-devtools-extension#11-basic-store).

Could you please clarify which versions of a browser and Redux DevTools you are using? This may help us reproduce the error.

**Comment by cellog** [comment]
I believe the issue may be when you don't have redux devtools installed. I was using a browser that did not at the time.

**Comment by LazyLahtak** [comment]
@cellog

I checked our site under Chrome with Redux DevTools and without. Also, I checked our site under Mozilla Firefox, Safari and on mobile devices. I couldn't get the same error.
Could you please provide additional information to help us solve this issue? Under which browser do you get this error, what extensions are installed?

**Comment by cellog** [comment]
I figured out the source of the issue, and for future reference is it that this XState visualization extension has a bug in it: https://chrome.google.com/webstore/detail/xstate-devtools/aamnodipnlopbknpklfoabalmobheehc?hl=en

I'm going to close this, and apologize for the noise, and also open a bug for them!
