### ISSUE TITLE
Row Re Ordering Feature

### ISSUE THREAD

**Issue by totalard** [DevExpress/devextreme-reactive#2847]
It would be better, if Implimented Row Reordering , Like a Handle at Left most side, so that we can move it up and down

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by ushkal** [comment]
Hi @totalard ,

Please see the following threads to find a sample implementation: #419, #2592 . Also, we are planning to release a guide on the row reordering feature.
