### ISSUE TITLE
I need to know for which value field the editor I am rendering

### ISSUE THREAD

**Issue by agundogdu1** [DevExpress/devextreme-reactive#2848]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hello,
"AppointmentForm.TextEditorProps" or any editor props in not has field key.I need to know for which value field the editor I am rendering.
Because when I crush the relevant editors, it needs to be used to determine the new features I want to put on them.

For example my appointment model has  City and country.
Both are editor of choice but options should be different

**Comment by AryamnovEugeniy** [comment]
Hello,

Could you clarify what you want to achieve? The best way would be to update the [example](https://codesandbox.io/s/angry-bush-vdexe?file=/demo.js) I created. In my example I added two custom fields to the `ApointmentForm`: `country` and `city`.

**Comment by agundogdu1** [comment]
You have static fields. I use created dynamic model.
I updated your example. Can you see  columns and custom text editor

**Comment by AryamnovEugeniy** [comment]
I need the link to your updated example. Because every time a sandbox is forked, a new link is created. And in order for me to see the changes you've made, I need this link.

**Comment by agundogdu1** [comment]
Oh sorry 
https://codesandbox.io/s/busy-curran-vj0ez?file=/demo.js:3689-3756

**Comment by AryamnovEugeniy** [comment]
Could you clarify a little bit further why the approach described above won't work in your case?
And also, your use case is still unclear to me. Could you describe it in more detail? For example, what do you want to render inside the AppointmentForm? What editors do you want to render? Do you want to change already existing editors or create new ones? And do you know beforehand your appointments' properties (for example, you mentioned `city` and `country`. Do you know them beforehand or they will be somehow generated in runtime?) A screenshot of what you want to achieve would be very helpful.

**Comment by agundogdu1** [comment]
Maybe I can succeed if I try again. Replacing .Appointment.BasicLayout resolved my problem thanks
