### ISSUE TITLE
Deselect all on rows change?

### ISSUE THREAD

**Issue by tmaiaroto** [DevExpress/devextreme-reactive#2849]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

With integrated selection, is there an easy way to clear all selected rows on a change? When I filter the set of results (from the api) or change the page, it will get a new set of rows. At this point I want to remove anything that was previously checked. -- In other words, I don't want anything not visible to the user selected. 

Using the selection state and setting the selection prop certainly worked...the problem is the check/uncheck render performance is extremely slow. The reason is because it first needs to loop every row. When you have data type providers at play as well...this can really take a bit of time. In general, I wish there was better memoization for data type providers in general. The formatterComponent ends up being called all the time. If there's been no change to the row/cell, it need not be called at all.

Regardless, this can be helped by ensuring the entire grid isn't re-rendered more than necessary. The problem? SelectionState is a child of the Grid and now when you go to manage selection state outside of the Grid.... well, you get hit with the complete re-render.

I've tried with a variety of header cell overrides, but it can lead to some loops. Maybe some examples and more documentation on plugins? Is there a link? Codesandbox examples? I'm just not sure how I can get at those Actions...but i'd really love to be able to just call a function to reset what's selected. That I can do when rows change. My memoized grid will see the rows update and I should easily be able to call something to wipe out the selection. I just need the selection state within the child and not coming back in on top the grid. 

Any thoughts? Thanks!

### Environment

- devextreme-reactive: 2.6.0
- react: 16.8.0
- browser: N/A / all
- material-ui: 4.9.1

**Comment by LazyLahtak** [comment]
Hi @tmaiaroto,

To manually select or unselect rows, you need to use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode). Check this [example](https://codesandbox.io/s/optimistic-waterfall-u9lc6?file=/demo.js) illustrating selection and filtering.

If you have further questions, let us know.

**Comment by tmaiaroto** [comment]
Too slow. Like I was saying, it requires the entire grid and all the cells and any formatter components. I'm getting fairly familiar with this component (framework really if you ask me, it's quite robust and I'm enjoying it a good bit). I know the normal approach for selection state in controlled mode.

Do you have any collection of examples with plugins? That's the one area I'm still learning. I have a plugin now that I'm working on that might do the trick ... But I'm still trying to learn more about them and how to get to the actions so I can get access to that toggle function.

Thanks!

**Comment by LazyLahtak** [comment]
@tmaiaroto,

Our Actions and the plugin's property change the same state. Changing the `selection` property re-renders only cells with a checkbox.
Performance issues may be caused by custom components. Please refer to our [guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/).
Also, it would help if you send us your code or a runnable project (using [CodeSandbox](https://codesandbox.io/s/ecstatic-cherry-cccw7?file=/demo.js), for example). This may help us research the issue and find a solution.

**Comment by tmaiaroto** [comment]
Actually, I figured out how to make a plugin and found a solution. If I can get the time, I'll post an example code sandbox.

Basically:
const { dispatch, state } = useContext(store);
const { rows } = state;

Then you have your memoized render returning:
<Grid rows={rows}>
  <SelectionState onSelectChange={s => dispatch({ type: setSelection, payload: s}) }
  <IntegratedSelection />
  <SelectionDeselectOnChangePlugin rows={rows} />

Where you have rows as JSON.stringify(rows) in the memo check. Now, you can pass the selection off to your state elsewhere and not have it come back and re-render the entire grid. That is still managed by the integrated selection.

So then the plugin will catch any row update and reset the selection. This way, when you change pages, filter, etc. it won't keep a selection the user can't see.

However, it also won't use setState which would update the parent component and force the <Grid> to re-render. Yet it also lets us keep the rows, filters, and so on ... AND selection in the same state. Which is convenient. Rather than having all these different states or contexts.

Again the reason here is that if the entire <Grid> runs through an update each time a checkbox is checked, it can be very slow depending on how many <DataTypeProvider> you have and whatever else you have going on. You can load the grid up with tons of plugins and functionality. Draggable columns, column resize, visibility, etc. So preventing the grid from re-rendering more than necessary is critical. 

You will see a lag time from when you check a checkbox to when you actually see it visually checked if you have to go through a complete grid update in some cases. Id imagine many cases really. The more rows you have? 50? 100? The longer it will take. 

That's what I'll try to get into a codesandbox. A scenario where you can see how much delay datatypeproviders will add.

I suspect it comes down to the formatterComponent prop. Im guessing it gets passed an object and that's always going to trigger the re-render even if that object hasn't changed. Since I can't get to that area of the code (or maybe with some override component I can??) I can't put those props into a useMemo. So I can't prevent each row and each column where a formatterComponent is being used from being re-rendered. That means anything heavy in a formatterComponent becomes a serious issue.

**Comment by LazyLahtak** [comment]
@tmaiaroto,

Thank you for your clarification. 

Please, keep in mind that the plugin order is important (see our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#data-processing-plugins)). I suggest that you place `IntegratedSelection` after other `Integrated` plugins. Here is a simple [example](https://codesandbox.io/s/patient-sun-rvsu0) demonstrating selection, paging, and filtering.

Does this solution meet your requirements?

If you still have some performance issues, please share your code or a runnable project with you custom components (for example, you could modify the sample above).
