### ISSUE TITLE
VirtualTableState not optimized for cursor pagination

### ISSUE THREAD

**Issue by cellog** [DevExpress/devextreme-reactive#2850]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

The implementation of lazy loading by `VirtualTableState` currently passes an arbitrary value to `take`. For cursor pagination, this means we cannot use this value as-is, but must do some math. For some context, the endpoint I am querying is a DynamoDB endpoint, and the cursor is a combination of the endpoint data plus the page size. If I have just requested a page size of 20 items, I can't suddenly request 40 items, or the cursor no longer works. This forces some awkward math - I will have to take the endpoint requested, and iterate, requesting an endpoint, then subtracting until it hits 0, all in an async loop.

It would be great if there was a way to specify "always request the same page size" so this weird math dance was unnecessary

**Comment by LazyLahtak** [comment]
Hi @cellog,


I suggest you try the following approach to implement cursor pagination without `VirtualTableState`:

1. You can handle the top row ID using the VirtualTable onTopRowChange [handler](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#properties). This handler is raised on scrolling.
2. Change your cursor if necessary. During the cursor change, you can trigger a function that loads new rows based on the cursor and page size.

Check this [example](https://codesandbox.io/s/goofy-leakey-b7eji?file=/demo.js), which can be modified for your API.
Let me know if this solution meets your requirements.

**Comment by cellog** [comment]
This could work. A quick question - the `onTopRowChange` handler triggers with an `onscroll` event or `IntersectionObserver`? Performance will be a concern for us. If it uses intersection observer, it will meet our needs perfectly. That's a great example to put in the docs!

**Comment by LazyLahtak** [comment]
@cellog,

The `onTopRowChange` handler is triggered on the scroll event. We will consider using `IntersectionObserver` in future releases (probably, in the next major release). Also, we will consider adding the example mentioned above to our docs.
