### ISSUE TITLE
Remote Paging Help Needed

### ISSUE THREAD

**Issue by lutakyn** [DevExpress/devextreme-reactive#2852]
I have searched this repository's issues and believe that this is not a duplicate. I have followed the steps in this demo below https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/paging/ , but I am finding it difficult to use the Paging Component.
I want to start implementation of Remote Paging to my component. In the tutorial, you have 

```
const getQueryString = () => (
    `${URL}&take=${pageSize}&skip=${pageSize * currentPage}`
  );

  const loadData = () => {
    const queryString = getQueryString();
    if (queryString !== lastQuery && !loading) {
      setLoading(true);
      fetch(queryString)
        .then(response => response.json())
        .then(({ data, totalCount: newTotalCount }) => {
          setRows(data);
          setTotalCount(newTotalCount);
          setLoading(false);
        })
        .catch(() => setLoading(false));
      setLastQuery(queryString);
    }
  };

  useEffect(() => loadData());
```
I have to call this in a high order component to pass data down to the grid. now you have setRows and other properties for the grid

I'm using ...
 React Grid
Current Behaviour
Grid component doesn't have remote paging. The problem is i have this grid as a generic component i call in other components to use. But looking at the tutorial, 

Expected Behaviour
A reusable grid component with remote paging activated

Steps to Reproduce
Use the code below

    `import React, { useState,useRef, useCallback } from "react";
      import { withRouter } from "react-router-dom";
     import {
     Template,
     TemplatePlaceholder,
      TemplateConnector
       } from "@devexpress/dx-react-core";
     import { PagingState,SearchState,SelectionState,IntegratedPaging,
     IntegratedSelection,
     IntegratedFiltering
     } from "@devexpress/dx-react-grid";
     import {
      Grid,
       Table,
       TableHeaderRow,
      Toolbar,
      SearchPanel,
      PagingPanel,
      ExportPanel
       } from "@devexpress/dx-react-grid-bootstrap4";
      import { GridExporter } from '@devexpress/dx-react-grid-export';
     import saveAs from 'file-saver';
      import "@devexpress/dx-react-grid-bootstrap4/dist/dx-react-grid-bootstrap4.css";

      const onSave = (workbook) => {
      workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'DataGrid.xlsx');
      });
     };
      const GridUtils = props => {
     const { rows, columns } = props;
      const [pageSizes] = React.useState([50, 100, 500, 0]);
      const exporterRef = useRef(null);
     const startExport = useCallback(() => {
       exporterRef.current.exportGrid();
       }, [exporterRef]);

      const [selection, setSelection] = React.useState([]);

     return (
      <div className="">
     <Grid rows={rows || []} columns={columns || []}>
      <PagingState />
      <SearchState defaultValue="" />
      <SelectionState
        selection={selection}
        onSelectionChange={setSelection}
       />

      <IntegratedPaging />
      <IntegratedSelection />
      <IntegratedFiltering />
      <PagingPanel pageSizes={pageSizes} />
      <Table
        cellComponent={props.cellComponent} //getting props here didn't work
        tableComponent={props.tableComponent}
        rowComponent={props.rowComponent}
       />
      <TableHeaderRow />
       <Toolbar />
      <ExportPanel startExport={startExport} />
      <SearchPanel />
      <Template name="toolbarContent">
        <TemplateConnector>
        {({ totalCount }) => (
          <React.Fragment>
            <div>Total Count: {totalCount} Records</div>
            <TemplatePlaceholder />
          </React.Fragment>
        )}
        </TemplateConnector>
      </Template>
     </Grid>
     <GridExporter
      ref={exporterRef}
    rows={rows}
    columns={columns}
    selection={selection}
    onSave={onSave}
    />
      </div>
      );
     };

     export default withRouter(GridUtils);`

This is an example component I use.

```
export default class Messages extends React.Component{
   state={ allUsers:[]}
   // i have to make api call to retrieve users here
    fetch(url)
        .then(response => response.json())
        .then( this.setState({
                    allUsers:data
              })
        .catch(() => setLoading(false));
   
render(){
return (
            <GridUtils
                  columns={columns}
                  rows={this.state.allUsers}
                  cellComponent={this.TableCell}
                  rowComponent={this.TableRow}
                  tableComponent={TableComponent}
                />)
}

My issue is how can user setRows when i get data from the api
```

Environment
devextreme-reactive: "^2.6.2",
react: xxx"^16.12.0",
browser: chrome
bootstrap: "^4.4.1",
react-bootstrap: "^1.0.0-beta.16",

**Comment by lutakyn** [comment]
Hello,any update??

**Comment by ushkal** [comment]
Hi @lutakyn ,

I recommend you pass rows to GridUtils as show in this [example](https://codesandbox.io/s/modest-bhabha-rxe1f?file=/demo.js). Let me know if it helps. Otherwise, please describe your issue in greater detail.
