### ISSUE TITLE
Drag-n-drop grouping working incorrectly in container with attribute 'transform: translate(x, y)'

### ISSUE THREAD

**Issue by igor-stecyura** [DevExpress/devextreme-reactive#2853]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I'm using React Grid with grouping panel in popup window and that window positioned on page with css property 'transform; translate(x, y)'. When I'm trying to drag and drop column from table to grouping panel the dragged component located not exactly on cursor. Difference beetween correct position and current the same as values in **translate(x, y)**. If I'm turn of transform attribute all works as expected.

### Expected Behaviour
Dragged component located exactly under the cursor.

### Steps to Reproduce
1. Open sandbox example
2. Drag and drop column to Grouping panel

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/elegant-kilby-li5sl?file=/demo.tsx&gt;

### Environment
Reproduced in devextreme's example 
https://codesandbox.io/s/elegant-kilby-li5sl?file=/demo.tsx

**Comment by LazyLahtak** [comment]
Hi @igor-stecyura,

I suggest that you place a container with the `transform` css property into Grid rootComponent. Here is an [example](https://codesandbox.io/s/throbbing-sea-rj1f9?file=/demo.tsx).
Does this solution meet your requirements?

**Comment by igor-stecyura** [comment]
Hi @LazyLahtak 
Actually not, this implementation not meet my requirements because in this case container with `transform ` it's a part of grid and if I'll put this grid to component with transform I'll receive same results...

For example: 
```
<Modal style={{ transform: 'translate(100px, 178px)' }}>
  <Grid rootComponent={'some root component with transform can be here but it hasn't any sense} />
</Modal>
```

`translate(100px, 178px)` - is dynamically changing by dragging modal  

In this case we will have same issue.

Initial case how I using this grid it is inside devexpress popup component
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Popup/Overview/React/Light/

**Comment by LazyLahtak** [comment]
@igor-stecyura,

I put our Grid in the DevExpress Popup component and didn't get any problem with dragging. Here is an [example](https://codesandbox.io/s/inspiring-hodgkin-wli06?file=/demo.tsx).
Could you please clarify what kind of problem you experience?

**Comment by igor-stecyura** [comment]
Hello @LazyLahtak, thanks for reply

I have created another [https://codesandbox.io/s/friendly-sky-hsq3b?file=/demo.tsx](example) based on your last example.

**Comment by LazyLahtak** [comment]
@igor-stecyura,

Is there any reason to avoid rendering containers in the `Grid.Root` component and provide additional properties like in this [example](https://codesandbox.io/s/funny-frog-i1jy5?file=/demo.tsx)? Could you clarify this?

**Comment by igor-stecyura** [comment]
@LazyLahtak thanks for reply

Your example works and it’s good, but it looks like a huge workaround and that’s not what I expect from the React component. The fact is that I expect to use and reuse the same grid in different places(dialog, modal, app root or any other place where grid is appropriate) of my application without changing this grid for each of use case:

```
<SomeContainer> // some place in the application
  // ... render here some other components
  <Grid>
  // ... render here some other components
</SomeContainer>
```
In your last example, Grid component is responsible for Container component rendering, in fact the container becomes part of the grid, it makes the container dependent on the grid itself and the container cannot exist without the Grid.

Please let me know why we can't consider this problem as a bug in the grid implementation? For example, the grid from the `devextreme-react/data-grid` library works correctly in such cases. I know that this is just a wrapper over non-react components, but the behavior of this wrapper matches my expectations and understanding of how a react component should behave in a composition with other components.

**Comment by LazyLahtak** [comment]
@igor-stecyura,

Thank you for elaborating on your scenario. We double-checked this use case, but didn't find a way to fix the issue at the widget level. Currently the component has access to the context of the current container only, while this particular scenario requires us to have access to external DOM elements.
To support this scenario, we need to attach elements to the `body` container, which contradicts the current implementation. We will need to refactor this implementation to support this scenario. We'll take your use case into account in future development. As a possible solution, you may consider the following [example](https://codesandbox.io/s/sweet-blackwell-gp953?file=/index.html).

**Comment by igor-stecyura** [comment]
Hi @LazyLahtak 
Thanks for your example and issue fix!  Good job!
