### ISSUE TITLE
Right to Left (rtl) Grid

### ISSUE THREAD

**Issue by shmuliko** [DevExpress/devextreme-reactive#2854]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
i want use devExpress-grid into RTL website
i find old issue about this, but is not active very long time
(https://github.com/DevExpress/devextreme-reactive/issues/1423)

i decided how way i need to add this attribute to this project

for example: i drill into the code, and i change in file helpers.ts, Line 7, replace the minus for shift to use rtl direction [to change direction on resizing columns]

i want follow about variable to read if this grid direction is rtl or ltr, to change the code by direction 

i think about use with Getter to set "isRtl = true" and read this value from all nodes as this influencing

but i have very Confusion about the plugins templates and getters
do i need create new plugin?
what kind?
how i get the getter value in helper file?
Where do I add the style?

thank you of the help

**Comment by LazyLahtak** [comment]
Hi @shmuliko,

I suggest you follow [this](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) guide, that will help you understand our plugin system. Here it is shown how you can implement your own plugins.

Other useful links:

* [Getter API](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/)
* [Template API](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/)
* [TemplateConnector API](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template-connector/)


Component styles are applied in theme packages. For example, [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-cell.jsx) is a way in source, where you can find the TableCell component for Material-UI.

If you have any further questions, let us know.
