### ISSUE TITLE
Passing data to Toolbar Root Component ?

### ISSUE THREAD

**Issue by totalard** [DevExpress/devextreme-reactive#2855]
i have cuustomized Toolbar part of the Grid, it Works Great.

But How i pass some information from Table to the  toolbar. Like selection data.. As props have only children. I cant find any way to pass selection data to Toolbar Root Component.

- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by LazyLahtak** [comment]
Hi @totalard,

Сould you please clarify the purpose of passing data into the `Toolbar.Root` component?
Here is an [example](https://codesandbox.io/s/still-shadow-n8q3d?file=/demo.js) of how you can provide additional info into the component.
Does this solution meet your requirements?

**Comment by totalard** [comment]
For Selected Count Purpose and also Placing Delete Button Once Rows Selected

**Comment by totalard** [comment]
The given example is good... It's working... But using rootprops in toolbar root component is good instead of using Memo

**Comment by LazyLahtak** [comment]
@totalard,

We provide only necessary properties in our component. If you want to provide additional properties, use the solution described above or our [connectProps](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/connect-props/) function. Here is an [example](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/).

If you have any further questions, feel free to contact us.
