### ISSUE TITLE
Change cell background color if edited

### ISSUE THREAD

**Issue by parthmishra** [DevExpress/devextreme-reactive#2856]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I'm not sure how it's possible to change a cell style after doing an inline-cell edit. If the new value is different than the old value, then I want the cell background color to change. Is there an event that fires that I can do this in? 

### Environment

latest react
material-ui

**Comment by MaximKudriavtsev** [comment]
Hi @izundo-viennv,

We have already registered the similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/2479#issuecomment-545883737).
