### ISSUE TITLE
date and time selection within the editable area

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2858]
Hello there,

I am using the Editable table. I want to use "DateTimePicker" for a field in a table. So I want to choose the time and date in the field. I searched the documents but I couldn't get anything.

**Comment by MaximKudriavtsev** [comment]
Hi @turkdoktoru,

We have already registered the [same issue](https://github.com/DevExpress/devextreme-reactive/issues/2539#issuecomment-558527604).

**Comment by turkdoktoru** [comment]
I need date + time information.

**Comment by turkdoktoru** [comment]
ok, problem solved
