### ISSUE TITLE
Creating data from json with chart

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2859]
Hello there,

I am using a query like the one below.

For a reporting screen, the result is as follows with the API.
How can I transfer this result to the chart?

**json format from the server**

     {
           constantSpendingAmount: "23.00"
           constantSpendingTotal: "23.35"
           receivedAmount: "59.00"
           spendingAmount: "750.00"
           spendingKdv: "18"
           spendingTotal: "885.00"
           totalDebt: "470.00"
     }

`

     import React, { Component } from "react";
     import Paper from "@material-ui/core/Paper";
     import {
        Chart,
        ArgumentAxis, 
        ValueAxis,
        Title,
        Legend,
       BarSeries
     } from "@devexpress/dx-react-chart-material-ui"; 
     import { Animation, Stack } from "@devexpress/dx-react-chart";
     import { Input, Row, Col, Label, Button } from "reactstrap";

     class FinancialTable extends Component {
        constructor(props) {
         super(props);
  
      this.domain = process.env.REACT_APP_APISERVER;
         this.state = {
         data: [ ],
          isLoaded: true
       };

         this.getFinancialReports = this.getFinancialReports.bind(this);
         this.handleChange = this.handleChange.bind(this);
       }
  
  
       async getFinancialReports() {
         await fetch(
           `${this.domain}/api/financialreport/report?` +
             `groupCode=${this.props.account_profile.profile.profile.groupCode}` +
             `&startingDate=${this.state.startingDate}` +
             `&endDate=${this.state.endDate}`,
           {
             headers: {
               Authorization: `Bearer ${localStorage.getItem("id_token")}`,
               "Content-Type": "application/json"
             }
           }
         )
           .then(res => {
              if (res.ok) {
               return res.json();
             } else {
               return res.json().then(err => Promise.reject(err));
             }
           })
           .then(json => {
             console.log(json)
             this.setState({
               data: json
             });
          })
        .catch(error => {
            console.log(error);
           return error;
         });
       }

       handleChange(e) {
         this.setState({
            [e.target.name]: e.target.value
         });
       }

       Root = props => (
         <Legend.Root
           {...props}
           style={{
             display: "grid",
             gridTemplateColumns: "auto auto auto",
             margin: "auto"
           }}
         />
       );
        render() {
          const { isLoaded, data } = this.state;

         if (!isLoaded) {
           return <div>Loading...</div>;
         } else {
           return (
             <Paper>
               <Row>
                 <Col xs={"3"}>
                   <Label>Start date</Label>
                   <Input
                      type={"date"}
                      name={"startingDate"}
                     onChange={this.handleChange}
                  />
              </Col>

            <Col xs={"3"}>
              <Label>End date</Label>
              <Input
                type={"date"}
                name={"endDate"}
                onChange={this.handleChange}
              />
            </Col>

            <Col xs={"auto"}>
              <br />
              <Button
                disabled={!this.state.startingDate || !this.state.endDate}
                onClick={this.getFinancialReports} >
                Query
              </Button>
            </Col>
          </Row>

          <Chart data={data}>
            <ArgumentAxis />
            <ValueAxis />

            <BarSeries
              name="total debts"
              valueField="totalDebt"
              argumentField="state"
            />
            <BarSeries
              name="received amount"
              valueField="receivedAmount"
              argumentField="state"
            />

            <BarSeries
              name="spending total"
              valueField="constantSpendingTotal"
              argumentField="state"
            />
            <BarSeries
              name="constant spending amount"
              valueField="constantSpendingAmount"
              argumentField="state"
            />

            <BarSeries
              name="spending amount"
              valueField="spendingAmount"
              argumentField="state"
            />
            <BarSeries
              name="spending kdv"
              valueField="spendingKdv"
              argumentField="state"
            />
            <BarSeries
              name="spending total"
              valueField="spendingTotal"
              argumentField="state"
            />

            <Animation />
            <Legend position="bottom" rootComponent={this.Root} />
            <Title text="Tarihli gelir/gider raporu" />
            <Stack />

            </Chart>
            </Paper>
          );
         }
       }
      }

      export FinancialTable;

`

**Comment by AryamnovEugeniy** [comment]
Hello,

Every chart has two axes: value axis and argument axis. You need to provide values for both of them in order for chart to know what to render. However, you provide `argument: "state"` property for all of your bars, which is absent in your data (the data you get from json object).
In other words, the solution is tp provide `argument` field in your data, for example, as below:
```
this.setState({
    data: [{
        ...yourFeilds,
        state: 'Some argument value here',
    }, {
       ...
    }, ...],
});
```
