### ISSUE TITLE
Publish a new version of dx-react-grid-material-ui

### ISSUE THREAD

**Issue by jgoux** [DevExpress/devextreme-reactive#286]
Hello,

I'm trying dx-react-grid-material-ui and I was wondering if you could publish a new version of the package with the fix for using material-ui@1.0.0-beta.6 ?

Thank you very much!

**Comment by oallouch** [comment]
see https://github.com/DevExpress/devextreme-reactive/pull/275

**Comment by jgoux** [comment]
This is the fix I was talking about actually. 👍 

Maybe I don't understand, is it published yet?

**Comment by dxbykov** [comment]
Hi,

It's not published yet. We are going to publish it in a week.

**Comment by oallouch** [comment]
can be closed now
