### ISSUE TITLE
Incorrect viewport of VirtualTable inside dx Popup

### ISSUE THREAD

**Issue by igor-stecyura** [DevExpress/devextreme-reactive#2861]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
 
### Current Behaviour
`VirtualTable ` incorrectly calculate the width of the viewport when using Grid inside devextreme `Popup ` component. Regardless of `Popup ` width only two column with data are visible but table rows are displayed across the entire width.

### Expected Behaviour
Columns with data are visible across the entire width of the table.

### Steps to Reproduce
1. Open Codesandbox example
2. Scroll table horizontally 

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/dark-microservice-ngddk?file=/demo.js&gt;

### Screenshots
![viewport](https://user-images.githubusercontent.com/19396733/80410200-df5ac900-88d2-11ea-9976-eb06ce801100.png)

### Environment
@devexpress/dx-react-core: "2.6.2"
@devexpress/dx-react-grid: "2.6.2"
@devexpress/dx-react-grid-material-ui: "2.6.2"
@material-ui/core: "^4.9.7"
@material-ui/icons: "^4.9.1"
devextreme: "19.2.7"
devextreme-react: "19.2.7"
react: "^16.13.1"
react-dom: "latest"

**Comment by LovedByTheLord** [comment]
This issue is being discussed in the DX Support Center: https://supportcenter.devexpress.com/ticket/details/t887799/reactive-grid-doesn-t-correctly-render-columns-and-rows-when-using-virtualtable-inside

**Comment by LazyLahtak** [comment]
@igor-stecyura

If you have any further questions, feel free to contact us.
