### ISSUE TITLE
create and query the lookupField field within the appointment

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#2862]
Hello there,

I am using the appointment code below.

I want to add a lookupfield field in <AppointmentForm.Overlay in AppointmentFormContainerBasic.

This lookupField field that I added will search within this.state.customerList. How can I achieve this?

https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/#react-scheduler-data-editing

https://filebin.net/eoe5974kngha9bne

**Comment by AryamnovEugeniy** [comment]
Hello,

For such a scenario, you can use a state management library, such as [Redux](https://redux.js.org/), or [connectProps](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/connect-props/) function (see [our guide and example](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) on how to access parent component's state). This will allow you to access your Customer List and, thus, create your lookupField.
