### ISSUE TITLE
Virtual Grid layout is broken under hidden DOM parent

### ISSUE THREAD

**Issue by serche** [DevExpress/devextreme-reactive#2868]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Virtual Grid layout is broken in case Grid component has been mounted under hidden DOM parent

### Expected Behaviour
Layout should not to be broken for such cases

### Steps to Reproduce
Switch on "Second" tab. 

Example: https://codesandbox.io/s/restless-microservice-pj8m0?file=/demo.js

### Screenshots
![image](https://user-images.githubusercontent.com/6908703/80680015-b3079e00-8ac6-11ea-910d-dc2d9ce67e5c.png)

![image](https://user-images.githubusercontent.com/6908703/80680048-c286e700-8ac6-11ea-9a74-98a0db6f2d5c.png)

**Comment by AryamnovEugeniy** [comment]
Hello @serche!

We have already had a similar issue. You may refer to it: https://github.com/DevExpress/devextreme-reactive/issues/2550#issuecomment-604409085
