### ISSUE TITLE
Handling the search of SearchPanel on a click button.

### ISSUE THREAD

**Issue by dalborgo** [DevExpress/devextreme-reactive#2869]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is it possible to implement the SearchPanel searching, on a button click instead of on the every changing value of textinput?

Thanks.

- devextreme-reactive: 2.6.2
- react: 16.13.1
- browser: chrome
- material-ui: yes

**Comment by LazyLahtak** [comment]
Hi @dalborgo,

You could define you own SearchPanel [inputComponent](https://codesandbox.io/s/priceless-morning-2wj0e?file=/demo.js), where you can catch the `onValueChanged` handler and pass it into the Button's click. Here is an [example](https://codesandbox.io/s/priceless-morning-2wj0e?file=/demo.js).
If you have any further questions, let us know.

**Comment by dalborgo** [comment]
Thank you.

**Comment by LazyLahtak** [comment]
You are welcome!
