### ISSUE TITLE
TableEditColumn position

### ISSUE THREAD

**Issue by jgoux** [DevExpress/devextreme-reactive#287]
Hi,

is it possible to put a `TableEditColumn` at the end the of grid instead of the begining ?

**Comment by dxbykov** [comment]
Hi,

It's not possible via our public API now, but as a temporary workaround, you can follow [this sample](https://stackblitz.com/edit/react-pzyqxc?file=index.js).

**Comment by Justiffy** [comment]
same,  `this sample` didnt work for me :C 
    "@devexpress/dx-react-core": "1.8.0",
    "@devexpress/dx-react-grid": "1.8.0",
    "@devexpress/dx-react-grid-bootstrap3": "^1.8.0",
    "@devexpress/dx-react-grid-material-ui": "1.8.0",
    "@material-ui/core": "3.1.2",
    "react": "^16.2.0",

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to the updated [sample](https://stackblitz.com/edit/react-x33fvt?file=index.js).
The difference is using the [TableEditColumn.COLUMN_TYPE](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column#static-fields) value to identify a table edit column. Before now it was just the `editCommand` string.

**Comment by SergeyAlexeev** [comment]
Hi,

Please refer to the updated [sample](https://stackblitz.com/edit/react-x33fvt?file=index.js).
The difference is using the [TableEditColumn.COLUMN_TYPE](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column#static-fields) value to identify a table edit column. Before now it was just the `editCommand` string.

**Comment by Justiffy** [comment]
ty, its work :3

**Comment by rainmak33r** [comment]
Any updates on this ? except the workaround ?

**Comment by churkin** [comment]
Hi @rainmak33r,
Thank you for your interest in our grid. We have no plans to implement this functionality in the near future. The workaround is quite simple. However, we will consider user requests for this feature.

**Comment by paillave** [comment]
this grid is the most perfect and complete that exists in the whole react ecosystem. However, the fact that not  out of the box "command" type column that we can put wherever we want is not in the solution seems crazy given how simple and advanced is this grid. Even more knowing that nowhere (unless I missed something) lies a functionality that permits to select ONE row or this listen the click on a row out of the box.

**Comment by paillave** [comment]
FYI, by looking `EditCommand` plugin devextreme source I made an `ActionColumns` that works with the same spirit than other devextreme plugins (internally and externally).
https://codesandbox.io/s/m6yve
