### ISSUE TITLE
Difficulty Using DayView.TimeScaleLayoutProps

### ISSUE THREAD

**Issue by smirciat** [DevExpress/devextreme-reactive#2872]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I am trying to pass a custom height to the time scale using TimeScaleLayoutProps but I can't seem to get the structure right.  A simple example of what I'm trying to do is at https://codesandbox.io/s/elated-hodgkin-1pn61?file=/demo.js .  

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/elated-hodgkin-1pn61?file=/demo.js&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.6.2
- react: 16.13.1
- browser: Chrome 81.0.4044.129
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.7

**Comment by AryamnovEugeniy** [comment]
Hello,

I updated your [sample](https://codesandbox.io/s/heuristic-elion-e68cg).
Note, that it will not change the heights of labels inside the `TimeScale`, neither will custom `style` if you pass it to the `TimeScaleLayout`. If you want to change the `TimeScale` you can customize the [labelComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/day-view/#dayviewtimescalelabelprops). if you want to change the height of the whole Scheduler - use [Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/#properties)'s `height` property.
