### ISSUE TITLE
Typescript TemplateConnector Getter's and Actions' types

### ISSUE THREAD

**Issue by stasyaner** [DevExpress/devextreme-reactive#2874]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello.  Might be a stupid question but are there any types for exported Getters and Actions to refer in TemplateConnector children function arguments? I've quickly looked through the sources and couldn't find any. Below, selection, rows and toggleSelection implicitly has "any" type. Thank you.
![image](https://user-images.githubusercontent.com/9165512/81002969-674c5000-8e4a-11ea-9edb-c48154440c4f.png)

**Comment by MaximKudriavtsev** [comment]
Hi @stasyaner,

You are right. We don't provide types for the TemplateConnector's child function arguments. You can get information about Getter and Action types in the `Plugin Development Reference` section of our API Reference.
