### ISSUE TITLE
Format textual column - React grid

### ISSUE THREAD

**Issue by DBS12** [DevExpress/devextreme-reactive#2875]
### I'm using ...
- [x] React Grid

### Description
Is this possible to format column to display text as it receive it (multi line + spaces etc..)?
For example, lets assume the column should display the following text:

"Color = Yellow
Age = 18
Info =
       Name = Temp
       LastName = Temp1"
I want it to be displayed in this format , but its getting display as single row all together

**Comment by LazyLahtak** [comment]
Hi @DBS12,

To format cell values, use the [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) plugin with a custom [formatterComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/#datatypeprovidervalueformatterprops). To save all line breaks and spaces you should define your own Table [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) with the CSS property `white-space: pre` or `white-space: pre-wrap`. Here is an [example](https://codesandbox.io/s/brave-gates-d4fpk).
If you have any further questions, feel free to contact us.
