### ISSUE TITLE
VirtualTable doesn't render last 3 cells, eg if totalRowCount === 103

### ISSUE THREAD

**Issue by artyil** [DevExpress/devextreme-reactive#2877]
- [x ] React Grid

consider the row caching example from the docs - https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#row-caching

I changed line number 195 by enforcing total rows to **103** rows. 
https://codesandbox.io/s/awesome-drake-w5zqh?file=/demo.js
scroll to the end of the table
The table won't trigger additional request to bring the last 3 cells.
The table show the skeletons cells instead

Please investigate ASAP, we are a paying customer!

### Current Behaviour
Only 100 rows fetched / shown in table

### Expected Behaviour
Should bring and show all 103 rows with virtual scrolling
It may also fail for other totals, 110, 120 etc... 

### Steps to Reproduce
check the description and example above

### Environment
Mac + Chrome

- devextreme-reactive: view your example
- react: xxx
- browser: chrome macOS
- material-ui: xxx

**Comment by LazyLahtak** [comment]
Hi @artyil,

Thank you for your report. I've reproduced that problem and we will fix it soon. In the meantime, I suggest you use workaround from this [example](https://codesandbox.io/s/trusting-silence-lc9zx?file=/demo.js). Take special note of the `updateRows` method.

**Comment by artyil** [comment]
@LazyLahtak thanks for fast response. Will try the workaround and wait for the stable fix

**Comment by MaximKudriavtsev** [comment]
Hi @artyil,

We have released the 2.6.3 version of DevExtreme Reactive with this fix.

**Comment by artyil** [comment]
Thank you @MaximKudriavtsev - these are great news!
