### ISSUE TITLE
Banded Column example from Documentation does not render in CodeSandbox

### ISSUE THREAD

**Issue by LovedByTheLord** [DevExpress/devextreme-reactive#2878]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
The code example under Basic Setup on the Banded Columns page in the documentation, when opened in CodeSandbox, fails to load due to a missing file.

Documentation Page: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/banded-columns/

CodeSandbox Example: https://codesandbox.io/s/2oe4n

Error message: Could not find module in path: '../countries' relative to '/demo.js'

### Expected Behaviour
The code example should render correctly.

### Steps to Reproduce
From the documentation page, click the Open in CodeSandbox button under Basic Setup.

**Comment by MaximKudriavtsev** [comment]
Hi @LovedByTheLord,

Thank you for reaching out to us. I've reproduced the bug.
