### ISSUE TITLE
Custom CSS Classes on rendered table

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#288]
Hey guys,

sorry if this is obvious and I just missed it but I've been looking through the Docs and Demos and unable to find a place where I can declare custom CSS classes that the grid should add to the table HTML element it creates.

This is relevant in for example bootstrap where you may want to use some of the bootstrap built-in table classes such as ``` table-bordered ``` ``` table-striped ``` ``` table-condensed ``` etc.

I tried adding them using the className react decorator on TableView or Grid elements without success.

Any ideas?

**Comment by kvet** [comment]
Hi,
 
Thank you for reporting this scenario. This is a very common use case. We have no API for adding custom CSS classes at this moment. We will provide a table customization API in future releases.
 
In the meantime, we suggest using the following workaround: https://stackblitz.com/edit/react-3kavn7?file=index.js

**Comment by SergeyAlexeev** [comment]
I've created a separate [issue](https://github.com/DevExpress/devextreme-reactive/issues/627) that describes a similar scenario.
