### ISSUE TITLE
onFiltersChange change VirtualTableState skip value unexpected way

### ISSUE THREAD

**Issue by Demonell** [DevExpress/devextreme-reactive#2883]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Skip value in VirtualTableState changes to unexpected values when u change filters. Sometimes it's 0 then previousValue-100 (200) and then 0 again.

Seems like it does try to filter values and scroll to top at the same time. I would like to disable automatic scroll to top or (and) disable automatic filtering but seems like there are no such option.

### Expected Behaviour

Skip value correctly changes to 0 on filter changes.

### Steps to Reproduce

1. Turn on console
2. Scroll Virtual Table to value of skip 300+ in console
3. Type '1' in Id filter
4. Watch enexpected behaviour of skip value in console

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/objective-currying-0mxjy?file=/demo.js&gt; ([pre-configured example on CodeSandbox from Lazy Loading page](https://codesandbox.io/s/mnr5y)).

### Screenshots

![](https://i.imgur.com/qoNKYj5.png)

### Environment

- devextreme-reactive: 2.6.2
- react: 16.13.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.2

**Comment by LazyLahtak** [comment]
Hi @Demonell,

Thank you for your report. We will fix it soon.
