### ISSUE TITLE
Uglifyjs issues with GridExporter

### ISSUE THREAD

**Issue by neilst** [DevExpress/devextreme-reactive#2891]
- [ x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

  Uglifyjs is failing due to ES6 syntax being present in the `dx-react-grid-export.es.js`. Specifically

```

const defaultSummaryMessages = {
  sum: 'Sum',
  min: 'Min',
  max: 'Max',
  avg: 'Avg',
  count: 'Count',
};


```

However when looking at `dx-react-grid.es.js` it does not use const and does not give any issues.

```
var defaultSummaryMessages = {
    sum: 'Sum',
    min: 'Min',
    max: 'Max',
    avg: 'Avg',
    count: 'Count',
};

```

Is this difference intentional ?

### Environment

- devextreme-reactive: 2.6.2

**Comment by Ettery** [comment]
Linking to the DevExpress support ticket: https://supportcenter.devexpress.com/ticket/details/t889656/problem-with-es6-syntax-in-dx-react-grid-export-es-js

**Comment by MaximKudriavtsev** [comment]
Hi @neilst and @Ettery,

We have merged the fix into the `master` branch and closed the issue. The fix will be available in the next package version. We'll notify you after we publish it.
