### ISSUE TITLE
Using TemplateConnector outside of Template

### ISSUE THREAD

**Issue by akozhemiakin** [DevExpress/devextreme-reactive#2894]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I have a scenario when I need to pass some computed value (from getter) as a property to one of the core plugins. After some experiments I found out that I actually can use TemplateConnector outside of Template and it seems to work.  Could you please help me: is it ok to use TemplateConnector outside of the Template or is there a better way to pass some value from getter as a prop to the plugin?

**Comment by LazyLahtak** [comment]
Hi @akozhemiakin,

Thank you for your interest in our product.
`TemplateConnector` is designed to be used inside a `Template`. Using it outside this component may cause unexpected behavior.
Could you please elaborate on your scenario? This will help us find the solution that suits you.

**Comment by akozhemiakin** [comment]
Thanks for the fast response and for the great library. Its plugin system makes it really flexible and extendable. Actually we already developed a little set of custom plugins around the lib and we will be glad to contribute them after some more testing and polishing. However at some points we still seeking for canonical ways to do stuff.

In our scenario we have a plugin that dynamically manage columns (it can add or remove columns in some cases). To make it play well with `TableColumnResizing` we need to pass computed value from our custom plugin to the `TableColumnResizing` plugin `columnWidths` property (because it is required and must match the columns set at any time).

We did our best to find idiomatic way to pass computed values as a properties to plugins and did not find any better than to use TemplateConnector. We are trying to implement our extensions to the grid as plugins, and sometimes they use core plugins under the hood and need to pass computed values to the properties that way. We also tried to kind of listen to the value of interest using getter, to update the state and to pass state value as a property to the dependent plugin. But, for example, it doesn't work well with `TableColumnResizing` because before state is actually updated `TableColumnResizing` already receives outdated value in a `columnWidths` prop and throws.

**Comment by LazyLahtak** [comment]
@akozhemiakin

You can split your plugin in two: the `ColumnState` and `ColumnManager` plugins, for example. The `ColumnState` plugin will store current columns and have the `onColumnChanges` handler, which passes column changes (see [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode)). Also, this plugin will provide an [Action](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/action/) that allows you to call the `onColumnChanges` handler in the `ColumnManager` plugin. Most of our features (Sorting, Filtering, Searching) are implemented in this way.

In your application, you will catch column changes and correct properties for the `TableColumnResizing` plugin.

Let me know if this solution meets your requirements.

**Comment by akozhemiakin** [comment]
Thanks again for the quick response. I carefully studied the proposed solution and I see at least one problem here.

Actions are imperative by their nature and they are perfectly suited for handling user interactions. However in our case it is not about user interactions changing columns. Generally speaking we have some input (columns) and have a sequence of `Plugins` in our pipe affecting this input with computed getters. At some point we need to compute value from `columns` and pass it to the `TableColumnResizing` plugin property. In that case it looks pretty unnatural to store columns somewhere and instead of using computed getters to update its value with actions.

**Comment by MaximKudriavtsev** [comment]
Hi @akozhemiakin,

In this case, you can create a custom `EnhancedTableColumnResizing` plugin - just [copy-paste](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-column-resizing.tsx) our code and add corresponding custom Getters.

**Comment by akozhemiakin** [comment]
Okay, sounds legit. How do you think, could we incorporate ability to define it with getter into the lib (in backwards-compatible way, keeping the ability to set it through the property as well)? I could try to prepare the PR.

**Comment by MaximKudriavtsev** [comment]
We appreciate your desire to enhance our products. However, I'm not sure if this particular feature is necessary in common code. If it's specific to your particular case, I think it will be better to keep custom code inside your project.
 
If you would like to implement some complete features with tests, demos, and documentation, we will be happy to help you in this way.

**Comment by akozhemiakin** [comment]
Ok, thanks again for the assistance and for the great lib :)

I'm closing this issue because of the original question being answered.
