### ISSUE TITLE
Charts are not responsives..

### ISSUE THREAD

**Issue by tsabbay** [DevExpress/devextreme-reactive#2897]
Hello,
We got a licensed product and in general, we like it.
The main problem is with charts.
Seems like they are not responsive by default and we can't find any properties that can help us to fix it.
For example: 
Let say I got a bar chart with 10 items.
on a desktop device, it will look good but on mobile, all the text will be overlapped.
The Axes looks terrible and I wondered if we missed something as We also see the same thing on the devexpress demo page.

A property that will limit the number of items per device, pagination will be nice!
Any ideas?

**Comment by MaximKudriavtsev** [comment]
Hi @tsabbay,

Currently, we have no plans to implement such a functionality out of the box. However, you can use a workaround with hidden labels, which I described [here](https://github.com/DevExpress/devextreme-reactive/issues/2306#issuecomment-528814298). Please check it and let me know if this approach is appropriate to you.

**Comment by tsabbay** [comment]
Thank you for your reply but to be honest, I am kind of surprised.
Responsive should be an integral part of web components.
 Solving the X is "easy" but this will not help Y-AXIS.
The charts are not responsive and you should specify it in your product description.

**Comment by tsabbay** [comment]
ps- this is how you guys describing your components:
**HTML5 JavaScript Component Suite for Responsive Web Development**

**Comment by MaximKudriavtsev** [comment]
@tsabbay,

Thank you for your point. That statement is true for our [DevExtreme dxChart widget](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/Overview/React/Light/). It provides [special settings](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/adaptiveLayout/) for this. You can use it in your app.

However, we cannot give you an estimate as to when this option will be implemented in [React Chart](https://devexpress.github.io/devextreme-reactive/react/chart/). We'll update our Roadmap and GitHub discussions if we decide to work on this feature.

**Comment by sky-matilderibeiro** [comment]
If we could have access to the rootComponent we could change it's style properties:

<img width="929" alt="Chart" src="https://user-images.githubusercontent.com/62330486/86488207-22fd0380-bd58-11ea-9286-d56405807e61.png">

**Comment by MaximKudriavtsev** [comment]
Hi @sky-matilderibeiro,

You can create a custom Chart Root component with custom styles based on [our internal root component](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-chart/src/templates/layout.tsx) and pass it to the `rootComponent` property.

Note, however, that it's a private API and these properties and components can be changed in the future without any notifications.
