### ISSUE TITLE
Multiple DataTypeProvider doesn't work well with resizing

### ISSUE THREAD

**Issue by dpsxp** [DevExpress/devextreme-reactive#2900]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When there are multiple `DataTypeProvider` (mostly one for each column for more customization) changing the amount of columns can create errors with other Plugins. In this specific case I got the error using `TableColumnResizing`

### Expected Behaviour
Using multiple `DataTypeProvider` shouldn't cause any problem with other plugins.

### Steps to Reproduce
- Go to the sandbox link
- Click on "Add Columns"

Link to the example that reproduces the issue: [example](https://codesandbox.io/s/compassionate-architecture-z01vx?file=/demo.js)

If you remove the `DataTypeProvider` the example will work without any error.

### Screenshots

![image](https://user-images.githubusercontent.com/1787446/82255050-57dd0480-992a-11ea-9638-2177e362964a.png)

### Environment

- devextreme-reactive: 2.6.3
- react: 16.13.1
- browser: Any
- bootstrap: 4
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @dpsxp,

When you change the number of `DataTypeProviders` dynamically, you need to wrap them in the [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) component. Here is an updated [example](https://codesandbox.io/s/quiet-resonance-94059?file=/demo.js).
If you have any further questions, feel free to contact us.

**Comment by dpsxp** [comment]
Thanks for the quick response.
