### ISSUE TITLE
Is there a way to have multiple Table Summary rows?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#2901]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is there any way to have multiple TableSummaryRows implemented in the grid? For example right now I'm using a TableSummaryRow to do a custom calculation to display on my grid. I'm using the totalCellComponent to format my data in certain columns properly as well. I want to declare another TableSummaryRow for another set of calculations. I can't seem to put the HTML tag there twice like so:

`        <TableSummaryRow
          totalCellComponent={StandardPriceSummaryCell}
        /> 
        <TableSummaryRow 
          totalCellComponent={AnotherCalculationSummaryCell}
        />
`

and I've tried to create a template on the tableBodyRows with getter = "tableFooterRows" but that only allows me to create a template on the bottom of the grid. I want the calculation to be a part of the grid as the last row, similar to how TableSummaryRow is implemented where you can define which column my calculation will go for the TableSummaryRow.

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

You can define a custom component as the TableSummaryRow's [totalRowComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-summary-row/#properties). In it you can duplicate `TotalRow` and pass additional properties to its children (to the `TotalCell` component). Here is an [example](https://codesandbox.io/s/suspicious-dubinsky-rm6yy?file=/demo.js).
If you have any further questions, let us know.
