### ISSUE TITLE
Could not find a declaration file for module '@devexpress/dx-grid-core' / '@devexpress/dx-chart-core'

### ISSUE THREAD

**Issue by igor-stecyura** [DevExpress/devextreme-reactive#2902]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
`TS7016: Could not find a declaration file for module '@devexpress/dx-grid-core'. 'C:/projects/WideOrbit/WOLongForm/WideOrbit.WOCentral.LFDR.Site/ClientApp/node_modules/@devexpress/dx-grid-core/dist/dx-grid-core.umd.js' implicitly has an 'any' type.   Try `npm install @types/devexpress__dx-grid-core` if it exists or add a new declaration (.d.ts) file containing `declare module '@devexpress/dx-grid-core';`
`

### Expected Behaviour
It compiles successfully.

### Steps to Reproduce
Install `@devexpress/dx-grid-core@2.6.3`

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment
 @devexpress/dx-grid-core: 2.6.3
 @devexpress/dx-react-core: 2.6.3
 @devexpress/dx-react-grid: 2.6.3
 @devexpress/dx-react-grid-material-ui: 2.6.3
  react: 16.9.0,
  react-dom: 16.9.0

**Comment by MaximKudriavtsev** [comment]
Hi @igor-stecyura,

Could you, please, provide us with an example where the issue is reproduced? In this case, we will be able to help you sooner. For example, you may update this [example](https://codesandbox.io/s/angry-feather-gu1wv?file=/src/demo.tsx).

**Comment by MaximKudriavtsev** [comment]
I have reproduced the issue in this [example](https://codesandbox.io/s/react-typescript-mfz68?file=/src/index.tsx).

**Comment by igor-stecyura** [comment]
Hi @MaximKudriavtsev , sorry for late response and thanks for your example!

**Comment by MaximKudriavtsev** [comment]
@igor-stecyura,

My example reproduced the issue with the dx-chart-core package.

Inside the `dx-grid-core` package, we keep only internal and non-documented functions and don't provide typescript definitions for it. It is not clear how you use the `dx-grid-core` package in your app. Please describe your use-case in more detail so I can research the problem.

**Comment by igor-stecyura** [comment]
Hi @MaximKudriavtsev , thanks for reply

I'm implementing custom TableSelection plugin and using a lot of utils from `react-grid-core` like 

```
import {
  isDataTableRow,
  isRowHighlighted,
  isSelectAllTableCell,
  isSelectTableCell,
  tableColumnsWithSelection
} from '@devexpress/dx-grid-core';
```

**Comment by MaximKudriavtsev** [comment]
@igor-stecyura,

Thank you for sharing your example. Regarding `dx-grid-core`, this behavior is by design. We don't provide `d.ts` files because these functions are private. They can be changed without any BC in the future.

As for your use-case, we will discuss the possibility of implementing it in the future.

**Comment by MaximKudriavtsev** [comment]
Hi @igor-stecyura,

We discussed the problem and decided to not add TypeScript definitions for our private code. This feature requires a significant amount of time and resources. We don't plan it at the moment.
