### ISSUE TITLE
How to override nested styles in Grid?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#2907]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is there any way to apply styling to the indented table rows? In my use case I want to 

1. Decrease the default indent pixels (I see it's at 24 per level) on the table row.
2. For every increase level of indent, make table row a darker color.

I was looking through the fundamentals guide here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/ and I see there are ways to customize the styling of the table. I'm able to customize the components seen on the grid through the `xxxComponents` attribute but I don't know how to override styling on indented rows.  For example, I'm using the `TableTreeColumn` and for my first use case, I'm trying to decrease the indent amount on the `TableTreeColumn`. I see in the DOM that I want to remove the margin-left on the `memo-indent-xxx` class to 0.

I tried to create the IndentComponent and apply the margin that way but that doesn't seem to work. 

Here is my attempt:

```

const tableStyles = theme => ({
  tableStriped: {
    '& tbody tr': {
      marginLeft: 0,
      backgroundColor: fade(theme.palette.primary.main, 0.15),
      // style the indented rows
    }
  },
  indent: {
    '& span': {
      marginLeft: 0
    }
    '& div': {
      marginRight: 0
    }
  }
})

const IndentComponentBase = ({classes, ...restProps}) => {
  console.log("props: ", restProps);
  return <TableTreeColumn.Indent {...restProps} className={classes.indent} />
}

const TableComponentBase = ({ classes, ...restProps }) => (
  <Table.Table
    {...restProps}
    className={classes.tableStriped}
  />
);


export const TableComponent = withStyles(tableStyles, { name: 'TableComponent' })(TableComponentBase);

export const IndentComponent = withStyles(tableStyles, { name: 'IndentComponent '})(IndentComponentBase);


const Grid = () => {
   ...
   <Table
       tableComponent={TableComponent}
   />
     <TableTreeColumn
          for="name"
          indentComponent={IndentComponent}
     />
}
```
Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

We don't provide the `className` property in `TableTreeColumn.Indent` component. For this reason, you can't customize this component the way you have tried. You can define your own component, based on our [code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-tree-indent.jsx). Here is an [example](https://codesandbox.io/s/elastic-villani-f0e7q?file=/demo.js).
If you have any further questions, feel free to contact us.
