### ISSUE TITLE
Conditional Cell Edits with DataTypeProviders

### ISSUE THREAD

**Issue by neilst** [DevExpress/devextreme-reactive#2911]
### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

We need to make use of a function to determine if a cell is editable.

```
<TableEditRow
	cellComponent={(props) => {
		if (props.column.allowEditing === false || (props.column.conditionalEdit && !props.column.conditionalEdit(props.row))) {
			const { editingEnabled, onValueChange, ...viewOnlyProps } = obj;
			return <Table.Cell {...viewOnlyProps} />;
		}

 <TableEditRow.Cell {...props} />;
/>

```

The issue is that with DataTypeProviders, the disabled prop is linked to the children prop that is passed to cellComponent. 

```

children:
$$typeof: Symbol(react.element)
key: null
props:
column: {name: "date", title: "Date", allowEditing: false, dataType: "date"}
**disabled: false**
onValueChange: ƒ (newValue)
row: {code: "eerg", type: {…}, date: "2020-05-25"}
value: "2020-05-25"
__proto__: Object
ref: null
type: ƒ editorComponent(params)
_owner: FiberNode {tag: 1, key: null, stateNode: TemplatePlaceholderBase, elementType: ƒ, type: ƒ, …}
_store: {validated: true}
_self: null
_source: null
__proto__: Object
colSpan: 1
column: {name: "date", title: "Date", allowEditing: false, dataType: "date"}
editingEnabled: true
onValueChange: ƒ (newValue)
row: {code: "eerg", type: {…}, date: "2020-05-25"}
style: undefined
tableColumn: {column: {…}, key: "Symbol(data)_date", type: Symbol(data), width: undefined, align: undefined, …}
tableRow: {row: {…}, rowId: 0, type: Symbol(edit), key: "Symbol(data)_0", height: undefined}
value: "2020-05-25"

```

Is there a way to replicate the `obj.column.allowEditing === false || (obj.column.conditionalEdit && !obj.column.conditionalEdit(obj.row))` logic so that it will apply to the DataTypeProvider props without having to iterate through the children here.

**Comment by LazyLahtak** [comment]
Hi @neilst,

DataTypeProvider's editorComponent provides the `disabled` value based on EditingState's [columnExtension](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/#editingstatecolumnextension) property. I suggest that you define this property using the `column.allowEditing` value.

Also, you can check `column.conditionalEdit` in DataTypeProvider. Here is an [example](https://codesandbox.io/s/focused-moore-t8eqj?file=/demo.js).

Does this solution meet your requirements?

**Comment by neilst** [comment]
Hi @LazyLahtak,

Thank you. the example you provided helped me solve the issue.
Are there any plans in the future to provide a native implementation for conditional editing, possibly on the `columnextensions`?

**Comment by neilst** [comment]
@LazyLahtak, can you confirm that https://github.com/DevExpress/devextreme-reactive/blob/3732635b55dd3e4cf54c790be0834c47c5e23af4/packages/dx-react-grid/src/types/data-type-provider/data-type-provider.types.ts#L16 is missing the `disabled` property on the type ?

**Comment by LazyLahtak** [comment]
@neilst,

For now, we do not plan to implement conditional editing. We will take this feature into account when planning further development. You can check our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed about our new features.

If you have any further questions, feel free to contact us.
