### ISSUE TITLE
Scheduler - create appointment with single click or custom button

### ISSUE THREAD

**Issue by nevadyzm** [DevExpress/devextreme-reactive#2912]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi!
Is it possible to add the "onClick" event to a custom Scheduler cell? I see the "onDoubleClick" in WeekView.TimeTableCellProps but can't see anything for a single click.
The user experience I'm looking for is to either allow creating new appointments using a single click OR have the user select a specific cell and then click on a custom button that will open new appointment page with time already set to the value that the user selected (similarly to how it works for doubleClick). 
Is either option supported?
Best Regards,
Michael

### Environment

- devextreme-reactive: 2.5.0
- react: 16.12.0
- browser: xxx
- bootstrap: 4.4.1
- react-bootstrap: none
- material-ui: 4.9.5

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you customize `timeTableCellComponent` and use its `onDoubleClick` event to create `onClick` event. here is an example: https://codesandbox.io/s/vigilant-blackwell-w265o?file=/demo.js

Does this solution suit you?

**Comment by nevadyzm** [comment]
Thank you so much, this is exactly what I was looking for!
