### ISSUE TITLE
Validations and Custom cells losing focus.

### ISSUE THREAD

**Issue by neilst** [DevExpress/devextreme-reactive#2913]
### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am aware of the various issues surrounding functions to create components with-in render, although it is still not clear on the correct approach (when not using Redux). I have previously used the work around found [here](https://github.com/DevExpress/devextreme-reactive/issues/496) and made use of the `createRendercomponent`. This does not appear to work with the example I try below.

I have taken the example [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#data-validation) and made some modification to illustrate roughly what I am looking for, you can find the fork [here](https://codesandbox.io/s/elastic-hoover-d3np9?file=/demo.js).

When you edit and type in the cell, the cell will lose focus.

**Comment by LazyLahtak** [comment]
Hi @neilst,

Your TableEditRow's `cellComponent` depends on the `errors` value. When you change this value, `cellComponent` is re-rendered. In our validation [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#data-validation) this component doesn't depend on any state variable.
I suggest that you save information about errors in `cellComponent`. Here is an [example](https://codesandbox.io/s/optimistic-silence-8ujs1).

Does this solution meet your requirements?
If no, could you clarify your scenario? Why do you need to pass the `errors` variable to TableEditRow's 'cellComponent'?

**Comment by neilst** [comment]
Hi @LazyLahtak,

Thanks for the help, the `onValueChange` will only return the current cells value. We would require validation across the current row that is being edited. The `onRowChangesChange` as used in the original example will give all current values for the row (including the edited values).

Is there another way to approach this using your example ?

**Comment by LazyLahtak** [comment]
@neilst,

I suggest that you use the [Context](https://reactjs.org/docs/context.html). Here is an updated [example](https://codesandbox.io/s/weathered-monad-ufluc?file=/demo.js).
Does this solution meet your requirements?

**Comment by neilst** [comment]
Thank you @LazyLahtak . This solution does meet our requirements.

**Comment by LazyLahtak** [comment]
You are welcome!
