### ISSUE TITLE
Hybrid filter of grid

### ISSUE THREAD

**Issue by Panepo** [DevExpress/devextreme-reactive#2914]
### I'm using ...

- [x] React Grid

### Description
(I search the issue but seen the related questions are locked: #2119 #2692 )

Hi there, I have two problems about implement a hybrid filter with selection and text input. [Here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-wzfet?file=/index.js)'s an demo project.

The first problem is it seems have some conflict with SearchState, while I remove SearchState and SearchPanel, all things work correctly.

The second problem I don't know why I can't reproduce at codesandbox. The problem description is the text input box of filter will lose focus while I typing.

very thanks

### Environment
- devextreme-reactive: 2.6.2
- react: 16.12.0
- browser: Firefox 74.0
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.11

**Comment by AryamnovEugeniy** [comment]
Hello,

`IntegratedFiltering` performs **both** Searching and Filtering. So, the predicate you pass to the `IntegratedFiltering` works with both Searching and Filtering. That is why all the rows are removed when you use Searching and everything works correctly without Searching. I suggest you either remove the predicate and `integratedFilteringColumnExtensions` or change the predicate. Here is an example where I modified the predicate a bit: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-d8fxn?file=/index.js.

Concerning your second issue. The most frequent cause of why an input may lose focus is when the input is customized and is created in the render method, for instance, as I've done here: https://codesandbox.io/s/nervous-jennings-feiz7?file=/demo.js. If that is the case in your application, I suggest to remove it from the render method (here is our [article](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods) on the subject).

Do these solutions meet your requirement?

**Comment by Panepo** [comment]
Hi @AryamnovEugeniy 

Thanks for the answer and the first problem is solved. 

The second problem seems like as you mentioned, while I remove `cellComponent={FilterCell}` and the problem disappears. The [project file](https://gist.github.com/Panepo/a763f97318f0b19f0c8bd37527a3d933) and demo file are similar but still don't know why it doesn't occurs at codesandbox. I am going to try another method to implement it.

thanks.

**Comment by AryamnovEugeniy** [comment]
Hello,

I reproduced your issue: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-715ju?file=/index.js.
The best solution is to not declare components inside render method - you can refer to our [article](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) on the subject.

If you have any other questions, feel free to ask them.

**Comment by Panepo** [comment]
Hi @AryamnovEugeniy 

Thanks a lot that all things are clear.

But if I declare `FilterCell` of your [demo project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-715ju?file=/index.js:1434-1444), how can I pass custom variables to `FilterCell`?

Thanks

**Comment by AryamnovEugeniy** [comment]
There are several ways to achieve this. The best one would be to use a state management library, such as [Redux](https://redux.js.org/). Another option is to wrap your component inside React's `useCallback`.
In other words, your component must not be **recreated** on every rerender, it should be **updated**.
Refer to our article on performance optimization: https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/.
