### ISSUE TITLE
Filtering not reordering paging

### ISSUE THREAD

**Issue by lindomar-oliveira** [DevExpress/devextreme-reactive#2915]
## Issue type
[x] documentation

**I have a table with several rows that are paginated, but when I apply a filter the results are divided by the pages. How to make the results stay together.**

**Comment by AryamnovEugeniy** [comment]
Hello,

It works correctly in this demo: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/
Make sure that you place the `IntegratedPaging` after the `IntegratedFiltering` plugin (see our [article](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order) on plugin order).

Let me know if this solution meets your requirements.

**Comment by lindomar-oliveira** [comment]
Thanks! @AryamnovEugeniy. **Worked perfectly.**
