### ISSUE TITLE
Charts not rendered in hidden divs

### ISSUE THREAD

**Issue by cemeai** [DevExpress/devextreme-reactive#2918]
I am using a Carosel from bootstrap4 to add 2 different bar charts, but the second one is not rendering because it starts in a hidden div, is there a way to trigger the render manually. I know some other plugins have this

**Comment by AryamnovEugeniy** [comment]
Hello,

We have already had a similar issue with Grid. The solution was to use `key` to rerender the component. Here is that issue: https://github.com/DevExpress/devextreme-reactive/issues/2550#issuecomment-604409085

Let me know, if this is helpful in your scenario.
