### ISSUE TITLE
Composite key in grid

### ISSUE THREAD

**Issue by lucas-bustos** [DevExpress/devextreme-reactive#2922]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

 Hi. I am using selection in my grid and I have composite key (two colums are key in my database), I need to select a row and send to my database those two IDs selected ( each colum has a diferent name), as follows: [column one, column two]

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/devextreme-react-grid-for-material-ui-v79bl?file=/index.js&gt;
in this example i have two keys/IDs sex and name, 
I would like my select variable to have the following: [1,robert]

### Environment

- devextreme-reactive: 2.6.0
- react: 16.11
- browser: chrome.
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.8.

**Comment by LazyLahtak** [comment]
Hi @lucas-bustos,

If you want to get information about selected rows, you can use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/). You can get an array of ids of selected rows (a row's id is an index) in the function you passed into SelectionState's [onSelectionChange](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/#properties) property. 
Here is an [example](https://codesandbox.io/s/late-platform-vihhu?file=/demo.js).

If you have any further questions, let us know.
