### ISSUE TITLE
Retrieve all cell values of a row with onRowChangesChange

### ISSUE THREAD

**Issue by neilst** [DevExpress/devextreme-reactive#2923]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Based on the example given as part of [this](https://github.com/DevExpress/devextreme-reactive/issues/2913#issuecomment-635970318) support question, is it possible to retrieve all the cell values for the row with-in validate function. I would like to have both edited and unedited values and would also like to avoid using the original rows array that was passed in and get it directly from the grid.

**Comment by LazyLahtak** [comment]
Hi @neilst.

Could you please clarify your scenario?
It would help us understand your scenario better if you describe why you wish to not use original rows for your validation function. What is the purpose to pass these rows in the function?
