### ISSUE TITLE
Attempting to set default column width percentages errors out for TableColumnResizing

### ISSUE THREAD

**Issue by thejonmonte** [DevExpress/devextreme-reactive#2926]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi, I'm attempting to utilize percentages for the defaultColumnWidth property of TableColumnResizing (in uncontrolled mode). I've navigated through most of the issues relating to this, and they all end with statements about the ability to now utilize CSS-accepted units for widths.

But when trying to set width percentages, I keep getting this error:
<img width="953" alt="Column Width Issue" src="https://user-images.githubusercontent.com/42880566/84193457-547ff900-aa50-11ea-8ee0-bd96badfd723.png">

I'm defining defaultColumnWidths as
```
const defaultColumnWidths = [
    { columnName: "id", width: "25%" },
    { columnName: "name", width: "25%" },
    { columnName: "text", width: "50%" }
];
```

and passing it in to a child component Grid Table as so:
```
...
<Table
     tableComponent={TableComponent}
     rowComponent={Row}
     cellComponent={Cell}
/>
<TableColumnResizing defaultColumnWidths={props.defaultColumnWidths} />
...
```

Using just plain numbers instead of strings works, but I'd rather be able to use strings for percentages. What's the solution to this?

### Environment

- devextreme-reactive: 2.6.3
- react: 16.6.0
- browser: xxx
- bootstrap: 4.5.0
- react-bootstrap: none
- material-ui: none

**Comment by thejonmonte** [comment]
Actually, it seems that setting the `columnWidths` property of `TableColumnResizing` to an empty array as so
```
...
<TableColumnResizing defaultColumnWidths={props.defaultColumnWidths} columnWidths={[]} />
...
```
solved the problem. Is there a reason why this workaround is specific to strings only and not numbers as well? The [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#resizing-modes) for the uncontrolled mode of `TableColumnResizing` also states that the `defaultColumnWidths` property is only required.

**Comment by LazyLahtak** [comment]
Hi @thejonmonte,

A percentage value can be used to specify a column width only in `nextColumn` resizing mode (see: [Properties](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#properties)). Please refer to this [example](https://codesandbox.io/s/staging-wildflower-q7i2p).

If you have any further questions, feel free to contact us.
