### ISSUE TITLE
dx-grid Expand all groups?

### ISSUE THREAD

**Issue by kyle-ssg** [DevExpress/devextreme-reactive#2928]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Duplicate of https://github.com/DevExpress/devextreme-reactive/issues/756, the comment in this bug does not answer the question. 

I want to be able to expand all groups by default however it seems in order to be able to do that I'd need to know what all the grouped keys are if I'm to used the "expandedGroups" property of GroupingState.

The code example linked in the previous example does show usage of this however simply expands 1 group which is trivial in comparison to setting all.
https://codesandbox.io/s/o6o622k35

If I can get a hold of all of the groups (including a nested group scenario) then setting this would be straight forward, is there a way to do this or another approach to expanding all groups?

**Comment by MaximKudriavtsev** [comment]
Hi @kyle-ssg,

Unfortunately, we don't have another workaround except for the one described in the [original issue](https://github.com/DevExpress/devextreme-reactive/issues/756#issuecomment-454685780).

**Comment by kyle-ssg** [comment]
@MaximKudriavtsev, thanks, that answer would be fine except there's no indication of how to get all of the possible group expansions. 

For example if I have nested groups, how can I retrieve all of the possible list of available groups to expand?
  
e.g. I group a list of items by town and county. I'd want to expand

["Come County", "SomeCounty|Division A" , "SomeCounty|Division B"]

**Comment by MaximKudriavtsev** [comment]
@kyle-ssg,

The simplest way to find information about group rows is to create a custom plugin with a `row` [getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). You can either add your custom plugin or replace our `IntegratedGrouping` with your custom one.

I've created an [example](https://codesandbox.io/s/focused-river-scolo?file=/demo.js) with the group expanding functionality. In it, you can expand only visible rows without any hidden items. Expanding all group items is a more difficult task. In this case, you will need to override the `IntegratedGrouping` plugin.
