### ISSUE TITLE
dx-grid show total items within a group on the TableGroupRow

### ISSUE THREAD

**Issue by kyle-ssg** [DevExpress/devextreme-reactive#2929]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
![image](https://user-images.githubusercontent.com/8608314/84263285-21546d00-ab17-11ea-9ff0-c5db5b9492be.png)

I wish to simply show the count of rows directly under a group. It seems that similarly to https://github.com/DevExpress/devextreme-reactive/issues/2928, in order to do this sort of thing I'd need the entire state of the groups in advance. 

Is there a way to achieve this that I'm missing? The documentation doesn't seem to indicate any sort of functionality around this.

**Comment by LazyLahtak** [comment]
Hi @kyle-ssg.

To display a summary in a group row, use the `SummaryState` plugin's `groupItems` property (see. [Properties](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/summary-state/#properties)). Please follow this [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/summary-row/#basic-setup).

If you have any further questions, let us know.

**Comment by kyle-ssg** [comment]
@LazyLahtak ok but does this give me access to the group rows so that I can create a summary?
