### ISSUE TITLE
Column Pinning

### ISSUE THREAD

**Issue by aaronsalud** [DevExpress/devextreme-reactive#293]
Are there any plans adding in a column pinning feature similar to the ui-grid?
http://ui-grid.info/docs/#/tutorial/203_pinning

**Comment by kvet** [comment]
Hi,
 
Thank you for your suggestion. We are planning to implement column pinning in future versions.

**Comment by madhan-dhamodaran** [comment]
Hi, 
Any idea when we would be able to get to use this feature. 

Kindly advise. 

Thanks,
Madhan

**Comment by johnoscott** [comment]
Waiting for this enhancement. Is it on the roadmap ?

**Comment by datadidit** [comment]
I am as well just looking for any sort of update? Could also get this working with a sychronized multigrid solution. Does anyone have an example of that similar to react-virtualized example?

**Comment by kvet** [comment]
Hi,

This feature is on our roadmap. We plan to implement it in the first half of the year. For now, however, we cannot provide an example, I am afraid.

**Comment by datadidit** [comment]
@kvet Thanks for the feedback looking forward to the release of it.

**Comment by SergeyAlexeev** [comment]
Hi, 

We started working on this. We'll update this thread as soon as we have any news.

**Comment by vijayvmenon** [comment]
Hi,

Just wanted to see if there is any update on this feature and when it would be released?

**Comment by SergeyAlexeev** [comment]
Hi,

The related [PR](https://github.com/DevExpress/devextreme-reactive/pull/1305) is ready. Currently, we are reviewing the changes and are testing the new functionality. If we don't find serious bugs, we'll release this version with the next minor update, 1.8.0, I suppose.

**Comment by vijayvmenon** [comment]
Thank you for the update !!

**Comment by SergeyAlexeev** [comment]
We've released the [1.8.0-beta.1](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#180-beta1-2018-09-07) version that contains the described feature.

You can install it with the next tag:

npm i --save @devexpress/dx-react-core@next @devexpress/dx-react-grid@next
npm i --save @devexpress/dx-react-grid-bootstrap3@next
npm i --save @devexpress/dx-react-grid-bootstrap4@next
npm i --save @devexpress/dx-react-grid-material-ui@next

See the related [guide](https://devexpress.github.io/devextreme-reactive/@next/react/grid/docs/guides/fixed-columns/) as well.

**Comment by vijayvmenon** [comment]
Thanks a lot . That's awesome! Appreciate all the work you are doing for this!

**Comment by Krijovnick** [comment]
We've released the [1.8.0](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.8.0) version containing described changes.
