### ISSUE TITLE
Weird loading issue with images in rows, using ReactGrid: VirtualTable

### ISSUE THREAD

**Issue by natenrb9** [DevExpress/devextreme-reactive#2931]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid

### Description
First off, thank you for your product. It is amazing! 

Issue:
I have searched high and low for a solution and figured I would see if you guys could be of assistance. We include thumbnails in each row, and are making use of VirtualTable. When you scroll the row text data pops in perfectly, BUT the image does not load until you STOP scrolling, while scrolling it is just a blank spot where the thumbnail will load. Any ideas on why it would do this? Do you have any examples of a long list table that uses images and also VirtualTable?

Any help would be much appreciated, thanks!

**Comment by LazyLahtak** [comment]
Hi @natenrb9,

Thank you for your interest in our product!
Could you please share a runnable project (for example, in [CodeSandbox](https://codesandbox.io/s/lqx8j))? It will help us solve this issue.
