### ISSUE TITLE
Lazy loading with remote searching

### ISSUE THREAD

**Issue by plevamatus** [DevExpress/devextreme-reactive#2932]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I've added searching feature into your Lazy loading (Row cache) demo. Sometimes grid is not scrolled properly and currently loaded data are not visible.

### Steps to Reproduce

- open an example in CodeSample [https://codesandbox.io/s/sleepy-silence-8jlgv](https://codesandbox.io/s/sleepy-silence-8jlgv)
- write "asia" into search box
- scroll down to load more pages
- remove last character from search box

### Screenshots

![image](https://user-images.githubusercontent.com/11454499/84350035-df7c0300-abb8-11ea-8f96-39ee0925503b.png)

### Environment

- devextreme-reactive: 2.6.3
- react: 16.13.1
- browser: chrome 83.0.4103.97
- material-ui: 4.10.1

**Comment by LazyLahtak** [comment]
Hi @plevamatus ,

Thank you for reporting this problem. We will fix this soon.
