### ISSUE TITLE
The content of DetailRow horizontal centered while scrolling

### ISSUE THREAD

**Issue by Panepo** [DevExpress/devextreme-reactive#2935]
### I'm using ...

- [x] React Grid

### Description
(I search the issue but seen that there are not any related questions.)

Hi there, I am thinking if it possible to add a feature that make the content of DetailRow horizontal centered while scrolling? Just like this [demo project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-wzfet), but I can't make the content centered very well.

It would be useful for a large table with many columns.
Very thanks

**Comment by LazyLahtak** [comment]
Hi @Panepo.

I suggest that you calculate the `left` value based on the container width. Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-6o9em?file=/index.js).

We are not planning to implement this functionality in the near future. We will take this feature into account when planning further development. You can check our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed about our new features.

If you have any further questions, feel free to contact us.
