### ISSUE TITLE
Possible inconsistency between property names: (Scheduler > AppointmentForm > ResourceEditor)

### ISSUE THREAD

**Issue by acollazo25** [DevExpress/devextreme-reactive#2937]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Scheduler

### Current Behaviour

I think there is an inconsistency between the definition and the Resource Editor template.

The property named **resources** on https://github.com/DevExpress/devextreme-reactive/blob/743fbd76c48b0843355ad855cf22dd9b96bda873/packages/dx-react-scheduler/src/types/editing/appointment-form.types.ts#L182

It is named as **resource** on https://github.com/DevExpress/devextreme-reactive/blob/743fbd76c48b0843355ad855cf22dd9b96bda873/packages/dx-react-scheduler-material-ui/src/templates/appointment-form/basic/resource-editor.jsx#L124

What causes the exception **TypeError: Cannot read property 'map' of undefined** on the line https://github.com/DevExpress/devextreme-reactive/blob/743fbd76c48b0843355ad855cf22dd9b96bda873/packages/dx-react-scheduler-material-ui/src/templates/appointment-form/basic/resource-editor.jsx#L107

### Expected Behaviour
I think both properties must match in name, if I am in error I would like to know. Thank you.

### Steps to Reproduce

1. Implement the **AppointmentForm** basic layout
```js
<AppointmentForm
   basicLayoutComponent={BasicLayout}
/>
```
2. Use the **ResourceEditor** component in **BasicLayoutForm**
```js
<ResourceEditor
  readOnly={readOnly}
  appointmentResources={appointmentResources}
  resources={resources}
  onResourceChange={() => null}
/>
```

#### devextreme-reactive
- "@devexpress/dx-react-core": "^2.6.3",
- "@devexpress/dx-react-scheduler": "^2.6.3",
- "@devexpress/dx-react-scheduler-material-ui": "^2.6.3",

#### react
- "react": "^16.12.0"

#### material-ui
- "@material-ui/core": "^4.9.3"

**Comment by AryamnovEugeniy** [comment]
Hello,

Thank you for your interest in our product!
In our implementation of the `AppointmentForm` we create several Resource Editors, each for every specified resource in the `resources` property. Here is how we create Resource Editors in the `BasicLayout`:
```
resources.map(resource => (
  <React.Fragment key={resource.fieldName}>
    <Label
      text={resource.title}
      type={TITLE}
      className={classes.labelWithMargins}
    />
    <ResourceEditor
      readOnly={readOnly}
      resource={resource}
      appointmentResources={appointmentResources}
      onResourceChange={changeResources}
    />
  </React.Fragment>
))}
```

And from that point everything seems to be correct. We have several Resource Editors and pass a single resource to each of them.

If you have any other question, we will be happy to assist you.
