### ISSUE TITLE
How to manage long sentences in table 

### ISSUE THREAD

**Issue by Gauthamjm007** [DevExpress/devextreme-reactive#2938]
![SWATI_Swavalamban_Technology_Interface](https://user-images.githubusercontent.com/26291295/84563325-3c71e780-ad78-11ea-8c2a-8a7d2db70e61.png)

Can anyone help me how we can bring sentences to the next line if they are long in React Grid Tables ?

**Comment by LazyLahtak** [comment]
Hi @Gauthamjm007,

To enable multiline cells, you need to use a Table plugin's [columnExtenstions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#properties) property. Please follow this [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#multiline-cells).

If you have any further questions, let us know.
