### ISSUE TITLE
Ability to Define Multiple Appointment Organization under Same Cell on Week View

### ISSUE THREAD

**Issue by flavioribeiro** [DevExpress/devextreme-reactive#2940]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello Team. I'm experimenting with the Scheduler library to see if it fits the needs of one of our projects. I want to use the Scheduler to represent a 24/7 linear channel programming, with a minute granularity on the WeekView. However, I didn't want the `cellDuration` to be `1` as this would be pretty heavy to render. 

Ultimately, I wanted to keep the `cellDuration` on the 10-15min scale but wanted to be able to place multiple appointments under the same cell without getting them to overlap in time and shift on its width.  When I try to do it now, I get something like this:

![image](https://user-images.githubusercontent.com/244265/84853149-8b47a780-b02c-11ea-812e-2a81c5e9655c.png)

I was looking at doing something like this:

![image](https://user-images.githubusercontent.com/244265/84853309-e7123080-b02c-11ea-94a6-26e20933d656.png)

Note that I don't care if the times/details of the appointment are not showing up there. If the operator wants to know more he/she will click on it and get a detailed view. I'm able to create custom components but wanted to get some input on whether I should try to change the `containerComponent` on the `Appointments` object or if I should go via the `WeekView` object and change something there.

Any thoughts?

### Environment
```
    "@devexpress/dx-react-core": "^2.6.3",
    "@devexpress/dx-react-scheduler": "^2.6.3",
    "@devexpress/dx-react-scheduler-material-ui": "^2.6.3",
   "@types/node": "13.7.1",
    "@types/react": "16.9.35",
    "@types/react-dom": "16.9.8",
    "@types/react-redux": "7.1.7",
    "@types/react-router-dom": "5.1.3",
    "@types/redux-immutable-state-invariant": "2.1.1",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "@typescript-eslint/parser": "2.19.2",
```

**Comment by AryamnovEugeniy** [comment]
Hello!

That would be quite a difficult task. This functionality cannot be customized in the React Scheduler. The only way this can be achieved is to create your own Appointments plugin (it can be based on our [implementation](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler/src/plugins/appointments.tsx)). What you would need in this case is to sort appointments from `timeTableAppointments` and, possibly, `allDayAppointments` getters and to find those whose `startDates` are roughly the same and move them according to your needs.
You may also find useful the guide on how to implement custom plugins: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/.

If you have any other questions, we will be happy to answer them!

**Comment by AryamnovEugeniy** [comment]
I forgot to mention one more point. We will enhance rendering for overlapped appointments very soon (here is [Pull Request](https://github.com/DevExpress/devextreme-reactive/pull/2889)). Here is how it will look like:
![image](https://user-images.githubusercontent.com/51905811/85109840-a546dd00-b21a-11ea-9924-ac1f9e9c4838.png)

Maybe this will suit your requirements?

**Comment by flavioribeiro** [comment]
hey @AryamnovEugeniy thanks for the detailed response. This enhancement will definitely improve the experience. In fact, if I find a way to customize the Appointment to keep the same `width` for all the appointments, we should get pretty close to what I tried to do. Any tips on customizing it to ignore the calculation of the width there?
