### ISSUE TITLE
How to change Tooltip background color

### ISSUE THREAD

**Issue by jbournonville** [DevExpress/devextreme-reactive#2941]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description
Is there a way to change background color of a chart tooltip ?
I've tried to use style, but nothing change :
```jsx
import {ArgumentAxis, BarSeries, Chart, Tooltip, ValueAxis} from '@devexpress/dx-react-chart-material-ui';
import {EventTracker, Stack, ValueScale} from '@devexpress/dx-react-chart';
...
<EventTracker />
<Tooltip
    style={{backgroundColor:'#585858'}}
    onTargetItemChange={changeToolTip}
    contentComponent={TooltipContent}
    targetItem={toolTipTarget}
/>
...
```
### Environment
- react: 16.13.1
- material-ui: 4.10.2

**Comment by AryamnovEugeniy** [comment]
Hello,

You may customize Tooltip's [Sheet](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/tooltip/#tooltipsheetprops) and [Arrow](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/tooltip/#tooltiparrowprops) components. Here is an example: https://codesandbox.io/s/silent-bird-e7txo?file=/demo.js

If you have any other questions, feel free to ask them.
