### ISSUE TITLE
Need Grid sorting to push null values to last

### ISSUE THREAD

**Issue by del-naz** [DevExpress/devextreme-reactive#2942]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am using IntegratedSorting and providing a compare function in columnExtensions. 
I would like null values in the column to appear at the bottom regardless of the sorting direction..
The following compare function works for descending order : 
(a, b) => a === null ? -1 : (a < b) ? -1 : (a > b) ? 1 : 0

In order to make it work for ascending order I need the compare function to provide the direction of sorting, which is not.

Can you suggest a solution?

### Environment

- devextreme-reactive: 2.5.1
- react: ^16.12.0
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: ^4.5.2

**Comment by LazyLahtak** [comment]
Hi @del-naz.

I suggest that you create a custom [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/). For more information on how to do this, refer to our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
In this custom Plugin, you can use [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) to get `rows` and `sorting` values passed from `Grid` and `SortingState` plugins through Getters. Thus, you will be able to move rows with empty values to the end.
Here is an [example](https://codesandbox.io/s/zen-pasteur-tqeqd).

If you have any further questions, feel free to contact us.
