### ISSUE TITLE
Adding unlockEditingNewRow prop for TableEditRow

### ISSUE THREAD

**Issue by stasyaner** [DevExpress/devextreme-reactive#2943]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello. Thank you for your awesome Advanced Grid module. 
I have a feature request. For me it looks strange that when I add a new row, the columns that I restricted editing of in the EditingState.columnExtensions prop are not editable. So they stay empty. The only solution I could come up with was set some default values for the non-editable columns via EditingState.onAddedRowsChange prop. But that doesn't suit me. As I want full edit mode.
My apologies if I missed some valuable workaround, as your module is so huge and complicated that sometimes it happens for me.
So, I suggest an unlockEditingNewRow prop for TableEditRow. So, when it's set TableEditRow would ignore EditingState.columnExtensions setting for newly added rows and let all of its columns be editable.
I think, considering [this file](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-edit-row.tsx), the change would look like this:
```tsx
const changedRow = isNew
    ? row
    : { ...row, ...getRowChange(rowChanges, rowId!) };

const value = getCellValue(changedRow, columnName);
const onValueChange = (newValue: any) => {
    const changeArgs = {
        rowId,
        change: createRowChange(changedRow, newValue, columnName),
    };
    if (isNew) {
        changeAddedRow(changeArgs);
    } else {
        changeRow(changeArgs);
    }
};
// change here
let editingEnabled = isColumnEditingEnabled(columnName);
if (isNew && unlockEditingNewRow) editingEnabled = true;
// change here
return (
    <TemplatePlaceholder
```

Let me know your thoughts. And thank you for your time.
Thank you.

**Comment by LazyLahtak** [comment]
Hi @stasyaner,

Thank you for your interest in our product!
I suggest that you customize TableEditRow plugin's [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-row/#tableeditrowcellprops). In the component you need to pass `editingEnabled: true`, if `tableRow.type` is `TableEditRow.ADDED_ROW_TYPE`.
Here is an [example](https://codesandbox.io/s/friendly-grothendieck-t5myv?file=/demo.js).

Does this solution meet your requirements?

**Comment by LazyLahtak** [comment]
You are welcome!
