### ISSUE TITLE
Can't Dynamically Update BarSeries with .map() | Cannot read property 'argument-domain' of undefined

### ISSUE THREAD

**Issue by samfromaway** [DevExpress/devextreme-reactive#2946]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x ] React Chart
- [ ] React Scheduler

### Current Behaviour
The idea is that the user can add and remove categories dynamically in the app and the changes are reflected on the legend and the chart itself.

I want to dynamically update the BarSeries component with .map() but it throws and error:
Cannot read property 'argument-domain' of undefined 

I tried it with a function component there I can remove a component but can't add additional.

And with a class component I get another error:
If I remove a category: Cannot read property 'map' of undefined
If I add a category: Cannot read property 'scaleName' of undefined

I tried the exact same environment with another chart plugin for react and it worked, so I think it has to do with DevExpress Chart for react itself.

### Expected Behaviour
That the chart dynamically updates the Bar component.

### Steps to Reproduce
Fork https://github.com/samfromaway/ChartIssue01   and click the buttons on each chart to reproduce the error. The button ad a hardcoded new array of categories to simulate how a user would add or remove a category on the app.

### Environment
package.json

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@devexpress/dx-react-chart": "^2.6.3",
    "@devexpress/dx-react-chart-material-ui": "^2.6.3",
    "@devexpress/dx-react-core": "^2.6.3",
    "@material-ui/core": "^4.10.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

Thanks for the help
Sam

**Comment by MaximKudriavtsev** [comment]
Hi @samfromaway,

We've already had a [similar issue](https://github.com/DevExpress/devextreme-reactive/issues/2947#issuecomment-646500351). I've updated your [example](https://codesandbox.io/s/charming-glade-vkchw?file=/chart2.jsx) accordingly.

**Comment by samfromaway** [comment]
Perfect, thanks a lot :D
