### ISSUE TITLE
Version 2.6.3 Cannot read property 'scaleName'

### ISSUE THREAD

**Issue by DavidHenri008** [DevExpress/devextreme-reactive#2947]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour

I am getting an error with version 2.6.3, however, it works with 2.6.2.

Cannot read property 'scaleName' of undefined.

### Expected Behaviour

Should work with @devexpress/dx-react-chart 2.6.3 as it does with 2.6.2.

### Steps to Reproduce

1) Create chart with one value axis, 
2) Add another series that uses the same value axis

https://codesandbox.io/s/pensive-glitter-07zyp?file=/demo.js

### Environment

- devextreme-reactive: 2.6.3
- react: 16.13.1
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @DavidHenri008,

We recommend you wrap all custom plugin structures in our [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) component. This is necessary to keep our internal state system up to date.

```jsx
<Plugin name="custom-name">
  ...
  {/* Custom plugins structure */}
  ...
</Plugin>
```
I've updated your [example](https://codesandbox.io/s/young-snowflake-bvtrx) accordingly.
