### ISSUE TITLE
'Grid' cannot be used as a JSX component

### ISSUE THREAD

**Issue by klubis** [DevExpress/devextreme-reactive#2948]
### I'm using ...

- [x] React Grid

### Description

'Grid' cannot be used as a JSX component.
  Its element type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> | Component<...>' is not a valid JSX element.
    Type 'Component<GridProps, any, any>' is not assignable to type 'Element | ElementClass'.
      Type 'Component<GridProps, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'ReactNode' is not assignable to type 'Element'.
            Type 'string' is not assignable to type 'Element'.ts(2786)

`
import * as React from 'react';

import {
  GroupingState,
  IntegratedGrouping,
} from '@devexpress/dx-react-grid';
import {
  Grid,
  Table,
  TableHeaderRow,
  TableGroupRow,
} from '@devexpress/dx-react-grid-bootstrap3';

import { generateRows } from '../../../demo-data/generator';

export default () => {
  const [columns] = useState([
    { name: 'name', title: 'Name' },
    { name: 'gender', title: 'Gender' },
    { name: 'city', title: 'City' },
    { name: 'car', title: 'Car' },
  ]);
  const [rows] = useState(generateRows({ length: 8 }));

  return (
    <div>
      <Grid
        rows={rows}
        columns={columns}
      >
        <GroupingState
          grouping={[{ columnName: 'city' }]}
        />
        <IntegratedGrouping />
        <Table />
        <TableHeaderRow />
        <TableGroupRow />
      </Grid>
    </div>
  );
};

`

### Environment

  "dependencies": {
    "@devexpress/dx-react-core": "^2.6.3",
    "@devexpress/dx-react-grid": "^2.6.3",
    "@devexpress/dx-react-grid-bootstrap3": "^2.6.3",
    "@devexpress/dx-react-grid-bootstrap4": "^2.6.3",
    "@devexpress/dx-react-grid-material-ui": "^2.6.3",
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/spfx-controls-react": "1.17.0",
    "@types/axios": "^0.14.0",
    "@types/jest": "24.0.12",
    "@types/jquery.soap": "^1.7.0",
    "@types/node": "11.13.8",
    "@types/react": "16.8.15",
    "@types/react-dom": "16.8.4",
    "@uifabric/fluent-theme": "^0.16.7",
    "@uifabric/react-hooks": "^7.4.6",
    "axios": "^0.19.2",
    "jquery.soap": "^1.7.3",
    "office-ui-fabric-react": "^6.174.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.0",
    "typescript": "3.4.5"
  },

**Comment by LazyLahtak** [comment]
Hi @klubis,

I couldn't reproduce your error. Could you please send us an a workable project (for example, use [CodeSandbox](https://codesandbox.io/s/heuristic-sara-64bk1?file=/demo.js)). It will help us solve this issue.
Also, we have a demo with TypeScript: [React Grid - TypeScript Support](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/typescript/). This may be useful for you - please refer to it.
