### ISSUE TITLE
How to override localization in Date Navigator

### ISSUE THREAD

**Issue by KazeIU** [DevExpress/devextreme-reactive#2949]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I need to have a custom localized DateNavigator component popup calendar in Japanese. I need to be able to customize localization in the DateNavigator calendar. However, I can't figure this out after looking through the docs and playing around with the code in this [sandbox](https://codesandbox.io/s/mystifying-gareth-ix53s?file=/demo.js). 

Localization in Japanese adds this character 日 after each day. For example,  1日, 2日, 3日, I would like to be able to remove these characters. 

Any direction or help concerning this issue would be greatly appreciated. Thank you!

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

Currently, we don't have such a public API to customize this part of the `DateNavigator` plugin. But you can use our private API, though. The easiest way is to customize `DateNavigator`'s `calendarComponent`. And to override its `formatDate` function. Here is an example: https://codesandbox.io/s/beautiful-water-1xdom?file=/demo.js.
