### ISSUE TITLE
How can i prevent entering multitask for same time?

### ISSUE THREAD

**Issue by muserrefakillibaykus** [DevExpress/devextreme-reactive#2950]
For React Scheduler

I want only 1 task to enter in 1 hour. Is it possible?

Also, Is this scheduler available for responsive?

**Comment by AryamnovEugeniy** [comment]
Hello,

We do not have such functionality out of the box. But it is possible to create a custom [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) (see our [article](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) on the subject). This custom plugin should override `onDoubleClick` event in the `cell` [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/) (and in `allDayPanelCell` `Template` if you use the `AllDayPanel` plugin). Before firing `onDoubleClick` it is necessary to check whether the cell is already occupied. To do that, you need to iterate through `timeTableAppointments` (`allDayAppointments` in case of `allDayPanelCell`). You can get these appointments through [TemplateConnector](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template-connector/). If there isn't any appointments in the cell you can fire `onDoubleClick`. Here is an example of this approach in action: https://codesandbox.io/s/cranky-booth-p1gw7?file=/demo.js.
If you use grouping, apart from the dates you should check appointment's groups as well.

One more point: do not forget about plugin order. It affects the way plugins interact with each other. In this case, your custom plugin should be after `View` plugins but before the `AppointmentForm`.

Does this solution suit you requirements?

**Comment by muserrefakillibaykus** [comment]
That's great. Thank you so much!

**Comment by AryamnovEugeniy** [comment]
You are welcome!
