### ISSUE TITLE
Grid Selection - selection.includes is not a function

### ISSUE THREAD

**Issue by plevamatus** [DevExpress/devextreme-reactive#2952]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm trying to change row selection on button click, but when I call setSelection, error message "selection.includes is not a function" appears.

### Steps to Reproduce

- open Selection example in CodeSample [https://codesandbox.io/s/currying-http-o1dus](https://codesandbox.io/s/currying-http-o1dus)
- click TEST button

### Screenshots

![image](https://user-images.githubusercontent.com/11454499/85113025-eb9a3d00-b216-11ea-8943-1bacefcdf0a7.png)

### Environment

- devextreme-reactive: 2.6.3
- react: 16.13.1
- browser: chrome 83.0.4103.106
- material-ui: 4.9.14

**Comment by AryamnovEugeniy** [comment]
Hello,

I found an error in your code. It is on line 29: `Grid`'s [selection](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/selection-state/#properties) accepts an array, not a number. If you change `onClick={() => setSelection(2)}` to `onClick={() => setSelection([2])}` everything will work correctly.

**Comment by plevamatus** [comment]
Hello,
you are right, my fault. Thanks for advice.
