### ISSUE TITLE
Grid data editing: Data insert form at the bottom of the list.

### ISSUE THREAD

**Issue by dalborgo** [DevExpress/devextreme-reactive#2959]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is there a way to get the insert form at the bottom of the list?

https://codesandbox.io/s/hupde
In this example when I press "NEW" the insert form appears at the top of the list. Is it possible to get the insert form at the bottom?

Thank you.

### Environment

- devextreme-reactive: 2.6.3
- react: 16.13.1
- browser: Chrome
- material-ui: yes

**Comment by AryamnovEugeniy** [comment]
Hello!

You can create your own plugin that will place the new rows at the end of the table (here is our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) on custom plugin development). And here I made a small example: https://codesandbox.io/s/gracious-shockley-ey9jk?file=/demo.js
In my example I created a plugin, `AddedRow`, which removes the first N rows from `tableBodyRows` Getter and places them at the end (where N is the number of added rows). 

If you have any other questions, we will be happy to assist you.

**Comment by dalborgo** [comment]
Thank you so much!

I don't know the best way to remove the "no data" row if I add the new row as first element.

Can you help me?

**Comment by AryamnovEugeniy** [comment]
I'm happy that it helped!
