### ISSUE TITLE
Grid - Remove a blank row between a custom header and a table on exporting

### ISSUE THREAD

**Issue by sometimesElen** [DevExpress/devextreme-reactive#2960]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Currently, GridExporter adds a blank row between the customizeHeader part and the main table. It requires a complex workaround if you wish to remove it. I suggest that we do not add it out of the box. If you need it, you can easily add it inside the customizeHeader.

**Comment by markusbellus** [comment]
Thank you for raising this as an issue. Changing this would help us a lot.

**Comment by MaximKudriavtsev** [comment]
Hi @markusbellus,

We have released the 2.7.0 version of [DevExtreme Reactive Grid](https://devexpress.github.io/devextreme-reactive/react/grid/) with these changes.

**Comment by markusbellus** [comment]
Awesome thanks for the quick turnaround!
