### ISSUE TITLE
How to auto select children checkboxes upon selecting parents for react tree ?

### ISSUE THREAD

**Issue by ladynsnoopy** [DevExpress/devextreme-reactive#2962]
- [ x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I am implementing a tree data and with selection checkboxes. Is there any way that I can auto select a child row's checkbox when the parent rows are selected? Appreciate any suggestions :)

### Environment

- devexpress/dx-react-grid": "^2.6.3"
- react:  "^16.13.1"
- browser: xxx
- bootstrap: none
- react-bootstrap: none
-material-ui/core": "^4.10.2"

**Comment by LazyLahtak** [comment]
Hi @ladynsnoopy,

I suggest that you use the [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode) for selection. You could find which row was selected/unselected, find all children, and select/unselect them. Here is an [example](https://codesandbox.io/s/crazy-gagarin-qd03r?file=/demo.js).

If you have any further questions, feel free to contact us.
