### ISSUE TITLE
Typescript error with rowComponent custom styling

### ISSUE THREAD

**Issue by KLagdani** [DevExpress/devextreme-reactive#2964]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

I have the following grid with rowComponent customization:
```
<Grid rows={rows} columns={columns} getRowId={getRowId}>
          <SortingState defaultSorting={sorting} />
          <IntegratedSorting />
          <FilteringState defaultFilters={[]} />
          <IntegratedFiltering />
          <PagingState
            currentPage={currentPage}
            onCurrentPageChange={setCurrentPage}
            pageSize={pageSize}
            onPageSizeChange={setPageSize}
          />
          <IntegratedPaging />
          <EditingState onCommitChanges={commitChanges} columnExtensions={editingStateColumnExtensions} />
          <Table cellComponent={Cell} rowComponent={TableRow} />
          <TableHeaderRow showSortingControls />
          <TableEditRow />
          <TableEditColumn showEditCommand showDeleteCommand cellComponent={EditCell} />
          <TableColumnVisibility defaultHiddenColumnNames={defaultHiddenColumnNames} />
          <Toolbar />
          <ColumnChooser />
          <TableFilterRow />
          <TableInlineCellEditing startEditAction="doubleClick" selectTextOnEditStart />
          <PagingPanel pageSizes={pageSizes} />
        </Grid>
```

```
const styles = {
  disabled: {
    backgroundColor: theme.palette.disabled.main,
  },
};


const TableRow = ({ row, ...restProps }: { row: User; restProps: any }) => {
  const style = {
    ...(row.disabled ? styles.disabled : null),
  };

  return <Table.Row {...restProps} style={style} />;
};
```

But I have a typescript error on the rowComponent
![image](https://user-images.githubusercontent.com/21138162/86110411-d13d4a80-bac5-11ea-9874-10122a13aebe.png)

And this onwone on Table.Row:
![image](https://user-images.githubusercontent.com/21138162/86110501-eca85580-bac5-11ea-9655-9e75037e7aa4.png)

It works fine on the page, it's just that I can't seem to find a solution for those typescript errors.

### Environment

- devextreme-reactive: ^2.6.4
- react: 0.0.0-7f28234f8
- browser: -
- bootstrap: none
- react-bootstrap: none
- material-ui: ^4.10.2

**Comment by AryamnovEugeniy** [comment]
Hello!

You can either use [Table.DataRowsProps](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatarowprops) or extend it (here I made a small example based on your code snippets - https://codesandbox.io/s/dazzling-khayyam-jqwxk?file=/demo.tsx).

If you have any other questions, feel free to contact us.

**Comment by KLagdani** [comment]
Works perfectly, thank you !

**Comment by AryamnovEugeniy** [comment]
You are welcome!
