### ISSUE TITLE
Correct use of connectProps in fuctional Component

### ISSUE THREAD

**Issue by dalborgo** [DevExpress/devextreme-reactive#2970]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I have found `connectProps ` examples in Class component context. I wanted to ask your advice about the correct use (best practice) in a functional component.

I report an extract of my code to understand if I get an optimization or if my use of `connectProps` is useless.

```
const GridDetailContainerBase = ({ row, rows, dispatch }) => {
  const { licensePlate, state, attachments } = row
  if (state !== 'ATTIVO') {
    return (
      <RowAttachmentsComponent
        attachments={attachments || []}
        dispatch={dispatch}
        licensePlate={licensePlate}
        state={state}
        vehicles={rows}
      />
    )
  } else {
    return null
  }
}



//My render component
const VehiclesTable = props => {  
  const { policy: { vehicles: rows }, policy, tablePd, dispatch, enqueueSnackbar, vehicleTypes } = props
  ....
const OptimizedGridDetailContainerBase = connectProps(GridDetailContainerBase, useCallback(() => {
    return {
      dispatch,
      rows,
    }
  },[dispatch, rows]))

 return (
 <Paper>
           <Grid
              columns={columns}
              getRowId={getRowId}
              rootComponent={Root}
              rows={rows}
            >
             <TableRowDetail
                contentComponent={OptimizedGridDetailContainerBase}
              />
             ....
            </Grid>
 </Paper>
}
```

Thank you for the support.

### Environment

- devextreme-reactive: 2.6.4
- react: 16.13.1
- browser: Chrome
- material-ui: yes

**Comment by AryamnovEugeniy** [comment]
Hello!

`connectProps` is meant to be used with class components. In functional you can easily achieve a similar effect if you do something like the following:
```
const rows = ...
const dispatch = ...
const OptimizedGridDetailContainerBase = React.useCallback(() => {
    // Your custom component here
}, [dispatch, rows]);
```

**Comment by dalborgo** [comment]
Thank you so much!
