### ISSUE TITLE
Is Toolbar.Root component necessary?

### ISSUE THREAD

**Issue by eugenio1590** [DevExpress/devextreme-reactive#2971]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
What is the functionality of this component? Can I replace it for a `div `for example?

I am using Kotlin/Js to write some components to React. Currently, React Scheduler worked very well. But I am trying to create a custom toolbar with remote data. The problem is importing `Toolbar.Root` component into Kotin wrappers. So, I replaced this component with a `div`, and this work for me. I can see the custom progress bar and the original toolbar. So, this is a good practice or could I have some problems?

This is the native code

````
const ToolbarWithLoading = withStyles(styles, { name: 'Toolbar' })(
  ({ children, classes, ...restProps }) => (
    <div className={classes.toolbarRoot}>
      <div>
        {children}
      </div>
      <LinearProgress className={classes.progress} />
    </div>
  ),
);
````

### Environment
- dx-react-scheduler: 2.6.4

**Comment by AryamnovEugeniy** [comment]
Hello!

Toolbar's root is a container for the `DateNavigator`, `TodayButton` and `ViewSwitcher`. As a base for our toolbar, we use Material-UI's [implementation](https://material-ui.com/ru/api/toolbar/). And you can provide your own implementation for this component (as well as for any other, if you need to). If the div with your styles solves your issues - then there is nothing wrong with this approach.
As an example, we replace default implementation of `TimeTableCell` with a custom implementation in [this demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/overview/).

Does this answer your question?

**Comment by eugenio1590** [comment]
Hi @AryamnovEugeniy  Yes, that's helped me. I think that can be added to the documentation if it is necessary to use a custom implementation. I'll close this ticket. Thanks for the support.

**Comment by AryamnovEugeniy** [comment]
You are welcome!
