### ISSUE TITLE
Virtual scrolling column height "jumps" if cell height varies

### ISSUE THREAD

**Issue by cellog** [DevExpress/devextreme-reactive#2974]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

as you scroll horizontally, the row height "jumps" as the cell with higher height is rendered off screen.

### Expected Behaviour

row height should remain constant as horizontal scrolling happens

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/gifted-wilson-2hcgf?file=/demo.js

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @cellog,

When you use `wordWrapEnabled` for some columns, cells in these columns may expand. In the `VirtualTable`, all elements outside the viewport are removed and the table calculates row height based on cells in the viewport.
I suggest that you define a row's height using the `VirtualTable` plugin's `rowComponent`. Also, you need to define the [estimatedRowHeight](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#properties) property for correct operation of vertical scrolling. Here is an [example](https://codesandbox.io/s/festive-cdn-t5erb).

If you have any further questions, feel free to contact us.

**Comment by cellog** [comment]
sorry, but this is not helpful. The use case we have is custom renderers in dynamic tables that can have many columns. In order to calculate height, we will need to render the entire row to determine whether any cells are dynamic height, which defeats the purpose of using the virtual table.

Is there any way to turn off virtual columns, and ONLY have virtual rows?

**Comment by LazyLahtak** [comment]
Unfortunately, we have no any way to turn off column or row virtualization for the VirtualTable. We will consider this possibility in future releases, but this requires a lot of refactoring. You can check our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed about new features.
