### ISSUE TITLE
Filter input loses focus on typing a character when I pass props to custom filter cell

### ISSUE THREAD

**Issue by bgrand-Lam** [DevExpress/devextreme-reactive#2978]
- [x] I have searched this issue [#2019](https://github.com/DevExpress/devextreme-reactive/issues/2019) but his not answer to my request.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I would like to pass props to my custom filter cell but if I do that custom filter is render again.

How can I do that ?

My table filter row:
```
<TableFilterRow
      showFilterSelector
      cellComponent={(props) =>
           <CustomFilterCell {...props} rows={properties} columnsChanged={[
               {columnName: "unitOfMeasure", type: "selection"},
               {columnName: "languageCode", type: "selection"},
            ]}/>
       }
/>
```
And my Custom filter cell:

```
const CustomFilterCell = (props) => {
    const {column, rows, columns} = props;
    let isCustom = false;
    let propertyUse = undefined;

...

    if (isCustom && propertyUse !== undefined) {
        if (propertyUse.type === "selection") {
            return <SelectionFilterCell {...props} content={rows} property={propertyUse.columnName}/>;
        } else if (propertyUse.type === "dateRange") {
            return <DateRangeFilterCell {...props}/>;
        }
    }
    return <TableFilterRow.Cell {...props}/>;
};
export default CustomFilterCell;
```

### Environment

- devextreme-reactive: "^2.6.4"
- react: "^16.13.1"
- browser: chrome

**Comment by MaximKudriavtsev** [comment]
Hello,

We have already registered a similar issue: [#2019](https://github.com/DevExpress/devextreme-reactive/issues/2019#issuecomment-491797904).

**Comment by bgrand-Lam** [comment]
Hello,

Yes I have see this similar issue.

But how can I pass props to my customFilterCell when it is outside ?

[example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-3zuwi)

**Comment by MaximKudriavtsev** [comment]
@bgrand-Lam,

Please follow [this guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) for more information.

**Comment by bgrand-Lam** [comment]
This is work with [PureComponent ](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-3zuwi?file=/index.js).

But I can't do the same think with [function](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-3zuwi?file=/index.js).

This is possible to do this with function component ?

**Comment by bgrand-Lam** [comment]
It's ok ! 

I have find how do this.

[CODE](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-3zuwi?file=/index.js)

Thank for your support.
