### ISSUE TITLE
Fixed Header and Left / Right Column

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#298]
Somewhat related to #293 but it's always so handy to have the ability to fix the tableheader during scrolling and fix a column to either the left or the right.

It's a simple CSS functionality but it's really powerful and often gives problems so would appreciate it being built-in functionality.

Just an idea ;)

**Comment by dispix** [comment]
Hi, is there any way to achieve a fixed header and/or footer since this issue popped up ? I think it's a must have that a lot of react tables are implementing.

**Comment by kvet** [comment]
Hi @dispix,

Have you seen the following demo: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/? It shows pinned header columns.

**Comment by terndrup** [comment]
Yeah the headers are fine, it's really just the left or right column now. If we can get a pinned Left Column (for side scrolling) then all is well

**Comment by dispix** [comment]
@kvet Yes I saw the demo but I don't see anything in the code that points shows how the header is fixed ?

**Comment by rao123dk** [comment]
Hi @kaatula @komarovalexander  
As per your doc guidelines and with the help of your sandbox sample [https://codesandbox.io/s/4xom180v14](https://codesandbox.io/s/4xom180v14) .
I have used my own theme (neither BS3/BS4/material). Its works fine. But last problem is fixing header and left column.

could you please guide us?

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please describe the problem in greater detail?

**Comment by rao123dk** [comment]
Thanks,
I have used DevExtreme React Grid with Custom Theme(i.e. without Bootstrap 3 or Bootstrap 4).
As per your Custom theme guidelines, and  I have also got sample sandbox from your side for [reference.](https://codesandbox.io/s/4xom180v14) . I have developed my complete table, thanks its working fine. But I got one last problem for fixing my header on top like you have implemented in virtual table. 
Is there any doc or sample available where I can go through to fix my problem.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification. In your case, you need to implement the `VirtualTable` plugin instead of the `Table` one. Refer to our [source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/src/plugins/virtual-table.jsx) to see how it is implemented.

**Comment by devleopertest** [comment]
As you said Virtual table will fix table header fixing problem, thanks It works. But I have implemented tble fixed header plugin same as [https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/src/templates/table-fixed-cell.jsx](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/src/templates/table-fixed-cell.jsx) for fixed first row in table. But geetting error could you please provide a sample to us for refernce. 

Note:- I am using typescript with own custom tempalate.

**Comment by SergeyAlexeev** [comment]
What error did you get?

**Comment by devleopertest** [comment]
I thought I have messed up with TableFixedColumns. Could you please define what props should <TableFixedColumn /> required?
```
 <TableFixedColumns
                    cellComponent={this.Cell}
                    leftColumns={['checkbox']}
                   rightColumn={[rColumns]}
                />
```

**Comment by devleopertest** [comment]
The main problem with me is the cellComponent structure. I am trying to refer from  [this link](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-fixed-columns/). But ??

**Comment by SergeyAlexeev** [comment]
As you can see in our  [source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/src/plugins/table-fixed-columns.jsx) the `TableFixedColumn` plugin `requires` the `FixedCell`, `TableInvisibleRow` and `TableListenerCell` components. I should say these are internal components and their names and interfaces can be changed.
Currently, we don't provide TypeScript definitions for them for the same reason. Please refer to an updated [sample](https://codesandbox.io/s/yvw32w908z) for more details.
We have plans to add documentation that will describe how to create a custom theme. We are also working on TypeScript definition improvements for plugins and components.
