### ISSUE TITLE
Attempted import error: 'GridExporter' is not exported from '@devexpress/dx-react-grid'.

### ISSUE THREAD

**Issue by ptkpyitheim** [DevExpress/devextreme-reactive#2980]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Shows import error above when trying to use GridExporter as described in https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/

### Expected Behaviour

To be able to use it without giving me the import error

### Steps to Reproduce

I have the code as follow.

```
import React.. and some other imports
import { GridExporter } from "@devexpress/dx-react-grid";
import { ExportPanel } from "@devexpress/dx-react-grid-material-ui";

class UsersTable extends React.Component {
    constructor(props) {
        this.exportRef = React.ccreateRef();
    }
    render() {
        return(
            <Paper>
            <Grid rows={rows} columns={columns}>
                ......
                ......
                <ExportPanel
              startExport={(options) => exporterRef.current.exportGrid(options)}
            />
          </Grid>
          <GridExporter ref={exporterRef} columns={columns} rows={rows} />
          </Paper>
        )
}
```

And that gives the error as the title shows. When I comment out the GridExporter component it's fine but when I have it as above it throws me import error. Not sure what's wrong.

### Environment

- @devexpress/dx-react-core": "^2.6.4
- @devexpress/dx-react-grid": "^2.6.4
- @devexpress/dx-react-grid-material-ui": "^2.6.4
- react: "^16.13.1"
- browser: Latest Chrome
- bootstrap: none
- react-bootstrap: none
- "@material-ui/core": "^4.10.1"

**Comment by ptkpyitheim** [comment]
Okay so I found the solution.

Apparently I cannot import as such
`import { GridExporter } from '@devexpress/dx-react-grid';`

But I found this npm library to **install specifically for dx-react-grid**
https://www.npmjs.com/package/@devexpress/dx-react-grid-export

This was failed to be mentioned in the original documentation here:
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/

and here https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid-exporter/

It would be great to update the documentation with correct installation and import statements

**Comment by LazyLahtak** [comment]
Hi @ptkpyitheim,

Thank you for reporting this problem. We will update our documentation in the nearest release.
