### ISSUE TITLE
No support to render component in center for doughnut chart in @devexpress/dx-react-chart

### ISSUE THREAD

**Issue by yash2code** [DevExpress/devextreme-reactive#2983]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour

 ```
<Chart data={data} height={300}>
            <Palette scheme={scheme} />
            <PieSeries
              valueField="val"
              argumentField="isGraduated"
              innerRadius={0.6}
            />

            <Title text="Graduation Rate" />
            <Animation />
          </Chart>
```

### Expected Behaviour

```
 <Chart data={data} height={300} centerComponent/centerRender/centerTemplate = {}>
            <Palette scheme={scheme} />
            <PieSeries
              valueField="val"
              argumentField="isGraduated"
              innerRadius={0.6}
            />

            <Title text="Graduation Rate" />
            <Animation />
          </Chart>
```

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by MaximKudriavtsev** [comment]
Hi @yash2code,

Unfortunately, we don't provide a special API for this case. I suggest you use the absolute positioning to place your custom content in the center of a chart.
