### ISSUE TITLE
How can i show first and last hours on timeline?

### ISSUE THREAD

**Issue by muserrefakillibaykus** [DevExpress/devextreme-reactive#2984]
I'm using **React Scheduler**

How can i show first and last hours on timeline? Example when first hour is 9, it doesn't display. And last hour is same.

**Comment by AryamnovEugeniy** [comment]
Hello!

You will have to override [TimeScaleLayout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalelayoutprops) component. All you need is to provide **all** of the labels with `time` and `formatDate` (in our implementation, we do not pass these props to the first and the last labels). After you've done that, you need to change first and last labels' `height` and `line-height`. You can use as an example our implementation of the TimeScaleLayout: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-scale/layout.jsx
To make things easier, I made an example for one of the most complex cases - when vertical grouping is enabled. Here it is:  https://codesandbox.io/s/runtime-snow-6izsj?file=/demo.js

Is this solution helpful?

**Comment by muserrefakillibaykus** [comment]
It works! Thank you so much.

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
