### ISSUE TITLE
IntegratedFiltering/Searching with CustomTreeData

### ISSUE THREAD

**Issue by wc-lei** [DevExpress/devextreme-reactive#2985]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I have a tree data with 4 levels of information, implemented search with integratedFiltering, just as the example does. However, I found the filtering/search doesn't seem to match on level 3 and 4, and doesn't seem to match in a long text field. Has this been implemented? or I have to implement my own custom search algorithm? Could you please provide some hints if so?

Thanks.

### Environment

- devextreme-reactive: xxx
- react: ^16.13.1
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: @devexpress/dx-react-grid-material-ui ^2.6.4

**Comment by wc-lei** [comment]
After playing a bit the order of plugin, the filtering seems working on all levels if I have the plugin in this order:
```javascript
              <SearchState />
              <FilteringState columnExtensions={filteringStateColumnExtensions} />
              <TreeDataState />
              <CustomTreeData
                getChildRows={getChildRows}
              />
              <IntegratedFiltering />
              <Table
                columnExtensions={tableColumnExtensions}
              />
              <TableHeaderRow />
              <TableFilterRow />
              <TableTreeColumn
                for="code"
              />
              <Toolbar />
              <SearchPanel />
```

However, my tree data is collapsed by default. How can I automatically expand the row/rows that match with search text? These matching rows could be at any level of the tree.

**Comment by LazyLahtak** [comment]
Hi @wc-lei,

The order of plugins is important in our Grid. To get more information about it, please refer to our guide: [React Grid - Plugin Overview. Plugin Order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order).
To expand rows after search/filtering, I suggest that you use [tree data in controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#controlled-mode). Here is an [example](https://codesandbox.io/s/zealous-dijkstra-y5dzk?file=/demo.js), where all rows are expanded after the search. Also, you can expand only necessary rows in the same way.

If you have any further questions, feel free to contact us.
