### ISSUE TITLE
Reactive Chart doesn't correctly update lines with dynamic values

### ISSUE THREAD

**Issue by ilyapavlovdx** [DevExpress/devextreme-reactive#2988]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour

\[ from https://supportcenter.devexpress.com/ticket/details/t913811 ]

I have multiple Reactive charts on a web page embedded in Grid (from material-ui) for the responsiveness. I display dynamic data in the Chart, and I only display the last 5 values.

In some cases, the lines are not rendered/refreshed correctly, it is not very easy to identify the reason. Sometimes, the first 5 values are displayed correctly and then we see the argument axis increasing but the line does not move. Sometimes, the Chart does not render the lines at the first render… In both cases, I a resize the window, the lines are refreshed but if I resize the window during the render, it seems to "block" the rendering…

### Steps to Reproduce
If lines render correctly, try to resize the browser inside codesandbox.

Link to the example that reproduces the issue: https://codesandbox.io/s/live-dx-chart-in-grid-l5f1x?file=/demo.js.

### Environment
MacOS X 10.15
Visual Studio Code

- devextreme-reactive: 2.6.4
- react: 16.13.1
- browser:
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by woodreamz** [comment]
There is an error is the ticket link, it's: [https://supportcenter.devexpress.com/ticket/details/t913811](https://supportcenter.devexpress.com/ticket/details/t913811).

A workaround is also provided in the ticket comments.

**Comment by Krijovnick** [comment]
fixed in #3354
