### ISSUE TITLE
How do I turn off dynamic class names or how can we access dynamic class names

### ISSUE THREAD

**Issue by fdevGit** [DevExpress/devextreme-reactive#2990]

**Comment by AryamnovEugeniy** [comment]
Hello,

You cannot turn dynamic class names off. But there is a possibility to override default classes if you want to customize a component. Here we have examples on how to do that:
- Grid: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#customize-the-appearance
- Scheduler: https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance
- Chart: https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/legend_title/#customize-the-legend-layout
