### ISSUE TITLE
Auto expanding all CustomTreeData

### ISSUE THREAD

**Issue by wc-lei** [DevExpress/devextreme-reactive#2993]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Firstly, this is somehow related to issue #2985. Thanks for the help, I took the example from #2985 and applied in my scenario, it works but the performance is quite poor. I guess this is due to the fact on every SearchState value change, the component has to update the state of expandedRowIds list. When I have over 500 rows in 4 different levels, there is a significant and noticeable lag in the response.

This makes me thinking what if I expand all the rows by default and just apply the default filtering. Based on my experience, filtering is quite efficient on client side. Is there a way of configuring the Grid table expand all rows of a multi-level treedata? The only way I can think of is setting every single rowId in my expandedRowIds array.

Your help is much appreciated, either on how to improve the performance of row expanding on search, or how to automatically expand all the rows. I am also curious about any experience of filtering large treedata structure, and how good the responsiveness could be.

- devextreme-reactive: latest
- react: latest
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: latest

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you use the [VirtualTable](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#react-grid---virtual-scrolling) instead of `Table`. It takes too long to update because the Grid has to render too much rows (in your case - 500). And `VirtualTable` solves this issue - it renders only those rows that are visible and several others, but not all of them. Here is a small example: https://codesandbox.io/s/sleepy-darwin-xvgd6?file=/index.js.

Let me know if this is helpful.

**Comment by wc-lei** [comment]
@AryamnovEugeniy thanks a lot, I didn't know there exists a virtualtable. Just tried it, much faster than the table, so I will probably go with it. Do you know how to get rid of the vertical scrolling? It seems the virtualtable imposes a height by default, instead of filling the full page height and let the browser scrolls natually.

Also, an auto-expand/collapse all rows would still be a very nice feature. Even with virtualtable, once all rows are expanded, it's hard to collapse them.

**Comment by AryamnovEugeniy** [comment]
It is not possible to get rid of the virtual scrolling, but you can try to follow this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#fill-the-container). In this case your table will fill its container. Another option is to set `VirtualTable`'s height to the one you need.

About auto-expanding/collapsing. This can be implemented using the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode). Here I made a small [example](https://codesandbox.io/s/focused-tree-5jh48?file=/demo.js). Click on Collapse All Rows Button and all of the will collapse.
