### ISSUE TITLE
Dragging event in scheduler causing intensive render calls for cells and appointments

### ISSUE THREAD

**Issue by ajsergeev** [DevExpress/devextreme-reactive#2994]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Current Behaviour

Multiple appointments and table cells actively rendererd when drag one appointement. 
This make application laggy on slow or mobile devices.

### Expected Behaviour

Only changed appointment should be rendererd, no cells should be rendered

### Steps to Reproduce

1) Attached application with customized cells and appointments. Each custom component logs into console once its render method calls
[schedule-test2.zip](https://github.com/DevExpress/devextreme-reactive/files/4937870/schedule-test2.zip)

2) Open browser console, drag some appointment, see how much render methods called for cells and appointments
3) Open react dev tools, start capture performance profile
4) Drag some appointment
5) Finish performance profile recording, see there are two long frames.

Link to the example that reproduces the issue: [schedule-test2.zip](https://github.com/DevExpress/devextreme-reactive/files/4937870/schedule-test2.zip)

### Screenshots

![many_renders_on_drag](https://user-images.githubusercontent.com/2513770/87788375-ec3de780-c845-11ea-98f7-b446630e27b2.jpg)

![issue_in_profiler](https://user-images.githubusercontent.com/2513770/87788654-62424e80-c846-11ea-976c-32d6dea68e00.jpg)

### Environment

- devextreme-reactive: 2.6.4
- react: 16.13.1
- browser: Chrome latest
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.10.2

**Comment by AryamnovEugeniy** [comment]
Hello!

We have already fix this issue as part of this PR: https://github.com/DevExpress/devextreme-reactive/pull/2969. All you need is to update to version 2.7.0. You may compare these two versions: [2.6.4](https://codesandbox.io/s/charming-chebyshev-p3h0k?file=/demo.js) and [2.7.0](https://codesandbox.io/s/funny-heyrovsky-jnet6).

I also noticed that you customize your appointments. Starting from 2.7.0 we have significantly changed the way Day's and Week's appointments are rendered. Should you encounter any problem, feel free to contact us.
