### ISSUE TITLE
Detailed error handling when individual components fail

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#2995]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I have a situation where a single React Component is responsible for displaying the results of a variety of different API responses.

To support this, I have the `tableColumnExtensions` (which defines my column widths, filtering enabled etc) defined inside my React App, and the `columns: []` (which columns should be displayed) is specified in the API response alongside the `rows: [{}, {}, ...]`.

At this time, I can think of a handful of ways to resolve this with access to the backend (Bundle the `tableColumnExtensions` into the API response as well) however as a matter of interest how could I resolve this if I _didn't_ have access to the backend?

My first thought is to be able to define some kind of default `tableColumnExtension` that would catch any columns that were attempting to display without definition, and supporting the minimal set of features possible (columnWidth). At the very least this column could have no width and be functionally hidden, rather than crashing everything down :P

My second thought is to somehow handle the `Error: The columnWidths property of the TableColumnResizing plugin is given an invalid value.` error in a graceful fashion, but the best I can do at this time is to wrap the entire table in an `<ErrorBoundary>` which still causes the entire table to stop rendering.

My final thought is that if the Error report (`Error: The columnWidths property of the TableColumnResizing plugin is given an invalid value.`) contained the name of the column that caused the error then my bugfix turnaround time would be much shorter :D

### Environment

- devextreme-reactive: 2.6.0
- react: 16.13.1
- material-ui: 4.9.8

**Comment by MaximKudriavtsev** [comment]
Hi @thehig,

You can generate `tableColumnExtensions` based on `columns`, `rows`, and table dimensions after your data grid is rendered for the first time.

As for more detailed error messages, we don't have immediate plans to implement them. But we will consider this feature for future releases.

**Comment by thehig** [comment]
> You can generate `tableColumnExtensions` based on `columns`, `rows`, and table dimensions after your data grid is rendered for the first time.

Yep, I ended up doing something similar as part of my API redux `SUCCESS` action:

```javascript
const parseResult = (state, action) => {
  const result = {
    rows: [],
    columns: [],
    totalRows: 0,
  };

  try {
    const { users, records, columns } = JSON.parse(action.payload);
    result.rows = users;
    result.totalRows = records;

    const { tableColumnExtensions } = state.initialTableState;

    // "Keep" columns
    result.columns = columns.filter((x) =>
      // Where the tableColumnExtensions: [ { columnName: "", ... } ]
      // Contains the column : { name }
      tableColumnExtensions.map((c) => c.columnName).includes(x.name)
    );

    if (result.columns.length !== columns.length) {
      // "Ditch" columns
      result.unmatched_columns = columns.filter(
        (x) =>
          // Where the tableColumnExtensions: [ { columnName: "", ... } ]
          // Does *NOT* contain the column : { name }
          !tableColumnExtensions.map((c) => c.columnName).includes(x.name)
      );
    }
  } catch (err) {
    result.list_error = err;
  }

  return result;
};
```
