### ISSUE TITLE
VirtualTable column width not effective

### ISSUE THREAD

**Issue by DavidHenri008** [DevExpress/devextreme-reactive#2996]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When using a VirtualTable in grid, the defaultColumnWidth is not applied as described by the TableColumnResizing component documentation.

### Expected Behaviour

According to documentation the column width should accept different units like %, em, vh, etc.

### Steps to Reproduce

You may see in the example that it works with Table but not with VirtualTable component.
[https://codesandbox.io/s/modern-pond-ybo5w](https://codesandbox.io/s/modern-pond-ybo5w)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13
- browser: Chrome 83

**Comment by LazyLahtak** [comment]
Hi @DavidHenri008,

We have already registered a similar issue: #2976. Please, refer to [this](https://github.com/DevExpress/devextreme-reactive/issues/2976#issuecomment-656093828) comment.
