### ISSUE TITLE
TableColumnRisizing minColumnWidth not working

### ISSUE THREAD

**Issue by DavidHenri008** [DevExpress/devextreme-reactive#2997]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The TableColumnRisizing property minColumnWidth has no effect.

### Expected Behaviour

I was expecting the table to respect the minColumnWidth for each column when the grid get smaller.

### Steps to Reproduce

You may see the issue on this CodeSandBox [https://codesandbox.io/s/peaceful-sound-rxto0?file=/demo.js](https://codesandbox.io/s/peaceful-sound-rxto0?file=/demo.js)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13
- browser: Chrome 83

**Comment by LazyLahtak** [comment]
Hi @DavidHenri008,

The `TableColumnResizing` plugin allows resizing column widths programmatically or via the Grid's UI, using special controls. It isn't intended to resize the Table. We will take this feature into account when planning further development. You can check our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed about our new features.

If you have any further questions, feel free to contact us.

**Comment by DavidHenri008** [comment]
I am sorry but this is not clear for me. In my example the minColumnWidth is set to 222 but the table renders column with a size of 194. If it does not increase the size of the table to fit the minimum column width requirement, what is the purpose of this property?

**Comment by LazyLahtak** [comment]
The TableColumnRisizing property limits the width of each column that is being resized. Here is an [example](https://codesandbox.io/s/restless-star-d2thh?file=/demo.js). As you can see, you can use this property to limit the minimum width of each column. You can also limit the minimum width of any column using [TableColumnResizing.ColumnExtension](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#tablecolumnresizingcolumnextension).

To limit the minimum column width when you resize the Table, I suggest that you use [TableColumnResizing in controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#controlled-mode). Thus, you can change column width when resizing a component. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-5nzh1?file=/index.js:364-385) where we use the [react-resize-detector](https://www.npmjs.com/package/react-resize-detector) to detect the resizing of the Grid.
