### ISSUE TITLE
HeaderFilter In DevExtreme, Can we have a similar feature in DevExpress Grid

### ISSUE THREAD

**Issue by yshaik77** [DevExpress/devextreme-reactive#2998]
HeaderFilter In DevExtreme, Can we have a similar feature in DevExpress Grid

![image](https://user-images.githubusercontent.com/62965483/87880482-95581f80-c9b7-11ea-9f1f-0789ddf88842.png)

**Comment by MaximKudriavtsev** [comment]
Hi @yshaik77,

We have already registered a similar issue: #304.
