### ISSUE TITLE
How i can hide the left side time panel in week view?

### ISSUE THREAD

**Issue by brijrajsinh** [DevExpress/devextreme-reactive#3001]
I want to achieve below functionalities. Can you help me which are of below are available?

I am posting this question as non of them are available in documentation.

1. Hide time column on left side in week view.
2. How i can display entire month days  like week view?
3. Is lazy loading available in vertical grouping?
4. Create schedule for multiple resources at same time.

Hope you will help/guide for above problems.

**Comment by AryamnovEugeniy** [comment]
Hello!

1. You can customize the [TimeScaleLayout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalelayoutprops). Here is an example: https://codesandbox.io/s/infallible-minsky-bq7c2?file=/demo.js

2. If you want to show a full month, you can set `intervalCount` to the [WeekView](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#properties) and specify the current date (the first day of the month you need to display). The `intervalCount` should be between 4 and 6 depending on the number of days in a month and on the first day of week in this month. I made a small example demonstrating this (though I did not turn Date Navigation on to keep my example simpler): https://codesandbox.io/s/still-worker-5qq7x?file=/demo.js. In this example I set `intervalCount` manually. If Date Navigation is turned on, however, it is necessary to calculate `intervalCount` programmatically. Another option is to set `intervalCount` to the [DayView](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/day-view/). In case with DayView, `intervalCount` should be between 28 and 31.

3. Lazy loading is not available for the React Scheduler.

4. Could you clarify this point a bit further? We have several demos where multiple resources are used. For example, [this](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/resources/#enable-resource-editing), without grouping. Or [this](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/grouping/#basic-usage), where appointments are grouped by two resources at once.

**Comment by brijrajsinh** [comment]
Hi AryamnovEugeniy,

Thank you so much for all your help. Just one more help needed.  I have created a custom theme using theme builder. And exported css.  How i can register and use that into my component.  I have imported the css file but new theme is not getting applied. 

Thanks for you support and help

**Comment by AryamnovEugeniy** [comment]
Could you specify the Theme Builder you use? The Reactive Scheduler supports [Material-UI's theming](https://material-ui.com/customization/theming/). For example, you can change appointments' colour, as I've done: https://codesandbox.io/s/eloquent-hofstadter-rlu36?file=/demo.js.
But if it is the DevExtreme [Theme Builder](https://js.devexpress.com/Documentation/Guide/Themes_and_Styles/ThemeBuilder/) that you are trying to use, it won't work with the Reactive Scheduler because we use Material-UI's theme.

**Comment by brijrajsinh** [comment]
Hi AryamnovEugeniy,

Thanks for your all support. Lucky i was able to resolve all the above changes. 

I need your more help for below points: 

1. I want to change appointment color grammatically. Means if data has value publish then blue color else orange.
2. I want to display edit, delete button in custom appointment tool tip.
3. When we have more than one appointment in "timelineMonth" view I want to display display "more 3" in bottom of appointment not on top of it which is as default.
4. Is there any scroll event so i can achieve lazy loading by API and add more resource.
5. How to disable previous days than today without using cellData event.
6. How to create tooltip view for resource.
7. Is there any inbuilt time overlapping validation functionality?

Your help is highly appreciated. Thanks in advance.
-Brijrajsinh

**Comment by AryamnovEugeniy** [comment]
The React Scheduler does not have "timelineMonth" view. Do you use [Reactive Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/) or [DevExtreme Scheduler](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/)?

**Comment by brijrajsinh** [comment]
I am useing devextreem scheduler:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/jQuery/Light/

**Comment by AryamnovEugeniy** [comment]
In this case you should either open an issue [here](https://github.com/DevExpress/DevExtreme/issues) or create a ticket (if you have a license) [here](https://supportcenter.devexpress.com/ticket/list).
