### ISSUE TITLE
Tree view with column checkbox inputs

### ISSUE THREAD

**Issue by sri-vathsa** [DevExpress/devextreme-reactive#3005]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I want to create a Tree view with nested resources and each element has 3 types of access edit, read, and delete. So basically each column would look like

Name of resource | Edit checkbox | Read checkbox | Delete checkbox

And I want to get the values selected for each row in the tree view.
It would be an extension of [this](https://codesandbox.io/s/ecstatic-matsumoto-ee5ic?file=/demo.js) where the columns gender, city and car will be replaced by edit, read and delete checkboxes and there won't be a checkbox for the row. And selection would contain the selected rows with the data of the read, edit and delete checkbox.

**Comment by LazyLahtak** [comment]
Hi @sri-vathsa,

I suggest that you use the [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) plugin. Here is an [example](https://codesandbox.io/s/ecstatic-keldysh-z2zd7).
To get more information about the data formatting, please refer to our [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/).
If you have any further questions, feel free to contact us.
