### ISSUE TITLE
React Scheduler Modify monthly view default start/end dates

### ISSUE THREAD

**Issue by lim1017** [DevExpress/devextreme-reactive#3006]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I am building a scheduler app that has some specific requirements.  One of them being that an appointment cannot span multiple days.

I've implemented a check to make sure the day/month/year of the start/end date are equal, and it works as expected.

However when I switch to the month view the default times provided when I attempt to create an appointment are for example:
27/07/2020 - 28/07/2020

The days being unequal will automatically trip my multi-day error check.

How do I modify the default appointment dates provided on the monthly view so they don't by default cause an error?  I'm looking to provide a time similar to the weekly/daily view
27/07/2020 => 27/07/2020 03:30 AM

Ive been looking at the monthly view docs
https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/month-view/#monthviewdayscalecellprops

maybe
startDate | Date | Specifies the cell's start time.

But I'm not sure how I would go about modifying it...  I'm not even sure how the scheduler knows which date I've clicked on before I submit

Thanks for any help!

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you use Editing in the Controlled Mode (here we have a [demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#controlled-mode)). When a user creates an appointment, it is stored in the `addedAppointment` state property. All you need is to set the endDate as you need before saving the new appointment to the state. I made an example that illustrates this approach: https://codesandbox.io/s/laughing-surf-q7m95?file=/demo.js.

Should you have any other question, feel free to open a new issue.
