### ISSUE TITLE
Tree grid on click throws an error

### ISSUE THREAD

**Issue by sri-vathsa** [DevExpress/devextreme-reactive#3007]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

TypeError: changeEvent is not a function

### Expected Behaviour

Row to be selected
### Steps to Reproduce

I've modified the tree data grid code given [here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/) in the documentation to use as a react component.
I created a code sandbox [demo](https://codesandbox.io/s/crazy-tree-lqvw3?file=/demo.js)

### Screenshots

![Screenshot from 2020-07-28 14-05-50](https://user-images.githubusercontent.com/53426607/88640713-e2d13c80-d0db-11ea-8c1d-447c53b77537.png)
![Screenshot from 2020-07-28 14-05-54](https://user-images.githubusercontent.com/53426607/88640723-e5cc2d00-d0db-11ea-8291-a877b2341b08.png)
![Screenshot from 2020-07-28 14-08-17](https://user-images.githubusercontent.com/53426607/88640727-e6fd5a00-d0db-11ea-8d91-f5d3e2422de4.png)

### Environment

    react-dom: "latest",
    react: "^16.13.1",
    material-ui/icons: "^4.9.1",
    material-ui/core: "^4.11.0",
    devexpress/dx-react-grid-material-ui: "2.7.0",
    devexpress/dx-react-grid : "2.7.0",
    devexpress/dx-react-core: "2.7.0"

**Comment by AryamnovEugeniy** [comment]
Hello!

I noticed a number of mistakes in your code. `setSelection` must be a function. In your case this is an array. `setExpandedRowIds` should also be a function.

If you have any other questions, feel free to ask them.

**Comment by sri-vathsa** [comment]
@AryamnovEugeniy It is an array in the example linked from the documentation [here](https://codesandbox.io/s/optimistic-dewdney-2rwe2?fontsize=14&hidenavigation=1&theme=dark)

**Comment by AryamnovEugeniy** [comment]
According to the [docs](https://reactjs.org/docs/hooks-reference.html#usestate), the `useState` Hook returns a value and a **function** (in case of our demo, it is `setSelection`). [Here](https://reactjs.org/docs/hooks-state.html) you can read more about React Hooks.
