### ISSUE TITLE
Possible for "excel-like" controls using inline editing?

### ISSUE THREAD

**Issue by nolanlocke** [DevExpress/devextreme-reactive#3009]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

This may be directly related to #1966 but unsure if it will be part of adding keyboard support.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Looking to simulate "excel-like" controls using inline cell editing (arrow keys to move between cells, enter to begin editing, etc.),  but can't find any examples modifying cell selection using anything but tab, and only finding triggering edits via click/doubleClick and was unsure if there was a way to override these given the current framework.

Thank you!

### Environment

- devextreme-reactive: 2.7.0
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @nolanlocke,

Yes, we have plans to support this case in the context of the request you found. I see you also created a ticket in our SC.
If you need further clarification on this, feel free to contact us.
