### ISSUE TITLE
Setting style settings on Table Column Header

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#301]
Hey guys,

from your demos and docs I have figured out how to apply templates to a Table cell in a row, but for my project I need to set some style attributes on some of the Table header elements.

For example, I need to set a max-width of 25px on the first Table Header <th> element.

I know how to do this with a workaround adding it after the table has been rendered but is there an api for doing it? Like passing a react style object to the list of columns. If not, there really should be ;)

Thanks.

**Comment by KamiGim** [comment]
waiting too thanks!

**Comment by MaximKudriavtsev** [comment]
This functionality is available starting with [v1.0.0-beta.2](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-beta.2). To implement it in your scenario, you can use the `TableHeaderRow` plugin's component [TableHeaderRow.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#plugin-components) and add it to the `cellComponent` property. The component's styles depend on the first column name of your grid.
