### ISSUE TITLE
Writing tests for React Scheduler, where/how to add test-ids??

### ISSUE THREAD

**Issue by lim1017** [DevExpress/devextreme-reactive#3012]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Im very new to testing, and I can at least get some tests working if I can successfully add the testID's.. but I cannot figure out the best way to add test-ids to the scheduler elements.  

I was able to add test IDs to my custom appointment form elements so I can write things like 
    cy.get('[data-cy=location]').find('input').type("Toronto")

but when trying to do something like double click a specific date on the calendar I have no idea where/how to add a testID to each calendar cell.

So i am forced to use their DOM selector tool which just generates something like
    cy.get('.MuiTableBody-root > :nth-child(2) > :nth-child(3)').dblclick()

It works but its can get very messy, and not best practice, etc.

Thanks for any help.

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

We pass to our components only those properties that they need. So, cells, for example, do not have a unique identifier by default. So, to find them in DOM and click them, you either should you selectors (as you've already mentioned) or customize and provide them with a custom className (such as `time-table-cell` for TimeTableCell component). In this case, you will be able to find them during the test.

But we thoroughly test our components. So, could you clarify why you need to test them? Maybe, we would be able to come up with a better approach.
