### ISSUE TITLE
React state update on an unmounted component in the scheduler current time indicator.

### ISSUE THREAD

**Issue by knightburton** [DevExpress/devextreme-reactive#3013]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
When a `Scheduler` is used with the `CurrentTimeIndicator` plugin and it's unmounts (therefore the `CurrentTimeIndicator` as well) this warning shows up:
```
Warning: Can't perform a React state update on an unmounted component.
This is a no-op, but it indicates a memory leak in your application.
To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
Besides the warning (which is annoing) the `CurrentTimeIndicator` plugin own interval ticks are still works in the background.

### Expected Behaviour
After the `CurrentTimeIndicator` unmount the `clearInterval` should clear the callback for real.

### Steps to Reproduce
1. Create a new `Scheduler` with a `CurrentTimeIndicator` plugin.
2. Navigate to the component in your application.
3. Navigate to somewhere else in your application.
4. Check the developer console for the warning.

### Screenshots
![image](https://user-images.githubusercontent.com/12102205/88783853-9b0bed00-d18f-11ea-99eb-f0f13e918713.png)
As you can see in the developer console screenshot, after the component called the unmount process (which is the `clearInterval` here) the interval is not stopped at all.

### Solution
The problem is that, the useEffect is used incorrectly inside the [current-time-indicator](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler/src/plugins/current-time-indicator.tsx) because the hooks requires the `indicatorUpdateTimer` as well however that is not passed as a dependency (which is clear if we consider that would lead an infinite render...). Therefore, the useEffect will use the `indicatorUpdateTimer` with the initial value which is `undefined` therefore the `clearInterval` will never clear that. The whole interval handling should be placed inside the useEffect hook to avoid this. This should be the the code:

```javascript
const [currentTime, setCurrentTime] = React.useState(Date.now);

React.useEffect(() => {
  const tick = () => setCurrentTime(Date.now());
  const intervalId = (updateInterval && setInterval(tick, updateInterval)) || undefined;
  return () => clearInterval(intervalId);
}, [updateInterval]);
```

After the devs are agree I could create a PR for it as well.

### Environment
- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: Chrome Version 84.0.4147.89
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.8

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product!
I reproduced this behaviour. And this is a bug, of course. If you are willing to create a Pull Request that fixes it - we will be happy to review it and help you with it. Please also refer to our Contributing Guide first: https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md.

**Comment by knightburton** [comment]
Hi @AryamnovEugeniy!

Thanks for the response, I've created the PR for it (as you can see above).

**Comment by AryamnovEugeniy** [comment]
Thank you for your contribution! We greatly appreciate it!

**Comment by adamcarr** [comment]
Thanks @knightburton for contributing to this. We also were running into this issue. When will there be a published patch version with this fix available @AryamnovEugeniy ?
