### ISSUE TITLE
AppointmentForm component with Custom Fields

### ISSUE THREAD

**Issue by eugenio1590** [DevExpress/devextreme-reactive#3015]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I have been using "**_AppointmentForm_**" component to edit the data on my scheduler. But I have a couple of questions:

- Is it possible to get the form with non-editable fields? I mean: Can I create resources like: `"owner": { readOnly: true }` or something like that? In the same way, I can include resources on demand. I mean: Can I create resources  like: `"materials": { url: "http://mydomain.com/materials?name={{name}}" }` or something like that?

- I think the above behavior can be resolved including an "**_AppointmentForm_**" component with custom fields. Is it possible?

### Environment

- dx-react-scheduler: "2.7.0"

**Comment by MaximKudriavtsev** [comment]
Hi @eugenio1590,

You can set the `readOnly` property to `true` for the `ResourceEditor` component to disable editing for a required resource field. Here is an example, where I created a custom `ResourceEditor` component and disabled editing for the `Room` resource: [CodesandBox](https://codesandbox.io/s/friendly-gareth-krcsu?file=/demo.js).
