### ISSUE TITLE
Popover from Material-UI re-renders whole table

### ISSUE THREAD

**Issue by ilterugur** [DevExpress/devextreme-reactive#3016]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When I use Popover from Material-UI on the React Grid, it causes the whole table to re-render on the trigger.
It also causes Material-UI Avatars and native html img elements with invalid sources to send another network request to the target source.

### Expected Behaviour

React Grid should not re-render itself when Popover from Material-UI is triggered.

### Steps to Reproduce

[CodeSandbox Link](https://codesandbox.io/s/admiring-cartwright-bsp5k)
Hover to the dates or right arrow icon on any row to trigger popover and reproduce the re-rendering bug.

### Environment

- @devexpress/dx-react-core: 2.7.0
- @devexpress/dx-react-grid: 2.7.0
- @devexpress/dx-react-grid-material-ui: 2.7.0
- @material-ui/core: 4.11.0
- @material-ui/icons: 4.9.1
- react: 16.13.1
- react-dom: 16.13.1

**Comment by LazyLahtak** [comment]
Hi @ilterugur,

When you trigger a render of the `Popover`, you change the application state and re-create the `Cell` component. Thus, on each change the Virtual Table gets a new component and re-renders each cell. To avoid this, we strongly recommend you define custom components outside the main component.
If you need to use data from the main component, you need to use the [React.useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback) hook. This hook allows you to avoid re-creating the `Cell` component and makes it possible to pass additional data to it. Here is an [example](https://codesandbox.io/s/laughing-brown-ou22e).
To get more information on performance optimizations, please refer to our guide: [React Components - Optimize Performance](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/).

**Comment by ilterugur** [comment]
Thanks a lot! You are really helpful. Much appreciated!

**Comment by LazyLahtak** [comment]
You are welcome!
