### ISSUE TITLE
Add posibility to show or not a line with a check box in the legend

### ISSUE THREAD

**Issue by bgrand-Lam** [DevExpress/devextreme-reactive#3017]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

I have much line in my chart and I want to do disappear some lines with a checkbox in the legend.

### Screenshots
![Annotation 2020-08-04 085858](https://user-images.githubusercontent.com/68049467/89263152-02fb8100-d631-11ea-895d-69cefd4d76cf.jpg)

**Comment by MaximKudriavtsev** [comment]
Hi @bgrand-Lam,

You need to override the Legend's components and render series by a condition. I've created an [example](https://codesandbox.io/s/quirky-surf-xt26w?file=/demo.js) illustrating how to do this.
