### ISSUE TITLE
Disable the allDay and repeat checkboxes in Scheduler

### ISSUE THREAD

**Issue by Sebcrk** [DevExpress/devextreme-reactive#3018]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Is there any way to disable the allDay and Repeat checkboxes? I'm getting a warning if I save a new appointment whitout using the recurrence option and its becoming a problem when trying to save in a database.
![image](https://user-images.githubusercontent.com/60935077/89359133-b2187680-d68a-11ea-806f-b287aabde4d1.png)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- chrome: 84.0.4147.105
- material-ui: 4.11.0

**Comment by MaximKudriavtsev** [comment]
Hi @Sebcrk,

To disable `allDay` and `repeat` checkboxes, you can override the `BooleanEditor` component in the `AppointmentForm` plugin. I have created an [example](https://codesandbox.io/s/cool-montalcini-6ekp1).

Regarding the warning, it's a mistake in our code and we will fix it soon. However, this bug cannot affect your application and database. I suggest you make sure that you correctly save data and use fields required for your database.

**Comment by Sebcrk** [comment]
Hi @MaximKudriavtsev, thanks for the answer. 
Unfortunately disabling the checkboxes doesn't solve the issue as seen below, and while it doesn't directly affect the connection with the database, the application does become slower and kind of crashes, but this may also be due to my computer, so its unclear.
![image](https://user-images.githubusercontent.com/60935077/89414263-bd51bd80-d6ef-11ea-8b9d-e10fa32e50fa.png)
To be honest, I don't know why this is happening because it's behaving like the commitChanges is inside a componentDidMount, but it isn't, and as I'm not that used to working with classes, I've been trying to make it work but something is clearly missing.

**Comment by MaximKudriavtsev** [comment]
@Sebcrk,

I have prepared a PR with a fix for this problem and we will merge it as soon as possible. BTW, you can use a production build for your application to increase the performance of your app.

**Comment by Sebcrk** [comment]
@MaximKudriavtsev , I was able to avoid the warning by assigning a value="" to the selectComponent while the PR is merged. Thank you for the rapid response, I'll be checking for that merge.
