### ISSUE TITLE
Older version of material-ui

### ISSUE THREAD

**Issue by rpkRED** [DevExpress/devextreme-reactive#302]
Hi! Can somebody tell me if is it possible for grid to work and if yes how with older version of material-ui e.g. v0.18.7?

**Comment by SergeyAlexeev** [comment]
Hi,

DevExtreme React Grid supports [Material UI](https://material-ui-1dab0.firebaseapp.com/) starting with v1.0.0*.

**Comment by Durairaj** [comment]
@rpkRED You can include both versions of material ui >1.0.0 and the version u are talking about in your application. ( since few components are not available in latest version of material ui for your application if thats the case)
