### ISSUE TITLE
export icon change(custom icon) in react grid express and place export icon outside grid

### ISSUE THREAD

**Issue by yshaik77** [DevExpress/devextreme-reactive#3023]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @yshaik77,

You can replace the default [ExportPanel.ToggleButton](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/export-panel/#exportpaneltogglebuttonprops) with your own button using the `toggleButtonComponent` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/export-panel/#properties) of the `ExportPanel` plugin.
To render this button outside the toolbar, I suggest that you use the [React Portal](https://reactjs.org/docs/portals.html) that renders an element outside the Grid. Here is an [example](https://codesandbox.io/s/red-forest-3v9wc). I attached the export button to `document.body`. Note that in the example I hid the empty [Toolbar](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/) using the [Toolbar.Root](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/#toolbarrootprops) component.

**Comment by sajidsheik** [comment]
i this example export button is attached to document.body can we have assigned to div tag in the same component file 
like <div><div id="selector"></div><Grid></Grid></div>

Can we have the export button inside the <div id="selector">

As the component is loading we dont get reference to <div id="selector">
how to handle this case

**Comment by LazyLahtak** [comment]
Components appear in the browser when you render them for the first time. Before that, they don't exist and you cannot get element references. I suggest that you use [React.useEffect](https://reactjs.org/docs/hooks-effect.html) to get the element reference after the first rendering of components. Then, store this reference in the component's state. Here is an updated [example](https://codesandbox.io/s/romantic-nobel-hyf3h).
