### ISSUE TITLE
LazyLoad does not work properly when using filter

### ISSUE THREAD

**Issue by bahamut657** [DevExpress/devextreme-reactive#3024]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
With lazyLoad enabled, if i search some value using the filter:
 - the filter works properly
 - I can see record placeholder for records disappered (seems that the grid expects the total numRows to be present)

### Expected Behaviour
- The total numRows must decrease if some records are filtered out

### Steps to Reproduce
1) Activate lazyLoad and  FilteringState + TableFilterRow
2) Apply some filter => The records disappeared are replaced by the loading placeholder

### Screenshots
No filter applied (only lazyLoad active)
![NoFiltering](https://user-images.githubusercontent.com/1759168/89633515-43af0080-d8a4-11ea-80d0-a7800cbf68d1.png)

After filter apply 
![FilterActive](https://user-images.githubusercontent.com/1759168/89633532-46a9f100-d8a4-11ea-99f0-5b67e8e80adc.png)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: ALL
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.1

**Comment by LazyLahtak** [comment]
Hi @bahamut657,

We have a demo on our site, where we use Lazy Loading with a filtering feature. Please refer to it: [React Grid - Virtual Scrolling with Remote Data: Lazy Loading. Row Caching](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#row-caching).
Note that in Lazy Loading mode the Virtual Table has no information about the total number of rows. For this reason you need to pass it to the `totalRowCount` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table-state/#properties) of the `VirtualTableState` plugin.
If you have any further questions, feel free to contact us.

**Comment by bahamut657** [comment]
I already use the `totalRowCount` and set it to the  MAX records I can extract from remote.
Because I use the `detailRow` plugin I have to increment by the current expanded rows.

Must I have to decrease by the records cutted off by the filter? How to do this?

For example:
1) I initialize the component with totalRowCount = 200
2) I apply a filter that cut off 198 records
=> I see the remaining 2 records, but, after these, there are record placeholders for the remaining part of the viewport (and the scrollbar can scroll for 200 records)

**Comment by LazyLahtak** [comment]
In the demo above, we send a new request on changing a filter and get new rows and a new total row count from the server. If you load rows only on initialization, I suggest that you use the Virtual Table without Lazy Loading. In this case, you won't need to calculate the total number of rows. Here is an [example](https://codesandbox.io/s/winter-grass-zz1qu).

**Comment by bahamut657** [comment]
Thank you @LazyLahtak 

In my case, I have all the rows loaded during intialization, but I use lazyLoad to send remote request to retrieve the decoration metadatas for each column in each row, based on the pageSize (so if I load the first 10 records I retrieve datas locally but I'm performing a request with recordIds on display, in order to retrieve missing metadata information).
The only way is re-calculate locally the totalRowCount? If so, I have to re-implement all the filter algorithms by myself?

I've used this approach, because if I don't use lazyLoad I cannot know which records are currently rendered (and I cannot retrieve allDatas metadata because the remote request got heavy calculation each row - so I have to minimize it). Can I use another approach?

Regards
Jacopo

**Comment by LazyLahtak** [comment]
The Lazy Loading mode was developed to work with remote data and is not able to recalculate total row numbers locally.
I suggest that you create a custom plugin, that will give you information about rendered rows. For this you need use the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/), which can get information about table rows in the viewport. Here is an [example](https://codesandbox.io/s/amazing-bash-0zijg).
To learn more about custom plugin development, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
Does this solution meet your requirements?

**Comment by bahamut657** [comment]
The issue is resolved. 
Using you suggestions I'm able to make the grid work correctly.
Best regards and thank you

**Comment by LazyLahtak** [comment]
You are welcome!
