### ISSUE TITLE
LazyLoad does not work properly with detailRow expanded

### ISSUE THREAD

**Issue by bahamut657** [DevExpress/devextreme-reactive#3025]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
If a detailRow is expanded, it result impossible to scroll the grid (if done it renders the same records or loading placeholder)

### Expected Behaviour
Scroll operation can be performed also with detailRow expanded

### Steps to Reproduce
1) Open one detailRow when lazyload is active
2) Perform a scroll operation => Records are replaced by placeholder and, sometimes, same records are re-rendered (even if the scroll is changed)

### Screenshots
No Detail Row Expanded (all renders correctly)
![noDetailRowExpanded](https://user-images.githubusercontent.com/1759168/89634569-e74ce080-d8a5-11ea-92dd-2ca89ff5a494.png)

Detail Row Expanded (one at the bottom of the grid)
![detailRowExpanded](https://user-images.githubusercontent.com/1759168/89634580-ea47d100-d8a5-11ea-80f1-06a1b3c361bb.png)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: ALL
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.1

**Comment by LazyLahtak** [comment]
Hi @bahamut657,

We have already registered a similar issue: #2564. Please refer to this [comment](https://github.com/DevExpress/devextreme-reactive/issues/2564#issuecomment-559658376).

**Comment by bahamut657** [comment]
The solution found in issue #2564 is working.
Addings some logic to onExpandedRowIdsChange to increment or decrement the total number of rows will do the job.
Thank you so much
