### ISSUE TITLE
Regarding junk characters in grid paging view

### ISSUE THREAD

**Issue by maris8838** [DevExpress/devextreme-reactive#3026]
I am using grid from devexpress/dx react grid and i am having issues on paging view down i have attatched the screenshot of grid view there is letter 'A' in paging view.could yoy please help me to fix it

**Comment by maris8838** [comment]
![Screenshot from 2020-08-08 10-58-11](https://user-images.githubusercontent.com/51428822/89703308-f6e02e00-d966-11ea-8d41-f51887373704.png)

**Comment by LazyLahtak** [comment]
Hello @maris8838,

I couldn't reproduce this issue. Could you modify my [example](https://codesandbox.io/s/ecstatic-burnell-eezcg) to reproduce this error? It will help us find a solution.
