### ISSUE TITLE
Smart row index column.

### ISSUE THREAD

**Issue by nikitxskv** [DevExpress/devextreme-reactive#3027]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Hi!

I want to add smart column with row index.
It means that when I do a filter on the table, the numbering of the rows is recalculated.
Example: I have a table:
```
1. Apple
2. Banana
3. Cherry
```
After filtering, we have only 1 and 3 lines left. In this case table should look like:
```
1. Apple
2. Cherry
```

Could you tell me how to do this, please?

**Comment by LazyLahtak** [comment]
Hi @nikitxskv,

I suggest that you create a custom plugin that will add the index column to the Grid using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). To simplify the process of getting the row index, you can send additional information to the [tableRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablerow) also using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). After that, you can define a table cell with the index value using [a ](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/)[Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/). Here is an [example](https://codesandbox.io/s/naughty-aryabhata-iosz8).
To learn more about custom plugin development, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
