### ISSUE TITLE
How to render TableRowDetail.ToggleCell button at the end of the row 

### ISSUE THREAD

**Issue by ddavydov** [DevExpress/devextreme-reactive#3028]
Is it possible to control the order of TableRowDetail.ToggleCell rendering? I'd like to render it as a last column
 

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @ddavydov,

I suggest that you create a custom plugin that will change the column order using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). Note that the plugin order is important and you need to place your plugin after the `TableRowDetail` plugin. Here is an [example](https://codesandbox.io/s/recursing-ramanujan-9bf8l).
To learn more about custom plugin development, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
