### ISSUE TITLE
Ability to add a column header to the toggleCellComponent in TableRowDetail

### ISSUE THREAD

**Issue by noahjstewart** [DevExpress/devextreme-reactive#3029]
### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello, my use case is pretty simple. I am using the toggleCellComponent to expand a row, like so:
![image](https://user-images.githubusercontent.com/35273789/89815289-89710080-db12-11ea-8f2c-86a14d27cf2a.png)

I'm looking to add a column header to the column with the expand icon, like this, highlighted in red:
![image](https://user-images.githubusercontent.com/35273789/89815380-aa395600-db12-11ea-9313-6bd2032e78b3.png)

**Comment by LazyLahtak** [comment]
Hi @noahjstewart,

The header cell above a column with toggle buttons is the `Table.StubHeaderCell` [component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#plugin-components) with a column's type `TableRowDetail.COLUMN_TYPE`. To customize this cell, you need to define the `stubHeaderCellComponent` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#properties) of the `Table` plugin with your custom component. Here is an [example](https://codesandbox.io/s/amazing-brahmagupta-bvwvg).
If you have any further questions, feel free to contact us.

**Comment by noahjstewart** [comment]
Thanks!

**Comment by LazyLahtak** [comment]
You are welcome!
