### ISSUE TITLE
Click on intersection of vertical scroll bar and horizontal scroll bar selects record when select on a row click is enabled

### ISSUE THREAD

**Issue by creddaiah** [DevExpress/devextreme-reactive#3030]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Clicking on intersection of vertical scroll bar and horizontal scroll bar selects a record when select on a row click is enabled. 

### Expected Behaviour

Selection should not happen on the click of intersection.

### Steps to Reproduce

1. Click on the intersection of vertical scroll bar and horizontal scroll bar when select on a row click is enabled.
2. Notice a record is getting selected. (THIS IS SPECIFIC TO ONLY WINDOWS)

https://codesandbox.io/s/ecstatic-bouman-kgssx?file=/demo.js

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: Chrome (Windows)  84.0.4147.105 (Official Build) (64-bit)
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @creddaiah,

I researched this behavior and found that it is reproduced with any `table` element. Here is an [example](https://codesandbox.io/s/mystifying-hertz-1trnh). Also, I reproduced this behavior in Chrome using Mac. I hope that the Chrome development team will fix this behavior in the future.
