### ISSUE TITLE
Validation in Batch Editing mode

### ISSUE THREAD

**Issue by rsbCodeZ** [DevExpress/devextreme-reactive#3033]
My use-case fits to use grid in batch editing mode as described in demo mentioned in the below ticket. 
https://github.com/DevExpress/devextreme-reactive/issues/2479 

I am trying  extend the demo mentioned to validate the data entered in the grid.

My approach is to use BatchDisplaying custom plugin to check for valid data if invalid data is found I render the cell in red color. 

But after this I'm unable to get the save/apply button disabled in-case of invalid data.  How does the save/apply button get disabled ?

**Comment by MaximKudriavtsev** [comment]
Hi @rsbCodeZ,

To accomplish this task, you can create a special property and pass it into the `BatchPanel` plugin.
