### ISSUE TITLE
React Grid Dev Express unselect all rows through external button

### ISSUE THREAD

**Issue by yshaik77** [DevExpress/devextreme-reactive#3034]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is there a way to unselect all the rows of the grid through external button. using external button i want to update the checked state of selected rows  .
Like similar functionality of uncheckall grid has.
Can't update the props of grid .

Thanks @LazyLahtak

**Comment by MaximKudriavtsev** [comment]
Hi @yshaik77,

To manually select or unselect rows, you need to use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode). Check this [example](https://codesandbox.io/s/proud-wildflower-m7g1q?file=/demo.js) illustrating selection.
