### ISSUE TITLE
When the Toolbar has more than 2 elements, conditionally showing GroupingPanel does not work

### ISSUE THREAD

**Issue by Feijo** [DevExpress/devextreme-reactive#3036]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When the Toolbar has more than 2 elements, conditionally showing `GroupingPanel` does not work.

### Expected Behaviour
Showing/hiding GroupingPanel based on a property should work regardless of how many items there are in the Toolbar.

### Steps to Reproduce

Create a Toolbar with 3 items, one being a GroupingPanel, and add a condition to show/hide the GroupingPanel:

```
<Toolbar />
{grouping && <GroupingPanel />}
<SearchPanel />
<ColumnChooser />
```

Link to the example that reproduces the issue: [Example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-co4ne?file=/index.js)

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: Chrome 84.0.4147.125
- material-ui: 4.11.0

**Comment by Feijo** [comment]
Any news about it?

**Comment by LazyLahtak** [comment]
Hi @Feijo,

We are still looking into this. As workaround I suggest that you place the `GroupingPanel` plugin after other plugins that render in the `Toolbar`. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-bjcse?file=/index.js).
