### ISSUE TITLE
How can i render Tree Data parent row's child rows under TableTreeColumn.Cell?

### ISSUE THREAD

**Issue by ilterugur** [DevExpress/devextreme-reactive#3037]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I want to render child rows of parent rows on TreeData React Grid when I expand the row using TableTreeColumn.ExpandButton component. I've linked states of Expand Button and Table to each other but I don't know what to do next. I need to use cellComponent prop on TableTreeColumn element because I need to customize tree data column of child rows (I actually want to remove unnecessary space of ExpandButton on child rows and I need to set a string character limit on tree data column cells). How can I achieve that?

Link to the example sandbox: [Sandbox Link](https://codesandbox.io/s/winter-breeze-r5rlz?file=/SummaryTableCell.js)

### Environment

- @devexpress/dx-react-core: 2.7.0
- @devexpress/dx-react-grid: 2.7.0
- @devexpress/dx-react-grid-material-ui: 2.7.0
- @material-ui/core: 4.11.0
- @material-ui/icons: 4.9.1
- react: 16.13.1
- react-dom: 16.13.1

**Comment by LazyLahtak** [comment]
Hi @ilterugur.

If you want to remove the space before `ExpandButton`, I suggest that you customize the [TableTreeColumn.Indent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-tree-column/#tabletreecolumnindentprops) component. Thus, you can reduce or remove this space. Here is an [example](https://codesandbox.io/s/winter-glade-s2b4l).
If you have any further questions, let us know.
