### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by eugenio1590** [DevExpress/devextreme-reactive#3042]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I need to add a context menu when a cell is empty. Is it possible? I do not want to override the default value for timeTableCellComponent because I am using [Kotlin Wrappers](https://github.com/JetBrains/kotlin-wrappers) to import the module and it is impossible to import DayView.TimeTableCell component for now.

### Environment

- @devexpress/dx-react-scheduler@: 2.7.0

**Comment by AryamnovEugeniy** [comment]
Hello!

One possible solution is to copy our implementation of the `TimeTableCell` into your code ([here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-table/cell.jsx) you can find how the TimeTableCell is implemented for the Day and Week views) and change it as you need to. After that you may use it to override the `timeTableCellComponent`.

Does this solution meet your requirements?

**Comment by eugenio1590** [comment]
> Hello!
> 
> One possible solution is to copy our implementation of the `TimeTableCell` into your code ([here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/views/vertical/time-table/cell.jsx) you can find how the TimeTableCell is implemented for the Day and Week views) and change it as you need to. After that you may use it to override the `timeTableCellComponent`.
> 
> Does this solution meet your requirements?

Hi @AryamnovEugeniy ,

Thanks for the quick response. It is a possible solution. But I expected to access the real implementation using a different namespace. I mean I'd like to import the component like that:

````
import TimeTableCell from '@devexpress/dx-react-scheduler-material-ui/MonthView';

or

import TimeTableCell from '@devexpress/dx-react-scheduler-material-ui/DayView';
````

**Comment by AryamnovEugeniy** [comment]
Unfortunately, it is impossible to import these components the you want to. You can import plugins and get access to component through these plugins (for example, `DayView.TimeTableCell`) but not their components directly. The reason for this is that we provide three main components: the Scheduler, Grid, and Chart. And Plugins for them. We do not provide other components as part of the DevExtreme Reactive. Those components (such as TimeTableCell) are meant to be used as parts for the Grid, Scheduler and Chart.

If you have any other question, feel free to open a new issue.
