### ISSUE TITLE
Setting default editing 

### ISSUE THREAD

**Issue by rsbCodeZ** [DevExpress/devextreme-reactive#3043]
Hi Team, 

My use-case fits to use grid in batch editing mode as described in demo mentioned in the below ticket.
https://github.com/DevExpress/devextreme-reactive/issues/2479

I want to set few cells editable by default in the above demo.

I tried  :
1. Setting `defaultEditingRowIds` but this doesn't work.
2. Setting `defaultEditingCells` this take an array but sets only 1 cell in editable state i.e  the last entry of the array elements

Please check this behavior.

 Thanks

**Comment by LazyLahtak** [comment]
@rsbCodeZ 

Based on your description, I assume that you don't need `Batch Editing`. I suggest that you use [editing in controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode) instead. Here is an updated [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-x3rdu).
For more information about controlled and uncontrolled modes, refer to our guide: [React Grid - Controlled and Uncontrolled Modes](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).
