### ISSUE TITLE
Display a custom component during edition

### ISSUE THREAD

**Issue by KLagdani** [DevExpress/devextreme-reactive#3045]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to codesandbox: https://codesandbox.io/s/optimistic-dubinsky-ek9bg

I use materialUI Avatar component to display images in my grid in the avatar column, and this column should not be editable.

The problem is that when I click on edit row, since I used a material ui component on the avatar column I have the following displaying:
[object Object]

Not very bad but not the prettiest... Is there a way to keep displaying the image using the material ui component, or to hide it completely during edition?

Snapshot:
I want to display the image with the material ui component during edition
![image](https://user-images.githubusercontent.com/21138162/90754218-e79f9f80-e2d9-11ea-9a67-5b474de87d26.png)

### Environment

- devextreme-reactive: ^2.7.0
- react: 16.13.1
- browser: any
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you follow [this](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/#custom-editors) guide and create a `DataTypeProvider` for the `Avatar` column. Here is a small example: https://codesandbox.io/s/boring-kowalevski-13brg?file=/demo.js:2150-2151

**Comment by KLagdani** [comment]
That will do! Great, thank you :)

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
