### ISSUE TITLE
Hide AppointmentTooltip when using custom AppointmentHeader IconButtons

### ISSUE THREAD

**Issue by doctorallen** [DevExpress/devextreme-reactive#3050]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I have the need to implement custom edit and delete events in the AppointmentTooltip (I'm displaying my own forms for these features), and I have been able to create a custom AppointmentHeader component to do so, however I need to hide the tooltip after the user clicks on the Edit or Delete buttons, because right now after the user deletes the event and the calendar refreshes with the new data, the tooltip is still displayed.

I have provided an example below, all I need to be able to do is hide the tooltip in my code on line 39 and 46 in my click events for the buttons. 

Link to the example that reproduces the issue: https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-forked-2g7ew

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by doctorallen** [comment]
Nevermind, I decided after a few hours of messing around with a customized AppointmentTooltip, that it was better to just created a controlled `Dialog` instead, and use an overridden `appointmentComponent` on the `Appointments` component. If anyone else finds this, [this](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointment-tooltip/#controlled-mode) documentation was helpful.

**Comment by boboci9** [comment]
Hi Allen,

Did you manage to remove the default appointment tooltip content completely? I would like to completely override the content as my design asks for a different setup. 
Thank you for your help in advance.

**Comment by AryamnovEugeniy** [comment]
Hello @boboci9 !

Let me answer your question. You can override AppointmentTooltip's Layout and add whatever content you need to. Here I made an example - https://codesandbox.io/s/optimistic-dream-h5iuo?file=/demo.js.

Does this solution solve the problem?
