### ISSUE TITLE
Reactive Scheduler build error in version 2.7.0

### ISSUE THREAD

**Issue by masull** [DevExpress/devextreme-reactive#3051]
../node_modules/@devexpress/dx-scheduler-core/dist/dx-scheduler-core.es.js
Module not found: Can't resolve 'rrule' in 'C:\work\cbd-phoenix\node_modules\@devexpress\dx-scheduler-core\dist'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
Compiling...
Failed to compile.

**Comment by JaegerJens** [comment]
https://www.npmjs.com/package/rrule version 2.6.5 is broken

**Comment by AryamnovEugeniy** [comment]
We have fixed this issue. I will update this thread once the release containing the fix is available.

**Comment by masull** [comment]
This issue does not seem to be fixed in version 2.7.0 of the devextreme native react scheduler. Is this a case issue for rRule and rrule?

**Comment by mandaxts** [comment]
Does anybody fix this issue?

**Comment by AryamnovEugeniy** [comment]
Hello!
We have fixed this issue with [this](https://github.com/DevExpress/devextreme-reactive/pull/3053) PR and now working on a new release (2.7.1). We will publish it as soon as possible.

**Comment by AryamnovEugeniy** [comment]
We have published the new release containing the fix. It is available on NPM.
