### ISSUE TITLE
The field I created specially appears on the appointment screen

### ISSUE THREAD

**Issue by turkdoktoru42** [DevExpress/devextreme-reactive#3054]
hello, I'm using the appointment plugin. I want the "customerName" field I created to appear on the appointment screen. How can I do that ?

In other words, I want the "customerName" field I created before to appear on the appointment screen.

Can you help me?

https://codesandbox.io/s/2wfsj?file=/demo.js
https://stackoverflow.com/questions/63558103/adding-a-custom-field-to-appointment-table-with-reactjs

**Comment by AryamnovEugeniy** [comment]
Hello!

if you want to show a custom editor (to edit `customerName`) inside the [AppointmentForm](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/), you can follow [this](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#customize-the-appointment-form) guide.
If you want to show `customerName` next to the appointment's title and date you can override the [AppointmentContent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentcontentprops) component (you can follow [this demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/integrated-data-shaping/): here we've overridden the `Appointments` plugin's `appointmentContentComponent` and shown appointment's `priority` and `location` aside from its `title`).

Let me know if this was helpful.

**Comment by fatihenerya** [comment]
yes, I've reviewed these examples and documents before. But I could not add it to the code I gave above. @AryamnovEugeniy

**Comment by AryamnovEugeniy** [comment]
In this case, could you clarify what you want to achieve? Because as far as I can see, the example you provided is a copy of our [demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/). And it is not completely clear what you mean by `appointment screen`.

**Comment by fatihenerya** [comment]
yes, i got your demo. I used this plugin as is. But I want to add "AppointmentContent". and I want to show the customerName field in this marked field


[https://ibb.co/8cjX2F9](url)

This way I want to show it on the screen


	const AppointmentFormContainer = withStyles(containerStyles, { name: 'AppointmentFormContainer' })(({
	   data, ...restProps
	}: AppointmentContainerBasic) =>  {

	  return (
		<Appointments.AppointmentContent {...restProps} data={data}>
		  <div className={classes.container}>
			<div>
			  {data.customerName}
			</div>
			<div className={classNames(classes.text, classes.content)}>
			  {data.customerSurname}
			</div>
		  </div>
		</Appointments.AppointmentContent>
	  );
	});

**Comment by fatihenerya** [comment]
Can you check the above code block?

**Comment by fatihenerya** [comment]
@AryamnovEugeniy please help me

**Comment by AryamnovEugeniy** [comment]
We've already had a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/2008). In short: when you try to do what you've done in the Code Block you've shared the default content of the appointment is replaced with your сщтеуте. So, you need to restore the default code if you need it (as suggested in the issue I mentioned) and then show the properties you need to show.
Let me know if this was helpful.

**Comment by turkdoktoru42** [comment]
yes, unfortunately I could not find how to show it.

**Comment by turkdoktoru42** [comment]
yes, unfortunately I could not find how to show it.

**Comment by turkdoktoru42** [comment]
also the original code is already running. But I want to show it on the appointment screen with the code snippet below. Or is there a different way


	 const AppointmentFormContainer = withStyles(containerStyles, { name: 'AppointmentFormContainer' })(({
		data, ...restProps
	 }: AppointmentContainerBasic) =>  {

	 return (
	<Appointments.AppointmentContent {...restProps} data={data}>
	  <div className={classes.container}>
		<div>
		  {data.customerName}
		</div>
		<div className={classNames(classes.text, classes.content)}>
		  {data.customerSurname}
		</div>
		</div>
	   </Appointments.AppointmentContent>
	   );
	 });


But this piece of code fails

**Comment by AryamnovEugeniy** [comment]
I updated our "Integrated Data Shaping" demo and it works for me: https://codesandbox.io/s/wizardly-sun-3jxfm?file=/demo.tsx. Could you clarify a bit further what you want to achieve?

**Comment by turkdoktoru42** [comment]
yes it will be like you do. But it is necessary to add it into the application below.

https://codesandbox.io/s/2wfsj?file=/demo.js

**Comment by turkdoktoru42** [comment]
yes it will be like you do. But it is necessary to add it into the application below.

https://codesandbox.io/s/2wfsj?file=/demo.js

**Comment by turkdoktoru** [comment]
Hello,

Can it be done this way?

I tried but it didn't work. Can you add it?



      render() {
        const {
          data,
          confirmationVisible,
          editingFormVisible,
          startDayHour,
          endDayHour
        } = this.state;
        const { classes } = this.props;

        const mapAppointmentData = () => ({
          ...this.state.data,
          startDate: data.StartDate,
          endDate: data.EndDate,
          customerName: data.Text,
          customerSurname: data.Text,
        });
    
        const formattedData = this.state.data ? this.state.data.map(mapAppointmentData) : [];

        return (
          <Paper>
            <Scheduler
              data={formattedData}
              height={660}
            >
              <ViewState
                onCurrentViewNameChange={this.currentViewNameChange}
              />
              <EditingState
                onCommitChanges={this.commitChanges}
                onEditingAppointmentChange={this.onEditingAppointmentChange}
                onAddedAppointmentChange={this.onAddedAppointmentChange}
              />
              <WeekView
                startDayHour={startDayHour}
                endDayHour={endDayHour}
              />
              <MonthView />
    
              <EditRecurrenceMenu />
              <Appointments />
              <AppointmentTooltip
                showOpenButton
                showCloseButton
                showDeleteButton
              />
              <Toolbar />
              <IntegratedDates
                startViewDateComputed={this.startViewDateComputed}
                endViewDateComputed={this.endViewDateComputed}
              />
              <ViewSwitcher/>
              <AppointmentForm
                overlayComponent={this.appointmentForm}
                visible={editingFormVisible}
                onVisibilityChange={this.toggleEditingFormVisibility}
              />
    
            </Scheduler>
    
    
    
          </Paper>
        );
      }

**Comment by AryamnovEugeniy** [comment]
I've updated the example from above and it worked for me: https://codesandbox.io/s/proud-bash-o610h?file=/demo.js (though it is necessary to add styles so that it would be displayed correctly. You can find our implementation of the AppointmentContent [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/appointment/vertical-appointment.jsx)).

Should you have any other issue, we will be happy to assist you.
