### ISSUE TITLE
Appointment tooltip content still shows the basic tooltip content as well as the personalized content

### ISSUE THREAD

**Issue by boboci9** [DevExpress/devextreme-reactive#3057]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
I am trying to override the tooltip content by changing the AppointmentTooltip contentComponent property but it will still show the default tooltip content on top of my content.

` <AppointmentTooltip
          contentComponent= MyTooltipContent
          headerComponent={() => <></>}
          visible={props.tooltipVisible}
          showOpenButton
          onVisibilityChange={props.toggleTooltipVisibility}
          showCloseButton
        />`

<img width="345" alt="Screen Shot 2020-08-25 at 1 27 17 PM" src="https://user-images.githubusercontent.com/9323474/91163775-c6262580-e6d6-11ea-97e6-d193c7e8062c.png">

### Expected Behaviour

I would expect only my content to show without the default content on top of mine.

### Steps to Reproduce
Looking at your examples on CodeSandbox I see when you edit the contentComponent your content get's completely overriden no default is showing so my question is is there any additional setting I need to use? 

### Environment

 "@devexpress/dx-core": "2.0.5",
 "@devexpress/dx-react-core": "2.0.5",
 "@devexpress/dx-react-scheduler": "^2.6.3"
 "@devexpress/dx-react-scheduler-material-ui": "^2.7.0"
 "@material-ui/core": "^4.10.2"
 "react": "^16.13.1"
"@material-ui/core": "^4.10.2"

**Comment by AryamnovEugeniy** [comment]
Hello!

One way is to override the `layoutComponent` as I've explained [here](https://github.com/DevExpress/devextreme-reactive/issues/3050#issuecomment-679946442). 
Another way is to follow the approach you suggest. But you will have to override the `contentComponent` completely. As far as I understand, you use our default implementation and provide it with your markup as a child. It will not override the default implementation though. The Tooltip will show its default content **and** your custom markup. To get rid of the default content, it is necessary to override the `contentComponent` completely. Here is an example - https://codesandbox.io/s/stoic-wescoff-nd2kt?file=/demo.js.

Does this meet your requirements?

**Comment by boboci9** [comment]
Hi, thank you for your quick reply. My problem is when I try to override the `contentComponent` I still have the basic content show up on the top. Can you help me on why this could happen?
https://github.com/DevExpress/devextreme-reactive/issues/3057

**Comment by boboci9** [comment]
Hi,

Thank you for your quick response, my error was that I was using the <AppointmentTooltip.Content in my tooltip implementation. It works well when I skip it. I am closing this issue. Best regards. Bogi
