### ISSUE TITLE
TableTreeColumn not working with Typescript - all props are mandatory even though they shouldn't be

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#3060]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The `<TableTreeColumn />` doesn't work with typescript 

### Expected Behaviour

The `<TableTreeColumn />` should work with typescript 

### Steps to Reproduce

Hi, I'm using the <TableTreeColumn /> tag with Typescript but I can't seem to get it to work with typescript. If I look at hte example posted, it tells me I only have to include the `for` field in the TableTreeColumn tag: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/ (see the first example). With typescript, I can't seem to use it if I don't declare all of the props, namely the `cellComponent`, `indentComponent`, `checkboxComponent` and `expandButtonComponent` props. However, I just want to use the out-of-the box features but I keep getting a static compilation error that says:

```
Type '{ for: string; expandButtonComponent: ({ visible, expanded, onToggle }: any) => Element | null; }' is missing the following properties from type 'TableTreeColumnProps': cellComponent, contentComponent, indentComponent, checkboxComponent
```

Is there any way to fix this? I've tried the following:

```
    const ContentComponent = (props : TableTreeColumn.ContentProps) => {
      return <ContentComponent {...props} />
    }

    const IndentComponent = (props : TableTreeColumn.IndentProps) => {
      return <IndentComponent {...props} />;
    }

    const CheckboxComponent = (props : TableTreeColumn.CheckboxProps) => {
      return <CheckboxComponent {...props} />
    }

    const ExpandButtonComponent = ({ visible, expanded, onToggle} : any) => {
      return <ExpandButtonComponent {...props} />
    }

    const Cell = ({ row, column, ...props }: TableCellProps) => {
        return <Table.Cell {...props} row={row} column={column} />
    }

   <TableTreeColumn
              for="name"  
              cellComponent={Cell}
              contentComponent={ContentComponent}
              indentComponent={IndentComponent}
              checkboxComponent={CheckboxComponent}
              expandButtonComponent={ExpandButtonComponent}
            />
```

And the typescript stops complaining but I can't see anything on my grid. Can we make these attributes optional? or is there a way to include them to using the default attributes?

### Environment

- devextreme-reactive: 2.4.1
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

I assume that you imported the TableTreeColumn plugin from the @devexpress/dx-react-grid package. All plugins in this package have no default components, and you need to define them. If you want to use the plugin with default components, you need to import it from another package: [TableTreeColumn Plugin Reference. Import](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-tree-column/#import).
Here is an [example](https://codesandbox.io/s/staging-snowflake-cn87r).

If you have any further question, feel free to contact us.
