### ISSUE TITLE
Scheduler - create appointment by selecting cells and release click

### ISSUE THREAD

**Issue by mitchobrian** [DevExpress/devextreme-reactive#3061]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler
- [x] React Week View @devexpress/dx-react-scheduler-material-ui

### Description
Hey, I am looking for an option to add appointments by selecting multi cells. The add new form should appear with the selected times from the cells. Could somebody help me out?

### Environment
- material-ui: yes

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product!
Unfortunately, the Reactive Scheduler does not support multiple cells selection.
If you would like to use multiple selection, however, you can use our React Wrappers. Please refer to our [documentation](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/). That scheduler does not open the AppointmentForm on mouse up but it opens the form on enter click.
