### ISSUE TITLE
Change filter logic from AND to OR

### ISSUE THREAD

**Issue by nikitxskv** [DevExpress/devextreme-reactive#3063]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi!

I want to change filter logic from AND to OR.
Suppose that I have table with two columns:
```
Name | Age
----------
Ivan |  21
Nick |  23
Alex |  17
```
Now if I set first column filter with `Ivan` value and second column filter with `23` value I'll got empty table. But I want to get table with two rows:
```
Name | Age
----------
Ivan |  21
Nick |  23
```
Could you tell how to do this, please?

**Comment by AryamnovEugeniy** [comment]
Hi!

We have already registered a similar issue: #2686. Please, refer to it.

If you have any other questions, we will be happy to assist you.

**Comment by nikitxskv** [comment]
Thank you very much!

**Comment by nikitxskv** [comment]
And what if I want to create more complicated filter? For example:
`firstColumn == 'Nick' && (secondColumn == 4 || thirdColumn == 'Apple')`
How can I do this?

**Comment by AryamnovEugeniy** [comment]
You can update `filterExpression` getter as i've done in this example: https://codesandbox.io/s/adoring-meitner-4sedo. I created a complex filter out of `name`, `gender` and `city` columns
Note, that this example only illustrates the approach, it may in several cases, for example, when a filter value is not provided for one of the columns I mentioned above. It is necessary to add logic that processes cases when, for example, one of the filters is empty. But approach will remain the same.
