### ISSUE TITLE
Scheduler - Locale is not formatting date correctly in appointment form

### ISSUE THREAD

**Issue by hunterbrown97** [DevExpress/devextreme-reactive#3064]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

The appointment form is formatting the dates as DD/MM/YYYY instead of MM/DD/YYYY despite setting the locale property to "en-US" in multiple places.

### Expected Behaviour

The appointment form will display the dates according to the given locale setting.

### Steps to Reproduce

`				<Scheduler
					data={eventData}
					height={(height-80-30)}
					locale={'en-US'}
				>
<AppointmentForm 
						layoutComponent={ApptFormLayout}
						basicLayoutComponent={ApptBasicLayout}
						recurrenceLayoutComponent={RecurrenceComponent}
					/>
{.....}
`

The property locale is set to 'en-US' in ApptBasicLayout component as well. Have also attempted to set the dateEditorComponent locale to no avail.

### Screenshots

![image](https://user-images.githubusercontent.com/59578324/91476234-4fb62e80-e862-11ea-9c37-6942676b50a9.png)

### Environment

    "@devexpress/dx-react-core": "^2.6.2",
    "@devexpress/dx-react-scheduler": "^2.6.2",
    "@devexpress/dx-react-scheduler-material-ui": "^2.6.2",
"react": "^16.13.1",
 "@material-ui/core": "^4.9.5",
 "devextreme": "^20.1.3",
    "devextreme-react": "^20.1.3",

**Comment by AryamnovEugeniy** [comment]
Hi @hunterbrown97,

We use editors from the Material UI library in the edit form. In this case, Scheduler uses date picker and you can specify the format option in the DateEditor component: https://codesandbox.io/s/date-change-forked-fz5fe?file=/demo.js:686-696

I see that this option is not mentioned in our documentation. We'll consider adding more information about editors' customization in future versions.

Should you have further questions, feel free to contact us.

**Comment by jox51** [comment]
FYI, The prop that needs to get passed to the Date Editor component is inputFormat, not format. Also the linked CodeSandbox has an error. I was able to get the date format to where I needed it but please update your documentation as nowhere does it say anything that inputFormat is a prop to the Date Editor component. Thank you.

[https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#appointmentformdateeditorprops](url)

`   <AppointmentForm.DateEditor
      {...restProps}
      excludeTime={excludeTime}
      inputFormat={"MM/DD/YYYY HH:mm"}
    />`
