### ISSUE TITLE
rRule Issue

### ISSUE THREAD

**Issue by omarazzi000** [DevExpress/devextreme-reactive#3065]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello All,

I would like to present my issue regarding the rRule which taking as a result from the recurrence table after repeat is on, only in case of repeat Monthly ==> first/second/third/last week the rRule which been created is like this:
RRULE:INTERVAL=1;FREQ=MONTHLY;COUNT=12;BYMONTHDAY=22,23,24,25,26,27,28;BYDA
Y=TH
This expression works correctly on Google calendar but when it goes to Outlook it doesn't work because of the recurrence rule. when I fix this expression for example to:
RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=-1TH
It works as I really want.

Please give me your advice

### Environment

![Screen Shot 2020-08-28 at 09 23 44](https://user-images.githubusercontent.com/60194387/91528428-62873c80-e910-11ea-8d87-be47606d1a8d.png)

**Comment by omarazzi000** [comment]
@AryamnovEugeniy Hello, 
This issue appears on wherever I test the rRule : it looks not understandable for the other calendars
Hope it's not a bug but could u please explain to me how we could fix this issue,
Our program's calendar after the appointment reserved automatically the event sent to the user as an email where the props of the event have the same which created from the Devextreme calendar.
Hope you can help me.
Best Regards

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product and your patience.
I've researched this behaviour. The recurrence rule that we generate is valid (for instance, you can try it out here: https://jakubroztocil.github.io/rrule/). But it seems that Outlook does not fully support iCalendar RFC that we use.
But we've found a way that would work with both the Reactive Scheduler and Outlook (and Google Calendar as well). So, I'm marking this issue as a bug and we will fix it as soon as possible.

**Comment by omarazzi000** [comment]
Hello again, 

Really thanks for your response,
Unfortunately, I got published my app and after many and many testing we found this issue in rRULE at only this specific case, as I mentioned before, it works in Devextrem calendar and at Google calender too, but when it goes to outlook in all of its versions it has been rejected because of the recurrence rule, 
The link you provided to me I used to simulate the dates on it and if you test the same case on it you will see some ununderstandable texts as in the attachment below especially rule.toText():
<img width="895" alt="Screen Shot 2020-09-01 at 20 16 36" src="https://user-images.githubusercontent.com/60194387/91885851-1a11ab00-ec91-11ea-8b7a-c7a3fb72a6a7.png">
 
This text is also important because I present it at many placed to explain the recurrence rule for the user.
The last test I did was creating an event(the same props of my issue) by Google calendar and decoding it to see how it's written I found it as:
RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=-1TH
I tried many times to convert the rRule which created from Devextrem to the previous one but I couldn't because (BYDAY: TH) It needs a number before the TH which of course impossible to do.
As you did explain that it's a bug and you're fixing it, and it would be highly appreciated if you can fix it ASAP.

Best Regards

**Comment by AryamnovEugeniy** [comment]
Hello!

I made a workaround that you can use while we are fixing this: https://codesandbox.io/s/elated-drake-z5mrk?file=/demo.js. Here I use Controlled Mode and validate the recurrence rule that I get after appointment was edited. If it is not correct, I use [RRule](https://github.com/jakubroztocil/rrule) to make it valid.

**Comment by omarazzi000** [comment]
@AryamnovEugeniy Waaaw!!!
Amazing,
Really I don't know how I can thank you, it fixes my issue and saves my project and it works very well till now, and I'm waiting to fix this issue in the future,
Really thanks again for your time and for your workaround function which gives what I really want
👍 👍 👍 👍 💯 👍 👍 👍

**Comment by AryamnovEugeniy** [comment]
We have fixed this issue. The fix will be available in the next release.
