### ISSUE TITLE
Apply filter when onBlur event occurred

### ISSUE THREAD

**Issue by nikitxskv** [DevExpress/devextreme-reactive#3068]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi!

I have filters in my table. And I don't want to apply them immediately, but after I've finished typing. In other words, when the onBlur event occurred.

Could you tell how to do this, please?

**Comment by LazyLahtak** [comment]
Hi @nikitxskv,

I suggest that you define the `editorComponent` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#properties) of the TableFilterRow plugin by a custom [TableFilterRow.Editor](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/#tablefilterroweditorprops) component. Thus, you can get the `onChange` handler from the component's properties and call it manually. Please refer to the [example](https://codesandbox.io/s/cool-cookies-rm8uj) where we call this handler when the component loses focus.

If you have any further questions, feel free to contact us.
