### ISSUE TITLE
How do I pass my own props to scheduler beside data for Scheduler

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#3069]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [v] React Scheduler

### Description

I'm trying to pass my own props to exist scheduler component, but have a really hard time. I only get the props from the data I pass in, but I need more. Can someone give me a suggestion? Thank you.
Like how I pass this test props to `Appointment` and `AppointmentContent` component? 

```
<Appointments 
       test={"testing"}
       appointmentComponent={Appointment}
       appointmentContentComponent={AppointmentContent}
  />
```

Try to that on Scheduler, not working also
```
<Scheduler test={"testing"}
   data={data}
  >
```
[Code sample](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/overview/)
Thanks for the help!
### Environment
- devextreme-reactive: 2.7.1
- react: 16.8
- browser: Chrome
- material-ui: 4.11

**Comment by AryamnovEugeniy** [comment]
Hello!

You cannot pass custom properties into the Scheduler itself. But you can override components and, for example, use React.useCallback. Here I made a small example: https://codesandbox.io/s/festive-hoover-sqx2l?file=/demo.js.
You can also refer to our guide on how to access a parent's state correctly: https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly
