### ISSUE TITLE
Make Filter row unfixed in Virtual Table

### ISSUE THREAD

**Issue by nikitxskv** [DevExpress/devextreme-reactive#3070]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi!

I have a virtual table with filters. And I have a two questions.
1) It is possible to make filter row unfixed?
2) It is possible to make header row unfixed?

Thank you!

**Comment by LazyLahtak** [comment]
Hi @nikitxskv,

Thank you for your interest in our Grid.
Unfortunately, there is no property or component with which you can make header rows mobile in a virtual table. However, all header rows (including the filter row) are placed in a separate sticky table. I suggest that you define the `position: unset !important` style for all tables using `CSS`. Here is an [example](https://codesandbox.io/s/youthful-ellis-0u6z3).
Please let me know if this solution is suitable.
