### ISSUE TITLE
Exporter downloads file twice in Strict Mode

### ISSUE THREAD

**Issue by Feijo** [DevExpress/devextreme-reactive#3071]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When the application is running in Strict Mode and the export button is clicked the browser downloads the file twice.

### Expected Behaviour
It should only download the button once per click.

### Steps to Reproduce
1. Get any examples from the official documentation https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export
2. Edit the `index.js` file and wrap the `<Demo />` tag with `<React.StrictMode>`
3. Click the export button
4. The browser will download the file twice

Link to the example that reproduces the issue: [example](https://codesandbox.io/s/fragrant-sun-l5d1p).

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- browser: Chrome 85.0.4183.83
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

Strict Mode renders components twice in Development Mode in order to detect any problems in the code. But it does not affect [Production Mode](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build). So, we advise you to use Production Mode with the Grid Exporter.
