### ISSUE TITLE
How to hide the "Detail Row button" for some rows?

### ISSUE THREAD

**Issue by Feijo** [DevExpress/devextreme-reactive#3074]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
In my application some rows don't have details. Is there a way to hide the expand button conditionally?

https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/detail-row/

Example of the desired result:
![DetailRow](https://user-images.githubusercontent.com/1585710/92229720-03bc5700-eefe-11ea-8e69-d171d30140a4.png)

**Comment by MaximKudriavtsev** [comment]
Hi @Feijo,

We have already had a similar issue. You may refer to it: #1266.
