### ISSUE TITLE
Adjusting the column height in the grid table

### ISSUE THREAD

**Issue by turkdoktoru** [DevExpress/devextreme-reactive#3076]
Hello there,

I am using grid table. I have codes as follows. I cannot adjust column heights. So I want to adjust the column height. Is there a way to do this?

    this.state = {
          pageSizes:[5,10, 20, 30],
          columns:[
            {name: "totalDebt", title: "Borç"},
            {name: "receivedAmount", title: "Alınan"},
            {name: "description", title: "Açıklama"},
            {name: "paymentDate", title: "Ödeme Tarihi"},
            {name: "first_name", title: "Adı"},
            {name: "last_name", title: "Soyadı"}
          ],
          defaultColumnWidths:[
            {columnName: "totalDebt", width: 65},
            {columnName: "receivedAmount", width: 65},
            {columnName: "description", width: 85},
            {columnName: "paymentDate", width: 80},
            {columnName: "first_name", width: 80},
            {columnName: "last_name", width: 80}
          ],
          columnBands: [
            {
              title: 'İşlem Sahibi',
              children: [
                { columnName: 'first_name' },
                { columnName: 'last_name' },
              ],
            },
          ],
          totalSummaryItems: [
            { columnName: "totalDebt", type: "sum"},
            { columnName: "receivedAmount", type: "sum"}
          ]
        }

        <div>
          <Grid
                rows={this.state.debtItems}
                columns={this.state.columns}
              >
                <EditingState
                  onCommitChanges={this.commitChanges}
                  columnExtensions={[
                    {columnName: "first_name", editingEnabled:false},
                    {columnName: "last_name", editingEnabled:false},
                  ]}
                />
                <PagingState
                  defaultPageSize={5}
                  defaultCurrentPage={5}
                />

                <IntegratedPaging />
                <Table />
                <TableColumnResizing
                  defaultColumnWidths={this.state.defaultColumnWidths}
                />

                <TableHeaderRow />
                <PagingPanel
                  pageSizes={this.state.pageSizes}
                  messages={this.pagingPanelMessages}
                />
                <TableEditRow />
                <TableBandHeader
                  columnBands={this.state.columnBands}
                />
              </Grid>
        </div>

**Comment by AryamnovEugeniy** [comment]
Hello,

I suggest you customize `TableBandHeader`'s `cellComponent` and `TableHeaderRow`'s `cellComponent`. Here is an example: https://codesandbox.io/s/floral-sound-2we2j?file=/demo.js
