### ISSUE TITLE
Reactive Grid - VirtualTable - It's not possible to reset the current loading state if infiniteScrolling is `true`

### ISSUE THREAD

**Issue by DevExpressSupportTeam** [DevExpress/devextreme-reactive#3077]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### I'm using ...
- [x] Reactive Grid

**Example:**
https://codesandbox.io/s/reative-grid-reset-state-after-filtering-6rnb1?file=/demo.js

**Steps:** 
1. Open the example
2. Scroll the grid multiple times to load 80-100 rows
3. Click on the "Change Filter" button
4. Try scrolling the grid 

**Actual behavior:**

Grid stops loading records after scrolling multiple pages

**Expected behavior:**

Grid should load the next pages

**Comment by artyil** [comment]
Hi, do you have plans to solve it in next release?
