### ISSUE TITLE
Support select all in ColumnChooser

### ISSUE THREAD

**Issue by NguyenTheSon** [DevExpress/devextreme-reactive#3078]
How can I add item select all in ColumnChooser?

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you use `ColumnVisibility` in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-visibility/#controlled-mode) and customize `ColumnChooser`'s [Container](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#columnchoosercontainerprops). You will need to add one more item to that container - an item that would select/unselect all columns. Here I made an example illustrating this approach in action: https://codesandbox.io/s/elegant-mayer-erl0p?file=/demo.js

**Comment by NguyenTheSon** [comment]
Thank you for your help! 👍

**Comment by AryamnovEugeniy** [comment]
You are welcome!
