### ISSUE TITLE
Adding onClick event to a row or column to interact with react-router-dom

### ISSUE THREAD

**Issue by qtzar** [DevExpress/devextreme-reactive#3079]
I've searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description

I have been following the instructions to use rowComponent to add a generic onClick event to all the rows in the table and I can can successfully get the json string contents of the clicked row to appear in an alert however I cannot figure out how to then use that row data to navigate to a new page via the react-router-dom's useHistory hook.

I'd also rather do this by adding a new column to my grid that displays a icon that can be clicked on to navigate to the new page but can't figure out a way to add custom cols that don't come from the backend data source.

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- react-router-dom: 5.2.0
- browser: Chrome 86.0.4240.22
- bootstrap: 4.5.2
- react-bootstrap: 1.3.0
- material-ui: none

**Comment by qtzar** [comment]
I have figured out the first part of the question. The examples on the documentation site show the setup of the TableRow const outside of the react functional component, moving that setup to inside the function component allowed me to get access to the useHistory hook in my onClick handler.

```
    const history = useHistory();
    const TableRow = ({row, ...restProps}) => (
        <Table.Row {...restProps} onClick={() => history.push(`/mypath/${row.id}`)} style={{cursor: 'pointer'}} />
    );
```

However I am still at a loss as to how to add a custom column with a clickable icon to a row.

**Comment by LazyLahtak** [comment]
Hi @qtzar,

I suggest that you create a custom [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/), where you will add additional column using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). After that, you need to define the [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/) for column cells, to render content. Here is an [example](https://codesandbox.io/s/beautiful-margulis-nwexu).
To learn more about custom plugins, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
If you have any further questions, feel free to contact us.
