### ISSUE TITLE
How can I custom scheduler toolbar styling? 

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#3080]
I'm using ...
 React Grid
 React Chart
[v] React Scheduler

Description
1. Can I pass the month the viewing in the toolbar?
2. How can I custom style toolbar, I have tried things below does not work.
(I also check the custom appearance styling documentation here: https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/)
```
<Toolbar
    //  classes={{root: classes.toobar}}
    // className={classes.toobarCalendar}
    flexibleSpaceComponent={FlexibleSpace}
/>
```
[Code sample
](https://codesandbox.io/s/nice-merkle-oe4qn?file=/demo.js)
Thanks for the help!

Environment
devextreme-reactive: 2.7.1
react: 16.8
browser: Chrome
material-ui: 4.11

**Comment by AryamnovEugeniy** [comment]
Hello!

You can customize both [Root Component](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/toolbar/#toolbarrootprops) and [FlexibleSpace Component](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/toolbar/#toolbarflexiblespaceprops). You can also use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/date-navigation/#controlled-mode) to control the current date.
Here I made a small example: https://codesandbox.io/s/condescending-euler-j6hcu
