### ISSUE TITLE
Tooltips on ellipsis in grid

### ISSUE THREAD

**Issue by stormaction** [DevExpress/devextreme-reactive#3081]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello,

I'm using React Grid 2.7.1 and I would like to know if you will add the tooltips when the ellipsis shows up in the grid. Or do you have an idea how to do it ?

**Comment by LazyLahtak** [comment]
Hi @stormaction,

We have a demo on our site, where we add a tooltip for a cell component. Please refer to this guide: [React Grid - Data Formatting. Cell Tooltip](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/#cell-tooltip). Also, you can enable word wrapping for some columns to show full cell content without ellipses. Refer to the following guide: [React Grid - Fundamentals. Multiline Cells](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#multiline-cells).
If you have further questions, fell free to contact us.
