### ISSUE TITLE
Disable column virtualization

### ISSUE THREAD

**Issue by nikitxskv** [DevExpress/devextreme-reactive#3082]
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi!
Could you tell when you fix this problem: https://github.com/DevExpress/devextreme-reactive/issues/2974 ?
Thank you!

**Comment by artem-kurchenko** [comment]
HI @nikitxskv 

We don't have a precise date and will update our [Roadmap](https://js.devexpress.com/Roadmap/) if we start working on it.

If this is a must-have requirement for your application, consider using our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/HorizontalVirtualScrolling/React/Light/). You can set [columnRenderingMode](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/scrolling/#columnRenderingMode) to "standard" to achieve the same behavior.

Thanks,
Artem

**Comment by nikitxskv** [comment]
@artem-kurchenko 
Maybe it is possible to change current row style looking on row data?
Or increase number of out-of-screen column that are loaded along with visible columns?
It is very important for our table to have this functionality and it is pretty expensive for us to replace `@devexpress/dx-react-grid` with `devextreme-react/data-grid`

**Comment by nikitxskv** [comment]
Hi, @artem-kurchenko!
Is there any news?:)

**Comment by LazyLahtak** [comment]
Hi @nikitxskv,

I suggest that you define custom styles based on row data using the rowComponent property of the Virtual Table plugin. Please refer to our demo: [React Grid - Fundamentals. Customize the Appearance. Rows](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#rows). Note that if you change VirtualTable's row height, you will need to define the `estimatedRowHeight` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#properties).

Our React Grid doesn't have any option to disable column virtualization. I suggest that you create your own plugin with the `viewport` Getter. Here is an [example](https://codesandbox.io/s/vigilant-driscoll-6gu9f?file=/demo.js). Note that `viewport` is our non-documented [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/), it may be changed in the future. Also, changing this getter may lead to unexpected behavior in certain scenarios.

To learn more about custom plugins, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).

**Comment by nikitxskv** [comment]
@LazyLahtak Thank you very much!

**Comment by LazyLahtak** [comment]
You are welcome!

**Comment by sukiasyan** [comment]
> Hi @nikitxskv,
> 
> I suggest that you define custom styles based on row data using the rowComponent property of the Virtual Table plugin. Please refer to our demo: [React Grid - Fundamentals. Customize the Appearance. Rows](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#rows). Note that if you change VirtualTable's row height, you will need to define the `estimatedRowHeight` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#properties).
> 
> Our React Grid doesn't have any option to disable column virtualization. I suggest that you create your own plugin with the `viewport` Getter. Here is an [example](https://codesandbox.io/s/vigilant-driscoll-6gu9f?file=/demo.js). Note that `viewport` is our non-documented [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/), it may be changed in the future. Also, changing this getter may lead to unexpected behavior in certain scenarios.
> 
> To learn more about custom plugins, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).

Awesome. Working perfectly good. Thanks man
