### ISSUE TITLE
TableEditColumn custom action (custom handling click event)

### ISSUE THREAD

**Issue by adrsr** [DevExpress/devextreme-reactive#3087]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello,

I would like to add a simple TableEditColumn with only the edit button :

`           
 <TableEditColumn
              showEditCommand
            />
`

and handle myself the click event on the edit command without using any reactive stuff.
To illustrate, that would be something like that :

`
            <TableEditColumn
              showEditCommand
              onEditCommandClick={handleClickEditCommand}
            />
`

What's the correct way to do that ?

Thank you very much for your help !

**Comment by AryamnovEugeniy** [comment]
Hello!

You can customize `TableEditColumn`'s [Command Component](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncommandprops). Here is a small example: https://codesandbox.io/s/dreamy-sunset-wfpkz?file=/demo.js

**Comment by adrsr** [comment]
this is perfect, thank you !
