### ISSUE TITLE
Fixed header without virtual scrolling

### ISSUE THREAD

**Issue by creddaiah** [DevExpress/devextreme-reactive#3088]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I was going through this bug [https://github.com/DevExpress/devextreme-reactive/issues/896](url) and I see it is closed without any solution.
I would like to know if you have any plans in having fixed header with Table plugin. I know this works with Virtual table but we need the fixed header even for Table.

### Environment

- devextreme-reactive: 2.7.1
- react: 16.10.2
- browser: Google chrome 85.0.4183.102
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.7

**Comment by AryamnovEugeniy** [comment]
Hi!

We don't have a precise date and will update our [Roadmap](https://js.devexpress.com/Roadmap/) if we start working on it.

If this is a must-have requirement for your application, consider using our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/React/Light/). It works there by default. You just need to specify the `height` property.
