### ISSUE TITLE
Labelling axis

### ISSUE THREAD

**Issue by tomasaschan** [DevExpress/devextreme-reactive#3089]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

One of the first things one learns about plotting is that a plot with unlabelled axes could say basically anything, and therefore says nothing. Still, it seems like axis labels is not properly supported by this charting library!

https://stackoverflow.com/questions/63958444/how-do-i-create-an-axis-label-for-my-chart?noredirect=1#comment113099447_63958444

What I'd like, is a simple way to add some text below the x-axis on e.g. this graph, that says what the values on the axis represent:
![image](https://user-images.githubusercontent.com/1550920/93616112-9536c900-f9d4-11ea-8566-833c5686a089.png)

On this screenshot, I have manually edited the `svg` to add another text node, to illustrate what I'm after:
![image](https://user-images.githubusercontent.com/1550920/93616351-ec3c9e00-f9d4-11ea-8ebe-8f45fad63be6.png)

Note the text "Response Rate [%]" at the bottom. If this is already possible, how do I add it? Could the docs be made clearer on this?

**Comment by AryamnovEugeniy** [comment]
Hello!

We do not provide such a possibility out of the box. But you can customize this. Here is a small example: https://codesandbox.io/s/brave-snowflake-nte1y?file=/demo.js.
If you want to use this feature out of the box, you may try our[ Chart for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/SideBySideStackedBar/React/Light/).

Regards,
Eugeniy

**Comment by tomasaschan** [comment]
@AryamnovEugeniy Yeah, I realize you're not providing this. My point was to request this feature 😄

As noted, it is very much a best practice in any type of plotting to label your axes, so not being able to do this out of the box makes the library significantly less useful. I've taken a look at Chart for React, but did not see anything about axis labels there either... 😕 In addition, the whole _point_ of using this component was to get the Material UI look, since that goes well with the rest of our application. Thus, my option would be to go to the raw Google libraries, not to use another of your chart components.
