### ISSUE TITLE
Feature Request: add sticky header to normal table

### ISSUE THREAD

**Issue by Nipodemos** [DevExpress/devextreme-reactive#3090]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I have a design to follow, which includes to have pagination from server side. Unfortunaly i can't use the virtual scrolling because the design is to make with the pagination

I'm trying a lot to make a sticky header to work, but i could not get it to work
I tried what @tmaiaroto suggested here: https://github.com/DevExpress/devextreme-reactive/issues/896#issuecomment-597799097 (by the way thank you for that man, thanks a lot!) but still does not work perfectly for my use case

The header was indeed being sticky, but it disappears half of it when scrolling. I don't know if is my code or is the Grid code that is causing that

Also the first column have it's name in header overlaped

Here is the closer i could get to what I want:
![GbPOaZk2CX](https://user-images.githubusercontent.com/11494727/93692607-b9290600-facb-11ea-9f6e-f61a9162af04.gif)

**Comment by LazyLahtak** [comment]
Hi @Nipodemos,

We have no plans to implement this feature in the immediate future. You may follow our [Roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed if we start working on it.
If you need this feature, you can use our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/React/Light/). It works there by default.

If you have any further questions, feel free to contact us.
