### ISSUE TITLE
Color change in the scheduler

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3092]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello! I am new to both Material-UI and to your scheduler, which I need for a service I'm developing. Maybe it's a dumb question, but I can't really seem to find a way to change the color palette of the Scheduler component. It was fine at the beginning, but I changed the default secondary color and now I have basically a white text/white background situation. How can I set the text of the <Scheduler /> to be theme.palette.primary.main?

### Environment

- devextreme-reactive: 2.7.1
- react: 16.4.1
- browser: Microsoft Edge
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

Could you clarify what you want to achieve? A screenshot would be helpful. You could also update my example (where I changed primary and secondary colors) to illustrate the issue you've encountered: https://codesandbox.io/s/elastic-borg-hb51y

**Comment by GRawhideMart** [comment]
> Hello!
> 
> Could you clarify what you want to achieve? A screenshot would be helpful. You could also update my example (where I changed primary and secondary colors) to illustrate the issue you've encountered: https://codesandbox.io/s/elastic-borg-hb51y

No need, I solve it. I passed to it an isolated ThemeProvider just for the scheduler
