### ISSUE TITLE
Show top selection checkbox checked is set even when row is collapsed?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#3097]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is there a way to set the "selection" checkbox header to be set to "selected" even if the selected row is collapsed? I tried to use the Integrated Selection plugin before the Tree plugin so that selection would happen before the expand/collapse of the rows but that doesn't seem to work. Here's my code:

```            
              <SelectionState
                selection={selection}
                onSelectionChange={(selected) =>
                  setSelection
                    ? setSelection(selected)
                    : () => {
                        /* do nothing */
                      }
                }
              />
            <IntegratedSelection />
              <TreeDataState
                expandedRowIds={allExpandedRowIds}
                onExpandedRowIdsChange={setAllExpandedRowIds}
              />
            {expandRows && <CustomTreeData getChildRows={getChildRows} />}
```

Any ideas how to alleviate this?

Thanks!

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

Here is an [example](https://codesandbox.io/s/jovial-cookies-ehyom). In it, I select a collapsed row, and the header checkbox shows it.
Does the sample above meet your needs? If not, could you please clarify your scenario?
