### ISSUE TITLE
Custom logic to show selected Table Cell as disabled?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#3098]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Hi, I have some custom logic where I want to display the Table Selection Cell as disabled and unselected. For example, this is what I would want:

`<TableSelection 
              cellComponent={(props) => props.row.shouldDisable ? <TableSelection.Cell {...props} selected onToggle={() => {}} disabled />  :<TableSelection.Cell {...props} />}
              showSelectAll />
`

Is there any way to do this without making a custom component? If I need to make a custom component, how would I do so with Typescript? I tried to return an object from Material-UI that looks something like this:

`
getDisabledCheckbox = () => (
<TableSelection.Cell {...props}> <Checkbox disabled /> </TableSelection.Cell>
) 
`
But this just renders a checked box no matter what I put in between the `TableSelection.Cell` tag.

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

Here is an [example](https://codesandbox.io/s/hardcore-noether-lhogi). In it, I create a custom `TableSelection.Cell` component with TypeScript.
Also, the `TableSelection.Cell` component doesn't render children. If you need to render custom content in this cell, I suggest that you render a custom `Table.Cell` instead. Here is an [example](https://codesandbox.io/s/festive-ramanujan-0w6h7).

If you have any further questions, let us know.
