### ISSUE TITLE
Grid : getting row id when editing a row

### ISSUE THREAD

**Issue by adrsr** [DevExpress/devextreme-reactive#3099]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Description

Hello,

My question is related to my previous one (which is solved, thank you) : https://github.com/DevExpress/devextreme-reactive/issues/3087

Having a look at this code from @AryamnovEugeniy  : https://codesandbox.io/s/dreamy-sunset-wfpkz?file=/demo.js

We have a custom commandComponent called `EditButton`

I want to get the **row id** on which we have clicked on the edit button. So in this example I would show the id in the alert popup. How to do that ?

Note : I need to get the ID before the commitChange

Thank you for help

### Environment

- devextreme-reactive: last version
- react: last version
- material-ui: last version
- typescript : last version

**Comment by AryamnovEugeniy** [comment]
Hello!

To achieve this, you need to create a custom plugin (here is our guide on custom plugin development: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/). In it, you will be able to determine the id of the row being edited. Here I made a small example: https://codesandbox.io/s/dreamy-sunset-wfpkz?file=/demo.js. You may also take a look at this PR (a popup editing demo will be implemented this way): https://github.com/DevExpress/devextreme-reactive/pull/2945/files#diff-65c584bb28939037303cc3a1fc60c3edR1-R154. The example I made is based on this PR.

**Comment by thatPranav** [comment]
The above example gives an array of ids of ALL rows that are being edited. Is there any way to get the id of the row that is being COMMITTED?
