### ISSUE TITLE
Reactive Grid - Rows no more displayed when totalCount > ~300000

### ISSUE THREAD

**Issue by QuentinLuc** [DevExpress/devextreme-reactive#3100]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Hey!  I'm trying to use the Grid with Virtual Scrolling and Remote Data to display a large amount of data (> 300000 rows).  The Grid works really well when totalCount doesn't exceed ~300000.  Over that, when you scroll to the items after that limit, the Grid always displays the loading "grey block" or it's even totally blank sometimes.  If you inspect the page, you'll see the data are there but they're hidden (second screenshot)
Is it a limitation of the Grid or an actual bug?

### Steps to Reproduce
I've forked one of your pre-configured examples and modified it to illustrate the bug: https://codesandbox.io/s/sweet-worker-dowcj?fontsize=14&hidenavigation=1&theme=dark
I've set the MAX_ROWS variable to 300000 to make it work.  You can change it to 400000 then scroll to reproduce the bug.

### Screenshots
<img width="1264" alt="Screenshot 2020-09-28 at 12 10 44" src="https://user-images.githubusercontent.com/5237095/94419960-bee5b200-0183-11eb-9e4a-88eea26a6245.png">
<img width="1966" alt="Screenshot 2020-09-28 at 12 16 23" src="https://user-images.githubusercontent.com/5237095/94420572-a4f89f00-0184-11eb-8958-a3c96bef94a8.png">

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.x
- browser: Chrome 85.0.4183.121
- bootstrap: none
- dx-react-grid-bootstrap4: 2.7.1
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @QuentinLuc,

This is a bug, we have already registered the [issue](https://github.com/DevExpress/devextreme-reactive/issues/2490). We cannot say when this bug will be fixed, it requires a lot of refactoring.
If you need to use a grid with a large amount of data, you can use our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/React/Light/), which has no such problem.

**Comment by QuentinLuc** [comment]
Hey @LazyLahtak !  Okay thanks and sorry for the duplicate, I didn't find the other existing one.
