### ISSUE TITLE
Integrate scheduler with Redux

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3102]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I am trying to integrate the scheduler editing (starting from [this](https://codesandbox.io/s/uh9ki) sandbox), but I'm having a hard time doing so.
So far, I have:
* created the store, the reducers and the action to add an appointment like so: 
```
// start data
const SCHEDULERDATA = [
  {
    startDate: "2020-09-24T09:45",
    endDate: "2020-09-24T11:00",
    title: "Meeting",
    room: 1,
  },
  {
    startDate: "2020-09-24T12:00",
    endDate: "2020-09-24T13:30",
    title: "Go to a gym",
    room: 2,
  },
];

// action creator
const ADD_BOOKING = 'ADD_BOOKING';

const addBooking = (startDate, endDate, title, room) => ({
    type: Actions.ADD_BOOKING,
    payload: {
        startDate,
        endDate,
        title,
        room
    }
})

// reducer
export const SchedulerData = (state = SCHEDULERDATA, action) => {
    switch(action.type) {
        case ADD_BOOKING:
            var booking = action.payload;
            return state.concat(booking);
            
        default:
            return state;
    }
}
```

* mapped the dispatch to props in the calling component, like so:
```
const mapDispatchToProps = (dispatch) => ({
  addBooking: (startDate, endDate, title, room) =>
    dispatch(addBooking(startDate, endDate, title, room)),
});
// some code in between, including constructor and render method opening
<SchedulerPresentation
                  schedulerData={schedulerData.filter(      //schedulerData comes from a mapStateToProps
                    (event) => event.room === 1
                  )}
                  addBooking={addBooking}
                />
```

But if I call `this.props.addBooking(added.startDate, added.endDate, added.title, added.room)` in the commitChanges method, it does not work, generating ![this](https://user-images.githubusercontent.com/62698128/94453123-9d4eef80-01b0-11eb-95d1-c3b3f01f9d5f.PNG) error. Can someone help me figure this out?

[This](https://codesandbox.io/s/heuristic-dubinsky-3mlwr) is a sandbox of the full project.

### Environment

- devextreme-reactive: xxx
- react: ^16.13.1
- browser: Microsoft Edge
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0
- redux: ^4.0.5
- react-redux: ^7.2.1

**Comment by AryamnovEugeniy** [comment]
Hello!

I updated your example: https://codesandbox.io/s/xenodochial-elbakyan-6o5kv?file=/src/components/SchedulerComponent.js.
I changed:
1) `commitChanges` method - you do not need to save new appointments into SchedulerComponent's state if you use redux.
2) `SchedulerComponent`'s render method - I take appointments from props instead of its state.
3) `SchedulerData` reducer - I save a new instance of appointments array to trigger rerender.

If you have any other questions, we will be happy to answer them!
