### ISSUE TITLE
Daylight change TimeCell bug in React Scheduler

### ISSUE THREAD

**Issue by Bloodyline** [DevExpress/devextreme-reactive#3104]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

When adding the plugin `WeekView` with a `startDayHour` prop to 1, navigating to 1 week before daylight change, let's say `25-31 October`, 
```javascript
<WeekView
   startDayHour={1}
   endDayHour={19}
/>
```
the timecell breaks, and will generate each time duplicates timecells.

### Expected Behaviour

It should start at `00:00` instead of creating duplicates timecells or allow activating/deactivating daylightChange behavior.

### Steps to Reproduce

[Codesandbox demo link](https://codesandbox.io/s/confident-hertz-in44j?file=/demo.js)

1. Navigate to `25-31 October`. What really matters is it should be before daylight change `1st Nov`
2. Navigate using date navigator arrow to next week `1-7 Nov`

### Screenshots

![CZFcti62HQ](https://user-images.githubusercontent.com/13756173/94595565-02f6b680-0259-11eb-8c28-dfc193e595b7.gif)

### Environment

- devextreme-reactive: 2.7.1
- react: ^16.13.1
- browser: Google Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: ^4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product! I reproduced this issue, we will fix this as soon as possible.

**Comment by Rocky640** [comment]
Same issue here. Any progress ?

**Comment by Bloodyline** [comment]
Can you reopen this issue.

The problem above is resolved, but it doesn't completely handle changes between DST
From DST to non DST weeks, it works as expected
![pyhOfrDWla](https://user-images.githubusercontent.com/13756173/98047453-e8849f80-1df9-11eb-8034-7a033c206826.gif)


But from non DST to DST (7-13 March 2021), it doesn't.
![EFNDdDEVbR](https://user-images.githubusercontent.com/13756173/98047435-e0c4fb00-1df9-11eb-8617-b436d8c08acd.gif)
