### ISSUE TITLE
How can I get the current date period?

### ISSUE THREAD

**Issue by baj84** [DevExpress/devextreme-reactive#3105]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hi,
I'm just trying to get the current weekly date period that is active in the scheduler. I can't for the life of me figure this out. Could someone please point me in the right direction?

**Comment by MaximKudriavtsev** [comment]
Hi @baj84,

You can get the current time period using our Plugin System. In the following [example](https://codesandbox.io/s/currying-breeze-g204y?file=/demo.js:415-429), I created an additional plugin (`ViewBoundaries`) that gets two values - `startViewDate` and `endViewDate` - from the scheduler component and passes these values to the parent component on callbacks.

You can find more information on the plugin system in our [knowledge base](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/).

**Comment by baj84** [comment]
Thanks. I found a much easier way, for anyone else who stumbles along this, this was my solution:
`const handleDateChange = date => { console.log(date)};`
`<ViewState onCurrentDateChange={date => handleDateChange(date)} />`
