### ISSUE TITLE
Disable resource selection in AppointmentForm

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3106]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello. As in the title, I'm having trouble figuring out how to tell the appointment form not to allow the user to select among resources. I tried setting the resourceEditorComponent prop to null and undefined, but it didn't work.

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- browser: Microsoft Edge
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

I made a small example: https://codesandbox.io/s/flamboyant-goldstine-5cbtn.
You can override Resource Editor this way:

```
const ResourceEditor = () => null;
```

You will also have to remove unnecessary labels. To do that, you will have to customize AppointmentForm's labelComponent (see my example).

**Comment by AryamnovEugeniy** [comment]
There is also another way. You can disable the editor without removing it. Here is another example: https://codesandbox.io/s/amazing-wood-jsgws

**Comment by GRawhideMart** [comment]
Much obliged! You're very kind!

**Comment by AryamnovEugeniy** [comment]
You are welcome!
