### ISSUE TITLE
How do I change the color of ColumnChooser Icon button? 

### ISSUE THREAD

**Issue by GKNetaphor** [DevExpress/devextreme-reactive#3107]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

How do I change the color of ColumnChooser Icon button?  I want it to inherit my theme's primary color.  I am using ThemeProvider in App.

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @GKNetaphor,

I suggest that you customize the [ColumnChooser.ToggleButton](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#plugin-components) component with a custom class. Here is an [example](https://codesandbox.io/s/recursing-thompson-zveuf).
If you have any further questions, let us know.
