### ISSUE TITLE
Context to day being rendered or if appointment spans multiple days in custom Appointment component

### ISSUE THREAD

**Issue by adamcarr** [DevExpress/devextreme-reactive#3109]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I am customizing the Appointment and AppointmentContent components. One piece of data I need to know is if the even spans multiple days. This data could be provided either by the current date being rendered, or via the `toNext` or `fromPrev` props being passed into the appointmentContent template. It isn't a trivial task or my desire to completely replace the Appointments plugin just for this need. Is there another way I can get this information in my custom Appointment component?

I can provide a link to an example if absolutely necessary, but this doesn't seem like something needing an example. Just don't have the proper plumbing in place for this that I can see. 

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- browser: all
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by adamcarr** [comment]
If there is no easy way to do this now, what about just changing the current Appointments plugin to pass `toNext` and `fromPrev` to the `Appointments.Appointment` component (or any custom passed substitute)? I don't see any harm from providing this information unless there are plans to remove this information.

**Comment by AryamnovEugeniy** [comment]
Hello!

Usually we do not provide unnecessary properties to a component.
But in this case it is possible to pass the properties you need from your side. Here is an example: https://codesandbox.io/s/bold-kirch-g527h?file=/demo.js. I did the following:
1. I created a plugin that adds additional parameters to the `appointmentContent` template (see our guide on custom plugin development: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/). In this case - `customToNext` and `customFromPrev`. They will be passed to the `Appointment` component. Note: this plugin should be **after** the `Appointments` plugin.
2. Now the props are passed to the Appointment component but they are not passed to the `AppointmentContent`. To do that, I cloned `Appointment`'s children and added these properties to them.

If you have any other question, we will be happy to assist you.
