### ISSUE TITLE
Bad rendering performance when adding/removing columns if grid has a lot of data

### ISSUE THREAD

**Issue by stefankirchfeld** [DevExpress/devextreme-reactive#3110]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I am using the Grid with a TreeDataState and ColumnChooser plugins.

My Grid has 23 columns in this test case, where I then open the column chooser and choose to add another column.
Because the adding of a column seems to be animated (like a sliding in of the new column), this leads to really bad performance or even rendering of complete whitespace if the grid is huge (tested in Chrome).

### Expected Behaviour

I would expect to be able to configure if the adding of column should be a static or animated rendering, to improve performance in this case.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stefankirchfeld,

Our Grid doesn't allow you to configure animation. We will take this functionality into account in future development.
I suggest that you use [Virtual Scrolling](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/), which has no animation, and render only visible rows and columns. Here is an [example](https://codesandbox.io/s/hopeful-cartwright-9st75).

If you have any further questions, feel free to contact us.
