### ISSUE TITLE
Maximum call stack size exceeded using treeData with large set of nested records

### ISSUE THREAD

**Issue by bahamut657** [DevExpress/devextreme-reactive#3111]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
I'm using the Tree Data plugin and it work fine with small dataset.
If working with a large dataset (5000 records), it seems that the Array.reduce method is called too many times, resulting in JS error RangeError: Maximum call stack size exceeded.
I tried to debug it with some breakpoint and it seems that the plugin iterate all the nested row before rendering (even if I enable VirtualTable plugin to make it work faster).

This is the stack trace:
```
index.js:1 The above error occurred in the <TemplateConnectorBase> component:
    in TemplateConnectorBase (created by TableBase)
    in TemplatePlaceholderBase (created by Context.Consumer)
    in Unknown (created by Context.Consumer)
    in Unknown (created by TableBase)
    in TemplatePlaceholderBase (created by Context.Consumer)
    in Unknown (created by Context.Consumer)
    in Unknown (created by GridCore)
    in div (created by RootBase)
    in RootBase (created by WithStyles(RootBase))
    in WithStyles(RootBase) (created by GridCore)
    in TemplatePlaceholderBase (created by Context.Consumer)
    in Unknown (created by Context.Consumer)
    in Unknown (created by PluginHostBase)
    in PluginHostBase (created by GridBase)
    in GridBase (created by Grid)
    in Grid (at TableRequestList.jsx:207)
    in div (created by AutoSizer)
    in AutoSizer (at TableRequestList.jsx:204)
    in TableRequestList (at App.js:69)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2273
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
(anonymous) @ App.js:43
view_context_requests_success @ DebuggerSocketClient.js:312
done @ DebuggerSocketClient.js:216
(anonymous) @ DebuggerSocketClient.js:758
use_callback @ DebuggerSocketClient.js:757
handle_connection_message @ DebuggerSocketClient.js:745
ws.onmessage @ DebuggerSocketClient.js:1305
Show 2 more frames
index.js:1 RangeError: Maximum call stack size exceeded
    at childRows.reduce.rows (computeds.ts:24)
    at Array.reduce (<anonymous>)
    at customTreeRows (computeds.ts:16)
    at childRows.reduce.rows (computeds.ts:18)
    at Array.reduce (<anonymous>)
    at customTreeRows (computeds.ts:16)
    at childRows.reduce.rows (computeds.ts:18)
    at Array.reduce (<anonymous>)
    at customTreeRows (computeds.ts:16)
    at childRows.reduce.rows (computeds.ts:18)
    at Array.reduce (<anonymous>)
    at customTreeRows (computeds.ts:16)
    at customTreeRowsWithMeta (computeds.ts:34)
    at treeRowsComputed (custom-tree-data.tsx:40)
    at GetterBase._this.plugin._a.<computed> (getter.tsx:58)
    at plugin-host.ts:109
    at Array.forEach (<anonymous>)
    at PluginHost.get (plugin-host.ts:108)
    at getGetterValue (getter.tsx:44)
    at Object.get (helpers.ts:15)
    at tableBodyRowsComputed (table.tsx:29)
    at Array.GetterBase._this.plugin._a.<computed> (getter.tsx:58)
    at PluginHost.get (plugin-host.ts:107)
    at getGetterValue (helpers.ts:6)
    at Object.get (helpers.ts:15)
    at table.tsx:99
    at TemplateConnectorBase.render (template-connector.tsx:59)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at beginWork$1 (react-dom.development.js:23179)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
    at Object.onDataAvailable (App.js:43)
```

### Expected Behaviour
TreeData with VirtualTable have to process only the root level records and all the expanded (not all the nested records).
TreeData is able to support large datasets

### Steps to Reproduce
- Enable TreeData plugin
- Enable VirtualTable plugin
- Provide custom function to CustomTreeData component,  getChildRows prop (that is returning only the child records of current parentId)
- Provide deep nested dataset with at least 5000 records

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13
- browser: Chrome 85.0.4183.121
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @bahamut657,

Thank you for reporting this problem. We will fix this soon.

**Comment by bahamut657** [comment]
Any updates on this side?
Do you have an estimated date for this fix?
Regards

**Comment by LazyLahtak** [comment]
@bahamut657,
We are still working on this bug. Unfortunately, we are unable to give you an approximate date for the fix.
If this is a must-have requirement for your application, consider using our [TreeList for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/Overview/React/Light/).

**Comment by bahamut657** [comment]
Hi @LazyLahtak 

> If this is a must-have requirement for your application, consider using our TreeList for React.


Does it support VirutalScrolling or LazyLoading? 
I need a treeview that supports big dataSet (at least 5000 records). 
Do you think that TreeList is suitable for this?

Cheers

**Comment by LazyLahtak** [comment]
@bahamut657,

The TreeList supports Virtual scrolling, but doesn't have a Lazy Loading mode. However, TreeList can load data on demand (refer to the [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/LoadDataOnDemand/React/Light/)).

**Comment by bahamut657** [comment]
It seems the problem is still reproducing.
I performed an `npm update` and tested with version 2.7.3.
Using a lot of datas, I obtain the same error signaled on top of this issue.

Am I doing something wrong?

Regards

**Comment by LazyLahtak** [comment]
We have merged this fix yesterday. The fix will be available in the next release.

**Comment by bahamut657** [comment]
Hi @LazyLahtak 

I updated to version 2.7.4.
I've retried the page that load tons of datas (where I found this issue). Now, the behaviour is different: the browser completely freezes itself on page render.

How to investigate more?
Regards

**Comment by LazyLahtak** [comment]
Hi @bahamut657,

Could you send us a runnable project (for example, using [CodeSandbox](https://codesandbox.io/s/competent-beaver-748tq))? It will help us investigate this issue.
