### ISSUE TITLE
How do I change the color of the appointment background based on data?

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3112]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I have two scheduler components in two separate routes, which are supposed to render the same scheduler, but referred to different resources (in this case, rooms). This is the component I'm talking about:
```
class StudioScheduler extends Component {
  constructor(props) {
    super(props);

    this.state = {
      currentViewName: "work-week",
      currentDate: new Date(),
      addedAppointment: {},
      appointmentChanges: {},
      editingAppointment: undefined,
    };

    this.currentViewNameChange = (currentViewName) => {
      this.setState({ currentViewName });
    };
    this.currentDateChange = (currentDate) => {
      this.setState({ currentDate });
    };

    this.commitChanges = this.commitChanges.bind(this);
    this.changeAddedAppointment = this.changeAddedAppointment.bind(this);
    this.changeAppointmentChanges = this.changeAppointmentChanges.bind(this);
    this.changeEditingAppointment = this.changeEditingAppointment.bind(this);
  }

  changeAddedAppointment(addedAppointment) {
    this.setState({ addedAppointment });
  }

  changeAppointmentChanges(appointmentChanges) {
    this.setState({ appointmentChanges });
  }

  changeEditingAppointment(editingAppointment) {
    this.setState({ editingAppointment });
  }

  commitChanges(props) {
    const { added } = props;
    const { schedulerData } = this.props;
    if (added) {
      alert("Will add appointment " + JSON.stringify(added));
      this.props.addBooking(
        added.startDate,
        added.endDate,
        added.title,
        schedulerData[0].room
      );
    }
  }

  render() {
    const { resources, schedulerData } = this.props;
    const {
      currentViewName,
      currentDate,
      addedAppointment,
      appointmentChanges,
      editingAppointment,
    } = this.state;
    return (
      <ThemeProvider theme={theme}>
        <Paper>
          <Scheduler data={schedulerData} locale="it-IT" firstDayOfWeek="1">
            <ViewState
              currentDate={currentDate}
              onCurrentDateChange={this.currentDateChange}
              currentViewName={currentViewName}
              onCurrentViewNameChange={this.currentViewNameChange}
            />

            <EditingState
              onCommitChanges={this.commitChanges}
              addedAppointment={addedAppointment}
              onAddedAppointmentChange={this.changeAddedAppointment}
              appointmentChanges={appointmentChanges}
              onAppointmentChangesChange={this.changeAppointmentChanges}
              editingAppointment={editingAppointment}
              onEditingAppointmentChange={this.changeEditingAppointment}
            />

            <DayView
              displayName="Giornaliero"
              startDayHour={9}
              endDayHour={21}
              cellDuration={60}
            />

            <WeekView
              name="work-week"
              displayName="Settimanale"
              excludedDays={[0]}
              startDayHour={9}
              endDayHour={21}
            />
            <MonthView displayName="Mensile" />
            <Toolbar />
            <DateNavigator />
            <TodayButton messages={{ today: "oggi" }} />

            <EditRecurrenceMenu />
            <ConfirmationDialog />
            <Appointments />
            <Resources data={resources} mainResourceName="room" />

            <AppointmentTooltip showCloseButton />
            <AppointmentForm
              resourceEditorComponent={() => null}
              labelComponent={LabelComponent}
            />

            <ViewSwitcher />

            <CurrentTimeIndicator
              shadePreviousAppointments={true}
              shadePreviousCells={true}
              updateInterval={60000}
            />
          </Scheduler>
        </Paper>
      </ThemeProvider>
    );
  }
}
```

Only problem is, even though they are already clearly separated by the routing, I still can't get the events to change color. Is there any way to color each text and background according to data received (for example, from a Redux reducer) and default to the resource-based coloring if color string is not available?

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- redux: 4.0.5
- react-redux: 7.2.1
- browser: Microsoft Edge
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

You can provide different colors in resources depending on the resource ID. Here is an example where we define custom colors for the resources: https://codesandbox.io/s/admiring-sanderson-rg7yl?file=/demo-data/resources.js. You just need to pass different resources depending on routing.

Does this solution meet your requirements?

**Comment by GRawhideMart** [comment]
> Does this solution meet your requirements?

Mmm, not quite. What I am doing is a radio weekly schedule; each different program has a palette (which is defined in a separate SQL table, but that's not important for the frontend). What I would like to do is to display each program with its background and its color. Should I define a resource for each program? Would be honestly very complicated, since it would be a dynamic resource which changes every few months.

**Comment by AryamnovEugeniy** [comment]
In this case, you may override `Appointments`' [appointmentComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointments/#appointmentsappointmentprops) and choose a color based on appointment's data. Here is a small example: https://codesandbox.io/s/late-smoke-fqwss?file=/demo.js.

**Comment by GRawhideMart** [comment]
Thank you. Do you happen to know if I can also put an image with backgroundSize cover?

**Comment by AryamnovEugeniy** [comment]
This question was addressed here: https://github.com/DevExpress/devextreme-reactive/issues/3121
