### ISSUE TITLE
How to show AllDay appointments in the time cells

### ISSUE THREAD

**Issue by baj84** [DevExpress/devextreme-reactive#3113]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I would like to show an appointment that stretches over multiple days (in the week view) in the actual cells as opposed to using the AllDayPanel plugin, is this possible?

This is a requirement as the user can essentially 'block out' dates, which need to be shown in a week view instead of just having a single event in the 'AllDayPanel'.

Thanks!

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

The only way to do this is to create a custom plugin (here is our guide on custom plugin development: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/). It should override `timeTableAppointments` getter. This plugin must be after all the Views you use but before the `IntegratedGrouping`. In this plugin you will have to filter appointments, cut them by dates, etc. But basically, what you actually need to do is to copy the function from [this](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-scheduler-core/src/plugins/week-view/computeds.ts#L17) file and change `true` to `false` on line 17. To make things easier, I made an example: https://codesandbox.io/s/holy-sun-jnu66?file=/demo.js. I created `IntegratedAppointments` plugin and overrode `timeTableAppointments` getter. The function I mentioned is in utils.js.

Regards,
Eugeniy

**Comment by baj84** [comment]
Amazing thank you!

**Comment by baj84** [comment]
Hi @AryamnovEugeniy I implemented your solution and noticed that there is a bug. When a date stretches over more than 2 days it only shows the event on the first and last dates.

Do you know how I might make the event appear on all days that it spans?

**Comment by AryamnovEugeniy** [comment]
Hello!

I updated my previous example: https://codesandbox.io/s/awesome-wing-p4bpz?file=/utils.js:5283-5764.
In this sample I create a separate appointment instance inside `sliceAppointmentByDay` for every day between the first and the last days. This should help you.

**Comment by nojuskybartas** [comment]
Did you end up with a working solution?
