### ISSUE TITLE
Pass Additional Props to custom row while persisting state

### ISSUE THREAD

**Issue by sajithk** [DevExpress/devextreme-reactive#3114]
I am using a TableEditRow to show the editing row in my Table. I need to pass additional properties to the custom row as well.
Here is the sample of my implementation, https://codesandbox.io/s/muddy-architecture-lrumf?file=/demo.js

I'm using,
`<TableEditRow rowComponent={(props) => <Row {...props} customProp={val} />} />` 
syntax to define the custom row with custom properties. The problem with this approach is that the state of the row component gets reset when the parent component is updated. (commented in the line 72 in demo.js of the sample. Uncomment it and comment 69 to see the behavior).

But if I use,
`<TableEditRow rowComponent={Row} />`
The state is persisted. But can not pass custom properties.

How can I pass additional properties while persisting the state of the row component?

**Comment by MaximKudriavtsev** [comment]
Hi @sajithk,

We have already registered the similar issues [#1654](https://github.com/DevExpress/devextreme-reactive/issues/1654#issuecomment-442807510) and [#2855](https://github.com/DevExpress/devextreme-reactive/issues/2855#issuecomment-621141527)

**Comment by sajithk** [comment]
I am trying to use `connectProps`. I am using functional component. So trying to set the row in state using setState. 
`
const [row] = useState(
    connectProps(RemarksFormForDetailRow, () => ({
      testProp: "val",
    }))
  );
`

I am getting a exception, 
`
Uncaught TypeError: Cannot set property 'props' of undefined
    at PureComponent (react.development.js:530)
    at RenderComponent (connect-props.tsx:15)
    at basicStateReducer (react-dom.development.js:15013)
    at updateReducer (react-dom.development.js:15135)
    at updateState (react-dom.development.js:15237)
    at Object.useState (react-dom.development.js:15949)
    at useState (react.development.js:1497)
`

Thanks.

**Comment by sajithk** [comment]
OK, followed this #3075, managed to resolve with useCallback hook,

`
const row = useCallback(
    (props) => {
      return <RemarksFormForDetailRow {...props} onClose={handleRowClose} />;
    },
    []
  );
`

Thanks for help.
