### ISSUE TITLE
Page freezes on drag and drop

### ISSUE THREAD

**Issue by creddaiah** [DevExpress/devextreme-reactive#3118]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When we have few fixed left columns and if we try to drag a column from extreme right on to the fixed left columns, page freezes. This was not the case with versions below 2.6.4. Starting from 2.7.0 we have this issue.

### Expected Behaviour

Page should not freeze and it should be operational.

### Steps to Reproduce

In the below code sandbox, scroll to the extreme right and drag "Show the first 50 characters of a text" column on to the fixed left columns. Notice the page freezes.

[https://codesandbox.io/s/keen-cdn-l9dy7](https://codesandbox.io/s/keen-cdn-l9dy7).

In the same sandbox, change the versions from 2.7.2 to 2.6.4 and notice we don't see this issue.

### Environment

- devextreme-reactive: 2.7.2
- react: 16.13.1
- browser: Chrome (85.0.4183.121)
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @creddaiah,

Thank you for reporting this problem. We will fix this soon.
