### ISSUE TITLE
T937684 - VirtualTable infiniteScrolling getRows requesting wrong skip & limit

### ISSUE THREAD

**Issue by DevExpressSupportTeam** [DevExpress/devextreme-reactive#3119]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### I'm using ...
- [x] Reactive Grid
### Info
<p>React Grid</p>
<p>consider the infiniteScrolling example from the docs - <a href="https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#infinite-scrolling">https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#infinite-scrolling</a></p>
<p>I forked it and changed 2 lines:</p>
<ol>
<li>line 20 - set total rows to something that is not multiples of pageSize, eg <strong>137</strong> rows.</li>
<li>line 99 - added a <code>console.log({ requestedSkip, take });</code> to demonstrate the problem</li>
</ol>

<p>See this sample: <a href="https://codesandbox.io/s/little-morning-uxb6n">CodeSandBox</a></p>

<p>Under above configuration the grid should call to getRows method 2 times, but it calls it  3 times with malfunctioned parameters.<br>
Check the console logs I added and optionally check the outgoing requests in devtools.</p>
<p>Important notice - this doesn't happen using your other example <a href="https://codesandbox.io/s/7nxhs">https://codesandbox.io/s/7nxhs</a> when infiniteScrolling is false.</p>
<p>Please investigate ASAP and recommend a workaround in the meanwhile</p>
<h3>Steps to Reproduce</h3>
<p>Open the forked example, open the console and network tab<br>
Rerun the sandbox<br>
See first request to the API is {requestedSkip:&nbsp;0, take:&nbsp;100}<br>
scroll the grid to line  50+<br>
See the table requesting wrong skip</p>
<h3>Current Behaviour</h3>
<p>getRows requesting {requestedSkip:&nbsp;50, take:&nbsp;37} instead {requestedSkip:&nbsp;100, take:&nbsp;37}.<br>
This may break the  grid completely under some conditions</p>
<h3>Expected Behaviour</h3>
<p>getRows should request for {requestedSkip:&nbsp;100, take:&nbsp;37} because first request was {requestedSkip:&nbsp;0, take:&nbsp;100}.</p>
<h3>Environment</h3>
<p>Mac + Chrome + Your example has all the details although it is also reproducible on version 6.x.x</p>

**Forked from this ticket: T937684**

**Comment by artyil** [comment]
> This may break the grid completely under some conditions

The conditions may be when the API doesn't have a stable sort mechanism and returns same ids but in different order. Then the Grid will broken since it fails with duplicate (React) keys console errors and skeleton row cells visually appear in different places in the Grid. 

Never mind the backend API issue, I expect that if my customer case working with `infiniteScrolling:false` it should not break when I switch the value into `true`.

**Comment by artyil** [comment]
Hi. Any updates here?
