### ISSUE TITLE
How to replace the default require id 

### ISSUE THREAD

**Issue by be-next-hotdog** [DevExpress/devextreme-reactive#312]
Hello, 
I came to know that each data object should have a `id` property which is given to `rows` props. Nevertheless, there's a `articleId` property in my data objects but not a `id`. Except resolving it by adding a id property on purpose, how may I make point the required `id` to the my `articleId` property ? 

Thx, guys

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, you can use the `getRowId` function of Grid. See the following code:
```js
<Grid
  rows={rows}
  columns={columns}
  getRowId={row => row.articleId}
>
...
</Grid>
```
