### ISSUE TITLE
TableInlineCellEditing with New Rows with Uncontrolled Mode

### ISSUE THREAD

**Issue by neilst** [DevExpress/devextreme-reactive#3120]
### I'm using ...

- [  x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is there a plan to extend TableInlineCellEditing to support new rows with the use of uncontrolled mode? The current approach with committing an empty row (via controlled mode) appears that it would not run through the standard flow for validations unless one specifically tries to edit the invalid cell.

**Comment by LazyLahtak** [comment]
Hi @neilst,

The "Add" button adds a special row that will be added into the Grid. This row is rendered by the `TableEditRow` plugin. Without this plugin, there is no way to add a row in uncontrolled mode.
I suggest that you use the `TableEditRow` plugin and the `TableInlineCellEditing` plugin together. Here is an [example](https://codesandbox.io/s/vibrant-galileo-mznqq).

Let us know if this solution meets your requirements.

**Comment by neilst** [comment]
Thank you. This is what I was looking for.

**Comment by LazyLahtak** [comment]
You are welcome!
