### ISSUE TITLE
AppointmentComponent messes up the Tooltip

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3121]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

[This CodeSandbox](https://codesandbox.io/s/xenodochial-bird-d6eev?file=/demo.js) is a small reference forked from one of the examples.

One can notice that:
* I cannot seem to change anything beside the color of the background of an appointment
* The data in the AppointmentTooltip gets messed up by the customized component in the Appointment component.

Can someone help me address this issue?

### Environment

- devextreme-reactive: 2.7.2
- react: 16.13.1
- browser: codesandbox
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

I updated your example: https://codesandbox.io/s/trusting-antonelli-7ht7y?file=/demo.js.
I passed the `data` to the `Appointments.Appointment` - it needs this to open the Appointment Tooltip correctly.

About text color and other possible customizations. We have two main components that you can customize: `Appointment` and `AppointmentContent`. In your case you can customize the [AppointmentContent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-tooltip/#appointmenttooltipcontentprops) component (see the example above) to change the text color.

Should you encounter any other problem, we will be happy to assist you!
