### ISSUE TITLE
Select Dropdown does not blur and save proper value with Inline editing

### ISSUE THREAD

**Issue by las3r** [DevExpress/devextreme-reactive#3123]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
My use case is a (controlled)  grid where users can change cell values using `TableInlineCellEditing`. I want to use a select dropdown as described in your sample on your website. This however does _not_ work when you use `TableInlineCellEditing` - the selectbox is never blurred, the onValueChanged is never fired, meaning the data won't update. The data only updates when you click / focus another cell, which from a UX-perspective is not a good thing.

Link to the example that reproduces the issue: [https://codesandbox.io/s/silent-sun-32mhh?file=/demo.js](https://codesandbox.io/s/silent-sun-32mhh?file=/demo.js)

### What have I tried:

If you change
```ts
  <select
    className="form-control"
    value={value}
    onChange={(e) => onValueChange(e.target.value === "true")}
    onBlur={onBlur}
    autoFocus={autoFocus}
  >
```
to 
```ts
  <select
    className="form-control"
    value={value}
    onChange={(e) => {
        onValueChange(e.target.value === "true")}
        e.target.blur(); // or onBlur();
    }
    onBlur={onBlur}
    autoFocus={autoFocus}
  >
```
You'll see that the update is not happening correctly (it will send out a change with value undefined.

### Environment
- devextreme-reactive: 2.7.2
- react: 16.13.1
- browser: all
- bootstrap: 4
- react-bootstrap: none
- material-ui: none
- typescript

**Comment by las3r** [comment]
This is actually a bug in the "typings":

`DataTypeProvider.ValueEditorProps` does not contain a definition 

The following code works:

```ts
const SelectFormatter = ({ value }: DataTypeProvider.ValueFormatterProps) => value;

const SelectEditor = ({ value, onValueChange, onBlur, autoFocus }: any) => (
  <Form.Control
    as='select'
    defaultValue={value}
    onChange={(e) => {
      onValueChange(e.target.value);
    }}
    onBlur={onBlur}
    autoFocus={autoFocus}
  >
    <option value='Sales'>Sales</option>
    <option value='Lease'>Lease</option>
    <option value='Trade-in'>Trade-in</option>
    <option value='Support'>Support</option>
  </Form.Control>
);

const SelectTypeProvider = (props: any) => (
  <DataTypeProvider formatterComponent={SelectFormatter} editorComponent={SelectEditor} {...props} />
);

```

In the grid use:
```ts
      <BooleanTypeProvider for={['neccesaryColumn']} />
```

When I "type"
```ts
const SelectEditor = ({ value, onValueChange, onBlur, autoFocus }: any) => (
```
to 
```ts
{ value, onValueChange, onBlur, autoFocus }: DataTypeProvider.ValueEditorProps) => (
```
It gives me an error that onBlur / autoFocus are not in the definition. This got me off on the wrong foot.

**Comment by LazyLahtak** [comment]
Hi @las3r,

Both handlers, the `onValueChange` and the `onBlur`, work with one state. When you call them in sequence, React applies only the last change. I suggest that you call `onBlur` using `setTimeout`. Thus, this handler will be called after the first state update (which was triggered by the `onValueChange` call).
Here is the updated [example](https://codesandbox.io/s/adoring-pond-ru1fd).

If you have any further questions, let us know.
