### ISSUE TITLE
How to leave the cell unchanged if editing is disabled

### ISSUE THREAD

**Issue by las3r** [DevExpress/devextreme-reactive#3126]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
My grid allows cell editing using inline-editing, but only for a few columns. I've set this up following the documentation, and this works. However, when a cell is "not editable" it will still show a greyed out editing field and this is not very usable as a UX-pattern.

I know it is possible to provide a custom cellRenderer like I do for the disabled filter-rows:
```ts
const hideFilterCellRenderer = (props: TableFilterRow.CellProps): ReactElement => {
  if (!props.filteringEnabled) {
    return <TableFilterRow.Cell {...props}>&nbsp;</TableFilterRow.Cell>;
  }
  return <TableFilterRow.Cell {...props} />;
};
```

Could you please provide some guidance on what type of cellrenderer I need to provide to only show the "edit"-mode for a cell if it is enabled? 

Link to the example that reproduces the issue: [https://codesandbox.io/s/serene-leavitt-lxr82?file=/demo.js](https://codesandbox.io/s/serene-leavitt-lxr82?file=/demo.js)

### Environment
- devextreme-reactive: 2.7.2
- bootstrap 4
- typescript

**Comment by LazyLahtak** [comment]
Hi @las3r,

We have already registered similar issues. In [this](https://github.com/DevExpress/devextreme-reactive/issues/3021#issuecomment-678251444) topic, we discussed how to achieve this behavior via cell customization. [Here](https://github.com/DevExpress/devextreme-reactive/issues/2684#issuecomment-588990283) we described a solution with [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode).

**Comment by las3r** [comment]
Hi there @LazyLahtak,

The examples are all with material-ui, if I use the same way that is referenced in the other issues, I get a stacktrace because it seems to do some kind of recursive lookup.

**Comment by LazyLahtak** [comment]
I researched your example and found that you have an unclosed `link` tag in the `index.html`. For this reason, the `<div id="root"></div>` element is not rendered.
Also, there is missed additional style:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
```

Here is an updated [example](https://codesandbox.io/s/muddy-cache-ye2zk?file=/index.html).
