### ISSUE TITLE
The date field in Grid is still in focus after editing.

### ISSUE THREAD

**Issue by Yash-GitB** [DevExpress/devextreme-reactive#3127]
I am trying to implement a simple grid with employee details. But the focus on the date field is not lost on update of the date. Please help. You can find the code [here ](https://codesandbox.io/s/vffse?file=/demo.js). Try to modify any of the dates and you will see the problem faced.

**Comment by MaximKudriavtsev** [comment]
Hi @Yash-GitB,

Sorry for the long response. For such cases, we have a property that calls `commitChanges` inside a Grid - `onBlur`. To achieve the expected behavior, you need to call this property when your custom editor loses focus (on the blur event). Also, use the `autoFocus` property of the date picker to focus your custom editor when you click on a cell.

I updated your [example](https://codesandbox.io/s/test-forked-n7cef?file=/demo.js) accordingly.

**Comment by stmchan93** [comment]
@MaximKudriavtsev Hi, your example doesn't work, when you click on the date button, the datepicker doesn't show up. Any other ideas how to get this to work?

**Comment by Yash-GitB** [comment]
@MaximKudriavtsev 
Sorry for the delayed response, the suggested changes wont help as the date picker is not enabled on selection. Please help

**Comment by MaximKudriavtsev** [comment]
@stmchan93, @Yash-GitB,

My apologies for the wrong sample. I updated [my example](https://codesandbox.io/s/test-forked-n7cef?file=/demo.js). Does this solution meet your requirements?

**Comment by Yash-GitB** [comment]
@MaximKudriavtsev 
Works as expected with some limitations.

But few observations.
1. The value selected in the Date Selection is not updated back in Grid.
2. Also, if we open the enable Permanent Open, the accessibility for the form is restricted. Meaning, my forms are accessible even without mouse, i.e. only keyboard. Tab works great for first row. But we can never traverse to the second row, as the focus never moves to the next row.

**Comment by MaximKudriavtsev** [comment]
@Yash-GitB,

Thank you for your research. I updated [my example](https://codesandbox.io/s/test-forked-n7cef?file=/demo.js:835-848). Our Grid doesn't fully support keyboard navigation, and this example still doesn't work with a keyboard. You can play with the KeyboardDatePicker component's props to adjust it as your needs require. The main idea is to call the `onBlur` method when you move out of a cell and not to call `onValueChange` together with `onBlur` (I added `setTimeout` for this purpose).
