### ISSUE TITLE
Is TreeData/-state & virtual scrolling possible

### ISSUE THREAD

**Issue by LaurelineP** [DevExpress/devextreme-reactive#3129]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Hi there,
I'm currently working on a table using TreeData, TreeDataState in order to have a tree view within the table but also Virtual table and VirtualTableState in order to have a infinite scroll.

There are generally three indentation levels.
The max row size would be 50 per request once reached to the scrolling point where the getRows ( == getRemoteRows function in your demo ) should start requesting the next 50.

Typical data in the table would be a first level row having few second level rows which each might have 1000 - 2000 or else rows.

When the first branch of data is loaded basically
-  this display the first level row, then the second and then the 48 next rows ... But no request is triggered.
Which led me to think that the scrolling identify first levels rows maybe ??? 
- therefore, the other firsts level rows are not displayed neither unless I load all data .

Do you have any advices or solutions for those needs ?
I don't have any reproductible code yet.

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @LaurelineP,

Thank you for your interest in our Grid.
We do not have a demo with Tree Data and Lazy Loading and it is a little difficult to make one.
I suggest your implement `Cursor Pagination` as described in the following help [topic](https://github.com/DevExpress/devextreme-reactive/issues/2850). This solution doesn't require the VirtualTableState plugin.
If it doesn't suit you, could you please send us your project (for example, using the [CodeSandbox](https://codesandbox.io/s/epic-villani-zmce2))? It will help us find a suitable solution.

**Comment by LaurelineP** [comment]
I'll do my best to provide a code example once I have an opportunity to do it, in a meanwhile:
- Is there a way to have infinite scroll using a treeView ( maybe that might solve others questions/ or help understand better the situation ) ?
Use Case:
1st level = one row = one folder 
2nd level = this row generally has another folder 
3rd level = generally might have thousand of documents => this is here we's like to infinite scroll ( loading 50 by 50 )
That was at this point I tried to get the get rows to trigger, hopping that it would triggers once the 50 ( 1 + 1 + 48 ) rows are reached but it did not :/.

If unfortunately my explanation are not enough, I'll came back once I get this codesandbox settup

**Comment by LazyLahtak** [comment]
@LaurelineP,

Unfortunately, we have no examples on how to use tree data with the Infinite Scrolling feature. It's a complex scenario, which is difficult to implement. The main problem is the current tree data implementation. We need to research how to support it along with the Lazy Loading and the Infinite Scrolling features.

I suggest that you use data loading on demand instead. Please, refer to our guide: [React Grid - Tree Data. Load Remote Data on Demand](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/tree-data/#load-remote-data-on-demand).

If you have any further question, feel free to contact us.

**Comment by zdzarsky** [comment]
@LaurelineP @LazyLahtak we are fighting this right now. I'll let you know about the progress.
