### ISSUE TITLE
Zoom Region feature crashes the app when clicking instead of dragging

### ISSUE THREAD

**Issue by ToFischer17** [DevExpress/devextreme-reactive#3130]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour
The "zoom region" feature crashes when the user only clicks into the chart instead of performing an actual drag.

### Expected Behaviour
The chart does not crash or at least provides a way to disable the "zoom region" feature.

### Steps to Reproduce
- Go onto the [guide page for the Zoom and Pan Plugin](https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/zoom-and-pan/) or into the Code Sandbox of any of the official examples like [this one](https://codesandbox.io/s/mpc9z?file=/demo.js).
- Hold down the Shift key and click into the chart without moving the cursor.
- On the guide page the chart simply disappears, in the code sandbox we get the error "Cannot read property 'x' of null".

**Comment by AryamnovEugeniy** [comment]
Hello! We reproduced this issue and will fix this as soon as possible.
