### ISSUE TITLE
Grid - RTL with virtual-scrolling not working

### ISSUE THREAD

**Issue by imgharavi** [DevExpress/devextreme-reactive#3137]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When activating RTL with virtual-scrolling, hidden columns back of scroll does not display anything.

### Expected Behaviour

its expected to display all columns as LTR

### Steps to Reproduce

https://codesandbox.io/s/dawn-currying-zgobs?file=/demo.js

**Comment by LazyLahtak** [comment]
Hi @imgharavi,

Thank you for your interest in our Grid.
We process Virtual Table's viewport manually and don't support RTL. We will consider your request in the future. You can follow our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed once we start working on it.

If you need this feature now, I suggest that you use our [DataGrid for React](https://js.devexpress.com/Overview/React/). It supports [RTL](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RightToLeftSupport/React/Light/) with [virtual scrolling](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/HorizontalVirtualScrolling/React/Light/).
If you have any further questions, feel free to contact us. I will be happy to follow up.
