### ISSUE TITLE
Banded columns are not exported

### ISSUE THREAD

**Issue by sergioadimedia** [DevExpress/devextreme-reactive#3140]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

When I export the table to Excel, the banded columns are not exported with it. In the cases, as in this example, when two column titles are the same, it can be quite confusing.

Is there any way to export the banded columns?

Link to the example that reproduces the issue: [Example](https://stackblitz.com/edit/react-yvvp8r?file=src%2FApp.js)

### Environment

- devextreme-reactive: 2.7.2
- react: 16.14.0
- browser: Google Chrome v86.0.4240.75
- bootstrap: 4.5.3

**Comment by LazyLahtak** [comment]
Hi @sergioadimedia,

Thank you for your interest in our React Grid.
I suggest that you use the `customizeHeader` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid-exporter/#properties) of the `GridExporter`. In this case you can pass a handler and add additional banded rows. Here is an updated [example](https://codesandbox.io/s/small-sun-6d9vm). You may wish to refer to our guide: [React Grid - Export. Excel Document Customization](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/#header-and-footer-customization).
If you have any further questions, feel free to contact us.

**Comment by andrei9669** [comment]
how would one implement this with nested bands?
