### ISSUE TITLE
Scroll to current hour automatically

### ISSUE THREAD

**Issue by davidwu1010** [DevExpress/devextreme-reactive#3144]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello

Is there a way to let the scheduler scroll to the current hour automatically after page load?

Thank you

**Comment by MaximKudriavtsev** [comment]
Hi @davidwu1010,

To scroll the scheduler to the current time indicator, put an element in its template and invoke the standard [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)() method in the element. Refer to the [CodeSandBox sample](https://codesandbox.io/s/optimistic-payne-u8jcu?file=/demo.js) demonstrating this solution.
