### ISSUE TITLE
iOS version 13.3 and below showing times an hour ahead

### ISSUE THREAD

**Issue by curtisd14** [DevExpress/devextreme-reactive#3145]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x ] React Scheduler

### Current Behaviour

In iOS 13 and below or on Mac, the time is 1 hour ahead of where it should be. The appointment appears in the correct place on the scheduler. On Android and other browsers, this is not an issue.

### Expected Behaviour

Time in appointments to match time on sidebar

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

![Screenshot 2020-10-21 at 12 00 33](https://user-images.githubusercontent.com/73228968/96711711-e7815600-1395-11eb-86d3-4a2f0a4a7073.png)

### Environment

- devextreme-reactive: 2.7.2
- react: 16.14.0
- browser: iOS App, Safari 13 and below
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.7.2

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product.
I reproduced the issue. We will research this issue and get back to you with the results as soon as possible.
