### ISSUE TITLE
How to export all data with remote paging

### ISSUE THREAD

**Issue by KLagdani** [DevExpress/devextreme-reactive#3147]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

In the following example: https://codesandbox.io/s/practical-driscoll-g10z1?file=/demo.js

We have remote paging with an Export button. Currently on this codesandbox, when exporting, only the current displayed data on the page is exported (meaning only 6 rows).
How would you change the onSave method or the startExport to export all remote data (all 93 rows) ?

### Environment

- devextreme-reactive: ^2.7.1
- react: 16.13.1
- browser: any
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @KLagdani,

The `GridExporter` plugin exports all rows that you pass to the `rows` property. In your example, you do not load all rows. If you want to export all rows from the server, you should load them all and pass them to the plugin. Here is an [example](codesandbox.io%5Cs%5Cgoofy-panini-zncep) where all rows are loaded when the application is initialized.
If you wish to continue to load blocks of rows when the page is changed, you can load rows before you export them. Here is another [example](https://codesandbox.io/s/awesome-germain-pvqbg).
If you have further questions, please let us know.

**Comment by KLagdani** [comment]
Great, thank you @LazyLahtak !

**Comment by LazyLahtak** [comment]
You are welcome!
