### ISSUE TITLE
Virtual Table: Table header size as big as content

### ISSUE THREAD

**Issue by himynameissebbo** [DevExpress/devextreme-reactive#3149]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I have implemented a `VirtualTable` which is working fine so far. My table headers are quite long and important for having context for the column. All headers are truncated based on the column size. Is it somehow possible to extend the table header that it always takes the full width of it's content without setting a fixed width for every column?

Thank you very much for the work and the help!

https://codesandbox.io/s/cool-worker-d9sds?file=/demo.js

### Environment

- devextreme-reactive: 2.7.2
- react: 16.14.0
- browser: latest Chrome

**Comment by MaximKudriavtsev** [comment]
Hi @himynameissebbo,

We don't support this functionality out of the box. As an alternative, I can suggest you play with the [width](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#column-width) and [wordWrapEnabled](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#multiline-cells) properties.
