### ISSUE TITLE
Example with Context Menu

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#315]
This is kinda related to #284 but it would be great to get an example of an implementation of a react native context menu (similar to the ones in other DevExpress grid implementations) but natively in react.

I.e. something like when you right click a row in the grid a toggle is fired and a custom dropdown menu is rendered on the row at the position of the mouse cursor.

I think this would be a pretty common thing that people would be interested in, I know I personally would be!

Thanks,

**Comment by SergeyAlexeev** [comment]
Thank you for sharing your idea! We are going to implement such functionality in the future releases.

**Comment by terndrup** [comment]
Awesome, any indication at all when we could see something like this? :) 👍

**Comment by SergeyAlexeev** [comment]
We are currently working on it. Hopefully, this functionality will be available with the next update.

**Comment by SergeyAlexeev** [comment]
Hi,

The [latest](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1.0.0-alpha.10) update contains the requested functionality.

This [sample](https://stackblitz.com/edit/react-kawvft?file=index.js) shows how to handle the `onContextMenu` event and implement a custom logic.

**Comment by terndrup** [comment]
Awesome! In your example you use the Popover componentl, is the approach the same with the Dropdown bootstrap component? To make a "proper" context menu I mean.

Would it just call show on the dropdown for the specific row?

**Comment by SergeyAlexeev** [comment]
Yes, you can easily use any component there. I've just demonstrated how to handle the `onContextMenu` event using the `tableRowTemplate` property.
