### ISSUE TITLE
Appointments in "WeekView" dosn't handle multiple days, it does work only with one day!

### ISSUE THREAD

**Issue by rwaidaAlmehanni** [DevExpress/devextreme-reactive#3152]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
WeekView display just the one day appointments

### Expected Behaviour
WeekView should handle the multiple days appointments like MonthView 

### Steps to Reproduce
ex: startDate: 2020-02-01 & endDate: 2020-02-07  the appointment disappear from the weekView 

### Environment
Ubuntu 16 

- devextreme-reactive:" ^2.7.2"
- react: r^16.13.1" & nextjs:"^9.5.2"
- browser: chrome & firefox
- bootstrap: none
- react-bootstrap: none
- material-ui: "^4.11.0"

**Comment by baj84** [comment]
I ran into this limitation recently and while the solution is not pretty I did get it working. 
See the example here:
https://github.com/DevExpress/devextreme-reactive/issues/3113

**Comment by AryamnovEugeniy** [comment]
Hello!

`WeekView` does not show all-day appointments. But you can add the [AllDayPanel](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointments/#all-day-appointments) plugin. It will show you appointments that are not shown in the main part of the scheduler.
