### ISSUE TITLE
how to use material-ui date pickers in DateNavigator

### ISSUE THREAD

**Issue by bluelovers** [DevExpress/devextreme-reactive#3153]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

i wanna config date picker like https://material-ui.com/zh/components/pickers/

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

You can override the `DateNavigator`'s `OpenButtonComponent` and use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/date-navigation/#controlled-mode). Here is a small example: https://codesandbox.io/s/strange-cori-dohgk?file=/demo.js
