### ISSUE TITLE
Set the timezone for the Scheduler

### ISSUE THREAD

**Issue by baj84** [DevExpress/devextreme-reactive#3154]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Description

I have the timezone set for each individual user. This might be different to the browser local time. Is it possible to specify what timezone the scheduler should use as opposed to defaulting to the local browser one?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your interest in our product! Unfortunately, this feature is unavailable in the Reactive Scheduler.
In case this is an absolute must for your application, you can try out our [Scheduler for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/TimeZonesSupport/React/Light/). It supports different time zones.

Regards,
Eugeniy

**Comment by baj84** [comment]
Thanks. For anyone else who might stumble along this I got it working by converting all my timestamps into the local timezone and then when posting back to the API i'd convert them back to the specified timezone.

**Comment by ajorkowski** [comment]
I managed to get this working a different way. This component seems to use moment to do a lot of the date calculations, and our website changes the 'Default' timezone of moment - this seems to all work correctly in terms of rendering everything were it should in the correct place, the only problem is that the date formatting is in the local timezone, so the times etc look wrong. 

I fixed this by adding a custom formatter that takes the moment date and creates a local date that matches the time so it can be used in the browser formatter, something along the lines of:

```
import { Getter } from '@devexpress/dx-react-core';
import { Scheduler } from '@devexpress/dx-react-scheduler-material-ui';
import moment from 'moment';

<Scheduler>
  <Getter name="formatDate" value={formatter} />
  ...
</Scheduler>

const langCache = new Map();
function formatter(date, opts) {
  if (date === undefined) return '';

  // Handle different langs/formats
  const culture = auth.user?.culture || 'default';
  let formatterCache = langCache.get(culture);
  if (!formatterCache) {
    formatterCache = new Map();
    langCache.set(culture, formatterCache);
  }

  let formatInstance = formatterCache.get(opts);

  if (!formatInstance) {
    formatInstance = new Intl.DateTimeFormat(culture, opts);
    formatterCache.set(opts, formatInstance);
  }

  // Important bit happens here
  const d = moment(date);
  const local = new Date(d.year(), d.month(), d.date(), d.hours(), d.minutes(), d.seconds());
  return formatInstance.format(local);
}
```

By default this formatter is used by all components, so this instantly makes every part of the calendar show the correct time/day/etc.

The only other thing I had to watch out for is when getting the current date via `onCurrentDateChange` - this is a local date object so it needs to go through moment to get the timezone aware date.

Hope this helps!
