### ISSUE TITLE
Is there a possibility to set isShaded just partly for a cell?

### ISSUE THREAD

**Issue by boboci9** [DevExpress/devextreme-reactive#3157]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

My scheduler has to accept 15 minutes (and it's duplicates) time periods as well (possible even 10 minutes in the future), but TimeTableCell component's isShaded is only working for the whole cell, is it possible somehow send to the cell the percentage of the shaded, something like topShadePercent and bottomShadePercent and then using background: linear-gradient(180deg, #FFFFFF 50%, #00FFFF 50%) we could partially shade a cell.

In this case if I have a period from 3.45 to 4.15 I can properly show the slot busy/selected

![Screen Shot 2020-11-03 at 12 30 02 AM](https://user-images.githubusercontent.com/9323474/97926459-d52af300-1d6b-11eb-91e5-8127e13d6725.png)

**Comment by AryamnovEugeniy** [comment]
Hello!

`isShaded` is necessary to correctly shade cells for the `CurrentTimeIndicator` plugin. And it is not meant to be used as you are using it. But as far as I can see, you can achieve this behaviour by a simple customization: https://codesandbox.io/s/quiet-river-iyx6n?file=/demo.js.

Regards,
Eugeniy
