### ISSUE TITLE
Summary row alignment issues with grouping and detail plugins.

### ISSUE THREAD

**Issue by hayarza** [DevExpress/devextreme-reactive#3158]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When introducing RowDetailState and TableRowDetail
Then TableSummaryRow will misalign columns. Assuming that your groupItems for SummaryState have these params showInGroupFooter: false, alignByColumn: true

### Expected Behaviour

Alignment by column parameter is respected

### Steps to Reproduce

Link to the example that reproduces the issue: [CodeSandbox](https://codesandbox.io/s/bold-mendel-tbjk6)

### Screenshots

![image](https://user-images.githubusercontent.com/57017863/97932938-80b55280-1d2e-11eb-9926-6431307623fd.png)
![image](https://user-images.githubusercontent.com/57017863/97932947-86129d00-1d2e-11eb-9053-7ff3a6718b53.png)

### Environment

- devextreme-reactive: 2.7.2
- react: 16.13.1
- browser: Chrome 86.0.4240.111
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @hayarza,

Thank you for reporting this problem. We will fix this soon.
As workaround, I suggest that you place the `TableRowDetail` plugin before the `TableGroupRow` one. Here is the updated [example](https://codesandbox.io/s/peaceful-moore-9xgzf).

**Comment by mfl512** [comment]
Hi @LazyLahtak
I find in your [example](https://codesandbox.io/s/peaceful-moore-9xgzf) , if I set `const [grouping] = useState([{ columnName: "region" }]);` to `const [grouping] = useState([{ columnName: "amount" }]);` which amount column is` alignByColumn:true`, the question remains.
![image](https://user-images.githubusercontent.com/23716767/131649397-055c209e-139a-4f52-8fe6-036688b8c954.png)

Here is [example](https://codesandbox.io/s/peaceful-moore-9xgzf?file=/demo.js) I updated. **Or is it not recommended to group columns which alignByColumn value is true?**
