### ISSUE TITLE
RFE : ripple effect on selection (material-ui)

### ISSUE THREAD

**Issue by oallouch** [DevExpress/devextreme-reactive#316]
Hi,
The pattern is use the most is:
. selection on click anywhere on the row (with a ripple effect) -> navigation to the detail page
. delete icon on the right of the row

Btw, I'd also like to be able to add a column with an icon button.

Anyway, thx for all that's already here.
Olivier

**Comment by SergeyAlexeev** [comment]
Hi,

Thanks for your feedback about Material UI appearance! 
We are already informed about [the issue with handling a row click](https://github.com/DevExpress/devextreme-reactive/issues/284) and are working on solving it.

As for using an icon button, this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/) shows how to implement such functionality.

**Comment by SergeyAlexeev** [comment]
Hi, 
 
The functionality that allows handling the `onClick` event has been implemented in the [latest](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1.0.0-alpha.10) update.

You can find a code sample [here](https://github.com/DevExpress/devextreme-reactive/issues/284#issuecomment-330196553).

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
