### ISSUE TITLE
Editing table custom add button

### ISSUE THREAD

**Issue by J4CKVVH173** [DevExpress/devextreme-reactive#3165]
I want to create a custom button that should create a new editable line when clicked. I want to put it outside of the table header. I looked to the side of the custom plugin but but I didn't understand how to do this using examples from the documentation. 
Can someone share similar examples ?[IMG_20201105_224818.jpg](https://user-images.githubusercontent.com/33596000/98289304-06e4c980-1fb9-11eb-9b22-e8342be63c37.jpg)
I want to move button like on the screenshot

**Comment by AryamnovEugeniy** [comment]
Hello!

You do not need a separate plugin to achieve the desired behaviour. You can use [Editing in Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode) instead. Here is an example where I added a button outside the Grid which creates a new row: https://codesandbox.io/s/elated-lamport-zm8vb?file=/demo.js.

Should you have any other questions, we will be happy to answer them.

**Comment by J4CKVVH173** [comment]
Thanks for your quick response ☺️. It's really work without any plugins

**Comment by AryamnovEugeniy** [comment]
I'm glad that it helped!
