### ISSUE TITLE
Indentation and tree-structure appears when updating with TemplatePlaceholder?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#3166]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hi, I was following this example to make my cells editable: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-iuw4u?file=/index.js and this worked great, but the one thing is, I noticed when I used this code in combination with `TableTreeColumn` and `CustomTreeData`, I notice 2 things:

1. The indentation for children columns disappears
2. Every row now gets a `Expanded` icon, denoting that every row is a parent row.

When I first load the grid, everything is fine. However, when I edit a row, the indentations are suddenly gone and an `Expanded` icon shows up for all the rows now. 

I did some debugging and found that it is the `TemplatePlaceholder` that is causing the issue. For some reason, when it is being rendered instead of the normal `TableCell` component, the styles for `TableTreeColumn` and `CustomTreeData` go away. I tried to remove the `styles` from the TemplatePlaceholder` component but that didn't seem to do anything - it seems to be that the `TemplatePlaceholder` itself is rendering and replacing some of the styles of the `TableCell`.

 Any ideas why?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @stmchan93,

It is difficult to reproduce the issue by your description only. Please send us a runnable project (for example, using [CodeSandbox](https://codesandbox.io/s/vibrant-turing-dlrmg?file=/demo.js)). It will help us find a solution.
