### ISSUE TITLE
Example Grid Lazyload with PureComponent

### ISSUE THREAD

**Issue by 23mluk** [DevExpress/devextreme-reactive#3167]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I followed your`re tutorial about optimize Performance in DataGrid
https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/

You`re recommendation was to use PureComponent and their is no example for the DataGrid. Their you always use Functional Component

Can you write an Example about the DataGrid with: 
-  Lazyload
-  PureComponent
-  Redux Connect

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hello @23mluk,

Here is an [example](https://codesandbox.io/s/compassionate-bohr-tcps5?file=/demo.js) based on our [Lazy Loading. Basic Setup](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#basic-setup) guide and the [React Grid Redux Integration](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/redux-integration/#react-grid-redux-integration) demo.

If you have any further questions, let us know.

**Comment by 23mluk** [comment]
Perfect thanks. But I have a question. 
If I have a Virtual table  and I want also support drag and drop grouping.
 How can I do that. Because he shows me always the "loadingRows"

![image](https://user-images.githubusercontent.com/68957230/103094801-f3d89800-45fe-11eb-8937-8201b6bc4c72.png)

Is their a way to handle that? Or is that Impossible
