### ISSUE TITLE
Add additional component after TableHeaderRow column label, but before sorting control

### ISSUE THREAD

**Issue by dontpressthat** [DevExpress/devextreme-reactive#3169]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am using a TableHeaderRow with a sortLabelComponent. In my sort label, I want to add a tooltip directly after the label title, but before the sorting control arrow. In doing so, a couple things do and do not happen:

1. If sorting is enabled on the column, the tooltip hint shows on hover, but the sorting message bubble competes with it.
2. If sorting is disabled via columnExtensions/sortingEnabled on SortingState, the sorting message bubble doesn't appear, but neither does the tooltip hint.

I was successful in using tableHeaderCellBefore template to prepend the tooltip icon on the header cell as a workaround, but I would like to have it between the column title and arrow instead.

Additionally, is there a way to assign different hover messages between the label title and the arrow?

Link to the example that reproduces the issue where column1 shows the tooltip hint and Sort message, and column2 shows nothing: https://codesandbox.io/s/devextreme-react-grid-example-plugin-and-templateconnector-forked-5ydbz?file=/index.js

### Environment

- devextreme-reactive: 2.7.1
- react: 16.8.0
- material-ui: 4.9.1

**Comment by LazyLahtak** [comment]
Hi @dontpressthat,

I suggest that you place the children of [TableHeaderRow.SortLabel](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowsortlabelprops) into a separate tooltip. Here is an [example](https://codesandbox.io/s/autumn-bash-u8vkz). Note that styles for the title and the `onTitleClick` handler are based on our [component](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/sort-label.jsx).

If you have any further questions, feel free to contact us.
