### ISSUE TITLE
Virtual Table Percentage Widths

### ISSUE THREAD

**Issue by llaver** [DevExpress/devextreme-reactive#3172]
### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

In 2019, percentage width and css unit support was [added to TableColumnResizing](https://github.com/DevExpress/devextreme-reactive/issues/411#issuecomment-532082958) as a way to dynamically set the default width of columns for Tables. This has been great to use and has really helped keep our apps looking modern no matter the screen size.

Unfortunately, [due to limitations this functionality was not added to Virtual Table](https://github.com/DevExpress/devextreme-reactive/issues/411#issuecomment-532627709), but @LazyLahtak mentioned support for `%` and `auto` would be considered. Could this functionality be added to VirtualTable, even if in a limited state? Using actual pixel widths has caused problems as we have users with many different screen sizes. 

I find the use case for VirtualTable most often is when the number of rows is so significant that virtualization is needed. Very very rarely are there enough columns to even need to scroll horizontally, much less virtualize that scrolling. Usually, I use `resizingMode="nextColumn"` and percentage widths so the user can't scroll horizontally even when expanding rows, but this is currently impossible with VirtualTable, causing either scrolling on small screens or a large amount of extra empty space at the end of the rows on large screens. This is especially noticeable when there are only 5-10 columns and the table spans the majority of the page. With percentage or auto widths, that can be avoided.

**Comment by LazyLahtak** [comment]
Hi @llaver,

Thank you for your interest in our React Grid.
We have no plans to implement this functionality in the near future. We need to research how we can support `auto` width for the Virtual Table in the current implementation. You may follow our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed if we start working on this.

As a workaround I suggest that you obtain container width and initialize column width in [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#controlled-mode). Here is an [example](https://codesandbox.io/s/rough-water-uj98o?file=/demo.js). Note that the width applies only on initialization and isn't recalculated on container resize. You may wish to refer to the solution described in the following help topic: [#2997 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/2997#issuecomment-661695516).

If you have any further questions, feel free to contact us.
