### ISSUE TITLE
Sortable Tree implementation

### ISSUE THREAD

**Issue by cobyrne09** [DevExpress/devextreme-reactive#3176]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I noticed this [previous example](https://codesandbox.io/s/zealous-shape-plld8?file=/demo.js) which is pretty great. However, one shortcoming that I see in it is that it the user is not able to see wether the row is going to be a child row or a root row as they drag. React-sortable-tree does a great job with this, but has a number of other issues (fixed-height nodes, no HOC). Very few of the available tree-sorting packages see to have all the features of devextreme (editable, highly-cusomizable nodes), so if there was a way to get this to work with devextreme, that would be awesome!

If you suggest a different package in 2020, I would be interested to hear as well. Thanks for any guidance!

### Environment

- devextreme-reactive: 2.1.0
- react: 16.8.4
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @cobyrne09,

Thank you for your interest in our React Grid.
We are working on a row reordering guide for the table and the tree data. Unfortunately, we cannot give you any estimate at the moment.
If you need this feature urgently, I suggest that you use our [TreeList for React.](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/Overview/React/Light/) Please refer to the following guide: [React Tree List. Node Drag & Drop](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/LocalReordering/React/Light/).
If you have any further questions, feel free to contact us.
