### ISSUE TITLE
In React Scheduler how to validate AppointmentForm when I click on the save button

### ISSUE THREAD

**Issue by hamcher** [DevExpress/devextreme-reactive#3177]

**Comment by AryamnovEugeniy** [comment]
Hello!

I suggest you use Editing in [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#controlled-mode) and customize [commandButtonComponent](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#appointmentformcommandbuttonprops). That will allow you to validate data when the Save button is clicked. Here is an example: https://codesandbox.io/s/clever-christian-tjkc0?file=/demo.js

**Comment by akoboy** [comment]
@AryamnovEugeniy Thank you for your solution, but how display error messages in the corresponding field instead of alert?
