### ISSUE TITLE
DataGrid Responsive

### ISSUE THREAD

**Issue by 23mluk** [DevExpress/devextreme-reactive#3178]
### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is their a way to make the Datagrid Responsive. I dont mean that columns resize. I mean that the columns stacks on each other on a certain point, or better a calculated cell Value, that I can display the Grid like a List on mobile View and display only the most important informations.

### Environment
- devextreme-reactive: 2.7.3
- react: 16.14.0
- bootstrap: none
- react-bootstrap: none
- material-ui: latest

**Comment by MaximKudriavtsev** [comment]
Hello!

We've already registered a similar issue. Please, refer to it: [#1235 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/1235#issuecomment-606413625)
