### ISSUE TITLE
Prevent link click propagation to row onClick event handler

### ISSUE THREAD

**Issue by ccarv** [DevExpress/devextreme-reactive#3180]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I have a table / grid with an `onClick` event triggering on the table row.

```javascript
<Table.Row
    {...restProps}
    style={{ cursor: 'pointer' }}
    onClick={() => {
        var link = document.createElement("a");
        link.href = '/some-link/' + row.object-id;
        link.click();
    }}
/>
```

The table row click works fine but cells with nested links causes the row `onClick` event to fire. I have searched all over and I'm unable to find a solution to prevent the click propagation from happening.

### Environment

- devextreme-reactive: 2.4.0
- react: 16.7.0-alpha.2
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 2.4.0

**Comment by LazyLahtak** [comment]
Hi @ccarv,

We've already registered a similar issue. Please, refer to it: [#2627 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/2627#issuecomment-572404301).
