### ISSUE TITLE
Hide/Disable delete button on specific row

### ISSUE THREAD

**Issue by raedabusanad** [DevExpress/devextreme-reactive#3183]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.7.4
- react: 16.4
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

Hi, 

I would like to build on top of this sample code by keeping the Edit/Delete/Cancel/Save behaviour:

https://codesandbox.io/s/5c33u

However, how can i disable/hide the delete button from certain rows based on column value?

Thanks

**Comment by LazyLahtak** [comment]
Hi @raedabusanad,

I suggest that you modify the children of [TableEditColumn.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncellprops) using [React.Children.map](https://reactjs.org/docs/react-api.html#reactchildrenmap). The children of the component are [TableEditColumn.Command](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncommandprops) components. You could return `null` for a child which "id" property is `"delete"`. Here is an [example](https://codesandbox.io/s/jovial-lumiere-g3xj3).

If you have any further questions, feel free to contact us.
