### ISSUE TITLE
Custom placeholder ViewSwitcher [Scheduler]

### ISSUE THREAD

**Issue by liliangiraudo5** [DevExpress/devextreme-reactive#3184]
### I'm using React Scheduler

Changing the "locale" property in Scheduler does not change the language in the ViewSwitcher .

How to customize this component ?

**Comment by AryamnovEugeniy** [comment]
Hello!

Locale property does not affect the `ViewSwitcher`. But you can use Views' `displayName` property to provide any name you like. Here is a small example: https://codesandbox.io/s/keen-sun-xis8r?file=/demo.js

**Comment by liliangiraudo5** [comment]
Thank's mate !
