### ISSUE TITLE
[React-Grid] Custom filtering on specific keypress 

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#3185]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

At the moment, the filtering action fires on every keypress, which leads to a big amount of requests to the backend (remote filtering). How can i specify that, for example, the filtering action only fires upon a specific keypress (e.g. Enter) ?

At the moment i see there is no option to attact a keypress event listener to the FilteringRow.

I'd hate to have to implement a custom filter component only for this

Please advise

### Environment

- devextreme-reactive: latest
- react: latest
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @vtrphan,

Thank you for your interest in our React Grid.
Unfortunately, we do not have an option to fire a filter action on a key press. We will consider this in the future.
There is an [example](https://codesandbox.io/s/zealous-blackburn-ssx3z) with a custom filter component, which fires the action on the `Enter` key press.

If you have any further questions, feel free to contact us.
