### ISSUE TITLE
Question on ApplicationForm use of SelectProps

### ISSUE THREAD

**Issue by griffithsimon** [DevExpress/devextreme-reactive#3186]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X] React Scheduler

### Description

Can you provide an example of how to use a select in the Appointment Form? Having issues trying to get it work in my custom AppointmentForm 

Thanks,

**Comment by MaximKudriavtsev** [comment]
Hi @griffithsimon,

In t[his article](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#customize-the-appointment-form), we explain how to customize an appointment form. In your case, replace `AppointmentForm.TextEditor` with [AppointmentForm.Select](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#plugin-components) or use your custom select editor.

**Comment by yarivShamash** [comment]
In a bit more detail after searching the a solution to the same problem, I understood that a select menu can be applied through the <Resources /> widget. Look at the code [here](https://codesandbox.io/s/69fu6?file=/demo.js:517-526) for an example.
If there is abetter practice for it please let me know.
