### ISSUE TITLE
How to hide default component on AppointmentForm.BasicLayout

### ISSUE THREAD

**Issue by Rakhisharma** [DevExpress/devextreme-reactive#3187]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

 How can I hide `AppointmentForm.BasicLayout's` default component elements( i.e: `Title`,`dateEditor`, `More Information`, `AllDay`, `Repeat` checkboxes)?  I am successfully able to add custom components to the AppointmentForm using `AppointmentForm.BasicLayout`, but I am not able to hide the default elements that come's with `AppointmentForm.BasicLayout`  in the AppointmentForm. 

Is it possible to hide all those elements?  Once user open's the  appointment form,  they should be able see a blank form / or only their custom component.

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

If you do not want to use all of our default components inside the `BasicLayout`, you may choose not to use it at all. Like I've done here: https://codesandbox.io/s/condescending-chaum-9jlne?file=/demo.js. And after that, you can add to it anything you want.

Should you encounter any other problem, we will be happy to assist you!

**Comment by Rakhisharma** [comment]
Thank you very much. Example was really helpful! It's solves the problem.

**Comment by AryamnovEugeniy** [comment]
I am glad that it helped!

**Comment by AkshayShenvi** [comment]
Hey @Rakhisharma, How were you able to add custom components to the AppointmentForm using AppointmentForm.BasicLayout? Any examples would be helpful
