### ISSUE TITLE
Cannot create a fixed positioned stub cell

### ISSUE THREAD

**Issue by dewren99** [DevExpress/devextreme-reactive#3188]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

![image](https://user-images.githubusercontent.com/13694167/100292992-12cc0780-2f37-11eb-94d3-918721ac63d5.png)

I am trying to place a button on the first cell of the column filtering row just under the select all checkbox. 
Although the checkbox column is fixed the button itself is not fixed. If I were to scroll the table vertically, the button also scrolls. I have tried to wrap the button component with TableFixedColumns.Cell but nothing changed.  I have limited the table width to 500px on the example below to replicate the issue.

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/table-demo-wcq7p?file=/package.json:0-364&gt;

### Environment

   - "@devexpress/dx-react-core": "2.7.0",
  -  "@devexpress/dx-react-grid": "2.7.0",
  -  "@devexpress/dx-react-grid-export": "2.7.0",
 -   "@devexpress/dx-react-grid-material-ui": "2.7.0",
  -  "@material-ui/core": "^4.11.0",
  -  "@material-ui/icons": "^4.9.1",
  -  "file-saver": "2.0.2",
 -   "react": "^16.13.1",
 -   "react-dom": "latest"

**Comment by LazyLahtak** [comment]
Hi @dewren99,

I researched your example and found that you don't pass `props` to the `ClearAllColumnFiltersButtonCell` component. Also, you completely redefine the `style` property in your component. As a result, you removed styles that the `TableFixedColumn` plugin applied to stub cells. Here is an updated [example](https://codesandbox.io/s/table-demo-forked-r3t3d).
If you have any further questions, please let us know.
