### ISSUE TITLE
Expose classes prop to dx-react-grid-material-ui components for styling

### ISSUE THREAD

**Issue by jahglow** [DevExpress/devextreme-reactive#3189]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

There's no way to style internal classes like "TableFixedCell-dividerLeft/Right" etc - because they are obfuscated by JSS in production. Drestically need an ability to style them without using a cascading approach as some things are inaccessible the cascading way. Material UI provides a robust way of doing it (via `classes` property) so please expose them

**Comment by LazyLahtak** [comment]
Hello @jahglow,

Thank you for your interest in our React Grid.

I suggest that you use the `className` property, which exists in most of our customizable components for the Material-UI framework. This property will allow you to partially redefine styles for components.
To pass a few custom classes in a component, I suggest that you use the [clsx](https://www.npmjs.com/package/clsx). Note that custom classes passed through the `className` property have higher priority than internal classes.
Here is an [example](https://codesandbox.io/s/vibrant-morning-i2y20).

If you have any further questions, let us know.
