### ISSUE TITLE
Scheduler - Month View - More Events Visible

### ISSUE THREAD

**Issue by liliangiraudo5** [DevExpress/devextreme-reactive#3190]
### I'm using ...
- [x] React Scheduler

### Description

Hello, 

I'm using the Scheduler React and I can't control the number of events visible in a day in MonthView.

I would like to know how to display a message like "Show more" when there are more than 2 events for example.

Thank you for your response!

![Capture d’écran 2020-11-26 à 16 14 24](https://user-images.githubusercontent.com/69634059/100367647-cf3ecf80-3002-11eb-8ff3-aca7668c63ae.png)

**Comment by AryamnovEugeniy** [comment]
Hello!

The Reactive Scheduler does not support this feature. If this is a must for your application, you can try our [Scheduler for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/jQuery/Light/) - it supports it out of the box.

Regards,
Eugeniy

**Comment by liliangiraudo5** [comment]
Hi Eugeniy, 

Thank you for your answer, will there be a new feature including management of this problem? 
Because my app is based on materialUI and the design of the classic scheduler doesn't match...

Sorry for my late answer, thank you very much

**Comment by AryamnovEugeniy** [comment]
For now, we do not have plans to introduce this feature. You can follow our roadmap to be informed on our plans: https://js.devexpress.com/Roadmap/.

And while we are here, could you describe why the design of our Scheduler for React does not match your requirements? It supports [Material-UI theme](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/BasicViews/React/MaterialBlueLight/). We need this information to improve our products.
Thank you!
