### ISSUE TITLE
Control the VirtualTableState "loading" via props 

### ISSUE THREAD

**Issue by dalborgo** [DevExpress/devextreme-reactive#3191]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
  If I manage the loading state with the render of a component (for example a CircularProgress), I hide the entire React Grid. I search for a way to render a loading component maintaining the Table header visible (as the lazy loading makes). I thought of using the React Grid lazy loading to take the advantage of its loading implementation.
  So, I tried to pass to the Grid component two properties: `rows` and `loading`. Is there a way to control the rows visibility based on the loading prop?

This is my idea of code...
```
const TableList = ({ rows, loading }) => {
  return (
    <Grid
      columns={columns}
      getRowId={getRowId}
      rootComponent={Root}
      rows={rows}
    >
      <VirtualTableState
        getRows={() => null}
        loading={loading}
      />
      <VirtualTable
        height="auto"
      />
      <TableHeaderRow/>
    </Grid>
  )
}
```

...but It still remains in loading state.

### Environment
- devextreme-reactive: 2.7.3
- react: 16.4
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by dalborgo** [comment]
Probably my attempt to use VirtualTableState is wrong. I found a easy solution to my easy request.

I manage the loading state using noDataCellComponent.

```
const TableList = ({ rows, loading }) => {
  
  const LoadingState = React.useCallback(() => {
    return (
      <td colSpan={columns.length} style={{ textAlign: 'center', verticalAlign: 'middle' }}>
        {loading ? <CircularProgress/> : <Typography>No data</Typography>}
      </td>
    )
  }, [loading])
  
  return (
    <Grid
      columns={columns}
      getRowId={getRowId}
      rootComponent={Root}
      rows={rows}
    >
      <VirtualTable
        height="auto"
        noDataCellComponent={LoadingState}
      />
      <TableHeaderRow/>
    </Grid>
  )
}
```

Is there a better solution?

Thanks

**Comment by LazyLahtak** [comment]
Hi @dalborgo,

`VirtualTableState` is used for remote data load in [Lazy Loading](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading) mode. If you load all data on the application startup or work with local data, you don't need to use `VirtualTableState`, it would be enough to use VirtualTable.

The [NoDataCell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table#tablenodatacellprops) component is displayed when the `rows` array is empty. For this reason, if you have at least one element in the `rows` array and the `loading` value is `true`, you will not see the `<CircularProgress/>` element.
I suggest that you use the solution from this demo: [Lazy Loading. Row Caching](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#row-caching). In this demo, we render a special element over the whole `Grid` if the `loading` value is `true`. Here is an [example](https://codesandbox.io/s/admiring-grothendieck-gdm56).

If you have any further questions, feel free to contact us.

**Comment by dalborgo** [comment]
Thank you!

**Comment by LazyLahtak** [comment]
You are welcome!
