### ISSUE TITLE
Is it possible to use filtering in the column cell instead of the TableFilterRow?

### ISSUE THREAD

**Issue by ismailat** [DevExpress/devextreme-reactive#3192]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I'm using a VirtualTable to render a large set of data (5-10k rows) and I'm using the filter, sort, grouping and column resizing features. The "heading part" of the table is occupying too much space in my app, so I want to make that header smaller while keeping the same functionalities. In order to do that I rendered the column title in the filter input as a placeholder (instead of the "Filter..." text) and it looks nice, but now that I'm showing the column title there I want to completely delete the column row. At the same time I want to keep the resizing and filtering functionalities, so is that possible with the current components?

Something like this, but the sorting arrow in the same space as the filtering input:

![image](https://user-images.githubusercontent.com/69157940/100464190-71c38500-30cd-11eb-9cb9-eaff8486e725.png)

Also is it possible to set the height of the table dynamically according to the amount of rows existing in the table? And is it possible to change the SummaryRow position to the top of the table instead of bottom? Thanks a lot in advance!

Link to the example that reproduces the issue: [link](https://codesandbox.io/s/distracted-khorana-kbmel) (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

Edit: I managed to render a custom cell that is empty, so technically it's not showing the column titles anymore, but there's still the styles of the HeaderRow that I can't modify, is there a better way to do this?

![image](https://user-images.githubusercontent.com/69157940/100590762-1ffd4380-32f5-11eb-8c5e-21beb5766759.png)

### Environment

- devextreme-reactive: 2.7.3
- react: 16.14
- browser: Firefox 83.0 (last version)
- bootstrap: none
- react-bootstrap: none
- material-ui: 2.7.3

**Comment by ismailat** [comment]
I ended up adding a custom icon in the toolbar and hiding the column row using that button. So by default the column names are hidden, and you can view them by using that icon. It's a temporal fix since I don't find any way to do it, but I would love to be able to get the sorting working in the same cell as the filter cell. I was also able to fix the rest of problems I faced playing with the height of the VirtualTable and Grid.

Another question that I had was: is it possible to force the cell contents to be 1 complete line while having the column width's as "auto"? Right now if the content of a cell is too long it gets shortened, or it can fit in multiple lines, all while being able to leave the width column calculations to the VirtualTable component itself. Is there a workaround for this? Thanks a lot for the help.

**Comment by LazyLahtak** [comment]
Hello @ismailat,

I suggest that you use the solution from the [#2119 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/2119#issuecomment-510465850). This way, you can save all features (column reordering, column resizing) and get rid of the `TableFilterRow` plugin.

To place a summary row to the top of the table, you can use the solution from the [#1998 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/1998#issuecomment-487734679).

To control the height of the Virtual Table, you may want to use the `height` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#properties) of the `VirtualTable` plugin. Here is an [example](https://codesandbox.io/s/nice-robinson-cmjiy?file=/demo.js).

We calculate the width of the Virtual Table manually and don't support the `auto` width for columns. Unfortunately, there is no way to make a column width automatically match the content width in the Virtual Table.

If you have multiple questions, we kindly ask you to create a separate issue for each of them. It will simplify processing of the issues and will help other users.

If you have any further questions, feel free to contact us.

**Comment by ismailat** [comment]
Thanks a lot for answering! The example you linked works perfectly for my needs, even though I would need to customize it a bit more for what I want, but it's really helpful. About the height of the table I ended up using height as 100% and then modifying the template of my app to fit the table in the whole viewport of the user using external containers. And about the width of the table, I'll experiment with the wrap feature to be able to fit 1-line content inside the Cell component, maybe there's a solution using CSS purely to get what I want. Thanks again!

**Comment by LazyLahtak** [comment]
Review the following guide that demonstrates how to make the Virtual Table fill the container: [React Grid - Virtual Scrolling. Fill the Container](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/#fill-the-container). Please note that if you set the `height` property to `auto` without a fixed container, table virtualization may break.

We encountered a similar issue about column widths for the Table component here: #2403. That solution is not suitable with your current implementation, but the thread could be helpful.
