### ISSUE TITLE
Series with enum data is not shown if scaleName of vertical value axis contains 'top' or 'bottom'

### ISSUE THREAD

**Issue by ajsergeev** [DevExpress/devextreme-reactive#3194]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ x] React Chart
- [ ] React Scheduler

### Current Behaviour

I'm using multiple axes configuration of chart, data is enumerated values.
If scaleName property contains 'top' or 'bottom', series are not displayed.  

### Expected Behaviour

Series should always be shown, scaleName shouldn't affect this.

### Steps to Reproduce

1) Open my CodeSandbox example bellow, demo.js
2) There is constant for sclaeName, OIL_AXIS_NAME
3) Any value of OIL_AXIS_NAME after comment "Doesn't work", chart doesn't show any series
4) Any value of OIL_AXIS_NAME after comment "Works", chart shows series

As I can see it happens because of this code in `isReadyToRenderSeries`:
`  Object.entries(restLayouts).forEach((el) => { 
    if (el[0].includes('top') || el[0].includes('bottom')) {
      height += el[1].height;
    } else {
      width += el[1].width;
    }
  });
`
Most probably Instead of includes, here should be startsWith().

Link to the example that reproduces the issue: &lt;[link to example](https://codesandbox.io/s/keen-poitras-3u36l)&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

1) [Doesn't work](http://create.dglux.com/video/devex_chart_enum_bug_doesnt_work.png)
2) [Works](http://create.dglux.com/video/devex_chart_enum_bug_works.png)
3) [Debug](http://create.dglux.com/video/devex_chart_enum_bug_debug.png)

### Environment

- devextreme-reactive: 2.7.3
- react: 16.14
- browser: Chrome 86
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11

**Comment by LazyLahtak** [comment]
Hi @ajsergeev,

Thank you for reporting this bug and sharing a possible solution. Unfortunately, this solution doesn't fix all the problems. To fix this, we need to refactor our current implementation. This is a big task that may require breaking changes. That's why, we cannot give any estimates as to when a fix can be introduced.

**Comment by ajsergeev** [comment]
Hi, Andrey!
Thanks for reply. Since workaround is simple, it’s not critical issue.
Thanks!

14 дек. 2020 г., в 18:37, Andrey Ignatovskiy <notifications@github.com> написал(а):

﻿

Hi @ajsergeev<https://urldefense.com/v3/__https://github.com/ajsergeev__;!!Po4YltK3bPMkYw!j52WOhb-xjMIFzAoYYFqzkjvcHoeHjhT74JTHph2XNRiUn4wrXzng-PVKo0Sn8uF$>,

Thank you for reporting this bug and sharing a possible solution. Unfortunately, this solution doesn't fix all the problems. To fix this, we need to refactor our current implementation. This is a big task that may require breaking changes. That's why, we cannot give any estimates as to when a fix can be introduced.
