### ISSUE TITLE
Adjust the time cell height in scheduler

### ISSUE THREAD

**Issue by dupled** [DevExpress/devextreme-reactive#3199]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I would like to ask if there is anyway to adjust the height of these hour cell? I have searched all the documentation but unable to find a way to change it, thanks.
![image](https://user-images.githubusercontent.com/25809350/101338584-be6a4580-38af-11eb-81fa-10f9336aa55d.png)

### Environment

- "@devexpress/dx-react-core": "^2.7.2"
- "@devexpress/dx-react-scheduler": "^2.7.2"
- "devexpress/dx-react-scheduler-material-ui": "^2.7.2"

**Comment by aswinckr** [comment]
I was able to change it by setting the style manually - 

```
<WeekView.TimeTableCell
            style={{height: 20}}
        />
```

**Comment by AryamnovEugeniy** [comment]
Hello!

To achieve this, you need to customize the following components: [TimeTableCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimetablecellprops), [TimeScaleLabel](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalelabelprops) and TimeScaleTickCell (our private component). I made a small example to illustrate this: https://codesandbox.io/s/broken-cdn-kv864?file=/demo.js
