### ISSUE TITLE
Cannot edit row when detail row is expanded and using inline editing

### ISSUE THREAD

**Issue by mklosterboer** [DevExpress/devextreme-reactive#3200]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When using inline editing with a detail row, you cannot edit an expanded row. This behavior is different from the standard editing which allows a row to enter edit mode even if the row is expanded.

### Expected Behaviour
Rows that are expanded should still be editable using inline editing.

### Steps to Reproduce
Minimal repo for reproduction forked from inline cell editing example:
https://codesandbox.io/s/funny-feather-o1fyx?file=/demo.js

#### Steps:
1. Click into a cell and it will show an input and enter edit mode
1. Click out of that cell
1. Expand that row with the arrow on the left
1. Attempt to click into a cell in the row that is expanded
1. The cell never displays the input

### Environment
See package.json in sandbox, but I do not believe this is related to any particular version

- devextreme-reactive: 2.6.4 in my repo, but reproduced in sandbox with 2.7.3
- react: 16.14.0
- browser: Chrome 86.0.4240.198
- bootstrap: none
- react-bootstrap: 0.33.1
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @mklosterboer,

Thank you for reporting this bug. We will fix it soon.
As workaround, I suggest you place the `TableInlineCellEditing` plugin before the `TableDetailRow` plugin. Here is an [example](https://codesandbox.io/s/silly-meninsky-27kw2?file=/demo.js).

**Comment by mklosterboer** [comment]
@LazyLahtak Thanks so much for the quick response and solution! This solution worked in my repo as well. 
Also looks like you already have a PR. I'm very impressed and appreciate your response!

**Comment by LazyLahtak** [comment]
@mklosterboer,

We have merged the PR. The fix will be available in the nearest release.
