### ISSUE TITLE
Custom select component blur

### ISSUE THREAD

**Issue by Gudrodr** [DevExpress/devextreme-reactive#3203]
### I'm using ...

- [✔️] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Click-edit table. Some of the cells are edited by Input components, some by Select components. When you click on a cell with a Select component, the Formatter component in the cell switches to the Select component, when you click on the Select component a menu appears. When you click outside the cell or select a value, the Select component is still focused, a function that log changes is not called. After an attempt to edit a cell with the Select component, when you click on a cell with an Input component in another row and in another column, editing a cell from the column with a Select component is also activated.

### Expected Behaviour

After losing focus or choosing a value, the Select component should be replaced with the cell Formatter component. The log function must be called.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/vigilant-meadow-1z2lz&gt;

### Environment

- devextreme-reactive: 2.7.3
- react: 16.13.1
- browser: Chrome Version 86.0.4240.198
- material-ui: 4.10.0

**Comment by LazyLahtak** [comment]
Hi @Gudrodr,

We have already registered the similar issue: #3123.
