### ISSUE TITLE
Edit all rows and the cell should turn into editable input

### ISSUE THREAD

**Issue by aamirbhat** [DevExpress/devextreme-reactive#3204]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

- On- right side of the search on toolbar, we should have edit
- all the rows convert into editable columns
- save option on the toolbar, will save all columns

**Comment by LazyLahtak** [comment]
Hi @aamirbhat,

I suggest that you implement a custom [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) for this. This way, you can add `Edit`, `Apply`, and `Cancel` to the [Toolbar](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/) using the `toolbarContent` [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/). In the `Template`, you can use [TemplateConnector](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template-connector/) to get [Actions](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/action/) and [Getters](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/), which allow you to control the state of rows.
Here is an [example](https://codesandbox.io/s/loving-drake-s849v).

For more information on custom plugin development, please refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).
