### ISSUE TITLE
Add new row in tree table

### ISSUE THREAD

**Issue by Gudrodr** [DevExpress/devextreme-reactive#3208]
### I'm using ...

- [✔︎] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I want to add a child row in a hierarchical table with editable rows by clicking on the button in the child row. In my example, I want to call an event of adding a row by clicking on the `<Button>Add new row</Button>` component and pass a parent row ID. Is it possible?

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/vigilant-meadow-1z2lz&gt;

### Environment

- devextreme-reactive: 2.7.3
- react: 16.13.1
- browser: Chrome Version 86.0.4240.198
- material-ui: 4.10.0

**Comment by LazyLahtak** [comment]
Hi @Gudrodr,

I suggest that you create a custom [Plugin](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/plugin/) for this. There, you can recalculate the `tableBodyRows` [getter](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#exports) using the [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) component to add additional rows. After that, you need to use the [Template](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template/) to define the content of added rows. Here is an [example](https://codesandbox.io/s/unruffled-feistel-rlxql).
To learn more about custom plugin development, refer to our guide: [React Grid - Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/).

If you have any further questions, let us know.
