### ISSUE TITLE
How to keep the TableInlineCellEditing active all the time?

### ISSUE THREAD

**Issue by ismailat** [DevExpress/devextreme-reactive#3209]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is it possible to keep the TableInlineCell component always active? I want to be able to see the inputs when loading the table instead of having to click the cell to see the edit component. Basically to be able to see it like this all the time:

![image](https://user-images.githubusercontent.com/69157940/102237285-cdc34180-3ef4-11eb-94c2-3f1c94bf02c5.png)

Link to the example that reproduces the issue: [link](https://codesandbox.io/s/amazing-firefly-86qvc?file=/src/App.js).

I tried adding a TextField Component inside the VirtualTable.Cell but the problem is that I don't know how to save the data after editing, that's why I want to use the TableInlineCell to be able to "commit changes". [Here's what I got](https://codesandbox.io/s/small-currying-mq5t0?file=/demo.js).

### Environment

- devextreme-reactive: 2.7.3
- react: 17.0.1
- browser: Firefox 83.0 (last version)
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.1

**Comment by LazyLahtak** [comment]
Hi @ismailat,

[TableInlineCellEditing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/) doesn't allow you to edit multiple cells simultaneously in the current implementation. I suggest that you use [TableEditRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-row/) with [editing in controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode). Here is an [example](https://codesandbox.io/s/withered-wood-lmh36).
Also, you may wish to move these buttons to [Toolbar](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/toolbar/). We recently discussed this case in this topic: [#3204 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/3204#issuecomment-744416395).

Let me know if this solution meets your needs.
If you have any further questions, feel free to reach out to us.

**Comment by ismailat** [comment]
Thanks for the reply! This solution is the closest one to my needs right now, but I really don't want the "Save" and "Apply" buttons, I want to directly save after changing the input. The problem with what I want to do as well is that I want to save space, because in each row later I'll want to add custom buttons that do X action (like showing a modal with X information for example), so I really don't need the save function, just being able to edit the cells as it is.

To workaround this what I was doing was rendering custom cells using VirtualTable.Cell and placing what I want inside. I managed to place 2 TextFields inside 1 column to edit information from the row and it works perfectly, but the TextField loses focus after editing, and that issue is sadly a big disadvantage for me now. I looked online and it looks like the easiest way to solve it is to wrap the TextField, but even after doing that it didn't work. Probably because I have it inside a table. I may change it to your solution.

**Comment by ismailat** [comment]
I'm going to answer myself, I managed to do it using DataTypeProviders. My objective was to have a VirtualTable component with inline editing active all the time and being able to save after each edit in the inputs. And at the same time being able to have columns with editing disabled while keeping the same format normal columns have (instead of a disabled input like in the documentation examples).

Here's the link: https://codesandbox.io/s/adoring-cannon-8tpxk?file=/demo.js
