### ISSUE TITLE
Column Resizing not working properly with Table.tableComponent specified

### ISSUE THREAD

**Issue by slicktdog08** [DevExpress/devextreme-reactive#3211]
I am running into a problem where the contents of my column cells overflow the column and remain visible even when the column is resized smaller than the content.

This is my table
`<VirtualTable
        ref={tableRef}
        height={window.innerHeight - 200}
        rowComponent={CustomTableRowComponent}
        tableComponent={CustomTableComponent}
        bodyComponent={CustomTableBodyComponent}
      />`
My issue stops happening if I comment out the tableComponent prop above. I have a custom component written for the table but I wanted to eliminate the chance I was causing this in my plugin so I copied the template from https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table.jsx and this behavior still persisted. My material ui version "@material-ui/core": "^4.9.5",

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

@devexpress/dx-react-core": "^2.1.2",
"@devexpress/dx-react-grid": "^2.1.2",
"@devexpress/dx-react-grid-material-ui": "^2.1.2",
"@material-ui/core": "^4.9.5",
"react": "^16.13.1",
- browser: Chrome

**Comment by LazyLahtak** [comment]
Hi @slicktdog08,

I couldn't reproduce this issue. Could you modify my [example](https://codesandbox.io/s/beautiful-sky-jfx5b) to reproduce this? It will help us find a solution.

**Comment by slicktdog08** [comment]
Hello @LazyLahtak Thank you a lot for your swift reply, especially during the holidays. I am going to close the issue but first let me explain what my issue was for anyone else out there.

When you create a custom TableComponent using dev express is it very important that the root of your table has the css proprerty `tableLayout: 'fixed'`. If you are missing this css property you table will not resize properly as shown below in my demo.
https://codesandbox.io/s/laughing-wozniak-mh9xc?file=/custom-table.js

Thank you for your help and **happy holidays**!
