### ISSUE TITLE
Edit and Delete command buttons outside the grid

### ISSUE THREAD

**Issue by picassadi** [DevExpress/devextreme-reactive#3212]
### I'm using 

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

Is there a possibility to place the Add,Edit and Delete commands buttons outside the grid, in a toolbar?

I am using React Grid with  material-ui.

**Comment by LazyLahtak** [comment]
Hi @picassadi,

We have already registered the similar issue: #3204.
