### ISSUE TITLE
Labels that stagger

### ISSUE THREAD

**Issue by Lagicrus** [DevExpress/devextreme-reactive#3219]
### I'm using ...
- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description
Labels that stagger or rotate to avoid overlap.
I noticed that in [https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/commonAxisSettings/label/](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/commonAxisSettings/label/) there was a method to do this, but this site seems to both break and not be up to date? 
So I was wondering if it was possible to add staggering of labels such that they don't overlap, or a way to rotate labels to avoid this behaviour.
Thanks

**Comment by LazyLahtak** [comment]
Hi @Lagicrus,

We have different products. The following repository is related to the React Grid, React Scheduler, and React Chart: [https://devexpress.github.io/devextreme-reactive/](https://devexpress.github.io/devextreme-reactive/).
The link you gave above is related to our [Chart widget](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/Overview/React/Light/). This product doesn't relate to this repository and has a different API.
To get more information about the difference between these products, please review this [ticket](https://supportcenter.devexpress.com/Ticket/Details/T811071/devextreme-react-vs-devextreme-reactive).

Also, you mentioned the feature of the Chart widget, but in the description you wrote that you are using our React Grid. Please clarify what product you are using.

**Comment by Lagicrus** [comment]
Hi @LazyLahtak ,

Sorry for the confusion, I was referring to the `@devexpress/dx-react-chart-material-ui` package and the Chart, BarSeries and ValueAxis contained within.

**Comment by LazyLahtak** [comment]
Thank you for clarification!

I suggest that you customize the [ArgumentAxis.Root](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-axis/#argumentaxisrootprops) component. In custom component, you will modify `children` whose type is `ArgumentAxis.Label`. This way, you can define the `y` property of [ArgumentAxis.Label](https://devexpress.github.io/devextreme-reactive/react/chart/docs/reference/argument-axis/#argumentaxislabelprops) components and avoid overlaps. Also, you may wish use the [react-resize-detection](https://www.npmjs.com/package/react-resize-detector). This allow you to get Axis width, detect width changes and stagger only the small Axis. Here is an [example](https://codesandbox.io/s/clever-hill-ik9gw?file=/demo.js).

If you have any further questions, feel free to contact us.

**Comment by ntwarijoshua** [comment]
Cannot update a component (`ArgumentRoot`) while rendering a different component (`ResizeDetector`). To locate the bad setState() call inside `ResizeDetector`

The above example breaks when the arguments reach max

**Comment by ntwarijoshua** [comment]
is there anyway to rotate -45 the label?

**Comment by Spawar1530** [comment]
@LazyLahtak I know this issue is closed, I've tried your code for overlapping behaviour but in my case it's not working. I have X axis greater than Y axis, I want to stagger labels on X axis, how could I achieve it?
