### ISSUE TITLE
Custom sort for dates not working in 

### ISSUE THREAD

**Issue by KostasKoufos** [DevExpress/devextreme-reactive#3220]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid

### Current Behaviour
Implemented a custom sort for dates using javascript Date objects. It sorts fine in DESC direction, but not in ASC direction.

```
const compareDate = (a, b) => {
  let datea = new Date(a);
  let dateb = new Date(b);
  return datea > dateb;
};

```
### Expected Behaviour
Sorting should work fine in both directions.

### Steps to Reproduce
Example provided in codesandbox.

https://codesandbox.io/s/hardcore-lichterman-8juc0?file=/src/App.js

### Screenshots
![image](https://user-images.githubusercontent.com/42872244/104195206-99bf3b80-5422-11eb-8a63-4c9ff76ccecd.png)

### Environment
- devextreme-reactive: xxx
- react: 17.0.0
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.2

**Comment by LazyLahtak** [comment]
Hi @KostasKoufos,

Your compare function returns a boolean value in your example. The compare function should return a number value (0 if values are equal, 1 if the first value is greater than the second, and -1 if the second is greater than the first). Here is an updated [example](https://codesandbox.io/s/dreamy-minsky-b2y1d?file=/src/App.js).

If you have further questions, feel free to contact us.
