### ISSUE TITLE
How to disable a column with custom data type provider only on edit but not on add?

### ISSUE THREAD

**Issue by ionescho** [DevExpress/devextreme-reactive#3221]
### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I know this issue has been raised before : https://github.com/DevExpress/devextreme-reactive/issues/953 <-- see Velociapcior's comment.

In March 2019 people said they will be adding this in the future.
Now, almost 2 years later there is still no way of knowing from inside a custom data type provider if your column is in an add or an edit situation in order to disable it where you need.

**Comment by ionescho** [comment]
Sorry, just found that the editorComponent of the data type provider receives a "disabled" prop and I can use a custom edit cell component to manipulate the editingEnabled prop as stated in https://github.com/DevExpress/devextreme-reactive/issues/953.
This can be closed

**Comment by LazyLahtak** [comment]
Hi @ionescho,

Thank you four your interest in our React Grid!

We have no plans to implement this feature in the near future. You can follow our [roadmap](https://js.devexpress.com/Roadmap/) to be informed once we start working on it.

By default, the `row` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/#datatypeprovidervalueeditorprops) of an editor, which is placed into the added row, is an empty object. You can check if this property has a specific non-displayed field. If the field doesn't exists, this means that the editor is placed in the added row. For example, this may be the `id` field, which we define for the added row only on committing changes. Here is an [example](https://codesandbox.io/s/nervous-voice-496o7?file=/demo.js).

If you have any further question, feel free to contact us.

**Comment by ionescho** [comment]
@LazyLahtak 
Thanks for the suggestion. In the meantime i used just that, checked the "row" prop if it's an empty object ( {} ) and if yes, it's most likely an add situation.
