### ISSUE TITLE
Limit number of items in month view with a show more button

### ISSUE THREAD

**Issue by woutergovaert** [DevExpress/devextreme-reactive#3223]
When there are many items on the same day the items on the month view are very small. It would be nice if we could limit the amount of items shown and add a +20 more link to show all of them in a modal.

**Comment by AryamnovEugeniy** [comment]
Hello,

Thank you for your interest in our product! Unfortunately, this feature is unavailable in the Reactive Scheduler.

But the [DevExtreme React Scheduler](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/) support this feature out of the box. So, if this feature is a must for you, I would recommend to try the DevExtreme React Scheduler, here is an example of this feature in action: https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/LimitAppointmentCountPerCell/React/Light/.

If you have any other questions, we will be happy to answer them!
