### ISSUE TITLE
AppointmentModel endDate should be nullable in TypeScript types

### ISSUE THREAD

**Issue by timiles** [DevExpress/devextreme-reactive#3224]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

[AppointmentModel](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-scheduler-core/src/types/scheduler-core.types.ts) endDate is not nullable in the TypeScript type. If I set endDate same as startDate, or pass an empty string to satisfy the TypeScript compiler, my zero-duration appointments do not display.

### Expected Behaviour

According to the [docs](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/#appointmentmodel), endDate can be nullable for zero-duration appointments.

How can I render zero-duration appointments using TypeScript? Here is my sample code:

```
import { ViewState } from '@devexpress/dx-react-scheduler';
import { Appointments, DateNavigator, MonthView, Scheduler, Toolbar } from '@devexpress/dx-react-scheduler-material-ui';
import { Paper } from '@material-ui/core';
import React from 'react';

export default function Test() {
  const appointments = [
    { id: 0, title: 'Test', startDate: '12 Jan 2021' },
  ];
  return (
    <Paper>
      <Scheduler data={appointments}>
        <ViewState />
        <MonthView />
        <Appointments />
        <Toolbar />
        <DateNavigator />
      </Scheduler>
    </Paper>
  );
}
```

**Comment by AryamnovEugeniy** [comment]
Hello,

I've reproduced this issue. We will fix this as soon as possible.

**Comment by SvetoFerit** [comment]
Hi,

I still can replicate this problem.

If I leave out the endDate I cannot see that appointment in the calendar.

Can you fix that, please?

Thank you.
