### ISSUE TITLE
Default Styles for React Grid

### ISSUE THREAD

**Issue by picosam** [DevExpress/devextreme-reactive#3226]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Thank you for such a great product!

When using the `Grid` component, I'm obliged to do the following (for example) to be able to "reset" styles to default Material UI:

```
import * as React from 'react';
import { FC } from 'react';
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';
import { Table as TableBase } from '@devexpress/dx-react-grid';
import { Table } from '@devexpress/dx-react-grid-material-ui';

const useStyles = makeStyles((theme: Theme) =>
	createStyles({
		row: {
			'&>th:first-child': {
				paddingLeft: 0,
			},
			'&>th': {
				paddingBottom: theme.spacing(1),
			},
			'&>td:first-child': {
				paddingLeft: 0,
			},
		},
	})
);

export const AppHeaderRow: FC<TableBase.RowProps> = (props) => {
	const classes = useStyles();
	return <Table.NoDataRow {...props} className={classes.row} />;
};

export const AppRow: FC<TableBase.DataRowProps> = (props) => {
	const classes = useStyles();
	return <Table.Row {...props} className={classes.row} />;
};
```
I would like to have a say so as to whether styles would be applied further to Material UI's default ones. Also, note that Material UI v5 is going to be introducing unstyled components -- are you going to support this approach?

### Environment

- devextreme-reactive: 2.7.4
- react: 17.0.1
- browser: irrelevant
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.2

**Comment by LazyLahtak** [comment]
Hi @picosam

Thank you for your interest in our React Grid!

Our plugins and plugin components cannot disable additional styles. We will take this possibility into account in future development.

If you need to use Material UI components without additional styles, I suggest defining custom components. Here is an [example](https://codesandbox.io/s/goofy-chandrasekhar-vtpwx). There, I defined the `cellComponent` and the `rowComponent` [properties](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#properties) in the `Table` plugin with Material UI components .

Note that some components have additional properties that we don't pass to Material components. Also, some components have additional logic. For example, in the `TableCell` component, we use the `value` property if `children` is not defined.

If you have any further question, feel free to contact us.
