### ISSUE TITLE
Grid TableGroupRow rendering issue in release 2.7.4

### ISSUE THREAD

**Issue by serche** [DevExpress/devextreme-reactive#3228]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

I have TableGroupRow rendering issue after updating up to 2.7.4 release. It can be reproduced by using Grid component with VirtualTable and TableRowDetail. See screenshots and example.

### Expected Behaviour

GroupRow renders correctly.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/mystifying-sky-0s9oy&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Screenshots

Correct:
![image](https://user-images.githubusercontent.com/6908703/104816029-243bdc80-5821-11eb-893d-005cd9ed1543.png)
Incorrect:
![image](https://user-images.githubusercontent.com/6908703/104816041-39b10680-5821-11eb-8a85-1857ee9a55f2.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @serche,

Thank you for reporting this issue. We will fix it soon.
As a workaround, you can place the `TableRowDetail` plugin before the `GroupRow` plugin. Here is an [example](https://codesandbox.io/s/cocky-glade-vp4tt).
