### ISSUE TITLE
Grid Rendering Issue - Deletion/Addition of Rows based on state update do no update the row cells properly

### ISSUE THREAD

**Issue by karanvij-ai** [DevExpress/devextreme-reactive#3229]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### Note
Looks like it is similar to below closed issue but it is still an issue for me: https://github.com/DevExpress/devextreme-reactive/issues/1565

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**dependency :** 
  "@devexpress/dx-react-core": "^2.4.0",
  "@devexpress/dx-react-grid": "^2.4.0"

### Current Behaviour

1. In the grid the rows are passed from the state. And initially the rows in the grid are rendered based on  the row array set in the state.
2. We have a requirement where if we change the value of a particular cell, we re-adjust the entire grid.(Example: Splitting and Merging based on the values of a particular/all cells)
3. Based on above statement, we have logic to update the state properly. 
Example of Split:

**Below is how state is updated:**

      **State Before Split:** 
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 02 |  50   |   0   |
      | 02 - 05 |  60   |   0   |
      
      **State After Split:**
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 01 |   0    |   0   |
      | 01 - 02 |  50   |   0   |
      | 02 - 05 |  60   |   0   |

      **Grid After Split:**
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 01 |  50   |   0   |
      | 01 - 02 |  50   |   0   |
      | 02 - 05 |  60   |   0   |

Example of Merge:
**Below is how state is updated:**

      **State Before Merge:**
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 01 |  40   |   0   |
      | 01 - 02 |  50   |   0   |
      | 02 - 05 |  60   |   0   |

      **State After Merge:** 
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 01 |  40   |   0   |
      | 01 - 05 |  60   |   0   |
      
      **Grid After Merge:**
      |   Col1   | Col2 | Col3 |
      ---------------------
      | 00 - 01 |  40   |   0   |
      | 01 - 05 |  50   |   0   |

### Expected Behaviour

Grid rows should match with final state of "after Split/Merge"

### Environment

- devextreme-reactive: "^2.4.0"
- react: "^2.4.0"
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @karanvij-ai,

Thank you for your interest in our React Grid. 

It is not quite clear what issue you faced. Could you clarify this? How do you delete and add (split) your rows? Please send us a simple project (for example, using [CodeSandbox](https://codesandbox.io/s/friendly-platform-81pv4)). It will help us resolve this issue.
