### ISSUE TITLE
How to calculate appointments today using AppointmentModel[] format

### ISSUE THREAD

**Issue by zallesov** [DevExpress/devextreme-reactive#3231]
Hello. Is there a way to calculate (not to just show) all appointments at a given time frame (today) without using external libraries to parse `rRule` and `eXdate`?

**Comment by zallesov** [comment]
I want to use the same data model in the app `AppointmentModel` and to store it in the DB. To avoid conversions. Could you point me out how can I givven a whole schedule `AppointmentModel[]` to determine what appointments I have today?

**Comment by AryamnovEugeniy** [comment]
Hello!

Appointments displayed by the Scheduler are calculated in two getters: `timeTableAppointments` and `allDayAppointments`. So, to get them, you can create your own plugin and override `timeTableAppointments` (or `allDayAppointments`) Getter there (see our article on [Custom Plugins Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/)). This will allow you to get the appointments that will be displayed on the current view.  All you need is to pick appointments of a specific date from these two getters.
I made a small example to demonstrate this approach in action: https://codesandbox.io/s/recursing-silence-b5vqv?file=/demo.js.

If you have any other questions, we will be happy to assist you!

Regards,
Eugeniy
