### ISSUE TITLE
Release date for v3

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#3233]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

When will v3 be released, to get rid of errors like findDOMNode deprecated? Thanks

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @vtrphan,

Unfortunately, we cannot give you any estimates as to when v3 will be released. For now, we need to fix some bugs and refactor components to get rid of some errors (such as `findDOMNode`). We will update this thread once we have any news.
