### ISSUE TITLE
[Scheduler > EditingState > onCommitChanges] Duplicate callback on Edit and Delete

### ISSUE THREAD

**Issue by kadenchoi** [DevExpress/devextreme-reactive#3234]
Once edit or delete an appointment, onCommitChanges will be triggered twice.

**Comment by AryamnovEugeniy** [comment]
Hello!

I could not reproduce this problem. Could you please update [my example](https://codesandbox.io/s/confident-fire-tqt98?file=/demo.js) so that I would be able to reproduce the issue?

**Comment by kadenchoi** [comment]
It seems my problem. I review my code first. Thank you for your help

「Aryamnov Eugeniy <notifications@github.com>」在 2021年1月25日週一，下午11:23 寫道：

**Comment by kadenchoi** [comment]
i didn't return data in the onCommitChanges
