### ISSUE TITLE
How to Save/Delete/Cancel appointmentForm using custom button.

### ISSUE THREAD

**Issue by Rakhisharma** [DevExpress/devextreme-reactive#3236]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
How to SAVE ,DELETE and CANCEL AppointmentForm using custom buttons as shown in screenshot? I have an appointmentForm shown as Modal(As you see in the screenshot), I don't want to use the default SAVE / DELETE/CANCEL buttons but instead I have my own button.

What I am trying to achieve:
CREATE Button -> Should save the appointment(same functionality as `SAVE` button in appointmentForm)
DELETE Button -> Should delete the appointment(same functionality as `DELETE` button in appointmentForm)
CANCEL Button => Should close the modal(same functionality as `CANCEL` button in appointmentForm))

I created a small example here for the buttons: https://codesandbox.io/s/scheduler-appointmentform-modal-vcb6r?file=/demo.js.

Would very much appreciate any help. Thank you!.

<img width="812" alt="Screenshot 2021-01-25 at 19 03 48" src="https://user-images.githubusercontent.com/9638740/105746870-48459f00-5f40-11eb-834b-87427e96fe7a.png">

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

We have a demo that demonstrates what you are trying to achieve: https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/. I suggest you use it as a starting point.

In short, you need to use AppointmentForm in Controlled mode - you will need to control its visibility with the help if `visible` and `onVisibilityChange` properties. To open or close the Appointment Form you will need to use these two properties. To save / delete an appointment pass `commitChanges` method to the AppointmentForm as a prop and call it when necessary.

If you have any other questions, we will be happy to help you.

**Comment by Rakhisharma** [comment]
Hello @AryamnovEugeniy thank you for the reply. By any chance you have same example with `Functional component` instead of classes ?

We use FC in our code base. And `connnectProps` is causing infinite loop for our component. As the behaviour of FC component differs from classes, it is causing us this issues. We would like to stick to FC, so if there is a way to do the same thing but the `FC` way, it would be a huge benefit for us. At the end I would still only want `CREATE/CANCEL/DELETE` button to work.

Thank you in advance already : )

**Comment by AryamnovEugeniy** [comment]
Hello!

Unfortunately, we do not have an example with Functional components.
But there are several ways to achieve this. For example, you may use [Redux](https://redux.js.org/) to manage your state and to access the state from child components. Or you may use `React.useCallback`.

**Comment by davidpene** [comment]
Hi @Rakhisharma 

Another option is to:
1. Wrap the TimetableCell component in a HOC
2. Overwrite the onClick handler
3. Add the data to app state (like redux) and use it in the Scheduler component

```typescript
interface ITimeTableProps {
	handleCellClick: () => void;
}

type DispatchProps = Pick<ITimeTableProps, 'handleCellClick'>;

const TimeTableCell = React.memo(({ onDoubleClick, handleCellClick, ...restProps }: any) => {
	return <DayView.TimeTableCell onClick={handleCellClick} {...restProps} />;
});

export const WrappedTimeTableCell = connect<{}, DispatchProps, any, IApplicationState>(
	() => ({}),
	(): DispatchProps => ({
                 // open up a custom modal
		handleCellClick: () => dispatch(openAppointmentModal()),
	})
)(TimeTableCell);

function CalendarDashboard(props: IProps) {
        // this comes from Redux
	const { tasks } = props;

	return (
		<Paper>
			<Scheduler data={tasks} height={660} firstDayOfWeek={1}>
				<ViewState defaultCurrentDate={Date.now()} defaultCurrentViewName='Week' />

				<DayView timeTableCellComponent={WrappedTimeTableCell} />
				<WeekView startDayHour={8} endDayHour={17} timeTableCellComponent={WrappedTimeTableCell} />
				<MonthView timeTableCellComponent={WrappedTimeTableCell} />

				<Toolbar />
				<DateNavigator />
				<TodayButton />
				<ViewSwitcher />
				<Appointments />

				<AppointmentTooltip showCloseButton showOpenButton />
			</Scheduler>
		</Paper>
	);
}
```

I hope that helps

**Comment by Rakhisharma** [comment]
Hello @davidpene Thanks for sharing the idea. I am trying to avoid using Redux for this project. But the good news is, I managed to make it work using `connectProps`.

**Comment by TJHeeringa** [comment]
Hi @Rakhisharma

I am in a similar situation as you. Would you be willing to share how you got it working?

**Comment by Rakhisharma** [comment]
Hi @TJHeeringa I followed this example [here](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/) in the docs. If you are using FC in your project, you can extend the types of `AppointmentForm.Overlay` and use it. In my case, I was using `useEffect` in `AppointmentForm basicLayout` and it was causing infinite-rendering. Having all the component in the same file inside Modal, solved the problem for me. Before my structure was something like this:

`<Modal>{children}</Modal>`

Children was `AppointmentForm.BaiscLayout` in my case, and this component was causing infinite rendering.

Now it is:

`<Modal>
      <div>
      //components goes here
      </div>
  </Modal>`
  
 I am not sure what exact problem you are facing but doing above solved my issue.

**Comment by faisalamin001** [comment]
@AryamnovEugeniy  I passed `commitChanges` in AppointmentForm's Overlay as a prop but its not working, gives **`undefined`**
