### ISSUE TITLE
How do I add custom style to an Table Column 

### ISSUE THREAD

**Issue by igormcsouza** [DevExpress/devextreme-reactive#3237]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Hello! Thank you for your great work!

I'm using the table from the example https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/ and it's perfect for what I'm doing, unless the part I need to add color to the columns according to it's type! But I just couldn't find a way to add custom CSS or anything similar to the component! There is a way to do that?

**Comment by LazyLahtak** [comment]
Hi @igormcsouza,

We have a [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#cells) where we customize the [Table.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) component based on the [Column](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/#column) name. In the same manner, you can customize cells using the [TableColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumn) type.

If you have any further questions, let us know.

**Comment by igormcsouza** [comment]
Hi there! Thank you! It worked! :D
