### ISSUE TITLE
AppointmentTooltip display on mouse hover instead of clicking on it

### ISSUE THREAD

**Issue by liliangiraudo5** [DevExpress/devextreme-reactive#3238]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Description

Hello everyone, I'm looking for a way to access the AppointmentTooltip when mouse over instead of clicking on it.
Has anyone been confronted with this and managed to get the right behaviour? Also keeping access to the header buttons?

Thank you very much !

**Comment by AryamnovEugeniy** [comment]
Hello!
We've already had a similar issue. Please, refer to it: https://github.com/DevExpress/devextreme-reactive/issues/2752
