### ISSUE TITLE
React Scheduler. How to hide events in a container

### ISSUE THREAD

**Issue by lokzzor** [DevExpress/devextreme-reactive#3239]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

dependency :
    "@devexpress/dx-react-core": "^2.7.3",
    "@devexpress/dx-react-scheduler": "^2.7.3",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.3"
    
### Current Behaviour
At the moment, events are not placed in the container, below is a screen of one looking for examples in the documentation
![Screenshot_2](https://user-images.githubusercontent.com/36513909/106261739-09129900-6233-11eb-9197-9134ca244c1a.png)

### Expected Behaviour
I would like it to be possible in the planner (month) to show only 2-3 events per day, the rest only by clicking the (more)
If this is implemented, then I'm sorry I just didn't find an example
![Screenshot_1](https://user-images.githubusercontent.com/36513909/106261740-0a43c600-6233-11eb-9046-742bc6ffab5b.png)
### Environment

- "react": "^16.13.1"
- browser: Chrome

**Comment by AryamnovEugeniy** [comment]
Hello!

We've already had a similar issue, please, refer to it: https://github.com/DevExpress/devextreme-reactive/issues/3190
