### ISSUE TITLE
React Scheduler. How to change only time format (WEEK)

### ISSUE THREAD

**Issue by lokzzor** [DevExpress/devextreme-reactive#3240]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

dependency :
    "@devexpress/dx-react-core": "^2.7.3",
    "@devexpress/dx-react-scheduler": "^2.7.3",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.3"
    
### Current Behaviour
Scheduler UI plugins can display dates that are formatted depending on the locale. To specify the locale, assign one of the supported formats to the Scheduler component's locale property.
![Screenshot_3](https://user-images.githubusercontent.com/36513909/106263299-3d875480-6235-11eb-941f-e484251cee45.png)

### Expected Behaviour
I would like the (week) planner to display the current time in 24 hour format. By default, it now displays the name in 12-hour format. When using the Localization plugin, putting Russia everything is translated into Russian, but I would like only 24 hour format, and the rest in English. If this is implemented then sorry, I just couldn't find an example.
![Screenshot_4](https://user-images.githubusercontent.com/36513909/106263294-3ceebe00-6235-11eb-940b-ab0bcf86668c.png)
### Environment

- "react": "^16.13.1"
- browser: Chrome

**Comment by AryamnovEugeniy** [comment]
Hello!

We have a demo that demonstrates how to achieve this. Here it is: https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/localization/#customize-date-formatting
