### ISSUE TITLE
Sort by epoch time, display formatted time?

### ISSUE THREAD

**Issue by tvt-joni** [DevExpress/devextreme-reactive#3241]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

    I was wondering if its possible to sort by epoch time, but display formatted time, like dd/mm/yyyy for example?

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @tvt-joni,

Our sorting mechanism can sort dates in epoch time by default. So, you can define cell data with epoch time.
However, cells can display only a string value. For this reason, you need to format date values for cells in the date column. Here is an [example](https://codesandbox.io/s/trusting-galois-jshn5).

If you have any further questions, feel free to contact us.
