### ISSUE TITLE
Custom data source for React Scheduler

### ISSUE THREAD

**Issue by nevadyzm** [DevExpress/devextreme-reactive#3243]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hello devextreme support,
Is it possible to configure a custom data source for Scheduler from @devexpress/dx-react-scheduler-material-ui package? In the documentation, I see that Scheduler from devextreme-react/scheduler has a "dataSource" attribute which allows you to provide either the data or a datastore that will provide it. I would like to do the same in my project but I'm using the scheduler-material-ui since it looks nicer and fits better with my other components (also material-ui based). 
The reason why I'm trying to do this is a large number of appointments. I was thinking that a custom dataStore would allow me to fetch only appointments that are visible on the current WeekView and fetch additional ones when user is switching from one week to another.
I would appreciate any guiadance you can offer on this.
Regards,
Michal

### Environment

- devextreme-reactive: 2.5.0
- react: 17.0.1
- browser: Chrome
- bootstrap: 4.5.3
- react-bootstrap: none
- material-ui: 4.9.5

**Comment by AryamnovEugeniy** [comment]
Hello!

Please, accept my apologies for a late answer. The Reactive Scheduler does not support `dataSource`.
A possible solution would be to manually create a request and send it to the server.

**Comment by nevadyzm** [comment]
Hello AryamnovEugeniy,
Thank you for your response. Can you please elaborate on what you mean by manually create a request and send it to the server? I see a "onNavigate" event in the scheduler so I could use that to fetch the next "page" of data but how can I get the time range that will be displayed after this "onNavigate" event is resolved?

Regards,
Michal
