### ISSUE TITLE
Export menu popover is hidden when grid is in a Panel

### ISSUE THREAD

**Issue by c-eiser13** [DevExpress/devextreme-reactive#3244]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Hi, I am using the grid in a Panel control from Fluent UI (MS Office Fabric React) project, and when using the ExportPanel and clicking the save icon, the popver is hidden behind the Panel. I've tried overriding ExportPanel.Menu and providing a target property, but I may not be doing this correctly as the popover is still appended to the body and it is still behind the panel depending on the width of the panel (sometimes it is partially visible but most sizes it is hidden behind the panel). 

Link to the example that reproduces the issue: https://codesandbox.io/s/reactgridexportinpanel-li5fk

### Environment

- devextreme-reactive: 2.7.0
- react: 16.8.5
- browser: Chrome 88
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.3

**Comment by LazyLahtak** [comment]
Hi @c-eiser13,

I researched your example an found that the `Panel` control has a `z-index: 1000000`. We use the Material UI Menu, which has `z-index: 1300`. For this reason, the `Menu` control was rendered behind the `Panel`.
I suggest that you define the `ExportPanel.Menu` component's style property `{ zIndex: 10000000 }`. Here is an [example](https://codesandbox.io/s/reactgridexportinpanel-forked-lb3ob).

If you have any further questions, feel free to contact us.

**Comment by c-eiser13** [comment]
Thanks @LazyLahtak appreciate the quick response! I completely missed the layer added by fluent UI where the z-index was included. For anyone that may stumble upon this in the future, there is a layerProps property on the Panel control where you can override the z-index of the panel. This issue was also affecting the pager control in the PagingPanel, but I am testing with the lower z-index on the <Panel> and working well so far.
