### ISSUE TITLE
Remotely trigger onValueChange

### ISSUE THREAD

**Issue by igorkrup** [DevExpress/devextreme-reactive#3255]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is there a way to remotely change other column value? I mean trigger `onValueChange`.
I know I can do that by writing own state logic but I want to avoid that.

Example: I would like to change two columns' values.

I was also thinking about writing an feature request to maybe have whole row with all columns data and it's `onValueChange` function in `onValueChange` second argument?

**Comment by LazyLahtak** [comment]
Hi @igorkrup,

Thank you for your interest in our React Grid.

We pass only the properties required for components. The use of the second argument for the `onValueChange` handler with a whole row is excessive for our components.
I suggest that you use [Editing in Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode). This way, you can get information about all rows and all actual changes. Here is an [example](https://codesandbox.io/s/musing-moore-mk6lx?file=/demo.js) where the values in the `Car` column change when the values in the `Name` column are changed.
To learn more about the Controlled and Uncontrolled modes, refer to our guide: [React Grid - Controlled (Stateless) and Uncontrolled (Stateful) Modes](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/).

If you have any further questions, feel free to contact us.
