### ISSUE TITLE
Release date for timeline view on the Material-UI React Scheduler

### ISSUE THREAD

**Issue by woutergovaert** [DevExpress/devextreme-reactive#3257]
Hello,

Do you have more information for when the timeline view will be implemented. We are currently using the Material-UI React Scheduler and I need to make a timeline view. It would be nice to know if the timeline view will be implemented any time soon so that I can maybe postpone my work on it. Best regards Wouter

**Comment by AryamnovEugeniy** [comment]
Hello!

We do not have immediate plans to implement timeline view for the Reactive Scheduler. You can find our roadmap here: https://js.devexpress.com/Roadmap/
If you need to use timeline views right now, you can try our [Scheduler for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/React/Light/).

**Comment by woutergovaert** [comment]
Maybe you need to remove it then from the coming soon section on this page.
https://devexpress.github.io/devextreme-reactive/react/scheduler/

**Comment by AryamnovEugeniy** [comment]
We will remove it, thank you!
