### ISSUE TITLE
React Grid - A scrollbar is hidden under a grid header 

### ISSUE THREAD

**Issue by onebalaban** [DevExpress/devextreme-reactive#3258]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

A grid header hides a scrollbar on scrolling.

### Expected Behaviour
The scrollbar should be displayed above the header.

### Steps to Reproduce

Demo: [Remote sorting](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/#remote-sorting) example.
Try scrolling a table in Safari.

### Screenshots

![T974878](https://user-images.githubusercontent.com/25555034/109277835-e3c07d00-7828-11eb-8b08-5f83f443e7b8.gif)

https://user-images.githubusercontent.com/25555034/109277844-e622d700-7828-11eb-8738-806d53085160.mp4

### Environment

- macOS Catalina 10.15.7 (19H2) and Safari 14.0 (15610.1.28.1.9, 15610)
- Mac OS X High Sierra 10.13.6 and Safari 14.0 (15610.1.28.1.9, 15610)

- devextreme-reactive: 2.7.4
- react: 16.14.0
- browser: Safari
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.2

### Notes
The issue doesn't occur on macOS Big Sur 11.2.2 and Safari 14.0.3 (16610.4.3.1.4).

**Comment by Krijovnick** [comment]
This bug is not reproduced in macOS Catalina 10.15.7 with Safari 15.1. I recommend you update your Safari version to the newest one to avoid this issue.
