### ISSUE TITLE
appointmentContentComponent on dragging/resing

### ISSUE THREAD

**Issue by lokomass** [DevExpress/devextreme-reactive#3268]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x ] React Scheduler

### Current Behaviour

When I'm dragging or resizing an Appointment, my custom appointmentContentComponent is not used, and default template replace my component.

### Expected Behaviour

Keep appointmentContentComponent when dragging/resizing

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-forked-94e8l?file=/index.js

### Screenshots

Here is my appointment : 

![image](https://user-images.githubusercontent.com/7886368/110301854-e1b0a800-7ff8-11eb-9d90-7edf9ee7ccca.png)

```
<Appointments
  appointmentContentComponent={
    () => <div>sdsd</div>
  }
/>
```

But when I drag/resize, my component disappears.

![image](https://user-images.githubusercontent.com/7886368/110302236-51269780-7ff9-11eb-8efc-0182a41b9e20.png)

### Environment

- react: "^16.13.1"
- browser: "Google chrome"
- bootstrap: "^4.6.0"
- react-bootstrap: "^1.5.0"
    "@devexpress/dx-react-core": "^2.7.5",
    "@devexpress/dx-react-scheduler": "^2.7.5",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.5",
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",

**Comment by atrudeau-vitall** [comment]
Hey there! Looks like you need to provide a callback for `EditingState`'s `onCommitChanges` property to get the drag and drop to work properly. [Here's a sandbox of a working example](https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-forked-inquq?file=/index.js).

You'll notice that when you're dragging, your custom component disappears. After taking a look at the [documentation](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/drag-drop-provider/#properties), it looks like you'll have to create a custom component for the `DragDropProvider`'s `draftAppointmentComponent` property to make it render the same as what you display in the scheduler while you're dragging.

Hope this helps.

**Comment by lokomass** [comment]
Thanks for your reply.
After looking at your exemple, during drag, the component is not the same (I can reproduice same block in my code), and dragging target in opacity, show the old wrong content :

![image](https://user-images.githubusercontent.com/7886368/110457727-3b81a280-80cb-11eb-8e11-316568736d06.png)

I haven't same appaerance on draggable div and I don't see How I can do.
Is it possible to get an example with same appareance on resize and drag ?
Thank you very much for reply

**Comment by lokomass** [comment]
Amazing thanks ! It look likes perfect, I will study this code, thanks a lot.
