### ISSUE TITLE
Is there a way to show AppointmentForm in DOM layout

### ISSUE THREAD

**Issue by zallesov** [DevExpress/devextreme-reactive#3271]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

- [x] React Scheduler

### Description
Our designers drew the layout where AppointmentForm is always visible. If an appointment is selected it is editing. if it is not it is used to create a new one. 
I struggle to attach the AppointmentPannel to the regular dom flow. It is always overlaying the calendar.
I have tried to override the Overlay. Provide it a reference to the div in the dom. Did not work properly.

<img width="1254" alt="Screen Shot 2021-03-09 at 13 11 56" src="https://user-images.githubusercontent.com/564452/110476133-8e625680-80d9-11eb-827a-dced309d629f.png">

I can do the modal like suggested here https://github.com/DevExpress/devextreme-reactive/issues/3225
But can not put AppointmentForm on the left Scheduler on the right.
Can you give me a hint on how to achieve this layout.
Thank you

**Comment by AryamnovEugeniy** [comment]
Hello!

Could you describe your use-case in greater detail? For example, do you want to use our Form layout or create your own? This will help us to find you a good solution.

If you want to create your own form, you do not need our plugin, you just need to use [Editing in Controlled mode](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#controlled-mode). [This demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/) could be a good starting point. We also have a [demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/view-switching/#control-the-view-externally) where view switching works with the help of an external component. You could also use this as an example.

If you want to place **our** Form's layout outside of the Scheduler, we will need to research this.
