### ISSUE TITLE
Add a name to DateEditor component

### ISSUE THREAD

**Issue by zallesov** [DevExpress/devextreme-reactive#3272]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Description

When overriding DateEditor it is impossible to tell if it is a startDate or endDate. I suggest adding a `type`  to a DateEditor component just like you did for the TextEditor. This will allow adding the right label before the date picker.

here
https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-scheduler-material-ui/src/templates/appointment-form/basic/layout.jsx#L151-L169

**Comment by AryamnovEugeniy** [comment]
Hello!

Thank you for your suggestion, we will consider this while planning our future releases. If it is necessary to add labels to the date editors, it is possible to change the [Basic Layout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#appointmentformbasiclayoutprops) itself. You can just copy our code from the file you mentioned in your comment and change everything you need.
