### ISSUE TITLE
How can I set same width on twins appointments ?

### ISSUE THREAD

**Issue by lokomass** [DevExpress/devextreme-reactive#3273]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X ] React Scheduler

### Description

On all examples on the devexpress website, events at the same time look like this : 

![image](https://user-images.githubusercontent.com/7886368/110530349-9f7f8780-811a-11eb-9319-a5762da47268.png)

In this example, events has same width and I don't know how can I do that ?

![image](https://user-images.githubusercontent.com/7886368/110530514-d6559d80-811a-11eb-9ffd-7e465fc95b21.png)

https://codesandbox.io/s/devextreme-react-scheduler-for-material-ui-forked-inquq?file=/index.js

### Environment

    react: "^16.13.1"
    browser: "Google chrome"
    bootstrap: "^4.6.0"
    react-bootstrap: "^1.5.0"
    "@devexpress/dx-react-core": "^2.7.5",
    "@devexpress/dx-react-scheduler": "^2.7.5",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.5",
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",

**Comment by atrudeau-vitall** [comment]
Hey that's actually my sandbox lol. After some messing around, it looks like the equal width appointments were default behaviour at least in version 2.5.1, which is what the sandbox uses. The latest version (2.7.5) does the stacking behaviour. I'm not sure how you'd go about changing that though, maybe go through the old 2.5.1 code and check to see how they were rendering the appointments?

**Comment by lokomass** [comment]
Thank you for reply
It seems to be vert difficult to find difference between two versions.
I Think it's user friendly to have same width.
Can I Just downgrade my module ? Or it's a bad idea ?

**Comment by AryamnovEugeniy** [comment]
Hello!

We changed this behaviour as part of 2.7.0. And it cannot be customized. But there is a workaround: you need to provide `placeAppointmentsNextToEachOther` property as true to the Appointments plugin, like I did here: https://codesandbox.io/s/frosty-sun-q8kc4.

Note that this is a private property and it may stop working in future.

**Comment by AryamnovEugeniy** [comment]
Currently, we do not have plans to delete this property. We will keep in mind your suggestions. Thank you!
