### ISSUE TITLE
BUG in property firstDayOfWeek

### ISSUE THREAD

**Issue by saintAlmond** [DevExpress/devextreme-reactive#3274]
- [x] I've searched the [issues] in this repository (https://github.com/devexpress/devextreme-reactive/issues) and I believe this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current behaviour
<## I am trying to define which day of the week should be displayed first. I am performing the process as the documentation says but it does not render the change. I think there is a bug but I am not sure. Theoretically in the documentation in the section "firstDayOfWeek" it says it should return number, but I'm running it like this firstDayOfWeek={1} and it doesn't make any changes>.

### Expected Behaviour
<!- The result should show which mount is the first column to display in the month view -->

### Steps to reproduce
`export default () => (
  <Paper>
    <Scheduler data={appointments}>
      <ViewState currentDate={currentDate} />
      <MonthView firstDayOfWeek={1} />
      <Appointments />
    </Scheduler>
  </Paper>
);
`
https://codesandbox.io/s/condescending-turing-5337h?file=/demo.js:0-555

### Screenshots
<## Use screenshots to illustrate the problem. -->
![Screenshot 2021-03-10 at 15 21 49](https://user-images.githubusercontent.com/53902132/110643472-6bf13b80-81b4-11eb-972e-8f7751ca400e.png)

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

**Comment by AryamnovEugeniy** [comment]
Hello!

I found a small mistake in your code. According to [documentation](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/#properties), `firstDayOfWeek` property should be passed to the Scheduler itself, not to a view plugin. For example, like I did here: https://codesandbox.io/s/hopeful-sunset-3ny51
