### ISSUE TITLE
AppointmentComponent dispatch onClick

### ISSUE THREAD

**Issue by lokomass** [DevExpress/devextreme-reactive#3275]
- [X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X ] React Scheduler

### Current Behaviour

When I call dispatch in custom AppointmentComponent this fix Appointment and I can't move it anymore.

### Expected Behaviour

When I call dispatch, I can drag again my component

### Steps to Reproduce

```
const AppointmentComponent = (props) => {
  const classes = event()
  const dispatch = useDispatch()
  const { data, className } = props
  return (
    <AppointmentBase
      className={classNames(classes.appointment, className)}
      onClick={() => {
        dispatch(SET_EVENT(data.id)) //this fix my event, I can't drag it anymore until I resize it, then I can again drag/drop
      }}
      {...props}
    >
      <Drop data={data}/>
    </AppointmentBase>
  )
}
```

### Environment
react: "^16.13.1"
browser: "Google chrome"
bootstrap: "^4.6.0"
react-bootstrap: "^1.5.0"
"@devexpress/dx-react-core": "^2.7.5",
"@devexpress/dx-react-scheduler": "^2.7.5",
"@devexpress/dx-react-scheduler-material-ui": "^2.7.5",
"@material-ui/core": "^4.11.3",
"@material-ui/icons": "^4.11.2",
"@testing-library/jest-dom": "^4.2.4",
"@testing-library/react": "^9.3.2",
"@testing-library/user-event": "^7.1.2",

**Comment by AryamnovEugeniy** [comment]
Hello!

I could not reproduce the issue based on your code snippet. Could you provide an example or modify [my sample](https://codesandbox.io/s/cool-johnson-umk6d?file=/demo.js) where the issue is reproduced? This will help us find a solution sooner.

**Comment by lokomass** [comment]
Hi,
I can't reproduce the problem with your sample (I'm not an expert :)) but can I send you my source code ?

**Comment by AryamnovEugeniy** [comment]
Yes, you can. But if the project is big, it may take a lot of time to debug. The best option would be to create a sandbox where the issue is reproduced.

**Comment by lokomass** [comment]
Hi,
I've clone my project to a public git : https://github.com/lokomass/temp/tree/master/beq
You can find my full functionnal code.


Here is the problem : 

When I'm calling dispatch, appointments can't be moved anymore, only resize.
I use 2 ways of dispatch : add new appointments, or edit, and select.

If I add a new appointment, or select an other, nothing can be drag anymore until I resize one of them (logical, it will re-render).

Thank you very very much for your support.

**Comment by lokomass** [comment]
Do you see the repository ?

**Comment by AryamnovEugeniy** [comment]
Yes, it is available. I will research it and get back to you once I have any results.

**Comment by lokomass** [comment]
Ok I wait for you, thank you very much.

**Comment by AryamnovEugeniy** [comment]
It seems, I found the cause of this issue. If you open `Calendar.js` and take a look at line 330 you will notice that you recreate appointment component on every rerender. This should be avoided because it reduces performance.
If you change it the way I did (take a look at the screenshot below), dragging should work correctly.

![image](https://user-images.githubusercontent.com/51905811/111329314-4472f680-862c-11eb-825e-3f53f0b749fe.png)

You may also take a look at our guide on how to improve performance: https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#avoid-declaring-statements-inside-render-methods

Let me know if this helped.

**Comment by lokomass** [comment]
You ARE a killer ! Amazing thanks again, it works !

**Comment by AryamnovEugeniy** [comment]
I am happy that it helped!
