### ISSUE TITLE
Scheduler appointment Form overlay component

### ISSUE THREAD

**Issue by attiqeurrehman** [DevExpress/devextreme-reactive#3276]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
I am trying to add overlay on appointment form but it's giving me the following error:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### Expected Behaviour
Able to assign overlay on the appointment form. 

### Steps to Reproduce
You can reproduce the error [here](https://codesandbox.io/s/infallible-gates-u01m5?file=/demo.js). You can try to uncomment line #155. 

### Environment
- devextreme-reactive: 2.7.4
- react: 17.0.1
- browser: Firefox v86.0
- material-ui: 4.11.2

**Comment by AryamnovEugeniy** [comment]
Hello!

I found a mistake in your code. You need to pass a component (either functional or class component) on the line 155. But you pass JSX markup. So, you need to convert `appointmentForm` const on the line 125 into a function. You also need to pass default props that we provide for the overlay component to the `AppointmentFormContainerBasic`. I made an example demonstrating this approach in action: https://codesandbox.io/s/withered-wildflower-1lsl6?file=/demo.js:4055-4070
