### ISSUE TITLE
Typescript error when providing custom messages to TypeFilterRow

### ISSUE THREAD

**Issue by elisoman** [DevExpress/devextreme-reactive#3277]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am getting a TS error when trying to set `messages` on the `TableFilterRow`.  I am trying to create a custom message for a filter option called 'Date contains'.

error:
```
Type '{ dateContains: string; }' is not assignable to type 'LocalizationMessages'.
  Object literal may only specify known properties, and 'dateContains' does not exist in type 'LocalizationMessages'.
```
code example:
```
<TableFilterRow
        showFilterSelector
        messages={{
          dateContains: 'Date contains',
        }}
/>
```
Is there another way to get the custom filter option label? Or, does the type need attention?

I am following this example from the docs:  https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#custom-filter-operations

### Environment

- devextreme-reactive: 2.7.4
- react: 16.13
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11

**Comment by danwoods89** [comment]
I too have this question.

**Comment by LazyLahtak** [comment]
Hi,

Thank you for reporting this issue. I noticed your PR where you fix types. I'll help you with this.
Note that we have several rules for PR naming as well as lint rules.
Please refer to our Contributing Guide: [https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md](https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md).

**Comment by danwoods89** [comment]
> Hi,
> 
> Thank you for reporting this issue. I noticed your PR where you fix types. I'll help you with this.
> Note that we have several rules for PR naming as well as lint rules.
> Please refer to our Contributing Guide: https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md.

Thanks, I have corrected the lint rules and PR naming.

**Comment by danwoods89** [comment]
@elisoman 

You can set messages with a workaround like this:         

`<TableFilterRow
          messages={dateMessages}
          iconComponent={DateFilterIcon}
          showFilterSelector
        />`

`// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const dateMessages: any = {
  dateEqual: 'Date equals',
  before: 'Date before',
  after: 'Date after',
  between: 'Date between',
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} as any;`

**Comment by elisoman** [comment]
@danwoods89 thanks for submitting a PR and for the workaround 👍

**Comment by LazyLahtak** [comment]
@danwoods89,

I see some type errors in your PR. Also we need to update our documentation. Could I update your branch or make my own PR based on yours?

**Comment by danwoods89** [comment]
> @danwoods89,
> 
> I see some type errors in your PR. Also we need to update our documentation. Could I update your branch or make my own PR based on yours?

@LazyLahtak please feel free to update my branch. Your help with type errors is much appreciated.
