### ISSUE TITLE
Fixed Header and Left for commandButtons

### ISSUE THREAD

**Issue by sukiasyan** [DevExpress/devextreme-reactive#3278]
- [x]I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

   Hi. Trying to fix commandButtons to the left. `<TableFixedColumns leftColumns={leftColumns} />` working fine for any other column but commandButton (I mean edit, delete buttons)
![Screenshot 2021-03-11 at 15 10 06](https://user-images.githubusercontent.com/5772045/110800433-74ad4480-827c-11eb-8847-185364fafbe2.png)

**Comment by LazyLahtak** [comment]
Hi @sukiasyan,

To make the column added by the [TableEditColumn](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/) plugin fixed, use [TableEditColumn.COLUMN_TYPE](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#static-fields). This value can be used in the `leftColumns` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-fixed-columns/#properties) of the `TableFixedColumns` plugin. Here is an [example](https://codesandbox.io/s/delicate-frost-qf4zu).

If you have any further questions, feel free to contact us.

**Comment by PavelA85** [comment]
How to put `TableEditColumn` on right?
`<TableFixedColumns rightColumns={leftColumns} />` does not help.
