### ISSUE TITLE
npm ERR! Failed at the devextreme-reactive@ postinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by KIndsKOpf** [DevExpress/devextreme-reactive#3279]
`Unknown option: --quiet
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devextreme-reactive@ postinstall: `check-node-version 
--quiet --node ">=6.11.1" --npm ">=5.3.0" --yarn ">=1.0.0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devextreme-reactive@ postinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

my versions:
node = v14.15.5
npm = 6.14.11

**Comment by LazyLahtak** [comment]
Hi @KIndsKOpf,

I couldn't reproduce this issue on my side. Could you describe the order of your actions? Also, you can send us a runnable project (for example, you may create a git repo, which I can download to reproduce the error). This will help us solve this issue.
