### ISSUE TITLE
Appointment Form save button closes form too fast.

### ISSUE THREAD

**Issue by wiktorkujawa** [DevExpress/devextreme-reactive#3284]
I used example from https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/overview/ (or https://codesandbox.io/s/69fu6). When I'm in AppointmentForm and after clicking 'save' button, form closes instantly and my method(graphql mutation and it's resolver) doesn't even finish the work. Is there a way to stop this behaviour(for example not closing the form or not doing it instantly).

**Comment by AryamnovEugeniy** [comment]
Hello!

As far as I can see, it takes about several hundred milliseconds to close the form. If this is not enough, you can use Appointment Form in controlled mode (it has [visible](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#properties) property). This will allow you to open and close the form when it is necessary, not when the save button is clicked.

Let me know if this helped.
