### ISSUE TITLE
I am facing a issue when using bootstrap tabs with devextreme-reactive grids inside them.  The grid for the active tab renders and displayed perfectly fine but the other tab having a tab-pane fade property does not rendered correctly.

### ISSUE THREAD

**Issue by Ali993abbas** [DevExpress/devextreme-reactive#3285]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LexDX** [comment]
Hi,

Use the way from this comment to resolve the issue: https://github.com/DevExpress/devextreme-reactive/issues/2550#issuecomment-604409085
