### ISSUE TITLE
Custom ToolBar

### ISSUE THREAD

**Issue by rossinicolas** [DevExpress/devextreme-reactive#3286]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

  How can i add a new iconbutton in the toolbar to use some actions likes add for example.

### Environment

- devextreme-reactive: 
- react: 2.7.5
- browser: Crhome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.13

**Comment by LazyLahtak** [comment]
Hi @rossinicolas,

We've already registered a similar issue. Please, refer to it: [#3204 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/3204#issuecomment-744416395).
