### ISSUE TITLE
How to change the label of Today Button in React Scheduler.

### ISSUE THREAD

**Issue by Tenkei-test** [DevExpress/devextreme-reactive#3287]
I am using React Scheduler - Date Navigation.  - [Details](https://codesandbox.io/s/vxs5o?file=/demo.js)
Using  `<TodayButton />`  Plugin, it shows the label **Today**
Can I change the label of  **Today**? Actually, I want to use the Japanese language. Instead of **Today** I want to use **今日**

Please help me solve this issue.

### I'm using ...
-  React Scheduler

**Comment by AryamnovEugeniy** [comment]
Hello!

Of course, this is possible. You need to use [messages](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/today-button/#properties) property. I made a small example to illustrate this approach in action: https://codesandbox.io/s/nifty-lalande-n98fq?file=/demo.js

**Comment by Tenkei-test** [comment]
Thanks a lot for your response.
