### ISSUE TITLE
Unable to convert the code from class based component to functional component(hook) for React Scheduler - Group Appointments

### ISSUE THREAD

**Issue by Tenkei-test** [DevExpress/devextreme-reactive#3289]
Currently, I am using this component - https://codesandbox.io/s/z3tpv
Actually, I am trying to convert the above component to a functional component(Hook). 
My code link - https://codesandbox.io/s/lucid-pine-h0w6c?file=/demo.js
But, I got an error.

Please help me to solve this error.

Thanks in advance.

### I'm using ...
- [x] React Scheduler

**Comment by AryamnovEugeniy** [comment]
Hello!

I found several mistakes in your code:
1. Resources should be an array, not an object (line 59)
2. Grouping should also be an array (line 63)
3. For functions, I would suggest to use something like useCallback, but not useState - useState just runs the function you are trying to save and you get boolean (line 64). But groupByDate must be a function, not a boolean

If you have any other questions, we will be happy to assist you!
