### ISSUE TITLE
finishCommitAppointment is not a function

### ISSUE THREAD

**Issue by 6uzm4n** [DevExpress/devextreme-reactive#3290]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

At the moment I have a working implementation of Reactive Scheduler. I now want to test drag and drop, so I added a DragDropProvider and an EditingState components to the Scheduler.

At the moment this 2 components are the simpler they can be, and they look like this:
```
</Scheduler>
  <EditingState
    onCommitChanges={(changes) => {
      console.log(changes)
    }}
  />
  {/** Rest of the components **/}
  <DragDropProvider/>
</Scheduler>
```

With this I can drag the appointments around, but at the moment of dropping the drag I get the following error:
```
Uncaught TypeError: finishCommitAppointment is not a function
    at eval (dx-react-scheduler.es.js?fdc5:1381)
    at DropTarget.handleDrag (dx-react-core.es.js?8d60:943)
    at DropTarget.eval (react-hot-loader.development.js?c2cb:717)
    at eval (dx-core.es.js?6f47:218)
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (dx-core.es.js?6f47:218)
    at DragDropProviderCore.end (dx-react-core.es.js?8d60:819)
    at onEnd (dx-react-core.es.js?8d60:892)
    at eval (dx-react-core.es.js?8d60:725)
    at batchedUpdates$1 (react-dom.development.js?61bb:21856)
``` 

Am I missing any function that I should provide? As I understand from the documentation, the only function I have to provide is `onCommitChanges`.

I am more than happy to provide more info if necessary. Thanks in advance!

### Environment

- OS: Manjaro Linux
- devextreme-reactive: 2.7.4
- react: 16.8.6
- browser: Google Chrome 88.0.4324.150
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

You need to add one of the following plugins to your application: [EditRecurrenceMenu](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/edit-recurrence-menu/) or [IntegratedEditing](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/integrated-editing/).

**Comment by 6uzm4n** [comment]
Hello! Thank you very much for your quick answer @AryamnovEugeniy!! It would be great if you could specify that one of those components needs to be added too in the documentation for [DragDropProvider](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/drag-drop-provider/), because right now they both appear as completely optional and that could be misleading to someone else too.
