### ISSUE TITLE
Is it possible to enable 'Last Day of Month' as an available option in the RecurrenceMenu?

### ISSUE THREAD

**Issue by conklin20** [DevExpress/devextreme-reactive#3292]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I am wondering how I can enable "Last Day of Month" as an option in the 'Monthly' recurrence menu. Currently, I don't see this is an option out of the box so I assume I'd need to implement my own logic? 

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@devexpress/dx-react-core": "^2.7.4",
    "@devexpress/dx-react-grid": "^2.7.4",
    "@devexpress/dx-react-grid-material-ui": "^2.7.4",
    "@devexpress/dx-react-scheduler": "^2.7.4",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.4",
    "@material-ui/core": "^4.11.2",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "@material-ui/pickers": "^3.2.10",
    "@material-ui/styles": "^4.11.2",
    "@material-ui/x-grid": "^4.0.0-alpha.18",
    "axios": "^0.21.1",
    "babel-loader": "8.1.0",
    "bootstrap": "^4.5.3",
    "d3": "^5.16.0",
    "d3-jetpack": "^2.1.1",
    "d3-scale-chromatic": "^1.5.0",
    "eslint": "^7.11.0",
    "gatsby": "^2.30.1",
    "jwt-decode": "^2.2.0",
    "material-ui-dropzone": "^2.5.0",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "query-string": "^6.13.8",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-dropdown-tree-select": "^2.5.1",
    "react-moment": "^0.9.6",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "react-select": "^3.1.1",
    "react-spring": "^8.0.27",
    "react-table": "^7.6.2",
    "react-to-print": "^2.12.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rrule": "^2.6.8",
    "styled-components": "^4.4.0",
    "webpack": "^4.44.2",
    "webpack-dev-server": "^3.11.0"
  },

![devextreme-reactive-scheduler](https://user-images.githubusercontent.com/32585166/112683439-8f1c1c00-8e3f-11eb-9131-8ba8c82d2575.png)

- devextreme-reactive: 2.7.4
- react: 16.14.0
- browser: Chrome
- bootstrap: 4.5.3
- react-bootstrap: none
- material-ui: 4.11.2

**Comment by AryamnovEugeniy** [comment]
Hello!

You are right, this option is unavailable out of the box, it is necessary to implement it. I suggest to override Form's [RecurrenceLayout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#appointmentformrecurrencelayoutprops).
