### ISSUE TITLE
Set starting scroll to a given hour

### ISSUE THREAD

**Issue by 6uzm4n** [DevExpress/devextreme-reactive#3293]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello! I have a simple question about React Scheduler regarding WeekView and DayView.

Is there any way to set the starting scroll for the WeekView and DayView so it defaults to having certain hour on top? 
The reasoning for this is that I don't want to limit the users of the Scheduler to certain startDayHour and enDayHour, but setting them both to 0 and 24 respectively is bad from a UX perspective because users will, most of the time, need to scroll to the "standard" hour they might start scheduling appointments in the majority of cases.

If there is no such feature in the library itself, what would be the best way to accomplish it?

Thanks in advance!

### Environment

- OS: Manjaro Linux
- devextreme-reactive: 2.7.4
- react: 16.8.6
- browser: Google Chrome 88.0.4324.150
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

The Scheduler does not have a method or a property to scroll to a certain position. But you can use approach described in this issue: https://github.com/DevExpress/devextreme-reactive/issues/3144. This will allow you to scroll to current time.
