### ISSUE TITLE
delete button in event of scheduler 

### ISSUE THREAD

**Issue by wowtqt** [DevExpress/devextreme-reactive#3295]
I am using 

React 17

- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using  this demo https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/
- [ ] React Scheduler

### Current Behaviour

The layout of event is outside . please see pic
![scheduler](https://user-images.githubusercontent.com/17221995/113034310-3e375b00-9192-11eb-85a8-93e75b0bee0c.png)

- devextreme-reactive: latest
- react: 17
- browser: chrome/FF
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

I could not reproduce this issue. This is how the Form looks to me in Google Chrome: 
![image](https://user-images.githubusercontent.com/51905811/113161113-c119ed80-9246-11eb-9129-690b30f37103.png)

Could you share with us any other information that would help us to reproduce the issue? Such as operating system, screen size, etc.

**Comment by wowtqt** [comment]
bug only happen with a sidebar
and can be fixed just to set fullSize to false in   AppointmentForm.Overlay
so this issue can be set 
 <AppointmentForm.Overlay
        visible={visible}
        target={target}
        fullSize={false}
        onHide={onHide}
      >

**Comment by AryamnovEugeniy** [comment]
I am glad that you found a solution! If you have any other questions, feel free to create a new issue.
