### ISSUE TITLE
Display default scroll to current time indicator.

### ISSUE THREAD

**Issue by Rsun24** [DevExpress/devextreme-reactive#3300]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I think this is simple feature, but it is useful. Display default scroll to current time indicator.

**Comment by MaximKudriavtsev** [comment]
Hello!

The Scheduler does not have a method or a property to scroll to a certain position. But you can use the approach described in this issue: https://github.com/DevExpress/devextreme-reactive/issues/3144. This will allow you to scroll to the current time.
