### ISSUE TITLE
React Grid (VirtualTable) does not show all columns and rows on first render

### ISSUE THREAD

**Issue by del-naz** [DevExpress/devextreme-reactive#3301]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

We are displaying the same Grid for different users. Sometimes on first render of the grid it is missing the last column and only a few rows are displayed. The rest of rows show a place holder. 

<img width="856" alt="partialGrid" src="https://user-images.githubusercontent.com/4042469/113420155-a8f8ba00-937d-11eb-8213-72db6f371375.png">

### Expected Behaviour

When we switch to another user, the grid renders fine and back to the original user it renders fine too.

<img width="849" alt="fullGrid" src="https://user-images.githubusercontent.com/4042469/113420196-bca42080-937d-11eb-84f9-1cfe6a0c5712.png">

### Steps to Reproduce

We have not been able to intentionally reproduce this issue.  We have enclosed the grid in an Autosizer to give the grid's container exact dimensions, but it has not helped. Please provide insight about why this is happening on first render. Why is the last column missing and why are there placeholders for the rows?

### Environment

- devextreme-reactive: 2.7.5
- react: 16.13.1
- browser: Chrome Version 89.0.4389.90
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by LazyLahtak** [comment]
Hi @del-naz,

Could you send us a runnable project (for example, using [CodeSandbox](https://codesandbox.io/s/inspiring-hellman-s33yx)). It will help us find a solution.
