### ISSUE TITLE
Disable time range like devextreme/scheduler

### ISSUE THREAD

**Issue by TMinh25** [DevExpress/devextreme-reactive#3303]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

like the title, im finding way to disable time range in react scheduler. 

this is the [example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/CellTemplates/React/DarkMoon/) of devextreme/scheduler which disable time range 

I can't find this in react scheduler docs.

### Environment

- devextreme-reactive: 2.7.5
- react: 17.0.1
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: dx-react-scheduler-material-ui: 2.7.5

**Comment by MaximKudriavtsev** [comment]
Hi @TMinh25,

Thank you for your interest in our product. This functionality is not available out of the box. To achieve this behavior, you can add some validation logic to the [onCommitChanges](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/editing-state/#properties) editing function. There, you can access edited appointments and prevent all actions according to appointment data.

To highlight cells, you can override `cellComponent` as described in the [Customize Appearance](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/fundamentals/#customize-the-appearance) section.

Could you describe why you don't use the [DevExtreme Scheduler for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/)? This component has the feature, and its functionality is much wider.

**Comment by TMinh25** [comment]
> ould you describe why you don't u
