### ISSUE TITLE
Grid paging doesn't work with cell editing

### ISSUE THREAD

**Issue by ivoovi** [DevExpress/devextreme-reactive#3308]
https://codesandbox.io/s/hopeful-dirac-5d2lj?file=/demo.js

**Comment by LazyLahtak** [comment]
Hi @ivoovi,

Thank you for your interest in our React Grid.

I researched your example and found that you placed the `PagingState` and `IntegratedPaging` plugins after the `Table` plugin. For this reason, the paging feature is broken. All State Management plugins and Data Processing plugins should be placed before UI plugins. Here is an [example](https://codesandbox.io/s/elegant-wu-4bsks).
To learn more about our plugins, refer to this article: [React Grid - Plugin Overview](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/).
If you have any further questions, feel free to contact us.
