### ISSUE TITLE
Integrate with other calendars (outlook, google calendar, etc)

### ISSUE THREAD

**Issue by baj84** [DevExpress/devextreme-reactive#3310]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

Is this possible?

**Comment by MaximKudriavtsev** [comment]
Hi @baj84,

Yes, it's possible. The React Scheduler is a client-side component; it can render data from any data source. We have an [example](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/remote-data/) with a read-only scheduler that shows appointments from Google Calendar.

To enable editing, use a third-party API in our `onCommitChanges` function and make remote changes.
