### ISSUE TITLE
Drop down on edit/insert

### ISSUE THREAD

**Issue by soodarpan-github** [DevExpress/devextreme-reactive#3314]
### I'm using ...

- [ ] React Grid - YES
- [ ] React Chart
- [ ] React Scheduler

### Description

Do we have any feature which enables us to use dropdown and selection from predefined values on edit or new row insert?

**Comment by MaximKudriavtsev** [comment]
Hi @soodarpan-github,

We have a [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/data-editing/) with described functionality. After clicking by `edit` button you can choose options for `Product`, `Region`, and `Customer` columns.
