### ISSUE TITLE
Can't reference the scheduler component

### ISSUE THREAD

**Issue by sgarciahotelbreak** [DevExpress/devextreme-reactive#3315]
- [ X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Scheduler

### Description
 
I want to use `showAppointmentPopup` so I can add a button from which I can click it and open the appointment form, but the reference does not return anything (only `{current: null}`) 

I am attempting to use the following method [showAppointmentPopup](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Methods/#showAppointmentPopupappointmentData_createNewAppointment_currentAppointmentData).

### code

```
  const schedulerRef = useRef(null);

  const handleMassiveFormToggle = () => {
    console.log("scheduler", schedulerRef.current) // this returns {current: null } so I can't find schedulerRef.current.showAppointmentPopup
  }


  return (
    <div className="content">
      <Paper>
      <Button
        onClick={() => {console.log(schedulerRef)}}
      >
        OPEN FORM BUTTON
      </Button>
        <Scheduler ref={schedulerRef} data={availabilities} locale={"en"}>
          <ViewState defaultCurrentDate={currentDate} />
          <EditingState onCommitChanges={commitChanges} />
          <MonthView locale={"es"} />
          <Toolbar flexibleSpaceComponent={ProductSelector} />
          <DateNavigator
            rootComponent={DateDisplacerLayout}
            navigationButtonComponent={DateDisplacerButtons}
          />
          <ConfirmationDialog />
          <Appointments appointmentComponent={Appointment} />
          <AppointmentTooltip showOpenButton />
          <AppointmentForm
            basicLayoutComponent={FormLayout}
            commandLayoutComponent={OverLay}
            disableSaveButton
          ></AppointmentForm>
        </Scheduler>
      </Paper>
    </div>
  );
}
```

```
    "@devexpress/dx-core": "^2.7.5",
    "@devexpress/dx-react-core": "^2.7.5",
    "@devexpress/dx-react-scheduler": "^2.7.5",
    "@devexpress/dx-react-scheduler-material-ui": "^2.7.5",
    "@material-ui/core": "^4.11.0",

```

**Comment by AryamnovEugeniy** [comment]
Hello!

The Reactive Scheduler does not have `showAppointmentPopup` method (you can find Scheduler's API in [docs](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/)). But it is possible to use Controlled Mode to open and close the Appointment Form when necessary. We have a demo where the Form is opened when an external button is clicked: https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/data-editing/

**Comment by sgarciahotelbreak** [comment]
should I be able to reference the component though? it shows as ill as well as the other components I am trying to reference. All of them but not `ViewState`

**Comment by AryamnovEugeniy** [comment]
No, it is not possible to reference the Scheduler or any of its plugins. Could you describe what you are trying to achieve? It may help us to find the solution, if any.
