### ISSUE TITLE
Grid - Typescript  - The toggleButtonComponent is not documented in FilterSelectorProps 

### ISSUE THREAD

**Issue by DevExpressSupportTeam** [DevExpress/devextreme-reactive#3318]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### I'm using ...
- [x] Reactive Grid
### Info
<p>react.development.js:220 Warning: Failed prop type: The prop <code>toggleButtonComponent</code> is marked as required in <code>FilterSelectorBase</code>, but its value is <code>undefined</code>.</p>
<p>This is the interface for FilterSelectorProps:</p>
<pre><code class="language-ts"><span class="hljs-keyword">interface</span> FilterSelectorProps {
   <span class="hljs-comment">/** A component that renders filter selector icons. */</span>
   iconComponent: React.ComponentType&lt;TableFilterRow.IconProps&gt;;
   <span class="hljs-comment">/** The currently selected filter operation. */</span>
   value: <span class="hljs-built_in">string</span>;
   <span class="hljs-comment">/** The list of available filter operations. */</span>
   availableValues: <span class="hljs-built_in">Array</span>&lt;<span class="hljs-built_in">string</span>&gt;;
   <span class="hljs-comment">/** Handles filter operation changes. */</span>
   onChange: <span class="hljs-function">(<span class="hljs-params">value: <span class="hljs-built_in">string</span></span>) =&gt;</span> <span class="hljs-built_in">void</span>;
   <span class="hljs-comment">/** Specifies whether the FilterSelector is disabled. */</span>
   disabled: <span class="hljs-built_in">boolean</span>;
   <span class="hljs-comment">/** Returns the specified localization message. */</span>
   getMessage: <span class="hljs-function">(<span class="hljs-params">messageKey: <span class="hljs-built_in">string</span></span>) =&gt;</span> <span class="hljs-built_in">string</span>;
 }<div class="icon icon-copy-alt-light copy-code" title="Copy code" data-code-id="0" onclick="supportCenter.common.codeCopy.copyToClipboard(this);"></div></code></pre>
<p><code>toggleButtonComponent</code> is not listed.</p>
<p>I'm simply trying to use the 'TableFilterRow.FilterSelector' component.</p>
<pre><code class="language-ts">&lt;TableFilterRow.FilterSelector
          availableValues={state.availableValues}
          getMessage={getMessage}
          iconComponent={DateFilterIcons}
          onChange={onChangeFilterOp}
          value={state.selectorValue}
          disabled={filteringEnabled}
        /&gt;<div class="icon icon-copy-alt-light copy-code" title="Copy code" data-code-id="1" onclick="supportCenter.common.codeCopy.copyToClipboard(this);"></div></code></pre>

**Comment by egaluza** [comment]
Hi,
It is an internal property, so we can't add it to our documentation or delete required for it.
There is a simple workaround: add to TableFilterRow.FilterSelector that contains all required properties for correct work of custom components.
Fixing this case would require a significant redesign of our product. Unfortunately, we are not in position to undertake this task at this time.
