### ISSUE TITLE
Is it possible to add selection to TableGroupRow in React Grid?

### ISSUE THREAD

**Issue by MarcusKane** [DevExpress/devextreme-reactive#3319]
Hi, I have been trying to figure out a way to add selection to the group rows, but have been unsuccessful so far. I thought that maybe adding an id to the group rows would allow them to have checkboxes generated but this did not work. Is there a way to give the group rows selection boxes that when selected will select all the children under it recursively and add only the data rows (not the group rows) to the selection state array? Any help is much appreciated, thank you in advance.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler 

Environment:
- devextreme-reactive: "1.9.1"
- react: "16.6.3"
- browser: all
- bootstrap: none
- react-bootstrap: none
- material-ui: "3.0.1"

- [CodeSandbox Example](https://codesandbox.io/s/dreamy-rubin-lh7gw?file=/demo.js
)

**Comment by MarcusKane** [comment]
Hello, just keeping in touch so you guys know I'm still interested in this issue.

**Comment by churchill1973** [comment]
I was wondering same thing..
