### ISSUE TITLE
How to update, delete and add an appointment using remote data source?

### ISSUE THREAD

**Issue by Tenkei-test** [DevExpress/devextreme-reactive#3326]
I have found an example to get the data from the remote data source [link](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/remote-data/).

Actually, I want that after adding an appointment using the appointment editing form, it will send an HTTP post request to the API.
Could you please give me an example of how to solve this issue?

Thanks in advance.

### I'm using ...
- [x] React Scheduler

**Comment by onebalaban** [comment]
Hello,

Thank you for reaching out to us. I see that you submitted a ticket to our Support Center (#T991614). We'll answer you there shortly.
