### ISSUE TITLE
Is it possible to open New Appointment Dialog from outside the component in Scheduler?

### ISSUE THREAD

**Issue by zallesov** [DevExpress/devextreme-reactive#3328]
### I'm using ...

- [ x] React Scheduler

I'm looking for a way to have a "Add new" button outside of a scheduler component which will act just like if I click on a cell to create a new Appointment. I can set the default values for the time and date, but there is just no API to open the Creation Dialog rather than clicking the cell.

**Comment by map32** [comment]
Hey I had the same problem

I solved it by making a ref to an outside div, pass it to the scheduler component using forwardref, then made a custom overlay component also wrapped in forwardref then had its target prop set to ref.
