### ISSUE TITLE
Turn off appointment splitting

### ISSUE THREAD

**Issue by baj84** [DevExpress/devextreme-reactive#3331]
My appointments have an hierarchy and as such I don't want to have the appointment splitting, I want them to just overlay each other.

Is it possible to turn off appointment splitting?

Thanks!

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

**Comment by onebalaban** [comment]
Hi,

What do you mean by "appointment splitting"? Could you please share pictures of your actual and desired appearance?
