### ISSUE TITLE
Hi Team, we are looking for similar keyboard navigation inline cell ability like this https://5vy2q8owj4.csb.app/ and it would be key for us in deciding the solution we pick. Could you please share us if there is such navigation available or in pipeline ?

### ISSUE THREAD

**Issue by shrikantpandeydotnet** [DevExpress/devextreme-reactive#3336]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by onebalaban** [comment]
Hi,

The Grid component doesn't support such keyboard navigation. We discuss possible improvements in the following thread: https://github.com/DevExpress/devextreme-reactive/issues/3141. Please note that we don't have any ETA as to when this functionality will be implemented and how.

In the meantime, you can consider using the DevExtreme [DataGrid](https://js.devexpress.com/Overview/DataGrid/) for React. You can review how keyboard navigation works in DataGrid in the following demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CustomizeKeyboardNavigation/React/Light/

Please let us know if you have additional questions.
