### ISSUE TITLE
Hi Team, we require feature to copy data from excel to react grid. Could you please suggest us if this feature is available or any suggestion how to implement it on top of react grid ?

### ISSUE THREAD

**Issue by shrikantpandeydotnet** [DevExpress/devextreme-reactive#3337]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by onebalaban** [comment]
Hi,

Unfortunately, the React Grid doesn't support the ability to copy tables from Excel files and we don't plan to implement this functionality.
