### ISSUE TITLE
grid CRUD operation sample with remote api & json

### ISSUE THREAD

**Issue by khoshbin** [DevExpress/devextreme-reactive#3338]
- [x] React Grid

### Description
Hi there , Is there any sample for crud operations with remote api & redux & bulk updates? I think this is most realistic use case
like : 
https://docs.telerik.com/kendo-ui/framework/datasource/crud#remote-transport-crud-operations
### Environment
- react: latest
- browser: firefox
- material-ui: latest

**Comment by onebalaban** [comment]
Hi,

We don't use data source instances in our Reactive components. We believe that it is better if a developer manually implements all required logic and fully controls CRUD operations. Handle the EditingState plugin's onCommitChanges event to commit changes made by an end-user in your data store: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#basic-setup
