### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gamoridev** [DevExpress/devextreme-reactive#334]
Hi, everyone!
I would like to know if it's possible to apply a new language to all plugins of the DevExtreme Table **or** even change _placeholders_ and _labels_ off Filtering and Pagination plugins manually.

Thanks in advance.

**Comment by kvet** [comment]
Hi,

Yes, you can re-define our default messages to complete this task. We allow defining custom text messages. However, this API is not documented at this moment, as it may be changed in the future.

The list of customizable text messages is listed below. They are available in the `@devexpess/dx-react-grid-bootstrap3` and `@devexpess/dx-react-grid-material-ui` packages.
- groupByColumnText in GroupingPanel
- showAllText in PagingPanel

It is also possible to change text messages for the TableEditColumn plugin by defining custom templates like we show in the following demo: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/

You can try that API and then please share your opinion. Thank you for your collaboration.

**Comment by gamoridev** [comment]
Hello, thank you for the response.

I don't need that feature right now, was just a doubt to implement in the future. So, I will wait for documentation.

That issue can be closed!

**Comment by kvet** [comment]
We've [implemented](https://github.com/DevExpress/devextreme-reactive/commit/c7581bdcdc080545b99259c178253191d5899040) this functionality, and it will be available with the next update.
