### ISSUE TITLE
Hide Appointment Form

### ISSUE THREAD

**Issue by lokzzor** [DevExpress/devextreme-reactive#3344]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
Hello please help me. I added the AppointmentForm package, thanks to which I was able to add events by clicking on a specific day. But I don't need a popup form. I created my component to add events.

### Problem
How to make the part of the code that reads the action work, but does not open the pop-up window?
{title: undefined, startDate: Sun Jun 24 2018 11:00:00 GMT+0300 (GMT+03:00), endDate: Sun Jun 24 2018 11:30:00 GMT+0300 (GMT+03:00), allDay: false}
![image](https://user-images.githubusercontent.com/36513909/119868921-532d3200-bf28-11eb-8f68-7b72b1703942.png)

https://codesandbox.io/s/zealous-aryabhata-89pik?file=/demo.js

### I would be very grateful for any help

**Comment by comertcimen** [comment]
To completely disable Appointment Form you can return null for the overlayComponent

`<AppointmentForm overlayComponent={() => null}/>`
