### ISSUE TITLE
Localization Support React Scheduler

### ISSUE THREAD

**Issue by gfiury** [DevExpress/devextreme-reactive#3345]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

I've been using [Dx react scheduler](@devexpress/dx-react-scheduler) pretty cool, we are having issues with the fact that the month view does not support the hiding or collapsing of the events. So checking the issues found that the [Dev Extreme Scheduler](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/BasicViews/React/MaterialBlueLight/) supports this feature, but does it support localization? The Dx react scheduler already does, over [here](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/localization/)

Localization is vital for us because we have multiple languages on our website.

### Environment

"devextreme": "^21.1.3",
"devextreme-react": "^21.1.3",

Thanks,
William

**Comment by AryamnovEugeniy** [comment]
Hello!

Yes, DevExtreme Scheduler supports localization. You can read more about it in this section: https://js.devexpress.com/Documentation/Guide/Common/Localization/
