### ISSUE TITLE
Is it possible to chart candlestick data?

### ISSUE THREAD

**Issue by bertdida** [DevExpress/devextreme-reactive#3346]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

I search the docs and the [issues ](https://github.com/DevExpress/devextreme-reactive/issues?q=candlestick) here for `candlestick` keyword, but didn't find result. I'm wondering if it's possible to display candlestick data (coming from [finnhub.io](https://finnhub.io/docs/api/stock-candles)) using this library.

**Comment by onebalaban** [comment]
Hi,

We don't have a candlestick chart in the DevExtreme Reactive suite. However, you can use the DevExtreme Chart component for React: https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/Candlestick/React/Light/
