### ISSUE TITLE
Appointment Form Validation

### ISSUE THREAD

**Issue by comertcimen** [DevExpress/devextreme-reactive#3347]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

1- I am trying to validate the Appointment Form before creating an appointment. If I pass required, it does not work like material ui text field. Can you provide example code with form control with disabled button on empty field and helper text? 

2- I could not disable or completely remove the repeat checkbox.

3- Select component creates a material ui warning, I tried both int and string as instance id.
(Material-UI: You have provided an out-of-range value `` for the select component.
Consider providing a value that matches one of the available options or ''.
The available values are `1`, `2`, `3`. )

4- Default value for the select component.

5- I can not see date on the appointment card. However, I can see it in tooltip. I believe it is because of my localization. 

Thank you if you can provide example code for these problems.

Link to the example code: [CodeSandbox](https://codesandbox.io/s/silly-surf-inpzz?file=/src/App.js).

### Environment

- devextreme-reactive: xxx
- react: ^16.8.6
- browser: Chrome 90
- bootstrap: none
- react-bootstrap: none
- material-ui: ^4.2.1
- @devexpress/dx-react-core: "^2.7.5",
- @devexpress/dx-react-scheduler: "^2.7.5",
- @devexpress/dx-react-scheduler-material-ui: "^2.7.5",

**Comment by comertcimen** [comment]
I solved the first issue by reading from text input and disabling save button without switching from uncontrolled mode to controlled mode. Here is the code block if you want the implement the same feature.

State:
```
titleValue: "

notesValue: "
````

Overriding components:
```
TextEditor = ({type, ...restProps}) => {
    const temp = type === "titleTextEditor" ? "titleValue" : "notesValue"
    return (
      <AppointmentForm.TextEditor
        {...restProps}
        variant="outlined"
        placeholder=""
        inputProps={{
          onChange: event => this.setState({[temp]: event.target.value})
        }}
        type={type}
      />
    )
  }

  CommandLayout = ({disableSaveButton, ...restProps}) => {
    const isEmpty = !Boolean((this.state.titleValue.trim()).length)
    return (
      <AppointmentForm.CommandLayout
        {...restProps}
        disableSaveButton={isEmpty}
      />
    )
  }
```

Appointment Form props:

```
<AppointmentForm
...
textEditorComponent={this.TextEditor}
commandLayoutComponent={this.CommandLayout}
/>

**Comment by vmvelev** [comment]
@comertcimen did you ever fix this issue?
