### ISSUE TITLE
Material UI V5 support

### ISSUE THREAD

**Issue by cp2004** [DevExpress/devextreme-reactive#3350]
### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Description

Hi, I'm using Material UI V5 alpha in a new project, and wanted to use React Chart here with this, but as I kind of expected this doesn't work, due to some of the breaking changes. Is there any plan to add support? You probably want to do it after the alpha period has ended, to avoid more breaking changes - the first beta is scheduled for the start of July I think.

I would be interested to know what your plans are here!

**Comment by vtrphan** [comment]
i want to know the roadmap for MUI v5 too

**Comment by LexDX** [comment]
Hi @cp2004 and @vtrphan,

Thank you for your interest in our components. We have plans to support Material v.5 when it is released officially if everything goes according to plan. We will update this issue once we start working on the task. Please stay tuned.

**Comment by onebalaban** [comment]
We are working on Material UI 5 support. Unfortunately, we don't have any ETA on this. We publish new functionality once everything is ready and tested, so we don't have fixed scheduled dates. Please stay tuned to our news. We'll make an update in our changelog once we support Material UI 5: https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md.
