### ISSUE TITLE
Month View compresses appointments too small  - is there functionality to only show 3/4 appointments and a 'show more' button?

### ISSUE THREAD

**Issue by AnnikaChauhan** [DevExpress/devextreme-reactive#3352]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X] React Scheduler

### Description
Hello, I was wondering if someone could assist.. Basically I'm building a scheduler in month view and on many occassions we have days with up to 10 appointments - the current component compresses these appointments/overlaps them to a point where they aren't readable. I was hoping someone had a solution to this? Maybe showing 3 or 4 appointments and a 'show more' button similar to what Google has? I can't seem to find the component that holds all appointments for a certain day. Dummy repo here: https://github.com/AnnikaChauhan/scheduler and you can see a demo of the problem here on 1st June: https://annikachauhan.github.io/scheduler/ - would be grateful for the help! 😄 

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).
https://github.com/AnnikaChauhan/scheduler
https://annikachauhan.github.io/scheduler/

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by onebalaban** [comment]
Hi,

This functionality is not implemented in our Scheduler. If it is strictly required in your application, you can try the Scheduler component for React: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/React/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/React/Light/)
