### ISSUE TITLE
VirtualTable will scroll not smooth after resize the column width.

### ISSUE THREAD

**Issue by shuijinliuxi** [DevExpress/devextreme-reactive#3359]
### I'm using ...

- [√ ] React Grid

### Steps to Reproduce

This is the demo: https://codesandbox.io/s/vigilant-turing-kybz3, it is base the https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/

First, scroll the table is smooth, but when I resize any column width, and then scroll it will not smooth.（Look the scrollBar when scrolling）

This is the demo snapshot:
![snapshot](https://user-images.githubusercontent.com/8765654/123920054-20a7a680-d9b8-11eb-85f8-84e3f55ba260.gif)

This is the our application snapshot:
![product](https://user-images.githubusercontent.com/8765654/123924365-7c742e80-d9bc-11eb-8f26-2fa6a54af489.gif)

### Environment

- react: 17.0.2
- @devexpress/dx-react-core: 2.7.6
- @devexpress/dx-react-grid: 2.7.6
- @devexpress/dx-react-grid-bootstrap4: 2.7.6

**Comment by onebalaban** [comment]
Hi,

I see that you submitted a ticket with the same inquiry: T1010587. Please avoid duplicating your inquiries, this will allow us to provide more efficient support. We'll reply to you in our Support Center.
