### ISSUE TITLE
Appointment style customisation 

### ISSUE THREAD

**Issue by jatintaggbox** [DevExpress/devextreme-reactive#3372]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
I need to design the appointments as below image 

<img width="164" alt="Screenshot 2021-07-23 at 5 40 16 PM" src="https://user-images.githubusercontent.com/70017046/126779774-f48a6056-69af-46e7-83f9-b2f639ad1468.png">

I suppose I can add more events button under Appointments component but I need guidance how to restrict height of Appointment if there are many in same time span but it should show if it is for more than 30 mins (just like it shows - overlapping all time boxes). 

below is the current view of my current schedule component:

<img width="2038" alt="Screenshot 2021-07-23 at 5 49 14 PM" src="https://user-images.githubusercontent.com/70017046/126780699-7333a3d3-ba3d-410a-9e3d-c03d26851207.png">

- devextreme-reactive: 2.7.6
- react: 17.0.1
- browser: Chrome
- bootstrap: 4.6.0
- react-bootstrap: 1.5.2
- material-ui: 4.12.2

**Comment by onebalaban** [comment]
Hi,

This functionality is not implemented in our Scheduler. If it is strictly required in your application, you can try the Scheduler component for React: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/React/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Timelines/React/Light/)
