### ISSUE TITLE
Display a minimum set number of all day events in All day Panel and on overflow show More button

### ISSUE THREAD

**Issue by repl-ullas-ml** [DevExpress/devextreme-reactive#3375]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description
 Is there a way to display a minimum set number of all day events in the all day panel. Beyond this number  would like to  show more events events like below
![mix-match-collectors](https://user-images.githubusercontent.com/11545334/127534379-d52520d3-fb5a-490f-84f1-f55d7a9f5d85.gif)

Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/determined-tesla-lgbf8?file=/demo.js&gt; 
### Environment

- devextreme-reactive: 2.7.6
- react: 17.0.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.2

**Comment by onebalaban** [comment]
Hello,

This functionality is not implemented in Scheduler. If it is strictly required, please consider using the Scheduler component for React: https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/React/Light/
