### ISSUE TITLE
Missing Typescript type which disable's users to adjust the time cell height in scheduler

### ISSUE THREAD

**Issue by repl-ullas-ml** [DevExpress/devextreme-reactive#3376]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
`timeScaleTickCellComponent` and its corresponding types are missing for typescript. This is necessary for us to override the cell height as described in https://github.com/DevExpress/devextreme-reactive/issues/3199 

![Screen Shot 2021-07-30 at 9 50 56 AM](https://user-images.githubusercontent.com/11545334/127678969-eabd61ab-0652-4181-8506-d677b4723fb5.png)

### Expected Behaviour
`timeScaleTickCellComponent` and its corresponding types should be exposed for consumption.

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/angry-wozniak-p5xx2

### Screenshots

![Screen Shot 2021-07-29 at 1 26 20 PM](https://user-images.githubusercontent.com/11545334/127553714-08543bf6-8a9d-442a-96b9-5d2ecf9207b7.png)

### Environment

- devextreme-reactive: 2.7.6
- react: 17.0.1
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.2

**Comment by karanaditya993** [comment]
@onebalaban we're experiencing the same issue on our end, is there a potential fix for this? 

@repl-ullas-ml were you able to find a workaround for this? Thanks
