### ISSUE TITLE
Material-UI v4.12+ warnings

### ISSUE THREAD

**Issue by DavidHenri008** [DevExpress/devextreme-reactive#3377]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Starting with Material-UI 4.12, many verifications have been added, with their respective warning, to encourage and facilitate migration to the future v5. Those warnings can really pollute the console.
One of the cases is the fade() function used by the getBorder() in the file utils.jsx of the dx-react-grid-material-ui package.

### Expected Behaviour
It would be interresting to use the fade() for when using matrial-ui < v4.12 and the new alpha() with material-ui >= v4.12.

### Steps to Reproduce
You can see an example of the fade() warning in the following [codesandbox](https://codesandbox.io/s/dx-grid-events-forked-hvj7s?file=/index.js)

### Environment

- devextreme-reactive: 2.7.6
- react: 17
- browser: Chrome
- material-ui: 4.12

**Comment by gfox1984** [comment]
Hey, can we have an official statement on this one? Is it a "won't fix" or will you be looking at it?

**Comment by mx-bernhard** [comment]
They are on it: https://supportcenter.devexpress.com/ticket/details/t1030031/support-for-material-ui-v5

**Comment by GreenGremlin** [comment]
The linked support ticket is for supporting v5, this issue involves deprecation messages introduced in v4.12. While those deprecations are preparing for v5, they should be addressed independently of upgrading to v5.

**Comment by JuanHeyda** [comment]
Any news about it?
