### ISSUE TITLE
Support for material ui v5.0.0-beta.0

### ISSUE THREAD

**Issue by fareeha-arshad** [DevExpress/devextreme-reactive#3378]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x]  React Grid
- [ ] React Chart
- [ ] React Scheduler

with material ui v5.0.0-beta.0

### Current Behaviour

./node_modules/@devexpress/dx-react-grid-material-ui/dist/dx-react-grid-material-ui.es.js
Attempted import error: 'withStyles' is not exported from '@material-ui/core/styles'.

### Expected Behaviour

The library should be compatible with v5 of material ui. 

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: 2.7.6
- react: 17.0.2
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 5.0.0-beta.0

**Comment by onebalaban** [comment]
We are working on Material UI 5 support. Unfortunately, we don't have any ETA on this. We publish new functionality once everything is ready and tested, so we don't have fixed scheduled dates. Please stay tuned to our news. We'll make an update in our changelog once we support Material UI 5: https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md.
