### ISSUE TITLE
Not really a coding issue but.. news on other DevExpress components than grid?

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#338]
Hey guys!

Just to say again, I think you guys are doing an awesome job with the DX React Grid!

This repo is called "devextreme-reactive" though, so maybe there's room for some other components too?

Any news on what other (if any) DevExpress components you are looking at implementing in pure React? Personally I would really love to see charting (focused on real time time-based data to show how good react is at rendering), I think React lacks good pure charting libraries so a lot of people (including myself) are using wrappers for things like Highcharts, Amcharts, Echarts etc. but if you have a strong grid control and strong charting control then you have a really good foundation to build some awesome react apps!

Anyways, just a question. Keep up the good work!

**Comment by Mehul** [comment]
Thanks Jeppe. We have some ideas for charts which we'll discuss in the coming weeks. You're feedback has been helpful. Stay tuned :)

**Comment by mtwallet** [comment]
Hi there,

Just want to ask if any progress has been made on the React Charts. I'm just starting a new project and I'm evaluating my options.

**Comment by SergeyAlexeev** [comment]
Hi,
 
We have a related task in our backlog, but we didn't start it yet. For now, we are basically working on React Grid to make it more flexible and useful.
 
Anyway, we'll let you know as soon as we have any progress.

**Comment by Krijovnick** [comment]
Hi there,

DevExtreme React Chart CTP is available now. You can find getting started guides [here](https://devexpress.github.io/devextreme-reactive/react/chart/docs/guides/getting-started/). Try our charts and share any thoughts with us in the [GitHub issue tracker](https://github.com/DevExpress/devextreme-reactive/issues).
