### ISSUE TITLE
dx scheduler - defaultAddedAppointment  does not work

### ISSUE THREAD

**Issue by map32** [DevExpress/devextreme-reactive#3380]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Current Behaviour

a code like
```
<EditingState
		onCommitChanges={commitChanges}
defaultAddedAppointment={whatever}
/>
```
does not change the default appointment object when i try to add one.

### Expected Behaviour

defaultAddedAppointment actually works to produce it

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by onebalaban** [comment]
Hi,

Could you please share a CodeSandBox example to demonstrate the issue?
