### ISSUE TITLE
Do you plan to make your components compatible with the material V5 version ?

### ISSUE THREAD

**Issue by Goochie** [DevExpress/devextreme-reactive#3382]
As i would really like to use them for a project of ours ...

**Comment by onebalaban** [comment]
Hello,

We are working on Material UI 5 support. Right now, we don't have fixed scheduled dates as we want to be sure that everything is ready and well-tested. We'll make an update in our change log once we support Material UI 5: [https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md)

**Comment by PTanwarCS** [comment]
Hi @onebalaban , any ETA on this. We are planning this integrate your solution on our solution. And we need MUI v5.
