### ISSUE TITLE
Custom Filter Cell only allows one character

### ISSUE THREAD

**Issue by JDHannan** [DevExpress/devextreme-reactive#3384]
I've come across several issues/questions raised regarding this issue with no one following through to get a real solution.

When you use a custom `cellComponent` it only lets you type one character in the filter cell before it loses focus.

[Here is a sandbox showing the problem](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-3em95?file=/index.js)

Thank you

**Comment by JDHannan** [comment]
Did I do something wrong? Does an issue normally go a calendar-month without being acknowledged?

**Comment by github-mickael-leclerc** [comment]
Same here

**Comment by dxbykov** [comment]
Hi everyone,

We completely understand your frustration and appreciate your decision to use DevExtreme Reactive. Although we do our best to process each and every GitHub issue, our resources are limited. We have to prioritize requests from users who own an active DevExtreme commercial license first. Note that a corresponding disclaimer is shown to anyone who creates a new issue:


>    We cannot guarantee a quick answer on GitHub.
>    If you own an active DevExtreme license, feel free to contact us in the Support Center (https://www.devexpress.com/ask)
    to receive an answer shortly.

Once we have resources available, we'll address open issues on GitHub. I hope this makes sense.
