### ISSUE TITLE
data property not working on appointmentContentProps

### ISSUE THREAD

**Issue by xererske** [DevExpress/devextreme-reactive#3388]
the data property isn't working on my side with the appointmentContentProps api. I have a sandbox here: https://codesandbox.io/s/mystifying-meitner-4myvr?file=/demo.js

Am I doing something wrong or what do you think?

Thanks!

**Comment by AryamnovEugeniy** [comment]
Hello!

It seems you forgot to pass data to the `AppointmentComponent`. I updated your example: https://codesandbox.io/s/strange-chaum-zqo15?file=/demo.js
