### ISSUE TITLE
scoped modules are not resolving in material ui

### ISSUE THREAD

**Issue by halloween603** [DevExpress/devextreme-reactive#339]
![capture](https://user-images.githubusercontent.com/25875190/30530299-393c1b86-9c63-11e7-9f6d-b62decc3d6c4.PNG)
when i run npm start command it is showing a module not resolved error but i got those in my node modules. can u help me out...

**Comment by kvet** [comment]
Hi,
 
Have you followed the installation instructions from the package readme file? It seems like you didn't install the 'material-ui', 'material-ui-icons', '@devexpress/dx-react-core', and '@devexpress/dx-react-grid' packages. See full installation instructions here: https://www.npmjs.com/package/@devexpress/dx-react-grid-material-ui#installation

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
