### ISSUE TITLE
Render AppointmentForm Inside AppointmentTooltip

### ISSUE THREAD

**Issue by akoboy** [DevExpress/devextreme-reactive#3392]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x ] React Scheduler

### Description

Hi! I'm using React Scheduler Material UI. How can I render AppointmentForm inside an AppointmentTooltip?

Thank you

**Comment by onebalaban** [comment]
Hi,

Scheduler doesn't have this functionality. If you need to display an appointment form in a popup, please refer to the following thread: [Is there a way to show AppointmentForm as modal?](https://github.com/DevExpress/devextreme-reactive/issues/3225)
