### ISSUE TITLE
Support Material UI version 5

### ISSUE THREAD

**Issue by daothan1211** [DevExpress/devextreme-reactive#3394]
### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Dear DevExpress support team,
I'm using React Scheduler on my project. After I upgrade Material UI to version 5 (https://mui.com/), I've faced with an issue related to unsupported Material UI version. I checked and see that on React Scheduler library, it use Material UI v4.
Could you help to guide me how to apply Material UI v5 on the library? And should you consider applying Material UI v5 (I'm using v 2.7.6)?
Thank you team.

**Comment by onebalaban** [comment]
Hello,

We are working on Material UI 5 support. Right now, we don't have fixed scheduled dates as we want to be sure that everything is ready and well-tested. We'll make an update in our change log once we support Material UI 5: https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md

**Comment by noverby** [comment]
@onebalaban Doesn't it make sense to have an issue open to track this, so people can get a notification when it is ready?

**Comment by onebalaban** [comment]
Reopened

**Comment by onebalaban** [comment]
An update.

We do not have exact estimates as to when we will accomplish this task. To support Material-UI 5, we need to migrate our library to React 17. This requires fixing a couple of issues:

[findDomNode issue](https://github.com/DevExpress/devextreme-reactive/pull/3404)
[Migration for Enzyme tests](https://github.com/DevExpress/devextreme-reactive/pull/3402)

After we complete the migration, we can start working on the Material-UI 5 support. However, the scope of work is still unclear since the Material team made some breaking changes that we need to fix in the code.

Once we have exact estimates or are ready to release the Material-UI 5 feature, we will update this thread.

**Comment by lcanavesio** [comment]
> > @jacten the packages are already released on npm. You just need to use the next or beta version. E.g:
> > ```shell
> > yarn add @devexpress/dx-core@next
> > # OR
> > yarn add @devexpress/dx-core@3.0.0-beta.1 
> > ```
> 
> Ahhh. @noverby thank you :)

@devexpress/dx-react-scheduler also has a beta or works with dx-core@3.0.0-beta.1 ?

**Comment by judgegodwins** [comment]
Hello @onebalaban . The beta release still uses @mui/styles. And this is causing an error for me.
![Screenshot from 2021-11-13 07-56-14](https://user-images.githubusercontent.com/38760034/141609328-18f9cb5f-d2de-497f-b9e4-4d422f6fc1bc.png)

How do I go around this?

**Comment by sienaguerrero** [comment]
I'm experiencing the same issue as @judgegodwins after upgrading @mui/material to [5.1.0](https://github.com/mui-org/material-ui/releases/tag/v5.1.0). 

There must have been a breaking change to `makeStyles` in 5.1.0, since it is working in 5.0.3.

**Comment by onebalaban** [comment]
Hi,

We released v3.0.0-beta.2 on November 22. Please try it and let us know if you encounter any issues.

**Comment by judgegodwins** [comment]
OK @onebalaban  after updating to latest beta version, it seems the cells are no longer clickable

**Comment by RiodeJaneiroo** [comment]
After updating to latest beta version, Column Reordering doesn't work.

**Comment by DavidHenri008** [comment]
@judgegodwins @sienaguerrero I am facing a similar issue on my side with the beta.2 version. Do you still have the problem?

**Comment by vpachedzhi** [comment]
> OK @onebalaban after updating to latest beta version, it seems the cells are no longer clickable

@onebalaban I found that when removing the `.Container-container`'s `height: 100%` fixes the non-clickable cells issue. It may break something else though

**Comment by sandeepgahlawat** [comment]
Hi Team,

First of all, I would like to appreciate all the hard work that you guys put in to make such an awesome library available to the public, and thank you so much for it.
I was wondering when will the new version 3.0 will be released or if the 3.0.0-beta.2  stable enough for use.

Best Regards

**Comment by onebalaban** [comment]
Hi,

v3.0.0-beta.2 is quite stable. We still need to fix some bugs and polish the code before we release v3.
