### ISSUE TITLE
Devextreme Scheduler React - EditReccurenceMenu/availableOperations

### ISSUE THREAD

**Issue by BartekObudzinski** [DevExpress/devextreme-reactive#3401]
Hi i wanted to disable one opiton in `availableOperations` in `EditReccurenceMenu`. It is currentAndFollowing option.

 I have used it like this: 

`export const layoutComponent = ({
  ...restProps
}: EditRecurrenceMenu.LayoutProps) => {
  return (
    <EditRecurrenceMenu.Layout
      {...restProps}
      availableOperations={['all | current']}
    />
  );
};`

And received two empty radio buttons with no message and no available operations,
and i expected `all`, and `current` option

**Comment by wdonet** [comment]
The value for `availableOperations` is an array of objects with `value` and `title` properties like below:
![imagen](https://user-images.githubusercontent.com/1031454/142145407-5dc603ca-3bad-4bcc-84d9-93a25e15ae97.png)

You can take those values from `restProps`, filter them out like you want ant then pass them out to the `<EditRecurrenceMenu.Layout>` component:

Example:
```js
export const layoutComponent = (props: EditRecurrenceMenu.LayoutProps) => {
  const { availableOperations } = props;
  const myOperations = availableOperations.filter(({ value }) => value !== 'currentAndFollowing' );
  return ( <EditRecurrenceMenu.Layout {...props} availableOperations={myOperations} /> );
};
```
