### ISSUE TITLE
devextreme-reactive scheduler Initial view from 8 o'clock

### ISSUE THREAD

**Issue by BartekObudzinski** [DevExpress/devextreme-reactive#3408]
Hi I already have, `DayView` and `WeekView` components with `startDayHour={0}` and `endDayHour={24}`, but initial view is set at 00:00 AM but i wanted to set initial view at 08:00 AM, what i should use to get this result?

**Comment by wdonet** [comment]
Did you figure it out ? I have exactly the same need but I was thinking in using CSS.  I just passed by to see if there's another solution
