### ISSUE TITLE
Keyboard Navigation for React Grid - Enter (Return) - Performs the action of the focused element doesn't switches the focused cell to the edit state.

### ISSUE THREAD

**Issue by nikhilahujaoutlook** [DevExpress/devextreme-reactive#3425]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Keyboard Navigation for React Grid - Enter (Return) - Performs the action of the focused element doesn't switches the focused cell to the edit state.

Nothing happens on click of Enter key on focused cell.

I am using 3.0.0-beta.1 of Devextreme as suggested [here](https://github.com/DevExpress/devextreme-reactive/issues/3141).

### Expected Behaviour

On click of Enter key focused cell should change to editable state.

### Steps to Reproduce

i have created a sample where issue is reproducible  [Sample](https://codesandbox.io/s/tablekeyboardnavigation-150hl?file=/index.js)

### Environment

- devextreme-reactive: 3.0.0-beta.1
- react: 17.0.2
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by nikhilahujaoutlook** [comment]
@Krijovnick Thanks for working on this. Is there a way i can try this out or do i have to wait until next beta or full release.

**Comment by Krijovnick** [comment]
@nikhilahujaoutlook You can try it in the next release.
