### ISSUE TITLE
One-Time Appointment addition ends updating a recurring appointment which was previously visualized in an edition modal

### ISSUE THREAD

**Issue by wdonet** [DevExpress/devextreme-reactive#3435]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour
Being at **Controlled Mode** :

1. Open any recurring appointment modal for edition
2. Close the modal without doing any change
3. Create a one-time appointment and click on Save
4. The Recurrence Menu appears when it should not.
  - If select "This appointment", it changes the recurring appointment at (1), adding an exception and creating a new one-time event
  - If select "This and following appointments", it changes the recurring appointment at (1) too
  - If select "All appointments", it again changes the recurring appointment at (1)

So, the first recurring appointment seems to be tied to the edition of the second action so that everything added as new data in the form, gets saved as changes for the previous recurring appointment visualized.

### Expected Behaviour
**First**: The first recurring appointment should be independent from the second addition
**Second**: Since it is a new addition the Recurrence Menu should not appear in any of both cases: one-time appointment or recurring appointment.

### Steps to Reproduce
Follow the steps above for reproducing. You can try directly at the **official demo editing page**.

Link to the example that reproduces the issue: &lt;[Controlled Mode Editing Demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/editing/#controlled-mode)&gt; 

### Screenshots
Recurring event
![imagen](https://user-images.githubusercontent.com/1031454/142288660-d3eccb7f-2654-4371-a7dc-9d058ff28bd6.png)
Closing modal for the same Recurring event without doing any change
![imagen](https://user-images.githubusercontent.com/1031454/142288744-693f77fd-314e-41ed-99e4-188381297a29.png)
Double click on any other date and time for creating a new appointment
![imagen](https://user-images.githubusercontent.com/1031454/142288818-e82d31b6-f5b9-4010-8ebe-7f32d05af78b.png)
Create a one-time appointment
![imagen](https://user-images.githubusercontent.com/1031454/142288896-e4e483f4-f03b-4d40-9776-3babc0aa8a2e.png)
You will get the Recurrence Menu
![imagen](https://user-images.githubusercontent.com/1031454/142288965-63c94cd6-6aa2-4e26-9c78-20941c06b089.png)
After selecting any of the provided options and confirm you get the previous recurring appointment updated
![imagen](https://user-images.githubusercontent.com/1031454/142289090-605cc695-cd87-41e9-9b45-df6d8d4ea945.png)

GIF
https://share.getcloudapp.com/xQujE5Rk

### Environment

In my case, I'm using these but not sure about the official web page.

- devextreme-reactive: 2.7.6
- react: 17.0.1
- browser: firefox/chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.12.2

**Comment by Krijovnick** [comment]
This issue will be closed as it was fixed in pull request #3463. You can check it in the nearest release.
