### ISSUE TITLE
Column reordering does not work when using VirtualTable (MUI v5)

### ISSUE THREAD

**Issue by RiodeJaneiroo** [DevExpress/devextreme-reactive#3461]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
When use VirtualTable and TableColumnReordering, then Reordering doesn't work (if swap headers label)

### Steps to Reproduce
Link to the example that reproduces the issue: [Codesandbox](https://codesandbox.io/s/long-cherry-zdrc4)

- devextreme-reactive: 3.0.0-beta.2
- react: 17.0.2
- browser: latest chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: **5.0.3**

**Comment by Krijovnick** [comment]
Fixed in #3451
