### ISSUE TITLE
I cant overwrite appointmentContentComponent

### ISSUE THREAD

**Issue by Shanille** [DevExpress/devextreme-reactive#3466]
Hi, 

Im just started with this package, I would like overwrite the appointmentContentComponent and I still have this error : 
TypeError: can't access property "rRule", data is undefined

Its a simple overwrite for now : 
```
return (<Appointments.AppointmentContent
    {...rest}
    style={{
      ...style
    }}
  >{data?.title}</Appointments.AppointmentContent >)
```

Can you help me ?
Thanks ! !

**Comment by onebalaban** [comment]
Hi,

Please share a runnable sample to demonstrate your entire implementation and the issue.
