### ISSUE TITLE
New appointment double tap on mobile (browser) doesn't work

### ISSUE THREAD

**Issue by SergioArrighi** [DevExpress/devextreme-reactive#3478]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [ x] React Scheduler

### Current Behaviour

Using one of your examples https://codesandbox.io/s/by7vu
Selecting mobile display option from browser (Chrome  97.0.4692.71) development tools.
Trying to create a new appointment by double tapping
No edit pane opens

### Expected Behaviour

The lateral box for adding a new appointment opens correctly.
Note: it works ok when using desktop display option.

### Steps to Reproduce

- Open the sandbox
- Copy the URL of the running page
- Paste it in a new tab
- Open developers options
- Select mobile display
- Try adding a new appointment

Link to the example that reproduces the issue: &lt;[put your link here](https://codesandbox.io/s/by7vu)&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- All info in the sandbox

**Comment by onebalaban** [comment]
Hi,

A double tap works correctly in Safari and Chrome on iOS 15. The "Device emulation" mode for the desktop version of Chrome could give incorrect results as it doesn't represent a real environment. Could you please confirm that you reproduced the issue using a **real** mobile device?
