### ISSUE TITLE
Invalid type for confirmation Dialogue messages prop 

### ISSUE THREAD

**Issue by pinchez254** [DevExpress/devextreme-reactive#3504]
The documentation species an `An object that contains localized messages` but the expected type is a react component type.
 `(property) ConfirmationDialogProps.messages?: React.ComponentType<ConfirmationDialog.LocalizationMessages> | undefined`

**Comment by Krijovnick** [comment]
@pinchez254 

It is not clear why the `ConfirmationDialogProps.messages` property expected react component type. Could you provide us with an example that shows it?

**Comment by pinchez254** [comment]
I want to modify the delete confirmation message to read something like "Are you sure you want to delete this event?" 

The comment describes the messages prop as an object that contains localised messages but the type expects a React component. 

![Screenshot 2022-02-10 at 14 39 31 (3)](https://user-images.githubusercontent.com/39158826/153401793-5ae824b4-3436-473a-9e57-ff7965ec2fa5.png)
