### ISSUE TITLE
AppointmentForm open on single click?

### ISSUE THREAD

**Issue by adriancrs** [DevExpress/devextreme-reactive#3507]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi, how can I trigger opening AppointmentForm in React Scheduler when I single click instead of double click? (I don't need AppointmentTooltip). I checked this here [here](https://supportcenter.devexpress.com/ticket/details/t951311/scheduler-how-to-open-appointment-form-with-single-click) but this doesn't seem to answer my question for the react version.

**Comment by onebalaban** [comment]
Hi,

Have a look at the following post: https://github.com/DevExpress/devextreme-reactive/issues/3225#issuecomment-759479343
