### ISSUE TITLE
Bug with drop and drag column group

### ISSUE THREAD

**Issue by armandkeller** [DevExpress/devextreme-reactive#3525]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Since the update 3.0.0, when I want to drop and drag group columns with GroupingPanel and his properties containerComponent, emptyMessageComponent, there is a bug

### Expected Behaviour

no bug when drop and drag with GroupingPanel and his properties containerComponent, emptyMessageComponent

note:
with the 2.7.6 update, no problem

### Steps to Reproduce

https://codesandbox.io/embed/intelligent-grass-hgj7h8?fontsize=14&hidenavigation=1&theme=dark

### Screenshots

![image](https://user-images.githubusercontent.com/41796633/154693667-c1619cb6-f0ec-44dd-bf8f-a92eaa7287ea.png)
![image](https://user-images.githubusercontent.com/41796633/154693807-45508884-83ba-450f-a4c0-b7e78d020b1d.png)

### Environment

- devextreme-reactive: 3.0.1
- react: 17.0.2
- browser: chrome 98.0.4758.82
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by Krijovnick** [comment]
@armandkeller You need to pass the `forwardedRef` property to `GroupPanel.Container`:
```
...
containerComponent={({ children, forwardedRef }) => (
    <GroupingPanel.Container
          style={{ width: "auto", marginRight: "10px" }}
          children={children}
          forwardedRef={forwardedRef}
    />
)}
...
```
Unfortunately, this property is not included in the documentation. We will add it in the near future.

**Comment by armandkeller** [comment]
@Krijovnick Thank you very much :)
