### ISSUE TITLE
rows Update Displays All Rows and ignores Page Sizing (CustomPaging inconsistent With Page Sizing)

### ISSUE THREAD

**Issue by ogheneovo12** [DevExpress/devextreme-reactive#3569]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

whenever i update the rows state, the grid displays all rows, while maintaining it's pageSize, i.e, i have a page size of 10 , initial row length was  10, updating row length 700,  the tables shows all 700 rows, but still maintains a page size of 10.

### Expected Behaviour

rows should get updated, and only 10 row items should be displayed, while maintaining the page size of 10.

### Steps to Reproduce

https://codesandbox.io/s/devextreme-react-grid-for-bootstrap-4-forked-yen7z7?file=/index.js

### Environment

- devextreme-reactive: 3.0.4
- react: 18
- browser: chrome
- bootstrap: 4
- react-bootstrap: none
- material-ui: none

**Comment by Krijovnick** [comment]
Hi,
The `CustomPaging` plugin is only used for remote paging, i.e in the page displays all rows requested from the server. Please refer to the [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/paging/#remote-paging) for more information. For your case, the `IntegratedPaging` plugin is more suitable.
