### ISSUE TITLE
Material UI Table / Row padding

### ISSUE THREAD

**Issue by kenzo23312** [DevExpress/devextreme-reactive#357]
Hi,

I have problem with adding padding to table's left edge or rows / header columns cells while I am removing padding from TableCellMui than my table looks like:

![image](https://user-images.githubusercontent.com/19548207/30742089-edb41d02-9f97-11e7-9056-c9418e07d916.png)

There is no padding on left side of rows and columns row.

When I add padding in global TableCellMui theme bigger than 8 px for example 16px than my list looks like: 

![image](https://user-images.githubusercontent.com/19548207/30742193-541bd8be-9f98-11e7-960f-972c6af2febb.png)

ID / Column 2 are custom cells which looks like this: 

 ```
<TableCell>
      <Typography type="body2">{someValue}</Typography>
 </TableCell>
```

This custom cells breaks padding on following cell `Column 1` and `Column 3`

`Column 1` has custom width = 200

Is this kind of bug or something is wrong in my styling?

**Comment by SergeyAlexeev** [comment]
Hi,
 
Thank you for reporting the issue. But would you please clarify what exactly appearance you wish to achieve? Do you want to change padding for all table cells?

**Comment by kenzo23312** [comment]
I would like to add padding for table left side, if I add padding to cell than occurs issue with moved some of the following cells as on the screen.

My question:
-  how to apply padding to table or data cell and column cell to be equal? 

Issue:
Creating custom cell template makes next cell in following column moved to right screen above.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification. 

In your case, I suggest you use the `tableCellTemplate` property of the [TableView](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-view/) plugin and the `headerCellTemplate` option of the [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/) plugin.

In these templates, you can add padding only for the particular cell. For example:

```js
<TableView
  tableCellTemplate={({ column, value }) => (
    (column.name === 'name' ? (
      <TableCell style={{ paddingLeft: 60 }}>
        <Typography type="body2">{value}</Typography>
      </TableCell>
    ) : undefined)
  )}
/>
```

I've created a [demo](https://stackblitz.com/edit/react-kccbii?file=index.js) that shows this approach in action.

**Comment by kenzo23312** [comment]
Ok thanks I will check that.

**Comment by bloolizard** [comment]
I've tried this but seems to have broken the sorting.  Any suggestions?

**Comment by SergeyAlexeev** [comment]
When sorting is enabled, I suggest you use a bit different approach. The idea is to add a custom CSS class for a row as shown below:

```js
const styles = {
  row: {
    '& th:first-child': {
      paddingLeft: 60,
    },
  }
};
```
Here I add a custom style only for the first cell within a row.

See this [demo](https://stackblitz.com/edit/react-if4wcg?file=index.js) as well.

**Comment by SergeyAlexeev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
 
Anyway, note that we introduced Table plugin's [components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#plugin-components) that provide a more convenient way to implement your scenario. The TableHeaderRow plugin has similar [components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#plugin-components).
