### ISSUE TITLE
BarSeries y-axis custom interval

### ISSUE THREAD

**Issue by fanorenantsoa** [DevExpress/devextreme-reactive#3576]
Hello, I use BarSeries component then I need to specify a custom interval for the Y axis, like 0, 50 000, 100 000, 150 000, 200 000,...

I want to change those values in this screenshot:
![image](https://user-images.githubusercontent.com/18212292/194020113-32e2f900-179a-4b7b-908b-21dc3a17e762.png)

How to do that please ?

Thank you in advance.

**Comment by fanorenantsoa** [comment]
Is there someone who can help here please ?

**Comment by Krijovnick** [comment]
Hi @fanorenantsoa 

We have already registered a similar https://github.com/DevExpress/devextreme-reactive/issues/2306.

**Comment by fanorenantsoa** [comment]
Hi @Krijovnick , thank you for response.  I've checked.

But I didn't mean the space between Argument axis labels.

I want to specify the interval, so replace 0, 20 000, 40 000, 60 000... values to 0, 50 000, 100 000, 150 000, 200 000...

Is there a way to do this ?

**Comment by Krijovnick** [comment]
@fanorenantsoa   Unfortunately, it is not possible to change the interval between ticks in Reactive Charts.
