### ISSUE TITLE
VirtualTable row with word wrap causes a rendering glitch

### ISSUE THREAD

**Issue by CamJohnson26** [DevExpress/devextreme-reactive#3583]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

Currently if a column has word wrap enabled and the text to display in that row is above a certain size, it causes you to not be able to scroll past that row. If you do, it triggers an infinite refresh in React.

### Expected Behaviour

Rows should be smoothly scrollable, regardless of their height, and shouldn't kick off an infinite rerendering glitch.

### Steps to Reproduce

 https://codesandbox.io/s/dazzling-cloud-t1upyt?file=/src/App.js

Try to scroll past "Super long details". The virtual table keeps jerking the row back to the top of the screen

### Environment

- devextreme-reactive: 3.0.5
- react: 17.0.2
- browser: Brave or Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 5.10.2

**Comment by Krijovnick** [comment]
@CamJohnson26  We have already registered and fixed the same [issue](https://supportcenter.devexpress.com/ticket/details/t1108194/reactive-grid-is-flickering-with-detail-row-and-virtual-table). The fix will be available in the next release.

**Comment by CamJohnson26** [comment]
Thanks @Krijovnick
