### ISSUE TITLE
What's the proper way to add an event handler for double clicking on a row

### ISSUE THREAD

**Issue by xwk** [DevExpress/devextreme-reactive#359]
I'm quite new to this wonderful library. I had a use case where I want to allow user to double click on a row to pop up some dialog populated with data associated with that row. I was wondering what's the proper way to implement that.

**Comment by SergeyAlexeev** [comment]
Hi,

You can implement the described functionality by using the `tableRowTemplate` property of the [TableView](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-view/) plugin.

The template can look like this:

```js
<TableView
  tableRowTemplate={({ children, row }) => (
    <tr
      style={{ cursor: 'pointer' }}
      onDoubleClick={(e) => {
        // show popup...
      }}
    >
    {children}
    </tr>
  )}
/>
```
See this [demo](https://stackblitz.com/edit/react-vbfyeu?file=index.js) as well.

**Comment by xwk** [comment]
@SergeyAlexeev Thanks for your nice solution and demo!
