### ISSUE TITLE
Drag recurring appointment

### ISSUE THREAD

**Issue by micha-nerdlichter** [DevExpress/devextreme-reactive#3594]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

I am moving the second occurance of a recurring appointment to a different time by drag n drop. I answer the "Edit recurring appointment" question with "all appointments" to shift them all in time. 
![image](https://user-images.githubusercontent.com/8459594/201915434-34531eb2-839e-420b-b004-e44b56c0caa9.png)

Now they all get shifted in date too:
![image](https://user-images.githubusercontent.com/8459594/201915618-a3654675-bbf8-4fe3-918b-baea1fd86b8a.png)

Although I understand this behaviour, it is not intuitive.  If I move the first occurence, everythign works as expected. But if I move the second occurence I dont' t expect the first occurance to shift to this date. Especially with recurring appointments with larger gaps and a wide date range it might be complicated to find the first occurence to move the appointments to a different time.

### Expected Behaviour

I would expect the appointments to shift in time, but not in date.
![image](https://user-images.githubusercontent.com/8459594/201912551-0b3c176e-fe5c-4689-9fec-64bcc9db9d8d.png)
![image](https://user-images.githubusercontent.com/8459594/201912627-d96c9e6b-f1b3-4016-bbe6-325f8de33a42.png)

### Steps to Reproduce

Go to [this example](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointments/#recurring-appointments)
Drag an appontment on tuesday to a different time. 

### Environment

- devextreme-reactive: 3.0.5
- react: 18.2.0
- browser: chrome 107.0
- material-ui: 5.9.2

**Comment by Krijovnick** [comment]
Hi, @micha-nerdlichter 

It is not a bug. When a user changes appointments, the `EditingState` plugin fires the `onCommitChanges` event that changes the editing state. You need to modify the `commitChanges` method in the example to achieve the behavior you require.

**Comment by micha-nerdlichter** [comment]
Hi @Krijovnick,
thank you for your response. I don't think I can do this in the `commitChanges` method, as I need the dragged appointment in order to calculate the correct date. In the function I only have the first occurance and the new (miscalculated) date.

I still think this is a bug. Please note that with "this and following appointments" everything works as I would expect. But if I select "all appointments" I don't suspect the head to move to the new time, but the exact appointment I dragged.

If anyone has the same problem: I fixed this by adding  the following lines to `packages/dx-scheduler-core/src/plugins/editing-state/helpers.ts`
````
if (parentData && !moment.utc(appointmentData.startDate).isSame(moment.utc(parentData.startDate))) {
    const dateDiff = moment.utc(changes.startDate).diff(moment.utc(appointmentData.startDate));
    const optimizedStartDate = moment(parentData.startDate).add(dateDiff, 'ms');
    const optimizedEndDate = moment(parentData.endDate).add(dateDiff, 'ms');

    return  {
      changed: {
        [appointmentData.id!]: {
          ...changes,
          startDate: optimizedStartDate.toDate(),
          endDate: optimizedEndDate.toDate(),
        }
      }
    };
  }
````
I don't think a PR makes any sense if this is not considered a bug.
