### ISSUE TITLE
Invalid transform with v4.0.0

### ISSUE THREAD

**Issue by DavidHenri008** [DevExpress/devextreme-reactive#3602]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

There is an error when building my app that says it cannot resolve module "@mui/material/node/SOMETHING".

> Module not found: Error: Can't resolve '@mui/material/node/Popover/index.js' in 'C:\Git\web-envysion\node_modules\@devexpress\dx-react-grid-material-ui\dist'

This error seems to be due to the newly added babel transform 
```
 ["transform-rename-import", {
      "original": "^@mui\\/material\\/(.*)$",
      "replacement": "@mui/material/node/$1/index.js"
    }]
```
The @mui/material package has no folder named node...

### Expected Behaviour

In version v3.0.6 everything was working fine.

### Environment

- devextreme-reactive: 4.0.0
- react: 18.2.0
- browser: Chrome v107
- bootstrap: none
- react-bootstrap: none
- material-ui: 5.10.15

**Comment by krisgerhard** [comment]
Also
`var VisibilityOff = _interopDefault(require('@mui/icons-material/VisibilityOff'));`

@mui/icons-material imports are not transformed at all.

**Comment by Nathan7934** [comment]
I'm also having this issue. Makes the component unusable for me, which is a shame since it's exactly what I need
