### ISSUE TITLE
Warning: `value` prop on `textarea` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.     at textarea

### ISSUE THREAD

**Issue by jhunexjun** [DevExpress/devextreme-reactive#3627]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

Upon showing the dialog on edit, the error comes out.

### Expected Behaviour

There should be no error.

### Steps to Reproduce

1. Open the DevTool.
2. You must have at least 1 schedule.
3. Double-click or try to clicking then click the pen to edit. A dialog will show.
4. Check the DevTool Console tab. The error will show you.
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6801369/213465480-a556bff0-6d2d-42d0-a46f-af99cff894e8.png">

### Environment

```
"dependencies": {
    "@devexpress/dx-react-core": "^4.0.2",
    "@devexpress/dx-react-scheduler": "^4.0.2",
    "@devexpress/dx-react-scheduler-material-ui": "^4.0.2",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.0.4",
    "@mui/lab": "^5.0.0-alpha.51",
    "@mui/material": "^5.11.5",
    "@mui/styled-engine-sc": "^5.11.0",
    "@mui/x-date-pickers": "^5.0.0-alpha.7",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "bootstrap": "^4.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.4.2",
    "react-scripts": "5.0.1",
    "reactstrap": "^9.1.5",
    "styled-components": "^5.3.6",
    "url-encode-decode": "^1.0.0",
    "web-vitals": "^2.1.4"
  },
```

**Comment by artem-kurchenko** [comment]
Hi @jhunexjun 

I'm closing this issue, as it's not clear how to reproduce it on this information. 
If you have an active DevExtreme license, you can contact us in our [Support Center](https://www.devexpress.com/ask) for further research . Otherwise, post your question on StackOverflow.
