### ISSUE TITLE
Warning: Failed prop type: The prop `groups` is marked as required in `HorizontalLayout`, but its value is `undefined`.     at HorizontalLayout

### ISSUE THREAD

**Issue by jhunexjun** [DevExpress/devextreme-reactive#3630]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

The error below shows and nothing in the UI.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6801369/214500603-2b8096d9-20a8-4d8c-9023-53b2865244d5.png">

### Expected Behaviour

No errors and Scheduler must show with grouping.

### Steps to Reproduce

let initSchedulerData = [];

let initResources = [
	{
		fieldName: 'workers',
		title: 'Workers',
		allowMultiple: true,
		instances: [],
	},
	{
		fieldName: 'invoiceNo',
		title: 'Invoice #',
		allowMultiple: false,
		instances: [],
	},
];

let initGroupings = [{
	resourceName: 'invoiceNo',
}, {
	resourceName: 'workers',
}];

let [currentDate] = useState(new Date());
let [schedulerData, setScheduleData] = useState(initSchedulerData);
let [resources, setResources] = useState(initResources);
let [groupings, setGroupings] = useState(initGroupings);

const groupOrientation = viewName => viewName.split(' ')[0];

<Scheduler data={schedulerData} height={700} >
	<ViewState defaultCurrentDate={currentDate} defaultCurrentViewName="Week" />
	<EditingState onCommitChanges={commitChanges} />
	<GroupingState grouping={groupings} />
	<IntegratedGrouping />
	<IntegratedEditing />
	<MonthView />
	<DayView startDayHour={7} endDayHour={21} intervalCount={2} />
	<WeekView startDayHour={7} endDayHour={21}  />
	<Resources data={resources} mainResourceName="workers" />
	<Toolbar />
	<ViewSwitcher />
	<DateNavigator />
	<TodayButton />
	<Appointments />
	<AllDayPanel />
	<ConfirmationDialog />
	<AppointmentTooltip showOpenButton showDeleteButton />
	<AppointmentForm />
	<GroupingPanel />
	<DragDropProvider />
</Scheduler>

### Environment

"dependencies": {
  "@devexpress/dx-react-core": "^4.0.2",
  "@devexpress/dx-react-scheduler": "^4.0.2",
  "@devexpress/dx-react-scheduler-material-ui": "^4.0.2",
  "@emotion/react": "^11.10.5",
  "@emotion/styled": "^11.10.5",
  "@mui/icons-material": "^5.0.4",
  "@mui/lab": "^5.0.0-alpha.51",
  "@mui/material": "^5.11.5",
  "@mui/styled-engine-sc": "^5.11.0",
  "@mui/x-date-pickers": "^5.0.0-alpha.7",
  "bootstrap": "^4.6.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-router-dom": "^6.4.2",
  "react-scripts": "5.0.1",
},

**Comment by artem-kurchenko** [comment]
Hi @jhunexjun

I'm closing this issue, as it's not clear how to reproduce it on this information.
If you have an active DevExtreme license, you can contact us in our [Support Center](https://www.devexpress.com/ask) for further research . Otherwise, post your question on StackOverflow.
