### ISSUE TITLE
Warning: Failed prop type: The prop `currentView.displayName` is marked as required in `Memo`, but its value is `undefined`.

### ISSUE THREAD

**Issue by jhunexjun** [DevExpress/devextreme-reactive#3631]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

Scheduler do not shows and console is showing an error.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/6801369/214507773-de7172b3-7789-4f7b-bd08-be6d64cd173c.png">

### Expected Behaviour

No error and Scheduler must show with groupings.

### Steps to Reproduce

let initSchedulerData = [];

let initResources = [
	{
		fieldName: 'workers',
		title: 'Workers',
		allowMultiple: true,
		instances: [],
	},
	{
		fieldName: 'invoiceNo',
		title: 'Invoice #',
		allowMultiple: false,
		instances: [],
	},
];

let initGroupings = [{
	resourceName: 'invoiceNo',
}, {
	resourceName: 'workers',
}];

let [currentDate] = useState(new Date());
let [schedulerData, setScheduleData] = useState(initSchedulerData);
let [resources, setResources] = useState(initResources);
let [groupings, setGroupings] = useState(initGroupings);

const groupOrientation = viewName => viewName.split(' ')[0];

<Scheduler data={schedulerData} height={700} >
	<ViewState defaultCurrentDate={currentDate} defaultCurrentViewName="Horizontal" />
	<EditingState onCommitChanges={commitChanges} />
	<GroupingState grouping={groupings} groupOrientation={groupOrientation} />
	<IntegratedGrouping />
	<IntegratedEditing />
	<WeekView startDayHour={7} endDayHour={21} displayName="name" />
	<Resources data={resources} mainResourceName="workers" />
	<Toolbar />
	<ViewSwitcher displayName="name" />
	<DateNavigator />
	<TodayButton />
	<Appointments />
	<AllDayPanel />
	<ConfirmationDialog />
	<AppointmentTooltip showOpenButton showDeleteButton />
	<AppointmentForm />
	<GroupingPanel />
	<DragDropProvider />
</Scheduler>

### Environment

"dependencies": {
    "@devexpress/dx-react-core": "^4.0.2",
    "@devexpress/dx-react-scheduler": "^4.0.2",
    "@devexpress/dx-react-scheduler-material-ui": "^4.0.2",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.0.4",
    "@mui/lab": "^5.0.0-alpha.51",
    "@mui/material": "^5.11.5",
    "@mui/styled-engine-sc": "^5.11.0",
    "@mui/x-date-pickers": "^5.0.0-alpha.7",
    "bootstrap": "^4.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.4.2",
    "styled-components": "^5.3.6",
  },

**Comment by artem-kurchenko** [comment]
Hi @jhunexjun 

I'm closing this issue, as it's not clear how to reproduce it on this information. 
If you have an active DevExtreme license, you can contact us in our [Support Center](https://www.devexpress.com/ask) for further research . Otherwise, post your question on StackOverflow.
