### ISSUE TITLE
Scheduler - some appointments are hidden by overlapping elements

### ISSUE THREAD

**Issue by adrien-may** [DevExpress/devextreme-reactive#3634]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

An item is hidden by the others when multiple overlaps happens.

### Expected Behaviour

There is one slot (19h-22h) which is hidden by the others

I'm expecting something similar to the following in terms of rendering

![Capture d’écran 2023-01-26 à 17 41 38](https://user-images.githubusercontent.com/64930588/214895454-577d3a97-51de-4921-b80d-92493d7db932.png)

### Steps to Reproduce

To reproduce the issue, you can create the following slots:
(sorry I did not manage to find a simpler example but it should not be that complicated)

|Start|End|
|----|----|
|2023-01-27 12:00:00.000 +0100 | 	2023-01-27 14:00:00.000 +0100|
|2023-01-27 13:00:00.000 +0100	 | 2023-01-27 16:00:00.000 +0100|
|2023-01-27 16:00:00.000 +0100 | 	2023-01-27 17:01:00.000 +0100|
|2023-01-27 17:00:00.000 +0100 | 	2023-01-27 20:00:00.000 +0100|
|2023-01-27 17:00:00.000 +0100 | 	2023-01-27 20:00:00.000 +0100|
|2023-01-27 20:00:00.000 +0100 | 	2023-01-27 22:30:00.000 +0100|
|2023-01-27 19:30:00.000 +0100	 | 2023-01-27 22:00:00.000 +0100|
|2023-01-27 19:00:00.000 +0100 | 	2023-01-27 22:00:00.000 +0100|
|2023-01-27 15:00:00.000 +0100 | 	2023-01-27 17:00:00.000 +0100|

You'll get something like:

![Capture d’écran 2023-01-26 à 17 40 43](https://user-images.githubusercontent.com/64930588/214895244-85d8c9f5-c2d1-4f54-baf2-c5f0ae2333d7.png)

Here, at the end, the item 19-22h is display BEHIND the others and thus, users don't see it.

### Environment

- devextreme-reactive: 4.0.2
- react: 17

**Comment by adrien-may** [comment]
I'm sorry to insist but is someone going to have a look at this ? I fear this king of bug could be a nogo for most people.

**Comment by adrien-may** [comment]
Is this even maintain ?

**Comment by artem-kurchenko** [comment]
Hi @adrien-may 

Thank you for the screenshots.  Unfortunately, the default overlapping algorithm cannot be modified. 
As an alternative solution, you can set the `placeAppointmentsNextToEachOther` property to "true" to disable the overlapping of appointments that occupy the same time
```jsx
<Appointments placeAppointmentsNextToEachOther={true} />
```

P.S. We maintain this repository as a community-driven effort. Please use our [Support Center](https://supportcenter.devexpress.com/ticket/create) if you wish to get responses in timely manner
