### ISSUE TITLE
allowSorting causes console errors in jest results

### ISSUE THREAD

**Issue by alexedev** [DevExpress/devextreme-reactive#364]
When I add `allowSorting` to `TableHeaderRow` then I get this error in test results:

```
console.error node_modules/warning/warning.js:51
    Warning: Material-UI: you have provided a custom Component to the `component` property of `ButtonBase`.
    In order to make the keyboard focus logic work, we need a reference on the root element.
    Please provide a class component instead of a functional component.
    You need to fix the: span component.
```
it appears as many times as many columns I have.

I think there is some bug with using `TableSortLabel` which is rendered in `TableHeaderRow` as:

<img width="1000" alt="screen shot 2017-09-26 at 18 29 55" src="https://user-images.githubusercontent.com/1526837/30871958-ced1bbf2-a2e8-11e7-887d-5b5f1a7937cb.png">

There are no errors if I normally import `TableSortLabel` and render it standalone (when `allowSorting` is not added in `TableHeaderRow`)

**Comment by SergeyAlexeev** [comment]
Hi,
 
Thank you for reporting the issue! Would you please clarify what Material UI version you are using?

**Comment by alexedev** [comment]
1.0.0-beta.9

**Comment by SergeyAlexeev** [comment]
I appreciate your clarification, but I can't reproduce the issue on my side. Could you provide us with a sample that reproduces the described behavior?

**Comment by alexedev** [comment]
Well, it happens with standard material-ui table too...
I will upgrade material-ui and see if it helps, otherwise will create and issue there.

This one can be closed.
