### ISSUE TITLE
rrule import (scheduler-core) error seems still to exist

### ISSUE THREAD

**Issue by NoerNova** [DevExpress/devextreme-reactive#3644]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

![Screenshot 2566-03-25 at 01 03 20](https://user-images.githubusercontent.com/9565672/227605139-89f44fcf-de62-4edd-b458-52086fd17ea3.png)

### Expected Behaviour

DX components should correctly render.

### Steps to Reproduce

To Reproduce
- [CodeSandbox Link](https://codesandbox.io/p/sandbox/xenodochial-gates-t2nob3?welcome=true&file=%2FREADME.md)

### Environment

- next: ^13.2.4
- react: ^18.2.0
- dx-react-core: ^4.0.3
- dx-react-scheduler: ^4.0.3
- dx-react-scheduler-material-ui: ^4.0.3
- @mui/icons-material: ^5.11.11
- @mui/lab: ^5.0.0-alpha.124
- @mui/material: ^5.11.14
- @mui/x-date-pickers: ^6.0.3

**Comment by omgaunicorn** [comment]
Facing the same issue; in my app I want to update @mui/x-date-pickers to v6, but the Scheduler implodes with the rrule error when trying to do this.

Up until now this library has been great but this has been a blocker for a couple months now and it's making us reconsider changing the DevExtreme Reactive components for something else 😕

Environment:
- next: ^12.3.0
- react: ^18.2.0
- dx-react-core: ^4.0.4
- dx-react-scheduler: ^4.0.4
- dx-react-scheduler-material-ui: ^4.0.4
- @mui/icons-material: ^5.11.16
- @mui/lab: ^5.0.0-alpha.126
- @mui/material: ^5.12.0
- @mui/x-date-pickers: ^6.6.0

**Comment by artem-kurchenko** [comment]
Hi @omgaunicorn ,

You need to add our packages to `transpilePackages` in `next.config` proper operation.
```
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  transpilePackages: [
    '@mui/icons-material',
    '@mui/x-date-pickers',
    'rrule',
    '@devexpress/dx-react-core',
    '@devexpress/dx-scheduler-core',
    '@devexpress/dx-react-scheduler-material-ui',
    '@devexpress/dx-react-scheduler',
    '@devexpress/dx-react-grid-material-ui'
  ],
};
```
module.exports = nextConfig;`
See the following ticket where we created an example: [t1159998](https://supportcenter.devexpress.com/ticket/details/t1159998/typeerror-cannot-destructure-property-adaptermoment-of-mui-x-date-pickers-adaptermoment)

**Comment by Fensterbank** [comment]
We had the same issue after upgrading from 3.x to the latest version.
I can confirm adding these lines to our next.config.js fixed the issue for us.
Thanks!

**Comment by EmielH** [comment]
We have the same issue but we're not using Next. We're using Vite and the error pops up when running unit tests using Vitest. Is there anything similar we can do in the Vite configuration?

**Comment by EmielH** [comment]
Hi @artem-kurchenko 
Thanks a lot for your reply! I have managed to create a reproduction scenario given your application template. If you run `npm run test` in this example, the error occurs.

The error started occurring after adding React Testing Library dependencies.

[test-react-vite.zip](https://github.com/DevExpress/devextreme-reactive/files/11726057/test-react-vite.zip)

**Comment by artem-kurchenko** [comment]
The following configuration in `vitest.config.ts` should solve the issue in testing:

```ts
import react from "@vitejs/plugin-react";
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [
    react()
  ],
  test: {
    environment: 'jsdom',
    deps: {
      inline: [
        "rrule", "@devexpress/dx-scheduler-core", "@devexpress/dx-react-scheduler", "@devexpress/dx-react-scheduler-material-ui", 
      ],
      registerNodeLoader: true,
      fallbackCJS: true,
      interopDefault: true
    },
  }
});
```
