### ISSUE TITLE
Recurring event not handling daylight saving time

### ISSUE THREAD

**Issue by jakubjanousek** [DevExpress/devextreme-reactive#3646]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

Let's say we have a recurring event that should happen daily and was created in Prague timezone on 21st March (GMT+1). on 26th March Prague is changed to GMT+2 (daylight saving time). Therefore when viewed from a timezone that is not observing daylight saving time (ie. Mumbai), the calendar should look as following (notice the last event is moved one hour prior)

<img width="791" alt="Screenshot 2023-03-22 at 8 18 26" src="https://user-images.githubusercontent.com/4403131/228443986-545300bc-22ba-48c2-83c3-c16d62ed0b24.png">

Unfortunately with @devexpress/dx-react-scheduler, this is not observed and the event is parsed every day at the same time as the first occurrence, see screenshot

<img width="820" alt="Screenshot 2023-03-22 at 8 23 39" src="https://user-images.githubusercontent.com/4403131/228444401-8659956a-f270-4e00-be9d-b40d07cba62e.png">

What can be done to fix this? This leads to various weird overlaps with non-repeated events and lots of confusion

### Expected Behaviour

Recurring schedule adapts to the user's timezone even with recurring events

### Environment

@devexpress/dx-react-scheduler: 4.0.3

**Comment by jakubjanousek** [comment]
Any idea in here? This is a real issue we have on production and it would help us tremendously if we know what is going on. Thanks

**Comment by artem-kurchenko** [comment]
Hi @jakubjanousek 

Reactive Scheduler now displays dates as is and doesn't track changes within time zones. There is no straightforward solution to display dates depending on the browser's settings unless you pre-process data that should be passed to Scheduler.

We have a different product for React that supports this feature (different time zones) out of the box: [dxScheduler](https://js.devexpress.com/Documentation/Guide/UI_Components/Scheduler/Getting_Started_with_Scheduler/).

Feel free to consider it as an alternative. If you have any questions about it please contact us at https://supportcenter.devexpress.com/ticket/create
