### ISSUE TITLE
Empty Table header

### ISSUE THREAD

**Issue by Dert1129** [DevExpress/devextreme-reactive#3654]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

When inspecting the column headers for my react table, there is an empty table header at the end of my table headers.

### Expected Behaviour

There is no empty table header at the end of the table header row.

### Environment

- devextreme-reactive: none
- react: 17.0.2
- browser: firefox, chrome, edge
- bootstrap: 5.2.3
- reactstrap: 8.9.0
- material-ui: none

**Comment by Madobyte** [comment]
Hello @Dert1129,

I believe you are referring to stub cells. Reactive Grid uses these cells for different rendering conditions. A simple example is when the total width of columns does not exceed the total width of the grid: [CodeSandbox](https://codesandbox.io/s/practical-hopper-0lucyf?file=/demo.js). In this case, stub cells occupy the remaining available width.

Try inspecting the grid element in the example, and you'll see that stub cells fill in the remaining width.

Additionally, Reactive Grid may render stub cells for proper indentation when data is grouped. You can see it in the following demo: [https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/).
