### ISSUE TITLE
Unexpected jump to top when scrolling down after Edge restart

### ISSUE THREAD

**Issue by nikolaykhodov** [DevExpress/devextreme-reactive#3658]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Grid

### Current Behaviour

If you have a long table:

- with virtual scrolling enabled
- text inputs in

and select into a cell:
- so the input is selected too,
 
the grid unexpectedly jumps to the top as you scroll down (the text input gets unmounted). This is taking place after Edge gets restarted. So it doesn't happen after the initial load, but it is the case if the browser is restarted

### Expected Behaviour

The grid keeps its scrolling position as you scroll down when there is a selected text input

### Steps to Reproduce

1. Open https://kdpqwv.csb.app/ or https://codesandbox.io/s/scroll-to-top-issue-kdpqwv
2. Scroll to the middle of the grid
3. Choose a cell
4. Scroll down until it unmounts
5. Restart the browser
6. Try to repro again
7. It jumps to the top (random position)

### Environment

- devextreme-reactive: 4.0.3
- react: 18.2.0
- browser: Windows 11 / Edge 114.0.1823.55
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by artem-kurchenko** [comment]
Hi 

I created a report to research this issue:

https://supportcenter.devexpress.com/ticket/details/t1176840/reactive-grid-the-scrollbar-jumps-on-the-top-on-scrolling-if-an-input-element-was
