### ISSUE TITLE
Add the capability to use the default template's properties like styles, classes, etc.

### ISSUE THREAD

**Issue by SergeyAlexeev** [DevExpress/devextreme-reactive#368]
Currently, templates like `tableCellTemplate`, `tableRowTemplate` etc. don't get access to default properties (classes, styles etc.) In some cases, it's useful to extend these properties without overriding them. For example, add some additional CSS class and keep default ones.

**Comment by MaximKudriavtsev** [comment]
This functionality is available starting with [v1.0.0-beta.2](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-beta.2).

**Comment by satiush** [comment]
Can I use edit cell with TableCell of TableCell from '@material-ui/core/TableCell';
