### ISSUE TITLE
Responsive or Possible to give columnWidth in Percentage

### ISSUE THREAD

**Issue by bhavin-00** [DevExpress/devextreme-reactive#372]
Can  I  give columnWidth in Percentage or Any Responsiveness possible in this ?

**Comment by kvet** [comment]
Hi,

Thank you for reaching out to us. We currently support column width definition only in pixels. But it is possible to override a cell's CSS styles. Here is an example: https://stackblitz.com/edit/react-af6fro?file=index.js

Can you describe what kind of functionality you mean by responsiveness? Do you mean hiding columns on small screens or adjusting column width depending on screen size? I'm looking forward to your response.

**Comment by bhavin-00** [comment]
I mean adjusting column width depending on screen size. Does it possible ?

**Comment by bhavin-00** [comment]
Thanks buddy  [(https://stackblitz.com/edit/react-af6fro?file=index.js)]  --- it helps me, Actually my columns are many numbers of in tabel so it looks wiered.. now quite looks cool :-)
