### ISSUE TITLE
Does it possible to give stateSelection on only particular row

### ISSUE THREAD

**Issue by bhavin-00** [DevExpress/devextreme-reactive#373]
Does it possible to give stateSelection on only particular row  ?

**Comment by bloolizard** [comment]
Looking for this feature as well.

**Comment by kvet** [comment]
Hi,
 
@bhavin-00, @bloolizard have you tried to use the SelectionState plugin in the controlled mode?
 
The following example shows how to get recently selected and deselected rows: https://stackblitz.com/edit/react-v5geoa?file=index.js
 
And, the following example shows how to select a row: https://stackblitz.com/edit/react-cd6qtk?file=index.js

**Comment by bloolizard** [comment]
That's how I have it working in my app right now, but sometimes you just want to have a context to the row that was clicked.  For instance maybe I want to trigger an action to only the row that was clicked and not the other selected rows.  Would be nicer if we can just have this row.

**Comment by bhavin-00** [comment]
Yes, I used that but, I just want the selection control on particular rows.. not all rows

**Comment by kvet** [comment]
@bhavin-00, we don't have such a built-in functionality. Here is a simple example demonstrating a workaround: https://stackblitz.com/edit/react-aji931?file=index.js
 
@bloolizard, we don't currently have plans to add such a functionality. You can create a separate issue describing your suggestion. It will help us to track similar requests.

**Comment by bhavin-00** [comment]
@kvet  It's superb thanks buddy
