### ISSUE TITLE
Custom sorting function in LocalSorting

### ISSUE THREAD

**Issue by phiilu** [DevExpress/devextreme-reactive#380]
Hello!

First of all I want to thank you for the great DataGrid!

Now to my question:
Is it possibly to add a custom sorting function to `LocalSorting `like in `LocalFiltering `the `filterFn`? 

For example I have a column with dates and I want to sort them. Currently it sorts it like strings, because I format the dates with `moment` in `getCellData`. Or am I using `getCellData` completly wrong and the sort order would work as expected, if I would just return a date instance and format the column in the `TableView` component?

Thanks

**Comment by kvet** [comment]
Hi,
 
Thank you for reaching out to us.

At this time there is no capability to customize the LocalSorting plugin. But it will be released soon. Here is the link to the merged PR: https://github.com/DevExpress/devextreme-reactive/pull/371
 
Also, we assume that the `getCellData` function is used to access cell values, not for formatting. We will release a new feature that allows formating cell values soon. Here is the link to the merged PR: https://github.com/DevExpress/devextreme-reactive/pull/336

**Comment by phiilu** [comment]
Thank you!

Alright I now use the `getCellData` function only to return the values and the sort seams to work just fine.

Looking forward to the new releases. Keep up the good work!
