### ISSUE TITLE
Ant Design theme

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#387]
Ant Design is one of the most mature & widely used React component toolkits, frequently used by Alibaba & Baidu who also pay for some of the development work. It would be very helpful if you could offer theming support.

https://ant.design/docs/react/introduce

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for the suggestion! We'll keep it in mind for future releases.

**Comment by DanHarman** [comment]
@SergeyAlexeev I'm not really clear why you have hard dependencies on 3rd party libraries, is it just for css? If so it would be great if you could just ship some simple themes that don't require pulling in whole UI frameworks customers may not be using, and which may clash with global styles etc. Forcing clients to take a dependency on material-ui or bootstrap seems fairly undesirable?

**Comment by SergeyAlexeev** [comment]
Currently, our React Grid is shipped with UI templates for two of the most popular component suites for React applications - React Bootstrap and Material UI. A data grid usually requires other components such as text fields, menus, date boxes etc. It takes a lot of resources to implement them from scratch. We decided to concentrate on Grid features instead and use these existing "small" components. 
But, you are not restricted to use only Bootstrap or Material UI. You can support any other component/css libraries, like Ant Design. To achieve it, you need to implement templates based on the component suite you prefer.
As a starting point, look at our existing packages [dx-react-grid-bootstrap3](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-bootstrap3) and [dx-react-grid-material-ui](https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-material-ui).
There is basic information about how to get started. We are also going to provide some docs on this matter soon. Hope it makes sense.

**Comment by DanHarman** [comment]
@SergeyAlexeev Well react-bootstrap only has 11k starts on github vs antdesign at 17k if you need convincing. It also has more controls than the others, and they are more compact so better suited to SPA apps  (in my opinion) :)

Realistically I don't have time to try and create a theme myself :(

**Comment by SergeyAlexeev** [comment]
@DanHarman I see your point, anyway thank you for the positive feedback!

**Comment by abenhamdine** [comment]
Just want to +1 : ant-design has now more than 20k stars and gains more traction every day.

**Comment by DanHarman** [comment]
28k stars now!

**Comment by gwmaster** [comment]
its will be great to support ANT design

**Comment by phnessu4** [comment]
@SergeyAlexeev  Is there any develop plan or roadmap?

**Comment by SergeyAlexeev** [comment]
We are currently working on our roadmap. It will be available [here](https://js.devexpress.com/Roadmap/).

**Comment by phnessu4** [comment]
Wait for the Layout Templates features. 
@SergeyAlexeev thanks.

**Comment by churkin** [comment]
Hi @MatthieuCoelho,

We don't have plans to implement the Ant Design theme in the near future. We have a [guide](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/custom-theme/) about creating custom theme package with examples, so you can try to implement yourself and share results with the community.

**Comment by churkin** [comment]
Hi everyone,
After further discussion, we decided to exclude implementation of the new UI themes from our strategy plans. Thus, I will close this issue. But you still can implement a custom theme yourself. Please use [this](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/custom-theme/) guide with examples.
