### ISSUE TITLE
Feature Request: Support React 16

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#388]
Please support React 16. Currently trying to create the most basic grid I get this error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Comment by kvet** [comment]
Hi,
 
It is not quite clear how to reproduce the issue. We have tested basic Grid scenarios with react@16 and it works well.

**Comment by DanHarman** [comment]
Hi - thanks for confirming it works with react@16. I'll take another look.
