### ISSUE TITLE
How may I make binding between 2 fields in the same row ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [DevExpress/devextreme-reactive#391]
Hello, folks,

Just one simple question, I wonder how to bind the values of 2 fields to figure up the third in the same row ? 
For example, I have `Unit Price`, `Quantity`, and `Amount` in the row, I wish to count the `Amount` automatically while typing something in `Unit Price` and `Quantity`. 

Thx for your helps ;)

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you use the `onChangedRowsChange` property of the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/) plugin. It takes an object that contains changed but not yet committed rows. You can implement your calculations within this function: 

```js
<Grid>
  <EditingState     
    changedRows={changedRows}
    onChangedRowsChange={(changedRows) => {
      // calculate Amount here
      this.setState({ changedRows });
    }}
  />
</Grid>
```

I've created a [small example](https://stackblitz.com/edit/react-pasadt?file=index.js) that demonstrates how it can be implemented.

**Comment by SergeyAlexeev** [comment]
Hi,
 
In your case, I suggest you use the `createRowChange` property of the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/) plugin. It allows you to calculate a row change manually:

```js
<Grid>
  <EditingState
    createRowChange={(row, columnName, value) => {
      const quantity = columnName === 'quantity' ? value : row.quantity;
      const unit_price = columnName === 'unit_price' ? value : row.unit_price;

      return {
        quantity,
        unit_price,
        amount: quantity * unit_price
      };
    }}
  />
</Grid>
```

I've created a [small example](https://stackblitz.com/edit/react-jy9yhe?file=index.js) that demonstrates how it can be implemented.

**Comment by be-next-hotdog** [comment]
Awesome !! Thx ;)
