### ISSUE TITLE
TableColumnResizing Issue with Sort Indicators

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#393]
Hi,

When using the TableColumnResizing addin along with SortingState & Localsorting, if the default width for a column is narrower than the column title text, then the sort direction indicator will not display, even when the column has been resized to be able to accomodate.

Thanks,

Dan

**Comment by gsobolev** [comment]
Hi Dan!

It looks like the issue you are describing is related to Chrome. I was not able to reproduce it in other browsers. Anyway, I investigated the issue a bit more and ended up with [the following sample](https://codepen.io/anon/pen/yzEqJp) which reproduces the same behavior.
