### ISSUE TITLE
How to disable multi editing rows ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [DevExpress/devextreme-reactive#399]
Hello, everyone,

By default, we could edit multiple rows in the same time, but how could I allow only one editing row and make users finish the current edit and start another edit.

Thx a lot :)

**Comment by dxbykov** [comment]
Hi,

You can use the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/) plugin in the [controlled state mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-state) and disable editing if at least one row is being edited. Here is a [sample](https://stackblitz.com/edit/react-bvfglk?file=index.js).

**Comment by be-next-hotdog** [comment]
Nice, thx !
