### ISSUE TITLE
Feature Request: VirtualTableView for Material-UI

### ISSUE THREAD

**Issue by Deadly0** [DevExpress/devextreme-reactive#401]
Hi, is it posslible to do scrollable table body in material-ui theme?

**Comment by SergeyAlexeev** [comment]
Hi,

Do you mean Virtual Scrolling?

**Comment by Deadly0** [comment]
No, i mean something like this http://jsfiddle.net/hashem/CrSpu/555/ where the table header is fixed and i can scroll only table body.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification!

It seems that Virtual Scrolling supports a similar functionality. Take a look at this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/).

As for Virtual Scrolling in the Material UI, it isn't implemented yet. We'll update this thread once we have any news.
