### ISSUE TITLE
ETA for VirtualTableView for material-ui ?

### ISSUE THREAD

**Issue by frankbolviken** [DevExpress/devextreme-reactive#402]
As in subject. This is a critical feature for us.
Also, using normal TableView I see now possibility of setting the height of the table?

**Comment by kvet** [comment]
Hi,
 
We plan to implement VirtualTableView for Material-UI in the nearest future. You can track our progress in the following issue: https://github.com/DevExpress/devextreme-reactive/issues/401

**Comment by albinekb** [comment]
Hi, i saw that [this](https://github.com/DevExpress/devextreme-reactive/commit/b28e365a37e000cb7e8d999d39f3e6256a15d056) was merged, is it released yet? I can't seem to be able to import the `VirtualTableView` component.

Thanks 👍

**Comment by kvet** [comment]
Hi,

It was released in [1.0.0-beta.1](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-beta.1).
