### ISSUE TITLE
Columns overlap in .alpha11

### ISSUE THREAD

**Issue by grbspltt** [DevExpress/devextreme-reactive#403]
Content wider than column width no longer show "...".  The content overlaps the content in the next column over.  Behavior seen here in this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/redux-integration/).  Expand Mary Jackson row group:

![image](https://user-images.githubusercontent.com/1534765/31511237-f6d3ebe8-af3b-11e7-8576-84dee28ede6e.png)

**Comment by grbspltt** [comment]
Note that this was working fine in .alpha10

**Comment by grbspltt** [comment]
@SergeyAlexeev I see that this is closed however the bug still exists in the build on NPM.  How do I fix this in my project?

**Comment by SergeyAlexeev** [comment]
@grbspltt the fix will be available in the alpha12 release. As a workaround, you can now use a custom table cell template:

```js
const tableCellTemplate = ({ value }) => 
  (<TableCell style={{ overflow: 'hidden' }}>{value}</TableCell>);
```

See this [sample](https://stackblitz.com/edit/react-zdmvyp?file=index.js).
