### ISSUE TITLE
Question: Possible to specify the columns that you want table filtered?

### ISSUE THREAD

**Issue by bloolizard** [DevExpress/devextreme-reactive#404]
I am using the remote filtering capability.  But I only want the filter to be applied on column.  Is it possible to do this and turn the other filters off?

![image](https://user-images.githubusercontent.com/539201/31521863-0280765e-af60-11e7-96fa-fe060af865c7.png)

**Comment by SergeyAlexeev** [comment]
Hi,

For now, you can use the `filterCellTemplate` property of the [TableFilterRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/) plugin:

```js
import { TableCell } from 'material-ui';

<Grid
  /*...*/
>
<TableFilterRow
  filterCellTemplate={({ column }) => {
    if (column.name === 'name') {
      return (<TableCell>Do not filter</TableCell>);
    }
    // use default template
    return undefined;
  }}
/>
</Grid>
```

**Comment by kvet** [comment]
Hi,

We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by zztimy** [comment]
Returning 'undefined' did not work for me nor did using the filterCellTemplate (maybe there was a change in the latest version). This code did work (for beta3):
`import { TableCell } from 'material-ui';

<Grid
  /*...*/
>
<TableFilterRow
  cellComponent={(cellComponentObject) => {
    if (cellComponentObject.column.name === 'name') {
      return (<TableCell>Do not filter</TableCell>); // Here is would suggest returning an empty string if you want to hide the filtering completely
    }
    // use default template
    return <TableFilterRow.Cell {...cellComponentObject}/>;
  }}
/>
</Grid>`

**Comment by joergd** [comment]
When using it like this, the textfield loses focus after every keystroke. How would I prevent this from happening?

**Comment by kvet** [comment]
Hi @joergd,
 
Just extract the component into a constant for this purpose. This should help.

```jsx
import { TableCell } from 'material-ui';

const FilterCell = (props) => {
  if (props.column.name === 'name') {
    return <TableCell>Do not filter</TableCell>;
  }
  return <TableFilterRow.Cell {...props}/>;
}

<Grid
  /*...*/
>
  <TableFilterRow
    cellComponent={FilterCell}
  />
</Grid>
```

**Comment by joergd** [comment]
Ok great - that worked thank you!
