### ISSUE TITLE
Question: CSV Export Capability?

### ISSUE THREAD

**Issue by bloolizard** [DevExpress/devextreme-reactive#405]
Any recommendations for outputting table data to CSV?

**Comment by gsobolev** [comment]
Hi,

Our Grid does not have any builtin export capabilities. And there are no plans on implementing this in the nearest future. So the only way I can suggest you for now is to use some sort of third-party library or implement the export logic yourself. Please check [this example](http://jsfiddle.net/hybrid13i/JXrwM/) for more information.

Anyway, thank you for your question. We'll consider it in the future.

**Comment by gsobolev** [comment]
Please track the #537 issue for further updates on this suggestion.
