### ISSUE TITLE
Question: Grid Footer / Summary

### ISSUE THREAD

**Issue by ddmedeiros** [DevExpress/devextreme-reactive#413]
Is there a way to add sum footers to the grid ? If not is it something that could be added to a future release ?

**Comment by kvet** [comment]
Hi,
 
The grid can be extended by custom components. For example, you can place components in the Grid footer. Here is the demo: https://stackblitz.com/edit/react-ze1oxh?file=index.js

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by rmariuzzo** [comment]
Hey @kvet! I'm looking into how to add a last row as the summary. The demo you linked doesn't seem clear to me on how to add it.

**Comment by up209d** [comment]
I did the TOTAL row like this 

```
rows: [
        { id: '001', type: 'A', quantity: 21, isFixed: 0 },
        { id: '002', type: 'B', quantity: 35, isFixed: 0 },
        { id: '003', type: 'A', quantity: 28, isFixed: 0 },
        { id: 'TOTAL A', type: 'A', quantity: 49, isFixed: 1.0 },
        { id: 'TOTAL B', type: 'B', quantity: 35, isFixed: 1.1 },
      ],
      columns: [
        { name: 'id', title: 'Id' },
        { name: 'type', title: 'Type' },
        { name: 'quantity', title: 'Quantity' },
      ]
```

I didn't show the `isFixed` column, and also disabled the sorting function for `isFixed` column, so the sorting result always takes `isFixed` sorting as the first priority following with other column sorting state pushed in.

```
<SortingState
   defaultSorting={[{ columnName: 'isFixed', direction: 'asc' }]}
   columnExtensions={[{ columnName: 'isFixed', sortingEnabled: false }]}
/>
```
