### ISSUE TITLE
Row reordering support?

### ISSUE THREAD

**Issue by leebailey88** [DevExpress/devextreme-reactive#419]
I want to implement a prioritized task list grid.  I want users to be able to reorder tasks (rows in the grid) by drag and drop.  Is this supported, or if not, is it easy to add?

**Comment by gsobolev** [comment]
Hi!

Our Grid does not support row reordering yet. But we are considering this feature in the future. In the meantime, you can implement it on your side. If you need any assistance with this, feel free to contact us.

**Comment by leebailey88** [comment]
Thanks for the quick reply!  I will attempt to implement on my side

**Comment by Phocea** [comment]
Hello @gsobolev . Any ETA on  the implementation of this feature in the core code?
Do you have any snippets you could share to achieve this by any chance?

**Comment by gsobolev** [comment]
Hi @Phocea,

To be honest, we have no plans to implement this feature soon. We are currently working on a stable release of React Grid. We will update this ticket once we have any news.

**Comment by petruscurtu** [comment]
@gsobolev 

Any news on a possible release of this feature? It would be much appreciated.

**Comment by gsobolev** [comment]
@petruscurtu,
 
This feature is still of a low priority at the moment. We will update this thread once it is changed.

**Comment by paulkendall-rhapsody** [comment]
Any news on this feature? This is a must-have for our application and the lack of this feature is holding us back from making a purchasing decision on this component.

**Comment by SergeyAlexeev** [comment]
Hi,

Currently, this feature isn't in our [roadmap](https://js.devexpress.com/Roadmap/#React). That's why we didn't start it yet. Anyway, we'll take your request into account during future planning.

**Comment by paulkendall-rhapsody** [comment]
Thank you for your response. In our application the order of the rows specifies the structure of a data set and the ordering is important. Does the API currently allow for us to custom add this behaviour until it is built in to the product?

**Comment by SergeyAlexeev** [comment]
It's quite a complex task and I'm afraid it isn't possible for now.

**Comment by KhalilMohammad** [comment]
Guys you can use [react-dnd](https://github.com/react-dnd/react-dnd) or [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)

**Comment by petruscurtu** [comment]
@KhalilMohammad I ended up using [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc)

**Comment by felixaa** [comment]
@petruscurtu Could you provide a basic example on how you integrated react-sortable-hoc? Would be greatly appreciated!! ❤️

**Comment by felixaa** [comment]
I figured it out using [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc). But we would like the possibility to drag items from another container into the table. Seems like [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) supports dragging between lists. The problem is that I cannot pass a `Draggable`-wrapped `Table.Row` component to the `Table`'s `rowComponent`.
It worked with react-sortable-hoc because of the ability to attach the `Table.Row`-component to an HOC. Is there any way I could template the Table.Row with a plugin to make it work with `Draggable` and [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)? ❤️

This one works - [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc)
```
const TableRow = SortableElement(({ ...props }) => {
  return (
    <Table.Row {...props} />
  )
});
```
This does not work - [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)
```
const TableRow = ({ ...props }) => {
  return (
    <Draggable {...props} key={`draggable-${props.index}`} draggableId={props.row.id} index={props.sortIndex}>
      {(provided, snapshot) => {
        return (
          <div ref={provided.innerRef}
            {...provided.draggableProps}
            {...provided.dragHandleProps}>
            <Table.Row {...props} />
          </div>
        )
      }}
    </Draggable>
  )
};
```

**Comment by marton-levay** [comment]
@felixaa Can you help out how have you integrated react-sortable-hoc?
I wanted to use your example in my VirtualTable but it does nothing (actually no matter what code I feed to rowComponent in Virtual table, it does nothing)
`<VirtualTable
                height="auto"
                rowComponent={props => {
                    return <span>row</span>
                }}`

Also where have you used SortableContainer ?

**Comment by churkin** [comment]
Hi guys, sorry for waiting. I have created a small [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ofys6) where row reordering works correctly.

**Comment by churkin** [comment]
Hi all,
I discussed the feature with the team and we decided not to implement it in the next releases. 
Feel free to ask questions if the workaround described below does not satisfy your needs.
