### ISSUE TITLE
Why do header cells have margin?

### ISSUE THREAD

**Issue by leebailey88** [DevExpress/devextreme-reactive#432]
Since we have `boxSizing: border-box`, we shouldn't have to have margin on the table header cells in the grid.  We are able to easily specify the widths we want with `columnWidths` prop.  The problem I'm experiencing is that I have an ID column that I want to be very skinny at 60px.  However, I still want the sort arrow to show up.  With the default margin (which I believe comes from [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell.jsx#L58)), the column has the proper width, but the arrow is hidden.  You can move the drag handle back and forth to see that useless white space is covering the arrow.

I've attached two screenshots below, the first is default template with 60px width, the second I manually set margin-right to 0 in dev tools:
![screen shot 2017-10-21 at 7 06 47 am](https://user-images.githubusercontent.com/5678278/31852564-9e722948-b62e-11e7-85fa-430cdea5c999.png)
![screen shot 2017-10-21 at 7 07 18 am](https://user-images.githubusercontent.com/5678278/31852566-a3d2ee86-b62e-11e7-8b9a-8bab3ed41d28.png)

If you don't think removing the margin-right on the table header cells is a good idea, could you please give me some pointers on the easiest way to fix this issue on my end?  Thanks very much for you time and consideration.

**Comment by SergeyAlexeev** [comment]
Hi,
 
Actually, this margin makes sense only if the `allowGroupingByClick` property of the `TableHeaderRow` is `true`. Otherwise, the margin isn't required. I've created a corresponding [pull request](https://github.com/DevExpress/devextreme-reactive/pull/434), which fixes the issue.

**Comment by leebailey88** [comment]
thanks for the fix!  this library really has great maintainers
