### ISSUE TITLE
Scroll to row feature?

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#436]
Hi,

When a user causes a row to be added to the grid through a dialogue etc, is there a way I can scroll the grid to show the new row?

Thanks,

Dan

**Comment by kvet** [comment]
Hi,
 
I am afraid that we don't currently have any workaround for the Virtual Table. We will consider your suggestion for future releases though.

**Comment by DanHarman** [comment]
Is there a solution for the non virtual table?

**Comment by kvet** [comment]
You can use React ref in the tableRowTemplate of the TableView plugin to get the DOM Node. After that, execute the `scrollIntoView` function on a row's DOM Node when needed.

Here is a link to a similar question on StackOverflow: https://stackoverflow.com/questions/41596411/how-to-scroll-component-to-the-bottom-in-react

**Comment by frankbolviken** [comment]
What's the status on this at this time? Still no workaround? This would be a really nice feature to have, and we need it.

**Comment by maruware** [comment]
+1

**Comment by franklixuefei** [comment]
@kvet I think your suggestion has some limitations. It will only work for rows that are already rendered, but not for those that are out of view. I believe what most people want is the ability to scroll to a row by specifying an index, just like what `react-virtualized` does.

I'm currently long for this feature as well. I believe this feature is very useful.

**Comment by gwmaster** [comment]
is some one have work example that solving this problem by using react-virtualized

**Comment by gwmaster** [comment]
Hi. 
it's super important for my project.
is there some basic code that give me ability develop by myself this functionality.
without this functionality i can't use it.

**Comment by MaximKudriavtsev** [comment]
Hi,
 
As we pointed above, currently React Grid doesn't provide the requested functionality. As a workaround, you can use the approach described below.
 
First of all, I'd point the main principles of the VirtualTable plugin implementation.
 
VirtualTable renders only visible rows. The rendered row count depends on a table height. Then, to keep a scrollbar thumb height consistent, VirtualTable renders two empty rows.
 
The first one is before visible rows, the second is after them. The empty row height depends on the scroll position. You can inspect the html markup and see it in action.
 
The idea is to manually change the height of these empty rows. It will put a scrollbar thumb to the required position and VirtualTable will render only expected rows.
 
I've created a [sample](https://codesandbox.io/s/m5kq7wzl2y) that shows this approach in action. Please refer to my comments in the code.

**Comment by gwmaster** [comment]
wow cool!! look on it, thank you very match..

**Comment by mattmarcello** [comment]
One approach would be to not render two large rows above and below the aperture, but instead render dummy rows that are just empty divs with no content.  There would be some perf hit, but i don't think its that expensive to render empty divs.

**Comment by gwmaster** [comment]
the big divs this what make the trick of scroller
without them will no be a scroller
the height of the big divs is simulate all invisible rows

**Comment by mattmarcello** [comment]
Multiple divs rendering empty content could take up the same height as a single div.

**Comment by kvet** [comment]
Rendering multiple stub rows instead of one will dramatically decrease performance

**Comment by mattmarcello** [comment]
i don't dispute that it would decrease perf.  but rendering empty divs is still pretty cheap:

https://repl.it/repls/LightcyanGregariousLifecycles

definitely a perf tradeoff, but the point here is to discuss a possible scrollToIndex implementation.   rendering empty divs would allow people to trivially scroll to nodes, whose content could be rendered when they are visible in the aperture.

**Comment by gwmaster** [comment]
ok so basically its work and all good if its only vScroll.
but after some work i stuck on performance problem when render 10,000 rows and on smile click you can change him and its take to match time.
so i use  PagingPanel its solve the problem of performance  but now i need some more help on scroller if you can .
i build basic [example](https://codesandbox.io/s/x3rnk300lq) there 2 problems
this how its look on my PC 
![image](https://user-images.githubusercontent.com/5362853/45769463-6308fa00-bc48-11e8-9442-5281fc2a65a7.png)
when click on button "Open Page 3 open N428 open V2 Select V2 Selct D2 and Scroll to 65" 
its do all this on my pc same code in online editor Tree dont work 
the main problem is right now i find this magic 
Page 3 and 65 
what i have the id of row and from this i need find his location on page 3 and scroll to 65
row on example is  {"id":"n428v2d2","name":"D2","mark":2,"parentId":"n428v2"}

**Comment by LazyLahtak** [comment]
Hi all

We are working on implementing this feature. We are developing an API, which allows scrolling to a specified row (by the ID) using VirtualTable's `scrollToRow` method. Note that this feature doesn't work with remote data because we don't have information about unloaded rows.
Does this meet your requirements?

**Comment by LazyLahtak** [comment]
The current API:

```jsx
const App = () => {
//...

  const scrollToRow = (row) => {
    vtRef.current.scrollToRow(row);
  };

//....

  return (
    <Grid
      rows={rows}
      columns={columns}
      getRowId={getRowId}
    >
      <VirtualTable
        ref={vtRef}
      />
      <TableHeaderRow />
    </Grid>
  )
}
```

**Comment by LazyLahtak** [comment]
Hi all,

We are happy to inform you that we released this feature. You may find more information about it in the following [post](https://community.devexpress.com/blogs/javascript/archive/2020/01/17/devextreme-react-grid-ui-amp-api-enhancements-v19-2.aspx).
