### ISSUE TITLE
How to use a custom row template when mouse click selection is enabled

### ISSUE THREAD

**Issue by SergeyAlexeev** [DevExpress/devextreme-reactive#437]
According to the [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/), if you are using the `selectByRowClick` or `highlightSelected` property, the `tableRowTemplate` property is ignored.

Currently, there is no documented way to implement a custom table row template in this case. Yet, you can use our internal templating mechanism to achieve such a functionality. 

This [demo](https://stackblitz.com/edit/react-vozcjo?file=index.js) shows how to do this. Please take a look at the comments given in the code.

**Comment by dapozdnyakov** [comment]
Hi! How to use this mechanism now in beta.2, when TemplateRenderer has been removed?

**Comment by SergeyAlexeev** [comment]
Hi, 
Please refer to the updated [demo](https://stackblitz.com/edit/react-ers8qy?file=index.js).

**Comment by dapozdnyakov** [comment]
@SergeyAlexeev Thank you!

**Comment by filippoitaliano** [comment]
Ok, You're right. It works. I don't realize why but few pointless changes (I think) have solved the issue...

[Commit that fixes the error](https://github.com/filippoitaliano/devextreme-reactive-tests/commit/4bd2c06a8018a9daa76db4fdc4434d5d590dd0de)

Thanks for your time.

**Comment by slavavasylencko** [comment]
@SergeyAlexeev How can I add hover, like this https://codesandbox.io/s/rylk1x324o in table and highlight selection plugin with enabled TableSelection Plugin?

**Comment by lin-zy1229** [comment]
> Hi,
> Please refer to the updated [demo](https://stackblitz.com/edit/react-ers8qy?file=index.js).

@SergeyAlexeev 
It doesn't work for dxgrid/core 1.10.0, only works for 1.7.2.

Please update for latest version of dxgrid, thanks.

**Comment by msteinmn** [comment]
@SergeyAlexeev @lin-zy1229 Are we talking around a workaround here for a bug that has not yet been fixed, or is this really the way it is supposed to be. I have not been able yet to get this to work with 1.10.0 and material-ui. Workarounds are great, but wait, are they really?

**Comment by lin-zy1229** [comment]
If I do `<TableSelection selectByRowClick  rowComponent={Row} />`, instead of `<Table rowComponent={Row} />`, it works in latest version , (1.10.0)

However, RowStyle doesn't work.

Any way to get done this?

**Comment by msteinmn** [comment]
@lin-zy1229 Awesome, that worked.

**Comment by sentient-drone** [comment]
Type interface for `<TableSelection selectByRowClick rowComponent={Row} />` has not been updated as of 1.10.3. And typescript errors that `rowComponent` does not exist on `TableSelection`

**Comment by SergeyAlexeev** [comment]
Hi,

> And typescript errors that rowComponent does not exist on TableSelection

As you can see in our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/), the `TableSelection` plugin doesn't contain a public `rowComponent` property. 

I've updated the previously provided [example](https://stackblitz.com/edit/react-rxlvns?file=index.js) to v.1.10.3 as well.

**Comment by LazyLahtak** [comment]
@paufar,
Let me explain what happens.
When you use the TableSelection with highlightRow or selectByRowClick properties, TableSelection overrides rowComponent from Table on its own.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/#properties
You can use cellComponent instead of rowComponent in Table to process the onClick event (see [this example](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-33y00)).
You can also define rowComponent in TableSelection. However, it's an undocumented approach. If you want to use it with the selectByRowClick option, add the onToggle() call inside the onClick handler like in [this example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-pbr9m).
