### ISSUE TITLE
Allow Multi-language on placeholders/ displaying text

### ISSUE THREAD

**Issue by kavimaluskam** [DevExpress/devextreme-reactive#444]
Maybe one solution is allow to allow passing of custom placeholders/ displaying test (e.g.: `filter...`, `Rows per page`) as props to replace the default text.

**Comment by SergeyAlexeev** [comment]
Hi,

We are currently working on the functionality you mentioned. You can track this [PR](https://github.com/DevExpress/devextreme-reactive/pull/385) for more information.

**Comment by SergeyAlexeev** [comment]
Hi, 

We've implemented this functionality, and it will be available with the next update.
