### ISSUE TITLE
[Proposal] Ability to change group panel text.

### ISSUE THREAD

**Issue by dmtrKovalenko** [DevExpress/devextreme-reactive#451]
Seems that there is no ability to change the text of group panel. Seems that is not actually flexible solution (for example its blocking localization).
So I propose you to change the text on this line https://github.com/DevExpress/devextreme-reactive/blob/c7581bdcdc080545b99259c178253191d5899040/packages/dx-react-grid-material-ui/src/templates/group-panel.jsx#L42 
to render from props, with default text going from default props as well. Thus it would be easy to customize it by passing to `<GroupPanel />` component. 
I can open a PR later, if you dont mind.

**Comment by SergeyAlexeev** [comment]
Hi,
We appreciate your suggestion. Good news is that we've already implemented the localization functionality in the context of this [PR](https://github.com/DevExpress/devextreme-reactive/pull/385).
