### ISSUE TITLE
On row click event

### ISSUE THREAD

**Issue by radi-ratlh** [DevExpress/devextreme-reactive#458]
Hi,
How to implement on row click event (without selection)?

**Comment by gsobolev** [comment]
Hi!

You can specify a custom `tableRowTemplate` for the `TableView` plugin to achieve that. Please check the following [demo](https://github.com/DevExpress/devextreme-reactive/blob/v1.0.0-alpha.14/packages/dx-react-demos/src/bootstrap3/basic/table-row-template.jsx) and [this guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grid-basics/#appearance-customization) for more details.

**Comment by gsobolev** [comment]
We see this issue is not active and are closing it. If you have any questions related to the original problem, feel free to reopen it and contact us.
