### ISSUE TITLE
Behaviour of select all button when rows are filtered

### ISSUE THREAD

**Issue by DanHarman** [DevExpress/devextreme-reactive#465]
Hi,

Currently the select all button on the `TableSelection` plugin will select hidden rows when row filtering is applied. This is fairly unintuitive as it allows users to select rows they can't see. Is there a workaround, and is it intended behavior?

**Comment by SergeyAlexeev** [comment]
Hi,
 
Take a look at this [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/uncontrolled-mode/). Here, the 'Select All' checkbox selects only visible rows.
 
Take note that the `FilteringState` and `LocalFiltering` plugins are placed before the `SelectionState` and `TableSelection` ones. In this case, Grid filters rows first. Next, it selects filtered ones.

**Comment by DanHarman** [comment]
@SergeyAlexeev Thanks for that. Does this mean that sorting `SortingState` should be after filtering too as it will then only sort the visible rows?

**Comment by SergeyAlexeev** [comment]
I'd say the `LocalSorting` plugin should be after the `LocalFiltering` one.
