### ISSUE TITLE
Show PagingPanel at the top of the Grid as well as at the bottom of the Grid

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#470]
Hi,

I was wondering if it is possible to show the paging panel at the bottom and at the top of the grid. In my case I have a grid with 100 items. If users want to navigate to the second page they have to scroll all the way to the bottom. 

I tried adding the PagingPanel as first element in de Grid but it always shows the PagingPanel at the bottom.

Thanks,

Rob

**Comment by SergeyAlexeev** [comment]
Hi,
 
To implement your scenario, you can put a footer template into a header template. Thus, the footer template contains a paging panel and it will be rendered in the header as well.

```js
<Grid>
  <Template name="header">
    <div>
      {/* keep existing header template */}
      <TemplatePlaceholder />
      {/* add footer template */}
      <TemplatePlaceholder name="footer" />
    </div>
  </Template>
</Grid>
```

I've created a [demo](https://stackblitz.com/edit/react-nexmap?file=index.js) that shows this approach in action.
 
Please note that the described approach isn't documented yet.

**Comment by Rob-Post** [comment]
Thanks! Works flawless!
