### ISSUE TITLE
Disable sorting on certain columns

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#473]
Hi,

I have a grid with multiple columns with sorting enabled. In the first column an image is shown and in the second column a name. I don't want people to be able to sort on the image. Is it possible to disable the sorting on a particular column?

Thanks,

Rob

**Comment by kvet** [comment]
Hi,
 
It is not currently possible to do this with a high-level API, but we plan to add this feature in future releases. As a workaround, I can suggest you override headerCellTemplate in the TableHeaderRowPlugin.

**Comment by gsobolev** [comment]
Hi,
 
We are closing this issue as a duplicate of #363.
