### ISSUE TITLE
A question: How to select a single Row and highlight it?

### ISSUE THREAD

**Issue by Roberthaf** [DevExpress/devextreme-reactive#477]
Hei, I was wondering If there is a simple way to: 
only allow selecting a single row and highlighting it at the same time.
Similar to dxDataGrid's
```JavaScript  
selection: {
   mode: 'single'
},
``` 
Currently i have a simple grid which gets populated with about 30 rows.
```JavaScript
           <Grid
            rows={this.state.rows}
            columns={this.state.columns}
            getRowId={row => row.id}
          >
            <PagingState defaultCurrentPage={0} pageSize={8} />
            <LocalPaging />
            <SortingState
              sorting={this.state.sorting}
              onSortingChange={this.changeSorting}
            />
            <LocalSorting />
            <SelectionState
              selection={this.state.selection}
              onSelectionChange={this.changeSelection}
              }
            />
            <TableView />
            <TableHeaderRow allowSorting />
            <TableSelection
              selectByRowClick
              highlightSelected
              showSelectionColumn={false}

            />
            <PagingPanel />
          </Grid> />
```

I saw "setRowsSelection" but was not sure if that is the correct way to do it, nor was I sure how to use it.  
Do you have any examples on how to do it or advice you could give?

Thanks in advance.

**Comment by kvet** [comment]
Hi,
 
It is possible to implement single selection with a public API. Here is an example: https://stackblitz.com/edit/react-ranopq?file=index.js

**Comment by Roberthaf** [comment]
Okey nice. Thank you very much!

Btw I really like using devextreme-reactive, it looks great and its very nice to work with.

**Comment by kvet** [comment]
Thank you for your feedback. We greatly appreciate the response.
 
I am closing the issue. Feel free to reopen it if you need further assistance.

**Comment by apopa-mood** [comment]
> Hi,
>  
> It is possible to implement single selection with a public API. Here is an example: https://stackblitz.com/edit/react-ranopq?file=index.js

Same problem in 2019: can't figure out how to implement single selection. The link above is not working anymore.
