### ISSUE TITLE
getMessage undefined in pagerTemplate

### ISSUE THREAD

**Issue by Rid** [DevExpress/devextreme-reactive#478]
I'm trying to customize the style of the paging panel using material-ui and `pagingTemplate` (as you cannot currently override the default styling), however in the following example `getMessage` is `undefined`

```javascript
<PagingPanel
  allowedPageSizes={allowedPageSizes}
  pagerTemplate={
    ({
      getMessage,
    }) => {
      console.log(getMessage);
    }
  }
/>
```

**Comment by SergeyAlexeev** [comment]
Hi,
 
I can't reproduce the behavior you described on [my side](https://stackblitz.com/edit/react-xcr4zz?file=index.js).
 
Please take a note that the localization functionality is available starting with [v.1.0.0-beta.1](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#features).

**Comment by Rid** [comment]
@SergeyAlexeev thanks, upgraded, that was the issue.
