### ISSUE TITLE
Bootstrap 4.0 support

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#481]
Hey guys,

any chance we can see support for Bootstrap 4? Could use something like https://reactstrap.github.io/ for easy integration

**Comment by SergeyAlexeev** [comment]
Hi,

Yes, we have plans to support Bootstrap 4.0 in the future. We will update this thread when we have any progress.

Anyway, thank you for sharing the link to the `Reactstrap` project. It looks quite interesting.

**Comment by terndrup** [comment]
Nice, looking forward to this!

**Comment by KamiGim** [comment]
looking forward to this too!!!

**Comment by terndrup** [comment]
Any news on this? Would be a great update!

**Comment by kvet** [comment]
Hi,

We haven't added Bootstrap 4 support yet. But to be honest, we have no plans to implement it soon. We are currently working on a stable release of React Grid. We will update this ticket once we have any news.

**Comment by toralux** [comment]
@kvet Late in December 2017 Bootstrap 4.0 beta 3 came out and I think it's time to support it as Boostrap 4.0 will not change from beta 3 to stable:

>  There will be no breaking changes from Beta 3 to stable

**Comment by terndrup** [comment]
It's now officially released:

http://blog.getbootstrap.com/2018/01/18/bootstrap-4/

I think reactstrap should really find it's way into dxreact

**Comment by MaximKudriavtsev** [comment]
Hi,
 
We started working on supporting the Bootstrap 4 theme. You may see this in our [PR](https://github.com/DevExpress/devextreme-reactive/pull/681).

**Comment by kvet** [comment]
We released initial Bootstrap 4 support in 1.1.0-beta.2. Your feedback is greatly appreciated.

You can install it with the `next` tag:

```npm i --save @devexpress/dx-react-core@next @devexpress/dx-react-grid@next```
```npm i --save @devexpress/dx-react-grid-bootstrap4@next```

The `@devexpress/dx-react-grid-bootstrap4` package has the same API with `@devexpress/dx-react-grid-bootstrap3`.

**Comment by SergeyAlexeev** [comment]
React Grid supports Bootstrap 4 starting with [v1.1.0](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.1.0) that is officially released.
