### ISSUE TITLE
Default sorting algorithm, does not take care of Uppercase vs Lowercase

### ISSUE THREAD

**Issue by frankbolviken** [DevExpress/devextreme-reactive#483]
When sorting on strings, Uppercase words are sorted before lowercase. But ideally I guess it should be the same ?

**Comment by gsobolev** [comment]
Hi!

Our default sorting algorithm works the same way as the native [`Array.prototype.sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) method. Please check the code below.

```js
console.log(["c", "A", "b", "B", "C", "a"].sort());
```

If you need a different behavior you can implement a custom sorting algorithm. Please see our [Sorting Guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/#custom-sorting-algorithm) for more details.

**Comment by frankbolviken** [comment]
aha, I see. Thank you for quick reply!
