### ISSUE TITLE
[Proposal] Dynamic allow* properties. 

### ISSUE THREAD

**Issue by dmtrKovalenko** [DevExpress/devextreme-reactive#489]
I am propose you to implement a feature of dynamic `allowSorting` `allowEditing` `allowDeleting` props, to have an ability to pass a function to them, instead of just boolean, and depend on type of passed value call the function with a row, or just use boolean value. 
P.S. I can create a pull request later

**Comment by SergeyAlexeev** [comment]
Hi,
 
Thank you for the suggestion. Currently, it isn't in our plans. Of course, if you are interested in implementing such a functionality and creating a pull request, feel free to do it. If so, I'd recommend you implement the described features in separate pull requests. The first PR for `allowSorting`, the second for `allowEditing`, etc.
