### ISSUE TITLE
[ ERROR ]  'findDOMNode' is not exported by node_modules\react-dom\index.js

### ISSUE THREAD

**Issue by johnholliday** [DevExpress/devextreme-reactive#493]
[ ERROR ]  bundling: node_modules\@devexpress\dx-react-grid\dist\dx-react-grid.es.js, line: 12
           'findDOMNode' is not exported by node_modules\react-dom\index.js

L11:  import { TABLE_DATA_TYPE, TABLE_REORDERING_TYPE, addRow, addedRowsByIds, cancelAddedRows, cancelChanges, cancelDeletedRows, cancelGroupingChange, cellValueGetter, changeAddedRow, changeColumnOrder, changeDraftTableColumnWidths, changeRow, changeTableColumnWidths, changedRowsByIds, columnChooserItems, computedCreateRowChange, customGroupedRows, customGroupingRowIdGetter, deleteRows, draftGrouping, draftGroupingChange, draftOrder, evalAnimations, expandedGroupRows, filterActiveAnimations, filteredRows, getAnimations, getAvailableSelection, getAvailableToSelect, getColumnFilterConfig, getColumnSortingDirection, getGroupCellTargetIndex, getMessagesFormatter, getRowChange, getTableRowColumnsWithColSpan, getTableTargetColumnIndex, groupByColumn, groupRowChecker, groupRowLevelKeyGetter, groupedRows, groupingPanelItems, isAddedTableRow, isDataTableCell, isDataTableRow, isDetailRowExpanded, isDetailTableRow, isDetailToggleTableCell, isEditCommandsTableCell, isEditTableCell, isEditTableRow, isFilterTableCell, isFilterTableRow, isGroupIndentTableCell, isGroupTableCell, isGroupTableRow, isHeaderStubTableCell, isHeadingEditCommandsTableCell, isHeadingTableCell, isHeadingTableRow, isNoDataTableRow, isSelectAllTableCell, isSelectTableCell, orderedColumns, pageCount, paginatedRows, rowCount, rowIdGetter, rowsWithPageHeaders, setColumnFilter, setColumnSorting, setCurrentPage, setDetailRowExpanded, setPageSize, setRowsSelection, sortedRows, startEditRows, stopEditRows, tableColumnsWithDataRows, tableColumnsWithDetail, tableColumnsWithEditing, tableColumnsWithGrouping, tableColumnsWithSelection, tableColumnsWithWidths, tableHeaderRowsWithFilter, tableHeaderRowsWithReordering, tableRowsWithDataRows, tableRowsWithEditing, tableRowsWithExpandedDetail, tableRowsWithGrouping, tableRowsWithHeading, toggleColumn, toggleExpandedGroups, visibleTableColumns } from '@devexpress/dx-grid-core';
     L12:  import { findDOMNode } from 'react-dom';

**Comment by kvet** [comment]
Hi,
 
The issue does not seem to be related to `devextreme-reactive`. We provide js bundles in ES and UMD standards. And they work well in webpack, for example.
 
It also seems that you are using a rollup as a bundle tool. If that is true, please see the original repository for a solution. Here is a similar issue related to the error: https://github.com/rollup/rollup-plugin-commonjs/issues/139

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
