### ISSUE TITLE
Allow displaying a row detail on editing

### ISSUE THREAD

**Issue by gsobolev** [DevExpress/devextreme-reactive#495]
Currently, on switching a row to the editing mode, the related row detail is collapsed if it was expanded. But in a number of cases, it may be useful to preserve editing the row detail. For example, the editing form may be placed in the row detail.

**Comment by KJoyner** [comment]
I saw a bit different behavior. I don't see the row data being collapsed if it is already expanded; however, the row detail selector goes away so I cannot expand/collapse when in editing mode.

**Comment by gsobolev** [comment]
We analyzed this issue further and found a way to achieve the desired behavior. Place the TableRowDetail plugin before TableEditRow. Please check the example here: https://stackblitz.com/edit/react-yly5ky?file=index.js
 
This works because of the internal React Grid structure. The grid uses data pipelines when constructing view data. TableEditRow, for instance, replaces user-defined rows which are being edited at the moment with its own ones. However, TableRowDetail adds details only for the user-defined rows. So, when you place TableRowDetail before TableEditRow, the Grid adds detail rows and only then replaces the user-defined rows with edit ones.
 
As @KJoyner mentioned, the Grid does not allow expanding and collapsing detail rows that are being edited. If you wish to avoid this behavior, feel free to create a separate issue.
