### ISSUE TITLE
Change row state doesn't rerender the row with custom tableCellTemplate method

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#509]
Hi,

Consider the following example: https://www.webpackbin.com/bins/-KziIgR-RQxWwAHd8adC

When pressing the button I would expect the word 'star' to appear in de fouth row, but it doesn't. How would I achieve this?

Thanks

**Comment by SergeyAlexeev** [comment]
Hi,

It looks like the problem is that you did not create a copy of rows and changed the existing ones:

```js
let rows = this.state.rows;
```

This string should be replaced with:

```js
let rows = this.state.rows
      .map((row, rowIndex) =>
        (rowIndex === 3
          ? Object.assign({}, row, { starred: true })
          : row));
```

Please refer to the updated [example](https://www.webpackbin.com/bins/-KziXgGstRwysTqsShC2).

**Comment by Rob-Post** [comment]
Thanks! Works good!
