### ISSUE TITLE
Have the ability to cancel commit event

### ISSUE THREAD

**Issue by AlexK-IL** [DevExpress/devextreme-reactive#515]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Using `EditingState`'s `onCommitChanges` callback I'm validating the row changes.  

In the case of some input being invalid I would like to prevent the component from canceling the edit and persevere the changed state.

### Expected Behaviour

I would return an undefined or false inside the callback and the edited row would remain the same as before clicking on the commit button.

### Your Environment

devextreme-reactive: 1.0.0-beta.1
react: 15.6.2
browser: chrome 52
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.17

**Comment by kvet** [comment]
Hi,
 
Have you tried using the EditingState plugin in controlled mode? It allows you to control the editing behavior. We have a different example showing how to delete confirmation here: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/. Feel free to reach out to us if you need further assistance.

**Comment by AlexK-IL** [comment]
Thanks, I'll look at that and see if I can make this work out.  
I have read your documentation about the controlled and uncontrolloed modes but I'm still confused a bit...  
Does controlled mode essentially means implementing all state logics? I'd like to refrain from that because it does save me a lot of code having all the state behavior out of the box.

**Comment by kvet** [comment]
Yes, using the controlled mode means that you will implement part of state logic manually. And I understand your concerns about this.
 
I also want to mention that React Grid is not mature enough to have all abilities built-in. Of course, we will consider your request for future enhancements. But today the controlled mode is a good solution to implement all required state logic for any specific scenario.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by xsqox** [comment]
Did the status of this issue changed? Is there a way to cancel Commit and/or leave editor open without using Controlled mode?

**Comment by xsqox** [comment]
Also, could you please help me to find Delete confirmation example? There is nothing here https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/
Thank you!
