### ISSUE TITLE
can this grid change the sort icon

### ISSUE THREAD

**Issue by KamiGim** [DevExpress/devextreme-reactive#519]
Thanks you!

**Comment by gsobolev** [comment]
Hi!
 
You can achieve this by specifying a custom `headerCellTemplate` of the `TableHeaderRow` plugin. For more details about the `headerCellTemplate` property see our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/).

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
