### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by MOZGIII** [DevExpress/devextreme-reactive#525]
Hello. Is there any way to make table horizontally scrollable with mouse wheel?

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I can't scroll table horizontally with the mouse wheel.

### Expected Behaviour

I can turn on some knob and then can scroll table horizontally with the mouse wheel.

### Steps to Reproduce (for Bugs)

Just create a grid with a lot of columns. You can't scroll it horizontally with the mouse wheel.

### Your Environment

devextreme-reactive: @devexpress/dx-core@1.0.0-alpha.13 @devexpress/dx-react-grid-material-ui@1.0.0-alpha.13
react: react@16.0.0
browser: Chrome 62
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.18

**Comment by kvet** [comment]
Hi,
 
It is possible to scroll horizontally by holding the 'shift' key.
 
The issue is not related to the React Grid, because the event system is built-in in the browser. You may try to find a solution on StackOverflow, for example.

**Comment by MOZGIII** [comment]
Thanks for the comment. I didn't know about the shift-scroll, this may be enough.
