### ISSUE TITLE
Can't filter on Link

### ISSUE THREAD

**Issue by jaydreyer** [DevExpress/devextreme-reactive#531]
I'm doing something wrong, but can't figure it out. I have filtering enabled, and it works perfectly for every column except the first one, where the data I want to filter on is a Link component: `        api_id: <Link to={'/catalog/' + rowData.api_id + '?catalog=true'}>{rowData.api_id}</Link>,
`
When api_id was just set to {rowData.api_id}, filtering worked. But when I added the Link component to display the api_id as a hyperlink, filtering stopped working. Well, it 'filters', but typing anything just filters out everything. Hopefully, this is something simple. 

***Edit*** I've figured out that everything is being filtered on the word 'object', since the letters e, t, o, j, c, and b (jumbles ftw!) all filtered nothing when used, and every other letter would filter out all of the values. So, everything displays correctly but filtering looks at every value as 'object'.

I need to know the correct way to display a hyperlink in a cell.

Thanks!

**Comment by gsobolev** [comment]
Hi!

Grid appearance customization should be performed via templates. Use the `tableCellTemplate` property of the `TableView` plugin to achieve the required behavior. Please see more on this topic in our [guides](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grid-basics/#appearance-customization).

**Comment by jaydreyer** [comment]
Thanks, @gsobolev. That worked out great.
