### ISSUE TITLE
Drag&Drop with Laptops which has Touch support

### ISSUE THREAD

**Issue by frankbolviken** [DevExpress/devextreme-reactive#535]
During our trial of this grid we discovered that users which have laptops with touch support could not drag&drop in Chrome. For instance grouping, rearranging columns and resizing columns. When these users are testing in Edge it works fine.

- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Nothing happens when dragging columns on touch enabled laptops and Chrome (might be more)

### Expected Behaviour
Should behave the same way as normal 

### Your Environment

devextreme-reactive: 1.0.0-beta.1
react: ^16.0.0
browser: Chrome/Edge/++
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.21

**Comment by frankbolviken** [comment]
After some more investigation we found out a hotfix for Chrome, however, it should not be needed I would hope :)

Point Chrome to URL: chrome://flags
DISABLE: "Enable touch events"
DISABLE: "Enable touch initiated drag and drop"
Relaunch chrome

After changing these settings it's working.

**Comment by kvet** [comment]
Hi,
 
I've researched the issue. There is a bug that prevents dragging on a laptop with a touch-enabled screen in Chrome. We will fix it.
