### ISSUE TITLE
PagingPanel throws an error with the latest Material UI

### ISSUE THREAD

**Issue by marcelmika** [DevExpress/devextreme-reactive#546]
Hi guys, I found out a small issue regarding the pagination in material-ui.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Steps to Reproduce
If you use the `PagingPanel` with the `allowedPageSizes` prop:
```jsx
<PagingPanel allowedPageSizes={allowedPageSizes}/>
```
you get:
```
warning.js:33 Warning: Unknown prop `InputClasses` on <div> tag.
```

This is caused by the breaking change introduced in **1.0.0-beta.22**. As you can see [here](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.22) the `InputCalasses` was removed from the `Select` component although it's still used in `PageSizeSelector` [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/page-size-selector.jsx#L68).

### Your Environment

devextreme-reactive: 1.0.0-beta.1
react: 15.6.2
browser: all
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.22

**Comment by gsobolev** [comment]
Hi!
 
Thank you for reporting this problem. We will take this into account when we update the `material-ui` package version our Grid depends on.

**Comment by MaximKudriavtsev** [comment]
Hi,
 
We have published a new version of the [DevExtreme React Grid](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-beta.2) where the problem you reported is resolved.

**Comment by marcelmika** [comment]
Works like a charm, thx!
