### ISSUE TITLE
Possibility to differentiate between rowclick and checkbox click

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#547]
Hi,

Currently when using selection with row click enabled the same method is called when clicking on the row or when clicking on the checkbox of the row. I want different behaviour depending on where the user clicks. Is this currently possible?

Thanks

**Comment by SergeyAlexeev** [comment]
Hi,
 
In your case, I suggest you use a custom template for a select cell to identify a click on a checkbox:
 
```js
class App extends React.PureComponent {
  constructor(props) {
    super(props);
    this.checkboxClicked = false;
  }
  render() {
    <Grid>
    { /* ... */ }
    <TableSelection
      selectByRowClick
      highlightSelected
      selectCellTemplate={({ changeSelected, selected }) => {
        return (
          <td>
            <input
              type="checkbox"
              checked={selected}
              onClick={(e) => { 
                // handle click on a checkbox
                this.checkboxClicked = true; 
                e.stopPropagation();
              }}
              onChange={() => {
                changeSelected();
              }}
            />
          </td>
        );
      }}
    />
  }
}
```
 
Then, you will be able to use the `this.checkboxClicked` flag within the `onSelectionChange` property in the `SelectionState` plugin.
 
The following [demo](https://stackblitz.com/edit/react-tsettv?file=index.js) shows this approach in action.

**Comment by Rob-Post** [comment]
Thank you very much! Works good!

**Comment by SergeyAlexeev** [comment]
You are welcome!
