### ISSUE TITLE
InputClasses Prop has been removed in the latest version of Material UI

### ISSUE THREAD

**Issue by SysOpsNet** [DevExpress/devextreme-reactive#559]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Warning: React does not recognize the `InputClasses` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputclasses` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Expected Behaviour

No Errors

### Steps to Reproduce (for Bugs)

I believe this error is related to this:  https://github.com/mui-org/material-ui/pull/9159

But I am pretty much a beginner, so if I am doing something wrong please let me know.

### Your Environment

devextreme-reactive: xxx
react: 16.2.0
browser: chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.22

**Comment by SysOpsNet** [comment]
if I delete 
Line: 593         InputClasses: { root: classes.inputRoot },
from dx-react-grid-material-ui/dist/dx-react-grid-material-ui.cjs.js
and
Line: 586         InputClasses: { root: classes.inputRoot },
from
dx-react-grid-material-ui/dist/dx-react-grid-material-ui.es.js

The warning seems to resolve itself.

**Comment by SergeyAlexeev** [comment]
Thank you for reporting the issue. 

We have already [fixed](https://github.com/DevExpress/devextreme-reactive/pull/554) it. The fix will be available with the next update. 
For now, I suggest you use the Material UI v1.0.0-beta.21.

**Comment by SysOpsNet** [comment]
Thank you, that worked.
