### ISSUE TITLE
Question about how to render buttons (Or any other custom elements in the footer or header)

### ISSUE THREAD

**Issue by SysOpsNet** [DevExpress/devextreme-reactive#571]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I am trying to implement buttons to delete multiple items at the bottom in the footer area and I am also trying to implement a header title in the top of the page. Everything else works perfectly but these two I could not figure out yet. I am using Material-UI and I can add this behind another Paper but that looks ugly because I will have double shadows. 
Can you assist me?

### Your Environment

devextreme-reactive: 1.0.0-beta.1
react: 16.2.0
browser: chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.22

**Comment by SergeyAlexeev** [comment]
Hi,
 
There are two ways to implement your scenario.
 
The first one is based on using the `headerPlaceholderTemplate` and `footerPlaceholderTemplate` properties of the `Grid`. [This](https://stackblitz.com/edit/react-xpchy9?file=index.js) demo shows how to achieve this. The main disadvantage of this approach is that your custom templates don't contain default CSS classes that are related to footer and header panels.
So, if you are using other plugins like `PagingPanel`, `GroupingPanel` etc., I suggest you use the second approach described [here](https://github.com/DevExpress/devextreme-reactive/issues/470). Please see [this](https://stackblitz.com/edit/react-kvs29r?file=index.js) demo.

**Comment by SysOpsNet** [comment]
Thank you Sergey! Excellent, this is exactly what I'm looking for! 👍
