### ISSUE TITLE
How to install from Github?

### ISSUE THREAD

**Issue by medihack** [DevExpress/devextreme-reactive#572]
This is more a rhetoric question as this seems to be quite hard ;-) There is a long discussion about installing a subfolder of a repository and monorepos in general at the [NPM Github issues](https://github.com/npm/npm/issues/2974) (yarn misses this feature, too). The thing is that this makes it quite hard to report issues of your project as one can't test the current master easily. Do you recommend a way how to use the latest Github version? I tried to clone your repository and `npm link` against a package subfolder directly but ended up with errors (`404 Not Found: @devexpress/dx-testing@1.0.0-beta.1`). (Addendum: The last error happens in your packages as there is no `@devexpress/dx-testing` package on NPM. Could it be that you linked it locally while developing? Then it shouldn't be a dependency in `package.json`.)

**Comment by kvet** [comment]
Hi,
 
We don't have a recommended solution for using React Grid from the master branch.
 
There is a way in which to try the latest features. Here are the steps:
 
- `git clone https://github.com/DevExpress/devextreme-reactive.git`
- `cd devextreme-reactive`
- `yarn`
- `yarn run build`
- `npx lerna exec -- yarn pack`
 
Now, you can use .tgz files in `packages/<package>` folders by installing them with npm/yarn.

**Comment by medihack** [comment]
Thanks a lot! Works perfectly. Would be a nice addition to the documentation. Very good project ... really the best thought out data grid.
