### ISSUE TITLE
Help with GetCellValue on selection change

### ISSUE THREAD

**Issue by deranjer** [DevExpress/devextreme-reactive#575]
I'm having an issue trying to extract the value of a cell when a row is selected.. does anyone have any examples for me to look at?

**Comment by gsobolev** [comment]
Hi!

Please check #378 and #373 where the same problem is discussed.

**Comment by deranjer** [comment]
Hmm, let me add some more information, I just started react a few weeks ago so maybe missing something simple:

This is my selection handler, it easily prints out the row of the selection just fine... but I need the cell value of the "Status" column.. which I'm not sure how to get with just the selection row, as the row data (the data in all of the cells) is not available.

`  selectionHandler = (selection) => {
        console.log("Selection", selection[0]) //prints out row number
        this.props.changeSelection(selection) //dispatch to redux
       
    }`


`render() {
        return (   
            <Grid rows={this.state.torrentList} columns={this.state.columns}>
                <SortingState sorting={this.props.sorting} onSortingChange={this.props.changeSorting} />
                <LocalSorting />
                <SelectionState onSelectionChange={this.selectionHandler} selection={this.props.selection}/> 
                <TableView  tableCellTemplate={({ row, column, style }) => {
                    if (column.name === 'PercentDone') {
                    return (
                        <ProgressBarCell value={row.PercentDone * 100} style={style} />
                    );
                    }
                    return undefined;
                }}/>
                <DragDropContext />
                <TableColumnResizing columnWidths={this.state.columnWidths} onColumnWidthsChange={this.changeColumnWidths}/>
                <TableColumnReordering order={this.state.columnOrder} onOrderChange={this.changeColumnOrder} />
                <TableSelection selectByRowClick highlightSelected />
                <TableHeaderRow allowSorting allowResizing allowDragging />
            </Grid>
        );
    }`

I can change the code around a little bit:

This will print out the status for each of the values in that column... but then nothing shows up in my actual grid..

`<Grid rows={this.state.torrentList} columns={this.state.columns} getCellValue={this.getCellValueFunc}>`

`getCellValueFunc = (selection) => {
        console.log(selection["Status"])`
}`

**Comment by gsobolev** [comment]
The way you are specifying the `getCellValue` property in the example above does not appear to be correct. The function which this property accepts has a different signature. Please review the Grid [reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/)  and [this guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-accessors/) to learn more.
 
In fact, I don't quite understand what `getCellValue` is used in your case. As far as I understand, you need to access a field of the last selected row. If so, I have created an example illustrating how this can be achieved: https://stackblitz.com/edit/react-nqtcxm?file=index.js.

**Comment by deranjer** [comment]
I can replicate the example just fine... I just don't understand how to use your example to get the "Last Name" or "Age" field of that row...

**Comment by gsobolev** [comment]
Oh, I see. Looks like I did not save the last changes in the example. I apologize for the inconvenience.
Now I have updated the link: https://stackblitz.com/edit/react-nqtcxm?file=index.js.

**Comment by deranjer** [comment]
Thanks, I was able to change the example to something that worked for me!

```
determineButtonState = (selectedRows) => {
        selectedRows.forEach(element => {
            if (element.Status === "Downloading" || "Awaiting Peers" || "Seeding") {
                let buttonState = [{startButton: "default", pauseButton: "primary", stopButton: "primary", deleteButton: "accent", fSeedButton: "default", fRecheckButton: "primary"}]
                this.props.setButtonState(buttonState)
            } else if (element.Status === "Completed")  {
                let buttonState = [{startButton: "default", pauseButton: "default", stopButton: "default", deleteButton: "accent", fSeedButton: "primary", fRecheckButton: "primary"}]
                this.props.setButtonState(buttonState)
            } else {
                this.props.setButtonState(this.props.buttonStateDefault)
            }
        });
    }

    changeSelection = (selection) => {
        this.props.changeSelection(selection) //dispatch selection to redux

        if (selection.length === 0) { //if selection is empty buttons will be default
            this.props.setButtonState(this.props.buttonStateDefault) //if no selection dispatch that to redux
        } else { // if we have selection continue on with logic to determine button state
            const selectedRows = [] //array of all the selected Rows
            selection.forEach(element => {   
                selectedRows.push(this.props.torrentList[element])   //pushing the selected rows out of torrentlist
            });
            this.determineButtonState(selectedRows) //running a filter on the rows to determing buttonState
        } 
       
    }
```
