### ISSUE TITLE
Is there a way to use summaries/aggregates in the grouping feature?

### ISSUE THREAD

**Issue by facuesr** [DevExpress/devextreme-reactive#579]
Is there a way to use summaries/aggregates in the grouping feature?

**Comment by kvet** [comment]
Hi,

We don't provide such computations in the LocalGrouping plugin. However, if you perform custom computations, it is possible to use the CustomGrouping plugin and customize appearance within the TableGroupRow plugin.

Please refer to the following guides:

- custom grouping setup: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/#custom-grouping
- configuring a custom group rows appearance: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/#local-grouping-with-custom-values

**Comment by facuesr** [comment]
Thanks!
