### ISSUE TITLE
Warning shows when using PagingPanel with allowedPageSizes

### ISSUE THREAD

**Issue by tuannat** [DevExpress/devextreme-reactive#580]
### Detail

> Warning: React does not recognize the `InputClasses` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputclasses` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Input)
    in Input (created by withStyles(Input))
    in withStyles(Input) (created by PageSizeSelectorBase)
    in Select (created by withStyles(Select))
    in withStyles(Select) (created by PageSizeSelectorBase)
    in div (created by PageSizeSelectorBase)
    in PageSizeSelectorBase (created by withStyles(PageSizeSelectorBase))
    in withStyles(PageSizeSelectorBase) (created by PagerBase)
    in div (created by PagerBase)
    in PagerBase (created by withStyles(PagerBase))
    in withStyles(PagerBase) (created by TemplateRenderer)
    in TemplateRenderer (created by TemplateConnector)
    in TemplateConnector (created by PagingPanel)
    in div (created by PagingPanel)
    in div (created by FooterBase)
    in FooterBase (created by withStyles(FooterBase))
    in withStyles(FooterBase) (created by TemplatePlaceholder)
    in TemplatePlaceholder (created by Root)
    in div (created by Paper)
    in Paper (created by withStyles(Paper))
    in withStyles(Paper) (created by Root)
    in Root (created by TemplatePlaceholder)
    in TemplatePlaceholder (created by DragDropContext$$1)
    in DragDropContext (created by DragDropContext$$1)
    in div (created by DragDropContext$$1)
    in TemplatePlaceholder (created by PluginHost$$1)
    in div (created by PluginHost$$1)
    in PluginHost$$1 (created by Grid)
    in Grid (created by Grid$$1)
    in Grid$$1 (at TableComponent.js:141)
    in div (created by Grid)
    in Grid (created by GridWrapper)
    in GridWrapper (created by withStyles(GridWrapper))
    in withStyles(GridWrapper) (at TableComponent.js:140)
    in div (created by Grid)
    in Grid (created by GridWrapper)
    in GridWrapper (created by withStyles(GridWrapper))
    in withStyles(GridWrapper) (at TableComponent.js:115)
    in TableComponent (created by withStyles(TableComponent))
    in withStyles(TableComponent) (at HomeContainer.js:47)
    in HomeContainer (created by Connect(HomeContainer))
    in Connect(HomeContainer) (at RoutesHelper.js:84)
    in main (at LayoutWrapperContainer.js:74)
    in div (at LayoutWrapperContainer.js:71)
    in div (at LayoutWrapperContainer.js:70)
    in PermanentDrawer (created by withStyles(PermanentDrawer))
    in withStyles(PermanentDrawer) (at RoutesHelper.js:83)
    in Route (at RoutesHelper.js:79)
    in PrivateRouteWithLayout (at RoutesHelper.js:22)
    in RoutesCreator (at Routes.js:14)
    in div (at AppContainer.js:24)
    in AppContainer (created by withStyles(AppContainer))
    in withStyles(AppContainer) (created by Connect(withStyles(AppContainer)))
    in Connect(withStyles(AppContainer)) (created by Route)
    in Route (created by withRouter(Connect(withStyles(AppContainer))))
    in withRouter(Connect(withStyles(AppContainer))) (at Routes.js:13)
    in Unknown (created by Connect(Component))
    in Connect(Component) (at RootContainer.js:21)
    in AppContainer (at RootContainer.js:19)
    in App (at index.js:24)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at index.js:23)
    in PersistGate (at index.js:20)
    in Provider (at index.js:19)
    in MuiThemeProvider (created by MuiThemeProviderWrapper)
    in MuiThemeProviderWrapper (at index.js:18)

### Environment
devextreme-reactive: ^1.0.0-beta.1
react: ^16.2.0
browser: Chrome
material-ui: 1.0.0-beta.23

**Comment by MaximKudriavtsev** [comment]
Hi!
Please check #546 where the same problem is discussed.
