### ISSUE TITLE
Contextmenu on grids

### ISSUE THREAD

**Issue by frankbolviken** [DevExpress/devextreme-reactive#584]
Would it be possible to implement a feature like right-clicking on a row to get a context-menu ? Is this planned?

**Comment by SergeyAlexeev** [comment]
Hi,

We don't have such plans. Currently, you can handle the `onContextMenu` event as follows:

```js
const Row = props => (
  <Table.Row {...props} onContextMenu={(e) => {
    e.preventDefault();
    alert('Context menu');
  }} />
);

<Grid
  rows={rows}
  columns={columns}
>
  <Table
    rowComponent={Row}
  />
</Grid>
```

Please refer to [this](https://stackblitz.com/edit/react-ugkw6e?file=index.js) demo.

**Comment by frankbolviken** [comment]
Thanks!
