### ISSUE TITLE
Issue with column resizing and loading external data?

### ISSUE THREAD

**Issue by frankbolviken** [DevExpress/devextreme-reactive#589]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
When showing grid with empty data while external data is loading, trying to resize the columns after data has finished loading and table is populated does not work. The first column works to drag and resize, but when dragging on the resize handler on the other columns does not work.

### Expected Behaviour
Should work :)

### Steps to Reproduce (for Bugs)
Create a view with with a table
When initialising the view, perform a fetch that takes at least over 2 seconds to retrieve Table data.
Observe that columns cannot be resized after data has been fetch

### Your Environment

devextreme-reactive: 1.0.0-beta.2
react: 16.20.0
browser: Chrome
material-ui: 1.0.0-beta.23

**Comment by kvet** [comment]
Hi,
 
I am afraid that I cannot reproduce this problem. Here is an example I created based on the described steps: https://stackblitz.com/edit/react-tyodze?file=index.js. If my test sample works correctly on your side, would you please send us your simple project demonstrating the issue? We will review it and provide you with a solution.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
