### ISSUE TITLE
Best way to theme a single component

### ISSUE THREAD

**Issue by Rob-Post** [DevExpress/devextreme-reactive#599]
Hi,

I would like to apply custom styling to the TableSelection.HeaderCell component. What would be the best way to do this? (Maybe add some documentation about this?)

Thanks in advance.

Rob

**Comment by kvet** [comment]
Hi,

It is possible to achieve this by passing custom styles or a custom class name into the TableSelection.HeaderCell component.

If you are talking about more complex customizations like replacing a check box with a switch, I am afraid that there is no simple solution. You need to redefine a cell completely. Though it may require additional efforts, it is possible to copy our default template from the GitHub repo and modify it.

**Comment by Rob-Post** [comment]
Hi,

I'm quite new to the whole styling thing. I managed to solve my problem in the following way:

```
const tableSelectionHeaderCellComponentStyles = {
    cell: {
        paddingRight: '8px',
        paddingLeft: ' 8px',
    }
};

..

private tableSelectionHeaderCellComponent = (props: any): JSX.Element => {
    return (<DxReactGridMaterialUi.TableSelection.HeaderCell {...props} />);
}

private tableSelectionHeaderCellComponentWithStyles = withStyles(tableSelectionHeaderCellComponentStyles)(this.tableSelectionHeaderCellComponent);

..

<TableSelection headerCellComponent={this.tableSelectionHeaderCellComponentWithStyles} />
```

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
