### ISSUE TITLE
Expose the TableLayout template on the Table

### ISSUE THREAD

**Issue by Maher4Ever** [DevExpress/devextreme-reactive#614]
Hello, I have a simple request: to expose the `TableLayout` template.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Currently, templates such as `Cell` and `Row` are expose on the `Table` component as can be seen [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/plugins/table.jsx#L37-L42). However, the `TableLayout` is not.

### Expected Behaviour
The `TableLayout` template is exposed. This allows overriding one or more of the props while using the original component. Given that `Table` also [allows specifying the `layoutComponent`](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/), it should be possible to reuse the original component in the wrapper.

### Steps to Reproduce (for Bugs)

N/A

### Your Environment

devextreme-reactive: 1.0.0-beta.2
react: 16.2.0
browser: Chrome 63
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.24

**Comment by SergeyAlexeev** [comment]
Hi,
 
Would you please clarify what exactly you want to customize by using the table layout component?

**Comment by Maher4Ever** [comment]
I'm trying to make the cells responsive to window size. Now the table has a `min-width` because my columns don't have a width. I looked in the code and the `TableColumn` has a `type` property that I can set to `flex` to deal with this issue. But to change it I need to access it and the only way is via the `TableLayout`

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification.
 
Actually, the `TableLayout` component is a part of our internal codebase and its interface can be changed in the future. Thus, we are going to hide the `layoutComponent` property of the `Table` plugin from API reference. 
 
As for html table element customization, I think it's better to extract the related component from the Table plugin. It should be similar to the `Table.Row`, `Table.Cell` etc. components. We are going to introduce such a functionality in the future.

**Comment by Maher4Ever** [comment]
Ok. How would you suggest handeling the `max-layout` issue at this moment?

**Comment by SergeyAlexeev** [comment]
Currently, you can use the way described [here](https://github.com/DevExpress/devextreme-reactive/issues/288). Please follow a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/627) as well.

**Comment by Maher4Ever** [comment]
@SergeyAlexeev Thank you! I was able to remove the `style` attribute using that technique.
