### ISSUE TITLE
export 'IntegratedFiltering' & 'IntegratedSorting' error

### ISSUE THREAD

**Issue by dvu714** [DevExpress/devextreme-reactive#635]
I'm having issues using the IntegratedFilter & IntegratedSorting components.  If I remove the Integrated components everything seems to works fine.

Getting this error - '@devexpress/dx-react-grid' does not contain an export named 'IntegratedSorting'.

package versions.
 "material-ui": "^1.0.0-beta.25",
 "@devexpress/dx-react-core": "^1.0.0-beta.3",
 "@devexpress/dx-react-grid": "^1.0.0-beta.3",
 "@devexpress/dx-react-grid-material-ui": "^1.0.0-beta.3",

**Comment by kvet** [comment]
Hi,
 
I could not reproduce the issue on my side. Here is the example I've created: https://www.webpackbin.com/bins/-L1Vucg3GWQvnTANYweM. If my example works correctly, would you please send us your example demonstrating the issue? We will review it and provide you with a solution.

**Comment by dvu714** [comment]
This was something on my side.  Thank you!
