### ISSUE TITLE
2 virtual table at the same page

### ISSUE THREAD

**Issue by Deadly0** [DevExpress/devextreme-reactive#636]
### Current Behaviour
I have added 2 virtual table at the same page and when i scroll 1st table i see how rows of the 2nd table disapears from the top

### Expected Behaviour
When i scroll 1st table the 2nd table should stay in the same state as before.

devextreme-reactive material-ui beta.2

**Comment by Deadly0** [comment]
Looks like i have found the real problem.

I have a dialog inside a cell in of the virtual table and with the dialog is opened and i sroll content of this dialog i scroll the virtual table too.

PS. There is not matter what inside the dialog: another table or just a text both will scroll the parent virtual table.

**Comment by MaximKudriavtsev** [comment]
I could not reproduce the issue on my side. Here is the [example](https://www.webpackbin.com/bins/-L1XwaW99dqv_L0KwYd0). If my example works correctly, would you please send us your example demonstrating the issue? We will review it and provide you with a solution.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
