### ISSUE TITLE
Allow editing of specific columns

### ISSUE THREAD

**Issue by Arochka** [DevExpress/devextreme-reactive#637]
Hello,

I would like to know if there is a way to only allow editing of specific columns.

For example, let say I have 4 columns:

Id, Firstname, Lastname, Email

And I would like to only allow editing of Firstname and Lastname and leave others intact

If it's not possible, i'm sure it can be a great improvement :)

### Your Environment

devextreme-reactive material-ui beta.3

**Comment by timothyvanderaerden** [comment]
Hello

You could do something like this:

```
import Input from 'material-ui/Input';
```
```
editCellComponent = (props) => {
    if (props.column.name === 'id' || props.column.name === 'email') {
      return(
        <Table.Cell>
          <Input
            disabled
            {...props}/>
        </Table.Cell>
      );
    }
    return <Table.Cell {...props} />;
  };
```
And in your Table:
```
<TableEditRow cellComponent={this.editCellComponent} />
```

Thats if you are using Material-UI.

**Comment by Arochka** [comment]
Thank you it's perfect :)

**Comment by hsimah** [comment]
Thanks for this info, it was helpful. Given this is a beta, are there plans to implement an `allowEdit` on the column definition down the line?

**Comment by SergeyAlexeev** [comment]
Hi, 
 
Yes, it's on our short list.
