### ISSUE TITLE
Add a custom column to each row for a button

### ISSUE THREAD

**Issue by lrossy** [DevExpress/devextreme-reactive#639]
Since I've updated to 1.0.0-beta.3 from 1.0.0-beta.1, the `<TableView />` plugin does not seem to be supported anymore. 

I used to do the following to get a button on each table row, it worked great: https://github.com/DevExpress/devextreme-reactive/issues/346

However now, this doesn't seem to work anymore. What is the recommended way to do this now?

**Comment by lrossy** [comment]
in case anyone is wondering, this is how I got it, although I'm not sure yet if this is the best way:

In my component I made a fn to get the cell:

```
getCell = (props) => {

    if(this.props.customColData !== undefined) {
      if (props.column.name.includes('customColumn')) {
        let thisCol = this.props.customColData.filter(d => {
          if (d.name === props.column.name) {
            return d;
          }
          return false;
        });
        return (
          <Table.Cell>
            <Button raised onClick={() => {
                      thisCol[0].onClick(props.row);
                    }}>{thisCol[0].label}</Button>
          </Table.Cell>
        )
      }
    }

    return <Table.Cell {...props} />;

  };
```

then in my render() I just use it like this:

```
<Table cellComponent={this.getCell} />
```

**Comment by kvet** [comment]
Hi,

It seems that you've faced the problem described here: #496. There is a solution for your case.

Anyway, your solution is correct.
