### ISSUE TITLE
Capture Event when using Selection Change

### ISSUE THREAD

**Issue by tablesOHA** [DevExpress/devextreme-reactive#641]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
After upgrading from alpha-13 to beta-3, I am unable to capture the mouse click event when clicking a check box in the selection column.

### Expected Behaviour
Expect to retrieve the the event that clicked the check box. The below code worked for alpha-13 and react 16. It also currently works to create an onClick bind for the table, row, ect., but won't work with row selection (either by checkbox of by row) as the checkbox click appears to prevent the event from properly bubbling (proper terminology?) up.

```
changeSelection = (selection, event) => {
       // event doesn't have any info on the click event
        if (event.shiftKey && selection.length > 0) { //errors here
            //Shift select code
    };

public render() {
        return <div className={this.props.classes.grid}>
            <Paper>
                <Grid
                    rows={this.props.transactions}
                    columns={this.state.columns}
                >
                    <FilteringState defaultFilters={[/* ... */]} />
                    <SortingState
                        sorting={this.state.sorting}
                        onSortingChange={this.changeSorting}
                    />
                    <SelectionState
                        selection={this.state.selection}
                        onSelectionChange={(selection) => { this.changeSelection(selection, event) }}
                    />

                    <IntegratedFiltering />
                    <IntegratedSorting />
                    <IntegratedSelection />
                
                    <VirtualTable cellComponent={this.Cell} />
                    <TableColumnResizing
                        columnWidths={this.state.columnWidths}
                        onColumnWidthsChange={this.changeColumnWidths}
                    />
                    <TableHeaderRow allowResizing allowSorting />
                    <TableFilterRow
                        cellComponent={FilterCell}
                    />
                    <TableSelection
                        showSelectAll
                    />
                    
                </Grid>
            </Paper>
        </div>;
    }
```

Is it possible to still obtain if shift was held down during click? This is the event I capture currently, which is vastly different than the typical react-click event I used to receive.

```
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: false
path: [react]
returnValue: true
srcElement: null
target: null
timeStamp: 111886806.14000002
type: "react-invokeguardedcallback"
```

devextreme-reactive: 1.0.0-beta.3
react: 16.2.0
browser: Chrome/Firefox
material-ui: 1.0.0-beta.25

**Comment by kvet** [comment]
Hi,

The solution you used contradicts the way the Grid works. The SelectionState plugin isn't linked to the DOM. So, to catch DOM events, you need to provide custom components to UI plugins and handle them manually.

To capture clicks within the checkbox, it is required to override the cellComponent property of the TableSelection plugin. Use the rowComponent property of the Table/VirtualTable plugin to capture clicks within a table row.

If you need any assistance with this, feel free to contact us.
