### ISSUE TITLE
Question : Change the handler of DetailRow

### ISSUE THREAD

**Issue by fridezlucas** [DevExpress/devextreme-reactive#643]
Is it possible to change the handler for show/hide the RowDetail and how ?

The simple arrow isn't very UX friendly and I want to click to the complete line to show/hide the complete RowDetail

**Comment by MaximKudriavtsev** [comment]
Hi,
 
You can achieve this by passing the `onClick` handler to the Table.Row component.
You need to use the [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) and change `expandedRows` in the `onClick` event handler as demonstrated in the [example](https://www.webpackbin.com/bins/-L2OSk5wh4UQ7CSyTXQM).
