### ISSUE TITLE
VirtualTable messages prop produces error "Cannot update during an existing state transition"

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#649]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
VirtualTable plugin takes a messages object prop. When using it, we get this message:
Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

### Expected Behaviour
We should not get any errors when using this prop.

### Steps to Reproduce (for Bugs)
Create a table with a VirtualTable as follows:
`
        <VirtualTable
          messages={{ noData: "No data" }}
        />
`

### Your Environment

devextreme-reactive: 1.0.0-beta.3
react: 16.2.0
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.27

**Comment by kvet** [comment]
Hi,
 
Thank you for bringing this to our attention. I've reproduced the issue. We will fix it.
 
As a workaround, I suggest you extract the messages object constant and place it outside the render function if it is possible. It will suppress redundant rendering and this will also increase performance in general as we use PureComponents.
