### ISSUE TITLE
Choosing a pre-formatted field from your data source to display in the grid...

### ISSUE THREAD

**Issue by dsibiski** [DevExpress/devextreme-reactive#664]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

@gsobolev I had brought up my use case earlier today in an old PR, here is my explanation for what I was talking about...

NOTE: I'm currently using Beta 2 of the Grid.

My use case it that I have some data that I am pre-formatting and passing to the grid:

```javascript
const rows = [
  {
    id: '0',
    createdAt: 1515589744375,
    createdAtFormatted: '2018-01-10 09:09 am'
  },
  ...
];
```

(of course, this is very basic and there are other fields that I want to do this with as well, have a raw data field that can be easily sorted, and a formatted version to be displayed)

I was trying to use a custom `DataTypeProvider` `FormatterComponent` to get the other rows value and display it, something like this:

```javascript
const DateFormatter = ({ column, row }) => (
  <span>{row[column.name + 'Formatted']}</span>
);

// Later in my grid...

<DataTypeProvider
  type="date"
  formatterComponent={DateFormatter}
/>
```

However, of course, the `row` isn't available in the `FormatterComponent` just the `column` and `value`.

I understand that I could just have my actual date formatting code right there in the `DateFormatter`, however I'd rather have that type of code in another function that is much easier for me to test. (also, this is a trivial example and there is other data similar to this that is much more critical to test as to the formatting of it)

Is there a nice clean alternate way to do this using the current API of the grid? Is there a way to perhaps get the `rowId` at least so that I could look up the formatted field on my own data and render it that way?

**Comment by gsobolev** [comment]
@dsibiski,
 
I attempted to reproduce your scenario in the [following example](https://stackblitz.com/edit/react-qpeaed?file=index.js) but did not face any problems though. Am I still missing anything?

**Comment by dsibiski** [comment]
Wow, I am so sorry for wasting your time! I could have sworn that I had tested and that I was not getting back a row into the DateFormatter function.

Must have been a long day or something heh...

**Comment by dsibiski** [comment]
@gsobolev After going back to my app, I found that the "row" object is only included when the field is NOT grouped. That is my problem...I am grouping some of these fields and that is where the row doesn't make it through, once I ungroup it, it works. Is this perhaps a bug?

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
