### ISSUE TITLE
Server side rendering with devextreme and material ui?

### ISSUE THREAD

**Issue by kkotwal94** [DevExpress/devextreme-reactive#671]
After refreshing the page (and going through my ssr) it looks like none of the css is sustained unless I navigate through my app and get back to it. Are there any examples of how this is done correctly?

Im using the exact same code from the controlled 'react material ui grid' example:

https://github.com/kkotwal94/DrivingService <- (in develop branch) where the component is under components / demoGrid, and the SSR is under server/render/pageRender.jsx. I use the material ui example for how this is done. I utilize demo grid in Students.jsx.

Here is a pic of what happens post refresh: 
![image](https://user-images.githubusercontent.com/8924340/34913058-97d86032-f8c0-11e7-8d6a-c452213f08bb.png)

Everything else renders fine (all other pages) in production mode and dev mode. I have no clue what im missing here.

**Comment by SergeyAlexeev** [comment]
Hi,
 
Thank you for your interest in our product! I just tested how the React Grid works with Next.js and Material UI and it all works fine as described  [here](https://github.com/mui-org/material-ui/tree/v1-beta/examples/nextjs). I could not find any problems or UI issues.

**Comment by kkotwal94** [comment]
Hmm maybe I can produce a working example and host it later today, I'm not sure what i'm doing differently. But after looking around some more I realized most of my material-ui css is not syncing right (jss tags are mismatched with SSR on refresh). I downgraded back to react 15 and all seems good, however I can't use the grid on 15. I will do some more experimentation later today.

**Comment by SergeyAlexeev** [comment]
Yes, you are right.

**Comment by kkotwal94** [comment]
http://transportation.kkotwal.me/
I hosted it, if you click on login  you can log in with yea@yea.com, password: 123, or you can just sign up where the username has to be a email it doesnt matter. After wards if you navigate to the students button on the navigation (if you click on transportation tracker after logging in you should be back to the root page / view). You will see the dev extreme controlled grid example. If you hit refresh on that page you will see all the css is messed up. In case you arent sure what the page is: http://transportation.kkotwal.me/students. The source is here: https://github.com/kkotwal94/DrivingService/tree/UpdateReact . The server side rendering is located https://github.com/kkotwal94/DrivingService/tree/UpdateReact/server/render. The component for the devExtreme component is called DemoBase.jsx in the components folder, and the container that renders this is https://github.com/kkotwal94/DrivingService/blob/UpdateReact/app/containers/students/Students.jsx.

Thanks for all the help. I don't use next js in my application.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification. I tried to run your project locally and debug your code, but I could not. There are some problems with the database connection. It would be great if you provide us with a small example that demonstrates the issue. In this case, we will be able to research the problem further.

**Comment by kkotwal94** [comment]
I will try to make a smaller example right before work, sorry about that.

If you can do this (assuming this isnt too difficult), this is how you run it (If not I can just create a small example before work, later today). Just apt-get install psql, set up your user, set up password, create database SchoolTransportation.

Update this file with your credentials: https://github.com/kkotwal94/DrivingService/blob/master/server/db/postgres/sequelize_config.js

If you want to test production bundle locally, change the sitename to your localhost instead of transportation.kkotwal.me here: 
https://github.com/kkotwal94/DrivingService/blob/master/config/app.js

then:
npm install sequelize -g

> sequelize db:migrate
> sequelize db:seed:all

then just run npm run-script build:dev, then npm run-script dev. and it should be the same as the site in dev mode. npm run-script start to run in prod mode.

**Comment by kkotwal94** [comment]
@SergeyAlexeev is there any version that is compatible with under react 16?

**Comment by SergeyAlexeev** [comment]
Under the hood, our Grid uses [React.Fragment](https://reactjs.org/docs/fragments.html) that isn't compatible with React 15. 

We're still researching your problem. We'll update this thread when we have any news.

**Comment by kkotwal94** [comment]
No problem, I think this has more to do with react 16 and hydrate rather then your library.

**Comment by kvet** [comment]
Hi,

I've researched the issue and found the cause. First of all, it is not strongly related to the DevExtereme React Grid. And I am not sure that it is related to the Material UI library.

To reproduce it without the Grid, change the following string:

```js
import Paper from 'material-ui/Paper';
```

with this one:

```js
import { Paper } from 'material-ui';
```

After this change, the page stops working correctly with SSR markup. As an assumption, the problem may be in the server or client configuration. Or, it may be related to issues with tree-shaking. @oliviertassinari, have you faced such an issue before?

To solve this problem, we can change all imports in our sources to those like in your project. It will also improve the bundle size and application start time.

**Comment by oliviertassinari** [comment]
> have you faced such an issue before?

@kvet Never.

**Comment by kvet** [comment]
We've released the [1.0.0-rc.2](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-rc.2) version containing the fix. You can try it out.

**Comment by oliviertassinari** [comment]
What was the root cause? Anything actionable here?

**Comment by kvet** [comment]
As far as I understand, the `index.js`, and `index.es.js` files are executed differently. We didn't notice this on other projects that we've tested. It is likely to be a problem with the SSR configuration.

Anyway, the related PR contains a fix for the issue though it was created to minimize the bundle size.

**Comment by oliviertassinari** [comment]
Oh wait, we release the modules twice! https://unpkg.com/material-ui@1.0.0-beta.30/es/
I think that I will remove this es folder. The more Material-UI external projects grow, the bigger the pain will be: conflicting class names + bloated bundle.

**Comment by oliviertassinari** [comment]
Unless we encourage all the external dependencies to use the non es version of the libraries, we should be good. Ok, simpler solution, let's keep the es folder :).

**Comment by oliviertassinari** [comment]
@kvet You made the right call with #684 👍 .

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
