### ISSUE TITLE
Styling the Material-UI TableSelection checkbox 

### ISSUE THREAD

**Issue by danmolitor** [DevExpress/devextreme-reactive#673]
I've looked in many different issues and the code itself trying to see examples of how to change styling. I would like to change the out of the box coloring that comes from the class '.MuiCheckbox-checked-139' to a color of my choosing. The default color is '#3f51b5'. 

I was hoping it would be as simple as passing 'className' to TableSelection, but that didn't seem to be what I was after. As far as implementing the TableSelection cell myself, I've gotten as far as 

```
<TableSelection
    cellComponent={(props) => {
        return (
            <TableSelection.Cell>
                {props.children}
            </TableSelection.Cell>
       );
   }}
/>
```

Correct me if I'm wrong, but from the looks of it I believe I would somehow have to reimplement the selection logic if I did that. 

Main question: What is the best practice for what I'm trying to do?

As a side note, there are great examples for basic usage, but it's pretty difficult for me personally to understand how to use the Plugin Developer References - how to go about implementing / utilizing Imports, Exports, etc. - Is there more in depth documentation on that or is it just simpler than I'm thinking it is? 

Thank you!

**Comment by MaximKudriavtsev** [comment]
Hi,

In your example you don't to pass rest props to our component.

```
<TableSelection
  cellComponent={({ row, selected, onToggle, children }) => {
    return (
      <TableSelection.Cell
         row={row}
         onToggle={onToggle}
         selected={selected}
      >
         {children}
      </TableSelection.Cell>
    );
 }}
/>
```

 
Please see [Appearance Customization](http://localhost:4000/devextreme-reactive/react/grid/docs/guides/grid-basics/#appearance-customization) examples. For information on the props the `TableCelection.Cell` component accepts, see this [section](http://localhost:4000/devextreme-reactive/react/grid/docs/reference/table-selection/#tableselectcellprops).

A simple way to override custom MUI styles is to use 'MuiThemeProvider'. Follow this [guide](https://material-ui-1dab0.firebaseapp.com/customization/themes/).

This [example](https://stackblitz.com/edit/react-jpaexj?file=index.js) demonstrates a simple method to override a custom palette. If your application has a single palette, use 'MuiThemeProvider' for the root app element.

Thank you for your feedback about documentation. We are working on it.

**Comment by danmolitor** [comment]
Okay, thank you. That was very helpful!
