### ISSUE TITLE
How to edit field added when use function createRowChange ?

### ISSUE THREAD

**Issue by Linh-Vu** [DevExpress/devextreme-reactive#675]
Hi,
I have a case like https://github.com/DevExpress/devextreme-reactive/issues/391. But i don't edit on field in line new. 
Please help me this case.
Thx for your helps ;)

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your interest in our product! We need more information to understand your problem. Please describe it in greater detail.

**Comment by Linh-Vu** [comment]
Hi, @MaximKudriavtsev 
I use version beta 2. 
`<EditingState
        createRowChange={createRowChange}
        columnExtensions={columnExtensions}
        editingRows={editingRows}
        onEditingRowsChange={changeEditingRows}
        changedRows={changedRows}
        onChangedRowsChange={changeChangedRows}
        addedRows={addedRows}
        onAddedRowsChange={changeAddedRows}
        onCommitChanges={commitChanges}
      />`
when i add new item to table like this.
![capture](https://user-images.githubusercontent.com/13365871/35041094-25e96914-fbb6-11e7-92f8-f481e472d82f.PNG)
i don't insert value to field on new item. Please help me this case . thanks

**Comment by MaximKudriavtsev** [comment]
Thank you for the clarification, but this information is still insufficient. Can you please share the full Grid configuration? For example, you can create a project in https://stackblitz.com/.
 
Additionally, please clarify what exactly you mean in the following statements.
- "But i don't edit on field in line new." - Are you unable to edit fields in a new row?
- "i don't insert value to field on new item." - Are you unable to save a new row?
