### ISSUE TITLE
Question : FilterInput outside the datatable

### ISSUE THREAD

**Issue by fridezlucas** [DevExpress/devextreme-reactive#688]
Is it possible to create a custom input and integrate it outside the datatable to filter it ?

**Comment by stclairdaniel** [comment]
Yep! Wrap the table in a custom class and provide a filter prop that comes from your custom input. Provide this prop to the FilteringState plugin. Are you doing client-side or server-side filtering? I can help out if you have any issues.

**Comment by fridezlucas** [comment]
Ok, Thank you !

I want to do a client-side pour string search and a server-side search for others (like categories, etc...).

Also, I want to move the input for string search outside of the Table!

**Comment by stclairdaniel** [comment]
Server search is simple - on input change, call your data GET API and pass new data into the table.

For client search, on input change, return an array like this:
`filters: [{ columnName: 'car', value: 'cruze' }],` and pass it into the table as a prop (you'll want to wrap the table in your own component)

Then in the table, use the FilteringState like so:
` <FilteringState filters={this.props.filters} />;`
