### ISSUE TITLE
Remove CommandComponent on a per row basis?

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#689]
I feel like this is possible but I couldn't understand how from the docs. I'd like to conditionally not show the CommandComponent for certain rows in the TableEditColumn (say for a RO object). It looks like I should be able to accomplish this using a cellComponent in the TableEditColumn, but I have no idea how to render the CommandComponent inside the cellComponent. Sorry if I am missing something obvious.

**Comment by kvet** [comment]
Hi,

We don't currently have a simple API to complete this task, but it is possible to do this with a React API. Here is an example: https://stackblitz.com/edit/react-xhtyh6?file=index.js

**Comment by stclairdaniel** [comment]
Fantastic! That's exactly what I was looking for :)

**Comment by ramneet-chopra** [comment]
> Hi,
> 
> We don't currently have a simple API to complete this task, but it is possible to do this with a React API. Here is an example: https://stackblitz.com/edit/react-xhtyh6?file=index.js

Thank you so much for posting this.
