### ISSUE TITLE
Edit DateTime Material-UI controls overlay adjacent column

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#691]
- [x I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Using the React Grid component ...

When in edit mode, I have a Material-UI TextField (type='date-time-local') to edit a date. However part of the controls hover over the next adjacent cell. For example the controls with the downward-triangle so that I can open the calendar view of the TextField. But because part of the DateTime control overs over the adjacent cell - when I try to click the downward triangle, the datetime cell loses focus as I am now actually hovering over the adjacent cell, so I can't click it.

### Expected Behaviour

Even though part of the DateTime control is hovering over the next adjacent cell, I still want to be able to make full use of the Material-UI DateTime control, and be able to click the far-right icons like the downward triangle to open the calendar view.

### Your Environment

@devexpress/dx-react-core: 1.0.0-rc1
@devexpress/dx-react-grid: 1.0.0-rc1
react: 16.2
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.30

**Comment by SergeyAlexeev** [comment]
Thank you for reporting the issue.
 
I reproduced it without our Grid. Please refer to this [sample](https://stackblitz.com/edit/react-7z1emv?file=index.js).
 
As you can see, the first TextField looks good in my sample. I fixed it using the styles as follows:

```js
<TextField
  style={{
    display: 'block'
  }}
  InputProps={{
    style: {
      display: 'block'
    }
  }}
  // ...
/>
```

You can use the same approach on your side.

Also, I created the similar [issue](https://github.com/mui-org/material-ui/issues/10018) in the Material UI repo.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
