### ISSUE TITLE
Make Virtual Table fill height of page

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#697]
Hey guys,

just a question regarding the Virtual Scrolling table. 

Since it seems to need an absolute set height is there an elegant way of making it fill the entire page (i.e. the available height). I guess its doable manually with refs after the DOM has rendered but is there a clever way to do it?

An example would be awesome!

Thanks

**Comment by tpisto** [comment]
Hi! You can use AutoSizer from react-virtualized package.

  <AutoSizer>
    {({ height, width }) => (
      <Grid ...>
       <VirtualTable height={height}/>>
     <Grid/>
    )}
  </AutoSizer>

**Comment by terndrup** [comment]
Thanks for the response, but Im trying to avoid having to install another package to achieve this

**Comment by natenrb9** [comment]
@tpisto when I try to use AutoSizer it returns a height/width of 0/0 at first (seeing via console.log) , but then it does return the correct height/width but the div that AutoSizer inserts is not updating...?

<div style="overflow: visible; height: 0px; width: 0px;"></div>
