### ISSUE TITLE
How to make row unavailable for selection?

### ISSUE THREAD

**Issue by andrispraulitis** [DevExpress/devextreme-reactive#699]
Question not issue.

I have used cellComponent prop for TableSelection component to hide checkbox for selection, BUT how do I actually mark such rows as unavailable for selection on select all checkbox ?

Would appreciate if someone can advise. Thanks

**Comment by stclairdaniel** [comment]
I'm not 100% sure but I'd be willing to bet it's similar to [this issue](https://github.com/DevExpress/devextreme-reactive/issues/689)

**Comment by andrispraulitis** [comment]
@stclairdaniel No I don't think so, I'm talking about select all checkbox in header row first column. Please see attached screenshot:
<img width="1331" alt="screen shot 2018-01-25 at 18 17 27" src="https://user-images.githubusercontent.com/8721800/35404868-4ff51180-01fc-11e8-8f3e-9195176d5bc1.png">

I have hidden checkbox for rows should not be allowed to select, but how do I now fix select all checkbox? I can of course use redux to do the same logic I do for hiding checkbox, but then select all checkbox won't work when you want to deselect because I manipulate in reducer that only 3 selected so next time you hit select all it thinks only 3 selected and wants to select the remaining 2.

**Comment by kvet** [comment]
Hi,

I've prepared an example with a possible solution: https://stackblitz.com/edit/react-yfrctq?file=index.js.

**Comment by andrispraulitis** [comment]
@kvet This is exactly what I needed. Thank you!

**Comment by andrispraulitis** [comment]
Hi @kvet, your example no longer works with version 1.8.0. Was still working fine with version 1.7.2. Whats changed?

**Comment by SergeyAlexeev** [comment]
Hi @andrispraulitis,

I've updated your [sample](https://stackblitz.com/edit/react-44mgbv?file=index.js). The `PluginContainer` component was renamed to `Plugin`. We [introduced](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#breaking-changes-3) this change in the 1.0.0 version.

**Comment by andrispraulitis** [comment]
No the issue was that this was undefined inside Getter computed
