### ISSUE TITLE
Move TableEditColumn from leftmost column to rightmost column

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#700]
As far as I can tell, I can't specify the placement of this column. Perhaps there's some config to do so, but I'm unable to locate anything about it. Help as always is appreciated!

**Comment by SergeyAlexeev** [comment]
Please, refer to the similar issue #287 

See the updated [sample](https://stackblitz.com/edit/react-xuq9ov?file=index.js) as well.

**Comment by stclairdaniel** [comment]
Thank you! I didn't notice that issue when searching. I appreciate the sample and the quick response. Our table is really looking great these days :)
