### ISSUE TITLE
Edit Row content in TableRowDetail

### ISSUE THREAD

**Issue by msteinmn** [DevExpress/devextreme-reactive#706]
I'd like to edit fields in the TableRowDetail contentComponent. How can I lift state that represents entered text from the RowDetail component back up?  I would need a onDetailContentRowUpdate function as part of the component props.

**Comment by MaximKudriavtsev** [comment]
Hi,

If I understand you correctly, you want to change a row's data from the TableRowDetail plugin. This [example](https://codesandbox.io/s/o9zmnyxj0z) demonstrates how to implement this.
You can see all your changes logged in the browser's console. Just replace the `console.log()` command with a call of the `setState` function to change the state.

**Comment by msteinmn** [comment]
That was very helpful. Works perfectly. Thanks.
