### ISSUE TITLE
column filters -> filter by dropdown list. 

### ISSUE THREAD

**Issue by bstumpexb** [DevExpress/devextreme-reactive#708]
### Expected Behaviour
for column-level filters, there should be an autocomplete dropdown textbox that helps me select items from the list. I would be able to scroll from the list to select the item.

**Comment by SergeyAlexeev** [comment]
Hi,

You can implement such a functionality using the `cellComponent` property of the [TableFilterRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/) plugin.

This [demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#customizing-filter-row-appearance) shows how it can be achieved.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
