### ISSUE TITLE
Hello. Is there an option to specify a fixed column and upon scrolling horizontally, the specified column would just stay unscrolled.

### ISSUE THREAD

**Issue by madhan-dhamodaran** [DevExpress/devextreme-reactive#709]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by MaximKudriavtsev** [comment]
Please, refer to the similar issue #293
