### ISSUE TITLE
Use Plugin > Exports like changeColumnFilter or changeColumnSorting?

### ISSUE THREAD

**Issue by natenrb9** [DevExpress/devextreme-reactive#711]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

How do you use Plugin > Exports, for example: changeColumnFilter or changeColumnSorting?

I have attempted a number of different ways to implement these, but they are not working, and I have scoured the docs and demos for any example user and can't find any...

Thank you for any help you can provide.

**Comment by kvet** [comment]
Hi,

Thank you for the question. We are currently working on complete documentation. As for now, I can recommend you see the following example: https://stackblitz.com/edit/react-16nodl

You can connect Getters and Actions with the help of the TemplateConnector component. The first argument in the TemplateConnector's children function is an object with all available Getters and the second one with Actions.

**Comment by natenrb9** [comment]
Awesome, thanks, that will come in handy.

Unfortunately, it looks like the 2 actions I was trying to use, don't accomplish what I was wanting. I want to just eliminate filtering/sorting on certain columns, and those action descriptions made it sound like that is what they do ("Set direction to null to cancel sorting by the current column." and "Pass null to the config argument to remove the filter associated with the specified column.") But I guess they simply are for real time calls.

How can I completely remove sorting/filtering from certain columns? I have searched high and low 
(docs and demos) and can't find if there is a way to do it...

**Comment by kvet** [comment]
We are working on the described features. You may see them in the pull requests list.

**Comment by kvet** [comment]
Hi,

I'm closing the issue as a duplicate. See original issues:
- disable column sorting: https://github.com/DevExpress/devextreme-reactive/issues/363
- disable column filtering: https://github.com/DevExpress/devextreme-reactive/issues/777
