### ISSUE TITLE
React grid crashes in IE 11

### ISSUE THREAD

**Issue by dmtrKovalenko** [DevExpress/devextreme-reactive#715]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
React grid is crashing in IE. Got the following error `cannot read property filter of undefiend or null refenrence`
Its caused by method `getColumns` during rendering.

![b00c3598-3e28-4072-8161-083d7c8dadd7](https://user-images.githubusercontent.com/16926049/35682306-ea126a76-0768-11e8-8789-b71ab42a3690.jpg)

### Expected Behaviour
It should not crashes in the IE11 

### Steps to Reproduce 

Here is a repo with example I have used to reproduce the bug - https://github.com/dmtrKovalenko/react-grid-ie

Note that I have included all possible pollyfills using pollyfill.io (in index.html)
P.S.: I have no ability to create a sandbox because it does not work in IE :(

### Your Environment

devextreme-reactive: 1.0.0-rc.2
react: 16.2.0
browser: IE 11.786
material-ui: 1.0.0-beta.31

**Comment by kvet** [comment]
Hi,

I've replaced the polyfill with the following one: https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js. The Grid works well.

**Comment by josser** [comment]
Looks like bug in Polyfill.io service
https://github.com/Financial-Times/polyfill-service/issues/1390

**Comment by dmtrKovalenko** [comment]
Thank you! Problem was fully fixed
