### ISSUE TITLE
HELP！

### ISSUE THREAD

**Issue by cjiang-object** [DevExpress/devextreme-reactive#719]
Excuse me, why do I use gird1.0.0-rc.2?

Error: Uncaught TypeError: Cannot read property 'charAt' of undefined.

I am a little confused, looking forward to your reply!

**Comment by SergeyAlexeev** [comment]
Hi,

It's currently difficult to understand what is going wrong. Would you please provide more details about your project?
I mean the `dx-react-grid-bootstrap3` or `dx-react-grid-material-ui` grid package, plugins that you are using to configure the Grid, etc. A browser version would be useful as well.

**Comment by cjiang-object** [comment]
dx-react-grid-material-ui  @devexpress/dx-react-grid-material-ui": "^1.0.0-rc.2" this's i used , i don't think the problem is here. Do I need to introduce other dependencies and whether I need to upgrade my material- UI?Excuse me for the trouble.

**Comment by cjiang-object** [comment]
Thank you very much. That's because the material- UI version is too low. I was too careless. I think you can write more clearly about other environments that your component depends on so that others can use it more easily. Thanks again for your reply.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
