### ISSUE TITLE
How do I sort comparing values from another column?

### ISSUE THREAD

**Issue by andrispraulitis** [DevExpress/devextreme-reactive#721]
Question.

I have a date column, date filter works fine BUT I want to use different row prop for sorting. Is that possible?

**Comment by SergeyAlexeev** [comment]
Hi, 
 
Currently, our Grid doesn't provide it out of the box. As a workaround, you can sort rows manually:

```js
changeSorting = (sorting) => {
  const { rows } = this.state;
  // Sort rows here...
  this.setState({ rows: sortedRows, sorting });
}
render() {
  return (
    <Grid
      //...
    >
      <SortingState
        sorting={sorting}
        onSortingChange={this.changeSorting}
      />
    </Grid>
  );
}
```

We will discuss the possibility of implementing such a functionality. It would help if you describe your scenario in greater detail. Would you please clarify why you sort rows by a column and take other columns into account? At first sight, it looks a bit unusual.

**Comment by andrispraulitis** [comment]
Hi, I simply have an array of data and want to display and filter by date added, but it may happen that date/time is exact second which is why sort needs to happen by database id.

**Comment by SergeyAlexeev** [comment]
OK, I've got it!

Thank you for the clarification.

**Comment by andrispraulitis** [comment]
No example yet?

**Comment by SergeyAlexeev** [comment]
Answered [here](https://github.com/DevExpress/devextreme-reactive/pull/692#issuecomment-369146581).

**Comment by andrispraulitis** [comment]
@SergeyAlexeev 
Thanks but that example is how to disable sorting on particular column. What I'm looking for is how to use a different column value for sort (see my comment re date vs database id issue). Was that not implemented in pull #692 ?

**Comment by SergeyAlexeev** [comment]
#692 isn't related to this issue.
 
As I pointed [above](https://github.com/DevExpress/devextreme-reactive/issues/721#issuecomment-363058682), you can sort rows manually.
 
I've created a [sample](https://codesandbox.io/s/7m5mp34no6) that demonstrates how to implement this.

**Comment by andrispraulitis** [comment]
If I understand correctly you created an example that will sort by ID when you click City column. If that is the case (which I need) then your example does not seem to work.
