### ISSUE TITLE
Column Freeze Plugin? 

### ISSUE THREAD

**Issue by datadidit** [DevExpress/devextreme-reactive#722]
Hi, 

Found your lib through the material-ui-next docs. It's great so far but wanted to know if there's a plugin available for `column-freeze`(scroll horizontally but 1st column stays stationary)?

Have google with no luck so far: http://lmgtfy.com/?q=column+freeze+devextreme-reactive+react

Also apologize in advance if this is not the correct issue type for a question.

**Comment by SergeyAlexeev** [comment]
Hi,
 
Currently, our Grid doesn't provide such a functionality. We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/293). You can follow it and check the progress.

**Comment by datadidit** [comment]
@SergeyAlexeev thanks for getting back to me. Enjoy your weekend.
