### ISSUE TITLE
Custom components inside the Toolbar 

### ISSUE THREAD

**Issue by omarwagih** [DevExpress/devextreme-reactive#723]
Is there a straightforward way to get a component inside the toolbar? 
I'd like to have an icon button component next to the column visibility icon in the toolbar.

**Comment by omarwagih** [comment]
Solved using the `Plugin` component. This example implements a button that toggles the filter row in the header. 

 
```
import React from 'react';
import PropTypes from 'prop-types';

import {
  Template, TemplatePlaceholder, Plugin, TemplateConnector,
} from '@devexpress/dx-react-core';


import IconButton from 'material-ui/IconButton';
import Tooltip from 'material-ui/Tooltip';
import FilterListIcon from 'material-ui-icons/FilterList';
import ClearIcon from 'material-ui-icons/Clear';



function FilterToggle(props){
  const { toggleFilter } = props;

  return (
    <Plugin name="FilterToggle">
      <Template name="toolbarContent">
        <TemplatePlaceholder />
        <TemplateConnector>
          {({}) => (
            <React.Fragment>
              <Tooltip title='Toggle filter' placement='bottom' enterDelay={300}>
                <IconButton onClick={toggleFilter}>
                  <FilterListIcon />
                </IconButton>
              </Tooltip>

            </React.Fragment>
          )}
        </TemplateConnector>
      </Template>
    </Plugin>
  );
}
```

**Comment by fonzy2013** [comment]
@omarwagih Can you please share the complete example? I tried with the above but I couldn't get the FilterListIcon to show...

**Comment by fonzy2013** [comment]
I solved it. `<FilterToggle` needs to be after the `<Toolbar` in the jsx decleration.
I vote for having this functionality native to the library. I bet a lot of people want it

**Comment by FGCorp** [comment]
@fondberg can you share an example of your useage.i try the above code but cant figure out where to use FilterToggle.

**Comment by aurigajamesparry** [comment]
Any suggestions in order to remove the default flexible div in the default toolbar

**Comment by christianjoun** [comment]
you can achieve this by creating a plugin "x" that uses the template 'toolbarContent' and omit the <TemplatePlaceHolder />. Make sure "x" is the first plugin after <Toolbar/>

Oddly enough, this plugin will remove the default flexible div and insert myFlexibleDiv.
 
<Plugin name="ToolbarPushRight">
      <Template name="toolbarContent">
        <TemplateConnector>
          {({}) => (
            <div id="myFlexibleDiv" style={{ flex: '0 0 0px', marginLeft: 'auto' }}></div>
          )}
        </TemplateConnector>
      </Template>
    </Plugin>

**Comment by slava-lu** [comment]
This Plugins solution does Not place a " ..component **next** to the column visibility icon in the toolbar." It replaces the  column visibility.  How can I have both myComponent and `ColumnChooser` inside the toolbar?

**Comment by ushkal** [comment]
@slava-lu  I can't reproduce the issue on my side. Would you please modify [this sample](https://codesandbox.io/s/mz8jj0vp69) to reproduce it?

**Comment by MaximKudriavtsev** [comment]
@yotamberk

To render custom markup inside the left side of the Toolbar, you should create a custom plugin.
 
See the [example](https://codesandbox.io/s/l5rjjpkljm).
