### ISSUE TITLE
PagingPanel containerComponent totalPages prop not outputting correctly

### ISSUE THREAD

**Issue by Rid** [DevExpress/devextreme-reactive#727]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
In `<PagingPanel />` the `containerComponent` props currently output `totalPages` as `NaN`

### Expected Behaviour
`<PagingPanel />` to output `totalPages` as the total number of pages

### Steps to Reproduce (for Bugs)

We're currently using it in this context, with a custom Pager component:

```javascript
<PagingPanel
  pageSizes={allowedPageSizes}
  containerComponent={({ totalPages, getMessage }) => (
    <Pager
      currentPage={currentPage - 1}
      totalPages={totalPages}
      allowedPageSizes={allowedPageSizes}
      pageSize={pageSize}
      onCurrentPageChange={this.changeCurrentPage}
      onPageSizeChange={this.changePageSize}
      totalCount={totalCount}
      getMessage={getMessage}
    />
  )}
/>
```

### Your Environment

devextreme-reactive: 1.0.0-rc.2
react: 16.2.0
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.31

**Comment by Rid** [comment]
Current work around is to call `pageCount` directly:

```javascript
<PagingPanel
  pageSizes={allowedPageSizes}
  containerComponent={({ getMessage }) => (
    <Pager
      currentPage={currentPage - 1}
      totalPages={pageCount(totalCount, pageSize)}
      allowedPageSizes={allowedPageSizes}
      pageSize={pageSize}
      onCurrentPageChange={this.changeCurrentPage}
      onPageSizeChange={this.changePageSize}
      totalCount={totalCount}
      getMessage={getMessage}
    />
  )}
/>
```

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for reporting the issue, but I can't reproduce it on my side. Would you please modify this [sample](https://codesandbox.io/s/ojzkojkm0q) to demonstrate the problem?

**Comment by Rid** [comment]
I can't reproduce it, I'll check my Pager code again, there must be an issue there.
