### ISSUE TITLE
Empty table and fetching data appearance customization

### ISSUE THREAD

**Issue by acentfrio** [DevExpress/devextreme-reactive#732]
Good evening, I was wondering if is it possible to render custom component inside a table instead of 
"No data" text when table is empty or when data is fetching from backend.

Any help will be appreciated!

**Comment by artem-kurchenko** [comment]
Hi,

You can use the noDataRowComponent/noDataCellComponent property to complete this task (see [Table Plugins](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#plugin-components). 
I've also created an example to illustrate a basic implementation of this idea 
https://stackblitz.com/edit/react-5kyinp
**See also** 
[Fundamentals - Appearance Customization](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/)

**Comment by lin-zy1229** [comment]
Improved code:
```
({ colSpan }) => (
	<td colSpan={colSpan} style={{ textAlign: 'center' }}>
		<big className="TableNoDataCell">Empty Data</big>
	</td>
)
```
