### ISSUE TITLE
Are Multi-Row Headers (Bands) supported?

### ISSUE THREAD

**Issue by hernanavila** [DevExpress/devextreme-reactive#733]
Hello, I need to collect two or more data columns under one column header and wondering if multi-row headers (band columns) are supported. 
I found this functionality in the DevExtreme DataGrid widget but not sure how to get the same behavior with DevExtreme React Grid.

source:  https://js.devexpress.com/Documentation/Guide/Widgets/DataGrid/Columns/Column_Types/Band_Columns/

Thanks in advance,
Hernán.-

**Comment by gsobolev** [comment]
Hi,
 
Thank you for your suggestion. We are planning to implement this feature in future versions.

**Comment by kvet** [comment]
We've released the [1.2.0](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.2.0) version containing described changes.
