### ISSUE TITLE
Is it possible to add a custom `<tfoot />` or a custom row inside the rendered table?

### ISSUE THREAD

**Issue by rmariuzzo** [DevExpress/devextreme-reactive#734]
Is it possible to add a custom `<tfoot />` or a custom row inside the rendered table? My scenario is a data table with several number columns, and the last row is a summary.

I have seen the use of `Template` and `headerPlaceholderTemplate` but both seems to allow to add an extra custom row in the end or a `<tfoot />`.

Is that possible right now?

**Comment by kvet** [comment]
Hi,

Currently, it is not possible to add a table foot element with a custom row. However, there is a capability to add a row at the end of the table and display summaries for data columns. Here is an example: https://codesandbox.io/s/o4m8o4xlj9

**Comment by rmariuzzo** [comment]
Thank you for your quick reply, do you know if that summary row will not be affected by filtering?

**Comment by rmariuzzo** [comment]
Just tested, and the filtering works as expected.

Modified example with row filtering: https://codesandbox.io/s/4ry9r1o8o9

![filtering](https://user-images.githubusercontent.com/439839/35998828-26db2a52-0cf4-11e8-887c-3d666559abc2.gif)

**Comment by rmariuzzo** [comment]
@kvet I'm figuring I could sum all values in a column and put it on the summary. Is it possible to sum all values from **visible** rows and add it to that summary?

**Comment by kvet** [comment]
Yes, it is possible. I've prepared an example: https://codesandbox.io/s/km8yzyjx0r. Just replace summary calculation with your custom one.

**Comment by rmariuzzo** [comment]
Awesome @kvet, thank you!
