### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by msteinmn** [DevExpress/devextreme-reactive#736]
I ran into some performance issues with a test setup involving a table with 35 columns, thereof 7 displayed, and about 500 rows of data. UI response time became unacceptably sluggish with lots of re-renders when parent props change, including consistent re-renders of Command Cells.  All this without changing the data that is displayed in the grid. I am wondering whether there are some best practices to control rendering, including the use of shouldComponentUpdate inside the component tree, as well as best practices for instrumentation to assess component performance.  

Release 1.0.0, material-ui beta 31, react 16.2
Thanks.

**Comment by kvet** [comment]
Hi,

We use React best practices. We can't tell you about new techniques if you are familiar with the following guide: https://reactjs.org/docs/optimizing-performance.html

The most typical problem that may slow down the performance of the React Grid is inlining complex objects in the render method. React Grid uses PureComponents, so it's optimized for scenarios where the state is not changed frequently.

We didn't also optimize React Grid to work with a large number of columns as we don't know use cases with such requirements. There is a Column Visibility feature: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-visibility/

I can detail more potential problems, but it may not be effective. Can you share your setup and describe problems you faced with? It will greatly reduce time to understand your issue and will give us a basis to write a performance guide with the most typical problems and solutions. Or, it may be a bug.

**Comment by msteinmn** [comment]
Thanks for the response. This was my fault. There was a problem elsewhere in my code.

**Comment by andrispraulitis** [comment]
Hi, I'm also experiencing performance issues with setting state on input change. State change is extremely slow when render contains grid.

**Comment by mikeethantien** [comment]
Hi, I am working on a project which requires 30+ columns, and I am experiencing quite a performance hit due to the number of columns I have. I understand that this wasn't optimized, and am just wondering if this would be an improvement in the near future. Thanks very much.
