### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by stefensuhat** [DevExpress/devextreme-reactive#746]
```
{!all || fetching ? <div /> :
 <Grid
            rows={items}
            columns={columns}
        >
            <CurrencyTypeProvider for={currencyColumns} />
            <PagingState
                currentPage={meta.current_page}
                onCurrentPageChange={() => handleChangePage}
                pageSize={meta.per_page}
            />
            <CustomPaging
                totalCount={meta.total}
            />
            <Table
                cellComponent={Cell}
            />
            <TableHeaderRow />
            <PagingPanel/>
        </Grid>
}
```

I have those code above. currently I'm try to using remote paging. 

but those code always return me those error.

my default meta key: `meta: { total: 0, per_page: 15, current_page: 0 },`

If I remove `<PagingPanel />` it works like charm (without paging of course). 

Environment: React 16.2, Material-UI latest beta, latest React Grid

**Comment by gsobolev** [comment]
Hi,
 
I'm unable to reproduce the behavior you are facing with. Besides, the configuration you provided does not seem to contain any issues. Would you please provide more details about your project?
In addition, check out our [Remote Paging demo](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/paging/#remotepaging).

**Comment by stefensuhat** [comment]
my bad. I mistakenly open my project. I opened project with old material ui beta. it works like charm!
