### ISSUE TITLE
Render several items (like MUI chips) in a table cell

### ISSUE THREAD

**Issue by msteinmn** [DevExpress/devextreme-reactive#758]
Like you demonstrate for the Custom Editors example on the Data Formatting page, I'd like to use Material-UI chips to render cell content using the cellComponent prop for VirtualTable. However, I have several chips I'd like to enter and display per cell. 

The row input data structure fed to the Grid seems to require key / value pairs of type string, or at least a non-nested data structure. My data structure includes a nested Object that represents the values for the Chips. 

When using such a data structure as row input to the grid I first get a warning: Warning: Failed prop type: Invalid prop `children` supplied to `TableCell`, expected a ReactNode. And then an error: Uncaught Error: Objects are not valid as a React child (found: object with keys {1, 2}). If you meant to render a collection of children, use an array instead.

I also tried this with a nested array of objects with the same result.

Is there a possible work-around or an example of how to do this in case I am missing somethig?

**Comment by msteinmn** [comment]
Asking a question seems to help. Just using a simple nested array works, not an array of objects or an object, just an array of strings. I was able to create a formatter like so based on the example here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-formatting/

`const GatewayFormatter = ({ value }) => {
  return (
    <div>
      { value ? (value.map(gateway => <Chip label={gateway} />)) : null}
    </div>
  );
};`

I still struggle with the editor to allow entering strings. And I'd like the cell content to wrap to the next line, so that the Chips align vertically.

**Comment by gsobolev** [comment]
Hi!
 
You need to pass a custom component that will render an editor for your field to the `editorComponent` property of the [DataTypePropvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) plugin to enable editing.
To customize a cell's content implement your own cell component and pass it to the `cellComponent` property of the [Table](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/) plugin.
 
I have prepared an [example](https://codesandbox.io/s/rr8kp0x054) demonstrating how to achieve the required behavior.

**Comment by msteinmn** [comment]
Your examples are awesome and extremely helpful. Would it make sense to allow a data structure where a nested array of objects is allowed in an row object?  To render such a cell will require a custom component anyway, and this way more data could be provided that also would allow creating a rowDetail component.

I stumbled into this twice now where my db Schema includes nested objects or arrays of objects and I don't seem able to use them directly as row data.

**Comment by gsobolev** [comment]
I suggest you take a look at the [Data Accessors guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/data-accessors/) demonstrating the possibilities of working with custom structured data.
