### ISSUE TITLE
Question  regarding slow filtering

### ISSUE THREAD

**Issue by fondberg** [DevExpress/devextreme-reactive#760]
I am evaluating dexextreme-reactive Grid table for a large customer and have a question.

Enviromnent:
```
"react": "^16.0.0",
 "material-ui": "^1.0.0-beta.31",
"@devexpress/dx-react-core": "^1.0.1",
"@devexpress/dx-react-grid": "^1.0.1",
 "@devexpress/dx-react-grid-material-ui": "^1.0.1",
``` 
Data:
I have around 2000 rows that I rely heavy on a custom cellComponent for enhancing the UI with JSX elements and it is painfully slow when I filter.

My JSX looks like this:
```
return (
      <Grid
        rows={projects}
        columns={columns}
      >
        <FilteringState defaultFilters={[]} onFiltersChange={this.filterChange} />
        <PagingState
          defaultCurrentPage={0}
          defaultPageSize={25}
        />
        <SortingState
          defaultSorting={[{ columnName: 'id', direction: 'asc' }]}
        />

        <IntegratedFiltering />
        <IntegratedSorting />
        <IntegratedPaging />

        <Table
          columnExtensions={tableColumnExtensions}
          cellComponent={Cell}
        />
        <TableHeaderRow showSortingControls />
        <PagingPanel />
        {this.state.showFilters
          ? <TableFilterRow />
          : null}
        <TableColumnVisibility defaultHiddenColumnNames={['owners']} />
        <Toolbar />
        <ColumnChooser />

        <FilterToggle toggleFilter={this.toggleFilters}/>
      </Grid>
    );
```  

I see that for every keypress in the filter input for a column I see the following behaviour:
```
filterChange: [{…}]
63 x   Cell component
112 x   Cell component
filterChange: [{…}]
28 x   Cell component
147 x   Cell component
filterChange: [{…}]
21 x   Cell component
154 x   Cell component
filterChange: [{…}]
175 x   Cell component
``` 
The number before the Cell component is the number of times it was called.

What I would like is a delay such as lodash debounce for keypresses. 
If I need to implement controlled filtering I would like to see a complete example as I think the uncontrolled examples are great and will make this library easily usable for our developers.

**Comment by kvet** [comment]
Hi,

I see that you show a large set of rows and columns. You can use the VirtualTable or Column Visibility features to reduce the number of currently visible rows.

As for the filter debouncing, the controlled mode will not help you if you are using one of integrated data processing plugins. However, I could provide you with a solution that will work with the remote and integrated data processing. Here is an example: https://codesandbox.io/s/13omrmp5pj

**Comment by fonzy2013** [comment]
Thanks fir the response. 
I tried with VirtualTable (same) and less columns (better but still slow).
I can try the remote one but in all honesty, I don't have that many records and it would be swell to have something in the provided library. Can you discuss amongst yourselves if this could be provided?

**Comment by kvet** [comment]
I am not sure that remote filtering will help you. As far as I understood, you have heavy markup inside cells. If so, the Grid takes a long time to render. I mean this is without applying a filter.

We have a demo with 200K rows. There are filtering and complex markup within cells. It works well. Maybe you should try to simplify cell markup? You can also provide us with an example with you cell markup. We may help you solve the problem.

**Comment by fonzy2013** [comment]
I tried both... the filtercell denounce and making the cell mark up
shorter. It is ok but I still don't understand why my custom cell is called
for every keystroke. Sometimes twice as shown in my example.

I can share the code if you want but need a place to send it.

Rgds
Niklas

Den 21 feb. 2018 14:33 skrev "Yury Orlov" <notifications@github.com>:

**Comment by kvet** [comment]
As I see, you are using the controlled mode. It may force redundant rendering if you inlined complex objects (arrays and objects) and components in the render method.

You may share your private code in our [Support Center](https://www.devexpress.com/ask).
