### ISSUE TITLE
How to set column width

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#761]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I can't figure out how to set a column width. One of my columns needs to be slightly wider to support rendering my datetime control properly without cropping off some of the control.

I read something about using TableHeaderRow.Cell - but I just can't see an example anywhere on how I could use this, to say set the width of a column called 'timestamp'.

### Your Environment

devextreme-reactive: 1.0.1
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0

**Comment by artem-kurchenko** [comment]
Hi,
 
You can use the [columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/) property of the Table plugin to complete this task. 
For instance, review the following example - https://codesandbox.io/s/k058l2p2x5

**Comment by joergd** [comment]
Ah - that's great - thank you
