### ISSUE TITLE
Cursor jumps to the end after changing an editor value in controlled mode

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#762]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

When editing a column/textfield - say I insert a character in the middle of the existing word (like Paris on your docs page in the controlled example: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/) - after insertion, the cursor jumps to the end of the textbox.

### Expected Behaviour

The cursor should not jump to the end of the textbox, as it won't allow me to add two characters without having to reset the insertion point.

### Steps to Reproduce (for Bugs)

Go to your docs to the controlled example - and change "Paris" to "Pahris"
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/

### Your Environment

devextreme-reactive: 1.0.1
react: xxx
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0.beta33

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. We're going to research if it's possible to overcome the issue at the control level. Please bear with us.
