### ISSUE TITLE
Pass additional property to formatterComponent

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#763]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I need to format a currency column, and am successfully using the DataTypeProvider. Is there a way to pass in the currency symbol to my formatterComponent - the currency symbol is not available on the row data, but on the 'parent' data node, so would need to pass it into the formatter (via the data provider I assume). Is this currently possible? I couldn't find a way.

So something like this:

    <CurrencyTypeProvider for={['currencyAmount']} currencySymbol='USD' />

### Your Environment

devextreme-reactive: 1.0.1
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by joergd** [comment]
Well - let's use another example. Say I have a formatter to format numbers, and I want to be able to pass in that the number should have say 2 decimal places, or 5 decimal places. Each column may have a different need.

My workaround for now is to have a separate datatypeprovider for both 2 and 5 decimal places (eg `Number2DecimalTypeProvider` and `Number5DecimalTypeProvider` ... which works, but is clumsy.

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification! The approach you are using is recommended for now. We'll discuss the possibility of improving it in the future.
