### ISSUE TITLE
<Table cellComponent={Cell} /> receives values before DataTypeProvider

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#764]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I have a DataTypeProvider that transforms my raw value to say a localString formatted value.

I also have a custom Cell component for my Table, so that I can colour the value either red or green depending on whether the value is negative or positive.

This all works fine independently - but when I use both components together, I find that the Cell component receives my unformatted values - as opposed to my formatted values.

So now my values are colour-coded but are missing the formatting.

          <CurrenyTypeProvider for={['currencyAmount']} />
          <Table cellComponent={Cell} />

### Expected Behaviour

Expect my custom cellComponent to receive my formatted values - as opposed to the raw values.

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by gsobolev** [comment]
The `value` parameter contains a raw cell value by design. Use the `children` parameter in your custom `Cell` component to achieve the required behavior like in the code sample below.

```jsx
const Cell = ({ children, value, ...restProps }) => (
  <Table.Cell {...restProps}>
    <span style={{
      color: value >= 1000 ? 'green' : 'red'
    }}>
      {children}
    </span>
  </Table.Cell>
);
```

**Comment by joergd** [comment]
Ah ok yes - that works too - thank you - this is really helpful!
