### ISSUE TITLE
Right align some columns

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#765]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I have some columns that contain currency values, and I would like to right-align those columns so that they read better. How would I achieve this?

### Your Environment

devextreme-reactive: 1.0.1
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by gsobolev** [comment]
Hi!

You can define column align via the `columnExtensions` property of the Table plugin.

```js
const tableColumnExtensions = [
  { columnName: 'rightAlignedColumn', align: 'right' },
];
```
```jsx
<Table
  columnExtensions={tableColumnExtensions}
/>
```

See more about `columnExtensions` in the [reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumnextension).

**Comment by joergd** [comment]
Hey that worked - thank you. :)

As an aside - I find that references page (and all API pages) very difficult to understand...
