### ISSUE TITLE
Striped table

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#768]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

It would be nice to have the ability to stripe the rows.

It's really difficult to be able to create CSS in react using pseudo selectors, like

    tbody tr:nth-child(odd) {
       background-color: #ccc;
    }

Therefore I imagine the solution is not providing a way to pass in a class to the underlying table (I don't think this is possible yet anyway), but that it is something that would have to be done internally in a declarative way.

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by MaximKudriavtsev** [comment]
We have already registered a similar [issue](https://github.com/DevExpress/devextreme-reactive/issues/627). You can follow it and check the progress.
