### ISSUE TITLE
[Help needed] Installation with both Material-Ui version

### ISSUE THREAD

**Issue by remy-poirier** [DevExpress/devextreme-reactive#770]
Hello,

I want to integrate this library, but I was using Material-Ui v.0.20, so I read the migration guide and installed both versions:

* `material-ui v.0.20` is referenced as **material-ui**
* `material-ui v.1.0` is referenced as **material-ui-next**

And it doesn't work, the console pops a lot of errors like:

```
Module not found: Error: Cannot resolve module 'material-ui-icons/List' in C:\workspace\app\node_modules\@devexpress\dx-react-grid-material-ui\dist
```

And I don't understand, the library should have material-ui v.1.0 in its own dependencies and load the good files, no ?

If not, do I have to add some config to specify the good path ? 

Am I missing something ? I hope there is a viable solution, because I am working on a big project, and it takes time to completely remove `material-ui v.0.20`

**Comment by MaximKudriavtsev** [comment]
Hello,

The `@devexpress\dx-react-grid-material-ui` package depends on [material-ui](https://material-ui-1dab0.firebaseapp.com/getting-started/installation/)@`next` and `material-ui-icons`. Two installed versions of `material-ui` can lead to errors.

**Comment by tkostus** [comment]
Hello

Think you need to alias material-ui@next as material-ui and material-ui@0.20 as something else - otherwise dx grid will not find the necessary components. That's our setup and it works fine.
