### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by JayathmaChathurangani** [DevExpress/devextreme-reactive#772]
I am not getting the expand icon (triangular icon) when using column grouping and I am getting the following errors in the console.

Failed to load resource: the server responded with a status of 404 (Not Found)   glyphicons-halflings-regular.woff2 
Failed to load resource: the server responded with a status of 404 (Not Found) glyphicons-halflings-regular.woff 
Failed to load resource: the server responded with a status of 404 (Not Found)  glyphicons-halflings-regular.ttf 

How to solve this?

**Comment by kvet** [comment]
Hi,

The issue is not related to DevExtreme Reactive. I recommend you check your bundle tool configuration for issues.
