### ISSUE TITLE
Question: can EditingState Plugin/Changeset provide my object ids, instead of grid id/index/position

### ISSUE THREAD

**Issue by jbuschke** [DevExpress/devextreme-reactive#774]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Question

Is it possible (and if so how) to make the EditingState plugins **ChangeSet** to give me the actual id's of modified/deleted objects instead of the index/position the changed elements had in the grid?
For example I have objects/rows

```
[
 { id: "00000000-0000-0000-0000-000000000001",value:"foo"},
 { id: "00000000-0000-0000-0000-000000000002",value:"bar"}
]
```

and the EditingState onCommitChanges will give me a Changeset that looks like this:
```
{
  changed: { 0:  { value: "modified value" } }
}
```
or
```
{
  deleted: [ 1 ]
}
```
Instead of above behaviour I would like to get my actual id's like this:
```
{
  changed: { 00000000-0000-0000-0000-000000000001:  { value: "modified value" } }
}
```
or
```
{
  deleted: [ "00000000-0000-0000-0000-000000000002" ]
}
```

**Comment by gsobolev** [comment]
Hi,
 
You need to specify the Grid's `getRowId` property which is a function returning a unique row identifier.
 
```js
const rows = [{ id: 1, value: "one" }];
const getRowId = row => row.id;
```
```jsx
<Grid
rows={rows}
getRowId={getRowId}
// other properties
>
{ /* Grid plugins */ }
</Grid>
```
