### ISSUE TITLE
New/Edit Dialog 

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#775]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

How would I implement bringing up a custom dialog for my new and edits .. instead of having the editing fields inside a row?

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by gsobolev** [comment]
Hi,
 
Currently, there is no built-in capability to implement the required behavior. Yet, this can be implemented manually. Consider using a state management library (e.g., Redux) for this purpose. Please take a look at the sources of the [Redux Integration demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/redux-integration/) for more details.

**Comment by joergd** [comment]
Ok cool - thank you. My app uses redux anyway - so that part is understood - my grid is a controlled grid. I'm still not sure though how to proceed?

Say I wanted the same Edit/Delete links on the command column - can  I still use these? I'm not sure what state I need to look out for that they have been clicked for example. Or do I need to create a custom command column - and use my own Edit/Delete buttons where I can listen out for the onClick and bring up a special dialog box?

Would I still access the EditingState plugin if I have my own dialog box? I can't see that this plugin would be any use for me.

The way I see it currently working is, that I would use NONE of the current plugins (EditingState, TableEditRow, TableEditColumn), and would need to figure out how to create my own command column - and use my own state to manage the whole edit/new process - and not use any of the existing state the grid provides, right?

**Comment by gsobolev** [comment]
Right. The first option for you is not to include any of our Editing plugins at all and use your own state for managing all the data editing process.
But there is another way which is to implement a custom Grid plugin responsible for displaying a popup (e.g. EditingPopup) instead of the TableEditRow plugin usage. If you need any further assistance regarding this option, feel free to contact us.

**Comment by joergd** [comment]
So option 1) would mean I need to create a custom command column with my own edit/delete buttons and a custom toolbar for the New button. So the only integration really with the Grid would be the custom command column?

Option 2) sounds interesting too - though would require a LOT MORE knowledge of the grid itself I imagine? I'll take a look at the code for TableEditRow as a start? It would be similar to that plugin - in terms of the grid integration?

**Comment by gsobolev** [comment]
Option 1. Yes, it is exactly like you describe it.
 
Option 2. Again, you are on the right track. The `TableEditRow` plugin sources are a nice point to start from. But to make the start easier, I have prepared an example with a basic implementation of the popup editing plugin, which can be found [here] (https://codesandbox.io/s/n9m2ky1r04). Note that only editing existing rows is supported in the demo.

**Comment by joergd** [comment]
Hey that's great - thank you! I'll take a look and see how you did it.

**Comment by joergd** [comment]
Ok I maybe half understand that code - and looking at it - and the code for TableEditRow, I still can't figure out how to handle the New functionality. For example, when I click the New button the toolbar - it just disappears now - with no error - but not sure where to declare that this EditPopup needs to appear the way it does with the Edit button. Any clues will be greatly appreciated it - almost there to having a functioning Dialog :)

**Comment by gsobolev** [comment]
The ids of currently editing rows and new rows are stored in separate arrays. But in the demo code. the Popup `open` property is set only depending on the `editingRowIds` array. So you just need to modify the code as shown below:
 
```jsx
<TemplateConnector>
  {(
    {
      addedRows,
      /* other getters */
    },
    { /* actions */ }
  ) => {
    const rowId = editingRowIds[0];
    const open = editingRowIds.length > 0 || addedRows.length > 0;
    /* ... */
  }}
</TemplateConnector>
```

**Comment by joergd** [comment]
Ah ok yes - I can see how that works - cool thanks - makes sense.

**Comment by joergd** [comment]
Now - when I Add a row, it opens fine - but when I eg want to cancel/apply changes - it does nothing. So it calls the `cancelChanges` method ok, but now I assume that the code in there needs to be made specific for added rows too?

I found a reducer method called `cancelAddedRows` which I can get from the second argument to the TemplateConnector (same place as `stopEditRows`). But when I pass in my added rows, and my rowIds as the second argument - it does nothing really - well the dialog box still doesn't close.

    const cancelChanges = () => {
      cancelAddedRows(addedRows, { rowIds: [0] })
      // stopEditRows({ rowIds: editingRowIds });
    };

My new rows don't have ids - so as the 'id' I am just passing in the index 0 ...

Anyway - I am still really struggling to figure out now how to make it work for Adding too - but not really having much luck. Again - can you point me in the right direction please?

**Comment by gsobolev** [comment]
The `cancelAddedRows` action accepts only one parameter as described in our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#imports). So you just need to call it the following way:

```js
cancelAddedRows({ rowIds: [0] });
```

**Comment by gsobolev** [comment]
No, there is no special method for this. So, the approach you described should work well.

**Comment by joergd** [comment]
Ok great thanks - I've just been using that method and it's been fine so far.

**Comment by james-tiqk** [comment]
I can put validation in onCommitChanges, however not sure how to keep the popup open in the plugin. Any ideas?

**Comment by gsobolev** [comment]
@james-tiqk,

The popup is closed when there are no rows available for editing. This happens after the `stopEditRows` action is called. I suggest you place the validation algorithm in the `applyChanges` handler. Then call the `stopEditRows` and `commitChangedRows` actions only if validation is passed.

**Comment by kzeman** [comment]
Pls, I need a help... I made my example with edit dialog, but I still have problems to find solution for NEW item dialog. I used similar template from `https://codesandbox.io/s/n9m2ky1r04` , but I can not find, how to use `addRow `action to fill `addedRows `array. There is a part of my Template:

```
         <TemplateConnector>
            {(
              {
                rows,
                getRowId,
                createRowChange,
                rowChanges,
                isColumnEditingEnabled,
                addedRows
              },
              {
                changeRow,
                addRow,
                commitAddedRows,
                cancelAddedRows
              }
            ) => {
              const rowId = 0;
              const open = addedRows.length > 0;
              const targetRow = rows.filter(row => getRowId(row) === rowId)[0];
              const changedRow = { ...targetRow, ...rowChanges[rowId] };
              const processValueChange = (fieldName, newValue) => {
                const changeArgs = {
                  rowId,
                  change: createRowChange(changedRow, newValue, fieldName)
                };
                changeRow(changeArgs);
              };
              const applyChanges = () => {

               //addRow(addedRows, ?);
                commitAddedRows({ rowIds: [0] });

              };
              const cancelChanges = () => {
                cancelAddedRows({ rowIds: [0] });
              };
              return (
                <Popup
                  open={open}
                  row={changedRow}
                  onChange={processValueChange}
                  onApplyChanges={applyChanges}
                  onCancelChanges={cancelChanges}
                />
              );
            }}
          </TemplateConnector>
  
```
