### ISSUE TITLE
[Question] Showing a combination of Plain Rows and Detail Rows in the same table

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#780]
When creating a Table/Grid is it possible to have a combination of plain rows and details rows?

In the following example, I have multiple tiers of nested data. I have managed to create a table that can show either TableDetails or plain Table depending on the number of rows in the dataset. (Lines 94 - 96)

What I'm attempting to do is remove the need for TOP-LEVEL 2 so that I can show BOTTOM-LEVEL 2-1 on the same 'tier' as TOP-LEVEL 1, but without an expander/collapser/toggler to the left.

Code: https://codesandbox.io/s/1vwlo0029j

**Comment by kvet** [comment]
Hi,

We don't have such built-in functionality, but it is possible to achieve it with a simple workaround: https://stackblitz.com/edit/react-dm4bxe?file=index.js

**Comment by thehig** [comment]
That is 100% awesome. Thank you so much, it would have no doubt taken me hours of trial-and-error to come up with that
