### ISSUE TITLE
how can i customize TableHeaderRow.Cell hover color

### ISSUE THREAD

**Issue by RahavLussato** [DevExpress/devextreme-reactive#781]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
the class `.MuiTableSortLabel-root-226:hover` manipulate it to be black.

### Expected Behaviour
have a simple way to override this class,
i tried to do it by using the example below but it seems to be not inner enough as `.MuiTableSortLabel-root` class and it changing only the regular color and not the hover one.

```
const styles = {
    customHeaderCell: {
        color: '#ffffff',
        fontSize:13,
        fontWeight:'bold',
        '&:hover': {
            color: '#ffffff',
        }
    },
};

<TableHeaderRow.Cell
            className={classes.customHeaderCell}
            {...props}
/>
```

**Comment by gsobolev** [comment]
Hi,

Thank you for bringing up this problem. Currently, there is no straightforward solution. As a workaround, I suggest you use a more specific CSS selector in the `customHeaderCell` class definition. Please see [this example](https://codesandbox.io/s/x3062779r4).
Anyway, we will consider this problem in the future.

**Comment by RahavLussato** [comment]
@gsobolev thanks
