### ISSUE TITLE
Set column default sort direction

### ISSUE THREAD

**Issue by andrispraulitis** [DevExpress/devextreme-reactive#782]
Question

Hi,

Is it possible to set default direction per column for the first click?

**Comment by andrispraulitis** [comment]
@SergeyAlexeev 

Lets say you have not set default sorting on any of the columns. The first click on sorting column is always ascending, is it possible to set that to be descending for particular columns? Take demo as example [here](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/) amount or date columns. First click is always ascending but I would want those 2 columns to be descending when you click the first time.

**Comment by andrispraulitis** [comment]
<img width="669" alt="screen shot 2018-02-28 at 11 44 24" src="https://user-images.githubusercontent.com/8721800/36786016-cb9f7164-1c7c-11e8-9cf6-0189ca389477.png">

Is this the only way to achieve it?

**Comment by SergeyAlexeev** [comment]
Thank you for your clarification. Currently, your scenario can be implemented as described in this [sample](https://codesandbox.io/s/5w982vv8ml).

**Comment by andrispraulitis** [comment]
Thanks.
