### ISSUE TITLE
[Question] Asp.net MVC serverside data aggregation support 

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#783]
Hi,
This might not be the right place to ask this question, but does React Grid support server side data aggregation for Asp.net MVC, just like Kendo does? (https://www.telerik.com/kendo-react-ui/components/dataquery/mvc-integration/) Not sure if DevExtreme support this. I haven't found any documentation related to serverside data grid aggregation yet. Any help or insight will be appreciated!

**Comment by SergeyAlexeev** [comment]
Hi,
 
Currently, we don't provide any server-side data processing utilities for React Grid. Of course, you can prepare data on the server using ASP.NET MVC and then pass it to the React Grid. For example, we have a [sample](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping#remote-grouping) that demonstrates how to implement server-side grouping using the [CustomGrouping](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/custom-grouping/) plugin.
