### ISSUE TITLE
Wrong column order when grouping grid with over 10 columns

### ISSUE THREAD

**Issue by tpisto** [DevExpress/devextreme-reactive#786]
### Current Behaviour

If you *have over 10 columns* AND you have enabled TableColumnReordering, the grouping behaves wrong:

Initial grid:
![screen shot 2018-02-28 at 16 41 12](https://user-images.githubusercontent.com/226244/36793671-a9e5a636-1ca6-11e8-8fdd-122d0e1f992f.png)

Column B grouped. The problem: Columns are reordering "randomly" and the grouped column is in weird position:
![screen shot 2018-02-28 at 16 41 45](https://user-images.githubusercontent.com/226244/36793680-b3367dc8-1ca6-11e8-88fc-b4e7b0c8a7d2.png)

### Expected Behaviour

If I have *10 or under 10 columns*  everything works perfectly:

![screen shot 2018-02-28 at 16 42 03](https://user-images.githubusercontent.com/226244/36793761-e3fa6168-1ca6-11e8-93ca-2123b3f799e3.png)

It should also work this same way for cases when you have over 10 columns.

### Steps to Reproduce (for Bugs)

Just create grid with following plugins (in this order):

Toolbar
SortingState
GroupingState
IntegratedGrouping
IntegratedSorting
FilteringState
IntegratedFiltering
DragDropProvider
VirtualTable
TableColumnResizing
TableHeaderRow
TableGroupRow
TableColumnReordering
GroupingPanel
TableFilterRow

AND, have over 10 columns in grid.

****

If I remove TableColumnReordering plugin, grouping works fine with over 10 column scenarios too. So something is wrong with TableColumnReordering and Grouping when over 10 columns...

****

devextreme-reactive: 1.1.0-beta.1
react: 16.0.0
browser: Chrome
bootstrap: yes
react-bootstrap: yes
material-ui: none

**Comment by kvet** [comment]
Hi,

I can reproduce the issue. We will prepare a fix with a minor priority as it has a simple workaround. Just place the TableColumnReordering plugin before TableGroupRow.

**Comment by tpisto** [comment]
Thank you! Indeed that workaround works very well. Issue is now resolved for me 👍
