### ISSUE TITLE
Hide column title from TableGroupRow.Cell

### ISSUE THREAD

**Issue by gerhat** [DevExpress/devextreme-reactive#793]
Hello!

Is there any way to hide the column name in custom grouping?

I would like to achieve the result of the first group in the image below:
<img width="863" alt="screen shot 2018-03-01 at 13 51 17" src="https://user-images.githubusercontent.com/11447903/36843485-c56c1e4c-1d57-11e8-8068-834f6fae8704.png">

I tried to nullify the column title and name properties (see code) but the colon wasn't removed.
```
<TableGroupRow.Cell
    {...props}
    column ={{title: null, name: null}}
>
    <img src="images/profile.png" /> {props.row.value}
</TableGroupRow.Cell>
```

The result was like this:
<img width="862" alt="screen shot 2018-03-01 at 13 57 24" src="https://user-images.githubusercontent.com/11447903/36843767-98555e40-1d58-11e8-9f0f-362bb7f24795.png">

Any way to resolve this?

**Comment by gerhat** [comment]
The workaround I currently use is to hide it via CSS. For example:
```
// grid.jsx
<TableGroupRow.Cell
    {...props}
    classes = {
        {columnTitle:'hideable-group-title'}
    }
>
    <img src="images/profile.png" /> {props.row.value}
</TableGroupRow.Cell>


//style.css
.hideable-group-title strong {
    display: none;
}
```

**Comment by SergeyAlexeev** [comment]
Hi, thank you for bringing our attention to this case. We'll consider how it can be improved.

**Comment by MaximKudriavtsev** [comment]
Hi,

As a workaround, you can use the [cellComponent](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-group-row-cell.jsx) propery of the `TableGroupRow` plugin. This [example](https://codesandbox.io/s/vy2rx4kl93) shows it in action.
