### ISSUE TITLE
Specifying column width in percentage

### ISSUE THREAD

**Issue by Jack-Works** [DevExpress/devextreme-reactive#795]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Now, columnExtensions sets width using <colgroup>, but how to set a relative width?
I didn't find a way of using flex or percentage.

### Your Environment

devextreme-reactive: 1.0.1
react: 16.2
browser: Chrome & Firefox
material-ui: 1.0.0-beta.35

**Comment by kvet** [comment]
Hi,

The Table plugin doesn't support percentage width for columns. It doesn't support a flex layout as it is built on the HTML table either.

As a workaround, I suggest adding a CSS rule. Here is an example: https://codesandbox.io/s/09pk0z8qv

**Comment by Jack-Works** [comment]
Cool, so I can use `withStyle` and add style to tableName col right?
Can you add this approach as a tool into code, or at least document it?

**Comment by kvet** [comment]
Yes, you can use `withStyle`. You will need to specify column index in the `nth-child(number)` selector.
 
I will change the issue from question to enhancement, and we will process it later.

**Comment by LazyLahtak** [comment]
Hi,

We have implemented this feature. To get more information see this [thread](https://github.com/DevExpress/devextreme-reactive/issues/411#issuecomment-532082958).
