### ISSUE TITLE
Stay in edit mode for specific row if row field is not valid

### ISSUE THREAD

**Issue by rpkRED** [DevExpress/devextreme-reactive#800]
Hi, if i click "new" button to add row and for that row i want to validate if some field has value or not or any other validation I have found this issue #475 . And by that logic row will not be saved but it will leave edit mode. Is it possible to stay in edit mode for that row?

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you manage added rows using the [controlled mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes#controlled-mode). I mean update the `addedRows` property of the [EditingState](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/editing-state/) plugin manually using the `onAddedRowsChange` property.

You can use this [sample](https://stackblitz.com/edit/react-xhqqvr?file=index.js) as a starting point. Please refer to comments in the code.

**Comment by rpkRED** [comment]
Thank you so much @SergeyAlexeev  it works. I just have one more additional question. Is it possible to get  all field values in added and changed row and not only ones that are actually changed?

**Comment by rpkRED** [comment]
One more question @SergeyAlexeev  is the logic same for edit button as well, cause I can't make it work for some reason?

**Comment by SergeyAlexeev** [comment]
Yes, but use the `editingRowIds` and `onEditingRowIdsChange` props instead. See the updated [demo](https://stackblitz.com/edit/react-2x9mpg?file=index.js) as well.
