### ISSUE TITLE
How to make Header sticky?

### ISSUE THREAD

**Issue by bendiy** [DevExpress/devextreme-reactive#806]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Scrolling down a page, the header scrolls out of the screen.

### Expected Behaviour
Have the header stick to the top of the window so it continues showing as you scroll far down the page.

### Your Environment
devextreme-reactive: 1.0.0
react: 16.2.0
material-ui: 1.0.0-beta.31

Is there any support for making the header sticky?

**Comment by kvet** [comment]
Hi,

I am afraid that HTML table doesn't support sticky positioning of its parts. So, the only way is to rewrite the table without using an HTML table. It will be possible once we merge the following PR: https://github.com/DevExpress/devextreme-reactive/pull/766
