### ISSUE TITLE
Question :: Row Y-Overflow or Wordwrap

### ISSUE THREAD

**Issue by mpolinowski** [DevExpress/devextreme-reactive#807]
[x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

The width of columns is fixed.

### Wanted Behaviour

Make content scrollable / add wordwrap to be able to add longer strings.

### Steps to Reproduce (for Bugs)

I found this Code sample and added some css to it to have scrollable content / also tried setting the width to auto, add word-wrap, etc. 

https://codesandbox.io/s/j3k2rqjql9

Does anyone know a proper solution for this? In my current project, I only have one column at 100%.

### Your Environment

"@devexpress/dx-react-core": "^1.0.3",
"@devexpress/dx-react-grid": "^1.0.3",
"@devexpress/dx-react-grid-material-ui": "^1.0.3",
"material-ui": "^1.0.0-beta.35",
"material-ui-icons": "^1.0.0-beta.35",

**Comment by mpolinowski** [comment]
I believe the default behaviour in Material UI is to use word wrap:
https://material-ui-next.com/layout/grid/#white-space-nowrap-

**Comment by kvet** [comment]
Hi,

Column widths are fixed and configured with no wrap in order to interoperate with various features. For example, the Grid with enabled paging will show records in the same viewport height across several pages with the same number of records.

As a workaround, I recommend you override cell styles. Here is an example: https://codesandbox.io/s/8y468jn740

**Comment by mpolinowski** [comment]
Hi,

thx @kvet this looks beautiful. I don't think that I am going to run into any problems with that, as I only needed a simple, elegant searchable list.

![reactgrid](https://user-images.githubusercontent.com/18694428/36974790-e5636684-20b2-11e8-82fe-2297badd41b4.png)


Thank you for your help!
