### ISSUE TITLE
How do i display more data in the same space, reduce the size of paddings, fonts and the size overall?

### ISSUE THREAD

**Issue by JureSotosek** [DevExpress/devextreme-reactive#808]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Displaying data with the Table is very space inefficient if you have a lot of data.

### Expected Behaviour

What is the best way to change the size of the table data to make it more space efficient/ to display more data in the same space. Do i change the font size, reduce the padding? What is the best way to do that?

**Comment by SergeyAlexeev** [comment]
Hi,
 
To reduce table cells' padding, you can override the [Table](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/) plugin's `cellComponent` property.
 
Do not forget to apply the same changes to the [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/) plugin to keep Grid UI consistent. Please refer to this [sample](https://codesandbox.io/s/p9j5jjxvvx).
 
If you are using the `dx-react-grid-bootstrap3` package, you can override styles for the table cell globally. This [demo](https://codesandbox.io/s/0mnxr1z2lv) shows how to do this. The index.html file contains custom styles.
