### ISSUE TITLE
How to add aggregation to grouped columns (like sum, avg, count) ?  

### ISSUE THREAD

**Issue by volkanakbas** [DevExpress/devextreme-reactive#813]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Hi, We are evaluating this table component and couldn't find a way to add aggregation to grouped column? 

### Expected Behaviour
Be able to set aggregate function to a column? For instance, if you have 
*Country
*State
*City
*Amount 
columns in your data set,  you group by Country and you have set the option for Amount column to be summed up when grouped by any column. When table is grouped by any column, it should show "Sum(amount)" as subtotals. 
Here is an example https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GroupSummaries/jQuery/Light/

**Comment by gsobolev** [comment]
Hi,
You can achieve the required behavior by implementing a custom Grid plugin. Please check the following [example](https://codesandbox.io/s/v31nj2q887) demonstrating the basics of such plugin implementation.

**Comment by carab** [comment]
Hello @gsobolev,

I have a similar case where I'd like to display the number of rows concerned by the group.
In your example I found that I can access those rows from `params.tableRow.row.collapsedRows`, but once the group is opened, `collapsedRows` is no more available and I can't seem to find how to get these.

Do you have an idea on how to do this ? `collapsedRows` should always be present ?

Thank you !

**Comment by gsobolev** [comment]
Hi @carab,
 
The `collapsedRows` property is available only for collapsed groups by design. It is a bit tricky to get both expanded and collapsed rows of a group, so I have created an example demonstrating how this can be achieved. Please find it [here](https://codesandbox.io/s/x2r4rq4vpw).

**Comment by carab** [comment]
Wow thanks for the example @gsobolev !
I see what you did and it is indeed a bit tricky, but it does the job ^^

Isn't it possible to simply always include the rows in `tableRow.row` ?
You say its because of the design that `collapsedRows` is not available when the group is opened, does it mean the design can't be easily changed ?

Thanks again for your help !

**Comment by gsobolev** [comment]
No, the design cannot be changed easily due to internal reasons. Anyway, we will consider your feedback in the future. Thank you for reaching out to us!

**Comment by carab** [comment]
Alright I understand ;)

Thanks again for your help !

**Comment by volkanakbas** [comment]
Is there anyway you can think of adding aggregates differently for each column? Example, I have 3 columns and want to implement avg, sum, count for each one respectively. Any idea how to go about adding this feature?

**Comment by jasper-lu** [comment]
I currently have aggregation working here to display averages for columns in the group now.
Is there a way for me to change what is exported in `<Template name="root">` in the `rows` parameter?
Right now, my data has 10 entries. When I add aggregation, there are 2 groups, so 12 rows get exported. 2 rows are of the format:
```
{
  groupedBy: <>
  key: <>
  ...
}
```
I want to add the aggregated column values to the row that is exported here. Is there a way I can do that?

I need this because I would like to access the aggregated value from a different section of the code, rather than reperforming aggregation elsewhere. Let me know if there is anything confusing. I can create a new thread as well.

**Comment by gsobolev** [comment]
Hi @jasper-lu,

You can define a [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) and override the `rows` parameter value:

```jsx
<Getter
  name="rows"
  computed={rowsWithAggregatedData}
/>
```

**Comment by Daemon-Knoppix** [comment]
Hi @gsobolev 
I tried your example for showing inner row count on grouped row (stated above in [this comment](https://github.com/DevExpress/devextreme-reactive/issues/813#issuecomment-372927293), [example url](https://codesandbox.io/s/x2r4rq4vpw)).

When i try to use the same code with latest devextreme-reactive packages of version 1.4.0 the code now does not show count only shows 0. If i open all collapsed rows it then shows count of Inner Rows. [updated example url](https://codesandbox.io/s/r0x3v5n8mm).

I can see that while using latest version 1.4.0 object `params.tableRow.row` does not contain key `collapsedRows`.

Can you provide any solution for the newer version of Grid? Also, is this feature still a workaround or implemented in new releases?

**Comment by gsobolev** [comment]
Hi @Daemon-Knoppix,

The provided solution is based on an internal API which has been changed. I have modified your example according to the updated API. Please find it [here](https://codesandbox.io/s/xrxr5nkp4o).

**Comment by desLT** [comment]
sorry to bother, but again the example is broken in v1.9
could you help me out... I love the way it's so easy to import a component and that thing does all the heavy lifting... but when I need custom behaviour... I get lost in the api docs...

As I see, I need a function param to count the rows (getCollapsedRows)... but according to chrome-debugger it never entered the TemplateConnector... and there I get lost  xD

I don't know how to pass the function or how to call it or where...

**Comment by MaximKudriavtsev** [comment]
@desLT 

I updated the [example](https://codesandbox.io/s/pk2nz5654m).
Also, you can use our build-in [Summary](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/summary-row/).

**Comment by fabiandeny** [comment]
Hi, I've seen the example in [here](https://codesandbox.io/s/pk2nz5654m)
But when I tried switching it to @devexpress/dx-react-grid-bootstrap4 as in [here](https://codesandbox.io/s/l4w45mw82q), I got error.
Is there a way I can use it with the bootstrap4 version?

Thanks

**Comment by MaximKudriavtsev** [comment]
Hi @fabiandeny,

You should install the required dependencies followed [Getting Started](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/#installation) guide. The [updated example](https://codesandbox.io/s/94xxn6jpxr).

**Comment by fabiandeny** [comment]
Thanks a lot @MaximKudriavtsev 
Got it working now
