### ISSUE TITLE
showSortingControls causes error with MaterialUI beta.36

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#825]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

After upgrading MaterialUI from beta.31 to beta.36, having

    <TableHeaderRow showSortingControls />

now causes the following error:

    helpers.js:29 Uncaught Error: Material-UI: capitalize(string) expects a string argument.
        at capitalize (helpers.js:29)
        at TableSortLabel (TableSortLabel.js:112)
        at mountIndeterminateComponent (react-dom.development.js:8032)
        at beginWork (react-dom.development.js:8221)
        at performUnitOfWork (react-dom.development.js:10224)

### Your Environment

devextreme-reactive: 1.0.0-beta.3
react: xxx
browser: Chrome
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0.-beta.36

**Comment by oliviertassinari** [comment]
This is related to https://github.com/mui-org/material-ui/issues/10557.

**Comment by oliviertassinari** [comment]
@kvet I believe the root of the issue is on this side:
https://github.com/DevExpress/devextreme-reactive/blob/cd459ade3be59205f0ef09397fec182047b8c67a/packages/dx-react-grid/src/plugins/table-header-row.jsx#L75-L76
`getColumnSortingDirection()` can return `null` which is not supported by the direction property Material-UI:
https://github.com/DevExpress/devextreme-reactive/blob/b5d0e2f04e639bfb26bff23b9b6eb9e296635bd5/packages/dx-react-grid-material-ui/src/templates/table-header-cell/sorting-control.jsx#L33-L35

**Comment by oliviertassinari** [comment]
Material-UI could add the support for the `null` value in the direction and warn when `direction=null` is used with `active=true`, but I'm not sure it will improve the current situation overhall.

**Comment by andrispraulitis** [comment]
But what is direction value when column not yet sorted? I always assumed that null, 'asc' and 'desc' are 3 possible values.

**Comment by oliviertassinari** [comment]
@andrispraulitis Why providing the direction anyway if the arrow isn't displayed?

**Comment by andrispraulitis** [comment]
How do you reset sort then?

**Comment by oliviertassinari** [comment]
> How do you reset sort then?

@andrispraulitis What about `active={false}`?

**Comment by andrispraulitis** [comment]
https://github.com/DevExpress/devextreme-reactive/blob/cd459ade3be59205f0ef09397fec182047b8c67a/packages/dx-react-grid-material-ui/src/templates/table-header-cell/sorting-control.jsx#L33-L42

Ok I see what you mean. So the actual fix then should be here on line 35 {direction || 'desc'} ?

**Comment by oliviertassinari** [comment]
> Ok I see what you mean. So the actual fix then should be here on line 35 {direction || 'desc'} ?

@andrispraulitis Or to make the `getColumnSortingDirection()` function returns `undefined` over `null`.

**Comment by andrispraulitis** [comment]
undefined won't work either, material will return the same error

**Comment by oliviertassinari** [comment]
> undefined won't work either, material will return the same error because capitalize helper specifically tests if value is string

@andrispraulitis Have you tried it out?

**Comment by andrispraulitis** [comment]
Yes I have

**Comment by oliviertassinari** [comment]
…

**Comment by andrispraulitis** [comment]
Ok my bad, you are correct

**Comment by vtrphan** [comment]
How can i fix this error as a user then??

**Comment by sanvie** [comment]
I have the same problem...
What I'm doing right now (waiting for a fix) is that I manually changed line 112 of TableSortLabel.js
by this...
(at least it stops crashing and I can work)

className: (0, _classnames2.default)(classes.icon, classes['iconDirection' + (0, _helpers.capitalize)(direction || 'asc')])

**Comment by kvet** [comment]
Hi,

Thank you for your report and detailed information about the fix. We are going to update the `material-ui` version with the next release. For now, I can only suggest downgrading the version to 1.0.0-beta.35
