### ISSUE TITLE
TableRowDetail toggle icon LTR

### ISSUE THREAD

**Issue by tomerpaz** [DevExpress/devextreme-reactive#827]
Hi, 
I want to adjust TableRowDetail toggle icon to RTL. need to flip the icon. Can it be done?
I'm using material-ui-next

Thank you. Tomer

<img width="608" alt="screen shot 2018-03-08 at 7 59 07 pm" src="https://user-images.githubusercontent.com/17382591/37167952-001e209e-230c-11e8-9c55-ac8a1c4cf2c0.png">

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, I suggest you follow [this](https://material-ui-next.com/guides/right-to-left/) guide. I've created a [sample](https://codesandbox.io/s/6wqr7xq4rz) as well.

**Comment by tomerpaz** [comment]
Thank you, 
I'm able to render RTL table as suggested. the only issue is with the icon, which needs to be flipped:
in instead of > it should be <.

I'm looking to implement: toggleCellComponent | ElementType<TableDetailToggleCellProps>.
Do you have an example how to accomplish that?

Thanks again, Tomer




I

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification. You can use the `ChevronLeft` icon within a custom toggle cell component. See the [updated](https://codesandbox.io/s/p3q5461vxj) sample.
