### ISSUE TITLE
Confirm delete

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#832]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

When pressing the delete button in the TableEditColumn, the row is deleted immediately. Is there a way to first ask for confirmation before deleting? 

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by kvet** [comment]
Hi,

Yes, it is possible. Please refer to the following demo: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/controlled-mode/

**Comment by joergd** [comment]
Ah perfect - thank you - that's really helpful.
