### ISSUE TITLE
Filter against formatted column values

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#833]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

I want to filter datetimes. My datetimes are unix timestamps. I use `DataTypeProvider` to format my unix timestamps as YYYY-MM-DD column values.

Now I want to filter my rows based on date - but I on'y want to pass in say YYYY, or YY, or YYYY-M etc . so I need to filter against the formatted values of my timestamps.

What would be the best approach for this?

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by kvet** [comment]
Hi,

It is possible to implement custom filtering logic. Here is an example: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/#using-custom-filtering-algorithms

**Comment by joergd** [comment]
Somehow missed this - works a treat thank you.
