### ISSUE TITLE
Fatal Bug when set TableHeaderRow showSortingControls

### ISSUE THREAD

**Issue by henryhuang** [DevExpress/devextreme-reactive#838]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Page can not be rendered caused by error:

Uncaught Error: Material-UI: capitalize(string) expects a string argument.
    at capitalize (static/js/bundle.js:195570)
    at TableSortLabel (static/js/bundle.js:187726)
    at mountIndeterminateComponent (static/js/bundle.js:214127)
...
static/js/bundle.js:223730 The above error occurred in the <TableSortLabel> component:
    in TableSortLabel (created by WithStyles(TableSortLabel))
    in WithStyles(TableSortLabel) (created by SortingControlBase)
    in RefHolder (created by Target)
    in Target (created by Tooltip)

### Expected Behaviour

No error

### Steps to Reproduce (for Bugs)

Following will get error:

```
<TableHeaderRow
    showSortingControls
/>
```

I use this code to avoid it, but default is **desc** forced,

```
<TableHeaderRow
    showSortingControls
    cellComponent={({ sortingDirection, ...props }) => {
    return <TableHeaderRow.Cell
        sortingDirection={sortingDirection || 'desc'} {...props}/>
    }}
/>
```

### Your Environment

devextreme-reactive: 1.0.3
react: 16.2.0
browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.37

**Comment by SergeyAlexeev** [comment]
Hi, 
 
Thank you for pointing that out. We already have a similar issue #825. The fix will be available with the next update, which will be published soon.
