### ISSUE TITLE
Column header with icons

### ISSUE THREAD

**Issue by ekaasatish** [DevExpress/devextreme-reactive#839]
Hi ,

I need to add some iconbuttons to the column header of devextreme react grid material ui , I am able to achieve that by writing a "cellComponent" in my "TableHeaderRow". However resize,reorder etc does not work on those column headers anymore(for eg: column "test" from screenshot ). I observed that with "TableCell","th" or anything other than "TableHeaderRow.Cell" this problem occurs .  Below is my code. Is there something that I am missing ?

        <TableHeaderRow
          cellComponent={tableHeaderCell}
        />

and my "tableHeaderCell" is below 

![image](https://user-images.githubusercontent.com/34710583/37398397-63da9198-27a4-11e8-9d80-a1b636eadab6.png)

and I am not able to do the below , the icon does not appear on the column header

![image](https://user-images.githubusercontent.com/34710583/37398981-42ef8a54-27a6-11e8-8a10-8105bccdb2e9.png)

**Comment by andrispraulitis** [comment]
I'm also interested in this. Column visibility chooser uses Toolbar which takes a lot of space, I want to replace 1 column title in header with column chooser

**Comment by ekaasatish** [comment]
Hello ,

So i found a work around to fix the issue,
I added a <TableCell> around the <TableHeaderRow.Cell> and it worked  , 
but it spoils the styles of the header  , 
which I guess could be fixed 

So 
So something like below would help

![image](https://user-images.githubusercontent.com/34710583/37506341-6b9bd98e-290f-11e8-938e-a5dfdce7ff93.png)


I am not sure if it is a good way of doing though , If someone know a better way of doing this , please do help us !

**Comment by Krijovnick** [comment]
Hi,
 
Currently, the 'TableHeaderRow.Cell' component doesn't support rendering nested HTML elements.
If you want to add a custom element to a table cell, it is necessary to use the 'TableCell' component or just the <th> element. As a disadvantage of this approach, it will not be possible to resize columns and change the sort order of a table. As for the workaround @ekaasatish provided, we examined it and did not find any possible way to overcome the mentioned errors. If you put the 'TableHeaderRow.Cell' component into the 'TableCell' one, markup will contain two nested <th> elements:
```
<th>
<th>
...
</th>
</th> 
```
Which is incorrect markup according to the HTML standard. You can see the related warning in a browser console.
We have also discussed this case and are going to research if we can support headers customization in further versions. Feel free to contact us if you have further questions.

**Comment by ekaasatish** [comment]
Hi @Krijovnick ,

Thank you for your reply.

Yes I observed that two <th> are getting added due to the code I have written, Is there any other correct way of doing this ? I understand there is no support for this kind of a feature right now , but is there any other correct work around for this for now ?

**Comment by Krijovnick** [comment]
There are two workarounds for now. 
1. If you need an icon without a click event, use jss pseudo selector ':before' for creating it. 
```
'&:before': {
      left: 55,
      top: 20,
      content: '"➕"',
      display: 'block',
      position: 'absolute',
    }
```
Resize columns and reorder of the elements will work as before.

2. You can use the 'TableCell' component and add iconButton into it. This approach will make resize columns and reorder elements not possible. So you should add the code to make it work.

The following [example](https://codesandbox.io/s/4qm8997vox) shows both approaches.

**Comment by andrispraulitis** [comment]
Hi, how to render ColumnChooser in header cell?

[example](https://codesandbox.io/s/oqlv93q2xq)

**Comment by ekaasatish** [comment]
Hello @Krijovnick ,

Thank you so much for the sample , that really helps !. But I do not see any grouping functionality in the material-ui (  https://material-ui-next.com/demos/tables/  ), but I want to be able to use all of the grid features that are available in the devextreme grid. Or am I missing something very obvious here ?

**Comment by Krijovnick** [comment]
Hi @ekaasatish,

If you want all of the grid features, you should implement them by yourself as reorder elements presented in the example above.

**Comment by ekaasatish** [comment]
Hello @Krijovnick ,

Sorry to bother you again , but there is no reorder implemented in the sample you shared. 
Only sort works , which is because of the "TableSortLabel" that is added from the material-ui ,but I do not see anything similiar for grouping in material-ui which is where I am stuck.

**Comment by SergeyAlexeev** [comment]
@ekaasatish Material UI doesn't provide a grouping control. You can see how it's [implemented](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/templates/table-header-cell/grouping-control.jsx#L50) in React Grid. We are using the `List` icon inside a clickable `div`.

**Comment by SergeyAlexeev** [comment]
@andrispraulitis Currently, the column chooser supports rendering only inside a toolbar.

**Comment by andrispraulitis** [comment]
@SergeyAlexeev Are you saying it is not possible to have a custom column chooser button at all?

**Comment by SergeyAlexeev** [comment]
@andrispraulitis  there isn't such a functionality out of the box. You can reuse the `ColumnChooser` plugin [components](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#plugin-components) to implement that. This [sample](https://codesandbox.io/s/3ro0yv2r06) shows how to do it.

**Comment by andrispraulitis** [comment]
@SergeyAlexeev Thanks for example, will have to work with what's possible but was looking for more simple way. On all my grid tables I always have edit/view icon or both in the row cell to open new page, then seemed I don't need "Actions" column title since I disable sorting anyway and wanted to replace with column visibility. That toolbar just takes too much space.

<img width="809" alt="screen shot 2018-03-20 at 15 27 31" src="https://user-images.githubusercontent.com/8721800/37664725-ca895da8-2c53-11e8-9078-9f0f99d188b9.png">

**Comment by ekaasatish** [comment]
Hello @SergeyAlexeev ,

Thank you 

I will have a look at it
