### ISSUE TITLE
[Question] How to column-resize nested details tables, or disable resize with manual column widths

### ISSUE THREAD

**Issue by thehig** [DevExpress/devextreme-reactive#840]
I've been working on creating a set of nested details tables (#780). I have had some success although I have reached an impasse. I am trying to manually define the widths of the columns in my table to try and make better use of my available space (similar to #808).

I've configured my code to use the 'TableColumnResizing' plugin if 'columnWidths' are specified. This allows me to specify the width of the columns manually which essentially achieves my goal. 

The column headers now have resize-handles, resize correctly, and correctly pass the resized column proportions down to the nested tables so that the columns all line up.

However, during resizing:

* the inner table does not 'draft' inline with the outer table. I have tried to bind one of the draft functions to the other with no success
* the inner table does not maintain the expanded columns due to react redrawing with the new props.

If I could fix these issues, I would leave the resize handlers enabled. Although if I could disable/remove those resize handles (which I think would be easiest) I would be equally happy to have a grid with manually defined, static column widths.

I hope this is enough information, and I apologise for the amount of code in my sample, it is compiled from multiple files & fixes

Code sample: https://codesandbox.io/s/rrvyxp46nn

Edit:

I've also been trying to style the scrollbars that arise, however I can't seem to find a way to access the TableContainer css/jss that is setting the CSS "overflow" property to disable it. Perhaps someone could point me in the right direction?

This is a great library, but styling parts of it has been a real headscratcher.

**Comment by kvet** [comment]
Hi,

Thank you for reaching out to us. Your feedback is greatly appreciated.

About static column sizing. There is a way to set a column size statically. See the following example: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/#uncontrolled-mode. It uses the Table.ColumnExtensions interface that is documented here: https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumnextension

We also have the issue with styling table parts. Here it is: https://github.com/DevExpress/devextreme-reactive/issues/627. It is implemented and will be released soon. Now you can try it in beta. We've added the tableContainer component to the Table plugin which renders a scrollable table container. Here are the docs: https://devexpress.github.io/devextreme-reactive/@next/react/grid/docs/reference/table/#properties

**Comment by thehig** [comment]
Thank you very much for the reply! I went down a completely wrong path replacing the TableComponent and was about to follow up when I noticed that while you refer to 'tableContainer', it's actually referred to in the docs as 'containerComponent'. I managed to get it to work, as demonstrated here: https://codesandbox.io/s/k3qrrj43qv (specifically the 'PatchedTableContainer')
