### ISSUE TITLE
Editable VirtualTable [Question]

### ISSUE THREAD

**Issue by afeldman1** [DevExpress/devextreme-reactive#842]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

Is there anyway to have editable cells and Column Reordering with a virtualTable not a normal table?

**Comment by gsobolev** [comment]
Hi @afeldman1,
 
The editing and column reordering features are supported both for the normal and virtual table. The usage is absolutely the same. Just import and use the `VirtualTable` plugin instead of the `Table` one.
