### ISSUE TITLE
Slow column resizes and reordering

### ISSUE THREAD

**Issue by ANTVirGEO** [DevExpress/devextreme-reactive#843]
Good day!

Start using grid with [column resizing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/)

And on 5-10 row it fast enough, but I have table with 10-20-30 rows (can't using pagination) and it start resizing very slow for user experience. [For example](https://codesandbox.io/s/rljmjplonq)

What I'm doing wrong? Or I must using virtual scrolling for this? (but still in one windows it will be 15-20 rows) 

### Your Environment

browser: Chrome 65
   "@devexpress/dx-core": "^1.1.0-beta.3",
    "@devexpress/dx-grid-core": "^1.1.0-beta.3",
    "@devexpress/dx-react-core": "^1.1.0-beta.3",
    "@devexpress/dx-react-grid": "^1.1.0-beta.3",
    "@devexpress/dx-react-grid-material-ui": "^1.1.0-beta.3",
    "material-ui": "^1.0.0-beta.37",
    "material-ui-icons": "^1.0.0-beta.36",

**Comment by kvet** [comment]
Hi,

Thank you for reaching out to us. The resizing and reordering features in development mode are slow. When building a production app, their performance increase.

However, there are several ways in which to improve performance dramatically. For example, by using a line indicating the next column size/position. So, I will leave the issue as an enhancement.

**Comment by SergeyAlexeev** [comment]
Hi,

We've just released Rect Grid [v1.2.0-beta.1](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#1.2.0-beta.1). This release contains column resizing improvements. Well, you can check it out and give us your feedback if any.

You can install it with the `next` tag:

```npm i --save @devexpress/dx-react-core@next @devexpress/dx-react-grid@next```
```npm i --save @devexpress/dx-react-grid-material-ui@next```
