### ISSUE TITLE
TableEditColumn`s commandComponent doesn't receives 'edit' id

### ISSUE THREAD

**Issue by IlyaSovenko** [DevExpress/devextreme-reactive#846]
I'm trying to update @devexpress lib on my project. Earlier I has a version 1.0.0-beta.2. I have an a table with my custom edit mod and add row. The problem is that my commandComponent don`t receives id 'edit' and that`s why i can't enter edit mod. I still can enter add mod, but not edit. Any ideas? 

devextreme-reactive: 1.0.3

**Comment by gsobolev** [comment]
Hi @IlyaSovenko,

Currently, it is not clear what the problem is. Could you please provide a code sample demonstrating it?

**Comment by IlyaSovenko** [comment]
problem is already solve in new version, thank you)

**Comment by gsobolev** [comment]
I'm closing the issue since the problem is already resolved. Feel free to reopen it if you need any assistance regarding it.
