### ISSUE TITLE
slow performance on updates

### ISSUE THREAD

**Issue by RahavLussato** [DevExpress/devextreme-reactive#849]
hi, im using your product and i'm facing performance issues.
i have a grid with virtual scrolling thats holds 50 rows and each row have 30 columns.

when the grid get update on one row, its rendering all the rows instead of render just the updated row.
is there any way to control when to update each row ? 

i tried to use VirtualTable's rowComponent with `shouldComponentUpdate` but its seems like its unmount and mount each row on each update instead of updating the existing row component and using the react life cycle. 

i also tried [this approach](https://github.com/DevExpress/devextreme-reactive/issues/496) which makes `shouldComponentUpdate` work but its even slower.

**Comment by RahavLussato** [comment]
here is a [snippet](https://stackblitz.com/edit/react-ddq9ft?file=index.js) to demonstrate the issue.
you can see that even that only row of index 1 is updated all the visible rows are mounting on each update.

on the snippet above its runs nice but imagine what will happen when you have more columns with complex objects under it (e.g. react nodes that preforms logic).

another point to check is that the browser is complaining on Violation.

**Comment by up209d** [comment]
Because you were trying to use inline Components which is returned as a new instance Component for every render. That s why all of your table rows & cells get updated in every render.
```
rowComponent={(props)=>_renderRow('myCustomClass', Object.assign({},props))}
cellComponent={(props)=>_createCustomElement(VirtualTable.Cell, 'myCustomClass', props)}
```

Don't do that unless you have no choice, rather do

```
const RowComponent = (props)=>_renderRow('myCustomClass', Object.assign({},props));
const CellComponent = (props)=>_createCustomElement(VirtualTable.Cell, 'myCustomClass', props);

...

rowComponent={RowComponent}
cellComponent={CellComponent}

```

https://stackblitz.com/edit/react-ytqzc5

P/S: For browser complaining: `Grid rows={data.ids} ` data.ids need to be an object, you can do an object array [{id: 0},{id: 1}, ...] instead of number [0,1,...] then change the `getCellValue` to `data.byId[row.id][columnName]`

**Comment by RahavLussato** [comment]
thanks @up209d it helped now it not mounting over and over again, but still the table is stuck for something like 2 sec on each update i'll try to make an example that will reproduce that and post it here.

**Comment by RahavLussato** [comment]
thanks for the help, the other issue was on my side.

**Comment by gwmaster** [comment]
help fix common problem [example](https://codesandbox.io/s/p9z6200wzj)
all rows rendered again and Smile PopUp Change closed
![image](https://user-images.githubusercontent.com/5362853/45801106-89b44880-bcbb-11e8-8f33-452a615232c1.png)
