### ISSUE TITLE
Sorting icon

### ISSUE THREAD

**Issue by IlyaSovenko** [DevExpress/devextreme-reactive#850]
Hello! Is there any way to change the sort icon?

devextreme-reactive: 1.1.0

**Comment by SergeyAlexeev** [comment]
Hi,

Recently we have answered a [question](https://github.com/DevExpress/devextreme-reactive/issues/839#issuecomment-373716972) that similar to yours. There is an [example](https://codesandbox.io/s/4qm8997vox) that demonstrates how to create a custom table header cell with a sorting control. You can go the same way to implement your scenario.

**Comment by IlyaSovenko** [comment]
Thank you)
