### ISSUE TITLE
slow scrolling with big amount of columns

### ISSUE THREAD

**Issue by RahavLussato** [DevExpress/devextreme-reactive#851]
hi, when i have bigger amount of columns then your [demo](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/) the scrolling is moving very slow.
[here](https://stackblitz.com/edit/slow-scroll?file=index.js) you can see that.
is there any way to achieve better performance on this case ?
what about render only the visible columns ?

**Comment by RahavLussato** [comment]
@kvet look at this example of react-virtualized that using virtualization along the vertical and horizontal axes.

**Comment by kvet** [comment]
Hi,

Please read the following answer: https://github.com/DevExpress/devextreme-reactive/issues/736#issuecomment-364159101

I've created a separate issue with column virtualization feature request: https://github.com/DevExpress/devextreme-reactive/issues/853

**Comment by RahavLussato** [comment]
Hi @kvet thanks for the fast response.
i saw your's answer on #736 and i can say that this is exactly our use case (grid with huge amount on columns) and it will be awesome to have horizontal virtualization.
currently after long playing with the reactive grid its the only blocker that we have from starting using it massively on our production.

**Comment by kvet** [comment]
I understand your concerns. Though I can't guarantee that column virtualization will be implemented soon, I should say that this feature has high priority.
