### ISSUE TITLE
Table cell decorator

### ISSUE THREAD

**Issue by IlyaSovenko** [DevExpress/devextreme-reactive#867]
Is there some way to wrap a cell in the component I need? If yes - where can I see an example?

devextreme-reactive: 1.1.0

**Comment by gsobolev** [comment]
Hi,
 
You can define a custom cell component via the `cellComponent` property of the `Table` plugin. Please refer to the [Appearance Customization](http://localhost:4000/devextreme-reactive/react/grid/docs/guides/fundamentals/#appearance-customization) guide to see the `cellComponent` example.

**Comment by IlyaSovenko** [comment]
Thank you)
