### ISSUE TITLE
Question: Column visibility and edit mode

### ISSUE THREAD

**Issue by rpkRED** [DevExpress/devextreme-reactive#879]
Hi, i have case where one column needs to be hidden from user perspective but when clicked on edit existing row or adding new one it should call api and fill in it's value even tho it should remain hidden. With TableColumnVisibility plugin I am able to hide it but that is all. Is this bug or that kind functionality is not even possible?

devextreme-reactive: 1.0.3
react: 16.2.0
browser: chrome
material-ui: 1.0.0-beta.35

**Comment by kvet** [comment]
Hi,

Any custom logic can be implemented outside the Grid. It is possible to set a default value when creating a row. Here is the example: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode

If you are talking about dependent columns, here is a link to the original issue: https://github.com/DevExpress/devextreme-reactive/issues/283

**Comment by rpkRED** [comment]
Hi, thank you for taking your time to help me. I have read your links and I'm not sure if that is solution to my problem, correct me if I'm wrong. I have issue with hidden columns that value is not stored in rows when it's hidden with  TableColumnVisibility plugin. And I set that value when i'm in edit or add mode of row. For example I have column that is TextField component with react lifecycle methods and in componentDidMount I call api when adding new row or editing to get and set value of that TextField. If i hide it initially  with TableColumnVisibility  plugin, lifecyle method is not called?

**Comment by kvet** [comment]
The Grid doesn't render invisible columns. So, the life cycle hooks are not called for hidden cells.

Such logic should be implemented in a state management library (e.g., redux) instead of the visualization library (react).
