### ISSUE TITLE
Question: copy row command button

### ISSUE THREAD

**Issue by rpkRED** [DevExpress/devextreme-reactive#880]
Hi, is it possible to add custom command button that will create new row with copied data from specific columns from row that is clicked on?

devextreme-reactive: 1.0.3
react: 16.2.0
browser: chrome
material-ui: 1.0.0-beta.35

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your interest in our product. Follow this [example](https://codesandbox.io/s/w03m40r177) to implement this feature.
