### ISSUE TITLE
Enhancement for VirtualTable to call handler to load more data

### ISSUE THREAD

**Issue by msteinmn** [DevExpress/devextreme-reactive#882]
There are solutions to implement a lazy loader external from VirtualTable, but everything I tried so far turns out to be unreliable and a hack. I ended up implementing a button for the user to load more data manually. The issue is that loading more data needs to work reliably independent of features such as sort, filter, and now search. 

I would wish VirtualTable offered a handler that is called when the user scrolls near the bottom of the current view.

**Comment by kvet** [comment]
Hi,
 
I've updated the example from the #501 issue. It works with integrated data processing plugins. Here it is: https://stackblitz.com/edit/react-igmnr9?file=index.js
