### ISSUE TITLE
Setting pagination page to 0 manually

### ISSUE THREAD

**Issue by tariqzafa700** [DevExpress/devextreme-reactive#884]
Hi,
I am using devextreme's paging plugins. My scenario is as given below:
I am using remote pagination and getting requests served by Elastic search apis. My steps are:
1. Conduct a search for a keyword and initially pageSize is set to 100 and currentPage as 0.
2. I move to another page for instance currentPage 2 ie 3 in PagingPanel.
3. I want to conduct a new search and want the first page to be shown again for that keyword.
4. I set currentPage to 0 through react state but it doesn't reflect on the PagingPanel.
5. If I manually set the currentPage to some other value other than 0 then on reset I can see PagingPanel focus shifting to that particular page.

```
               <PagingState
                  currentPage={config.customPagination.currentPage} // if this is 0 the PagingPanel doesnt reach 0 page
                  onCurrentPageChange={this.changeCurrentPage}
                  pageSize={config.customPagination.pageSize}
                  onPageSizeChange={this.pageSizeChanged}
                />
                <CustomPaging totalCount={config.customPagination.totalCount} />


```
Let me know if you need any more details.
Thanks
Tariq

**Comment by kvet** [comment]
Hi,

I am afraid that I couldn't reproduce the issue. I've prepared an example and it works well. Here it is: https://codesandbox.io/s/91o7vpnvmy

Note that the example is built using version 1.1.1. If you are using an older build, I recommend updating to the newest version.

**Comment by tariqzafa700** [comment]
Hi,
I think its because of version. We have been using "1.0.0-beta.3". In your example I changed it to this version and I can see the same issue. Hopefully we should change the version and it should go.

Thanks 
Tariq
