### ISSUE TITLE
[Question] Getting the row order information

### ISSUE THREAD

**Issue by kabial** [DevExpress/devextreme-reactive#885]
Hi. Is there a way to get the order of a row? I would like to access this information from the custom cell component. Cell component receives the tableRow prop, but order information is not present.

I build the tabIndex based on the row number, for a proper navigation between selectable elements, like this:
TAB->focus row edit button->TAB-> focus next row edit button->ENTER->TAB-> navigate between row edit fields and action buttons

Maybe there is a different solution.

**Comment by SergeyAlexeev** [comment]
Hi,

In your case, you can specify `rowId` based on a row index. Use the Grid's `getRowId` property as follows:

```js
getRowId(row) {
  return this.state.rows.indexOf(row);
}
```

Then you will be able to get a row index inside a custom cell component:

```js
const Cell = (props) => {
  console.log(props.tableRow.rowId);
  return <Table.Cell {...props} />;
}
```

This [sample](https://codesandbox.io/s/vn339xkl9l) shows the described approach in action.

**Comment by kabial** [comment]
Thanks for your answer. I have sorting enabled as well. Unfortunately, this will not work when rows are rearranged.
I might sort the data on my own to get the index, but I looked for a built-in solution. Maybe this could be added?

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information. This [sample](https://codesandbox.io/s/qxxv9545nq) shows how to implement your scenario.

Please refer to the [React Core](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/) documentation for more details.

**Comment by kabial** [comment]
Hi. It works based on the provided sample.

I have been not familiar with React Core plugins before, but I see they are quite powerful.

Many thanks!
