### ISSUE TITLE
[Question] Header cell`s tooltip

### ISSUE THREAD

**Issue by IlyaSovenko** [DevExpress/devextreme-reactive#886]
Hi! I have a table with sorting, and I want to change tooltip text on the header cell

### Current Behaviour
when hovering over a cell, the tooltip show 'Sort'

### Expected Behaviour
I need to show a value of column titlle

### Your Environment
devextreme-reactive: 1.1.1

**Comment by SergeyAlexeev** [comment]
Hi,
 
Use the `messages` property of the [TableHeaderRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/) plugin:

```js
<TableHeaderRow
  // ...
  messages={{
    'sortingHint': 'your message...'
  }}
/>
```
 
Please refer to the [Localization](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/localization/) guide to get more information about other plugins' customization.

**Comment by IlyaSovenko** [comment]
Ok, but my message should be different for every header cell,how can I pass there title of column?

**Comment by IlyaSovenko** [comment]
I try to use another tooltip as same as I do with table body cell 
`<TableView.Cell {...props} >
      <Tooltip
        classes={{ tooltip: props.classes.tooltip, popper: props.classes.popper }}
        id="tooltip-bottom-end"
        placement="left-end"
        title={props.value}
      >
        <span>
          {props.value}
        </span>
      </Tooltip>
    </TableView.Cell>`
But i don't see my tooltib

**Comment by SergeyAlexeev** [comment]
Thank you for the clarification!
 
To implement the functionality you described, use a custom cell component for the `TableHeaderRow` plugin as follows:
```js
const Cell = ({ getMessage, column, ...restProps }) => (
  <TableHeaderRow.Cell
    column={column}
    getMessage={() => `Sort by ${column.name}`}
    {...restProps}
  />
);
```
See this [example](https://codesandbox.io/s/o9nzp7nk29) as well.

**Comment by IlyaSovenko** [comment]
Ничёси) Thank you a lot)
