### ISSUE TITLE
[Typescript bug] Inconsistent props type of noDataCellComponent under <Table /> and <Table.NoDataCell /> 

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#898]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
![image](https://user-images.githubusercontent.com/1334982/38475684-975d4b96-3b5e-11e8-9097-c70bb01a53fe.png)

### Expected Behaviour
No errors.

### Steps to Reproduce (for Bugs)

Please take a look at the screen shot.

### Proposed fix:
1. Change the props type of `Table.NoDataCell` to `TableBase.NoDataCellProps`
2. `NoDataCellProps` interface should extend `TableBase.CellProps`, just like what `TableBase.DataCellProps` interface does.
![image](https://user-images.githubusercontent.com/1334982/38476094-e9ef8962-3b60-11e8-9d16-8c44420a989c.png)

### Your Environment

devextreme-reactive: 1.1.1
react: 16.2.0
browser: Chrome
material-ui: yes

**Comment by franklixuefei** [comment]
Thanks @gsobolev ! Commented on your CR. I think we need one more change.

**Comment by gsobolev** [comment]
Hi!

The fix is available in the 1.1.2 release.
