### ISSUE TITLE
[Feature Request] Ability to hide a column filter (in addition to just disabling the filter)

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#915]
Hi,

I have a feature request - **add ability to hide a column filter in addition to just disabling it.**
According to [this documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/filtering-state/#filteringstatecolumnextension), disabling a column filter is supported, but in my case, I want to go an extra step to hide a column filter, because in my project, I have a column called "Actions", and there are some action buttons, like showing details, etc, in the cells of that column. Even if I can disable the filtering for that column, it would be really nice that I can just hide it, rather than showing a disabled filter. Visually, hiding the disabled filter in my case will be much better. So, if possible, an extra prop in `FilteringState.ColumnExtension` interface, like `filteringVisible: boolean;`, would be nice.

devextreme-reactive: 1.1.1
react: 16.2.0
browser: Chrome/Edge
material-ui: yes

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you for sharing your idea! Currently, you can implement the described functionality by using a custom template for a filter cell.

```js
const Cell = (props) => {
  if (props.column.name === 'name') {
    return <TableFilterRow.Cell {...props}>
    &nbsp;
    </TableFilterRow.Cell> 
  }
  return (<TableFilterRow.Cell {...props} />);
};
<Grid>
  <TableFilterRow cellComponent={Cell} />
</Grid>
```

This [demo](https://codesandbox.io/s/4p74507q4) shows it in action.

Moreover, I'd point one more solution. It's based on using the [DataTypeProvider](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/data-type-provider/) plugin. It can be more convenient in your case. Please refer to this [sample](https://codesandbox.io/s/ykrwq3x3v1) to see how this approach works.

**Comment by franklixuefei** [comment]
@SergeyAlexeev Thanks a lot for your decent solutions! Solved my problem!
