### ISSUE TITLE
How to get filtered row count

### ISSUE THREAD

**Issue by EsaNuurtamo** [DevExpress/devextreme-reactive#916]
Hi,

How do I get row count of filtered items? 
In documents i found that IntegratedFiltering has getter 'rows' but how can i access it?

**Comment by SergeyAlexeev** [comment]
Hi, 

Would you please clarify your use case? The getter you pointed is helpful for plugin development and available in the [TemplateConnector](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/template-connector/) component, for instance.

**Comment by SergeyAlexeev** [comment]
FYI: the similar question is discussed [here](https://www.devexpress.com/Support/Center/Question/Details/T625441/can-you-provide-a-sample-for-getting-filtered-rows-from-react-grid).

**Comment by pbalzano91** [comment]
Using the TemplateConnector, how can you set an internal state? Use case: display  number of filtered rows outside table

**Comment by SergeyAlexeev** [comment]
This [sample](https://codesandbox.io/s/kk303l8k13) demonstrates how to show a row count. Here I created the `TableRowCounter` plugin that implements the described functionality.

**Comment by pbalzano91** [comment]
That was exactly what I was looking for. I could wrap my Toolbar plugin and manage that state. Thank you!

**Comment by zguillen** [comment]
Thank you @SergeyAlexeev !!
