### ISSUE TITLE
Use drag'n'drop for grouping

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/devextreme-reactive#92]
Add the capability to group/ungroup rows by dragging and dropping a column header from/to the Grid group panel (similar to [this demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Data_Grid/RecordGrouping/jQuery/Light/)).

**Comment by kvet** [comment]
Implemented in [1.0.0-alpha.6](https://github.com/DevExpress/devextreme-reactive/releases/tag/v1.0.0-alpha.6)
