### ISSUE TITLE
Delete all

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#920]
How would I go about implementing a Delete All button?

I can use the Selection functionality to select all the rows I want to delete - that's fine.

I would like to add the Delete All button next to the New button - if that seems like a good place?
Is there an easy way to add this extra button to the TableEditColumn for the header? How would I go about it?

Or is there an easier way?

**Comment by SergeyAlexeev** [comment]
Hi,

To add a custom button to the table edit column, use the `headerCellComponent` property of the `TableEditColumn` plugin. Please, refer to this [sample](https://codesandbox.io/s/64q0qp4653).

**Comment by joergd** [comment]
Ok thank you - that sample works well!
