### ISSUE TITLE
Grid no longer auto-fills width of page

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#921]
Hey guys,

I just upgraded from the Bootstrap3 version of the dx grid to the Bootstrap4 version and I have some new behaviour that is undesired:

The tables no longer auto-fill the width of the page but only wrap the content as narrowly as possible. I have width set to 100% etc but it doesn't seem to make a difference.

I also updated the version of the dx-grid-core so it could be something in there but, any ideas what is causing this and how to remedy it?

**Comment by SergeyAlexeev** [comment]
Hi,

Thank you to bringing this to our attention. I tried to reproduce the behavior you described but it all operates fine.

Both grids([Bootstrap4](https://rymyjlonpq.codesandbox.io/) and [Bootstrap3](https://7o46mkowx.codesandbox.io/)) work identically, i.e. take all the available page width.
