### ISSUE TITLE
[Typescript] `style` prop should have `React.CSSProperties` rather than `object`

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#922]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
The type of `style` prop under several Typescript `interface`s are marked as `object`

### Expected Behaviour

They should be marked as `React.CSSProperties` for proper type inference and autocompletion.

### Your Environment

devextreme-reactive: 1.1.2
react: 16.2.0
material-ui: yes

**Comment by gsobolev** [comment]
@franklixuefei,

Thank you for your suggestion. We will consider it as the future improvement of TypeScript definitions.
