### ISSUE TITLE
Latest material-ui (1.1.2) release error on install

### ISSUE THREAD

**Issue by andrispraulitis** [DevExpress/devextreme-reactive#927]
Bug?

Getting error on react-grid-material-ui 1.1.2
npm ERR! code E404
npm ERR! 404 Not Found: @devexpress/dx-react-material-ui@latest

**Comment by SergeyAlexeev** [comment]
Hi,

I can't reproduce the issue. I suppose the problem is here `npm ERR! 404 Not Found: @devexpress/dx-react-material-ui@latest`. We don't provide the `dx-react-material-ui` package. I think, it should be `dx-react-grid-material-ui`.

**Comment by andrispraulitis** [comment]
Oops.. sorry my bad.
