### ISSUE TITLE
Inline cell editing 

### ISSUE THREAD

**Issue by GuyWithCookies** [DevExpress/devextreme-reactive#931]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Edit Cells by Using TableEditRows

### Expected Behaviour
Do you plan a feature to edit single Cells of a controlled table when the user clicks on it?
Or maybe there already is a Plugin/Possibility which I am not aware of ?

### Your Environment

devextreme-reactive: 1.1.2
react: 16.3.1
browser: Google Chrome Version 65.0.3325.181
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.41

Thank you in advance!
Great Library!

**Comment by MaximKudriavtsev** [comment]
Hi,

Thank you for your suggestion and feedback. We will consider it as the future improvement with low priority because we don't have so many requests for this feature.

**Comment by hukuuu** [comment]
Hi there +1 on the feature. Also can you guys suggest how we should implement this in the current version? I am thinking of a custom cellComponent in the Table component which will handle the inline editing. Though I am not sure how to invoke the onCommitChanges action.

**Comment by changsheng1239** [comment]
+1 
Is there any future plan on this amazing feature? Or is there any possible alternative way to implement this feature.

**Comment by songlim327** [comment]
+1 for this awesome feature as it provides alternative for editing.

**Comment by Nusinka** [comment]
+1

**Comment by KaiWynn** [comment]
+1

**Comment by vantsymbalenko** [comment]
+1

**Comment by Butzman** [comment]
+1

**Comment by susuwatari2** [comment]
Hi, this is a awesome feature!! Is there any updates? Or can you show us how to implement in the current version? I was thinking like DataTypeProvider too.

**Comment by conny-nyman** [comment]
+1

**Comment by raghureddys** [comment]
+1

**Comment by VoiToi** [comment]
+1. Batch editing is much more user friendly when you want to change more data. Is this really still low priority because hou don't have so many requests for this feature?

**Comment by davecyen** [comment]
+1

**Comment by LvWentao** [comment]
Is there any update on this feature?

**Comment by MaximKudriavtsev** [comment]
Hi @LvWentao,

This feature is in our plans. We are going to implement it in the near future.

**Comment by LazyLahtak** [comment]
Hi all,
We started to implement this feature. Please, follow this [topic](https://github.com/DevExpress/devextreme-reactive/issues/2284) to be informed about our updates. We would also appreciate your feedback on this feature. You can provide it in the same topic.

**Comment by LazyLahtak** [comment]
Hi

We're happy to announce a new TableInlineCellEditing plugin for inline cell editing. Refer to our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/) to explore its functionality.
Also, we have added new demos about this feature: [React Grid - Inline Cell Editing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#inline-cell-editing).
