### ISSUE TITLE
Connect Search State Plugin  and Search Panel from two different Components

### ISSUE THREAD

**Issue by sanjayagnani92** [DevExpress/devextreme-reactive#932]
I am looking for connecting SearchPanel Plugin to dx-grid plugin from another component and changing it's style.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,

I'm afraid I don't understand your question. Would you please describe your use case in greater detail?

**Comment by sanjayagnani92** [comment]
Hi, am looking for  customizing the layout and moving Search Panel defined in Toolbar of DxGrid component to Header Component (custom Component layout)(Ex: https://codesandbox.io/s/xrq9xpj65q) , 
Can we achieve similar thing as it follows DxGrid follows data piping principle can similar things be achieved or how can we customize the DxGrid layout
