### ISSUE TITLE
Nitpick: Row Detail chevron should be Up/Down, not Right/Down

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#942]
- [ x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
Current Row Detail Chevron icons are ChevronRight for non expanded rows and ChevronDown for expanded rows

### Expected Behaviour

According to Material, the icon for non expanded content should be ChevronDown and expanded content should be ChevronUp

See - [Card Content Blocks](https://material.io/guidelines/components/cards.html#cards-content-blocks)
[Expansion Panels](https://material.io/guidelines/components/expansion-panels.html)

Please let me know if there's a reason you went with the current choice (or if there's any easy way to configure it for myself). Sorry for the nitpicking but it got brought up in a design meeting today :)

**Comment by MaximKudriavtsev** [comment]
Hi,
 
Thank you for your suggestion and feedback. You are right! We are going to update the icon with the next release.
In the meantime, you can use a custom `TableDetailToggleCell` component to fix the issue. See the [demo](https://stackblitz.com/edit/react-qywk8w?file=index.js).

**Comment by manuelnas** [comment]
This is not resolved since as @stclairdaniel mentioned ChevronDown should be shown when the detail view is collapsed, and ChevronUp should be shown when the detail view is expanded. Currently (as of 1.2.0) this is reversed.

[Material spec, scroll to Expand/collapse](https://material.io/guidelines/components/lists-controls.html)
