### ISSUE TITLE
Disable editing of a particular column only while editing a row and not while adding one

### ISSUE THREAD

**Issue by glenpadua** [DevExpress/devextreme-reactive#953]
I understand that editing of a column can be disabled using the `columnExtensions` property of the `EditingState` plugin. But that also disables the column when entering new values.

Is it possible to have column editing disabled only while rows are being edited and not when they are added?

Thanks.

**Comment by glenpadua** [comment]
Perfect! Just what I needed.

**Comment by Velociapcior** [comment]
and how will it work with custom DataTypeProvider? Beacuse I've tried to implement your sample into already working DataTypeProvider and it seems not to catch the editingEnabled set in this TableEditRow.Cell

**Comment by xZliman** [comment]
@MaximKudriavtsev Can this work with a custom DataTypeProvider?

**Comment by MaximKudriavtsev** [comment]
Hi @Velociapcior, @xZliman,

Currently, this case is not available. We will discuss how to implement it in the future.
