### ISSUE TITLE
How can we implement and execute a custom sorting algorithm by default on PageLoad

### ISSUE THREAD

**Issue by filipveschool** [DevExpress/devextreme-reactive#954]
Hi,

I have successfully implemented my custom sorting algorithm.

Now is my question how we can enable that algorithm by default when page is loaded and data is filled in.

For now, we have to press the sort button to actually use the algoritm to sort the values, but I want this to happen automatically.

Is this possible? and if yes, how?

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Your Environment

devextreme-reactive: xxx
react: xxx
browser: xxx
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by kvet** [comment]
Hi,

I've prepared an example demonstrating how to use a custom sorting algorithm instead of the default one: https://codesandbox.io/s/03xl3ol51w
