### ISSUE TITLE
Getters in Plugin are never computed

### ISSUE THREAD

**Issue by Zatine** [DevExpress/devextreme-reactive#967]
I am trying to extend the Table component by writing a plugin that allows any column to show a detail state. I started out by trying to simply copy the 1.0.1 implementation of `TableRowDetail`, to take it from there.

I have gotten to the point of the toggle button rendering in any correctly defined cell, and it toggles between expanded and closed correctly. However, I cannot get the detail state to show up. While trying to debug, I noticed that the `computed` functions in my `Getter`s are never called, thus never setting any of the rows type to `detail`, which I think is part of the issue. I have tried but I can't figure out why.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Steps to Reproduce (for Bugs)
https://codesandbox.io/s/zw6qnl12q3

### Your Environment
devextreme-reactive: 1.0.1
react: 16.2.0
browser: Chrome Version 65.0.3325.146
material-ui: 1.0.0-beta.31

**Comment by kvet** [comment]
Hi,

The `tableColumn` and `tableRow` getters you are trying to extend don't exist. According to our documentation, they are called `tableColumns` and `tableBodyRows`. Here is an updated example: https://codesandbox.io/s/o7kmvqj1z5.

**Comment by Zatine** [comment]
Ah, thank you! And I was staring at that for _so_ long without seeing it. Closing!
