### ISSUE TITLE
[Typescript] Type definition missing for `dx-grid-core`

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#970]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour

Currently I'm trying to write myself a plugin, but it seems that `@devexpress/dx-grid-core` does not have any type definitions.

### Expected Behaviour
There is a type definition file for `@devexpress/dx-grid-core`

### Context
I'm using Typescript, and I wanted to leverage the `getMessagesFormatter` from `@devexpress/dx-grid-core`, just like the built-in plugins you wrote.

### Environment
devextreme-reactive: 1.2.0-beta2

**Comment by kvet** [comment]
Hi,

The `@devexpress/dx-grid-core` package is not public. We do not plan to provide TypeScript definitions for it. I should also warn you about a possibility of changing a certain part of this package without notification.
