### ISSUE TITLE
Is the React Grid "Free"

### ISSUE THREAD

**Issue by Vaccano** [DevExpress/devextreme-reactive#985]
I can't seem to find any information on if the React grid from DevExpress is free or for pay.  

Is there any info about this?  I heard a .NET Rocks ad about the grid, and I got the feeling from the add that it was "Freemium" (meaning that full features would require payment).

I am fine to pay, I just need to budget for it.  **Is this a free tool?  Is it going to remain free for the next year an a half?**

**Comment by dyangua** [comment]
@Vaccano if you want a free option use react table
