### ISSUE TITLE
Data service source code

### ISSUE THREAD

**Issue by drinkwater99** [DevExpress/devextreme-reactive#99]
I think it would be a good idea to show the source code for web service used in the Remote Data sample https://js.devexpress.com/Demos/WidgetsGallery/data/orderItems

**Comment by dxbykov** [comment]
Hi,

There is no any server-side specificity related to using the mentioned Data Service with our React Grid. Depending on the server-side technology you are going to use in your app, you can implement a corresponding web service. For instance, if you are going to use ASP.Net MVC and Entity Framework, you can follow [these guides](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/). You'll find how to implement CRUD operations, sorting, filtering, paging, etc.
