### ISSUE TITLE
Set Column Min Width for Resizing

### ISSUE THREAD

**Issue by brunodahora** [DevExpress/devextreme-reactive#995]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Question

Hi guys, is there any way to set the min width of a column, during resizing?

### Your Environment

devextreme-reactive: 1.1.2
react: 0.16.3
browser: chrome 66.0.3359.117
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by brunodahora** [comment]
Hi I saw this property, tried to set it but it didn't make any difference!

Do you believe there is any way to implement this?
Can I block resize in some condition?

**Comment by jbuschke** [comment]
I would also need a more flexible way to set column widths. Typical css features like min, max, percentage and fr value types would be nice

**Comment by kvet** [comment]
@brunodahora,

Here is the working sample:
```
<TableColumnResizing
minColumnWidth={100}
/>
```

It allows setting minimal column width for all columns.

I am afraid that the implementation of minimal column width on your side may require a full rewrite of the TableColumnResizing plugin.

Also, there is no way to block resize in some cases. You can only remove the TableColumnResizing plugin if you don't need resizing.

@jbuschke,

Thank you for your suggestion. We have a dedicated issue for column width specification in percentages: #795.
