### ISSUE TITLE
How to make VirtualTable + Toolbar fill available height?

### ISSUE THREAD

**Issue by gabrielmdeal** [DevExpress/devextreme-reactive#996]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Question
Is there a clean way to make the `Grid` fill all available height when using a `VirtualTable` *with* a `Toolbar`?  Or is it a bug that the `height` prop on `VirtualTable` does not take the `Toolbar`'s height into account?

Per #697, I am using `AutoSizer` to get the available height so I can pass it to `VirtualTable`.  But to make the `Grid` exactly fill the available height, I have to subtract the `Toolbar`'s height from the available height before passing it into the `VirtualTable` (see code snippet below).  This seems like a hack to me.

```JSX
<Grid columns={this.state.columns} rows={this.state.rows}>
  <AutoSizer disableWidth>
    {({ height }) => (
      <VirtualTable
        height={height - this.getToolbarHeight()}
        rowComponent={this.tableRowComponent}
      />
    )}
  </AutoSizer>

  <Toolbar
    rootComponent={(props) => (
      <div className="my-toolbar-wrapper">
        <Toolbar.Root {...props} />
      </div>
    )}
  />
</Grid>

getToolbarHeight() {
  const domNode = ReactDOM.findDOMNode(this);
  const toolbarDomNode = domNode.querySelector('.my-toolbar-wrapper');
  return toolbarDomNode.getBoundingClientRect().height;
}
```

### Your Environment

devextreme-reactive: 1.1.1
react: 16.2.0
browser: Chrome 66.0.3359.117 (Ubuntu)
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.38

**Comment by kvet** [comment]
Hi,

I am afraid that there is no other way to set the whole component height. We will think about improving this in future releases.

**Comment by gabrielmdeal** [comment]
Thank you for the quick response!

I will leave this issue open in case you want to use it to track the improvement.  Or feel free to resolve it since my question is answered.

**Comment by szahn** [comment]
Shouldn't CSS Flex Grid handle this? It should be as simple as setting the grid parent div to flex: 1 to fill the grid.
